### ISSUE TITLE
EKS cluster-autoscaler 1.3.0 downscaling after reaching minimum limit

### ISSUE THREAD

**Issue by josepplaltg** [kubernetes/autoscaler#1004]
We've detected the cluster-autoscaler 1.3.0 running on EKS cluster is not stopping the downscaling after reaching the mimimum asg size declared on the Deployment. 

`            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --nodes=4:10:eks-jenkins-workers-m5xlarge-NodeGroup-XXXXXXXXXX
            - --skip-nodes-with-system-pods=false
            - --scale-down-delay-after-add=5m
            - --scale-down-delay-after-delete=5m
            - --balance-similar-node-groups
`

We stopped the autoscaler at 2 instances in the ASG

**Comment by MaciekPytel** [comment]
Can you provide some logs from when it scaled-down to get below the limit?

**Comment by josepplaltg** [comment]
Sorry but I deleted the pod and the cluster, I'm going to deploy it again so I will be able to provide you the logs again, I'll attach asap

**Comment by tomfotherby** [comment]
I've been using v1.3.0 with EKS for 48 hours and so far so good - I didn't see the same issue that you had @josepplaltg .

**Comment by jstol** [comment]
I am also having a similar issue with my autoscaling groups completely scaling down past their minimum limits. Furthermore, this is actually happening during a scale-up, meaning first all my nodes are destroyed, and then a larger amount of nodes in each group is spun up to accommodate the load.

**Comment by arjanschaaf** [comment]
I'm running into this issue as well on Amazon EKS. I've 2 auto scaling groups connected to my EKS cluster, one of those asg's is configured to scale down / up between 1 and 10 nodes by the cluster-autoscaler. The underlying asg is configured to allow between 0 and 20 nodes. This setup work for me like a charm using a Kops based cluster, but is causing headaches after I switched to EKS.

Some loggings around the time the cluster scaled down to 0 nodes, where I expected 1 node to remain untouched because of the configuration for the autoscaler: 

```
    Command:
      ./cluster-autoscaler
      --cloud-provider=aws
      --namespace=kube-system
      --nodes=1:20:ci-eks-build-nodes
      --logtostderr=true
      --stderrthreshold=info
      --v=4
```

The logs:
```
I1112 13:01:41.283279       1 static_autoscaler.go:297] Calculating unneeded nodes
I1112 13:01:41.283290       1 utils.go:462] Skipping <host1-different-autoscalingroup> - no node group config
I1112 13:01:41.283297       1 utils.go:462] Skipping <host2-different-autoscalingroup> - no node group config
I1112 13:01:41.283302       1 utils.go:471] Skipping <host3-autoscalingroup-managed-by-autoscaler> - node group min size reached
I1112 13:01:41.283362       1 static_autoscaler.go:323] Scale down status: unneededOnly=false lastScaleUpTime=2018-11-12 12:28:56.07013176 +0000 UTC m=+5222.795360746 lastScaleDownDeleteTime=2018-11-12 13:01:10.917288555 +0000 UTC m=+7157.642517602 lastScaleDownFailTime=2018-11-12 11:02:10.988509979 +0000 UTC m=+17.713738966 scaleDownForbidden=false isDeleteInProgress=false
I1112 13:01:41.283380       1 static_autoscaler.go:329] Starting scale down
I1112 13:01:41.283407       1 scale_down.go:641] No candidates for scale down
I1112 13:01:42.843357       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I1112 13:01:44.853540       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I1112 13:01:46.864204       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I1112 13:01:48.884529       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I1112 13:01:50.898424       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I1112 13:01:51.295595       1 static_autoscaler.go:117] Starting main loop
I1112 13:01:51.295642       1 auto_scaling_groups.go:249] Regenerating instance to ASG map for ASGs: [ci-eks-build-nodes]
I1112 13:01:51.347940       1 auto_scaling_groups.go:101] Updating ASG ci-eks-build-nodes
I1112 13:01:51.347968       1 aws_manager.go:136] Refreshed ASG list, next refresh after 2018-11-12 13:02:01.347965246 +0000 UTC m=+7208.073194221
I1112 13:01:51.348043       1 static_autoscaler.go:152] 1 unregistered nodes present
I1112 13:01:51.348070       1 utils.go:514] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I1112 13:01:51.348078       1 static_autoscaler.go:236] Filtering out schedulables
I1112 13:01:51.348124       1 static_autoscaler.go:246] No schedulable pods
I1112 13:01:51.348135       1 static_autoscaler.go:250] No unschedulable pods
I1112 13:01:51.348144       1 static_autoscaler.go:297] Calculating unneeded nodes
I1112 13:01:51.348161       1 utils.go:462] Skipping <host1-different-autoscalingroup> - no node group config
I1112 13:01:51.348177       1 utils.go:462] Skipping <host2-different-autoscalingroup> - no node group config
I1112 13:01:51.348241       1 static_autoscaler.go:323] Scale down status: unneededOnly=false lastScaleUpTime=2018-11-12 12:28:56.07013176 +0000 UTC m=+5222.795360746 lastScaleDownDeleteTime=2018-11-12 13:01:10.917288555 +0000 UTC m=+7157.642517602 lastScaleDownFailTime=2018-11-12 11:02:10.988509979 +0000 UTC m=+17.713738966 scaleDownForbidden=false isDeleteInProgress=false
I1112 13:01:51.348259       1 static_autoscaler.go:329] Starting scale down
```

**Comment by bskiba** [comment]
@arjanschaaf which node group sis you observe that was scaled down? From the logs I don't see any scale down operation, maybe it happened earlier, since one of the node groups reported reaching minimal size:

> I1112 13:01:41.283302       1 utils.go:471] Skipping <host3-autoscalingroup-managed-by-autoscaler> - node group min size reached

**Comment by arjanschaaf** [comment]
@bskiba after first responding to this issue (I suspected EKS to be the cause of my problems) I did some further testing & finally created a new issue: https://github.com/kubernetes/autoscaler/issues/1398 Not sure if the situation @josepplaltg reported and my problems are the same. More extensive logs are in the new issue. It looks like a regression problem that started with newer versions that 1.2.2 (that version works for me, on EKS as well)

**Comment by aleksandra-malinowska** [comment]
Closing as duplicate of  #1398.
