### ISSUE TITLE
 Failed to create AWS Manager: NoCredentialProviders

### ISSUE THREAD

**Issue by maauso** [kubernetes/autoscaler#1015]
Hi guys, 

I'm trying to use autoscaler in EKS, I found an error when I want to update autoscaler yaml, for example  adding a new ASG o something like that

Steps to reproduce it: 
1.- Create a EKS cluster
2.- Run cluster-autoscaler, version 1.2.2 or 1.3, it's the same
3.- Update cluster-autoscaler yaml adding new ASG

Then

```bash
I0623 11:37:46.710465       1 reflector.go:202] Starting reflector *v1beta1.PodDisruptionBudget (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:266
I0623 11:37:46.710473       1 reflector.go:240] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:266
I0623 11:37:47.407943       1 request.go:481] Throttling request took 696.787298ms, request: PUT:https://172.20.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
I0623 11:37:47.408128       1 request.go:481] Throttling request took 298.758142ms, request: GET:https://172.20.0.1:443/api/v1/nodes?limit=500&resourceVersion=0
I0623 11:37:48.009609       1 cloud_provider_builder.go:72] Building aws cloud provider.
I0623 11:37:48.108061       1 auto_scaling_groups.go:78] Registering ASG eks-dev-NodeGroup-1HW5XCKEG8OPJ
I0623 11:37:48.108083       1 auto_scaling_groups.go:139] Invalidating unowned instance cache
I0623 11:37:48.108093       1 auto_scaling_groups.go:153] Regenerating instance to ASG map for ASGs: [eks-dev-NodeGroup-1HW5XCKEG8OPJ]
F0623 11:37:48.207999       1 cloud_provider_builder.go:137] Failed to create AWS Manager: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
At this moment I didn't find the way to solve. 

Take in consideration that :
1- EKS use amazon-vpc-cni
2.- I'm using kube2iam, but I'm not using it to cluster-autoscaler
3.- I'm using Amazon Linux 2 and I modified the cert path

```
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
```

Any idea? If I can give you more info let me know

**Comment by zee-ahmed** [comment]
+1 I'm having the exact same issue with kops using v1.1.2 on kubernetes 1.9.6 without using kube2iam.

IAM policy
`
{
  "Effect": "Allow",
  "Action": [
    "autoscaling:DescribeAutoScalingGroups",
    "autoscaling:DescribeAutoScalingInstances",
    "autoscaling:DescribeTags",
    "autoscaling:SetDesiredCapacity",
    "autoscaling:TerminateInstanceInAutoScalingGroup"
  ],
  "Resource": "*"
}
`
My certificate path is the same that exists in the current documentation - `/etc/ssl/certs/ca-certificates.crt` and i'm manually looking up the ASG instead of using the ASG discovery

**Comment by aleksandra-malinowska** [comment]
cc @kubernetes/sig-aws-misc

**Comment by maauso** [comment]
Hi!
I found the problem, we are using kube2aim, in this case, you need to use the annotations in cluster autoscaler yaml like 

```bash 
 template:
    metadata:
      annotations:
        iam.amazonaws.com/role: role
      labels:
        app: cluster-autoscaler
```
