### ISSUE TITLE
[Azure AKS] not logging scale-up events in autoscaler 

### ISSUE THREAD

**Issue by sakthi-vetrivel** [kubernetes/autoscaler#1029]
@kkmsft 
 I'm using the cluster-autoscaler for a one-node AKS cluster (rbac-enabled, k8's 1.10.3) and I noticed that while my cluster did scale up to three nodes, the cluster-autoscaler did not log any ScaleUp events. However, when it scaled back down to two nodes, it did log a ScaleDown event.
![capture](https://user-images.githubusercontent.com/17627350/42187850-702e37a2-7e06-11e8-9c0f-7396df2e0b5a.PNG)
![capture2](https://user-images.githubusercontent.com/17627350/42187851-704ce666-7e06-11e8-8afb-34f46ff83c4f.PNG)
![capture3](https://user-images.githubusercontent.com/17627350/42187853-708be276-7e06-11e8-8c96-35a96bd5743c.PNG)

**Comment by feiskyer** [comment]
/remove-lifecycle rotten

Still not resolved yet.

**Comment by feiskyer** [comment]
Already resolved.

/close
