### ISSUE TITLE
[AWS Kops] Cluster autoscaler timeout when trying to run on master node

### ISSUE THREAD

**Issue by sc250024** [kubernetes/autoscaler#1064]
Greetings,

I'm running `cluster-autoscaler` as part of a Kops cluster running on AWS. The problem is simple: when I run `cluster-autoscaler` on a regular node, it works fine, but when it's running on a master node, the pod times out, receives a `CrashLoopBackOff`, and then tries again to no avail. The following log message is the most applicable

```
F0715 16:55:30.458743       1 main.go:319] Failed to get nodes from apiserver: Get https://100.64.0.1:443/api/v1/nodes: dial tcp 100.64.0.1:443: i/o timeout
goroutine 1 [running]:
```

Kops version:  **1.9.1**
Kubernetes version: **1.9.6**
Cloud provider: **AWS**
Commands ran: **Followed the commands in the [Kops cluster-autoscaler documention](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler)**
What happened after the commands executed?: **Pod starts, and then goes into a `CrashLoopBackOff` loops**
What did you expect to happen?: **The `cluster-autoscaler` app goes into its normal loop of checking if the ASG is in it's target node size.**

Extra notes:
- I'm using the Calico networking stack
- I'm using the [Kube2IAM](https://github.com/jtblin/kube2iam) project. Both the master and node IAM roles have the proper permissions to assume the role I provide in the annotation like so:

```yaml
annotations:
  iam.amazonaws.com/role: CompanyIamRole-ClusterAutoscalerEc2
```

Cluster manifest and full log output: https://gist.github.com/sc250024/81525c85f3cdfc60349b3bfdcce755af

**Comment by MaciekPytel** [comment]
This means cluster autoscaler can't connect to kubernetes api-server. I have no idea how kops runs CA and I don't really know why there is no connectivity to api-server. Probably some network issue, may also be a timing issue if CA is run from manifest (I've seen this happen when CA starts before api-server does, though it usually fixes itself after a few restarts in that case). 

None of regular CA maintainers uses kops and we don't know much about calico or (anything at all really) about AWS IAM. I think opening an issue on kops repo (or pinging kops maintainers here) may get you more useful help.

**Comment by aleksandra-malinowska** [comment]
You can also try asking for help on slack - there are some AWS users active on [sig-autoscaling](https://kubernetes.slack.com/messages/C09R1LV8S/), and definitely on [sig-aws](https://kubernetes.slack.com/messages/C0LRMHZ1T/).

**Comment by sc250024** [comment]
Thanks @MaciekPytel and @aleksandra-malinowska , I'll open an issue in the Kops repo
