### ISSUE TITLE
[Cluster-autoscaler, aws] Node not being deleted from kubernetes cluster

### ISSUE THREAD

**Issue by xtroncode** [kubernetes/autoscaler#1068]
`kubernetes-version: 1.10.5`
`cluster-autoscaler version: 1.2.2`

I am experimenting with `cluster-autoscaler` on aws, while the desired capacity is being properly adjusted and the scale-in and scale-out works well, the nodes that are terminated are not deleted by the cluster autoscaler from k8s i.e when I run `kubectl get nodes` I can still see the terminated nodes in `NotReady` state and this causes issues in updating `DaemonSets`   https://github.com/kubernetes/kubernetes/issues/44458   

Ideally one would expect the node to be deleted from the cluster as well since the instance is terminated. 
I am running cluster-autoscaler with the following params 
```
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --nodes=1:10:KubernetesStaging
```

Am I missing something or this is the expected behaviour ?

**Comment by MaciekPytel** [comment]
All Cluster Autoscaler does is remove the instance on cloudprovider side. It is up to Kubernetes (and specifically node controller) to remove node objects.

**Comment by xtroncode** [comment]
Thanks @MaciekPytel  Do I need to enable certain flag in the `kube-controller-manager`  ?  I have setup my cluster using kubeadm and have used the `--cloud-provider=aws` flag only in the `cluster-autoscaler` and  `kubelet` configs.

**Comment by MaciekPytel** [comment]
You probably do need to set a flag in controller-manager, but I've never run kubernetes on AWS and I don't know the details. #kube-aws on kubernetes slack may be a good place to ask that.

**Comment by jonathortense** [comment]
Hi @xtroncode Can you explain better how exactly you added `--cloud-provider=aws` to `kube-controller-manager`?

I have exactly the same problem here and I have no idea where and how I should do this (which files to update or what commands to run).

Thanks.

**Comment by xtroncode** [comment]
Hi @jonathortense , you need to add the flag `--cloud-provider=aws` to the init command of your `kube-controller-manager` . If your master components are hosted as static pods you should modify your pod manifests, you can find them in `/etc/kubernetes/manifests/` generally . Let me know if that resolves your issue, or I need to know how your cluster has been setup.
