### ISSUE TITLE
Azure: New nodes as part of scale up are not being setup properly

### ISSUE THREAD

**Issue by MirzaSikander** [kubernetes/autoscaler#1073]
Kuberentes version: `v1.11.0`
Autoscale version: `v1.3.0`

New NC6 nodes, being added by auto-scaler, are missing some dependencies which prevent the following **kube-system** pods from being deployed. 

```
azure-cni-networkmonitor-j85gh
kube-proxy-xhskd
nvidia-device-plugin-drhtd
```

And they all have the same error:

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "azure-cni-networkmonitor-j85gh": Error response from daemon: shim error: fork/exec /usr/bin/nvidia-container-runtime: no such file or directory

Pod sandbox changed, it will be killed and re-created.
```

Further details about node:
```
Kernel Version: 4.15.0-1013-azure
OS Image: Ubuntu 16.04.4 LTS
Container Runtime Version: docker://1.13.1
Kubelet Version: v1.11.0
Kube-Proxy Version: v1.11.0
```

**Comment by MirzaSikander** [comment]
All the deployments in Azure portal started by the auto-scaler are reporting succeeded status.

**Comment by feiskyer** [comment]
@MirzaSikander  Are you using acs-engine? Seems nvidia-container-runtime is not set properly on provisioning the new node.

**Comment by MirzaSikander** [comment]
@feiskyer Yes I am using acs-engine `v0.19.1`

**Comment by sshepel** [comment]
@feiskyer same thing for me (version of the acs-engine is `v0.19.2`), but want to note that same issue appeared on AKS.

**Comment by MirzaSikander** [comment]
Any work around for this? Currently blocking all operations.

**Comment by feiskyer** [comment]
It should be fixed in acs-engine v0.20.0. 

@sshepel @MirzaSikander Could you upgrade acs-engine and try again?

**Comment by sshepel** [comment]
@feiskyer looks OK, now. Will monitor further... but for now pods are scheduled without any issues.
Thanks a lot!

**Comment by feiskyer** [comment]
@sshepel Cool. Thanks for the confirmation.
