### ISSUE TITLE
cluster-autoscaler-status ConfigMap should support other namespaces besides kube-system

### ISSUE THREAD

**Issue by mtcode** [kubernetes/autoscaler#108]
CA can run in multiple namespaces, and supports the `namespace` command line argument.  This should propagate to the `cluster-autoscaler-status` ConfigMap so that it exists in the same namespace as the CA.  Currently it is a constant, `kube-system`, in `clusterstate/utils/status.go`.

**Comment by MaciekPytel** [comment]
I'll fix that along with #106, hopefully in time for 0.6 release.

**Comment by mtcode** [comment]
Great, thanks!

**Comment by mwielgus** [comment]
Fixed with #119
