### ISSUE TITLE
EKS and tag k8s.io/cluster-autoscaler/node-template/label is not assigned to worker nodes

### ISSUE THREAD

**Issue by cabrinoob** [kubernetes/autoscaler#1081]
Hi,
I'am using an EKS cluster and I'd like to use cluster-autoscaler with it.

So I have a brand new EKS cluster (with existing nodes) and I'd like to add new worker nodes with the CloudFormation script (as explained [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html)).

This script provided 3 new t2.small EC2 into an auto-scaling group. Because I'd like to use nodeSelector, I have tagged the ASG as explained [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0) : 

_If you are using nodeSelector you need to tag the ASG with a node-template key "k8s.io/cluster-autoscaler/node-template/label/"_

In my AWS console I see my tag on my ASGlike that : 

![tag](https://i.imgur.com/wzZltrG.png)

So, my problem is that I see news nodes in kubernetes, but the tag _k8s.io/cluster-autoscaler/node-template/label/project_ has not been assigned to the labels of these nodes .... I don't know what I have missed.

The only tags I see are : 

```
Labels:         beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t2.small
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1c
                    kubernetes.io/hostname=ip-xxx-xxx-xxx-xxx.ec2.internal
```

Here is the launch command of the cluster-autoscaler pod : 
```json
"command": [
              "./cluster-autoscaler",
              "--v=4",
              "--stderrthreshold=info",
              "--cloud-provider=aws",
              "--skip-nodes-with-local-storage=false",
              "--nodes=1:3:at-eks-worker-nodes-asg2-NodeGroup-1QOBK4RZ42IZI"
            ]
```
What I've missed?

Thank you for your help

**Comment by bskiba** [comment]
Is the label missing on all nodes in the asg or only if autoscaler creates them (during scale up)?

**Comment by cabrinoob** [comment]
The label is missing on all nodes. I did'nt succeed to deploy something using NodeSelector, because there is no node available with _project=asg2_ label in my cluster.

**Comment by bskiba** [comment]
Then AFAIU this is not a problem with autoscaler but AWS not propagating the label to nodes. I think it will be easier to find help from [sig-aws](https://github.com/kubernetes/community/tree/master/sig-aws). Unelss any of the folks deploying CA on AWS know how to debug this.

**Comment by cabrinoob** [comment]
Ok, I'll try over there. Thank you!

**Comment by rapuckett** [comment]
@cabrinoob  Has there been any progress on this? I'm experiencing the same issue. Labels from my ASG are not being propagated to nodes - in fact, node are being labeled "kops.k8s.io/instancegroup: k80-group" (which is from a completely different ASG). Would love a pointer in the right direction.

<img width="1181" alt="Screen Shot 2020-01-14 at 12 02 47 PM" src="https://user-images.githubusercontent.com/915724/72378375-16132780-36c6-11ea-945e-4f04a93458ee.png">

**Comment by xtroncode** [comment]
@cabrinoob  Were you able to fix this ?

**Comment by subhrang** [comment]
Use PropagateAtLaunch = true
