### ISSUE TITLE
Add unit tests for cluster_feeder.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#1086]
We really need tests for https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go

**Comment by Rajat-0** [comment]
I would like to work on it

**Comment by bskiba** [comment]
Great! Feel free to send PRs my way

**Comment by bskiba** [comment]
There's some test bu we still desperately need more coverage.
/remove-lifecycle stale
