### ISSUE TITLE
Support for new AWS EC2 instance types (R5, R5d, and z1d)

### ISSUE THREAD

**Issue by bob-shih** [kubernetes/autoscaler#1096]
Please add the new AWS EC2 instance types (R5, R5d, and z1d) support in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go

(See https://aws.amazon.com/blogs/aws/now-available-r5-r5d-and-z1d-instances/)

Thanks

**Comment by aleksandra-malinowska** [comment]
AWS cloud provider in Cluster Autoscaler is supported entirely by the community. Contributions are welcome :)

**Comment by bskiba** [comment]
Seems this can be closed.
