### ISSUE TITLE
VPA replaces annotations of pods, in stead of updating. This breaks PSP.

### ISSUE THREAD

**Issue by wmuizelaar** [kubernetes/autoscaler#1103]
Hi,

Testing with the vertical-pod-autoscaler, we figured out that the annotations on a pod are completely replaced by the admission controller, in stead of merged/added.

Used version of the containers:
```
k8s.gcr.io/vpa-admission-controller:0.2.0
k8s.gcr.io/vpa-recommender:0.2.0
k8s.gcr.io/vpa-updater:0.2.0
```

What I see is that containers that are run from a deployment, and I set a custom annotation in my specfile, these will be overwritten by the vpa-admission-controller:

Before:
```
kubectl describe pod nginx-deployment-5d78d59c86-dxg7h
Name:           nginx-deployment-5d78d59c86-dxg7h
Namespace:      default
Node:           gke-bolcom-sbx-4wu-internal-4e3396ab-b2lj/10.16.4.18
Start Time:     Tue, 31 Jul 2018 13:37:25 +0200
Labels:         app=nginx
                pod-template-hash=1834815742
Annotations:    bol.io/test=test
                kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container nginx
```

After:
```
kubectl describe pod nginx-deployment-5d78d59c86-lr2wv
Name:           nginx-deployment-5d78d59c86-lr2wv
Namespace:      default
Node:           <none>
Labels:         app=nginx
                pod-template-hash=1834815742
Annotations:    vpaUpdates=Pod resources updated by nginx-vpa: container 0: cpu request, memory request, memory limit
```

When using Pod Security Policies in a cluster, this will also set annotations, and since those are overwritten by the admission controller, those pods won't get scheduled again, since there cannot be found a valid podsecuritypolicy.

**Comment by bskiba** [comment]
Hm, can't seem to reproduce this... 
I've added annotations to the hamster example for the repo, like this: https://gist.github.com/bskiba/1aad99ecb52e75f744b3f88c21e1ea3f

And here is what I see:
```
kubectl describe pod
Name:           hamster-7cb9f4785d-ww8gh
Namespace:      default
Start Time:     Tue, 31 Jul 2018 20:24:13 +0200
Labels:         app=hamster
                pod-template-hash=3765903418
Annotations:    vpa-test=test
                vpaUpdates=Pod resources updated by hamster-vpa: container 0: cpu request, memory request, memory limit
```
Can you try the modified hamster example form the gist with your setup and see if it produces different results for you?

Also which version of Kubernetes?

**Comment by maartenvandenbogaard** [comment]
Hi, we run into this issue with GKE version 1.10.5-gke.3. 

I can reproduce it with your modified hamster example.

Before:
````
kubectl describe pod hamster-756b778486-drz6w
Name:           hamster-756b778486-drz6w
Namespace:      default
Start Time:     Tue, 31 Jul 2018 23:44:25 +0200
Labels:         app=hamster
                pod-template-hash=3126334042
Annotations:    vpa-test=test
````
After:
````
kubectl describe pod hamster-756b778486-f65vt
Name:           hamster-756b778486-f65vt
Namespace:      default
Start Time:     Tue, 31 Jul 2018 23:46:00 +0200
Labels:         app=hamster
                pod-template-hash=3126334042
Annotations:    vpaUpdates=Pod resources updated by hamster-vpa: container 0: cpu request, memory request, memory limit
````

We eventually got it working with attached pull request.

**Comment by bskiba** [comment]
Ah, I tested with 1.9, they must have changed the way patches are handled in 1.10... Thanks for the pr, I'll review today.
