### ISSUE TITLE
addon-resizer scale based on number of namespaces (feature request)

### ISSUE THREAD

**Issue by directionless** [kubernetes/autoscaler#1112]
Hi! I have a couple of small GKE clusters, and many of the tools I interact with use the addon-resizer. In my environment, it usually underprovisions and results in endless cycles of OOMKilling and number tweaking. 

I _suspect_ this is because I have a n large number of namespaces:
```
$ kubectl get ns | wc -l
     238

$ kubectl get nodes | wc -l
      47

$ kubectl get pods --all-namespaces | wc -l
    4008
```

Most recently, I've run into this with kube-state-metrics, heapster, and metrics-server. The latter two are mostly google provisioned, so it's extra awkward working with them.

How do y'all feel about adding a namespace scaling option?

**Comment by MaciekPytel** [comment]
cc: @x13n @kawych

**Comment by kawych** [comment]
I suspect that the actual issue is the number of pods, not the number of namespaces. Heapster and Metrics Server by default are configured to deal with ~30 pods per node, your cluster exceeds this significantly. You may want to take a look at custom Addon Resizer configuration as documented here: https://github.com/kubernetes/autoscaler/tree/master/addon-resizer#addon-resizer-configuration

**Comment by x13n** [comment]
Ideally, addon resizer should just look at pod count instead of node count and not assume anything about the count of pods/node.

Instead of reshaping your whole cluster to get lower pod/node ratio I'd just follow kawych's advice to bump the resource requests using custom config.

**Comment by directionless** [comment]
My current work around is to bump up resources using custom configs. But it's an ongoing battle. My usage seems to be just far enough outside normal, that a lot of things don't work out of the box.

But, the feedback that my issue is likely with the pod/node ratio is very useful to me. Thank you for that pointer.
