### ISSUE TITLE
Support AWS Spot block instances as pseudo ASG

### ISSUE THREAD

**Issue by nhoughto** [kubernetes/autoscaler#1125]
We use autoscaler on AWS quite successfully for real time workloads, but would like to use spot instances for our CI build workload. Since spot instances themselves are too disruptive for non-preemptive workloads like CI jobs we want to use Spot Blocks (defined duration instances) where they are guaranteed for N hours.

Autoscaler could provision these instances and then replace them when they expire, as well as manage the condoning and draining as required, could obv also managing scaling them up too.

We currently use some bash scripts to manage this but would love a first party / more flexible answer.

Our current bash scripts, for anyone else with this problem:

https://github.com/bsycorp/spot-keeper

**Comment by Jeffwan** [comment]
It's a very reasonable feature request. I will take a look at the change and evaluate the work.

**Comment by DanyC97** [comment]
@Jeffwan  have you made any progress on this  ?

**Comment by Jeffwan** [comment]
@DanyC97 Just see this message. Spot Block is an EC2 Fleet feature and currently CA only supports ASG features from LaunchConfiguration or LaunchTemplate. It would be some extra work to support it. For example, request spot block instances and then add to ASG, this brings some complexity managing these instance groups in scale up/down. 

Do you have any good ideas to add this support?

**Comment by mvisonneau** [comment]
spot blocks can now be defined through launch templates. I believe it should be easier to implement 👍

**Comment by Jeffwan** [comment]
/reopen

We still want to have this feature.

**Comment by unixfox** [comment]
/reopen

I'm also interested into this feature.

**Comment by unixfox** [comment]
Can someone reopen this issue?
