### ISSUE TITLE
Feature Request - Scale down should cordon nodes

### ISSUE THREAD

**Issue by timothyclarke** [kubernetes/autoscaler#1136]
I use EC2 and have had instances where pods have been scheduled onto nodes which are in a shutting down state in EC2.
From observation it appears that when scaling down pods the node is not cordoned which would prevent new pods from being scheduled onto them.

**Comment by MaciekPytel** [comment]
Cluster autoscaler adds `ToBeDeletedByClusterAutoscaler` taint with a NoSchedule effect to nodes it's deleting. Unless your pods have toleration for that taint (or some wildcard toleration) new pods should not be able to schedule on those nodes.

**Comment by MaciekPytel** [comment]
Agreed. This toleration doesn't fit our taint. 

Regarding your feature request - we already implement it by adding the taint. If CA is not tainting nodes in your env it's a bug, but to investigate it I'd need more data including CA version and scale-down logs.
