### ISSUE TITLE
Feature Request - scale-down-utilization-threshold per instance group, and from label

### ISSUE THREAD

**Issue by timothyclarke** [kubernetes/autoscaler#1137]
We utilise a cluster that contains both CI and development environments. As such there is more than one instance group that needs scaling.
We are in AWS and the instance groups use different sized nodes for the CI compared to the general environments. As such having a common `scale-down-utilization-threshold` will cause either one instance group to prematurely kill nodes to be rescheduled elsewhere (for the larger node types), or to never scale down instance types because their utilisation is too high when they are only running networking pods (or similar daemon sets).

It would be really useful to set the `scale-down-utilization-threshold` on a per instance group basis, and be able to set that via cloud labels so it can be autodiscovered.

**Comment by aleksandra-malinowska** [comment]
DaemonSet use-case should be addressed by #1407. As for different thresholds, the difficulty would be in configuring them - there's no such concept as node group in Kubernetes, so it'd either have to be done in a cloud provider specific way, like you suggest, or e.g. by node annotations (assuming all nodes in a node group have these identical). Both are possible but complicate things, so I'm not really sure if this is worth it. 

Can you elaborate a bit more about "prematurely kill nodes to be rescheduled elsewhere"? It seems to me that if it's OK for the pods to be rescheduled and if they can be moved elsewhere, reducing machine costs, it's a good thing to scale a bit more aggressively. On the other hand, if there's a pod that shouldn't be rescheduled (e.g. a job that you don't want restarted) and was only protected so far by low utilization threshold, safe-to-evict annotation could be used to protect it removal until it's completed.

**Comment by timothyclarke** [comment]
@aleksandra-malinowska Thanks for your response.

> Can you elaborate a bit more

We have traditional apps running which can be moved around and aggressive scaling for those are good.
However we also have jenkins scheduling builds when people commit new code. If those builds are killed half way through then the build goes red and has to be manually re-scheduled. While the builds don't take too long having the autoscaler kill them part way through gives the impression that the build environment is unstable / unreliable. Can you provide any details about a (un)safe-to-evict annotation ?

@awprice Thank you. That looks like it's what I would need to cover the jenkins / ci nodes while the standard autoscaler manages the traditional nodes where pods can be moved easily. It seems a little sub optimal to run two autoscalers. Granted I'm using AWS and I'm also auto registering the nodes by annotation on the nodes. 
My feature request challenges the inherent requirement that all nodes that an autoscaler manages be of the same instance type / capacity.

**Comment by aleksandra-malinowska** [comment]
> However we also have jenkins scheduling builds when people commit new code. If those builds are killed half way through then the build goes red and has to be manually re-scheduled. While the builds don't take too long having the autoscaler kill them part way through gives the impression that the build environment is unstable / unreliable. Can you provide any details about a (un)safe-to-evict annotation ?

Annotating the pods to prevent eviction and scale-down of nodes where they're running is described here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
