### ISSUE TITLE
Feature Request - Trigger webhook when scaling is performed

### ISSUE THREAD

**Issue by tomkerkhove** [kubernetes/autoscaler#1150]
_Disclaimer - If this is already possible, sorry for creating this issue but I couldn't find anything related to this_

Would be great to be able to configure a webhook which is called for every scaling operation (up or down).
This would allow users to gain insights on their scaling actions if they wish to do so.

A great example is how Azure Monitor autoscale provides this on their component for Azure scaling ([docs](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/insights-autoscale-to-webhook-email)).

[I wrote a blog post](https://blog.tomkerkhove.be/2017/10/16/autoscaling-your-platform-with-azure-monitor/) a while back why I love this and why it's important.

**Comment by bskiba** [comment]
@MaciekPytel @kgolab I think you are the best suited to comment here.

**Comment by MaciekPytel** [comment]
Currently there are no webhooks of any kind in CA and I'm worried adding them would require significant effort. For example we'd need to create a mechanism for registering those webhooks. We'd probably also have to start thinking about all the pesky stuff with certificates and security that we avoided so far by not having any API surface whatsoever. Personally I'd rather avoid the added complexity, even if someone volunteered to implement this. 

Note that we already provide some ways to monitor scaling operations:
- You can use scaled_up_nodes_total and scaled_down_nodes_total metrics to track scaling operations.
- We write Kubernetes events on every scaling operation. You can set up a watch on those. Admittedly they're meant to be human readable and so are a bit of pain to parse, but we could try to improve them.

Finally, recently we've been doing a bit of refactoring to make CA more extensible for use-cases such as yours. Basically what you're asking for, except it's a hook in code and not a webhook. If you're willing to compile your own CA image you can just implement your own status processor (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/processors/status) that calls back to your API.

**Comment by MaciekPytel** [comment]
For CA the events are described here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-events-are-emitted-by-ca.

HPA also writes events when performing scaling operations, but I don't know if they're documented anywhere. Probably the easiest thing would be to trigger a scale-up/scale-down and check out the events using `kubectl describe hpa`. For VPA @bskiba is a better person to answer.

**Comment by bskiba** [comment]
For VPA there are no events written yet. 
We are planning to add event on pod update for changing resource requests and there is an annotation on the pod that had it's requests modified by VPA.

**Comment by tomkerkhove** [comment]
Thank you for the information, I'm closing as the platform already provides information - I just need to find another way to hook into those.
