### ISSUE TITLE
Autoscaler docs - priority cutoff confusion

### ISSUE THREAD

**Issue by consideRatio** [kubernetes/autoscaler#1157]
While reading the [Cluster Autoscaler FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-work-with-pod-priority-and-preemption), I find the following statement saying that pods with priority lower than 0 don't trigger scale up.

**SCREENSHOT 1**
![image](https://user-images.githubusercontent.com/3837114/44282710-3bdf9700-a25c-11e8-84b7-795c4c35136d.png)

---

Later, in this section a lot of confusion is created:

1. The example suggest changing the cutoff which isn't recommended, without motivation.
2. The cutoff is claimed to be -1, while it was claimed to be 0 above.

**SCREENSHOT 2**
![image](https://user-images.githubusercontent.com/3837114/44282825-95e05c80-a25c-11e8-9bca-7f347610603a.png)

**Comment by MaciekPytel** [comment]
cc: @aleksandra-malinowska I think you made some changes in this doc when updating default cutoff? Can you take a look

**Comment by aleksandra-malinowska** [comment]
The default was only changed in manifest file for now (down to -10). Looking into why there's conflicting information here.

**Comment by consideRatio** [comment]
Stale discussion, but still very relevant, and the docs remain confusing to me.

**Comment by consideRatio** [comment]
There is now...

>Default priority cutoff is -10 (since version 1.12, was 0 before that). It can be changed using --expendable-pods-priority-cutoff flag, but we discourage it. Cluster Autoscaler also doesn't trigger scale-up if an unschedulable pod is already waiting for a lower priority pod preemption.

So, I'm happy to close this.
