### ISSUE TITLE
Expose culprit code path which resulted in an error in metrics

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/autoscaler#1161]
Currently we are reporting errors counts grouping them just by one axis. Each reported error is one of:
* cloudProviderError
* apiCallError
* internalError
* transientError

as defined in: https://github.com/kubernetes/autoscaler/blob/5c4693f95f37e37dc135cc4c3f69978a22545104/cluster-autoscaler/utils/errors/errors.go#L48

This does not give us information which code path resulted in an error. To address that we could extend the errors counts metrics with another label. Let's call "operation" and fill it in with values which marks code path which was source of an error.

**Comment by MaciekPytel** [comment]
Do you mean to have a label with value specific for every possible error? That would explode metric cardinality, probably making it a no-go.

**Comment by losipiuk** [comment]
Yep. It would change cardinality by factor of (wild guess) 50. Seems feasible.

**Comment by MaciekPytel** [comment]
Huh, I wonder how you got to 50. Counting NewAutoscalerError + ToAutoscalerError?
