### ISSUE TITLE
Use informer to list VPA checkpoints.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#1164]
We call API server directly to list VPA checkpoints. We should switch to using informer:
https://github.com/kubernetes/autoscaler/blob/9feb612e2200e04c2ac8f7dd7cc8e7adbe300add/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L190-L192

**Comment by petr-k** [comment]
Hello, I intend to work in this one ;)

**Comment by bskiba** [comment]
Great! LMK if you run into issues.

**Comment by bskiba** [comment]
Actually, since VPA is the one writing checkpoints and we only list them once on startup, adding an informer here is not necessary. Sorry for the confusion!
