### ISSUE TITLE
Check if VPA object update is needed.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#1165]
Object updates are costly. We should check if the object has changed before trying to perform an update. 
We can also skip updates if recommendation delta is small and conditions haven't changed.
https://github.com/kubernetes/autoscaler/blob/9feb612e2200e04c2ac8f7dd7cc8e7adbe300add/vertical-pod-autoscaler/pkg/utils/vpa/api.go#L58:6

**Comment by bskiba** [comment]
@phsiao Does the fix in #1204 mitigate your issues when scale testing VPA? It shortened the time of updating 100 VPAs from 20s to aroun 1s. (writing checkpoints need work still though)

**Comment by phsiao** [comment]
I have not run into issues with updating too slow yet, as I am not yet testing for convergence speed.   But it is good to know this will now better.
