### ISSUE TITLE
Cluster-autoscaler not considering the resource "pod" to scale upwards

### ISSUE THREAD

**Issue by fdornberger** [kubernetes/autoscaler#1184]
I'm using the CA on an AWS EKS cluster. 

In the dev environment, I use t2.small instances which serve the purpose. The resource footprint of my apps in this environment is fairly low, which is why my pods could easily fit on 2 t2.small instances but AWS has a limit with regards to how many pods can be installed on a given instance type. This list can be found here: https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

With 2 t2.small instances, I can thus host up to 16 pods before AWS no longer allows new pods to be scheduled.

Since I have more than 16 pods that should be deployed, some apps show this status:

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  1m (x330 over 1h)  default-scheduler  0/2 nodes are available: 1 Insufficient memory, 2 Insufficient pods.
```

The cluster auto-scaler determines he can't satisfy the apps needs even by scaling up the nodes by 1 as it doesn't seem to take "pods" as an allowed resource based on each instance. Understood that I ran out of memory to serve all the pods as of now, but scaling would solve this issue. The auto-scaler doesn't seem to know that scaling up instances will also allow the max-amount of pods that can be run on a cluster.

Manually provisioning an new EC2 instance does help but that is not the goal of using the cluster-autoscaler.

Did anyone solve that problem already?

**Comment by aleksandra-malinowska** [comment]
> The cluster auto-scaler determines he can't satisfy the apps needs even by scaling up the nodes by 1 as it doesn't seem to take "pods" as an allowed resource based on each instance. Understood that I ran out of memory to serve all the pods as of now, but scaling would solve this issue. The auto-scaler doesn't seem to know that scaling up instances will also allow the max-amount of pods that can be run on a cluster.

Scheduler's predicate PodFitsResources checks for the allowed number of pods based on Node object's Allocatable. Cluster Autoscaler runs this predicate, and if the limit is set correctly, it should be aware that it needs to add a new node. That being said, I have no idea how this limitation is imposed on EKS.

Can you provide output of running `kubectl get node \<node name\> -o yaml` to verify if the Allocatable is set?

And if you have access to autoscaler logs, can you also include any relevant log lines (i.e. anything related to the pending pods)?

**Comment by fdornberger** [comment]
Hey @aleksandra-malinowska 

Here's the YAML of one random node in the group:

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2018-08-23T08:41:52Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: t2.small
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-east-1
    failure-domain.beta.kubernetes.io/zone: us-east-1b
    kubernetes.io/hostname: ip-10-8-4-107.ec2.internal
  name: ip-10-8-4-107.ec2.internal
  resourceVersion: "4409910"
  selfLink: /api/v1/nodes/ip-10-8-4-107.ec2.internal
  uid: 625123c9-a6b0-11e8-9ac7-0ab6f0d19124
spec:
  externalID: REDACTED
  providerID: REDACTED
status:
  addresses:
  - address: 10.8.4.107
    type: InternalIP
  - address: ip-10-8-4-107.ec2.internal
    type: Hostname
  allocatable:
    cpu: "1"
    ephemeral-storage: "19316009748"
    hugepages-2Mi: "0"
    memory: 1939176Ki
    pods: "8"
  capacity:
    cpu: "1"
    ephemeral-storage: 20959212Ki
    hugepages-2Mi: "0"
    memory: 2041576Ki
    pods: "8"
  conditions:
  - lastHeartbeatTime: 2018-08-24T13:50:51Z
    lastTransitionTime: 2018-08-23T08:41:51Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2018-08-24T13:50:51Z
    lastTransitionTime: 2018-08-23T08:41:51Z
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: 2018-08-24T13:50:51Z
    lastTransitionTime: 2018-08-23T08:41:51Z
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: 2018-08-24T13:50:51Z
    lastTransitionTime: 2018-08-23T08:41:51Z
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: 2018-08-24T13:50:51Z
    lastTransitionTime: 2018-08-23T08:42:33Z
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni@sha256:db4efc51d5ed4ecaca3f5775655722be57825702e37df1bdedca8ce297289870
    - 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.1.0
    sizeBytes: 391689144
  - names:
    - newrelic/infrastructure-k8s@sha256:1f66509c55f8fb58f721dc5e90420a65b1ecc0f6da183ce9c2b7866b6e9ef30d
    - newrelic/infrastructure-k8s:1.2.0
    sizeBytes: 249713559
  - names:
    - k8s.gcr.io/cluster-autoscaler@sha256:36a369ca4643542d501bce0addf8b903f2141ae9e2608662b77a3d24f01d7780
    - k8s.gcr.io/cluster-autoscaler:v1.2.2
    sizeBytes: 208688449
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy@sha256:76927fb03bd6b37be4330c356e95bcac16ee6961a12da7b7e6ffa50db376438c
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.10.3
    sizeBytes: 96933403
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-dns/kube-dns@sha256:f7a8e125330398b41bafa1fc2bf0c56b003f0394b73e8222a2009b68c5ec4a1b
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-dns/kube-dns:1.14.10
    sizeBytes: 49549457
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-dns/sidecar@sha256:3bddd56ea6af0dfef6709702c111122046697986808ee9d6a154f856e8e5f3e6
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-dns/sidecar:1.14.10
    sizeBytes: 41635309
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-dns/dnsmasq-nanny@sha256:acdfb44e37405dc9cfa25dca2a07ed97f35d0d77e34f18d8348475f9c181ad09
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-dns/dnsmasq-nanny:1.14.10
    sizeBytes: 40372149
  - names:
    - registry.opensource.zalan.do/pathfinder/skipper@sha256:37f224fcc4998da0ade857bb2c3a1b08adedbab0689fde12e6b4c68b7961f333
    - registry.opensource.zalan.do/pathfinder/skipper:latest
    sizeBytes: 24834550
  - names:
    - registry.opensource.zalan.do/teapot/kube-ingress-aws-controller@sha256:c6d94bde129df68d3a09646be9e60320f3c3c808a29133718889207615f04a1d
    - registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:latest
    sizeBytes: 19286202
  - names:
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64@sha256:bea77c323c47f7b573355516acf927691182d1333333d1f41b7544012fab7adf
    - 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64:3.1
    sizeBytes: 742472
  nodeInfo:
    architecture: amd64
    bootID: REDACTED
    containerRuntimeVersion: docker://17.6.2
    kernelVersion: 4.14.62-70.117.amzn2.x86_64
    kubeProxyVersion: v1.10.3
    kubeletVersion: v1.10.3
    machineID: REDACTED
    operatingSystem: linux
    osImage: Amazon Linux 2
    systemUUID: REDACTED
```

**Comment by aleksandra-malinowska** [comment]
Looks like node's allocatable is set correctly, so it's probably not related to this. I'd recommend checking autoscaler logs for reason why there was no scale-up. Without knowing your exact setup, it's hard to guess what may be the cause.

**Comment by fdornberger** [comment]
@aleksandra-malinowska The above log extract (code block #2) is from the cluster autoscaler. It represents one full scaling cycle. What else would like like to have a look at?

**Comment by MaciekPytel** [comment]
I think that line from log is critical:
`W0824 14:01:35.660707       1 scale_up.go:105] Node group cr-k8s-dev-team-CASE20180822120533398900000002 is not ready for scaleup
`
Autoscaler is aware that you need more nodes, but it considers the node group is not healthy and adding more nodes to it will likely fail. This can be caused by one of two reasons:
1. A scale up on this group has failed recently.
2. There are too many unhealthy / unregistered nodes in the node group.

You can check which one is it by looking at status configmap:
`kubectl get configmap cluster-autoscaler-status -o yaml -n kube-system`

If it's #1 ScaleUp status of the node group will be 'Backoff', if it's #2 the node group will be listed as unhealthy.

**Comment by fdornberger** [comment]
@MaciekPytel Could it be that it was unable to scale up since I just manually terminated an instance to see if it's able to scale?

This is the configmap as you requested:

```
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2018-08-24 15:05:53.671525269 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=0)
                   LastProbeTime:      2018-08-24 15:05:52.966705691 +0000 UTC
                   LastTransitionTime: 2018-08-23 12:42:26.021473142 +0000 UTC
      ScaleUp:     NoActivity (ready=3 registered=3)
                   LastProbeTime:      2018-08-24 15:05:52.966705691 +0000 UTC
                   LastTransitionTime: 2018-08-23 12:42:26.021473142 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2018-08-24 15:05:52.966705691 +0000 UTC
                   LastTransitionTime: 2018-08-23 12:42:26.021473142 +0000 UTC

    NodeGroups:
      Name:        cr-k8s-dev-team-CASE20180822120533398900000002
      Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=0 cloudProviderTarget=3 (minSize=3, maxSize=10))
                   LastProbeTime:      2018-08-24 15:05:52.966705691 +0000 UTC
                   LastTransitionTime: 2018-08-23 12:42:26.021473142 +0000 UTC
      ScaleUp:     NoActivity (ready=3 cloudProviderTarget=3)
                   LastProbeTime:      2018-08-24 15:05:52.966705691 +0000 UTC
                   LastTransitionTime: 2018-08-24 15:00:39.972624964 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2018-08-24 15:05:52.966705691 +0000 UTC
                   LastTransitionTime: 2018-08-23 12:42:26.021473142 +0000 UTC

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2018-08-24 15:05:53.671525269 +0000
      UTC
  creationTimestamp: 2018-08-23T12:42:15Z
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "4419461"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: f6944ed4-a6d1-11e8-9ac7-0ab6f0d19124
```

**Comment by MaciekPytel** [comment]
Right, so now it looks fine. You'd need to look at configmap while the problem was ongoing. Having a single broken node shouldn't be enough for CA to consider the group unhealthy. IIRC the group is unhealthy if max(4, 33% * number_of_nodes) of nodes are unhealthy. A group is in backoff for 5 to 30 minutes after a failed scale-up (exponential backoff).

**Comment by MaciekPytel** [comment]
For backoff you can grep the log for log messages starting with `Disabling scale-up for node group`.

**Comment by fdornberger** [comment]
@MaciekPytel Thanks for your help. You pushed me in the right direction.

This issue was the following: My EC2 instances lacked the right `autoscaling:SetDesiredCapacity` I didn't spot this since all the other functionality was working. I had the policy created but it wasn't attached to the instances and it slipped my attention but I was able to spot it in the logs, eventually:

```
Failed to scale up: failed to increase node group size: AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/REDACTED/REDACTED is not authorized to perform: autoscaling:SetDesiredCapacity on resource: arn:aws:autoscaling:us-east-1:REDACTED:autoScalingGroup:REDACTED:autoScalingGroupName/REDACTED
```

After having waited until the scale-up schedule quarantine time was over, new nodes spun up.

Thanks for you help and same @aleksandra-malinowska 

The addon is working well if configured correctly. Shame on me.
