### ISSUE TITLE
Several puzzles with AWS cluster autoscaler

### ISSUE THREAD

**Issue by danbeaulieu** [kubernetes/autoscaler#1195]
Hi I am prototyping a cluster on AWS using k8s 1.11.z. I get similar results for CA 1.2.2 and the 1.3 beta.

I have a 3 node control plane running t2 mediums created via kubeadm. I am NOT using cloud-provider=aws for any of the control plane services as we found it introduces a lot of magic that complicates our architecture. We do however set cloud-provider=aws for CA. 

I have a worker node ASG (danb-test) with the correct tags and it is scaled to 0. So a 3 node control plane with no worker nodes and cluster auto scaler is running on the control plane.

I started a pod to test CA. I'd expect it to identify my worker node ASG (it does), figure out no nodes are running in the ASG, and scale it up.

```
kubectl run testpod --image=ubuntu:16.04 bash
```

Below is the log that illustrates some of my puzzles.

```
I0827 13:01:50.249429       1 leaderelection.go:209] successfully renewed lease kube-system/cluster-autoscaler
I0827 13:01:51.120193       1 static_autoscaler.go:131] Starting main loop
I0827 13:01:51.343324       1 auto_scaling_groups.go:245] Regenerating instance to ASG map for ASGs: [danb-test]
I0827 13:01:51.420342       1 aws_manager.go:125] Refreshed ASG list, next refresh after 2018-08-27 13:02:01.420334282 +0000 UTC m=+228.570627650
W0827 13:01:51.509220       1 clusterstate.go:517] Failed to get nodegroup for i-0253e1488de4b1f8c: Wrong id: expected format aws:///<zone>/<name>, got 
W0827 13:01:51.509266       1 clusterstate.go:517] Failed to get nodegroup for i-0ecf671292db11881: Wrong id: expected format aws:///<zone>/<name>, got 
W0827 13:01:51.509274       1 clusterstate.go:517] Failed to get nodegroup for i-065d19525b16ec0b4: Wrong id: expected format aws:///<zone>/<name>, got 
I0827 13:01:51.509363       1 utils.go:486] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0827 13:01:51.509378       1 static_autoscaler.go:244] Filtering out schedulables
I0827 13:01:51.509517       1 static_autoscaler.go:254] No schedulable pods
I0827 13:01:51.509540       1 scale_up.go:60] Pod default/testpod-74cdb45bf5-rwc72 is unschedulable
E0827 13:01:51.509560       1 static_autoscaler.go:283] Failed to scale up: failed to build node infos for node groups: Wrong id: expected format aws:///<zone>/<name>, got 
```

1) i-0253e1488de4b1f8c, i-0ecf671292db11881, and i-065d19525b16ec0b4 are all control plane nodes. They are in an ASG but that ASG is not tagged for discovery by CA. Why is CA doing anything with them?
2) The log indicates the testpod pod is unschedulable, why is this? Do I need to annotate my pod, etc?
3) Since I don't set cloud-provider=aws for the control plane services my nodes don't have a providerID. Is there a reason why the providerID needs to be set?

**Comment by MaciekPytel** [comment]
Let me start by saying we recommend our users to set --cloud-provider flag for control plane components. I haven't heard of anyone not setting it on purpose, so what you're trying to do is untested (at least to the best of CA developers knowledge).

1. I don't know, you'd probably have to dig through AWS cloudprovider code. Unfortunately AWS provider doesn't have a regular maintainer (none of the CA maintainers has access to AWS account to test any code, so we only advise and do code reviews for community members contributing to AWS provider).
2. It means the pod is pending, can't be scheduled on existing nodes and will need a scale-up. Given the description of your test that part seems to work as expected.
3. Scale-down deletes a specific node, as opposed to just resizing ASG and letting cloud provider pick the VM to delete. To do so CA must be able to translate node object into a VM identifier that can be used in API call to cloud provider.
