### ISSUE TITLE
Cluster-Autoscaler should query AWS meta-data to determine AWS_REGION if not set

### ISSUE THREAD

**Issue by frittentheke** [kubernetes/autoscaler#1208]
Currently, the cluster-autoscaler requires the AWS_REGION variable to be defined. Surely this can be done statically in the YAML or via some init container calling the meta-data service from AWS or even by using the downwardAPI at some point in the future (https://github.com/kubernetes/kubernetes/issues/40610).

But with auto-discovery of the node ASG by tags and the whole scaling up and down depending on access to the AWS API anyways, why not use the ec2metadata (https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/) to determine in which region we are running? Sure it should be possible to still configure this variable statically, but I believe this is then one less thing to configure when starting with cluster-autoscaling on AWS and allows the configuration to be even simpler, no matter in what region the Kubernetes Cluster lives ...

**Comment by zacharya** [comment]
It looks like this already exists, no? https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L70

I'm happy to contribute if you can confirm the need still exists and I'm missing something.

**Comment by Jeffwan** [comment]
This has been supported in v1.3.x and later released. Should be safe to close.
