### ISSUE TITLE
Release date of CA 1.2.3 and 1.3.2

### ISSUE THREAD

**Issue by Whitespirit0** [kubernetes/autoscaler#1220]
Hello,

Do you have an estimated release date for Cluster Autoscaler 1.2.3 and 1.3.2?

Thanks!

**Comment by aleksandra-malinowska** [comment]
Hi, 1.3.2 was released just now: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.3.2. 1.2.3 should be done today as well.

**Comment by Whitespirit0** [comment]
Ok great, thanks!

**Comment by aleksandra-malinowska** [comment]
And 1.2.3 is here as well: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.2.3
