### ISSUE TITLE
Use tide for PR merging

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/autoscaler#1239]
This is a [core repository](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#core-repositories).  As such, it [needs to use the same merge automation as the rest of the project](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-1)

I have a PR open that will address this at an org-wide level: https://github.com/kubernetes/test-infra/pull/9342.  It will:
- enable the approve plugin, to allow use of the `/approve` plugin
- enable the blunderbuss plugin, to assign reviews based on OWNERS files
- add all repos in the kubernetes org to tide's query

Can one of the repo maintainers here drop an LGTM (or objections) on the linked PR?  Alternatively, if I hear no objections by Monday 10am PT of next week, I will merge the PR.

**Comment by bskiba** [comment]
@mwielgus @MaciekPytel Do you have anything against this? Otherwise lets approve

**Comment by MaciekPytel** [comment]
@spiffxp Is this a complete list of changes? Or will we also need other things that are in k/k repo, like milestone + `priority/critical-urgent` requirement during freeze or release notes? I'd like to avoid too much overhead, given that this repo has just a handful of active contributors.

**Comment by spiffxp** [comment]
@MaciekPytel those merge requirements are specific to k/k, and a special case

This is an attempt to standardize on the same query and code review mechanisms all repos in kubernetes-client, kubernetes-csi and kubernetes-sigs currently use. If you'd like, you can submit follow-on PR's to customize the merge method used.
