### ISSUE TITLE
Autoscaler scaling down worker node with more pods than other candidate

### ISSUE THREAD

**Issue by zeelichsheng** [kubernetes/autoscaler#1240]
When autoscaler has multiple candidates for scaling down, it always picks the first candidate. It does not consider whether the cost of scaling down the first candidate is actually more than the second candidate.

For example, this is the log of autoscaler choosing a scaling-down candidate of two worker nodes. Worker node A has much more pods than node B. However, worker node A was chosen to be removed. This causes more disruption than scaling down node B:

> I0911 22:08:43.688940       1 cluster.go:80] Fast evaluation: worker-A for removal
> I0911 22:08:43.689041       1 cluster.go:206] Pod default/server-foo can be moved to worker-B
> I0911 22:08:43.779866       1 cluster.go:206] Pod default/server-bar can be moved to worker-B
> I0911 22:08:43.780039       1 cluster.go:206] Pod default/vsx-foo can be moved to worker-B
> I0911 22:08:43.780084       1 cluster.go:206] Pod default/db-tunnel can be moved to worker-B
> I0911 22:08:43.780133       1 cluster.go:206] Pod default/vsx-bar can be moved to worker-B
> I0911 22:08:43.780172       1 cluster.go:206] Pod default/publisher-foo can be moved to worker-B
> I0911 22:08:43.780206       1 cluster.go:206] Pod default/publisher-bar can be moved to worker-B
> I0911 22:08:43.780276       1 cluster.go:206] Pod default/es can be moved to worker-B
> I0911 22:08:43.780343       1 cluster.go:111] Fast evaluation: node worker-A may be removed
> I0911 22:08:43.780380       1 cluster.go:80] Fast evaluation: worker-B for removal
> I0911 22:08:43.780414       1 cluster.go:206] Pod default/sync-to-tap can be moved to worker-A
> I0911 22:08:43.780472       1 cluster.go:206] Pod default/bitnami-sync can be moved to worker-A
> I0911 22:08:43.780489       1 cluster.go:111] Fast evaluation: node worker-B may be removed

> I0911 22:08:43.780532       1 static_autoscaler.go:335] worker-A is unneeded since 2018-09-11 21:58:40.585339203 +0000 UTC m=+3106664.381171299 duration 10m3.100336453s
> I0911 22:08:43.780575       1 static_autoscaler.go:335] worker-B is unneeded since 2018-09-11 21:57:50.289226383 +0000 UTC m=+3106614.085058506 duration 10m53.396449246s
> I0911 22:08:43.803429       1 scale_down.go:488] Scale-down: removing node worker-A, utilization: 0.125, pods to reschedule: default/server-foo,default/server-bar,default/vsx-foo,default/db-tunnel,default/vsx-bar,default/publisher-foo,default/publisher-bar,default/es

Can we improve autoscaler to make a better decision to avoid such situation?

K8S version: 1.10.2
Autoscaler version: 1.2.2

**Comment by bskiba** [comment]
@MaciekPytel

**Comment by MaciekPytel** [comment]
@losipiuk I think you suggested a way to improve this?

**Comment by losipiuk** [comment]
Yeah - I logged it as  https://github.com/kubernetes/autoscaler/issues/1070 

Yet number disruptions is just one axis to look at when we choose node to scale down. 
Actual design should also look at other things like:
 - money cost
 - impact on HA 
 - etc.

**Comment by losipiuk** [comment]
I will close this one as duplicate feel free to add extra comments to #1070.
