### ISSUE TITLE
cluster-autoscaler in AzureGermanCloud

### ISSUE THREAD

**Issue by geoxanadu** [kubernetes/autoscaler#1262]
I am trying to implement the cluster-autoscaler in a kubernetes cluster in the Azure German Cloud. While editing the yaml file I came across the value "provider". Typically "azure" is here provided. However, it seems that this does not work for the german cloud. Unfortunately I was not able to find the suitable flag for the german cloud. 
"AZUREGERMANCLOUD", "azuregermancloud" does not work either. It always leads to a CrashLoopBackOff. Any ideas what I might have overseen?

**Comment by aleksandra-malinowska** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@geoxanadu Please keep `--cloud-provider=azure` and add a new environment variable `ARM_CLOUD` to `AzureGermanCloud` for the CA deployment.

We should also document this in the docs.

**Comment by hans-permana** [comment]
Would be nice to also have the list of possible values for `--cloud-provider` values in the documentation. I myself am wondering what I should put when configuring autoscaler on my cluster (on Open Telekom Cloud infrastructure).

**Comment by feiskyer** [comment]
For azure, `--cloud-provider` should be configured as `azure` for all cases, including standard vmas, vmss, aks and acs.

**Comment by feiskyer** [comment]
let's close the issue since it's not active for a long time.

/close
