### ISSUE TITLE
As VPA evolves to beta features in release 1.12, the README and examples need to be updated.

### ISSUE THREAD

**Issue by warmchang** [kubernetes/autoscaler#1278]
ref: https://github.com/kubernetes/features/issues/21

I can implement these changes. :smiley:

**Comment by warmchang** [comment]
hold because of the revert PR https://github.com/kubernetes/kubernetes/pull/64890
wait PR https://github.com/kubernetes/kubernetes/pull/65279

**Comment by warmchang** [comment]
@bskiba Well, I understand that the implementation of CRD represents the decoupling of VPA api from kubernetes.
And the [PR #1327](https://github.com/kubernetes/autoscaler/pull/1327) which you submitted has already upgraded the definition of VPA api to beta1. So close the issue.
/close

**Comment by khrisrichardson** [comment]
@warmchang PR #1327 didn't address the subject of this issue, which was to update the README and examples to beta, both of which still reference the alpha version.

**Comment by bskiba** [comment]
True. We're working towards releasing the beta version soon, which will include updating examples and readmes. Expect something in the coming weeks.

**Comment by warmchang** [comment]
@khrisrichardson @bskiba Thank your for reply, and I am clear how VPA versions evolved now. :smiley:
