### ISSUE TITLE
node-group-auto-discovery no longer accepts multiple tags

### ISSUE THREAD

**Issue by ReillyProcentive** [kubernetes/autoscaler#1280]
We're running a Kubernetes 1.10.8 cluster in AWS (provisioned via KOPS) with the following flags:
```
--namespace=k8s-autoscaler
--v=4
--stderrthreshold=info
--cloud-provider=aws
--skip-nodes-with-local-storage=false
--expander=least-waste
--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler=enabled,KubernetesCluster=k8s.ourcluster.domain
```

This worked fine with Autoscaler 1.1.3, however when we upgrade to 1.2.3 it fails with the following error:
```
I0927 17:20:35.816328       1 cloud_provider_builder.go:72] Building aws cloud provider.
I0927 17:20:35.916130       1 request.go:481] Throttling request took 399.921532ms, request: GET:https://100.64.0.1:443/api/v1/services?limit=500&resourceVersion=0
F0927 17:20:35.916206       1 cloud_provider_builder.go:137] Failed to create AWS Manager: invalid key=value pair [tag k8s.io/cluster-autoscaler enabled, KubernetesCluster k8s.ourcluster.domain]
```

Looks like the behavior was changed by this commit:
53fc344ecabbad73c0063d065bc2223d43318033

**Comment by aleksandra-malinowska** [comment]
Sounds reasonable. Can you build 1.2 with cherry-pick and verify if it works before we merge it? None of the maintainers has access to AWS cluster to test this.

**Comment by ReillyProcentive** [comment]
@aleksandra-malinowska I've been running a build with that commit cherry-picked in since yesterday and can confirm that it both builds and works as expected.

**Comment by aleksandra-malinowska** [comment]
Great, thanks.
