### ISSUE TITLE
Installation on cloud provider other than AWS, GCP, or Azure

### ISSUE THREAD

**Issue by hans-permana** [kubernetes/autoscaler#1297]
Hi guys,

Is cluster autoscaler installation on a cloud platform other than AWS, GCP, or Azure supported? On the documentation it says that I have to set `cloudProvider` and I don't know what to put in my case. I am using Open Telekom Cloud (OTC).  

I tried not specifying `cloudProvider` and it defaulted to `aws` (and hence resulted in errors). Could someone give me an enlightenment?

**Comment by aleksandra-malinowska** [comment]
Cluster Autoscaler doesn't have any code for interacting with Open Telecom Cloud, so it's not supported out-of-the-box. What you can do is add this by implementing [CloudProvider interface](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go), build your own release with it, and run this in your cluster. In the future, hopefully this will be made a lot easier by Cluster API.

**Comment by hans-permana** [comment]
OTC uses OpenStack under the hood, so the resolution of this issue https://github.com/kubernetes/autoscaler/issues/734 will solve my problem too. Closing this issue now. Thank you for the info @aleksandra-malinowska!
