### ISSUE TITLE
FailedToScaleUpGroup with version 1.3.3

### ISSUE THREAD

**Issue by hadr10** [kubernetes/autoscaler#1304]
Hello,

when i tested new version 1.3.3 i got error message during scaling:
Events:
  Type     Reason                Age              From                Message
  ----     ------                ----             ----                -------
  Warning  FailedToScaleUpGroup  1m (x2 over 7m)  cluster-autoscaler  Scale-up failed for group agentpool: containerserv
ice.ManagedClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.Ma
nagedClusterProperties.AadProfile.ServerAppSecret constraint=Null value=(*string)(nil) details: value can not be null; required parameter

With version 1.3.1 it works fine.

Thank you,
HH

**Comment by aleksandra-malinowska** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
Fixed in https://github.com/kubernetes/autoscaler/pull/1415.
/close
