### ISSUE TITLE
How to add customized kubernetes predicate

### ISSUE THREAD

**Issue by gongguan** [kubernetes/autoscaler#1311]
Autoscaler can't get some predicates which configured in kube-scheduler, such as PodFitsHostPorts, HostName, etc.
It seems that autoscaler only get predicate in priorityPredicates and k8s defaultPredicate(in cluster-autoscaler/simulator/predicates.go). Can predicates be customized?
`var priorityPredicates = []string{"PodFitsResources", "GeneralPredicates", "PodToleratesNodeTaints"}`
`predicateMap, err := schedulerConfigFactory.GetPredicates(provider.FitPredicateKeys)`

**Comment by aleksandra-malinowska** [comment]
priorityPredicates is just a set of predicates that will be run first, before the rest. All default predicates of scheduler from matching Kubernetes release are used. In particular, we have a couple of end-to-end tests relying on PodFitsHostPorts, which are passing. Same for using node selectors or affinity.

It isn't possible to use a custom set, so if you are extending scheduler with your own predicates (not in kubernetes/kubernetes), Cluster Autoscaler won't know about these.

Can you please describe where the observed behavior doesn't match this expectation? It'll be easier to debug the problem if we know it.

**Comment by gongguan** [comment]
@aleksandra-malinowska Thank you for your explanation. I didn't know predicates such as PodFitsHostPorts can be done by GeneralPredicates at first. I think this issue can be closed.

**Comment by aleksandra-malinowska** [comment]
No problem, glad to help.
