### ISSUE TITLE
Feature Request: Allow individual values of scale-down-utilization-threshold for CPU and memory

### ISSUE THREAD

**Issue by frittentheke** [kubernetes/autoscaler#1317]
When adjusting scale down limits it's far less risky to go full on Mad Max on the CPU as a resource than it is when talking about memory: When you run out of CPU everything becomes slower, when running out of memory things begin to crash.

Currently the cluster-autoscaler does not allow individual values for CPU and memory, _scale-down-utilization-threshold_ is always affecting both using the one with the higher value to determine if it can scale down more nodes. I suggest to allow for both resources to be configured to a different level, i.e. to allow a CPU headroom of only 10% while still only scaling down when there is more than 50% for memory still left. 

This would not be a breaking change, nobody is forced to move away from one value for both. I simply believe some workloads differ greatly in their required headroom of CPU and memory. A more flexible configuration allows to run those clusters more efficiently in regards to cluster scaling.

**Comment by aleksandra-malinowska** [comment]
Sounds reasonable to me, with a caveat that we already have too many parameters which are hard to tweak. @MaciekPytel, WDYT?

**Comment by losipiuk** [comment]
Sounds reasonable to me. 

If you are preparing a PR please just leave old configuration parameter which would serve as default value for the cpu/memory specific ones.

**Comment by frittentheke** [comment]
@aleksandra-malinowska may I kindly ask if you see this feature to be added?
If not by yourself - would you accept a PR then?

**Comment by MaciekPytel** [comment]
This is partly implemented by https://github.com/kubernetes/autoscaler/pull/3789. What will remain after it is merged will be adding integration for cloud providers.

**Comment by frittentheke** [comment]
@losipiuk  @aleksandra-malinowska @MaciekPytel do you see any chance this feature could be discussed again and how this could be implemented without cluttering the already configuration with more and more settings.
