### ISSUE TITLE
Allow scaling to/from 0 on AWS

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#132]
Follow up of #43 on AWS.

cc: @mumoshu @7chenko

**Comment by ryanwalls** [comment]
I would be interested in implementing this... but not sure how we would get over the technical hurdle that AWS doesn't provide an API for describing instances.  So not sure how we would know which ASG to scale up unless we had the user pass in the specs for the instances.  Thoughts or ideas @mwielgus?

**Comment by mwielgus** [comment]
What about launchconfig (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html)?

Please check https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/min_at_zero_gcp.md for a description on how we do it on GCP (and https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/gce/gce_cloud_provider.go#L251 for code)

**Comment by mumoshu** [comment]
@ryanwalls Hi, thanks for your interest on implementing this 👍 

Please also see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/gce/gce_manager.go#L308-L324.

Probably we need to have a map whose keys are EC2 instance types and values are pairs of num cpu cores + memory size so that it can be used to create a template node info from the instance type specified in the launch config of an auto-scaling group.

**Comment by mumoshu** [comment]
If you'd like to automate the generation of such map, I'd suggest utilizing [AWS Price List API](https://aws.amazon.com/jp/blogs/aws/new-aws-price-list-api/).

One of the lists produced by the API is the list of ec2 instance type info composed of num vcpus(cores in k8s), memory size, instance type name, etc.

http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html#download-the-offer-index

Beware that:
* There is one list per region
* The ec2 list is approximately 100MB in size. So it would not make sense to fetch the list at runtime :)

Perhaps adding out build script `go generate cloudprovider/aws` to trigger something like `go run ec2_instance_types_gen.go` which fetches a list for each aws region to finally generate `ec2_instance_types.go` containing the map would be nice.

Just my two cents..

**Comment by MaciekPytel** [comment]
I have discussed with @sethpollack on slack and he said he's working on this issue. Removing 'help wanted' label.

**Comment by ryanwalls** [comment]
@sethpollack let me know if you need any help.  Happy to implement subsections, review, or just be a 2nd pair of eyes on design.

**Comment by sethpollack** [comment]
Thanks will do. 

I can pull the cpu/mem from the price list, but I don't think there is a way to pull the node labels and taints. One option would be to add the node labels as tags on the ASG and then pull them from there.
