### ISSUE TITLE
Azure cluster autoscaler upgrade all virtual machines in vmss

### ISSUE THREAD

**Issue by heltondd** [kubernetes/autoscaler#1329]
When image is changed in vmss, cluster autoscaler execute upgrade in all virtual machines in vmss at same time, causing indisponibilty.

**Kubernetes 1.10.5**
**Cluster-autoscaler: 1.2.2**

**luster-autoscaler log:**
....
I1017 16:52:06.296148       1 utils.go:456] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I1017 16:52:06.296471       1 scale_up.go:59] Pod default/kuard-79d85cc498-sbgs6 is unschedulable
I1017 16:52:06.315470       1 scale_up.go:199] Best option to resize: k8s-small-23489316-vmss
I1017 16:52:06.315509       1 scale_up.go:203] Estimated 1 nodes needed in k8s-small-23489316-vmss
I1017 16:52:06.315523       1 scale_up.go:292] Final scale-up plan: [{k8s-small-23489316-vmss 5->6 (max: 10)}]
I1017 16:52:06.315535       1 scale_up.go:344] Scale-up: setting group k8s-small-23489316-vmss size to 6
I1017 16:56:39.759928       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2018-10-17 16:57:39.759919743 +0000 UTC
I1017 16:56:40.139878       1 utils.go:456] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I1017 16:56:40.140395       1 scale_up.go:59] Pod default/kuard-79d85cc498-tf7n6 is unschedulable
I1017 16:56:40.140411       1 scale_up.go:59] Pod default/kuard-79d85cc498-7rsd9 is unschedulable
I1017 16:56:40.140415       1 scale_up.go:59] Pod default/kuard-79d85cc498-h2cln is unschedulable
I1017 16:56:40.322798       1 scale_up.go:199] Best option to resize: k8s-small-23489316-vmss
I1017 16:56:40.322832       1 scale_up.go:203] Estimated 2 nodes needed in k8s-small-23489316-vmss
I1017 16:56:40.322847       1 scale_up.go:292] Final scale-up plan: [{k8s-small-23489316-vmss 6->8 (max: 10)}]
I1017 16:56:40.322857       1 scale_up.go:344] Scale-up: setting group k8s-small-23489316-vmss size to 8
I1017 17:06:09.556365       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2018-10-17 17:07:09.556355068 +0000 UTC
I1017 17:06:10.111621       1 utils.go:456] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I1017 17:06:10.111979       1 static_autoscaler.go:280] No unschedulable pods
....
**Scale Node: "Create or Upgrade Virtual Machine Scale Set"  initiate by clientid used by cluster autoscaler**

JSON:
....
"operationName": {
        "value": "Microsoft.Compute/virtualMachineScaleSets/write",
        "localizedValue": "Create or Update Virtual Machine Scale Set"
    },
    "resourceGroupName": "k8s",
    "resourceProviderName": {
        "value": "Microsoft.Compute",
        "localizedValue": "Microsoft.Compute"
    },
    "resourceType": {
        "value": "Microsoft.Compute/virtualMachineScaleSets",
        "localizedValue": "Microsoft.Compute/virtualMachineScaleSets"
    },
    "resourceId": "/subscriptions/xxxx/resourcegroups/k8s/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-small-23489316-vmss",
    "status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
    },
....
**Next Log is "Manual Upgrade Virtual Machine Scale Set" initiate by clientid used by cluster autoscaler**

JSON:
.....
operationName": {
        "value": "Microsoft.Compute/virtualMachineScaleSets/manualupgrade/action",
        "localizedValue": "Manual Upgrade Virtual Machine Scale Set"
    },
    "resourceGroupName": "k8s",
    "resourceProviderName": {
        "value": "Microsoft.Compute",
        "localizedValue": "Microsoft.Compute"
    },
    "resourceType": {
        "value": "Microsoft.Compute/virtualMachineScaleSets",
        "localizedValue": "Microsoft.Compute/virtualMachineScaleSets"
    },
    "resourceId": "/subscriptions/xxx/resourceGroups/k8s/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-small-23489316-vmss",
    "status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
....

**VMSS Upgrade Policy:**
az vmss show -g k8s -n k8s-small-23489316-vmss -o json | grep -i upgrade
  "upgradePolicy": {
    "automaticOsUpgradePolicy": {
      "enableAutomaticOsUpgrade": false
    "rollingUpgradePolicy": null
          "autoUpgradeMinorVersion": true,
          "autoUpgradeMinorVersion": true,

**Comment by aleksandra-malinowska** [comment]
> When image is changed in vmss, cluster autoscaler execute upgrade in all virtual machines in vmss at same time, causing indisponibilty.

I'm not sure how Azure cloud provider works specifically, but Cluster Autoscaler's logic doesn't perform any upgrades of nodes. If I were to guess what happened, I'd say upgrade was probably performed by some VMSS controller (outside of Cluster Autoscaler) in a way that caused nodes to become temporarily unready (or otherwise unusable), to which Cluster Autoscaler responded by adding more nodes.

cc @feiskyer

**Comment by heltondd** [comment]
@aleksandra-malinowska I understanding, but log of VMSS show manual upgrade initiaded by client-id (cli-kubernetes) used per Cluster Autoscaler after added more nodes.

In Azure Portal - Acitivity log of VMSS
Operation Manual Upgrade was the cause of unavailability

| Operation Name | Timestamp | Event initiated by |
| -------------------| -------------| ------------------- |
|Create or Update Virtual Machine Scale Set | Wed Oct 17 2018 13:56:29 GMT-0300 | cli-kubernetes |
|Manual Upgrade Virtual Machine Scale Set | Wed Oct 17 2018 14:06:10 GMT-0300 | cli-kubernetes |

I opened ticket on Azure Cloud to investigate.

**Comment by feiskyer** [comment]
@heltondd CA invokes Azure's `VirtualMachineScaleSetsClient.CreateOrUpdate()` API for updating VMSS instance numbers. I think this is why `Create or Update Virtual Machine Scale Set` is shown in the logs.

The other log of `Manual Upgrade Virtual Machine Scale Set` is not from CA, but seems from Kubernetes cloud provider. Kubernetes cloud provider would invoke instance upgrades for adding them to the backends of Azure Load Balance. Could you verify whether new services with type `LoadBalancer` created then?

**Comment by heltondd** [comment]
> @heltondd CA invokes Azure's `VirtualMachineScaleSetsClient.CreateOrUpdate()` API for updating VMSS instance numbers. I think this is why `Create or Update Virtual Machine Scale Set` is shown in the logs.
> 
> The other log of `Manual Upgrade Virtual Machine Scale Set` is not from CA, but seems from Kubernetes cloud provider. Kubernetes cloud provider would invoke instance upgrades for adding them to the backends of Azure Load Balance. Could you verify whether new services with type `LoadBalancer` created then?

No new services was created or updated.

**Comment by feiskyer** [comment]
@heltondd Thanks for the feedback. Could you send the ticket number privately? (e.g. on slack) I need to dig more why this is happening.

**Comment by heltondd** [comment]
> @heltondd Thanks for the feedback. Could you send the ticket number privately? (e.g. on slack) I need to dig more why this is happening.

Hi @feiskyer, Ronald Freitas @rofreitas sent you in the slack.

**Comment by sylr** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/71594 I believe

**Comment by alexeldeib** [comment]
@feiskyer This is fixed in 1.15 as of https://github.com/kubernetes/kubernetes/pull/76656, right?

**Comment by feiskyer** [comment]
Right, it has been fixed in the Kubernetes upstream. Let's close this issue.

/close
