### ISSUE TITLE
Review Azure cloud provider

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#133]
Mirror issue in kubernetes/kubernetes : https://github.com/kubernetes/kubernetes/issues/47511

**Comment by saada** [comment]
I don't mind working on this with some guidance from the experts.

**Comment by MaciekPytel** [comment]
@agolomoodysaada also mentioned being interested on kubernetes/kubernetes#47511. You may want to sync up to avoid doing the same work twice.

**Comment by masroorhasan** [comment]
+1 I'm willing to help out here as well :)

**Comment by djsly** [comment]
+1 We will be starting soon to work on this as well, with a vanilla k8s cluster in mind (not deployed using ACS)

**Comment by saada** [comment]
How about [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/en-us/blog/introducing-azure-container-service-aks-managed-kubernetes-and-azure-container-registry-geo-replication/)? 
Does this change the scope of the work here?
