### ISSUE TITLE
Question : Autoscaler to add two nodes (instead of 1) when scaling up on AWS

### ISSUE THREAD

**Issue by anshrma** [kubernetes/autoscaler#1338]
Looking for guidence/configuration/if feasible currently, for the autoscaler to add two nodes instead of one on AWS ?

**Comment by aleksandra-malinowska** [comment]
> Looking for guidence/configuration/if feasible currently, for the autoscaler to add two nodes instead of one on AWS ?

Can you explain in a bit more detail what you want to achieve? Sth like overprovisioning (have one extra node at any time), or making sure your pods can be spread across at least 2 nodes?
