### ISSUE TITLE
autoscaler 1.1.1 failed to detect changed ASG max size

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/autoscaler#1342]
We had a situation today where autoscaler 1.1.1 on a 1.9.6 k8s cluster refused to scale up a node group because it was at its limit. This puzzled us as we'd just added 30 nodes to the limit. After a couple of hours of this we restarted the autoscaler and it correctly resized the ASG at that point.

**Comment by Jeffwan** [comment]
@rbtcollins could you give more details on what kind of limitation? It would be better if you can attach full loop logs of your autoscaler

**Comment by tsmgeek** [comment]
I had similar but on v1.1.0.
It seems that it is not refreshing the AWS ASG max capacity, ie if i start autoscaler now it gets the ASG setup but does not seem to update this value at regular intervals.

**Comment by Jeffwan** [comment]
@tsmgeek True. This has been fixed probably after v1.1.1. Let me check code difference and if we need to have a change cherry-pick.
