### ISSUE TITLE
Does cluster-autoscaler need to support "out-of-tree" cloud providers? 

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/autoscaler#1345]
To be consistent with kubernetes/kubernetes, maybe it's time to consider an "out-of-tree" cloud provider model. Or at the very least, have each cloud-provider's implementation of the autoscaler in their respective repos (https://github.com/kubernetes/cloud-provider-gcp for GCE, https://github.com/kubernetes/cloud-provider-aws for AWS, etc) and have this repo import them. 

cc @mwielgus

**Comment by ringtail** [comment]
@andrewsykim agree!

**Comment by MaciekPytel** [comment]
CA does a ton of calls to cloud provider code and I suspect trying to move it out of the binary would require significant amount of work to avoid huge performance regression. I don't know of anyone trying to do it, so I don't think it's very likely to happen anytime soon. 

On the pro-side:
* With https://github.com/kubernetes/autoscaler/pull/1319 you can now build CA image with just a single cloudprovider compiled in. 
*  There is an ongoing effort to integrate CA with Cluster API ( https://github.com/kubernetes/enhancements/issues/609). AFAIK Cluster API already has out-of-tree cloudproviders, so we may be able to leverage those implementations without significant changes to CA itself.
