### ISSUE TITLE
Azure Fails to scale up nodegroup after setting new "Min"

### ISSUE THREAD

**Issue by damienwebdev** [kubernetes/autoscaler#1348]
I've updated the "min" on a deployment of cluster autoscaler on AKS from "4" to "6".

Not only did it not immediately start to scale up `2` new nodes to accomodate the request, now, when I try to apply pod cpu pressure to attempt to scale up nodes I get

```
Warning  FailedToScaleUpGroup  15s   cluster-autoscaler  Scale-up failed for group agentpool: Target size 5 requested outside Max: 10, Min: 6
```

It seems that it won't scale up to "min" even if told to. I've tried cluster-autoscaler v1.3.3 and cluster-autoscaler v1.2.2

**Comment by damienwebdev** [comment]
/remove-lifecycle rotten

cc: @feiskyer @aleksandra-malinowska

**Comment by nilo19** [comment]
Working on it.

/assign
