### ISSUE TITLE
Reservation mode in autoscaler.

### ISSUE THREAD

**Issue by ringtail** [kubernetes/autoscaler#1359]
I try to design the reservation mode in autoscaler to guarantee the speed of scaling up nodes. I think the key words of reservation is how to describe the workloads in the proper way. Maybe I can add a options like `--workloads-reservation` and pass an array such as `["4core8mem1gpu*10" ,"1core2mem0gpu"].  And we will try to simulate the pod to cluster in autoscaler. If the pod is unscheduled then we will follow the scale up logic below.

What's your opinion about this?

**Comment by ringtail** [comment]
@mwielgus

**Comment by aleksandra-malinowska** [comment]
What do you mean by "reservation mode"? Something like keeping spare resources in the cluster (overprovisioning)? If so, you can already do it with so-called "balloon" pods - essentially, pause containers with very low priority, which will be preempted to schedule a pod with higher priority. It's described in more details in FAQ: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler

**Comment by ringtail** [comment]
@aleksandra-malinowska cool! Thanks bro!

**Comment by bskiba** [comment]
Hi @ringtail, thanks for showing interest with cluster autoscaler. Please be mindful when referring to our contributors as "bro". We do have female core contributors here. Thanks!

**Comment by ringtail** [comment]
@bskiba Sorry.
