### ISSUE TITLE
Question : Configuration for Autoscaling in two Availability zones - AWS and EKS

### ISSUE THREAD

**Issue by anshrma** [kubernetes/autoscaler#1368]
Here is my scenario (on AWS and on EKS)

Have two ASGs, one creates nodes in us-east-1a and another in us-east-1b.
Here is how i install the cluster autoscaler

helm install --set autoDiscovery.clusterName=${CLUSTER_NAME} --set awsRegion=us-east-1  --set sslCertPath=/etc/kubernetes/pki/ca.crt --set rbac.create=true --set extraArgs.balance-similar-node-groups=false  --set cloud-provider=aws --name cluster-autoscaler stable/cluster-autoscaler --namespace kube-system

I have the following tags on both of the ASGs

k8s.io/cluster-autoscaler/enabled = kubernetes.io/cluster/${CLUSTER_NAME} 

Goal : Pods have two replicas and with necessary affinity in place, i am able to indeed spread the two replicas across the two ASGs (and hence two AZs).

Scenario :  When there is a scale up event due to addition of more application, only one node is added in either of the ASGs and now the two replicas of the application go on the same newly added node.

Question : Is there any configuration i can change, which ensures that nodes are added to both the ASGs instead of only one ???

**Comment by aleksandra-malinowska** [comment]
Cluster Autoscaler doesn't consider soft affinity, and hard pod affinity tends to kill performance (but can be used if you're OK with slowness). At large deployment and cluster sizes, we find that the best-effort approach based on balancing works well enough and is pretty resilient. But there are no guarantees at really small sizes that everything won't end up in the same place.

If it only adds one node, it means both pods fit there. Do you want to have at most 1 replica of this application on any node, or just spread as evenly as possible? If the former, quick and dirty hack would be to request a fixed port for the pods. Then the pods never end up one the same node, performance shouldn't be affected, and with balancing enabled (see below) and adding 2 nodes it's likely they'll be in different zones. Note that if the groups are already imbalanced, e.g. 3 nodes in zone A and 5 nodes in zone B, both new nodes will go the same zone, B.

> --set extraArgs.balance-similar-node-groups=false

Setting this parameters to false means than during scale-up, all requested nodes will be in the same group. If you set it to true, when adding 2 or more nodes CA will try to spread them across similar ASG, which usually means across zones.
