### ISSUE TITLE
Autoscaling doesn't work with new versions Cluster Autoscaler 1.3.3 and 1.3.4

### ISSUE THREAD

**Issue by hadr10** [kubernetes/autoscaler#1369]
Hello,

azure aks doesn't work with new cluster autoscaler 1.3.3 and 1.3.4. With 1.3.1 it works good. https://github.com/kubernetes/autoscaler/releases
Error from autoscaler:
Warning FailedToScaleUpGroup 2m cluster-autoscaler Scale-up failed for group agentpool: containerservice.Managed
ClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedCluste
rProperties.AadProfile.ServerAppSecret constraint=Null value=(*string)(nil) details: value can not be null; required parameter

Thank you,
Honza

**Comment by MaciekPytel** [comment]
cc: @feiskyer

**Comment by feiskyer** [comment]
@kkmsft Could you take a look at this?

**Comment by feiskyer** [comment]
Fixed in the https://github.com/kubernetes/autoscaler/pull/1415.
