### ISSUE TITLE
Please release 1.2.4 with r5 support

### ISSUE THREAD

**Issue by gwohletz** [kubernetes/autoscaler#1387]
Recently 1.3.4 was released and includes support for a couple new aws instance types (r5, z1), it would be greatly appreciated if a similar release 1.2.4 could be made for those of us that will be still using kubernetes 1.10 for at least another couple months.

**Comment by gwohletz** [comment]
If this isn't going to be fixed for a while, it would be super useful to have a release that includes the r5 support.

**Comment by Jeffwan** [comment]
Looks like #1478  resolve this issue?

**Comment by spronin-aurea** [comment]
Is it possible to release only with r5 support?

**Comment by spronin-aurea** [comment]
> Are you saying that you don't want the additional instance types beyond the "r5" family to be recognized by the autoscaler?

@seh if there is a PR already for all the instances new than r5 - great, if not - I would certainly want to add just r5 support and get working autoscaler back.

**Comment by seh** [comment]
I'm confused. Doesn't #1478 already include all the r5 family? Don't look at [the types added there](https://github.com/kubernetes/autoscaler/pull/1478/files#diff-e4d58ad5096a877c286c642a21646263); look at [the types that are already there](https://github.com/jeruane/autoscaler/blob/ce9da03ae704d6b75fc9a003e5303a2482e01541/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L786-L827).

Is the problem that this change has been committed, but there hasn't been a release that includes it?

**Comment by spronin-aurea** [comment]
Exactly. It is not released yet. We have compiled our own version with this fix, but would be nice to have non-custom version.

**Comment by Jeffwan** [comment]
@aleksandra-malinowska  I'd like to help on v1.2.4 release. Looks like a few people #1556 want this change on Kubernetes 1.10. But I don't have permission. If there's a way for me to help, feel free to let me know.  Thanks!

**Comment by aleksandra-malinowska** [comment]
Released 1.2.4: https://github.com/kubernetes/autoscaler/releases/tag/1.2.4

@Jeffwan thanks! We haven't migrated to fully automated cloud builds from github yet, so the process is kind of tricky for now. I think there's a release engineering effort to fix it, but there are no guidelines for setting it up for add-on components yet.

**Comment by Jeffwan** [comment]
@aleksandra-malinowska Thanks! The issue has a `good first issue` and then I thought I might be easy for contributors to make it. Now I get it.

**Comment by aleksandra-malinowska** [comment]
Right, sorry, this referred to fixing flaking tests.
