### ISSUE TITLE
AWS autoscaler (possibly) doesn't update records that are accessed by nginx-lego

### ISSUE THREAD

**Issue by OndrejKu** [kubernetes/autoscaler#1429]
Hey guys, I'm having troubles with nginx-lego (I know it's deprecated) and node autoscaler. I had to scale up manually through hpa and patching temporarily minReplicas to high number. All scaled well, new nodes were added because of pod increase. After the traffic spike I set the number back to normal (which is really low) and I can see a lot of bad gateway 502 errors. After I examinated nginx-lego pod's log, I was able to see that plenty of requests were going to pods that aren't there anymore (connection refused or No route to host). Any idea on what could be wrong?

**Comment by aleksandra-malinowska** [comment]
This doesn't seem to be related to autoscaling at all, and I'm not sure we can help you. If the pods are really gone and kube-apiserver doesn't list them anymore, I'd try asking in nginx community.
