### ISSUE TITLE
Updater crashed after creating VPA with example/hamster deployment 

### ISSUE THREAD

**Issue by Rajat-0** [kubernetes/autoscaler#1430]
Updater showing "CrashLoopBackOff" status after I created vpa and pods with "example/hamster.yaml".
Updater Logs:
 I1121 05:51:38.583230       7 flags.go:52] FLAG: --alsologtostderr="false"
I1121 05:51:38.583999       7 flags.go:52] FLAG: --eviction-tolerance="0.5"
I1121 05:51:38.584039       7 flags.go:52] FLAG: --httptest.serve=""
I1121 05:51:38.584063       7 flags.go:52] FLAG: --log-backtrace-at=":0"
I1121 05:51:38.584093       7 flags.go:52] FLAG: --log-dir=""
I1121 05:51:38.584117       7 flags.go:52] FLAG: --logtostderr="false"
I1121 05:51:38.584147       7 flags.go:52] FLAG: --min-replicas="2"
I1121 05:51:38.584170       7 flags.go:52] FLAG: --stderrthreshold="0"
I1121 05:51:38.584192       7 flags.go:52] FLAG: --updater-interval="1m0s"
I1121 05:51:38.584224       7 flags.go:52] FLAG: --v="4"
I1121 05:51:38.584248       7 flags.go:52] FLAG: --vmodule=""
I1121 05:51:38.584278       7 main.go:45] Vertical Pod Autoscaler 0.2.0 Updater
I1121 05:51:38.669950       7 reflector.go:202] Starting reflector *v1alpha1.VerticalPodAutoscaler (1h0m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/api.go:83
I1121 05:51:38.670031       7 reflector.go:240] Listing and watching *v1alpha1.VerticalPodAutoscaler from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/api.go:83
I1121 05:51:38.869940       7 shared_informer.go:123] caches populated
I1121 05:51:38.869984       7 api.go:87] Initial VPA synced successfully
I1121 05:51:38.870168       7 reflector.go:202] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:155
I1121 05:51:38.870220       7 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:155
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe572b3]

**Comment by bskiba** [comment]
@Rajat-0 Are you running the 0.2.0 version.

**Comment by Rajat-0** [comment]
@bskiba I am running the master version.

**Comment by bskiba** [comment]
I just built and deployed VPA from the master, created the example/hamster.yaml and can't seem to reproduce this. I wonder if there is anything specific about your setup?

**Comment by bskiba** [comment]
Any news? We have 0.3.0 version out now, which should not have this issue.

**Comment by Rajat-0** [comment]
Its working fine with latest versiom.
