### ISSUE TITLE
Cluster Autoscaler is not scaling the nodes when not using `--cloud-provider=aws` in kubelet configuration

### ISSUE THREAD

**Issue by vishalcs05** [kubernetes/autoscaler#1435]
Kubernetes Version: `v1.11.2`  
Cluster Autoscaler Version: `v1.2.2`  

Cluster Autoscaler is not scaling the nodes when not using `--cloud-provider=aws` in kubelet configuration, getting below logs in cluster autoscaler.

```
I1122 12:36:46.798580       1 scale_up.go:59] Pod default/my-application-56dc8d4bf5-j5jzs is unschedulable
E1122 12:36:46.798600       1 static_autoscaler.go:304] Failed to scale up: failed to build node infos for node groups: Wrong id: expected format aws:///<zone>/<name>, got
I1122 12:36:48.516201       1 leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
```
Though it recognised the autoscaling group which I passed in autoscaler deployment yaml.
```
I1122 09:26:53.892573       1 auto_scaling_groups.go:153] Regenerating instance to ASG map for ASGs: [k8s-test-workers]
I1122 09:26:54.693002       1 leaderelection.go:199] successfully renewed lease kube-system/cluster-autoscaler
I1122 09:26:55.023658       1 aws_manager.go:241] Refreshed ASG list, next refresh after 2018-11-22 09:27:55.023651853 +0000 UTC
I1122 09:26:55.023787       1 auto_scaling_groups.go:153] Regenerating instance to ASG map for ASGs: [k8s-test-workers]
I1122 09:26:55.028800       1 main.go:228] Registered cleanup signal handler
```
Options I gave in cluster autoscaler deployment are below
       
         command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=random
            - --max-node-provision-time=40m
            - --scan-interval=40s
            - --scale-down-unneeded-time=5m
            - --nodes=0:10:k8s-test-workers

Is using `--cloud-provider` necessary in kubelet config for autoscaler to work ? if not, can somebody tell me what I am missing in configuration.

**Comment by aleksandra-malinowska** [comment]
> Is using --cloud-provider necessary in kubelet config for autoscaler to work ? if not, can somebody tell me what I am missing in configuration.

It is. More precisely, Cluster Autoscaler needs Node objects to have ProviderId field set to a unique resource identifier of the machine running that node (in your case, `aws:///<zone>/<name>`, as the error states). This is usually done by cloud provider component for Kubernetes (either built-in or external). If you don't want to use it, you'll have to set this field in another way.

**Comment by vishalcs05** [comment]
thanks @aleksandra-malinowska will try to set it another way as dont want to give it in kubelet config.
