### ISSUE TITLE
Does autoscaler support dynamic config by updating the config map?

### ISSUE THREAD

**Issue by lvjing2** [kubernetes/autoscaler#1443]
Just as the title, I am curious about whether autoscaler support dynamic config via updating the config map, since it seems had been removed by #851 .

**Comment by losipiuk** [comment]
CA exposes `cluster-autoscaler-status` config map but it is used only for reporting CA status to the user. 
All the configuration is done via command line parameters.

**Comment by MaciekPytel** [comment]
The old option to update config via a separate configmap was dropped in the PR you linked, because there was a breaking bug in it for a year or more. Since no one ever complained about the bug we figured no one is using it anyway and we didn't want to keep a fundamentally broken feature.

**Comment by lvjing2** [comment]
Eh, I can understand your points. But for me, it is strange that no one using this feature especially in production env, I think we may need to add or delete some node groups(no auto discovery), increase the core and memory limitation as the system grows, could you show me some tips how can i achieve this without using config map?

**Comment by losipiuk** [comment]
This is probably far from being optimal but I guess you can add separate orchestration around CA and change the definition of POD which runs it over time. Each change will require CA restart of course yet it should not be a problem as CA handles that pretty well.

**Comment by aleksandra-malinowska** [comment]
My understanding was that auto-discovery won because it's so much easier to just configure the node group and have autoscaling work for it out of the box. And if you already have to update the autoscaling config separately, you can just as well update Cluster Autoscaler deployment with new groups and limits.

**Comment by lvjing2** [comment]
Ok, I see, we can restart the ca since it handle the gracefully terminating well if I want to change the configuration. thanks you all.

**Comment by deitch** [comment]
> Each change will require CA restart of course yet it should not be a problem as CA handles that pretty well

That won't work with auto-discovery, though, will it, especially with AWS? According to the docs, the min/max are as set by the AWS config (terraform, cloudformation, etc.). That means that I need to re-apply the above just to, e.g. change my max. I can change it if I use `--nodes=`, but that requires listing each group out.

Is there a way to combine auto-discovery with config-driven updates of min/max to an ASG?
