### ISSUE TITLE
Azure Scale Set - node labeling

### ISSUE THREAD

**Issue by spinus** [kubernetes/autoscaler#1452]
I have a set of specific worker nodes to scale and I have corresponding node selector on azure.

I get 
```
I1126 14:27:18.221788       1 scale_up.go:249] Pod XXX-6fbdd6b9b5-9w6tp is unschedulable
I1126 14:27:18.247845       1 utils.go:196] Pod XXX-6fbdd6b9b5-9w6tp can't be scheduled on k8sscaleset, predicate failed: GeneralPredicates predicate mismatch, cannot put XXX-6fbdd6b9b5-9w6tp on template-node-for-k8sscaleset-3970733359372029124, reason: node(s) didn't match node selector
```

I'm not sure what should I do to configure autoscaler to put labels on the nodes (azure scale set). How I do it?

**Comment by spinus** [comment]
For anybody looking at this.

The workaround is to prepare images for each "labelset" you plan with labels set in kubelet configuration and have different scaling sets with different images.

**Comment by left4taco** [comment]
@spinus Hi. Could you be more specific on the solution? I also ran into this problem and cannot figure out how to scale up from 0. 
(Scaling down to 0, or scale up from 1 to n works well though)

**Comment by spinus** [comment]
@left4taco my issue was not scaling above 1. I just wanted hosts to be labeled. In my case I just used few autoscaler configurations, each for different "type" of the machine I wanted instead of having them in 1 pool (because the labels can be provided in kubelet, I prepared few vm images with kubelet and different set of node labels for each machine type/scaling group I wanted).

**Comment by feiskyer** [comment]
https://github.com/kubernetes/autoscaler/pull/1982 is fixing this.
