### ISSUE TITLE
AWS: Failed to create AWS Manager

### ISSUE THREAD

**Issue by c4po** [kubernetes/autoscaler#1453]
Kubernetes: 1.11.4
CA: 1.3.4

tried the `cluster-autoscaler-one-asg.yaml` and `cluster-autoscaler-autodiscover.yaml`
getting error message like this.
```
I1127 00:45:11.243473       1 cloud_provider_builder.go:72] Building aws cloud provider.
E1127 00:45:11.243641       1 aws_manager.go:122] Failed to regenerate ASG cache: cannot autodiscover ASGs: MissingRegion: could not find region configuration
F1127 00:45:11.243667       1 cloud_provider_builder.go:137] Failed to create AWS Manager: cannot autodiscover ASGs: MissingRegion: could not find region configuration
```

did I miss anything?

**Comment by johanneswuerbach** [comment]
Looks like you tried the examples in master with version 1.3, which doesn’t support automatic region detection.

Could you try the 1.3 example https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.3/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml?

**Comment by c4po** [comment]
It works. thanks!
