### ISSUE TITLE
Vertical-pod-autoscaler is requesting more MEMORY than needed

### ISSUE THREAD

**Issue by luarx** [kubernetes/autoscaler#1458]
If I run the `hamster.yaml` example of vertical-pod-autoscaler, it schedules great the requested CPU (I have  tested it modifying the main command to see how VPA modifies the requested CPU).

The problem is that it **requests more memory than needed** (look at the picture). Do I have to configure anything else?
![image](https://user-images.githubusercontent.com/22997139/49157013-16642e00-f31f-11e8-8517-6483f532e7d4.png)

**Comment by kgolab** [comment]
Currently the 250 MiB you see is the default value of the lowest possible memory recommendation.
It can be changed with --pod-recommendation-min-memory-mb flag.

**Comment by luarx** [comment]
Oh nice! Thank you! :) Sorry, I hadn't seen this option before...

When I run the docker container with a different command line arguments **it doesn't show any log line** (probably I am doing something wrong):
```
command: ["/bin/sh"]
args: ["-c", "./recommender", "--v=4", "--stderrthreshold=info", "--prometheus-address=http://prometheus.monitoring.svc", "--pod-recommendation-min-memory-mb=100"]
```
But if I go inside the container I can see that it has received the arguments (**custom execution**):
```
root         1  0.0  0.0   4292   768 ?        Ss   15:41   0:00 /bin/sh -c ./recommender --v=4 --stderrthreshold=info --prometheus-address=http://prometheus.monitoring.svc --pod-recommendation-min-memory-mb=100
root         7  0.2  0.1 497664 28728 ?        Sl   15:41   0:00 ./recommender
```

And these are the processes which are created when I don't specify a custom command (**normal execution**):

```
root         1  0.0  0.0   4292   804 ?        Ss   15:44   0:00 /bin/sh -c ./recommender --v=4 --stderrthreshold=info --prometheus-address=http://prometheus.monitoring.svc
root         7  0.2  0.1 497664 28100 ?        Sl   15:44   0:00 ./recommender --v=4 --stderrthreshold=info --prometheus-address=http://prometheus.monitoring.svc
```

The only difference is that the **second process has more arguments** when it works correctly
What am I doing wrong?

**Comment by kgolab** [comment]
How exactly have you changed the command line arguments?
I just did locally the following change to vertical-pod-autoscaler/pkg/recommender/Dockerfile, rebuilt vpa-recommender and it returns 100 MB recommendation for RAM.
```diff
-CMD ./recommender --v=4 --stderrthreshold=info --prometheus-address=http://prometheus.monitoring.svc
+CMD ./recommender --v=4 --stderrthreshold=info --prometheus-address=http://prometheus.monitoring.svc --pod-recommendation-min-memory-mb=100
```

**Comment by luarx** [comment]
Yes, if I change the vpa-recommender Dockerfile and rebuild it, it works! :)
But if I change the command line arguments in `deploy/recomender-deployment.yaml` Kubernetes deployment file (so that I don't have to maintain my own Docker image), it doesn't work.

**Comment by kgolab** [comment]
I think I understand the problem now.
If you want to use `/bin/sh -c` please give recommender as a single parameter, like this:
```yaml
        command: ["/bin/sh"]
        args: ["-c", "./recommender --v=4 --stderrthreshold=info --prometheus-address=http://prometheus.monitoring.svc --pod-recommendation-min-memory-mb=100"]
```

Alternatively you could use:
```yaml
        command: ["./recommender"]
        args: ["--v=4", "--stderrthreshold=info", "--prometheus-address=http://prometheus.monitoring.svc", "--pod-recommendation-min-memory-mb=100"]
```

**Comment by luarx** [comment]
Yes!!! It has worked as you said.
I will close this issue then, thank you very much! 😃

**Comment by 97turbotalon** [comment]
If anyone else comes across this post, this is how I got around having to maintain my own docker image.
I also found that way more memory was being allocated to pods then was necessary.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
      - name: recommender
        image: k8s.gcr.io/vpa-recommender:0.3.0
        imagePullPolicy: Always
        command: [./recommender]
        args:
        - --v=4
        - --stderrthreshold=info
        - --pod-recommendation-min-cpu-millicores=25
        - --pod-recommendation-min-memory-mb=25
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - containerPort: 8080
