### ISSUE TITLE
Allow pod's graceful termination to override CA GracefulTermination 

### ISSUE THREAD

**Issue by vendrov** [kubernetes/autoscaler#147]
In a scenario when a PreStop duration is longer than 1 min (CA current default GracefulTermination time),
the pod will be killed in the middle of a "graceful shutdown". It might harm the user experience.
For example let's say that we would like to drain web-sockets connection and we decide that 20 min is enough time for the user to finish his task/action, we expect that setting the pod's graceful termination time to 20 will be enough, but currently it will just stop the socket right after 1 minute.

**Comment by mwielgus** [comment]
Than you for this report. We are aware of this issue and we are planning to fix it in K8S 1.8/CA 0.7.

**Comment by mwielgus** [comment]
cc: @MaciekPytel @aleksandra-malinowska

**Comment by vendrov** [comment]
@mwielgus This fix is temporary, since it doesn't consider the pod's graceful_terminatnion attribute. What if the container needs to be running more than 10min before termination?
