### ISSUE TITLE
vertical-pod-autoscaler - the way vpa recommender uses prometheus history cpu data

### ISSUE THREAD

**Issue by patrickshan** [kubernetes/autoscaler#1501]
when using prometheus as history data provider, how does VPA recommender calculate CPU recoomendation ? 

It seems currently it uses `container_cpu_usage_seconds_total` which is a counter but it doesn't seem to do any rate calculation based on it ? is this correct ? while for memory it uses a gauge metric `container_memory_usage_bytes` which makes sense

**Comment by patrickshan** [comment]
thanks @bskiba . I'd love to contribute back but I don't have a working setup with Prometheus at the moment. will do that when I have one.

**Comment by yashbhutwala** [comment]
I think this is fixed via #1824 and then fixed further by #3009 🔨
