### ISSUE TITLE
[cluster-autoscaler] Scale up based on Node Utilization

### ISSUE THREAD

**Issue by george-miller** [kubernetes/autoscaler#1503]
Hello, firstly I want to thank you for making this awesome autoscaler, it works so well and makes Kubernetes an even better platform (even though it was already the best).

The problem I am having is that it takes too long to provision new resources because CA waits until there is an unschedulable pod to trigger a scale up.  If CA scaled the cluster based on node resource utilization, it could preemptively scale the cluster and no pod would be left Pending in an unschedulable state unless a huge mass of pods arrived at the same time.  

This paradigm would make sense in a cluster like mine, where every pod must have resource requests and limits, because node utilization percent would be accurate.  In this way it would work a lot like a [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details), where the current metric value would be node utilization and the desired metric value would be a utilization percent that the admin sets, like 80%.  The equation would look like:
```
desiredNodes = ceil[currentNodes * ( currentUtilization / desiredUtilization )]
```
Maybe CA could implement both strategies, where it scales up either when a pod is unschedulable and a new node would help or when utilization is not at the desired percent.  

What do you think?  Is it a crazy idea?

**Comment by aleksandra-malinowska** [comment]
What cloud are you running on? Most of them have some sort of groups of instances which autoscale like you describe (for example, Managed Instance Groups on GCP). One thing that doesn't work out-of-the-box is that they tend to use actual resource utilization by default, so you may need to export a custom metric for your nodes (utilization in terms of requests) and use that as input.

**Comment by george-miller** [comment]
I am using amazon EKS with an ASG for my worker nodes.  Yeah they only have access to the ec2 metrics by default, so I could try to get some custom metrics in there for scaling and then adjust the autoscaler config so it doesn't scale the ASG down again.  I'll give that a try in a few weeks and post an update here afterward.  Thanks!

**Comment by calixwu** [comment]
You probably can use HPA  + CA.

**Comment by jkaniuk** [comment]
This FAQ entry could be of help:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler

**Comment by limbuu** [comment]
@george-miller  i am currently around the same problem. But my Kubernetes is in Google Cloud. I did lot of research but couldn't figure out to add customized metric for the autoscaler. I need my autoscaler to scale up the node when current node has used 80% of its resources. If you have work around the problem than would you mind to share?
