### ISSUE TITLE
scaling down node with running bare pods and nodes with safe-to-evict false pods as well

### ISSUE THREAD

**Issue by Deepak1100** [kubernetes/autoscaler#1508]
The whole Infra is running on AWS
I have tried setting annotation safe-to-evict = false and PDB as well. I have task schedule by airflow on Kube which is not controlled by aby Kube controller(airflow scheduler control them) and there nodes also getting scale down even though they are running there with above annotation and PDB as well and they are just bare pods but still. 
I can see in logs that CA is checking them and it is ignoring those nodes but when scale down happen some other nodes getting scale down.
and for me it is not even respecting --min-replica flag as well
I have launched the one ASG which spans instance in 2 AZs. it's in mumbai region.
scale up happen properly and its problem with scale down.
The termination policy of ASG is Default

**Comment by aleksandra-malinowska** [comment]
> I can see in logs that CA is checking them and it is ignoring those nodes but when scale down happen some other nodes getting scale down.

If CA logs state that these particular nodes are ignored and not scaled down, then it's very likely something else is deleting them. Are you 100% sure there is no other autoscaler operating on the cluster? In particular, please make sure autoscaling instances in ASG is disabled.

**Comment by Deepak1100** [comment]
@aleksandra-malinowska 
Yes. as I have setup whole cluster and other add-ons so I am 100% sure there is no other thing which is scaling it down
so there show in logs but I have seen suppose there are 3 replicas with annotation and logs only show 2 or 1, so this kind of things happen. some of the bare pods are not detected in logs as well.
and before logs (before 5-10 min of node goes down) there is no logs for those pods.
one thing I thought which is like CA is trying to delete 'A' node and it signal aws to delete 'A' node and aws 'Default' termination policy is creating some problem and deleting other pods.
is there is chances of something happening like this?

**Comment by aleksandra-malinowska** [comment]
Can you share the relevant part of the logs? It's hard to guess what may be the issue without more information.

**Comment by Deepak1100** [comment]
well, I think the issue is resolved after I suspended the AZRebalance process in aws ASG.
I will try to verify it on Monday.
