### ISSUE TITLE
Incorrect handling of condition based taints if TaintNodesByCondition is used

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/autoscaler#1515]
According to @aermakov-zalando in https://github.com/kubernetes/kubernetes/issues/72129
CA misbehaves if TainNodesByCondition is in use:

> The autoscaler itself doesn't treat these conditions in a special way, from what I understand by looking at the source code. This means that if the tolerations are not there, it'll spin up a new node, determine that the pods > can't run on it because of taints and happily create a new node instead of waiting for the node to be ready.

That needs to be verified and fixed if needed.

**Comment by aermakov-zalando** [comment]
We're migrating to 1.12, and this actually doesn't happen in practice. It looks like the actual state of unready nodes is ignored and a template node is substituted instead in https://github.com/kubernetes/autoscaler/blob/7f6344ef2a48fa64c9c0ae5a257f642eabdc0de5/cluster-autoscaler/core/scale_up.go#L288, so it works correctly.

**Comment by sanyu** [comment]
When using taints as node conditions, wouldn't the node still be **_Ready_** (at least for things like disk pressure, memory pressure...)?
Adding these taints doesn't doesn't change the status of the node and the user is allowed to ignore some of the Node's problems by adding the appropriate tolerations.

I added a random taint to a node in an ASG, this node was used as a template by the autoscaler so no Pods where able to run in this group (they didn't have the appropriate toleration), but the autoscaler decided not to spin up a new node in this group as it assumes every node will be identical to this special tainted node.

We haven't enabled TaintNodesByCondition yet, but based on this, I don't think this will work as expected, if the cluster-autoscaler happens to use a node that has been tainted as a template (the node is still **Ready** in some cases), will it decide that the entire group has this taint and therefore spinning up a new node is useless?

**Comment by SleepyBrett** [comment]
related: https://github.com/kubernetes/autoscaler/issues/1350

**Comment by aermakov-zalando** [comment]
@sanyu Good point! We run a fork that handles the templates more predictably, which is why we haven't noticed.

**Comment by vikaschoudhary16** [comment]
is not #1963 a complete fix for this issue?

**Comment by aermakov-zalando** [comment]
Yeah, #1963 looks like it fix the issue. This needs verification, however, and since we took a different approach in our internal fork, someone would need to test it.

**Comment by mvz27** [comment]
Have same issue in AWS cluster autoscaler 1.14.5.
Should this issue be fixed ??

**Comment by losipiuk** [comment]
> Have same issue in AWS cluster autoscaler 1.14.5.
> Should this issue be fixed ??

It was not cherry picked to any 1.14. The fix is in any CA 1.15+.

**Comment by losipiuk** [comment]
Fixed with #1963. Cherry-picked to 1.14 and 1.13
