### ISSUE TITLE
Question: Is it safe to run CAS 1.2.3 with AWS ASG with multi-type instances?

### ISSUE THREAD

**Issue by aly-aurea** [kubernetes/autoscaler#1519]
I am going to replace my AWS EKS production cluster workers ASG that uses a single instance type with the new ASG launch template that uses multiple types of EC2 instances.
I am already running a cluster in the test environment with this new setup, but I want to make sure that there are no concerns to run it before moving to production.

I use CAS v1.2.3 and EKS with k8s v1.10.3

**Comment by MaciekPytel** [comment]
CA is based on assumption that every node in NodeGroup (AWS ASG, GCP MIG, Azure VMSS, etc) is exactly identical (that's how CA predicts how a new node will look like). Having multiple instance types in a single ASG is not officially supported as of now. You can sort of hack it, but we give no guarantees and recommend against running such configs in prod.
 
You can find more details in discussion following https://github.com/kubernetes/autoscaler/issues/838#issuecomment-446179237.

**Comment by aly-aurea** [comment]
Thanks!
