### ISSUE TITLE
Cluster autoscaler fails to start

### ISSUE THREAD

**Issue by sorenmat** [kubernetes/autoscaler#153]
After removing the the pod I get the following error.
```
I0630 12:37:26.683009       1 leaderelection.go:248] lock is held by cluster-autoscaler-37505376-64n1p and has not yet expired
I0630 12:37:26.683032       1 leaderelection.go:185] failed to acquire lease kube-system/cluster-autoscaler
```
Tried to remove everything related to CA from the cluster, but it seems to be keep failing

**Comment by MaciekPytel** [comment]
Hi,
This looks like you still have a pod `cluster-autoscaler-37505376-64n1p` holding leader election lock (the lock should expire after ~15s after killing the pod as per defaults in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go#L69).

Can you provide more detail on how you run CA? Also can you provide output of `kubectl get pods --all-namespaces | grep autoscaler"?

Finally it may be faster to debug if you log on https://kubernetes.slack.com, room #sig-autoscaling than to exchange notes via github.

**Comment by mwielgus** [comment]
Leader election is implemented on top of endpoints. Something weird is going on there. 
Please attach `kubectl get endpoints --namespace=kube-system cluster-autoscaler -o yaml` output.
The most probable fix would be to just delete the forementioned

**Comment by sorenmat** [comment]
It's working now, I'm pretty sure it was because another pod was running in another namespace. Did take quite sometime to get the lock after deleting that pod though. Closing the issues.
Thanks for the quick response, awesome job !
