### ISSUE TITLE
Question:  what's the difference betwen Recorder and LogRecorder?  

### ISSUE THREAD

**Issue by zhaoar92** [kubernetes/autoscaler#1532]
I have a question about the code below, what's the difference betwen Recorder and LogRecorder?  

I can find the event log in configmap by using LogRecorder.Eventf().  But where's the event log by  Recorder.Eventf() ?  

```
type AutoscalingKubeClients struct {
	// Listers.
	kube_util.ListerRegistry
	// ClientSet interface.
	ClientSet kube_client.Interface
	// Recorder for recording events.
	Recorder kube_record.EventRecorder
	// LogRecorder can be used to collect log messages to expose via Events on some central object.
	LogRecorder *utils.LogEventRecorder
}
```

**Comment by bskiba** [comment]
LogEventRecorder is a wrapper around EventRecorder that logs autoscaler related events to configmap.
Recorder is a regular EventRecorder used to emit events about all other Kubernetes objects, for example pods. If you look at the codebase, all Eventf calls on recorder have a Kubernetes object as first argument. Example: https://github.com/kubernetes/autoscaler/blob/78513d064f34666d29cc67adb1537af30dd4ec80/cluster-autoscaler/processors/status/eventing_scale_up_processor.go#L41

**Comment by bskiba** [comment]
The events will be found on the corresponding object, in the case of the example, on the pod that triggered scale up.

**Comment by zhaoar92** [comment]
@bskiba  I see, you explained very clearly. Thanks.
