### ISSUE TITLE
Skipping node group ... max size reached

### ISSUE THREAD

**Issue by tmwtp** [kubernetes/autoscaler#1537]
Environment details:

K8s version - 1.10.7
Installer - Kops
cluster auto-scaler image - gcr.io/google-containers/cluster-autoscaler
Image version - v1.2.3 

Issue:

On heavy load on the cluster there was a need for new nodes to be ran but i got the following error in the auto-scaler logs:

> I1227 10:48:22.745330       1 scale_up.go:61] 30 other pods are also unschedulable
I1227 10:48:22.915535       1 scale_up.go:92] Upcoming 0 nodes
I1227 10:48:23.118126       1 scale_up.go:116] Skipping node group nodes.XXXXXXXX - max size reached
I1227 10:48:23.118148       1 scale_up.go:186] No expansion options

At the same time there were 10 nodes running in the ASG (nodes.XXXXXXXX) and the maximum value was 50 (40 more nodes can be started in the ASG) yet per the log the auto-scaler says it has reached the maximum nodes in the ASG.

I had no issue going to the AWS console and increase the number of desired nodes but the auto scaler did not take care of that by itself.

Any help will be appreciated

Thank you

Roiy

**Comment by bskiba** [comment]
Could you provide the output of `kubectl get -n kube-system configmap cluster-autoscaler-status -o yaml`?

**Comment by tmwtp** [comment]
Sure, thanks !

`apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2018-12-28 22:55:40.831585189 +0000 UTC m=+128593.031794002:
    Cluster-wide:
      Health:      Healthy (ready=12 unready=0 notStarted=0 longNotStarted=0 registered=12 longUnregistered=0)
                   LastProbeTime:      2018-12-28 22:55:40.064530399 +0000 UTC m=+128592.264739193
                   LastTransitionTime: 2018-12-27 11:13:00.934233437 +0000 UTC m=+33.134442120
      ScaleUp:     NoActivity (ready=12 registered=12)
                   LastProbeTime:      2018-12-28 22:55:40.064530399 +0000 UTC m=+128592.264739193
                   LastTransitionTime: 2018-12-27 11:13:00.934233437 +0000 UTC m=+33.134442120
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2018-12-28 22:55:40.064530399 +0000 UTC m=+128592.264739193
                   LastTransitionTime: 2018-12-27 12:38:46.379319329 +0000 UTC m=+5178.579528019

    NodeGroups:
      Name:        nodes.XXX.XXX
      Health:      Healthy (ready=9 unready=0 notStarted=0 longNotStarted=0 registered=9 longUnregistered=0 cloudProviderTarget=9 (minSize=6, maxSize=10))
                   LastProbeTime:      2018-12-28 22:55:40.064530399 +0000 UTC m=+128592.264739193
                   LastTransitionTime: 2018-12-27 11:13:00.934233437 +0000 UTC m=+33.134442120
      ScaleUp:     NoActivity (ready=9 cloudProviderTarget=9)
                   LastProbeTime:      2018-12-28 22:55:40.064530399 +0000 UTC m=+128592.264739193
                   LastTransitionTime: 2018-12-27 11:13:00.934233437 +0000 UTC m=+33.134442120
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2018-12-28 22:55:40.064530399 +0000 UTC m=+128592.264739193
                   LastTransitionTime: 2018-12-27 12:38:46.379319329 +0000 UTC m=+5178.579528019

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2018-12-28 22:55:40.831585189 +0000
      UTC m=+128593.031794002
  creationTimestamp: "2018-09-16T14:44:44Z"
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "23221800"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: 0d259135-b9bf-11e8-8926-0a5da0b356a8`

**Comment by Jeffwan** [comment]
@tmwtp How did you install the cluster autoscaler? There're several ways for aws and looks like your configmaps shows that CA didn't recognize the node group you mentioned. 

You would probably use multi-group or auto discovery for all groups.

**Comment by tmwtp** [comment]
> @tmwtp How did you install the cluster autoscaler? There're several ways for aws and looks like your configmaps shows that CA didn't recognize the node group you mentioned.
> 
> You would probably use multi-group or auto discovery for all groups.

Hi @Jeffwan 

I installed the autoscaler from its helm chart.

I am using auto discover for the ASG and it is defiantly can find the right group, it did increase the nodes count to 10 (min is 6) but could not expand more than that although there were 40 nodes more in the ASG capacity (50).

> Health:      Healthy (ready=9 unready=0 notStarted=0 longNotStarted=0 registered=9 longUnregistered=0 cloudProviderTarget=9 (minSize=6, maxSize=10))

This is part of the output i pasted above. I can see in that output that for some reason the maxSize is 10, should be 50. What does generate the configMap and in which scenario ?

Thanks for every bit of information

Roiy

**Comment by Jeffwan** [comment]
@tmwtp If you have multiple node groups, configMap will show all of them. Since you successfully scale up few nodes, is it an issue about your EC2 limits? Go to EC2 dashboard and check Limits and see if you have enough quota for the instance type of your node group.

**Comment by tmwtp** [comment]
> @tmwtp If you have multiple node groups, configMap will show all of them. Since you successfully scale up few nodes, is it an issue about your EC2 limits? Go to EC2 dashboard and check Limits and see if you have enough quota for the instance type of your node group.

Thanks @Jeffwan 

I have only one node ASG (3 more for masters)

The ASG is configured as follows:

Min - 6

Max - 50

For some reason when hitting the 10 nodes the autoscaler could not expand more, i am sure it was not an EC2 limit since i was able to add more nodes through the AWS console with no issue.

**Comment by MaciekPytel** [comment]
The ASG may have maxSize of 50, but your CA is configured with max=10 (note the `(minSize=6, maxSize=10)` part of configmap.

**Comment by tmwtp** [comment]
> The ASG may have maxSize of 50, but your CA is configured with max=10 (note the `(minSize=6, maxSize=10)` part of configmap.

Thank you very much @MaciekPytel !

I was double checking my configuration and it seems that the chart was initially deployed with static ASG name (including min & max values) and later we forgot to update that env to have dynamic ASG discovery like all other envs were updated. 
I reinstalled the chart with the dynamic ASG discovery and verified there is no issue and that the config map does update when i change the actual ASG min max values in the AWS console.

Many thanks !

Roiy
