### ISSUE TITLE
Recommender memory grows linearly with the number of different label sets in the cluster.

### ISSUE THREAD

**Issue by arjunrn** [kubernetes/autoscaler#1548]
The  [aggregateContainerStateMap](https://github.com/kubernetes/autoscaler/blob/0945a8fe9987a086223532ba60a3d1ffcf4e24fa/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L45) in the `cluster.go` is a map which stores container states where the keys of the map are a combination of the namespace, container name and pod labels. This works fine when the number of pods with unique labels does not grow a lot in an 8 day interval, after which the container state gets garbage collected. 

But this doesn't work well when there are a lot of CronJobs running in the cluster. The cronjob controller creates jobs for every execution and each job has a unique suffix. This job name is part of the pod label when the job runs. As a result an entry is created in the `aggregateContainerStateMap` every time the cronjob runs causing the memory to grow linearly and subsequently the container gets OOM killed. This is what it looks like in our production clusters:

![recommender_oomkills](https://user-images.githubusercontent.com/626536/50594510-2d0d2000-0e9d-11e9-86df-10620c4b4c9f.png)

I propose that the `job-name` be blacklisted and there be a flag on the recommender which accepts a list of labels which should not be recorded.

**Comment by bskiba** [comment]
Thanks for reporting. Can you share approximately how many CronJobs and how often they run?

**Comment by aermakov-zalando** [comment]
This also means that the users can DoS the recommender e.g. changing a label on every deployment. Would it make sense to record which label selectors are currently in use from all available VPA resources and ignore the rest of label key/values?

**Comment by bskiba** [comment]
We could do like this (probably behind a flag), but it comes at a price - in such a setup, you only start accumulating metric samples to calculate recommendation the moment you turn VPA on for a certain deployment. Currently, if there is enough historical information, you will have a recommendation with high confidence after ~minute.

**Comment by arjunrn** [comment]
@bskiba In that cluster we have 30 cronjobs and they run with varying frequency, some every 5 minutes to some which run daily. The issue is that the map contains keys with many strings like the `job-name` in the case of cronjob pods and we also have labels for things like application name and application version. And every entry will have all of those strings. Also I must say that I'm skeptical about storing everything in pod memory because pods get restarted quite often and it makes no sense to rely on the pod running for long periods of time.

**Comment by bskiba** [comment]
@arjunrn @aermakov-zalando I'm still thinking on how best to approach this, we recognize this is a significant issue. I'll try to get back to you before the end of week. Also sorry noone was at the sig meeting yesterday to discuss! If you'd still like to attend next week, I'll be attending for sure.

**Comment by aermakov-zalando** [comment]
Please note that it's not just cronjobs. A lot of our users deploy multiple times a day sometimes recreating hundreds of pods at a time. We only use VPA for a couple of system components, so it's tons of RAM wasted for nothing.

**Comment by bskiba** [comment]
After some thought, I think we should go with what @aermakov-zalando suggested. Namely:
Introduce --memory-saving-mode flag for recommender. We would keep the default false for backwards compatibility. With --memory-saving-mode=true in the aggregateContainerStateMap we would only keep info on labelsets for which there are matching VPAs defined in the cluster. 

We would probably be looking for someone to help with this. Are you interested in contributing?

**Comment by petr-k** [comment]
@bskiba I'd like to work on this one, but I'm not convinced that there is need to have a flag for this. I believe users do not really expect the VPA to give good recommendations immediately after turning it on.
Plus, the current behavior (i.e. wasteful memory consumption) seems to me to be much worse.

**Comment by bskiba** [comment]
@petr-k Cool! I'm wondering how to approach this. The new thing is we have changed the VPA in 0.5.0 to work on controllers (Deployments, CronJobs etc.) instead of labelsets. However, we haven't touched the implementation - the usage samples are still aggregated per label set, which is not necessary with the new API. 
I think just switching to aggregating per controller would be a huge win. WDYT?
