### ISSUE TITLE
vertiacal-pod-autoscaler: how to configure for integration with prometheus?

### ISSUE THREAD

**Issue by piontec** [kubernetes/autoscaler#1551]
I'm running VPA 0.3.0 on k8s 1.10.11. I'm trying to find some docs that explain how VPA fetches metrics' history from prometheus. Which metrics and labels it expects to be present in prometheus? Currently, no matter if I give it a correct or incorrect prometheus URL in `--prometheus-address`, nothing is logged about prometheus queries or connections, even with `--v=8`.

**Comment by bskiba** [comment]
I think you also need --storage=prometheus
Otherwise this defaults to reading from checkpoints on startup.
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/main.go#L37

**Comment by piontec** [comment]
Thanks for the tip! Does it mean that VPA uses either CRD checkpoints or it stores checkpoints in prometheus (and reads them back from there), but not both at the same time? Does it read any custom metrics from prom or uses it only as a storage for data it got previously from metrics-server?

**Comment by bskiba** [comment]
VPA uses checkpoints or history from Prometheus to initialise on startup. With checkpoints, it writes them periodically to etcd. With Prometheus it doesn't store any metrics, but assumes Proemetheus is already set up to gather pod metrics from the cluster. It reads `container_cpu_usage_seconds_total` and `container_memory_usage_bytes`.
You can take a look at [this file](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go) to see how it is done in more detail.

**Comment by bskiba** [comment]
Any luck? If you managed to set this up successfully, it would be extremely helpful if you wrote a short note on how you set it up that we could put in the docs.

**Comment by wyb1** [comment]
I setup the VPA to use prometheus. I set `--storage=prometheus` and `--prometheus-address=http://prometheus.default.svc.cluster.local:9090` Looking at the logs it looks like the vpa-recommender is using prometheus.
@bskiba is there any reason you are using `container_memory_usage_bytes` over `container_memory_working_set_bytes`? I found that `container_memory_working_set_bytes` delivers more accurate results regarding memory usage.

**Comment by bskiba** [comment]
@wyb1 This is good to know, would you maybe have time to add a short note on how to set this up in the [FAQ](https://github.com/kubernetes/autoscaler/vertical-pod-autoscaler/faq.md)? It would be very helpful to other users!

wrt the metric used, no specific reason I know of, I know the CPU metrics is also not used in a correct way (#1501). Talking to someone knowledgable about prometheus @ k8s to sort this out is on my TODO list, but couldn't get to it yet :(

**Comment by wyb1** [comment]
@bskiba no problem, I can add it to the FAQ. 
Just for clarification, if I configure the VPA to use prometheus it only uses prometheus for the history. So it creates the the checkpoints using metrics that prometheus gets from cadvisor. Is this correct?

**Comment by bskiba** [comment]
@wyb1 

> Just for clarification, if I configure the VPA to use prometheus it only uses prometheus for the history. 
This part is correct. It only uses prometheus for history
> So it creates the the checkpoints using metrics that prometheus gets from cadvisor. Is this correct?
This is only partly correct. After fetching history, VPA will also start gathering the metrics real time. Checkpoints are created based on history + observed metrics.

**Comment by panza24** [comment]
> I setup the VPA to use prometheus. I set `--storage=prometheus` and `--prometheus-address=http://prometheus.default.svc.cluster.local:9090` Looking at the logs it looks like the vpa-recommender is using prometheus.
> @bskiba is there any reason you are using `container_memory_usage_bytes` over `container_memory_working_set_bytes`? I found that `container_memory_working_set_bytes` delivers more accurate results regarding memory usage.

How did you set it?

My yaml looks like this:

apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: hamster-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hamster
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]

**Comment by mohang6770** [comment]
where about do you set these values..could anyone give an example yaml file

> I setup the VPA to use prometheus. I set `--storage=prometheus` and `--prometheus-address=http://prometheus.default.svc.cluster.local:9090` Looking at the logs it looks like the vpa-recommender is using prometheus.
> @bskiba is there any reason you are using `container_memory_usage_bytes` over `container_memory_working_set_bytes`? I found that `container_memory_working_set_bytes` delivers more accurate results regarding memory usage.

**Comment by nc-gcz** [comment]
@mohang6770, I think it's here (taken from Fairwinds VPA Helm chart): https://artifacthub.io/packages/helm/fairwinds-stable/vpa#utilize-prometheus-for-history

```
recommender:
  extraArgs:
    prometheus-address: |
      http://prometheus-operator-prometheus.prometheus-operator.svc.cluster.local:9090
    storage: prometheus
```

Adjust the addess to match your Prometheus instance.

**Comment by mohang6770** [comment]
Hi

Is there anyway we can do that extraargs on a yaml manifest..

Thanks

**Comment by mohang6770** [comment]
Hi

Is there anyway we can do that extraargs on a yaml manifest..
