### ISSUE TITLE
Cannot configure expander strategy in GKE

### ISSUE THREAD

**Issue by tsu1980** [kubernetes/autoscaler#1558]
### Description
I've created two node pools in GKE, preemptible(pool1) and non-preemptible(pool2) node pools. poo1 is used for stateless workload like web server, and pool2 is used for used for stateful workloads and fallback of the preemptible node. So I can make a more cost-efficient cluster.

But I struggled to configure to set high priority to pool1 that used when node pool scaling up.
AFAIK, its handled by CA expander strategy setting. And should be `price` strategy in my case.
But I don't know what GKE uses. and GKE is not provided to configure this setting.

#### pool1 - preemptible node pool
`gcloud container node-pools create pool2 --enable-autoscaling --num-nodes=1 --min-nodes=1 --max-nodes=10 --preemptible`
used for stateless workload like web server.

#### pool2 - non preemptible node pool
`gcloud container node-pools create pool1 --enable-autoscaling --num-nodes=1 --min-nodes=1 --max-nodes=10`
used for stateful workloads and fallback of the preemptible node.

Sorry for my poor english!

**Comment by aleksandra-malinowska** [comment]
> AFAIK, its handled by CA expander strategy setting. And should be price strategy in my case.
But I don't know what GKE uses. and GKE is not provided to configure this setting.

GKE uses only price expander, no worries :)
