### ISSUE TITLE
vertical-pod-autoscaler: make the admission controller self registration optional

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes/autoscaler#1561]
currently the `vpa-admission-controller` self register itself as an admission controller to the master API.
As a consequence the vpa-admission-controller service account must have enough permissions to do so.
Security aware organization may have a problem with this set-up as the `vpa-admission-controller` main duty is not to register new admission controller it is just to set correct resources for pod being created. 
I suggest to make it optional to have the `vpa-admission-controller` self-registering  and allow a path where the vpa-admission-controller is registered as a part of the installation process. 
This would allow for better separation of duties and least privilege, making the entire deployment more secure.

**Comment by bskiba** [comment]
That sounds like a very reasonable request and shouldn't be hard to set up.

**Comment by Rajat-0** [comment]
I would like to work on this

**Comment by bskiba** [comment]
Great! Feel free to send PRs my way.

**Comment by bskiba** [comment]
Fixed by #2949
