### ISSUE TITLE
Add enableEvict flag for cluster autoscaler

### ISSUE THREAD

**Issue by DeliangFan** [kubernetes/autoscaler#1566]
For scale down progress, we may need to disable evict for some condition. When enableEvict is disable, CA only need to taint the node. As long as the task finish, delete the empty taint node.

**Comment by aleksandra-malinowska** [comment]
Is the idea to keep the node tainted so no new workloads arrive, and it'll be removed as empty? We're considering adding "soft" taints (PreferNoSchedule) to nodes that are not yet possible to remove, but underutilized. Combined with non-removable pods, would it work for your use-case?

**Comment by DeliangFan** [comment]
> Is the idea to keep the node tainted so no new workloads arrive, and it'll be removed as empty? We're considering adding "soft" taints (PreferNoSchedule) to nodes that are not yet possible to remove, but underutilized. Combined with non-removable pods, would it work for your use-case?

Yeah, that's it!

**Comment by DeliangFan** [comment]
@aleksandra-malinowska  I would like to implement this feature, may I take the implementation? 

1. when scale down, check the node label, for example, soft-taint.
2. If the value of soft-taint is true, just taint the node.

**Comment by aleksandra-malinowska** [comment]
Thanks for offering to help :) Initial idea was to avoid adding extra controls (in form of node labels or otherwise) and just taint nodes that CA predicts it'll be able to scale down soon-ish. Let's sync with @jkaniuk as he was planning to work on this feature.
