### ISSUE TITLE
Release Cluster Autoscaler 1.12.2

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/autoscaler#1569]
To go with Kubernetes 1.12.5, we'll need to cut it on Monday, January 14th.

If you believe something should be included that isn't yet merged to cluster-autoscaler-release-1.12 branch, please link a PR with cherry-pick here. Short description of why it's needed would be welcome.

cc @feiskyer @ringtail @johanneswuerbach @Jeffwan

**Comment by ringtail** [comment]
Thanks! @aleksandra-malinowska. Alibaba Cloud Provider doesn't have any left in this release.

**Comment by Jeffwan** [comment]
Thanks! Nothing needs to be updated for AWS as I know. @aleksandra-malinowska

**Comment by feiskyer** [comment]
Thanks. Nothing from Azure as well.

**Comment by aleksandra-malinowska** [comment]
Released now, thanks for response!
