### ISSUE TITLE
Vertical Pod Autoscaler does not recover application from OOMKill loop

### ISSUE THREAD

**Issue by hjacobs** [kubernetes/autoscaler#1574]
I tried the Vertical Pod Autoscaler (VPA) with default settings and `updateMode: Auto` for more than a month and now have seen some disconcerning behavior: it reduced the memory requests/limits after some time and the application (which runs as a  single pod) went into `OOMKill` crashloop. Sadly the only way to recover was to set `minAllowed` for memory in the `VerticalPodAutoscaler` CRD.

Here the memory graph (usage + requests/limits) which shows the pod unavailable with `OOMKill` (it does not show OOM, but that's what `kubectl describe pod ..` showed me):

![kubernetes-vpa-oom](https://user-images.githubusercontent.com/510328/51061264-fd73bb80-15f2-11e9-8c7d-b1088263ad5c.png)

More details and context in my blog post: https://srcco.de/posts/one-month-of-kubernetes-vertical-pod-autoscaler-vpa.html

It would be great if the VPA could detect such `OOMKill` death situations and recover from it (by slowly (?) increasing memory again).

Anybody else has seen this behavior and could explain what was happening and/or if this general problem (no automatic recovery from OOM) is known?

/cc @arjunrn

**Comment by bskiba** [comment]
@hjacobs 
From your blog:
> (note the missing usage data for the time the pod was down because of OOMKill):
Can you elaborate more on what you were observing? Was the container constantly being restarted? If this is the case and the crashloop was reflected in the pod status, VPA should actually be handling this as I mentioned above. If it isn't working, we should look into it.

Reiterating my previous question to make sure we are on the same page, are you using the 0.3.0 version of VPA?

**Comment by arjunrn** [comment]
@bskiba Yes, we are using the 0.3.0 version. Also I guess the OOM kills are not picked up after the OOMObserver panics after the nil dereference. But hopefully that's fixed with #1585.

**Comment by bskiba** [comment]
@arjunrn ThankS!
Ah, I was worried that might be the case. All the more reason to cut a new release, I'll try to work sth out beginning next week.

**Comment by hjacobs** [comment]
@bskiba thanks!

**Comment by bskiba** [comment]
I've released 0.3.1 that contains the fix. LMK if it didn't solve the issue.

**Comment by musabshak** [comment]
OP's VPA was deployed in "Auto" mode. 

To clarify, in "Initial" mode (the mode which makes the most sense for many/most production apps?), if container is OOMkilled by the kernel, and is in a CrashLoop state because of OOMKills, VPA Updated will not step in to evict the Pod, right? So VPA's updated 20% memory request recommendation is not going to kick in until someone / something manually deletes the entire Pod, to force a new one to come up?
