### ISSUE TITLE
Why not to drain daemonset pods? 

### ISSUE THREAD

**Issue by calixwu** [kubernetes/autoscaler#1578]
I read the source code about the scaling-down part, and I found the cluster-autoscaler never drain the daemonset pods when scaling down. Wouldn't this cause problems?

**Comment by aleksandra-malinowska** [comment]
There's no point evicting DaemonSet pods, as they can't be scheduled on another node anyway. You're correct this means in particular we won't attempt any sort of graceful termination other than what kubelet may provide when shutting down. I'm not really sure if there's any mechanism we could utilize for it.

**Comment by MaciekPytel** [comment]
Note CA only respects graceful termination of up to 10 minutes anyway. Evicting daemonset pods if we're draining a node probably wouldn't be difficult, but the empty nodes case is a large issue. A lot of people rely on the fact that they're deleted in parallel and changing that would be a huge regression.

**Comment by calixwu** [comment]
> Note CA only respects graceful termination of up to 10 minutes anyway. Evicting daemonset pods if we're draining a node probably wouldn't be difficult, but the empty nodes case is a large issue. A lot of people rely on the fact that they're deleted in parallel and changing that would be a huge regression.

@MaciekPytel 
Could we do these to solve the empty-nodes issue? :
1. We ignore the daemonset pods when we try to find out the empty nodes.
2. We do not ignore the  daemonset pods when we try to delete the empty nodes. Then add the "delete traint" to the empty nodes and evict the daemonset pods in parallel, after the empty nodes being actually empty (no daemonset pods on them), we call the cloud provider's deletion in parallel.

**Comment by aleksandra-malinowska** [comment]
> Evicting daemonset pods if we're draining a node probably wouldn't be difficult

It may be harder than we think. We wait for pods to be scheduled back onto some other nodes, but with DaemonSet, each pod has a node selector for a particular node, and we don't want it to run anymore. These pods also seem to ignore the fact that node is not ready or unschedulable (which of course makes sense when starting a node that requires a DaemonSet to be ready), so they may just be scheduled back anyway. Finally, I recall some issues where an extra DaemonSet pod was left pending, so we'd have to make sure whatever we do is correctly handled by the controller.

Also, by default, `kubectl drain` doesn't try to remove DaemonSets, either. However, there's a flag `--ignore-daemonsets=false`, so it may be a starting point to investigate how it works.

**Comment by calixwu** [comment]
> These pods also seem to ignore the fact that node is not ready or unschedulable (which of course makes sense when starting a node that requires a DaemonSet to be ready.

@aleksandra-malinowska That's because "node.kubernetes.io/not-ready" and "node.kubernetes.io/unschedulable" toleration, also see: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations. If we use a custom taint, it won't be scheduled back, I think.

**Comment by calixwu** [comment]
Also agree to investigate how `kubectl drain -ignore-daemonsets=false` works.

**Comment by KJTsanaktsidis** [comment]
I just noticed this too on Google's GKE. We have a consul agent daemonset on every node, and have "leave_on_terminate: true" set in the Consul config to gracefully leave the consul mesh when the Consul agent is stopped. I wasn't seeing any graceful leaving happening however, and it turns out it seems that there's no SIGTERM of the Daemonset container before the cluster autoscaler deletes the node.

I agree that this does seem like something the kubelet should be handling though? Gracefully shutting down all the remaining workloads on a node when it itself is shut down.

**Comment by weichuliu** [comment]
@KJTsanaktsidis We face exactly the same issue -- Consul didn't cleanly exit on nodes CA killed and stale information (services/checks) are left in the cluster until we do a `force-leave`.

May I ask how you solved the issue? Is it by using `DaemonSetEvictionForEmptyNodes`?

**Comment by KJTsanaktsidis** [comment]
Took a bit of a look back through how our consul was set up - actually I just decided to live with the fact that the consul agents won't cleanly leave. They get marked as unhealthy (so their service registrations are therefore booted out of rotation) and after 72 hours the consul servers reap them I think.

**Comment by weichuliu** [comment]
@metral  Thank you! good to know about that.
