### ISSUE TITLE
Masters should be considered for reschedulable pod when scaling down

### ISSUE THREAD

**Issue by calixwu** [kubernetes/autoscaler#1590]
I read the source codes about the scaling-down part. I found that the autoscaler filter out masters when it "FindNodesToRemove" at "TryScaleDown" call:
```
nodesToRemove, _, _, err := simulator.FindNodesToRemove(candidates, nodesWithoutMaster, nonExpendablePods, sd.context.ListerRegistry,
		sd.context.PredicateChecker, 1, false,
		sd.podLocationHints, sd.usageTracker, time.Now(), pdbs)
```

I think it should pass "allNodes" instead of "nodesWithoutMaster", as some people may allow master node to be schedulable for normal pods.

**Comment by aleksandra-malinowska** [comment]
That's an unorthodox approach. Why would you do that? Master node running random pods sounds like it could lead to destabilizing the cluster (e.g. kubelet killing random component when it runs out of resources, then not being able to start it again if another pod claims these resources).

**Comment by calixwu** [comment]
> That's an unorthodox approach. Why would you do that? Master node running random pods sounds like it could lead to destabilizing the cluster (e.g. kubelet killing random component when it runs out of resources, then not being able to start it again if another pod claims these resources).

I know master node running random pods is bad. But k8s allows this happens, I just thought CA may better be consistent with it in case some people do run it in this way..
