### ISSUE TITLE
Binary in docker image of cluster-autoscaler:v1.3.5 does not match source code

### ISSUE THREAD

**Issue by gjasny** [kubernetes/autoscaler#1591]
I tried to use cluster-autoscaler version 1.3.5 with the Docker image at `gcr.io/google-containers/cluster-autoscaler:v1.3.5` on AWS. I got strange error messages saying it tried to call `DescribeLaunchConfigurations` and the `LaunchConfigurations` parameter was an empty list (or list of an empty string). This is weird because the auto scaling groups it complained about use LaunchTemplates, not LaunchConfigurations.

I used gdb to break at the error and saw that the `type aws` did only contain the `LaunchConfiguration` field, but none of the `LaunchTemplate*` fields that are present in this structure in the source code at tag `cluster-autoscaler-1.3.5`. That means the binary in the v1.3.5 Docker image was not built from the code at tag 1.3.5. Is it possible that an old version of the cluster-autoscaler binary was used to build the v.1.3.5 Docker image by mistake?

I manually built the binary and container from tag `cluster-autoscaler-1.3.5` and this works.

**Comment by aleksandra-malinowska** [comment]
That sounds worrying. We'll take a look, thanks for reporting this. 

cc @losipiuk

**Comment by aleksandra-malinowska** [comment]
Looks like the `v1.3.5` tag is on the master branch, not on `cluster-autoscaler-release-1.3` :/ This is certainly not as intended. It should point to [commit updating version to 1.3.5](https://github.com/kubernetes/autoscaler/commit/0b7a14651e9f1e4be4c3464b4ca4fb30b0542efe)).

I'll double check, but if the tree at that point contains the code you'd expect from the image, my suspicion is that the release was build from correct source, but a mistake was made when publishing release notes and creating tag on github (this step is done manually).

**Comment by MaciekPytel** [comment]
Sorry, my bad. I accidentally put tag on wrong branch.

**Comment by devkid** [comment]
Colleague of OP here. @aleksandra-malinowska @MaciekPytel Do you mean that the Docker image was correct and the tag in git was wrong or vice versa? If the Docker image is correct, does that mean that 1.3.5 does not support Auto Scaling Groups with Launch Templates? According to the `README.md`, we need to use 1.3.x for Kubernetes 1.11, would that mean we cannot use ASGs with Launch Templates?

**Comment by MaciekPytel** [comment]
Tag is wrong, image is right. 1.3.5 release was done from commit 0b7a14651e9f1e4be4c3464b4ca4fb30b0542efe. I don't use amazon and I'm not too familiar with amazon specific features, but if Launch Templates were added after 1.11 release they're probably not supported in CA 1.3.

CA uses baked-in scheduler code to predict how the scheduler in your cluster will behave. If you use CA based on different version of scheduler than you run in your cluster they may disagree and CA may make wrong autoscaling decisions. This is why we don't officially support version skew between CA and Kubernetes. That being said changes to scheduler predicates (part of scheduler we care about) are not that common and using a newer version of CA with older cluster usually works reasonably well. I'm not making any promises, but it may be worth giving it a try.

**Comment by MaciekPytel** [comment]
Officially we only accept bugfixes, but for cloudprovider-specific changes we've always been more liberal. If you get an AWS contributor (ex. @sethpollack, @Jeffwan) to review it I'm ok with cherry-picking it.
One condition is if the feature is not available in newer releases (1.12, 1.13) you must also cherry-pick it to those, so there is no regression in those versions.

**Comment by aleksandra-malinowska** [comment]
Tag is now fixed: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.3.5

No change to image as that seems to have been built from correct commit.

**Comment by devkid** [comment]
Thanks!
