### ISSUE TITLE
Cluster Autoscaler cannot parse Windows VMAS agent pool created by AKS-Engine

### ISSUE THREAD

**Issue by ankrause** [kubernetes/autoscaler#1593]
CloudProvider: Azure
Kubernetes version: 1.13.1
Cluster Autoscaler version: 1.13.1
AKS-Engine version: 0.28.1 and 0.29.1

I deployed a hybrid cluster to Azure using AKS-Engine with VMAS-based agent pools and small initial node counts (2 and 2). The resulting VM names followed the format {4 digits}k8s{3 digits}, where the last digit was the instance number which could presumably grow beyond a single digit. When evaluating scale options, the Cluster Autoscaler attempted to parse those machine names using the regex:

```
k8sWindowsVMNamingFormat               = "^([a-fA-F0-9]{5})([0-9a-zA-Z]{3})([a-zA-Z0-9]{4,6})$"
```

Since the regex doesn't match against the generated VM name, it returned an error indicating the resource was missing an identifier:

```
vmNameParts := vmnameWindowsRegexp.FindStringSubmatch(vmName)
if len(vmNameParts) != 4 {
    return "", "", -1, -1, fmt.Errorf("resource name was missing from identifier")
}
```

Hopefully this is the right repository for this issue.

**Comment by aleksandra-malinowska** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@ankrause Thanks of reporting the issue. It should be fixed with latest aks-engine pattern.
