### ISSUE TITLE
Azure AKS cluster autoscaler doesn't support bulk removal of empty nodes

### ISSUE THREAD

**Issue by netiperher** [kubernetes/autoscaler#1597]
CloudProvider: Azure AKS
Kubernetes version: 1.11.5
Cluster Autoscaler version: 1.3.5 and current master
ACS-Engine version: v0.26.3-aks

In our setup we run an Azure AKS cluster with multiple nodes that each run a single pod requiring all resources on the node. The pods are part of a statefulset that we scale quite aggressively from 2 to 20 and then back to 2 replicas at regular intervals.

When scaling down we observe unexpected behaviours in the cluster autoscaler, where initially nodes are removed quickly but then mysteriously are added back a few minutes later.

I believe this is caused by `scheduleDeleteEmptyNodes` bulk removing nodes in parallel. And `DeleteNodesInternal` in `azure_container_service_pool.go` decreasing the AKS cluster size with only one instead of actual number of nodes in the bulk set, since the function is called multiple times in parallel with a list of only a single VM each time.

The effect is that scaling down from 20 to 2 nodes takes about 1.5 to 2 hours for us. A workaround is setting `--max-empty-bulk-delete=1` (default: 10) since this decreases the scale down to 30 minutes, but running in parallel should be much faster.

**Comment by feiskyer** [comment]
@netiperher Thanks for reporting the issue. Could you share the logs of cluster-autoscaler ?

**Comment by netiperher** [comment]
Here are relevant part of logs during scale down, I've also attached a picture of the `cluster_autoscaler_nodes_count` metric, which illustrates the problem of nodes appearing during scale down. My interpretation of the problem (which I tried to explain above) can be seen by these lines from the log:

```
I0117 21:13:44.751594       1 azure_container_service_pool.go:304] Setting size for cluster ("saas-aks") with new count (19)
I0117 21:13:45.838940       1 azure_container_service_pool.go:304] Setting size for cluster ("saas-aks") with new count (19)
I0117 21:15:16.169794       1 azure_container_service_pool.go:304] Setting size for cluster ("saas-aks") with new count (19)
I0117 21:15:18.984420       1 azure_container_service_pool.go:304] Setting size for cluster ("saas-aks") with new count (19)
I0117 21:15:19.005730       1 azure_container_service_pool.go:304] Setting size for cluster ("saas-aks") with new count (19)
...
```

[autoscaler-azure-cluster-autoscaler-7b5c8c79bf-gmgtw.log](https://github.com/kubernetes/autoscaler/files/2820604/autoscaler-azure-cluster-autoscaler-7b5c8c79bf-gmgtw.log)
![cluster_autoscaler_nodes_count](https://user-images.githubusercontent.com/45091747/52109958-6d2c0380-25ff-11e9-99c0-7feb5ce156db.png)

**Comment by feiskyer** [comment]
Oh, I see. It removes the node one by one sequentially. We should change that to concurrently deletion. Great thanks for reporting the issue.
