### ISSUE TITLE
Support recycling mode node group 

### ISSUE THREAD

**Issue by ringtail** [kubernetes/autoscaler#1604]
In Alibaba Cloud. There is a kind of node group that can recycle nodes without deleting them. These nodes can be stopped without any payment and start at any time you need. But if the ECS inventory is empty. These nodes will be deleted from node group and replace by a new one. So if we use recycling mode node group with CA. Some nodes will be never deleted  because they are `notReady` and not in any node group.  So is there any similar scene in other clouds.If it is common, I'd like to make a pr to support it.

**Comment by ringtail** [comment]
@feiskyer @MaciekPytel @Jeffwan

**Comment by MaciekPytel** [comment]
Can you explain in more detail how it works and what you'd like CA to do?

**Comment by ringtail** [comment]
> Can you explain in more detail how it works and what you'd like CA to do?

In recycling mode node group. It will create nodes when scaling up nodes. And when the nodes are unneeded, it will stop the nodes instead of deleting nodes. And the second time, it will just start a node  in a few seconds. Here is the workflow about recycling mode node group.  So that we can reduce a lot of time in scaling up. But recycling mode node group can promise the node can start successfully due to the short inventory.If the happens, node group will delete the nodes and recreate new nodes. 

At that time. CA will have some nodes in NotReady status but can not be handled because they are not in recycling mode node group any more.

So I would like to Add some clean up code in CA. If the node was created by CA and unneeded anymore. CA will clean them in time even they are not in current cloud provider.

I would like to know whether you have the similar scene in other clouds.

**Comment by MaciekPytel** [comment]
> At that time. CA will have some nodes in NotReady status but can not be handled because they are not in recycling mode node group any more.

Won't NodeController remove those node objects if VM is not responding long enough?

**Comment by ringtail** [comment]
> > At that time. CA will have some nodes in NotReady status but can not be handled because they are not in recycling mode node group any more.
> 
> Won't NodeController remove those node objects if VM is not responding long enough?
NotReady is not the only reason for deleting. If this node is in node group and stopped,NodeController should not remove it.And I wonder to know if GKE have the similar node group or is that the unique scene for Alibaba Cloud.

**Comment by ringtail** [comment]
I got it. In cloud-controller-manager, it will check the node exists or not. if the node doesn't exist and it will remove the providerId and NodeController will recycle the Node. Maybe i just need to add some code into cloud provider to filter the stopped node.
