### ISSUE TITLE
Azure InstanceType case sensitive

### ISSUE THREAD

**Issue by suker200** [kubernetes/autoscaler#1608]
Hi, 
I met an issue relate to case sensitive instance type in Azure response. 

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_scale_set.go#L429
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go#L640

The value of "*template.Sku.Name" is : Standard_D8_V3 
But the key of "InstanceTypes" is: Standard_D8_v3

It made cluster autoscaler failed. 

I have workaround add 
```
	"Standard_D8_v3": {
		InstanceType: "Standard_D8_v3",
		VCPU:         8,
		MemoryMb:     32768,
		GPU:          0,
	},
	"Standard_D8_V3": {
		InstanceType: "Standard_D8_V3",
		VCPU:         8,
		MemoryMb:     32768,
		GPU:          0,
	},
```
to "InstanceTypes" and cluster-autoscaler works as normal

**Comment by feiskyer** [comment]
@suker200 Thanks for reporting the issue. This should be fixed within CA. Would file a PR to fix it.
