### ISSUE TITLE
cluster-autoscaler-release-1.12 make build failed

### ISSUE THREAD

**Issue by JinAirsOs** [kubernetes/autoscaler#1611]
when i run it on mac os,
$make build
rm -f cluster-autoscaler
go get github.com/tools/godep
GOOS=linux godep go build ./...
vendor/github.com/google/cadvisor/accelerators/nvidia.go:30:2: build constraints exclude all Go files in /Users/kerry/go/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/mindprince/gonvml
godep: go exit status 1
make: *** [build] Error 1

**Comment by MaciekPytel** [comment]
Can you try using `make build-in-docker` instead? `make build` is only meant for development.
