### ISSUE TITLE
cluster-autoscaler.kubernetes.io/safe-to-evict=true annotation not working

### ISSUE THREAD

**Issue by drewhemm** [kubernetes/autoscaler#1614]
I am using the `cluster-autoscaler.kubernetes.io/safe-to-evict=true` annotation, but I am still seeing messages like this in the autoscaler logs:

```
I0125 11:23:10.132575       1 cluster.go:89] Fast evaluation: node ip-192-168-##-##.eu-west-1.compute.internal cannot be removed: kube-system/kube-proxy-rbpck is not replicated
```

```
$ kubectl describe pod kube-proxy-6smv5 -n kube-system                           
Name:               kube-proxy-6smv5
Namespace:          kube-system
Priority:           2000001000
PriorityClassName:  system-node-critical
Node:               ip-192-168-###-###.eu-west-1.compute.internal/192.168.###.###
Start Time:         Fri, 25 Jan 2019 10:56:01 +0000
Labels:             controller-revision-hash=165802934
                    k8s-app=kube-proxy
                    pod-template-generation=2
Annotations:        cluster-autoscaler.kubernetes.io/safe-to-evict=true
Status:             Running
```

Am I doing something wrong?

_Originally posted by @drewhemm in https://github.com/kubernetes/autoscaler/issues/351#issuecomment-457542906_

**Comment by MaciekPytel** [comment]
What Cluster Autoscaler version is that?

**Comment by drewhemm** [comment]
1.3.x on k8s 1.11.5 and 1.2.x on k8s 1.10.11, as per the releases table:

https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases

**Comment by drewhemm** [comment]
Solved - see referenced issue: https://github.com/kubernetes/autoscaler/issues/351#issuecomment-457610943

**Comment by bbhenry** [comment]
@drewhemm I am having similar issue , but I am not sure which example yaml file were you referring to?
