### ISSUE TITLE
Considering Making Cluster Autoscaler Extensible

### ISSUE THREAD

**Issue by resouer** [kubernetes/autoscaler#1616]
Currently the Cluster Autoscaler is well designed and organized. 

While the the scaling policy (e.g. expander) requirements from cloud providers vary a lot, and even for different customers on same cloud. There're also use cases that for specific cloud workload, specific scaling policies are preferred as well. For instance, [the AWS cloud autoscaler of OpenAI](https://github.com/openai/kubernetes-ec2-autoscaler) is focusing on batch jobs.

The issue is an initial discussion about making Cluster Autoscaler policy extensible, the custom requirements for expander could be a good start point. In the whole picture, we can actually set up multiple extension point for every phase of Cluster Autoscaler.

The extension point can be implemented by standard [Go plugin](https://golang.org/pkg/plugin/) so we can have native performance comparing to RPC call.

cc @losipiuk @aleksandra-malinowska Would like to know your advices, if there're already plan/roadmap, would be happy to be involved.

**Comment by losipiuk** [comment]
> Currently the Cluster Autoscaler is well designed and organized.

Thanks for kind words :) We appreciate that.

> [...]
> Would like to know your advices, if there're already plan/roadmap, would be happy to be involved.

So far we modeled the extension point via a number of `Processor` interfaces (see https://github.com/kubernetes/autoscaler/blob/6f5e6aab6fe3129e01d5edce9f0cf0308e7e94d1/cluster-autoscaler/processors/processors.go#L46). They serve exactly the kind of purpose you mention. Would extending list of those with some more Processors solve your use cases?

> The extension point can be implemented by standard Go plugin so we can have native performance comparing to RPC call.

I think we can think of that. So far we modeled the extension points in the main repository and the specific implementation was provided in the fork. We could probably add implementation for runtime 
 resolution of externally provided `AutoscalingProcessors` instance via Plugins mechanism (especially if someone is willing to contribute that :) ). Do you feel that it would give a lot of benefits over providing implementation in the forked repository?

cc: @MaciekPytel

**Comment by losipiuk** [comment]
> The main benefits we are looking for is users can maintain their customized expander or estimator algorithms in their own repo with versioned interfaces. If it's possible, it's a huge benefits IMO.

I am not that convinced. Maintaining a fork of CA, where the only changes in the fork are added processors and bootstrapping logic in `main.go` seems like not much worse approach. In both approaches you have your own repo, with code you have to build and test. 
Just in one case these are only processors and in other case it is whole CA codebase.
In the fork-case the extra thing you have to do is rolling merging-in changes from CA upstream. Yet in case of point changes (like adding processor implementatation) those merges should be relatively painless.

Even if one goes with plugin approach the owners of plugin would still need to add automation which would check if plugins and current release of CA is still compatible. It does not seem like much less work that maintaining the fork.

Yet with all that said I am not saying that plugin approach is a bad thing to do. Two caveats though:
- it must be fully opt-in - CA should still work if no plugin is provided
- we will not commit to maintaining strict backward compatibility on `*Processor*` interfaces. Which implies that external implementations of plugins may break from time to time.

**Comment by MaciekPytel** [comment]
> we will not commit to maintaining strict backward compatibility on *Processor* interfaces. Which implies that external implementations of plugins may break from time to time.

+1 to that. Processors are hooks in internal logic of CA, which may (and likely will) change. At minimum we need to follow changes in upstream Kubernetes and any major change in scheduler will likely require refactors in CA (ex. https://github.com/kubernetes/community/pull/3082). As the code changes, some programming hook will likely change with it. I don't want to commit to any sort of deprecation policy, etc. 

I think this is an argument for fork approach. At least it gives you a minimum amount of control - you decide when you pull in our changes, so at least your plugin doesn't just randomly stop working. It's not much, so if there are any good arguments for using go plugin I can probably be convinced.
