### ISSUE TITLE
Deploy cluster-autoscaler to a different namespace

### ISSUE THREAD

**Issue by dnutels** [kubernetes/autoscaler#1620]
__What__

Probably documentation bug/request

__Description__

It seems that it should be possible to deploy `cluster-autoscaler` to a different namespace and is, in fact, working, as far as deployment go.

However, when inspecting the `cluster-autoscaler` (deployed to `system` namespace) logs the following error is found:

```
...   1 status.go:120] Failed to retrieve status configmap for update: configmaps "cluster-autoscaler-status" is forbidden: User "system:serviceaccount:system:cluster-autoscaler" cannot get configmaps in the namespace "kube-system"
```

And , indeed, the configmap isn't created, and then... isn't accessed.

Before I dive into configuring namespaces for Roles/Bindings and such, I'd like to verify whether this is normal? 

If it is not recommended, this should probably be documented.

__Reasoning__

`kube-system` AFAIK isn't the best namespace to put "external" stuff into, due to possible elevated permissions, certs or whatnot.

Theoretically, I'd like to separate (may be even on security group level) what is accessible for what node groups, where `cluster-autoscaler` isn't in the `kube-system` one.

Perhaps, however, this is an overkill.

__Side Note__

Setting RoleBinding and ClusterRoleBinding to be `kube-syste` seems to work properly, where `configmap/cluster-autoscaler-status` is created and updated.

**Comment by losipiuk** [comment]
The reason for picking `kube-system` namespace is that it somewhat matches `cluster-autoscaler` purpose (itself being a system component). Other autoscaling controllers (like HPA which is part of controller-manager) are deployed in kube-system namespace. 

On the other hand I do not see any strict reasons why it would be not recommended to run CA in other name-space if it is more convenient to someone. 
Then I think it would be reasonable to put `cluster-autoscaler-status` in same namespace CA pod is running.

Contributions here are very welcome. It can be either making code more elastic of documenting a limitation in the FAQ :)

**Comment by aleksandra-malinowska** [comment]
> On the other hand I do not see any strict reasons why it would be not recommended to run CA in other name-space if it is more convenient to someone.

One reason is that kube-system namespace is the only thing preventing CA from trying to evict itself. This would be undesirable as it'd then stop running and not complete deletion of the node until it was restarted somewhere else and node was tracked as unneeded again. Any race condition preventing it from being restarted on another node would completely disable autoscaling.

**Comment by dnutels** [comment]
Right. That is a pretty important reason.

PR for docs: https://github.com/kubernetes/autoscaler/pull/1648

Keep in mind that this required me to sign Linux CLA... which I do not intend to do. Your call.

**Comment by gemoya** [comment]
Did you use the argument ```--namespace``` to run the pod?

**Comment by Type1J** [comment]
> Did you use the argument `--namespace` to run the pod?

`unknown flag: --namespace other_namespace`
