### ISSUE TITLE
Need CPU & memory update for Deployment

### ISSUE THREAD

**Issue by mossuchida** [kubernetes/autoscaler#1624]
Currently I am testing VPA with HPA.  HPA creates new pods based on resource requests in Deployment.  VPA only updates currently created pods resource requests, when the new pods are scaled out by HPA, they use default hardcoded resource requests.  I would like newly scaled out pods to use the current resource utilization of the pod - scheduler uses resource request to determine which node to be deployed, it is important for HPA.
Please add an option to also update Deployment just the same as Pods.

**Comment by bskiba** [comment]
What metric do you have your HPA configured on? CPU?

This should not be the case. VPA should be able to notice that these new pods are also controlled by this VPA. Can you share you VPA and deployment spec?

**Comment by mossuchida** [comment]
Sorry, It was my mistake. Closing.
