### ISSUE TITLE
Cluster autoscaler: multiple node utilization

### ISSUE THREAD

**Issue by Globegitter** [kubernetes/autoscaler#1629]
We are making use of the kube downscaler (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) to reduce our cluster size over night and I noticed that we have 50% of our node with <60% utilization. It would be great if there was an additional setting that one could turn on to take the utilization of multiple nodes together into account. So e.g. if there are at least 3 nodes with <60% utilization that it will scale down one of the nodes because the other nodes should easily be able to handle the extra pods and we could save further costs.

**Comment by johanneswuerbach** [comment]
You can already achieve something similar with tweaking the “--scale-down-utilization-threshold”, which is 0.5 or 50% utilization by default.

We use 0.7 for example to target more utilized instances at the flip side of more scaling activity

**Comment by Globegitter** [comment]
@johanneswuerbach yes we use this flag and it is set to 0.5, but the point is if we have e.g. 10 nodes at 0.6 utilization this will not kick in even though we could easily scale down a couple of nodes.

**Comment by johanneswuerbach** [comment]
Correct, because you specified that only nodes below 50% utilization should be included (the 0.5 flag setting) if you set it to >0.6, the nodes would be included and CA would try to increase density further.

The flag basically specifies the maximum allowed overprovisioning of resources and that is 50% per default and your cluster is above that on all its nodes.

**Comment by Globegitter** [comment]
@johanneswuerbach yes but no matter what the flag is set to at some point if one has enough nodes one could still scale down even if the nodes are above to specified utilization. As another example, if I specify 0.8 for 80% utilization and I have a  100 nodes with 81% utilization, I could still easily scale down nodes because I have a 100 x 19% utilization available, i.e. the capacity of 19 nodes is not used. So this would ensure to have more "compact" nodes more and one could specify at what level one would want to compact the nodes. So I could say once the aggregate available resources of all my nodes available is above a threshold that a node should be scaled down.

I guess the number of nodes is not even so important, it is really just the aggregate resources available. So one could say maybe `--scale-down-aggregate-resource-threshold 2`, which would mean if all of my nodes together had 200% of resources available it would scale one down. That could then be 10 nodes with 20% or 100 nodes with 2%. Hope it makes more sense now.

/remove-lifecycle rotten.
