### ISSUE TITLE
addon-resizer changed parameter, examples still with "threshold"

### ISSUE THREAD

**Issue by carlosedp** [kubernetes/autoscaler#1645]
Since commit https://github.com/kubernetes/autoscaler/commit/93942efb7530a7d266dd7d7a0c83b0417b049471, addon-resizer changed the --threshold parameter to --acceptance-offset but the documentation wasn't updated.

> Usage of pod_nanny:
>       --container="pod-nanny": The name of the container to watch. This defaults to the nanny itself.
>       --cpu="MISSING": The base CPU resource requirement.
>       --deployment="": The name of the deployment being monitored. This is required.
>       --extra-cpu="0": The amount of CPU to add per node.
>       --extra-memory="0Mi": The amount of memory to add per node.
>       --extra-storage="0Gi": The amount of storage to add per node.
>       --log-flush-frequency=5s: Maximum number of seconds between log flushes
>       --memory="MISSING": The base memory resource requirement.
>       --namespace=$MY_POD_NAMESPACE: The namespace of the ward. This defaults to the nanny pod's own namespace.
>       --pod=$MY_POD_NAME: The name of the pod to watch. This defaults to the nanny's own pod.
>       --poll-period=10000: The time, in milliseconds, to poll the dependent container.
>       --storage="MISSING": The base storage resource requirement.
>       --threshold=0: A number between 0-100. The dependent's resources are rewritten when they deviate from expected by more than threshold.

**Comment by bskiba** [comment]
Thank you for reporting, we will be happy to accept contributions on this one!

**Comment by carlosedp** [comment]
Created #1651 for this.

**Comment by bskiba** [comment]
fixed by #1651
