### ISSUE TITLE
Cluster Autoscaler unaware of ephemeral storage of ASGs without nodes

### ISSUE THREAD

**Issue by nielsole** [kubernetes/autoscaler#1650]
When an ASG has 0 nodes, the cluster autoscaler does not scale up the nodes for pods which have `ephemeral-storage` requests with the error message: `reason: Insufficient ephemeral-storage`

When a node of the same ASG already exist, the scaling works fine. 

This seems to be similar to the issue with taints and labels of nodes, which can be set via tags on the ASG. I could not find a similar functionality for indicating allocatable resources of a node.

In my eyes this is clearly missing functionality / bug. What is the best way to go about it? 
Maybe also do it via tags on the ASG or can we autodetect it via describing the vanilla ASG.
Is there something I overlooked? I can't be the first one to run into this issue!?

Image version: k8s.gcr.io/cluster-autoscaler:v1.13.1
Flags used:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${CLUSTER}

Link to the same question in #sig-autoscaling
https://kubernetes.slack.com/archives/C09R1LV8S/p1549291479482900

**Comment by aleksandra-malinowska** [comment]
> In my eyes this is clearly missing functionality / bug. What is the best way to go about it?

Agreed. That being said, predicting what a node will look like in scale from 0 is usually tricky. Ideally, this should be possible to deduce from ASG's template/image/whatever it has that serves as blueprint for new instances.

**Comment by nielsole** [comment]
Guesstimating could always be wrong because of the AMI and user_data
that installs stuff on the first boot.To get started, a manual possibility via ASG Tags to configure it would
suffice at least for our use case.This could be held generic enough to support other resource types that
face the same issue.What do you think?



On Tue, Feb 5, 2019, at 7:59 PM, Aleksandra Malinowska wrote:
>> In my eyes this is clearly missing functionality / bug. What is the
>> best way to go about it?> Agreed. That being said, predicting what a node will look like in
> scale from 0 is usually tricky. Ideally, this should be possible to
> deduce from ASG's template/image/whatever it has that serves as
> blueprint for new instances.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/kubernetes/autoscaler/issues/1650#issuecomment-460760605

**Comment by aleksandra-malinowska** [comment]
I don't really mind either way, like @bskiba stated above, it's cloud provider specific part of code. Tags alone without fallback to some guesstimate will put extra configuration burden on the users, but perhaps this is acceptable.

And yeah, guessing game is exactly what I meant by tricky - same problem with estimating kernel memory reservation, which can be different for each OS/version/instance type combination:/

**Comment by doprdele** [comment]
I don't believe this is working.

Using k8s.gcr.io/cluster-autoscaler:v1.12.3

with label

```
k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage 
```

set to 100Gi

on

m5a.xl

Still requests in cluster-autoscaling producing the following output
```
: Insufficient ephemeral-storage
I0911 21:02:58.973224       1 utils.go:208] Pod sid-job-9662efd0-d3d2-11e9-a4ac-ed1c346fdfb1-ss9nn can't be scheduled on eks-iat-cluster-m5a.xlarge, predicate failed: PodFitsResources predicate mismatch, reason: Insufficient ephemeral-storage
I0911 21:02:58.973249       1 utils.go:208] Pod sid-job-9662efd0-d3d2-11e9-a4ac-ed1c346fdfb1-g65jx can't be scheduled on eks-iat-cluster-m5a.xlarge, predicate failed: PodFitsResources predicate mismatch, reason: Insufficient ephemeral-storage
```

**Comment by nielsole** [comment]
I would just think that this was not backported to 1.12?

**Comment by Jeffwan** [comment]
For feature users, minimum CA version supports this feature is 1.14.x.

**Comment by zentavr** [comment]
@Jeffwan so how to fix that in AWS? Should the ASG contain the certain tag? Should there be the instances of the certain type?

**Comment by zentavr** [comment]
Seems like the answer is [here](https://github.com/kubernetes/autoscaler/issues/1869#issuecomment-518530724).

**Comment by aaj-synth** [comment]
From the [CA readme](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup) in case someone else comes here:

> From version 1.14, Cluster Autoscaler can also determine the resources provided by each Auto Scaling Group via tags. The tag is of the format `k8s.io/cluster-autoscaler/node-template/resources/<resource-name>`. `<resource-name>` is the name of the resource, such as `ephemeral-storage`. The value of each tag specifies the amount of resource provided. The units are identical to the units used in the `resources` field of a Pod specification.
> 
> Example tags:
> 
> `k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage`: `100G`

**Comment by paymog** [comment]
I think I just stumbled on this myself running `registry.k8s.io/autoscaling/cluster-autoscaler:v1.27.2`. I had a node group with 0 nodes in it and several pods of mine couldn't be scheduled onto the node group. Here are the relevant logs from the autoscaler:

```
cluster-autoscaler-aws-cluster-autoscaler-859c6784f8-fslx9 aws-cluster-autoscaler I0813 13:39:57.378299       1 orchestrator.go:468] 5 other pods similar to standard-warpstream-agent-us-west-2b-b59ff774-5qplx can't be scheduled on eks-strick-ssd-us-west-2a-9ac6179e-1239-6d6d-4f4b-0825bb563efe
cluster-autoscaler-aws-cluster-autoscaler-859c6784f8-fslx9 aws-cluster-autoscaler I0813 13:39:57.378384       1 orchestrator.go:466] Pod standard-warpstream-agent-us-west-2b-b59ff774-5qplx can't be scheduled on eks-eksNodeGroup-m5-8xlarge-prod-us-west-2b-2-1cc89c27-8802-a25a-3417-daf6d88711e2, predicate checking error: Insufficient ephemeral-storage; predicateName=NodeResourcesFit; reasons: Insufficient ephemeral-storage; debugInfo=
cluster-autoscaler-aws-cluster-autoscaler-859c6784f8-fslx9 aws-cluster-autoscaler I0813 13:39:57.378395       1 orchestrator.go:468] 5 other pods similar to standard-warpstream-agent-us-west-2b-b59ff774-5qplx can't be scheduled on eks-eksNodeGroup-m5-8xlarge-prod-us-west-2b-2-1cc89c27-8802-a25a-3417-daf6d88711e2
cluster-autoscaler-aws-cluster-autoscaler-859c6784f8-fslx9 aws-cluster-autoscaler I0813 13:39:57.378481       1 orchestrator.go:466] Pod standard-warpstream-agent-us-west-2b-b59ff774-5qplx can't be scheduled on eks-eksNodeGroup-m5-8xlarge-prod-us-west-2b-fac872d5-4fd0-21d5-56fc-1de82d6b951c, predicate checking error: Insufficient ephemeral-storage; predicateName=NodeResourcesFit; reasons: Insufficient ephemeral-storage; debugInfo=
cluster-autoscaler-aws-cluster-autoscaler-859c6784f8-fslx9 aws-cluster-autoscaler I0813 13:39:57.378493       1 orchestrator.go:468] 5 other pods similar to standard-warpstream-agent-us-west-2b-b59ff774-5qplx can't be scheduled on eks-eksNodeGroup-m5-8xlarge-prod-us-west-2b-fac872d5-4fd0-21d5-56fc-1de82d6b951c
```

The autoscaler seems to think there are two nodes in this node group even though the AWS console says there are 0. Additionally, if there's insufficient ephemeral storage, why doesn't the autoscaler simply scale up and get more nodes to schedule these pods?

This issue persisted even after recreating the autoscaler pod.
