### ISSUE TITLE
Cluster autoscaler scaling too much with GPU nodes

### ISSUE THREAD

**Issue by dvianello** [kubernetes/autoscaler#1659]
Hello there,

playing with GPU instances & autoscaler on AWS, we're seeing something strange. 

We've added the ` cloud.google.com/gke-accelerator` label to the GPU nodes to help autoscaler recognizing that we're bringing up a GPU node,  and we do see
```
Overriding status of node xxxx.xxxx.compute.internal, which seems to have unready GPU
```
popping around in the logs.

Sometimes (I suspect race condition here) everything works fine and only _one_ node gets provisioned.  In other cases, the just-provisioned node quickly flips from `Ready` to `NotReady` and back, causing autoscaler to add another node to the pool. It's a transient status that I believe is due to the kops device plugin hook we use that switches everything over to `nvidia-docker` thus causing the few seconds of `NotReady`.

Any tunable in CA that can make it a bit more forgiving of these fluctuations & thus avoid spinning up GPUs instances that we don't need?

Thanks for the help!

**Comment by MaciekPytel** [comment]
The gke-accelerator thing is very much a hack and it works by internally pretending the node hasn't started up yet. It specifically relies on difference between node creation time and LastTransitionTimestamp of NodeReady condition to game the rest of CA logic, so the fact that it flips breaks the whole hack.

You can try changing the const https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/clusterstate/clusterstate.go#L48 and recompiling, but it may break other things.

**Comment by dvianello** [comment]
Fair enough - we'll try to avoid that restart on our side. 

Thanks for the help!
