### ISSUE TITLE
vpa "auto" mode does not work with replicas: 1

### ISSUE THREAD

**Issue by suhas184** [kubernetes/autoscaler#1665]
The vpa hamster example in the git repo does not work if the replica count is decreased to 1 . 

The deployment object definition is as below:
_apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hamster
spec:
  replicas: **2**_

if we  change the replicas to , it doesn't evict the pod and creare a new one with recommended cpu and memory. The recommendation is provided but it does not automatically recreate a pod with new specifications under "Auto" or "Recreate" mode.

_apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hamster
spec:
  replicas: **1**_

has anyone faced this issue before or is it a known behavior?

**Comment by mfilotto** [comment]
This is the expected comportment.
The updater is by default configure to change only with a min of 2 replicas

https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/main.go#L42

Till now I think we cannot change default parameters, an issue is open about that concern
https://github.com/kubernetes/autoscaler/pull/1664

**Comment by bskiba** [comment]
@mfilotto is right, by default VPA will not evict pods if there are less than 2 replicas. Closing as configuring this will be possible once #1664 is addressed.
/close

**Comment by Sudhanshu-Saurav** [comment]
what happened to this issue is this resolved ?
