### ISSUE TITLE
Allow honoring AWS ASG cooldown

### ISSUE THREAD

**Issue by c3mb0** [kubernetes/autoscaler#1666]
EKS does not allow direct interaction with `kube-controller-manager`, hence it is impossible to set the `--horizontal-pod-autoscaler-upscale-delay` flag, which leads to [thrashing](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-cooldown-delay). One way to tackle this situation could be to tell `cluster-autoscaler` to honor ASG cooldowns. Right now, it is a hardcoded [false](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go#L201). It would be great if the behaviour could be controlled via a flag.

**Comment by aleksandra-malinowska** [comment]
I'm not sure if this would actually help much with this, but feel free to send a PR if you verify it works. cc @Jeffwan

**Comment by Jeffwan** [comment]
@c3mb0 I can help on this issue and let us know if you want to take it or not.

**Comment by c3mb0** [comment]
@Jeffwan Yeah I'll take it, any ideas on the naming of the flag? Do other cloud providers have such honoring system, or should it be AWS specific? How does `--honor-aws-asg-cooldown` sound? Or something more generic such as `--honor-node-group-cooldown`?

**Comment by c3mb0** [comment]
I just noticed the proper flag to control the situation actually came with [1.13.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.0). Would it make more sense to backport it for 1.3.x since EKS is running 1.11.5?

**Comment by Jeffwan** [comment]
I prefer generic one. Looks like GCP instance group has concept [cool_down_period] (https://cloud.google.com/sdk/gcloud/reference/compute/instance-groups/managed/set-autoscaling#--cool-down-period). 

> I just noticed the proper flag to control the situation actually came with [1.13.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.0).
I am not sure which flag you are talking here? 

If we think that's feature request but not a bug fix, it's better to against master and cherry-pick feature into 1.3.x. 

BTW, as Aleksandra@ said, it may not help on the issue you meet. I am not sure if the flag is enable by default or not. If it's enabled, let's say `horizontal-pod-autoscaler-upscale-delay` has default setting for 3mins, if you add extra cool down on node autoscaler. It would be hard for you to control behavior.

**Comment by aleksandra-malinowska** [comment]
> I just noticed the proper flag to control the situation actually came with [1.13.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.13.0). Would it make more sense to backport it for 1.3.x since EKS is running 1.11.5? 

Which flag do you mean?

> I prefer generic one. Looks like GCP instance group has concept [cool_down_period] (https://cloud.google.com/sdk/gcloud/reference/compute/instance-groups/managed/set-autoscaling#--cool-down-period).

This only applies if MIG autoscaler is used, not when using CA.

**Comment by c3mb0** [comment]
> Which flag do you mean?

`--new-pod-scale-up-delay`

I now believe the proper solution to the trashing problem is to cherry-pick relevant commits from master into 1.3.x instead of stalling the scale up process through errors thrown via honoring. Should I close the issue?

**Comment by Jeffwan** [comment]
@c3mb0 

> --new-pod-scale-up-delay
This flag is used to give CA extra time for pending pod to be scheduled.. [PR](https://github.com/kubernetes/autoscaler/pull/1245/files)

Even CA doesn't have any cross version testing, I think maybe you can test this feature using closest CA version with this feature since we are not sure if this will help on your case? 

Once you confirmed, we can help cherry-pick the feature to 1.3.x. 

Since this is not related to AWS ASG cooldown, you can close this issue. Feel free to open another one if you think that will help.

**Comment by c3mb0** [comment]
I will try 1.13.0 and open another issue regarding cherry-picking after some observation, thank you @Jeffwan.
