### ISSUE TITLE
Scale-out latency?

### ISSUE THREAD

**Issue by khteh** [kubernetes/autoscaler#1675]
Hi, I am using AWS EKS with multi-ASG in multi-zones and I have deployed the autodiscover autoscaler. Is there any measured data regarding node scale-out latency? What measures does the autoscaler take to prevent production downtime due to the node scale-out latency when there is a sudden surge of load? Thanks.

**Comment by leonsodhi-lf** [comment]
@khteh you've probably already seen it, but the FAQ has a [Q/A](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-service-level-objectives-for-cluster-autoscaler) related to latency.

**Comment by MaciekPytel** [comment]
Note that all CA does is request a node from cloudprovider. As such the only thing we can control is how long it takes CA to make an autoscaling decision. How long it takes to spin a VM and register it in Kubernetes is up to cloud provider.

**Comment by khteh** [comment]
Thanks!
