### ISSUE TITLE
Allow custom AWS region overrides

### ISSUE THREAD

**Issue by mbach04** [kubernetes/autoscaler#1707]
Unique regional endpoints exist in disconnected AWS environments. Currently the aws-go-sdk that is utilized heavily in k8s hard codes these regions in json [1] and doesn't appear to expose an easy method to override that would flow down to a repo like the k8s/autoscaler. A similar issue [2] with a merged PR  [3] was filed against the k8s repo.

The previous solution was to read a file that specified the custom endpoints and associated services. This is something that would benefit those same environments tremendously and all for the use of the auto-scaler. I'm happy to take a crack at this patch, but it's taking me a while to find the right place in this repo to inject the reading of such a file or env var.

Because the hostnames and certs for these custom regions are private, they will never see the light of day in the aws-go-sdk models json file defining all available services. Being able to override these hostnames dynamically would be extremely helpful.

1. [AWS endpoints models](https://github.com/aws/aws-sdk-go/blob/182cda27d0921b14139ff6d352c09e0cb20e4578/models/endpoints/endpoints.json)
2. [RFE Allow to override default AWS endpoint](https://github.com/kubernetes/kubernetes/issues/70588)
3. [Add AWS Custom Endpoint capability #70588](https://github.com/kubernetes/kubernetes/pull/72245)

**Comment by aleksandra-malinowska** [comment]
> find the right place in this repo to inject the reading of such a file or env var

Anywhere in `cluster-autoscaler/cloudprovider/aws/` is fair game, I suppose. If you meant it more specifically (i.e. where in that module), I'm not sure.

**Comment by cuppett** [comment]
cc @jottofar

**Comment by jottofar** [comment]
@mbach04 I've been working on this change as well. See my code changes in https://github.com/kubernetes/autoscaler/pull/1717. I have not tested them but wanted to get them out here for review.

**Comment by mbach04** [comment]
@jottofar Awesome, do we want to close this RFE then? Also, I should be able to test this coming Monday / Tuesday.
