### ISSUE TITLE
AWS Autodiscovery 

### ISSUE THREAD

**Issue by anoora17** [kubernetes/autoscaler#1715]
I have problem applying Autoscaler https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml I got the error below:

I am using EKS with  Kubernetes version 1.11, changed the tags as the documentation recommended 
to k8s.io/cluster-autoscaler/enabled and   added this tag k8s.io/cluster-autoscaler/my_eks =1

 command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/my_eks

also changed the cert path in
` volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-bundle.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"`
 This is the error am getting, even I exported all the AWS env for region and keys
`I0222 21:20:27.282690       1 cloud_provider_builder.go:72] Building aws cloud provider.
E0222 21:20:27.282851       1 aws_manager.go:121] Failed to regenerate ASG cache: cannot autodiscover ASGs: MissingRegion: could not find region configuration
F0222 21:20:27.282869       1 cloud_provider_builder.go:137] Failed to create AWS Manager: cannot autodiscover ASGs: MissingRegion: could not find region configuration`

**Comment by radityasurya** [comment]
you need to add env aws_region

```
env:
            - name: AWS_REGION
              value: eu-west-1
```

like this

**Comment by Jeffwan** [comment]
@anoora17 The CA version you are using and example doesn't match. Please choose right Github branch for examples. As @radityasurya suggests, you can also add environments instead. Env was removed in the https://github.com/kubernetes/autoscaler/pull/1288 and read from config instead. Examples were also updated in the corresponding branch.

**Comment by Jeffwan** [comment]
@annora17 

EKS release support with kubernetes v1.12. I also update examples in https://github.com/kubernetes/autoscaler/pull/1864. It becomes easier now.
