### ISSUE TITLE
Prevent Cluster Autoscaler from scaling down a particular node by label

### ISSUE THREAD

**Issue by openstacker** [kubernetes/autoscaler#1716]
Hi @mwielgus @MaciekPytel , Is it possible to use lable instead annotation to prevent CA scaling down a particular node? Thanks.

**Comment by aleksandra-malinowska** [comment]
Not really. Labels are somehow different from annotations - we expect all nodes in a node group to have the same set of labels, they can be used to control scheduling etc. Is there any reason you can't use an annotation?

**Comment by openstacker** [comment]
I get that. But our scenario is a little bit different. In our case, we're also running kubelet on master nodes to host some daemonset or some pod we want them running on master nodes. At this case, we'd like to 'tag' the master when doing bootstrap. With label, I can use --node-labels for kubelet arguments, but seems there is no argument for annotation.

**Comment by bskiba** [comment]
Would it be possible to annotate the node as part of bootstrap?

**Comment by openstacker** [comment]
> Would it be possible to annotate the node as part of bootstrap?

That's what I want to figure out as well, but seems kubelet doesn't support that. Now I have to run kubelet to get the master and then annotate them one by one.
