### ISSUE TITLE
Azure: implement tainted VMSS

### ISSUE THREAD

**Issue by sylr** [kubernetes/autoscaler#1748]
In the event a VMSS can be scaled to 0 the cluster autoscaler might become unaware a VMSS spawns tainted nodes so it would be nice to implement a way for the cluster autoscaler to discover the taints a VMSS applies to the nodes it spawns.

AWS implemetation does this by reading ASG (equivalent of Azure VMSS ?) tags: https://github.com/kubernetes/autoscaler/blob/d9ad9f438a42afe7a7abf9a3ea4db1d603b9367a/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0

**Comment by feiskyer** [comment]
@sylr Thanks. This is a reasonable feature request, we should definitely support it.

**Comment by mvasilenko** [comment]
any chance for this to be merged?
works fine for me, but need a rebase

btw, how the taints would be propagated to kubelet options at the node?

**Comment by feiskyer** [comment]
https://github.com/kubernetes/autoscaler/pull/1982 is fixing this.
