### ISSUE TITLE
k8s in azure autoscaler with vmss

### ISSUE THREAD

**Issue by krishpavan** [kubernetes/autoscaler#1749]
I have built k8s with kubeadm with vmss and autocaler. The autoscaler work with job submission and add worker nodes join k8s. I have two ASG groups  vmss1, vmss0 with low priority vms.  
The issue is vm are not registered with ASG group and make the cluster unhealthy.  Attached the logs. 

Regards
Krish

azureuser@kubevanmaster:~$ kubectl get nodes --show-labels
NAME              STATUS   ROLES    AGE     VERSION   LABELS
kubevanmaster     Ready    master   3d19h   v1.13.4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kubevanmaster,kubernetes.io/role=master,node-role.kubernetes.io/master=
vmss05cd9000004   Ready    agent    7h22m   v1.13.4   agentpool=vmss0,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D1_v2,beta.kubernetes.io/os=linux,kubernetes.io/agent=,kubernetes.io/hostname=vmss05cd9000004,kubernetes.io/role=agent
vmss17819000007   Ready    agent    7h23m   v1.13.4   agentpool=vmss1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D1_v2,beta.kubernetes.io/os=linux,kubernetes.io/agent=,kubernetes.io/hostname=vmss17819000007,kubernetes.io/role=agent,spotfleet=true vmss17819000007   Ready    agent    7h22m   v1.13.4   agentpool=vmss1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D1_v2,beta.kubernetes.io/os=linux,kubernetes.io/agent=,kubernetes.io/hostname=vmss17819000007,kubernetes.io/role=agent,

azureuser@kubevanmaster:~$ kubectl describe  configmap cluster-autoscaler-status -n kube-system
Name:         cluster-autoscaler-status
Namespace:    kube-system
Labels:       <none>
Annotations:  cluster-autoscaler.kubernetes.io/last-updated: 2019-03-05 13:42:38.5694064 +0000 UTC

Data
====
status:
----
Cluster-autoscaler status at 2019-03-05 13:42:38.5694064 +0000 UTC:
Cluster-wide:
  Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=2)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801
  ScaleUp:     NoActivity (ready=3 registered=3)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801

NodeGroups:
  Name:        vmss0
  Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=1 cloudProviderTarget=1 (minSize=1, maxSize=10))
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801
  ScaleUp:     NoActivity (ready=0 cloudProviderTarget=1)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801

  Name:        vmss1
  Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=1 cloudProviderTarget=1 (minSize=1, maxSize=10))
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801
  ScaleUp:     NoActivity (ready=0 cloudProviderTarget=1)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2019-03-05 13:42:37.9341032 +0000 UTC m=+26566.679524601
               LastTransitionTime: 2019-03-05 06:20:22.3535484 +0000 UTC m=+31.098969801

Events:  <none>

The relevant error in logs , I have attached full logs of autoscaler pod.

Warning  ScaleUpTimedOut     13m                  cluster-autoscaler  Nodes added to group vmss1 failed to register within 22m3.133659s
  Warning  ScaleUpTimedOut     13m                  cluster-autoscaler  Nodes added to group vmss0 failed to register within 23m51.4120586s
&
I0305 05:31:57.371400       1 factory.go:33] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscal                      er-status", UID:"445789ff-3f05-11e9-99d8-000d3a1205c5", APIVersion:"v1", ResourceVersion:"1932043", FieldPath:""}): type: 'Warning' rea                      son: 'ScaleUpTimedOut' Nodes added to group vmss1 failed to register within 15m5.1236732s

**Comment by bskiba** [comment]
Not sure what the reasons could be for the newly added nodes to fail to register after scale up. @feiskyer would you be able to help?

**Comment by feiskyer** [comment]
@krishpavan There's possible cases that VMSS node's providerID is in different cases compared to cloud provider. So CA won't be able to recognize the node (see https://github.com/kubernetes/kubernetes/issues/71994).  Could you check the providerID for each node, and check whether they are in same cases format?

**Comment by krishpavan** [comment]
Thanks . VMSS report RG as CAP , while provider  report in small.  
I have changed cloud provider RG in CAPS  with kubelet config, seemed fixed the issue
