### ISSUE TITLE
[Feature Idea] A simple expander based on static precedence

### ISSUE THREAD

**Issue by viggeh** [kubernetes/autoscaler#1772]
This is similar to https://github.com/kubernetes/autoscaler/issues/1709

When using cluster-autoscaler there is no expander available for `price`. There seems to have been some effort put into implementing one but it looks like it has stalled https://github.com/kubernetes/autoscaler/pull/486

There is no simple mechanism currently to have multiple ASGs with different lifecycle types. For instance if you have two identical ASGs, one for spot and another for on-demand, cluster-autoscaler just picks one by random. There is no weighting between them. The same goes for the scenario of having two ASGs with different instance types but one having reserved instances, thus being cheaper.

We could solve this by adding a new expander based on `precedence`. Nodegroups would be created with a `precedence` value, this could be autodiscovered through tags. When picking through available nodegroups, the expander would simply pick the one with the lowest precedence. 

This would solve a lot of problems running in AWS, one could simply set the `precedence` value of the nodegroup to the spot market price being used, or the hourly RI price.

It seems like a quick solution while implementing a price expander for AWS, although being a better solution, seems like a much bigger task.

**Comment by MaciekPytel** [comment]
Sounds like a reasonable idea - I'm happy to review and merge if someone comes up with implementation.

**Comment by ringtail** [comment]
@MaciekPytel @viggeh I agree and would like to provide the implementation for alibaba cloud.

**Comment by ezalejski** [comment]
I think many of us using 'spot' instances on AWS would love that feature.

**Comment by ezalejski** [comment]
I think this PR - #1801 can help us a lot.

**Comment by jeffliu27** [comment]
@MaciekPytel  @viggeh  Could I help with implementing this feature as a first time contributor?

**Comment by MaciekPytel** [comment]
@jeffliu27 I believe it's already implemented (#1801). It will be included in 1.15 release.
