### ISSUE TITLE
QQ: Using VPA in Auto mode, whats the relationship with controller's (deployment's) requests/limits?

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes/autoscaler#1774]
when we assign a VPA in Auto mode to a controller, whats the point of having requests/limits defined in the controller and what should they even be?

I notice the VPA edits the pods resources directly but leaves the controller's resources in tact.

TIA

**Comment by kgolab** [comment]
Hi @naseemkullah ,

the requests you set will be used from the very beginning, before there is enough data for VPA to provide and actuate a recommendation. I'd recommend setting them to a safe (over-provisioned) value if only possible and letting VPA come up with a more precise request. You can also start with a low request and let VPA increase it as needed but it'll most likely be a more disruptive process to your workloads.

As for limits - the last bullet of [Limitations of beta version](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#limitations-of-beta-version) says that at the moment limits are not handled by VPA and thus have similar effect to specifying MaxAllowed value in VPA objects.
Please note though that as resource limits (together with requests) imply QoS class, for now it would be better to leave limits unset and use MaxAllowed if you want to limit the recommendation given by VPA.
NOTE: This is likely to change at some point.

**Comment by naseemkullah** [comment]
Thanks for the explanation @kgolab!
