### ISSUE TITLE
QQ: How to override MinAllowed ?

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes/autoscaler#1775]
I notice many pods getting 
```
          cpu: 12m
          memory: 131072k
```

But they actually require less. I would like to override the MinAllowed...

TIA

**Comment by kgolab** [comment]
There are two flags: pod-recommendation-min-cpu-millicores and pod-recommendation-min-memory-mb - but it looks like you're already overriding them since the defaults are 25 mCPU and 250 MiB.

Looking at the HistogramOptions used you can get to as low as 10 mCPU and 10 MiB plus safety factor (15% by default).

@naseemkullah , which value would like to lower: CPU, memory or both?

**Comment by naseemkullah** [comment]
Thanks @kgolab , I'm confused as to how I am overriding the defaults already - in my case, each controller sets a request of `10 mCPU` and `128 MiB`.  But I am not explicitly overriding them with the flags you've mentioned.

I just realized that `131072k` corresponds to `128 MiB`.
As for cpu I guess `10m` becomes `12m` with the 15% safety factor. 

Does the controller request act as `pod-recommendation-min-<resource>-<metric>` ?

With that said, I would be interested in the min cpu to actually be 10m. It seems silly at first but I am actually dealing with ~900 single pod deployments so `2m` each adds up.

P.S. I am using manifests directly to create the VPAs, if possible would like to know the YAML to edit rather than a flag.

**Comment by hongli-my** [comment]
@naseemkullah  https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L62  
minCpu is 25m for one pod,   if two container in one pod?

**Comment by naseemkullah** [comment]
Thanks @hongli-my , it's true there are actually 2 containers in each pod. 

I would like to reduce `minCpu` for the entire pod to be `10m` and `minMemory` to be `128Mi`

**Comment by Skull0ne** [comment]
@naseemkullah I think something like that should work : 
```apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
  name: foo-vpa
  namespace: foo-ns
spec:
  targetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: foo-deploy
  resourcePolicy:
    containerPolicies:
    - minAllowed:
        cpu: 50m
        memory: 75Mi
      mode: auto
      containerName: "*"
  updatePolicy:
    updateMode: "Auto"
```

**Comment by bskiba** [comment]
I think this one is answered, (thanks for all who helped!) let me know if there is something missing.
/close

**Comment by naseemkullah** [comment]
Thanks @SkullOne and everybody
