### ISSUE TITLE
how does the cluster autoscaler move pods?

### ISSUE THREAD

**Issue by nhooyr** [kubernetes/autoscaler#1776]
Does it start the new pod first and then shutdown the old one?

Or shutdown the old one and then start the new one?

Would be good for the FAQ.

**Comment by nhooyr** [comment]
Reason I ask is if its the second, then I cannot ensure that at least one replica is active because maybe all my deployment's pods are on a single node. Whereas with the first I can.

**Comment by lsytj0413** [comment]
when CA decide to remove one node, it will evict all the pod on the node first, and it won't care about whether the pod is running on another node.

Note CA won't remove a node if there is a independent pod is running.

**Comment by aleksandra-malinowska** [comment]
You can set PodDisruptionBudget for your workload. With maxUnavailable: 1 (or an equivalent configuration using minAvailable), pods should be evicted one after another.
