### ISSUE TITLE
QQ: Can targetref value be a label?

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes/autoscaler#1778]
Hi,
I am dealing with ~900 single pod deployments, as the example used the deployment name for value of targetRef, i am creating 1 vpa per deployment. However all ~900 of these deployments share a common label, which makes me wonder if a single vpa can recommend/adjust resources for all of their pods by targeting with this label. 
TIA

**Comment by ndon55555** [comment]
@naseemkullah Did you ever find an answer to your question? I would like to know this as well

**Comment by naseemkullah** [comment]
> @naseemkullah Did you ever find an answer to your question? I would like to know this as well

Hi @ndon55555 I did not, today I am using 1 VPA : 1 deployment ratio. I have not recently investigated though and perhaps there has been advancements I am unaware of, keep me posted if you find anything!

**Comment by RayBB** [comment]
I would also really like to be able to set the VPA based on labels.

@naseemkullah how does the VPA work when you add one per deployment?
Are all of your 900 pods using roughly the same resources and then the VPA sees that when new pods are created and allocates accordingly?
Or is it the case that you attach the VPA to a pod and then the VPA changes the pod based on what it sees that specific pod use in terms of resources?

**Comment by RayBB** [comment]
It seems label selectors were deprecated in [0.5.0](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.5.0).
As far as I can tell, there is no workaround.
GKE has some docs [here](https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling-migration#introducing_v1beta2_api) about the migration with no resolution.

**Comment by RayBB** [comment]
For reference, I was trying to address this using a service but that doesn't seem possible.
#3752
