### ISSUE TITLE
Rebase the image to distroless

### ISSUE THREAD

**Issue by yuwenma** [kubernetes/autoscaler#1787]
We are currently working on rebasing k8s base images to distroless. Distroless image has several good features (smaller in size, fewer components requiring CVE patching, etc) but also doesn't have some dependencies autoscaler uses (shell). To use distroless as the base image, the following AIs needs to be done:
Step 1. Sync up with current k8s head.
Reason: oss kubernetes no longer uses glog which requires shell to redirect the log file. Instead, k8s is using klog which accepts a log path flag. This sync-up is necessary to remove the bash file run.sh which is used to redirect the glog.
Step 2. Replace the glog to klog in other autoscaler files.
Step 3. Update the base image to distroless and remove distroless-preinstalled packages like ca-certificate.
Step 4. After the above steps are done, require release engineers' help on monitoring the performance.

**Comment by losipiuk** [comment]
Done. CA 1.16.0 is based on distroless image. (https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.16.0)
