### ISSUE TITLE
VPA for CronJob

### ISSUE THREAD

**Issue by estahn** [kubernetes/autoscaler#1790]
Would be great to have the VPA update CronJob resources.

**Comment by bskiba** [comment]
Seems reasonable, we need to find a consistent way to fetch a labelSelector from a CronJob. (CronJob does not support scale subresource).
@schylek @kgolab FYI

**Comment by bskiba** [comment]
This should not be very difficult to support. The parts to fix are:
- give VPA recommender permissions to read CronJobs
- add code to return JobSpec.LabelSelector for CronJobs in this switch: https://github.com/kubernetes/autoscaler/blob/e79fbeee44f6474cd80029ded60ef092d6a4c602/vertical-pod-autoscaler/pkg/target/fetcher.go#L153

Marking this as help-wanted if anyone wants to pick it up. Will be happy to review.

**Comment by estahn** [comment]
@bskiba Thanks for your input. I will make it my Friday project and report back.

**Comment by schylek** [comment]
One small addition: CronJob has to be added to the list of observed controllers as it is already happening for Job. https://github.com/kubernetes/autoscaler/blob/e79fbeee44f6474cd80029ded60ef092d6a4c602/vertical-pod-autoscaler/pkg/target/fetcher.go#L86
