### ISSUE TITLE
on premise scaling to aws

### ISSUE THREAD

**Issue by jyipks** [kubernetes/autoscaler#1798]
How do i provide credentials to the aws cloudprovider so i can run from on premise bare metal and scale out to aws when it there are not enough resources on the node? I believe the aws cloudprovider is grabbing creds to create the new aws nodes.

**Comment by Jeffwan** [comment]
@jyipks 
You're right, IAM roles has been attached to node group. client can be able to grab credentials.

In you case,  you can do this way,  add following env into your cluster-autoscaler deployment. 

```
          - name: AWS_ACCESS_KEY_ID
            value: YOUR_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            value: YOUR_ACCESS_KEY
          - name: AWS_REGION
            value: YOUR_REGION
```

I will file a PR to add documentation and samples.

**Comment by jyipks** [comment]
@Jeffwan i am able to have the cluster-autoscaler pod communicate to aws and launch a node in the ASG, however the node is not being provisioned as a kubernetes worker. I am using Canonical, Ubuntu, 18.04 LTS, amd64 bionic image build on 2019-02-12 AMI, is the cluster-autoscaler pod suppose to provision the node like what Kops or Kubespray does? Or do I somehow need an AMI with kubernetes pre-installed somehow?

**Comment by Jeffwan** [comment]
@jyipks You probably need to a node group defined, and then scale that ASG. node group can be created by kops or kubespray. Honestly I am not familiar with federated or hybrid architecture mixing with on prem and cloudprovider. You can probably ask this question in  Kops or Kubespray? Like how to create a nodegroup join as workers in on prem cluster?

**Comment by sd2k** [comment]
@jyipks Did you manage to get this working? I'm struggling with the same issue as you...

**Comment by jyipks** [comment]
@sd2k have not found anything to make this work yet unfortunately. i think possibly, we might have to configure a "providerID" to trick it.. there are logs saying my on prem nodes dont have one.. my aws nodes has something like this .. "ProviderID:                  aws:///us-east-2c/i-xxxxxxxxxxxxxx" i'm not a programmer.. but possibly someone could write something to skip that particular check/see if that is required to spin it up..

let me know if you find anything.

**Comment by sd2k** [comment]
I'm pretty sure you need to set the - -provider-id flag in the kubelet
which should handle that. I couldn't get to a point where my AWS nodes even
displayed a provider ID, they all just displayed as unregistered. I haven't
used kubespray to set up the AWS nodes though...

**Comment by jyipks** [comment]
my on prem nodes are kubespray configured, and aws i just setup up the autoscaling group and made sure its tagged with the required names. (the providerID bit was something I noticed when i used kops to directly create nodes in aws)

**Comment by JanNemcik** [comment]
did someone get this working? we are currently also facing challenge of scaling from on-prem to aws

**Comment by behdadkh** [comment]
I am also looking into this. 

Trying to launch a cluster with mixture of AWS and Baremetal workers, the only resource that I found so far is this [page](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/aws.md).
