### ISSUE TITLE
[CA] RefreshInterval is too low for auto discovering ASG for AWS

### ISSUE THREAD

**Issue by vivekgarg20** [kubernetes/autoscaler#1803]
As of now refreshInteval configuration is 10 seconds to discover ASG for AWS. 
It is causing AWS apis to be throttled. We are running 10's of clusters. 
I found same configuration for GCE is 1 minute.
Shouldn't 1 minute is sensible default. I would recommend to make it configurable.

**Comment by Jeffwan** [comment]
This is reasonable and should be an easy improvement. I will submit a PR today.

**Comment by Jeffwan** [comment]
@vivekgarg20 Azure, GCE, AWS both have this setting. I notice there're similar setting like machineRefreshInternal. 
If we make it configurable per cloud provider, that will bring too many options and we also don't like to bring cloud provider specific configuration to options. 

I think I will just update to 1minute for AWS. I didn't see any downside to make this change. The only thing affect is node info may come into aws manager a little bit late. 1 min still makes sense.

**Comment by vivekgarg20** [comment]
@Jeffwan Thanks for update.  I would have loved to have configuration nonetheless 1 minutes works as it is consistent with other (GCP) implementation as well.
