### ISSUE TITLE
Vertical Pod Autoscaler: load cpu usage from prometheus  is bug?

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/autoscaler#1810]
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go#L193

container_cpu_usage_seconds_total type is  counter,  use it as  container cpu usage is right?

**Comment by safanaj** [comment]
Hi, prometheus is used to collect history real usage, do you think that to use `sum(rate(container_cpu_usage_seconds_total[]))` would be more appropriate ?

**Comment by hongli-my** [comment]
I debug  this code: sample get from prometheus very large compare to the sample from metrics-server.

**Comment by bskiba** [comment]
Hi there. This is duplicate of #1501. We'll gladly see contributions from someone who can test this with prometheus.

**Comment by safanaj** [comment]
@bskiba I tested this and yes we should use `rate()` or `irate()` to get values close to what metrics-server is providing.
I can take this and prepare a PR soon

**Comment by bskiba** [comment]
That would be great, thanks!
