### ISSUE TITLE
Long running operations may fail because of Azure go-autorest bugs

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/autoscaler#1811]
According to Azure/go-autorest#357, the timeout set in context doesn't take effect and 15min is always used for long running operations.

We should upgrade the version of go-autorest >= 11.3.2 or a patch version 11.1.2.

Depending on https://github.com/kubernetes/kubernetes/issues/75579.

/kind bug

**Comment by edrevo** [comment]
@feiskyer, is there any way of backporting this to older autoscalers? Or is it impossible because it depends on a change on the main k8s repo?

**Comment by feiskyer** [comment]
@edrevo probably not possible because the package is only vendored from kubernetes 1.15 or master, while CA depends on this package indirectly via vendoring kubernetes.

The issue has been fixed in master branch.

/close
