### ISSUE TITLE
Mutating Webhook timeout on Private GKE Cluster

### ISSUE THREAD

**Issue by wyb1** [kubernetes/autoscaler#1820]
The mutating webhook will always timeout when the VPA is deployed in a private GKE cluster (using the `vpa-up.sh` script). This means pod creation will always take more than 30s.

After debugging the issue I found that there are some firewall rules created that block the API Server from reaching the webhook backend on port 8000. The firewall only allows traffic from the API Server to the cluster over ports 10250 and 443. 

How to recreate:
1. Create a VPC
2. Create a GKE Cluster, enable private cluster and use the VPC from step 1
3. Run `vpa-up.sh`
4. Creating a pod will take more than 30s because the webhook times out.

Allowing port 8000 in addition to 10250 and 443 fixes this problem, but this is not a great solution.

To mitigate this problem I wanted to have the vpa-webhook service map from port 443 to 443 instead of 443 to 8000. To do this I needed to change the `--port` flag in the vpa-admission-controller but it appears that this change isn't in the current release. Is a new release of the VPA planned in the near future?

**Comment by bskiba** [comment]
Thank you for filing, this is indeed a bug (and an issue with Kubernetes that the webhook timeout is not configurable in any way).

We are currently in the process of cutting the new release that will have the needed flags available for configuration, ETA this week.
However, note that the new release stops support for v1beta1 API, so if you are using it please make sure to migrate your VPA objects before upgrading (this will be covered in the docs for the new release). 
See https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#notice-on-switching-to-v1beta2-version-03x-to-040 on migrating between the APIs.

**Comment by wyb1** [comment]
Thanks @bskiba! We've already migrated over to v1beta2.

Hopefully this issue will help other people if they run into a similar problem.

**Comment by bskiba** [comment]
That's great to hear! I'm finishing up the work on 0.5 release sorry for the delay.

**Comment by bskiba** [comment]
0.5 is out
/close
