### ISSUE TITLE
VPA Updater minReplicas overridable in VPA objects

### ISSUE THREAD

**Issue by safanaj** [kubernetes/autoscaler#1828]
Would be great if the VPA objects could specify a minimum number of replicas to allow the updater to evict their pods, this would be used only if set and greater than zero, if that would be missing or 0 the updater would still to respect the `--min-replicas` param.

This feature would require an minor API change adding an integer under updatePolicy in VPA Spec.

**Comment by bskiba** [comment]
Updater respects Pod Disruption Budgets that should allow you to express these constraints for each deployment: https://kubernetes.io/docs/tasks/run-application/configure-pdb/

**Comment by bskiba** [comment]
I'll close as I think the PDB should be able to cover this usecase. If this is not the case, please reopen.
/close
