### ISSUE TITLE
Assymetric nodepools and downscaling

### ISSUE THREAD

**Issue by hmeerlo** [kubernetes/autoscaler#1838]
The docs state the following:

> The sum of cpu and memory requests of all pods running on this node is smaller than 50% of the node's allocatable. (Before 1.1.0, node capacity was used instead of allocatable.) Utilization threshold can be configured using --scale-down-utilization-threshold flag.

But I currently am in a situation where I have 1 small node (1vCPU, 3.75GB mem) which has 70% allocated CPU requests. Besides this I have 3 large nodes (8 vCPU, 30GB mem) with max 10% CPU and mem allocated. All pods on the small node are eligible to be moved, but according to the above rule this small node will never be deleted even though there is plenty of room for all pods on other nodes. Am I overlooking something?

**Comment by losipiuk** [comment]
Yes. With default settings the node will not be removed as more than 70% of allocatable is in use. You can change the 50% to different threshold via `--scale-down-utilization-threshold` command line argument.

**Comment by hmeerlo** [comment]
Ok, but it doesn't make sense to me. It makes some sense when you have a single nodepool, but not in the case of mixed nodepools. Resources can be distributed more efficiently in this case. Why is there even a utilisation threshold? Shouldn't all nodes be considered for deletion regardless of their utilisation? Just let the algorithm decide whether there is room for the resources in the rest of the cluster.

**Comment by losipiuk** [comment]
Originally the flag was introduced to limit the amount of disruptions - due to node scaledown. I agree this is somewhat controversial if we should have it or if the default value is correct. Especially for the cases like yours.

**Comment by losipiuk** [comment]
@hmeerlo do you believe there are any action items related to this issue? Or can we close this?

**Comment by hmeerlo** [comment]
Well I am not yet convinced that the current algorithm is the right algorithm. I try to discuss this on the slack channel as well, but nobody gives their opinion. Maybe what I would like the autoscaler to do is just too complex?
