### ISSUE TITLE
Behavior wrt min/max limits is not publicly documented

### ISSUE THREAD

**Issue by Shnatsel** [kubernetes/autoscaler#1849]
[Cluster autoscaler FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md) does not describe how CA handles min/max limits.

People often expect min/max to be enforced by CA, and that changing the minimum number of nodes alone will trigger a scale-up ([example](https://b.corp.google.com/issues/129746085)). The actual behavior is that CA does not enforce these limits, so if someone manually resizes the cluster beyond those limits, CA will not intervene.

Since this is a common cause of misunderstanding, we need some public documentation on the expected behavior.

**Comment by MaciekPytel** [comment]
You're 100% right, this should be documented. Do you want to take a shot at writing it up?

**Comment by Shnatsel** [comment]
Sure. I'll open a PR to get the ball rolling, and check "allow edits from maintainers" so that you can correct anything I got wrong.

**Comment by Jeffwan** [comment]
I have an issue related here. https://github.com/kubernetes/autoscaler/issues/1559

Auto-Discovery is preferred and min/max does brings confusion. I didn't come up good solutions on code side, documentation will be helpful.
