### ISSUE TITLE
[vertical-pod-autoscaler] The README is hard to read/understand

### ISSUE THREAD

**Issue by zedtux** [kubernetes/autoscaler#1853]
Please move all the migration instructions in a Wiki page or a `MIGRATE.md` file or something like that keeping [the `README.md` file](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md) cleaner so that new comers (like me) aren't spammed, therefore lost, with useless information.

**Comment by Rajat-0** [comment]
I can do this if Leads agree.

**Comment by bskiba** [comment]
Sounds good, thanks @zedtux and @Rajat-0

**Comment by zedtux** [comment]
Thank you @Rajat-0 👍
