### ISSUE TITLE
Magnum cloud provider includes master node in node group

### ISSUE THREAD

**Issue by tghartland** [kubernetes/autoscaler#1870]
The assumption for the single node group in the magnum autoscaler was that it covers the entire cluster. But since the master node is also registered in kubernetes the cloud provider was including it as a member of the node group as well.

This is the cause of the issue discussed in #1690 where having a single cordoned minion node in the cluster does not allow a scale up. The autoscaler sees that the cordoned minion should not be used in simulations and uses the master node as the template for a healthy node in the node group instead. The pending pods could not be scheduled if another master node was added, so no scale up is triggered.

By excluding the master from the node group
```go
 func (os *magnumCloudProvider) NodeGroupForNode(node *apiv1.Node) (cloudprovider.NodeGroup, error) {
        // TODO: wait for magnum nodegroup support
+       if _, found := node.ObjectMeta.Labels["node-role.kubernetes.io/master"]; found {
+               return nil, nil
+       }
        return &(os.nodeGroups[0]), nil
 }
```
the autoscaler falls back to using a cached version of the minion node from before it was cordoned as the template, and a scale up is possible.

I can make the PR for this tomorrow but I need to do some more testing first.
This needs to be fixed before the magnum cloud provider is included in a patch release of 1.14, as it is necessary for @openstacker for cluster auto healing.

**Comment by openstacker** [comment]
@tghartland Thanks for working on this. Really appreciate it. Cheers.

**Comment by openstacker** [comment]
@tghartland When I testing the auto scaling feature, sometimes I saw the master node is being rebuilt (delete and recreate) accidentally, though the annotation `cluster-autoscaler.kubernetes.io/scale-down-disabled=true` has been set for those master nodes. Do you think the fix you mentioned in this issue could also fix that? Thanks.

**Comment by tghartland** [comment]
@openstacker Diogo had the same issue with the master node disappearing and being rebuilt during scaling, but we think it was just a glitch due to the heavy load in devstack.

@strigazi suggests checking the event logs and creating an issue for magnum to track this, instead of here
```
openstack server event list strigazi-test-01-2rxqaudiu5me-master-0
openstack stack event list --nested-depth 2 strigazi-test-01-2rxqaudiu5me
```

**Comment by openstacker** [comment]
No useful information from those two commands. And I think it's mostly like an issue on AutoScaler side though I'm OK to track it on Magnum side. Could you please login #openstack-containers so that we can have a quick catch up? Thanks.
