### ISSUE TITLE
[addon-resizer] deployment update drops existing toleration fields

### ISSUE THREAD

**Issue by djsly** [kubernetes/autoscaler#188]
Probably due to the version of the k8s go client used by the addon-resizer 

```
#kubectl create -f heapster-controller.yaml
deployment "heapster" created
# kubectl get deployment heapster -o yaml | grep tolerations -A6
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: role
        operator: Equal
        value: k8s-edge-node
# kubectl get deployment heapster -o yaml | grep tolerations -A6
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: role
        operator: Equal
        value: k8s-edge-node
# kubectl get deployment heapster -o yaml | grep tolerations -A6
# kubectl get deployment heapster -o yaml | grep tolerations -A6
```

Go client version
```
       {
            "ImportPath": "k8s.io/kubernetes/pkg/client/clientset_generated/release_1_3",
            "Comment": "v1.3.0-alpha.5-165-g7476d97",
            "Rev": "7476d97781563b70e8b89a8bd3f99ea75ae6c290"
        },
```

**Comment by djsly** [comment]
@piosz @wojtek-t @Q-Lee

**Comment by djsly** [comment]
@x13n @MaciekPytel  since you guys seems to be the new owner :)

**Comment by x13n** [comment]
PodSpec used by pod_nanny (via DeploymentInterface -> Deployment -> DeploymentSpec -> PodTemplateSpec) doesn't have Tolarations field defined, looks like it's using an older definition of Pod. Old godeps?

**Comment by djsly** [comment]
looks like it indeed, from my understanding it is using an old k8s go client. version `v1.3.0-alpha.5-165-g7476d97`

**Comment by djsly** [comment]
I will try to find time for this as well, I had a question, how can I know the version of GO used by all of the different k8s projects? when I started to look at fixing, I got stuck at `which version of GO do I need` :)

**Comment by piosz** [comment]
@djsly there is something in godeps https://github.com/kubernetes/autoscaler/blob/master/addon-resizer/Godeps/Godeps.json#L3, though there is not guarantee it was built with this version.

**Comment by mwielgus** [comment]
@piosz - kubernetes/autoscaler contains the new version that has not been fully release yet. The old one lived in kubernetes/contrib.

**Comment by djsly** [comment]
This is fixed in the latest release, closing.

**Comment by seh** [comment]
Which release is that? I still see this behavior—for both the "tolerations" and "affinity" fields in the pod spec—using the container image _k8s.gcr.io/addon-resizer:1.7_.

**Comment by seh** [comment]
Ah, I see there was a release of [version 1.8.1 on 8 December 2017](https://github.com/kubernetes/autoscaler/releases/tag/addon-resizer-1.8.1).

**Comment by seh** [comment]
Version 1.8.1 does not parse command-line flags properly (per #559). There is also a later container image _k8s.gcr.io/addon-resizer:1.8.3_ that's free of that problem.
