### ISSUE TITLE
scale down time manipulation

### ISSUE THREAD

**Issue by hitesh1907nayyar** [kubernetes/autoscaler#1898]
Hi,

Can somebody please tell me how to reduce the scale down time in cluster-autoscaler-containerservice.yaml(azure). 

Manly i will like to manipulate the scale down waiting time before nodes scaling actually start.

Also what is the present time before it starts to scale down ?

**Comment by palmerabollo** [comment]
@hitesh1907nayyar take a look at the --scale-down-xyz parameters. You can tune them to fit your needs.

```
--scale-down-delay-after-add duration                      How long after scale up that scale down evaluation resumes (default 10m0s)
--scale-down-delay-after-delete duration                   How long after node deletion that scale down evaluation resumes, defaults to scanInterval (default 10s)
--scale-down-delay-after-failure duration                  How long after scale down failure that scale down evaluation resumes (default 3m0s)
--scale-down-non-empty-candidates-count int                Maximum number of non empty nodes considered in one iteration as candidates for scale down with drain.Lower value means better CA responsiveness but possible slower scale down latency.Higher value can affect CA performance with big clusters (hundreds of nodes).Set to non posistive value to turn this heuristic off - CA will not limit the number of nodes it considers. (default 30)
--scale-down-unneeded-time duration                        How long a node should be unneeded before it is eligible for scale down (default 10m0s)
--scale-down-unready-time duration                         How long an unready node should be unneeded before it is eligible for scale down (default 20m0s)
--scale-down-utilization-threshold float                   Node utilization level, defined as sum of requested resources divided by capacity, below which a node can be considered for scale down (default 0.5)
```

You can get the whole list with:
```
docker run --rm k8s.gcr.io/cluster-autoscaler:v1.3.9 /cluster-autoscaler --help
```

**Comment by hitesh1907nayyar** [comment]
> @hitesh1907nayyar take a look at the --scale-down-xyz parameters. You can tune them to fit your needs.
> 
> ```
> --scale-down-delay-after-add duration                      How long after scale up that scale down evaluation resumes (default 10m0s)
> --scale-down-delay-after-delete duration                   How long after node deletion that scale down evaluation resumes, defaults to scanInterval (default 10s)
> --scale-down-delay-after-failure duration                  How long after scale down failure that scale down evaluation resumes (default 3m0s)
> --scale-down-non-empty-candidates-count int                Maximum number of non empty nodes considered in one iteration as candidates for scale down with drain.Lower value means better CA responsiveness but possible slower scale down latency.Higher value can affect CA performance with big clusters (hundreds of nodes).Set to non posistive value to turn this heuristic off - CA will not limit the number of nodes it considers. (default 30)
> --scale-down-unneeded-time duration                        How long a node should be unneeded before it is eligible for scale down (default 10m0s)
> --scale-down-unready-time duration                         How long an unready node should be unneeded before it is eligible for scale down (default 20m0s)
> --scale-down-utilization-threshold float                   Node utilization level, defined as sum of requested resources divided by capacity, below which a node can be considered for scale down (default 0.5)
> ```
> 
> You can get the whole list with:
> 
> ```
> docker run --rm k8s.gcr.io/cluster-autoscaler:v1.3.9 /cluster-autoscaler --help
> ```

Thanks @palmerabollo . Can you please also let me know how to run this command ? I am not able to find any autoscaler pod in google kubernetes cluster.

**Comment by palmerabollo** [comment]
I am not familiar with Google Kubernetes Engine. The cluster-autoscaler is often in the kube-system namespace, try with `kubectl get pods -n kube-system | grep autoscaler`.
