### ISSUE TITLE
Autoscaler version

### ISSUE THREAD

**Issue by mariojacobo** [kubernetes/autoscaler#1899]
The documentation states the following :"Starting from Kubernetes 1.12, versioning scheme was changed to match Kubernetes minor releases exactly." 

However, I cannot find all the releases that should be in place for every minor.  The releases page (https://github.com/kubernetes/autoscaler/releases) only has, for example 1.12.3 and skipping straight to 1.13.2.  There are quite a lot of minor releases that are not addressed.

**Comment by MaciekPytel** [comment]
Minor release is 1.12, 1.13, etc. The last digit is a patch release - those do not track Kubernetes releases. You should generally use CA 1.12.<latest> when working with Kubernetes 1.12.X, regardless of the value of X.

**Comment by mariojacobo** [comment]
@MaciekPytel  Ok, that makes more sense now. thanks
