### ISSUE TITLE
Possible to stop the instance instead of delete it?

### ISSUE THREAD

**Issue by left4taco** [kubernetes/autoscaler#1901]
A little background. We are using AWS Kubernetes cluster as our CI platform and Gitlab runner as CI worker. A new pod will be created when there is a new job in the queue. 

The ideal situation is, there's no nodes(instances) running when there's no jobs. Once a new job comes in, CA will start a new node. But the problem is, it takes 5 minutes to initialize the node, pull the docker image of the pod. Once the job finished, the node is deleted after a period of time(5 minutes in our case). Then the process is done again for another job. 

It does save us some money by autoscaling, but also slow down the CI. Time is wasted on initializing the node and pull the image which almost remains unchanged. 

Is there any way to config the autoscaler to stop the instance instead of terminating and deleting the instance? In that way spinning up the node would be way faster than creating a new one. 

---
I know keeping one nodes running all the time would speed up the bootstrapping but that's waste of money.

**Comment by MaciekPytel** [comment]
Currently it's not supported, though we're of course open for contributions. The idea was discussed before and it seems stopping the node would be very simple. It's restarting it later on that's difficult - there is no mechanism in CA for keeping track of suspended instances and bringing them up later, currently CA is only able to request new nodes.

**Comment by left4taco** [comment]
If I understand correctly, CA jsut set the desired machine type to 0 in AWS auto scaling group. Looks like there no much CA can to to stop the machine. Closing the ticket now. Thanks
