### ISSUE TITLE
To scale up from 0, CA has to be started when there's 1 node at present

### ISSUE THREAD

**Issue by left4taco** [kubernetes/autoscaler#1906]
This is my finding while moving our CI to Kubernetes. The idea is to have a build node group, which has minimal node number of 0 so that we don't pay for the machine when there's no jobs. 

Scaling down to 0 always works. But It was weird that sometimes CA is able to scale up from 0, but some times not. The error message is like "The node doesn't match the node selector" while the node group is absolutely configured correctly. 

After numerous fail and trail, I finally found out why. It was because **CA has to be created when there's at least one node running in the group**.  

When CA is created as a `daemonset`, if there's no node running in the group, CA has no way to find out the information about the node in that group, like its capacity, label or taints. 

Looks like that's why we need a special tag to the ASG as described in FAQ
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0

**Comment by ringtail** [comment]
What does `CA has to be created when there's at least one node running in the group` mean? CA can use describe instance meta from node-group without nodes.

**Comment by left4taco** [comment]
@ringtail Yes a label on the node group can help indicate the label of the node within. But in the case where such label doesn't exist, you must have a running node when CA is started.

**Comment by ringtail** [comment]
I don't get it. Why the label is not on the node group?
