### ISSUE TITLE
Custom/external cloud provider?

### ISSUE THREAD

**Issue by VioletRainbows** [kubernetes/autoscaler#191]
Hello,

Would you be interested in an external cloud provider? This would allow the creation of new machines with specific requirements.

**Implementation**
https://github.com/VioletRainbows/autoscaler/blob/external/cluster-autoscaler/cloudprovider/external/external_cloud_provider.go
Please note that it is a work in progress.

**Implementation details**
New cloud provider that calls (http) an external server that can add and remove nodes.
autoscaler -> external cloud provider -> [homemade API server able to create machines]

Three endpoints would need to be implemented by the user for a default configuration; for instance:
- nodeGroups - http://127.0.0.1/api/v1/nodes
- IncreaseSize - http://127.0.0.1/api/v1/scaleUp/{size}
- DeleteNodes - http://127.0.0.1/api/v1/scaleDown/{name}

We are currently using it to scale our Azure architecture at my workplace.

**Comment by mwielgus** [comment]
The idea is nice, however: 
 * we want to have the full CloudProvider interface externalized,
 * we are expecting couple changes/addition to this interface in the near future, 
 * we don't have a capacity to design the proper/stable api in this (K8S 1.8) release cycle. 

So we would rather wait post-1.8 with designing/committing to any external api/interface.

**Comment by VolkerKozlowski** [comment]
Hi,
have there been started any efforts to define an external interface an external Cloud Provider has to implement in order to provide autoscaling infrastructure? We are just started working on an external cloud provider for azure and would be happy to contribute. Later on we would like to have solutions for Open Telekom Cloud and vmWare as well. Hopefully only one interface for all :-) I like the idea of @VioletRainbows very much.

**Comment by zonca** [comment]
@VioletRainbows thanks for sharing your code! I am trying to deploy your external cluster autoscaler, do you have an example `yml` to deploy the autoscaler on the master node?
Similar to the setup for other cloud providers: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-standard-master.yaml

**Comment by VioletRainbows** [comment]
Here is an example of a .yml file:

Launch with `--cloud-config=cloud-config.yml`
```
---
nodesURL: "http://127.0.0.1:8080/api/v1beta/autoscaler/nodes"
scaleUpURL: "http://127.0.0.1:8080/api/v1beta/autoscaler/scaleUp/{nodeGroupID}/{size}"
scaleDownURL: "http://127.0.0.1:8080/api/v1beta/autoscaler/scaleDown/{nodeGroupID}/{nodeID}"
```

Note that I haven't touched this project in almost a year, and I am no longer working at the company where this code was used.

**Comment by zonca** [comment]
thanks! do you happen also to still have a yml for `kubectl create -f` to create a deployment or a pod to launch this on the master node?

**Comment by VioletRainbows** [comment]
I'm sorry, I do not.

**Comment by MA357151** [comment]
> Hello,
> 
> Would you be interested in an external cloud provider? This would allow the creation of new machines with specific requirements.
> 
> **Implementation**
> https://github.com/VioletRainbows/autoscaler/blob/external/cluster-autoscaler/cloudprovider/external/external_cloud_provider.go
> Please note that it is a work in progress.
> 
> **Implementation details**
> New cloud provider that calls (http) an external server that can add and remove nodes.
> autoscaler -> external cloud provider -> [homemade API server able to create machines]
> 
> Three endpoints would need to be implemented by the user for a default configuration; for instance:
> 
> * nodeGroups - http://127.0.0.1/api/v1/nodes
> * IncreaseSize - [http://127.0.0.1/api/v1/scaleUp/{size}](http://127.0.0.1/api/v1/scaleUp/%7Bsize%7D)
> * DeleteNodes - [http://127.0.0.1/api/v1/scaleDown/{name}](http://127.0.0.1/api/v1/scaleDown/%7Bname%7D)
> 
> We are currently using it to scale our Azure architecture at my workplace.

Hi VioletRainbows,

I am trying to implement similar stuff. It would be really helpful if you can share code.

Thanks!
Mayank
