### ISSUE TITLE
Cluster Autoscaler can get stuck in pending if HPA scales too many pods and CA restarts

### ISSUE THREAD

**Issue by Moofasax** [kubernetes/autoscaler#1946]
This is not an issue of CA code functionality so i apologize if this is the wrong place for posting this issue.

## Problem:
We have noticed when running through the [HPA example](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/) on our AWS clusters, that HPA will scale out the number of pods as expected until pods are stuck in, "Pending", however, if the CA pod restarts, then the CA pod is now stuck in pending and you never scale. This happens pretty often.

Any strategies for mitigating this?

## Possible Solution:
I am not a Kubernetes expert and i have read its never good to run anything extra on the master, but would it be detrimental to the master to allow the CA pod to also run on master node?

**Comment by MaciekPytel** [comment]
We actually recommend running CA on master (at least that's how we do it in GCE). If you want to run it in cluster you can give CA pod a sufficiently high [pod priority][1] to guarantee it will have space to run.

[1]: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

**Comment by Moofasax** [comment]
Understood, we will explore pod priority but most likely end up scheduling it on the master.
Thanks for the help, I will close!
