### ISSUE TITLE
Scale in of GPU node group sometimes results in 2 nodes being created

### ISSUE THREAD

**Issue by stefansedich** [kubernetes/autoscaler#1949]
I am experiencing some odd behaviour running on EKS when scaling out my GPU node groups which results in 2 nodes being created, I think it is related to the nvidia-device-plugin having a delay in setting the available GPU after a node comes up, the following seems to happen:

1. Schedule pod with GPU taint and GPU resource request with no GPU nodes in cluster
2. CA picks up that a node needs to be created and correctly creates a node in a GPU node group
3. The node comes up
4. CA sees that the node does not have any available GPU resources and decides to scale out another node group
5. The first node appears to get assigned the GPU resource once the nvidia device plugin starts and the pod schedules successfully
6. There is now another node created which goes away after 15 minutes

Is there a way to handle this correctly so that I am not spinning up an extra uneeded node? it appears to not always happen and sometimes will work as expected.

**Comment by Jeffwan** [comment]
Yes. You need to create GPU label to your node groups. 
I added GPU Label for aws in https://github.com/kubernetes/autoscaler/pull/1584. But this has not been cherry-picked back to older version. Instead, you can add following label when you create new node groups. 

You can use other strings to replace `nvidia-tesla-k80`

```
--kubelet-extra-args --node-labels=cloud.google.com/gke-accelerator=nvidia-tesla-k80
```

**Comment by stefansedich** [comment]
Thanks @Jeffwan!

Looking at it does it matter what the gpu type string even is? digging through the code I cannot see the how it is use, using a g3s this is a Tesla m60 but this is not in the supported GPUs list, what is the imporance of the supported GPU list and what is the intended future purpose of this value?



Thanks!

**Comment by vikaschoudhary16** [comment]
+1 @stefansedich !!
IIUC, CA triggers to scale out if pods are in pending state and since scheduler will schedule pods only if GPUs are reported in node status by device plugins and not based on node labels and thus this extra node will still be created.

One possible solution could be to use labelSelector as well in the pod spec. Then `--node-labels` will help.

**Comment by Jeffwan** [comment]
> Thanks @Jeffwan!
> 
> Looking at it does it matter what the gpu type string even is? digging through the code I cannot see the how it is use, using a g3s this is a Tesla m60 but this is not in the supported GPUs list, what is the imporance of the supported GPU list and what is the intended future purpose of this value?
> 
> Thanks!

GPU type doesn't matter in this case, `value` is reserved for other purpose. Make sure you have key `cloud.google.com/gke-accelerator`. There's a method to check if node is GPU node which relies on this label.

**Comment by stefansedich** [comment]
Thanks @Jeffwan will give this a go, can you share any info on what the future use of the value might be for my own interests?

**Comment by stefansedich** [comment]
Thanks @Jeffwan this appears to be working, closing this issue off.

**Comment by Jeffwan** [comment]
@stefansedich 

Right now, AFAIK,  none of cloud provider use this type now. It could be used for scale up strategy or something else. If you have any use cases or requirements, please let me know. Thanks!
