### ISSUE TITLE
Do not run as root by default in Docker

### ISSUE THREAD

**Issue by der-eismann** [kubernetes/autoscaler#1972]
IMHO it is accepted as best practice to not run [processes in containers as root](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b). I'm not sure if this was discussed before or if root permissions are in fact needed for the scalers to work, but it would be nice if we could change this.

**Comment by aleksandra-malinowska** [comment]
Sounds reasonable, I don't think they're needed for anything. @bskbia @MaciekPytel - are you OK with this?

**Comment by bskiba** [comment]
SGTM
