### ISSUE TITLE
Ability to pause the autoscaler based on a tag in the AutoScaling Group

### ISSUE THREAD

**Issue by achinthagunasekara** [kubernetes/autoscaler#1976]
It would be really nice to have a feature to pause node autoscaler based on a tag in the autoscaling group (AWS) and have the ability to pass in the tag when node autoscaler starts.

E.G `--pause-tags=pause-node-autoscaler`

Then we should be able to add the tag `pause-node-autoscaler` to the ASG and have autoscaler pause any autoscaling activities.

**Comment by MaciekPytel** [comment]
Why not just just temporarily disable autoscaling for that ASG? How is this different?

**Comment by achinthagunasekara** [comment]
@MaciekPytel
Issue with that is, we'd have to update your Kube deployment for Autoscaler every time we roll the ASG. With this approach, it's all handled by adding/removing a tag to the ASG.

**Comment by aleksandra-malinowska** [comment]
Isn't it already possible when using autodiscovery? From [FAQ](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#auto-discovery-setup):

> It is recommended to use a second tag like k8s.io/cluster-autoscaler/<YOUR CLUSTER NAME> when k8s.io/cluster-autoscaler/enabled is used across many clusters to prevent ASGs from different clusters recognized as the node groups

This sounds like you should be able to enable/disable autoscaler just by changing the tags, without autoscaler restart?

**Comment by MaciekPytel** [comment]
There are 2 parallel discussions on this (here and on https://github.com/kubernetes/autoscaler/pull/1977). Let's continue on https://github.com/kubernetes/autoscaler/pull/1977 to avoid duplication.

**Comment by Jeffwan** [comment]
We have two PRs to help reduce API calls. #1935 #1841  Please check if you still have throttling issue or not using  autodiscovery
