### ISSUE TITLE
VPA 0.5.1 remote error: tls: bad certificate

### ISSUE THREAD

**Issue by FayeGibbins** [kubernetes/autoscaler#1979]
Using VPA 0.5.1 on k8s 1.11.9
The vpa-admission-controller pod is logging:

2019/04/30 14:06:10 http: TLS handshake error from x.x.x.x:48724: remote error: tls: bad certificate

How can I debug this please? The remote is the APi-master.

**Comment by FayeGibbins** [comment]
Aha! If you look in https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh
there is both vpa- and vpa_ used in CN's. one for hte CA and one for the cert.
Can they both be consistent please? Either vpa- or vpa_ for bth please?

**Comment by bskiba** [comment]
Hm, I think that if this was the problem, our e2e tests would fail and they seem to be working fine. Were you able to test successfully with the suggested fix? 
Also, contributions are very welcome :)

**Comment by rsreeni** [comment]
Hi,

I have a MAC webhook, that is getting the same error. Any additional info on this ?

Thanks,

-Sreeni
