### ISSUE TITLE
vertiacal-pod-autoscaler: how to configure for integration with prometheus(by custom.metrics.k8s.io,not metricsserver)

### ISSUE THREAD

**Issue by lovebaby979** [kubernetes/autoscaler#2001]
I read other issues(#1551,#1809),the issues explains how to config VPA for integration with prometheus, the prometheus work with metricsserver.
My prometheus work with custom.metrics.k8s.io.
I want to know: how to configure for integration with prometheus(by custom.metrics.k8s.io)

environment:
  kubernetes version:1.12
  get k8s monitoring data by custom.metrics.k8s.io.
  prometheus-adapter:v0.4.0
  vertiacal-pod-autoscaler:0.5.0

**Comment by bskiba** [comment]
VPA does not work with custom metrics atm, it works on resource metrics (CPU, memory). To use prometheus you need to have the resource metrics api (metrics.k8s.io) backed by prometheus.
You can try the [#sig-instrumentation](https://kubernetes.slack.com/messages/C20HH14P7/convo/C09R1LV8S-1556579721.042300/) for help on setting that up.

**Comment by lovebaby979** [comment]
Thank you @bskiba
