### ISSUE TITLE
GCE: Allow unknown key-value pairs in /etc/gce.conf

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/autoscaler#201]
Hello,

I'm requesting that the vendored GCE cloudprovider be updated so the autoscaler will have https://github.com/kubernetes/kubernetes/pull/49594 which allows config readers of `/etc/gce.conf` to ignore unknown key-value pairs. The latest GCE Ingress Controller (v0.9.6) was updated to have this change and has been cherry picked into K8s 1.7.4. 

Thanks

cc @bowei @freehan @MrHohn

**Comment by mwielgus** [comment]
Godeps updated for HEAD.

**Comment by nicksardo** [comment]
Could we record which CA version (and K8s version) will have this change? 

Thanks!

**Comment by mwielgus** [comment]
Depends. The change has not yet been cherry-picked to CA release shipped with 1.7

**Comment by mwielgus** [comment]
Shipped with 1.7.4
