### ISSUE TITLE
"safe-to-evict:false" label does not prevent node from scaling down ? 

### ISSUE THREAD

**Issue by xinxingliu90** [kubernetes/autoscaler#2027]
My purpose is to prevent a node from scaling down when there are running pods on them.

Based on this doc: -https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node, 

I label all my pods with: **cluster-autoscaler.kubernetes.io/safe-to-evict: false**

But still, I noticed some nodes scale down and my running pods on them just failed :(  

I DID set **scale-down-utilization-threshold=0.5** in my cluster autoscaler config because I want node to terminated when it is not that busy. But I do expect the "safe-to-evict: false" label can ensure nodes NOT scale down when there are running pods on them. 

What do you think the real reason that cause my node to scale down?

Thank you so much!

**Comment by xinxingliu90** [comment]
Kindly ping @Jeffwan because you resolved my previous autoscaling issue so well :)

**Comment by Jeffwan** [comment]
@xinxingliu90  Can you also check this issue? https://github.com/kubernetes/autoscaler/issues/1852

If you can attach CA logs, that would be helpful for us to debug the issue. @xinxingliu90 BTW, do you get my email?

**Comment by Jeffwan** [comment]
Probably same issue here. https://github.com/kubernetes/autoscaler/issues/1852#issuecomment-488590142

**Comment by xinxingliu90** [comment]
Oops:
```
00 UTC m=+21.428237532
F0516 01:06:13.783168       1 main.go:284] Failed to create autoscaler: Expander priority not supported
```

**Comment by xinxingliu90** [comment]
> @xinxingliu90 Can you also check this issue? #1852
> 
> If you can attach CA logs, that would be helpful for us to debug the issue. BTW, do you get my email?

Thank you ! I did receive your email and I will look into both of your pull request.

**Comment by Jeffwan** [comment]
> Oops:
> 
> ```
> 00 UTC m=+21.428237532
> F0516 01:06:13.783168       1 main.go:284] Failed to create autoscaler: Expander priority not supported
> ```
> 
> My cluster autoscaler version is 1.12.3
> Which is the correct version of cluster-autoscaler if our team would like to use expander=priority?

Priority changes has been merged into master recently, even 1.14 doesn't have this feature now. Could you test this feature separately?

**Comment by xinxingliu90** [comment]
> > Oops:
> > ```
> > 00 UTC m=+21.428237532
> > F0516 01:06:13.783168       1 main.go:284] Failed to create autoscaler: Expander priority not supported
> > ```
> > 
> > 
> > My cluster autoscaler version is 1.12.3
> > Which is the correct version of cluster-autoscaler if our team would like to use expander=priority?
> 
> Priority changes has been merged into master recently, even 1.14 doesn't have this feature now. Could you test this feature separately? Once you need expander, you can build latest version.

@Jeffwan 
Hi Jeff, I looked at your latest change a month ago, and found out that it is already the image I use: - image: k8s.gcr.io/cluster-autoscaler:v1.12.3. 

Are there more change other than apply the `autoscaler/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-multi-asg.yaml` to cluster?

Thanks!

**Comment by Jeffwan** [comment]
@xinxingliu90  I am trying to understand your requirement. What feature/change you mean in the v1.12.3?  How many regions in your cluster? Normally for machine learning training workloads, we suggest to use single availability zone

**Comment by xinxingliu90** [comment]
@Jeffwan, would you like me to open a AWS support ticket to EKS team and ask the one who answered the ticket to assign it to you? We can build direct communication this way. What do you think?

**Comment by Jeffwan** [comment]
> @Jeffwan, would you like me to open a AWS support ticket to EKS team and ask the one who answered the ticket to assign it to you? We can build direct communication this way. What do you think?

Sure. That's why I asked you to reach out to me through email or other ways. Please create a ticket and ask support team reach out to me. I also add you on LinkedIn.

**Comment by Jeffwan** [comment]
Leave a comment for users who look at this ticket. 

If user use multiple availability zones, there's possibility that nodes are not balanced. For example, some AZs run out of capacity(frequently happen for P3 instances), ASG will try to rebalance AZs if some AZ was unhealthy and back to health again, or new AZ has enough resources.

Suspend `AZRebalance ` will help in this case. This is a feature in ASG.  Please check following doc.
https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html

Besides that, for GPU users
1. GPU resources was not calculated in scaling down. For example, if cpu/memory usage is low but all GPUs are in use, it's still be considered as scale down candidate.  Check this PR for details https://github.com/kubernetes/autoscaler/pull/1589. User need to label nodes and use new version CA which has this change. 
https://github.com/kubernetes/autoscaler/pull/1562 Here's the documentation with more details.
2. Add "safe-to-evict:false" to make sure in-flight jobs are not interrupted. 
3. Better for ML training users to use single AZ to improve network performance and GPU utilization rate.
