### ISSUE TITLE
cluster-autoscaler works improperly with several kubernetes clusters in the same region

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#204]
Moved from: https://github.com/kubernetes/contrib/issues/2711
Author: @it-svit

I have two clusters in two different VPCs. 
But single cluster autoscaler is trying to affect both clusters.
```
I0808 15:01:14.854588       1 aws_manager.go:190] Regenerating ASG information for kube1-Nodepool2-1BK23XPH5999G-Workers
I0808 15:01:14.888882       1 aws_manager.go:190] Regenerating ASG information for kube2-Nodepool1-1303RAB6NXCBX-Workers
E0808 15:01:14.925243       1 static_autoscaler.go:219] Failed to scale up: failed to find template node for node group kube2-Nodepool1-1303RAB6NXCBX-Workers
W0808 15:01:14.925281       1 clusterstate.go:237] Failed to find readiness information for kube2-Nodepool1-1303RAB6NXCBX-Workers
W0808 15:01:14.925287       1 clusterstate.go:271] Failed to find readiness information for kube2-Nodepool1-1303RAB6NXCBX-Workers
```

**Comment by mwielgus** [comment]
@it-svit - Which K8S/CA version are you using?
cc: @mumoshu

**Comment by mumoshu** [comment]
Hi @it-svit, thanks for trying the auto-discovery feature!
You should use CA 0.6 or later plus you should also tell the tag to identify the targeted cluster to CA.

#176 would also help understanding what was going on.

Also, FYI, in kube-aws we provide CA:

```
- --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/{{.ClusterName}}
```

The tag `kubernetes.io/cluster/{{.ClusterName}}` is used to filter ASGs inside the cluster, and the tag `k8s.io/cluster-autoscaler/enabled` is used to further filter ASGs configured to be auto-scaled.

**Comment by it-svit** [comment]
@mwielgus 
K8S version
```
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
CA version:
```
quay.io/kube-aws/cluster-autoscaler:8b7d410fc5b9dbc9b7c707994259770f15613676
```

@mumoshu 
Sadly, but `https://quay.io/repository/kube-aws/cluster-autoscaler` has no human-friendly tags.
![1501004498013](https://user-images.githubusercontent.com/14011775/29559063-b2fa782e-8736-11e7-860e-43fa15a5a76c.jpg)
I think, tags according to release version would be great!

I managed to find `8b7d410fc5b9dbc9b7c707994259770f15613676` mentioning in `https://github.com/kubernetes/autoscaler/pull/107`. It has `CA-0.6` milestone. I assume, I'm using proper CA version.

Thank you for the nice idea regarding `--node-group-auto-discovery`.
But shouldn't it be automatic, should it?
I mean, can we autodiscover current cluster name?
Will anything be changed to me if I use 3 ASG within the same cluster, but with different `kube-aws.coreos.com/role` label?

**Comment by mumoshu** [comment]
@it-svit Thanks for the feedback 👍

> I think, tags according to release version would be great!

Which tool's release version you would like the image in the quay.io repo to have? CA's or kube-aws's? Anyway, the quay.io repo is used solely for testing purpose. So, basically, I'd recommend you to use CA images from the CA official, gcr.io repo.

> I mean, can we autodiscover current cluster name?

I may be not following what you meant by "autodiscover current cluster name", but the setup explained in my prev comment https://github.com/kubernetes/autoscaler/issues/204#issuecomment-321427088 is done by default since the latest release of kube-aws - v0.9.8-rc.1.

> Will anything be changed to me if I use 3 ASG within the same cluster, but with different kube-aws.coreos.com/role label?

No. That label doesn't relate to CA and its automatic discovery feature at all!
