### ISSUE TITLE
Scale from 0, taint

### ISSUE THREAD

**Issue by okgolove** [kubernetes/autoscaler#2043]
Hello! There is the instruction how to set up scaling from 0 https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0

I have two ASG with different labels. Nodes from one of these groups are tainted with NoSchedule.  I've followed the instruction. Is there a way to add the same tag for ASG but for taint? Sometimes autoscaler scales-up wrong ASG because it doesn't know about taints and most of my pods don't have node selectors.

**Comment by vikaschoudhary16** [comment]
Have you explored autodiscover expander and priority expander already?
https://github.com/kubernetes/autoscaler/issues/1976#issuecomment-487932353

https://github.com/kubernetes/autoscaler/pull/1977#issuecomment-493651073

**Comment by okgolove** [comment]
@vikaschoudhary16 it seems it works for me, thank you.
But anyway, is it possible to implement the same feature for taints? I believe it could be the useful thing.

**Comment by tbarrella** [comment]
Yes, there's a similar label for taints; for AWS for example see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0

**Comment by okgolove** [comment]
@tbarrella thank you! I don't know how I I was able to miss that thing.
