### ISSUE TITLE
Does CA support auto-discovery of Azure VMSSs?

### ISSUE THREAD

**Issue by sonnysideup** [kubernetes/autoscaler#2051]
The documentation in this project indicates that auto-discovery is only supported for **aws** and **gce** are supported, but the code for the Azure provider seems to indicate otherwise.

https://github.com/kubernetes/autoscaler/blob/cb4e60f8d4ffb7f0836509e65ba6270738f1e15c/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L49-L58

https://github.com/kubernetes/autoscaler/blob/cb4e60f8d4ffb7f0836509e65ba6270738f1e15c/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L265-L268

Is it possible that the docs have been update since https://github.com/kubernetes/autoscaler/pull/542 was merged? I believe this _should_ support VMSS in the same way it supports AWS ASGs now.

/cc @robinkraft

**Comment by MaciekPytel** [comment]
cc: @feiskyer

**Comment by feiskyer** [comment]
@sonnysideup It's an initial working version for vmss, e.g. by setting `--node-group-auto-discovery=label:<key>=<value>`, but still not fully supported yet. e.g. minSize and maxSize couldn't be set now.

**Comment by sonnysideup** [comment]
> ...but still not fully supported yet. e.g. minSize and maxSize couldn't be set now.

@feiskyer, thank you for your response.  Just to make sure I understand this behavior, please let me frame an example and ask some questions:

### Example Setup

1. CA is deployed into K8s (in Azure) with the setting `--node-group-auto-discovery=label:foo=bar`.
1. I then create a VMSS with the label `foo=bar` and set the min/max values on that resource during creation.

### Questions

- If we can't set `minSize` nor `maxSize`, how will this behave when the CA starts managing my VMSS?
- If it's not fully-supported, what is currently supported?

**Comment by feiskyer** [comment]
It could discovery vmss based on labels, but setting minSize and maxSize is not supported yet.

**Comment by fiunchinho** [comment]
Can this be closed now after merging https://github.com/kubernetes/autoscaler/pull/2121?
