### ISSUE TITLE
Generic integration with any infrastructure operator

### ISSUE THREAD

**Issue by jnicholls** [kubernetes/autoscaler#2053]
It would be nice if the cluster-autoscaler could be setup with an arbitrary (e.g. HTTP) endpoint that is called when it has determined a scaling operation should occur, so that all of its scaling heuristics and logic could be used for more than the cloud providers it supports and allowing users to use it everywhere (private clouds, unsupported cloud providers, etc.).

**Comment by jnicholls** [comment]
Sorry, this appears to have already been spoken about in #1050, #984 and #191. I understand there is a Cluster API in the works, which is great to hear. I've love to know what the latest status of that undertaking is.

**Comment by lfloris** [comment]
Has there been any progress on this? It would be great to get something like this working for private clouds and other providers outside of the supported list
