### ISSUE TITLE
add Hetzner support

### ISSUE THREAD

**Issue by hadifarnoud** [kubernetes/autoscaler#2054]
Hetzner cloud has a kubernetes controller manager. I assume the support for autoscaler can be added

https://github.com/hetznercloud/hcloud-cloud-controller-manager

**Comment by MaciekPytel** [comment]
I'm not sure what exactly is your question here? We accept new cloud provider implementations on condition that they don't modify global vendor/ and they don't introduce license-related problems.
Implementation wise - Cluster Autoscaler uses a completely different interface to talk to cloud provider, having working controller-manager doesn't help you at all. Implementing cloud provider support for CA is unfortunately a serious task (most existing implementations are >5k LOC).

**Comment by hadifarnoud** [comment]
I didn't realize how hard it is.

**Comment by ilkarataev** [comment]
What you mean LOC- line of code?

**Comment by alexanderkjeldaas** [comment]
The [digital ocean](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/digitalocean) autoscaler implementation looks like its less than 500 loc, mostly boilerplate.

**Comment by MaciekPytel** [comment]
Yeah, DO is much simpler than all previously existing implementations.
A lot of complexity comes from supporting scale-from-0 and optimizing for very large clusters (thousands of nodes in multiple nodepools), but if you don't care about this and just want basic support, DO is by far the best example to follow.

**Comment by Fgruntjes** [comment]
We started an implementation for the Hetzner Cloud in #3640

**Comment by hadifarnoud** [comment]
I cannot contain my excitement. can't wait

**Comment by ErwinSteffens** [comment]
Hi there, is this something the should work at the moment? We are trying it out but without any luck yet.

Running the master version on a 1.20 cluster results in this error. I will check what was changed there. Is it possible to get a 1.20 compatible version somehow? I see it is not in the 1.20 release branch. 

```
I0412 14:42:51.479800       1 reflector.go:255] Listing and watching *v1beta1.CSIStorageCapacity from k8s.io/client-go/informers/factory.go:134
E0412 14:42:51.483618       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: csistoragecapacities.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler-hetzner-cluster-autoscaler" cannot list resource "csistoragecapacities" in API group "storage.k8s.io" at the cluster scope
```
