### ISSUE TITLE
DaemonSet pod not scheduling after scale up

### ISSUE THREAD

**Issue by jackdreilly** [kubernetes/autoscaler#2087]
I have a cluster with autoscaler installed and a `fluentd` DaemonSet.

After increasing the load by launching 50 pods, the autoscaler successfully stands up 8 new nodes.

The issue is that the newly scheduled pods consume all available IP's on the nodes before the `fluentd` DaemonSet-spawned pod has a chance to schedule.

Since the `fluentd` pod has a node-selector for a specific node, it cannot find another home, and the autoscaler refuses to scale up because the node selector of the pod ensures that no node will ever satisfy the `fluentd` pod's criteria.

This leaves the nodes without any monitoring via `fluentd`.

Is there a configuration for autoscaler or my DaemonSet that I'm missing that ensures that DaemonSet pods get scheduled before other pods come in?

Thank you for the help!

**Comment by jackdreilly** [comment]
I solved this problem via PriorityClass on the DaemonSet.

Feel free to close if PriorityClass is the standard solution to the scheduling problem mentioned above

**Comment by rocketraman** [comment]
I had the same problem, thanks for providing your solution. Would be great if there was something in the docs or an FAQ entry about this.

**Comment by MaciekPytel** [comment]
We're very happy to accept any contribution to docs / FAQ about this, if anyone wants to give it a shot.
