### ISSUE TITLE
AWS AutoDiscovery ASG Limits

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes/autoscaler#209]
I'm running Kubernetes V1.6.4, CA V0.6.0 with autodiscovery of ASGs on AWS. If I change the maximum or minimum number of nodes in the AWS console, these changes are not reflected in the AutoScaler's config.

I chose to use the autodiscovery as I thought it would enable me to keep a single source of truth for ASG limits.

If I decrease the maximum number of nodes in AWS, CA can try to scale up but will throw an error when aws declines the request.

If I increase the maximum number of nodes in AWS, because the cluster has run out of resource, CA doesn't notice this and won't scale up even though there is capacity to

Given that AWS is constantly being polled for updates to the ASG, shouldn't changes in max/min number of nodes be updated? 

I'm not sure whether this behaviour has been implemented and isn't working or whether this would be classed as a feature request but it definitely seems like the intuitive behaviour of the autodiscovery

**Comment by MaciekPytel** [comment]
cc: @mumoshu

**Comment by mumoshu** [comment]
Hi @JoelSpeed, thanks for the report 👍 

> I chose to use the autodiscovery as I thought it would enable me to keep a single source of truth for ASG limits.

Yes, this is the intended use-case of the auto-discovery feature.

> Given that AWS is constantly being polled for updates to the ASG, shouldn't changes in max/min number of nodes be updated?

Yes, changes in an ASG's min/max size should be read from and synced to CA when the auto-discovery feature is configured correctly.

---

Would you mind helping me to clarify several things came up in my mind?

* How did you provision your k8s cluster?
* How may k8s clusters in your AWS account?
* Could you share us the YAML definition of the CA deployment?
* What tags are assigned to your ASG?
* Could you share us the result of `kubectl logs <your CA pod name>` so that we can see if there're error(s)

**Comment by JoelSpeed** [comment]
Hi @mumoshu :)

Thanks for your reply, to answer your questions:

>How did you provision your k8s cluster?

Custom EC2 instances (CoreOS + cloud-config) deployed via terraform

>How may k8s clusters in your AWS account?

3 presently, but there could be more

>Could you share us the YAML definition of the CA deployment?

`---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
    spec:
      containers:
        - image: gcr.io/google_containers/cluster-autoscaler:v0.6.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=true
            - --balance-similar-node-groups=true
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=cluster-autoscaler/enabled,cluster/deneb
          env:
            - name: AWS_REGION
              value: us-east-1
          ports:
          - name: http
            containerPort: 8085
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
`

>What tags are assigned to your ASG?

![screen shot 2017-08-10 at 10 42 55](https://user-images.githubusercontent.com/9232216/29164855-d6838e2a-7db8-11e7-9946-f35e0248b023.png)


>Could you share us the result of kubectl logs <your CA pod name> so that we can see if there're error(s)

Not sure how much you wanted so tailed the last 10mb of it
ca-log
[ca-log.txt](https://github.com/kubernetes/autoscaler/files/1214443/ca-log.txt)


Hope that helps to clarify everything

The autoscaler itself is working and is scaling up and down, obeying limits, autodiscovering all of our ASGs that are tagged appropriately, just not detecting changes to ASG limits

**Comment by JoelSpeed** [comment]
I've had another look through the codebase and found 

https://github.com/kubernetes/autoscaler/blob/44e0897fa7e03a9ec4320d895bdd165fdb8b0609/cluster-autoscaler/core/polling_autoscaler.go#L91-L92

I think this is wrong, I think the ASG should be considered changed when the min/max values change.

It seems the only way to update the values is by recreating the autoscaler so should some logic be added here to compare the min/max values?

**Comment by vainu-arto** [comment]
/remove-lifecycle stale

This is an actual bug in the code that needs a fix.

**Comment by aermakov-zalando** [comment]
Any updates on this? @fejta

**Comment by StevenACoffman** [comment]
This appears related to #647

**Comment by whereisaaron** [comment]
Had the same experience with ca 1.0.5 with k8s 1.8.13 on AWS with autodiscovery. When I change the min/max cluster size, the cluster-autoscaler never updates to match. Then it make incorrect scaling decisions base on the old ASG settings.

**Comment by MaciekPytel** [comment]
This should probably be updated somewhere around https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L130, but I don't have access to AWS, so no way to test anything.

**Comment by whereisaaron** [comment]
@MaciekPytel maybe that code is there and works in a newer version? Does 1.1 or 1.2 detect AWS changes?

**Comment by gjtempleton** [comment]
We're running v1.1.2 with K8s v1.9.8 and see the same behaviour, having to restart the CA to pick up changes in the ASG limits.

**Comment by MaciekPytel** [comment]
@whereisaaron No idea, as I said I don't have AWS account, so no way to test. Looks like it is actually done inside asgCache.regenerate(), so there is a good chance the problem is fixed in CA 1.2.

The problem is the whole autodiscovery was completely re-implemented in 1.2, so the fix can't be simply backported. To fix the old implementation you'd probably have to look into core/polling_autoscaler.go.

**Comment by vainu-arto** [comment]
/remove-lifecycle stale

As far as I understand this bug still exists.
