### ISSUE TITLE
Cherry-pick #1970 into next minor releases

### ISSUE THREAD

**Issue by rochacon** [kubernetes/autoscaler#2114]
#1970 added new AMD powered AWS instances types, but those did not land into any minors <= 1.14.

Could we cherry-pick #1970 into next minor releases for >= 1.12?

**Comment by Jeffwan** [comment]
This has been cherry-picked in #2229  #2230 #2231

**Comment by Jeffwan** [comment]
@rochacon Thanks for reporting the issues! I will close the issue and feel free to leave comments.
