### ISSUE TITLE
How to set up AKS with Managed Identity?

### ISSUE THREAD

**Issue by markusdresch** [kubernetes/autoscaler#2115]
i have installed cluster-autoscaler with this yaml: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml

the cluster-autoscaler pod stays in "Pending" state forever though. unfortunately it does not output any logs either, so i'm not sure how to debug this issue.

is there some documentation on the prerequisites for using managed identity? from the yaml and description it's not that clear which resource group and subscription should be used. it's also not clear to me how the managed identity should be set up for aks autoscaling.

what i got now is:
- 1 aks with vmss enabled. 
- 1 managed identity in a different resource group and subscription.
- 1 pending cluster-autoscaler pod with no output

**Comment by feiskyer** [comment]
MSI is not supported yet on AKS. Actually, there're now more easier way to enable CA on AKS, see https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler.

/close
