### ISSUE TITLE
VPA : Lower Bound remains constant for all deployment objects

### ISSUE THREAD

**Issue by jvaibhav123** [kubernetes/autoscaler#2125]
Dear Team,

We have deployed the VPA on test cluster using the script mentioned in repo file. The deployment seems to be successful as we do not see any error messages in logs. (Any other way to confirm if its installed successfully and get all metric info?)
We have created the VPA configuration for our deployment objects and we could see the lower bound values remain same for all objects.

Recommendation:
    Container Recommendations:
      Container Name:  test-query
      Lower Bound:
        Cpu:     25m
        Memory:  262144k
      Target:
        Cpu:     25m
        Memory:  262144k
      Uncapped Target:
        Cpu:     25m
        Memory:  262144k
      Upper Bound:
        Cpu:     62m
        Memory:  262144k

The actual usage in prometheus for container test-query is 20Mi memory. We have metric server running our cluster. Also i am curious how VPA gets metrics as in configuration files i do not see any configuration. Is there any configuration documentation available?

**Comment by milesbxf** [comment]
@jvaibhav123 this isn't well documented at the moment, but there is a `--pod-recommendation-min-memory-mb` flag which determines the minimum amount of memory the recommender will set - it defaults to 250MB, which I believe is what you're seeing here 🙂 

https://github.com/kubernetes/autoscaler/blob/d81bdb87ce5d6801d0030f02c2e96080b53a209e/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L28

**Comment by bskiba** [comment]
Yeah, @milesbxf is right. You can override that flag with a lower value if needed.
/close

@jvaibhav123 if you find the time, could you add this information to VPA [FAQ](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/FAQ.md)?

**Comment by dzarmola** [comment]
A noob-y question, but I'm running into the same problem - how can I override this flag?

**Comment by bskiba** [comment]
You can override the recommender arguments by specifying an args section in your [recommender deployment file](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/recommender-deployment.yaml):
```yaml
spec:
  containers:
  - args:
    - --v=4
    - --pod-recommendation-min-memory-mb=<override_value>
```
Then you deploy VPA as usual.
