### ISSUE TITLE
CA for EKS additional ASG doesn't scale down to 0

### ISSUE THREAD

**Issue by Luke035** [kubernetes/autoscaler#2126]
Hi everyone, 

I have an EKS cluster with multiple ASG: one with a min size of 1 and max size of 10 and a GPU-based ASG (min size 0 and max size 2)

The additional ASG has been created through `eksctl` with the following command: 
`eksctl create nodegroup --cluster=CLUSTER_NAME --node-type=p3.2xlarge --nodes-min 0 --nodes-max 2 --profile=eksctl-admin --region=us-east-1`

Once created, I provided the autoscaling policies to the newly created instance role. 

Scale up works perfectly: Once  a GPU is required, the ASG scales up perfectly, but when I delete all the pods that require GPU the cluster doesn't scale down the GPU ASG back to 0.
The CA logs are: 
`Skipping ip-192-168-42-220.ec2.internal - node group min size reached`

min size has been set to 0, I checked in the ASG and the min size is still set to 0 but the CA doesn't scale down. Any clue? 

CA version: 1.12.3
Kubernetes version: 1.12.7

**Comment by Jeffwan** [comment]
What's your CA configurations? Are you using node auto-discover? sorry for late response, just come back from vacation.

**Comment by Jeffwan** [comment]
@Luke035 Did you figure it out? If not, please provide more details

**Comment by Luke035** [comment]
Hi, @Jeffwan sorry for not reaching back. I figured it out: it was a problem with the AMI the EKSCTL provided (upgrading EKSCTL was enough for that purpose) and with the IAM policy attached to the ASG role.

Closing the issue
