### ISSUE TITLE
[VPA] can't set arguments only on recommender container

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/autoscaler#2162]
It will be helpful to have the possibility to add arguments to the container.

Currently, in the recommender deployment you can't add just the arguments, as they will be ignored. You have to also add the command overwrite, that it's not so intuitive to find out (./recommender).

By adding a CMD line, this can be solved as in https://stackoverflow.com/a/34245657/451348

Affected file:

https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Dockerfile

**Comment by Denton24646** [comment]
I can open a PR for this 👍

**Comment by cristifalcas** [comment]
thank you
