### ISSUE TITLE
[VPA] how are recommendations calculated

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/autoscaler#2164]
Hi, can you give an explanation on how recommendations are computed?

There is an explanation in code on  [how eviction works](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L114) but I couldn't find anything related to recommendations

**Comment by bskiba** [comment]
Short description OTOH:

Usage samples (gathered every minute) for 8 days are kept in a "decaying histogram" - older samples contribute less than fresh ones.
For CPU we take a very high* percentile of all those samples + some safety margin  as the target.
For memory every day we record daily max. We take a very high* percentile of those daily max values from the last 8 days. 

*(very high) - i don't remember the exact values, but can dig them up if needed. 

IMPORTANT: This is not part of API - i.e. may be subject to change in the future and we do not consider this a breaking change. That's part of the reason it is not in docs anywhere (another part being chronic lack of time :) )

LMK if you need more details.

**Comment by cristifalcas** [comment]
Thank you @bskiba 
It's clearer now.
