### ISSUE TITLE
Scale from 0, unwanted nodes

### ISSUE THREAD

**Issue by okgolove** [kubernetes/autoscaler#2165]
Hello. I have three ASGs:
main [min:1, max: 1]
spots [min: 1, max:10]
test-asg  [min:0, max:0, tainted]

Taint is specified for ASG and instances tags.

CA always creates a new node in the `test-asg` group there are no pods being scheduled on the test ASG nodes though. Then, it deletes the node (after unneeded period) and creates again (loop).

How can I fix this?

```
I0705 09:32:44.591122       1 auto_scaling_groups.go:245] Regenerating instance to ASG map for ASGs: [spots test-asg]
W0705 09:32:44.802636       1 clusterstate.go:539] Readiness for node group test-asg not found
W0705 09:32:44.804225       1 clusterstate.go:321] Failed to find readiness information for test-asg
W0705 09:32:44.804240       1 clusterstate.go:377] Failed to find readiness information for test-asg
W0705 09:32:44.804245       1 clusterstate.go:321] Failed to find readiness information for test-asg
```

**Comment by okgolove** [comment]
relates https://github.com/kubernetes/autoscaler/pull/2008

**Comment by Jeffwan** [comment]
what's the expand strategy are you using?

**Comment by Jeffwan** [comment]
Sorry for late response. just come back from vacation :D

**Comment by okgolove** [comment]
I'm using the default expander (i.e. random).

**Comment by Denton24646** [comment]
What settings are you using when running the autoscaler (the flags)? And which version? Could be a something in the configuration causing this

**Comment by okgolove** [comment]
```
cluster-autoscaler:v1.3.3
```
```
      --cloud-provider=aws
      --namespace=kube-system
      --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/prod.test.com
      --balance-similar-node-groups=true
      --logtostderr=true
      --skip-nodes-with-local-storage=false
      --skip-nodes-with-system-pods=false
      --stderrthreshold=info
      --v=4
```

**Comment by Denton24646** [comment]
Maybe something to do with `balance-similar-node-groups=true`? By default its false

**Comment by MaciekPytel** [comment]
My guess would be scale-from-0 logic incorrectly guessing how the node would look like. CA sees the template node that would help the pending pods, so it scales up. Once the node is created it turns out it looks differently than expected and it doesn't really fit the pods. So CA deletes it. Once there are 0 nodes it goes back to using scale-from-0 template and the situation repeats.

**Comment by okgolove** [comment]
I don't like the message:
```Failed to find readiness information for test-asg```

It seems something is going wrong.
As I wrote it looks similar to #2008

**Comment by okgolove** [comment]
It seems it got fixed.
