### ISSUE TITLE
Some AWS instance types (r5.8xlarge, r5a.8xlarge) are missing

### ISSUE THREAD

**Issue by viggeh** [kubernetes/autoscaler#2179]
Hey,

I got an error in cluster-autoscaler using an ASG with `r5a.8xlarge` instances. 

```
Unable to build proper template node for *: ASG "*" uses the unknown EC2 instance type "r5a.8xlarge"
```

Looking at https://github.com/kubernetes/autoscaler/blob/d9a86611a5305c2f73096f74735e0c77d2b3fae9/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L972
I noticed that `r5.8xlarge`, `r5a.8xlarge` and `r5d.8xlarge` are all missing. We do have the 12x and 4x options though. Maybe something went wrong in the last generation run.

**Comment by jerrylam** [comment]
I'm also looking into that. I wonder if adding a new instance type is as easy as adding a new entry into this ec2_instance_types.go file? If yes, I'm more than happy to add that :)

**Comment by Jeffwan** [comment]
I can add instances and cherry-pick to all branches, release team will roll out new images next week

**Comment by Jeffwan** [comment]
Sorry for late response. Just come back from vacation :D

**Comment by Jeffwan** [comment]
> I'm also looking into that. I wonder if adding a new instance type is as easy as adding a new entry into this ec2_instance_types.go file? If yes, I'm more than happy to add that :)

Yes. That's true. Next time you can run `go run ec2_instance_types/gen.go` to get updated file.

**Comment by Jeffwan** [comment]
Changes will backport to previous versions

**Comment by Jeffwan** [comment]
new release already have new instance types. I will close this issue.
