### ISSUE TITLE
Couldn't read config: error: Failed to create GCE Manager

### ISSUE THREAD

**Issue by RsknCankov** [kubernetes/autoscaler#2192]
Hello, 
I am trying to deploy cluster-autoscaler in my GKE, when Pod boots up following error is being thrown.

Deployed by:
helm - stable/cluster-autoscaler --version 0.14.2

Kubect Version:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider : GCE

**Comment by bskiba** [comment]
Is this GKE or plan GCE? 
If GKE, did you consider using the bundled autoscaler? 
https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler

**Comment by RsknCankov** [comment]
Actually yes, there was a misunderstanding from my side. Just activated the bundled autoscaler ...
