### ISSUE TITLE
vertical-pod-autoscaler: fails on recommender init

### ISSUE THREAD

**Issue by Moriadry** [kubernetes/autoscaler#2194]
When I try to creates a new recommender instance, I meet such error info:

`35:06.399692   70404 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode to metav1.Event`

and my method is written as below: 

```bash
func TestNewCommender(t *testing.T) {
	checkpointsGCInterval := flag.Duration("checkpoints-gc-interval", 10*time.Minute, `How often orphaned checkpoints should be garbage collected`)
	storage := flag.String("storage", "", `Specifies storage mode. Supported values: prometheus, checkpoint (default)`)
	useCheckpoints := *storage != "prometheus"

	status := &metav1.Status{TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "Status"}, Status: fmt.Sprintf("%s", metav1.StatusSuccess)}
	expectedBody, _ := runtime.Encode(scheme.Codecs.LegacyCodec(metav1.SchemeGroupVersion), status)
	fakeHandler := utiltesting.FakeHandler{
		StatusCode:   200,
		ResponseBody: string(expectedBody),
		T:            t,
	}
	testServer := httptest.NewServer(&fakeHandler)
	if testServer == nil {
	}
	config := &rest.Config{
		Host: 	   testServer.URL,
		APIPath:   "v1",
		ContentConfig: rest.ContentConfig{
			GroupVersion:         &metav1.SchemeGroupVersion,
			NegotiatedSerializer:	serializer.DirectCodecFactory{CodecFactory: scheme.Codecs},
		},
	}
	defer testServer.Close()
	c, err := restClient(testServer)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if c!= nil {
		body, _ := c.Get().Prefix("test").Do().Raw()
		if body!= nil {
			result, _ := runtime.Decode(scheme.Codecs.UniversalDeserializer(), body)
			fmt.Printf("result: %s", result)
		}
	}
	recommender := NewRecommender(config, *checkpointsGCInterval, useCheckpoints)
	if (recommender == nil) {
	}
}
```

and `fmt.Printf("result: %s", result)` log shows: 

`result: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,},Status:Success,Message:,Reason:,Details:nil,Code:0,}E0717 15:37:30.191045   70462 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode to metav1.Event`

I try to figured it out, but failed. What's wrong about the decoder and streamwatcher?

**Comment by bskiba** [comment]
Can you explain what you are trying to achieve? Are you trying to mock out the API Server?

Your test server always returns a Status object. VPA Recommender tries to read multiple types of objects from the server. Also the informers try to establish a watch (https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) on the resources, and from the error message I believe this is what is failing. I don't know much about this though. Recommender has a very strong assumption that the thing it is talking to is a Kubernetes API server.
