### ISSUE TITLE
Autoscaler should not use CreatedByAnnotation

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/autoscaler#220]
Based on this [announcement](https://groups.google.com/forum/#!msg/kubernetes-dev/juMOsdaCml0/FwVNJA9uBAAJ), `CreatedByAnnotation` will be deprecated in 1.8 in favor of `ControllerRef`. However, the annotation is still used in this repo:
(1) [drain.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go#L212) 
(2) [test_utils.go](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/updater/test/test_utils.go#L49)
(3) [pods_eviction_restriction.go](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/updater/eviction/pods_eviction_restriction.go#L230)
(4) [drain_test.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain_test.go#L55)

There is a necessary change to use `ControllerRef`. Does anyone have bandwidth to work on this?

**Comment by crimsonfaith91** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by crimsonfaith91** [comment]
@mwielgus @DirectXMan12 It will be great if someone from sig-autoscaling can have a look at this. Thanks!

**Comment by crimsonfaith91** [comment]
@mwielgus @DirectXMan12 Any update?

**Comment by mwielgus** [comment]
Fixed with #271
