### ISSUE TITLE
CA version is wrong in userAgent

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/autoscaler#2213]
CA version is always shown as `v0.0.0-master+$Format:%h$` in userAgent:
```
Go/go1.10.2 (amd64-linux) go-autorest/v10.12.0 Azure-SDK-For-Go/v14.6.0 compute/2017-12-01; cluster-autoscaler/v0.0.0-master+$Format:%h$
```

/kind bug

**Comment by tghartland** [comment]
Did this work in the past? I've seen client-go used to get the kubernetes version in other projects as well but it doesn't work there either:
```
$ ./openstack-cloud-controller-manager --version
Kubernetes v0.0.0-master+$Format:%h$
```

For CA you can now import the version string from here: https://github.com/kubernetes/autoscaler/blob/0a7bc88b78be412b876ed8ddb325a315b8d6e21e/cluster-autoscaler/version/version.go#L20

**Comment by feiskyer** [comment]
@tghartland Yep, not sure what's broken with client-go.
