### ISSUE TITLE
Least waste expander strategy support GPU resource

### ISSUE THREAD

**Issue by ringtail** [kubernetes/autoscaler#2215]
Should we support GPU resource in least waste expander. In other words what's the best expander to choose between GPU group and CPU group?

**Comment by MaciekPytel** [comment]
Seems like a reasonable improvement. Do you want to give it a shot @ringtail?

**Comment by ringtail** [comment]
@MaciekPytel Leave it to me ☺.

**Comment by piroszhog** [comment]
@ringtail decided to not implement it?
