### ISSUE TITLE
In cluster-autoscaler, when set ScaleDownUtilizationThreshold 0.0 , utilization >= sd.context.ScaleDownUtilizationThreshold is always true

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/autoscaler#2221]
In cluster-autoscaler, when set ScaleDownUtilizationThreshold 0.0 , utilization >= sd.context.ScaleDownUtilizationThreshold is always true,isNodeBelowUtilzationThreshold is always false.

Can we add an judge when the  utilization is zero, isNodeBelowUtilzationThreshold return true:

           if (math.Abs(utilInfo.Utilization) < math.SmallestNonzeroFloat32) && 
               (math.Abs(sd.context.ScaleDownUtilizationThreshold) < math.SmallestNonzeroFloat32) {
               return true             
             }
		

// isNodeBelowUtilzaionThreshold determintes if a given node utilization is blow threshold:
func (sd *ScaleDown) isNodeBelowUtilzationThreshold(node *apiv1.Node, utilInfo simulator.UtilizationInfo) bool {
	 if gpu.NodeHasGpu(sd.context.CloudProvider.GPULabel(), node) {
		 if utilInfo.Utilization >= sd.context.ScaleDownGpuUtilizationThreshold {
			 return false
		 }
	 } else {
           if (math.Abs(utilInfo.Utilization) < math.SmallestNonzeroFloat32) && 
               (math.Abs(sd.context.ScaleDownUtilizationThreshold) < math.SmallestNonzeroFloat32) {
               return true             
             }
		if utilInfo.Utilization >= sd.context.ScaleDownUtilizationThreshold {
			return false
		}
	}
	return true
}

**Comment by MaciekPytel** [comment]
Can you explain what you're trying to achieve with this? Seems like you could achieve the same effect just by setting --scale-down-utilization-threshold to a small enough fraction?
