### ISSUE TITLE
Can not refresh ASG list when start up autoscaler

### ISSUE THREAD

**Issue by thangbn** [kubernetes/autoscaler#2223]
I'm pulling my hair past few days. Somehow the Cluster autoscaler fail to discover my ASG, it worked previously and suddenly it stopped working in the last few days. I have another cluster having the same problem but it going away after I update my ASG by changing the desired instance number, I tried the same update to this cluster but the problem persists.
ENV:
- EKS 1.13
- Autoscaler 1.15.1

I have 3 ASG defined:
![Screen Shot 2019-07-29 at 1 10 13 PM](https://user-images.githubusercontent.com/5661982/62078804-3c213a00-b202-11e9-9e62-4f7f13fae12a.png)
All of them have correct tags:
![Screen Shot 2019-07-29 at 1 07 16 PM](https://user-images.githubusercontent.com/5661982/62078597-d2a12b80-b201-11e9-9e01-dd9335eb7767.png)

Auto scaler args:
```
  - command:                                                                                                                 
    - ./cluster-autoscaler                                                                                                   
    - --cloud-provider=aws                                                                                                   
    - --namespace=infra                                                                                                      
    - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster/dev-platform-eks                  
    - --balance-similar-node-groups=false                                                                                    
    - --cloud-provider=aws                                                                                                   
    - --expander=priority                                                                                                    
    - --logtostderr=true                                                                                                     
    - --max-node-provision-time=5m                                                                                           
    - --namespace=infra                                                                                                      
    - --scale-down-delay-after-failure=1m                                                                                    
    - --scale-down-unneeded-time=2m                                                                                          
    - --scale-down-unready-time=5m                                                                                           
    - --scale-down-utilization-threshold=0.8                                                                                 
    - --scan-interval=5s                                                                                                     
    - --skip-nodes-with-local-storage=false                                                                                  
    - --skip-nodes-with-system-pods=false                                                                                    
    - --stderrthreshold=info                                                                                                 
    - --v=4
```

Console log:
```
Regenerating instance to ASG map for ASGs: []
....
Skipping ip-172-30-3-168.us-west-2.compute.internal - no node group config
```
The problem is similar to this one: https://github.com/kubernetes/autoscaler/issues/1854

Please help to investigate this.
Thanks

**Comment by johanneswuerbach** [comment]
From your screenshot the tag „k8s.io/cluster/dev-platform-eks“ seems actually not to exists, but only two similar tags „kubernetes.io/cluster/dev-platform-eks“ and „k8s.io/cluster-autoscaler/dev-platform-eks“. Changing the tag or the command arg should solve this

**Comment by thangbn** [comment]
> From your screenshot the tag „k8s.io/cluster/dev-platform-eks“ seems actually not to exists, but only two similar tags „kubernetes.io/cluster/dev-platform-eks“ and „k8s.io/cluster-autoscaler/dev-platform-eks“. Changing the tag or the command arg should solve this

Awesome, good catch. Turned out to be a breaking change in autoscaler helm chart
