### ISSUE TITLE
CA Makefile not setting linker flags properly

### ISSUE THREAD

**Issue by tghartland** [kubernetes/autoscaler#2239]
Running `make build-binary` produces a 99M binary, and uses an environment variable `LD_FLAGS=-s`.
```
$ make build-binary 
rm -f cluster-autoscaler
CGO_ENABLED=0 LD_FLAGS=-s GOOS=linux go build -o cluster-autoscaler 

$ ls -lh cluster-autoscaler 
-rwxrwxr-x 1 thomas thomas 99M Aug  5 14:04 cluster-autoscaler
```

But, setting the linker flags by passing the flag `-ldflags=-s` directly to `go build` instead produces a smaller binary, 73M.
```
$ CGO_ENABLED=0 GOOS=linux go build -ldflags="-s" -o cluster-autoscaler .

$ ls -lh cluster-autoscaler 
-rwxrwxr-x 1 thomas thomas 73M Aug  5 14:07 cluster-autoscaler
```

I can't find any documentation that suggests that Go does anything with an LD_FLAGS environment variable. There is one called CGO_LDFLAGS but I also see this building a 99M binary.

The linker flags should be changed to be similar to `TAGS_FLAG`.

**Comment by aleksandra-malinowska** [comment]
Yeah, this sounds like a bug. @losipiuk is out of office now, but feel free to send a PR.
