### ISSUE TITLE
one pod will have more than one aggregateStateMap if pod's label change  /vertical-pod-autoscaler

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/autoscaler#2242]
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L308

in function `findOrCreateAggregateContainerState`,  pod's label change , 
1.  will call `NewAggregateContainerState ` ;
2.  vpa.aggregateContainerStates will repeat(difference label) for one pod;
3.  in `UpdateVPAs`, will use which one (vpa.aggregateContainerStates)

myabe need to delete old before `NewAggregateContainerState`

**Comment by hongli-my** [comment]
/ vertical-pod-autoscaler

**Comment by bskiba** [comment]
I'm not sure I understand the problem. If the pod's labels change, but it is still controlled by the same controller (for example Deployment) and so is controlled by the same VPA object, we will have a new entry (empty at the beginning) in aggregateContainerStates map. However, the old one is needed still as it contains historical usage samples that contribute to this VPA's recommendation. The old entry will not be updated with new samples and will be garbage collected after it is no longer needed: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L324. That will leave only the new entry in the map.

If the label change causes the pod to stop being controlled by the VPA, the new aggregation will not contribute to the VPA recommendation, but the old aggregation still stays in VPA's aggregateContainerStates. This is intended, those usage samples where gathered while that pod was still under control of VPA. Same as in the first case, the old entry will not be updated with new samples and will be garbage collected after it is no longer needed.

**Comment by hongli-my** [comment]
1.  pod label change ,  stop use vpa model
a. pod label change, do not update `cluster.Pods`, because match no vpas.
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L365
b. `AddSample`  use old `cluster.Pods`, so can still get old  ` aggregateContainerStates`,  garbage collected can delete  depent on `LastSampleStart`?
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L179

**Comment by hongli-my** [comment]
2.  pod label  change, still use vpa
a.   here will merge two  `aggregateContainerState`,   sorry about it.
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go#L256
