### ISSUE TITLE
CA not processing taints and labels when there are nodes in an existing ASG

### ISSUE THREAD

**Issue by shankarramshivram** [kubernetes/autoscaler#2243]
Have a use case where as part of worker pool replacement automation we want to prevent CA scaling up the nodes in a old pool, but allow scaling down  and were exploring the use of node labels and taints , currently looking at the code it looks like `buildNodeFromTemplate` is called only when there are 0 nodes in the asg.  So in case of an asg already having nodes,  the ca does not prevent scaling up.

**Comment by MaciekPytel** [comment]
CA is built with assumption that every node in any given NodeGroup is identical (ie. has the same set of labels, for taints you can make CA filter out some taints in new node, but not add new ones). So the way you try to do this won't work now or in future.

I think you can just set min==max for that NodeGroup. CA does not enforce those limits, it will not remove nodes if size > max other than by following normal scale-up logic. It will not scale-up if it's over limit though, which seems to be what you need.

**Comment by shankarramshivram** [comment]
ok thank you for the clarification
