### ISSUE TITLE
Failed to find acceptable ranges for node groups

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/autoscaler#2250]
Master branch. Need to investigate this issue.

```
I0812 01:08:34.619043   86316 static_autoscaler.go:191] Starting main loop
W0812 01:08:34.619861   86316 clusterstate.go:437] Failed to find acceptable ranges for eksctl-ca-testing-nodegroup-ondemand-NodeGroup-1C3FP32CDSL2M
W0812 01:08:34.621255   86316 clusterstate.go:437] Failed to find acceptable ranges for eksctl-ca-testing-nodegroup-spot-NodeGroup-1IKFMEITZKT7T
I0812 01:08:34.621565   86316 utils.go:619] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0812 01:08:34.621737   86316 filter_out_schedulable.go:65] Filtering out schedulables
I0812 01:08:34.622118   86316 filter_out_schedulable.go:130] 0 other pods marked as unschedulable can be scheduled.
I0812 01:08:34.622246   86316 filter_out_schedulable.go:130] 0 other pods marked as unschedulable can be scheduled.

```

**Comment by siwyd** [comment]
I'm seeing this as well in the logs. What does this actually mean?

**Comment by Jeffwan** [comment]
/assign @Jeffwan 

@siwyd AcceptableRange contains information about acceptable size of a node group. It's used in the cluster state registry. I will debug and figure it out.

**Comment by Jeffwan** [comment]
Looks like https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L436-L439
has been visited before acceptableRange is ready. 


https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L307

https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L955

https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L474

https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L456

https://github.com/kubernetes/autoscaler/blob/a258103f8ec9c24a333338468fa51262df0ef24a/cluster-autoscaler/clusterstate/clusterstate.go#L435

**Comment by Jeffwan** [comment]
@siwyd check pr here. #2436

**Comment by siwyd** [comment]
@Jeffwan Thanks!

**Comment by omeroner** [comment]
hi, what's the solution? can you help me?


Feb 8 12:25:16 cluster-autoscaler-67d9f9bc88-lwpjt cluster-autoscaler warn W0208 09:25:16.427264       1 clusterstate.go:437] Failed to find acceptable ranges for eks-3abafa64-7d72-4351-305e-d82901a3e09b
Feb 8 12:25:16 cluster-autoscaler-67d9f9bc88-lwpjt cluster-autoscaler warn W0208 09:25:16.427277       1 clusterstate.go:437] Failed to find acceptable ranges for eks-d6bafa64-7d75-24f8-fba3-b104db0b4147
Feb 8 13:54:13 cluster-autoscaler-67d9f9bc88-v2hhx cluster-autoscaler warn W0208 10:54:13.795048       1 clusterstate.go:437] Failed to find acceptable ranges for eks-3abafa64-7d72-4351-305e-d82901a3e09b
Feb 8 13:54:13 cluster-autoscaler-67d9f9bc88-v2hhx cluster-autoscaler warn W0208 10:54:13.795087       1 clusterstate.go:437] Failed to find acceptable ranges for eks-d6bafa64-7d75-24f8-fba3-b104db0b4147
Feb 8 16:29:59 cluster-autoscaler-b6dcd68c5-2pz2p cluster-autoscaler warn W0208 13:29:59.882942       1 clusterstate.go:437] Failed to find acceptable ranges for eks-3abafa64-7d72-4351-305e-d82901a3e09b
Feb 8 16:29:59 cluster-autoscaler-b6dcd68c5-2pz2p cluster-autoscaler warn W0208 13:29:59.882954       1 clusterstate.go:437] Failed to find acceptable ranges for eks-d6bafa64-7d75-24f8-fba3-b104db0b4147
