### ISSUE TITLE
Unit tests failing after PR #2245

### ISSUE THREAD

**Issue by towca** [kubernetes/autoscaler#2252]
Unit tests for cluster-autoscaler are failing after #2245:
```
cloudprovider/digitalocean/godo/util/droplet.go:8:2: cannot find package "github.com/digitalocean/godo" in any of:
	/usr/local/google/home/jtuznik/go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/digitalocean/godo/vendor/github.com/digitalocean/godo (vendor tree)
	/usr/local/google/home/jtuznik/go/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/digitalocean/godo
	/usr/lib/google-golang/src/github.com/digitalocean/godo (from $GOROOT)
	/usr/local/google/home/jtuznik/go/src/github.com/digitalocean/godo (from $GOPATH)
```

This was not caught by Travis due to #2251.

**Comment by towca** [comment]
cc @fatih

**Comment by fatih** [comment]
Hi @towca 

Thanks for the report. How were you able to obtain the output? Is there a script I can run locally to see the result? Because there are no problems inside the `digitalocean` folder:

```
$ pwd
/Users/fatih/go/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/digitalocean
$ go test
PASS
ok      k8s.io/autoscaler/cluster-autoscaler/cloudprovider/digitalocean 0.045s
```

**Comment by towca** [comment]
`go test ./...` in the project root (`autoscaler/cluster-autoscaler`) or `make test-in-docker` (ideally both) should be used to verify the unit tests locally.

This particular issue seems to be the `github.com/digitalocean/godo` import line located in the `k8s.io/autoscaler/cluster-autoscaler/cloudprovider/digitalocean/godo/util` package.

**Comment by towca** [comment]
The `k8s.io/autoscaler/cluster-autoscaler/cloudprovider/digitalocean/godo/util` package doesn't seem to be used at all, it should be enough to remove it, right?

**Comment by fatih** [comment]
Thanks @towca. I see the problem now. Yes, it's either that or we have to rewrite the import path of the util package. I'll create a follow-up fix PR.

**Comment by fatih** [comment]
@towca opened a PR, PTAL.

**Comment by MaciekPytel** [comment]
Thanks @towca for spotting this and for rapid fix.
