### ISSUE TITLE
Failed to scale up: Could not compute total resources

### ISSUE THREAD

**Issue by SheharyarTkxel** [kubernetes/autoscaler#2260]
Trying to scale up GPU Nodes (worker node group) from 0. Here is the log:
![image](https://user-images.githubusercontent.com/51945960/63010812-8233fa00-bea0-11e9-94ff-dcc63d95ee2a.png)

Here are the steps I followed to setup CA:
(1) Added the following IAM policy in AWS console and attached it to the GPU group:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}

```
(2) Took [this yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml) file and applied via kubectl command by modifying the node information like this:
--nodes=0:3:[MY GPU AUTOSCALING GROUP NAME]

I don't understand the errors mentioned in the log. Please let me know how may I solve this issue.

**Environment**
Kubeflow: v0.6.1-rc.2
Cluster Autoscaler: v1.12.3

**Comment by Jeffwan** [comment]
@SheharyarTkxel  Seems you don't have `autoscaling:DescribeLaunchTemplates`.  Can you add right policy to your node group role? 

Can you check documentation here? 
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws

**Comment by Jeffwan** [comment]
BTW. If you are using slack, please join #aws  kubeflow.slack.com and people are talk about some aws specific issues there.

**Comment by SheharyarTkxel** [comment]
> @SheharyarTkxel Seems you don't have `autoscaling:DescribeLaunchTemplates`. Can you add right policy to your node group role?
> 
> Can you check documentation here?
> https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws

Including "autoscaling:DescribeLaunchTemplates" in the IAM policy leads to this warning of Unrecognized Action:
![image](https://user-images.githubusercontent.com/51945960/63147237-f1335f00-c016-11e9-8098-aa77bfeba85c.png)

**Comment by SheharyarTkxel** [comment]
> BTW. If you are using slack, please join #aws kubeflow.slack.com and people are talk about some aws specific issues there.

@Jeffwan Yes that would be helpful. I wasn't able to find it in my channels, can you please send an invite to muhammad.sheharyar@tkxel.com?

**Comment by Jeffwan** [comment]
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws

Follow instruction here for detail permissions.

**Comment by calclavia** [comment]
I'm running into the same problem. I followed the permissions as described but somehow the cluster autoscaler does not scale up nodes from zero in AWS. However, it can scale down nodes.

**Comment by Jeffwan** [comment]
@calclavia Did you setup tags correctly for scaling up from 9

**Comment by SheharyarTkxel** [comment]
> I'm running into the same problem. I followed the permissions as described but somehow the cluster autoscaler does not scale up nodes from zero in AWS. However, it can scale down nodes if I manually scale up nodes.

@calclavia I was able to scale up/down nodes. The issue was with the IAM policy. Here is the policy I used: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "ec2:DescribeLaunchTemplateVersions"
            ],
            "Resource": "*"
        }
    ]
}
```

The problem was indeed with permissions and after adjusting this IAM policy it solved the issue. Also note that you will have to apply this IAM policy to all the resources (nodes) of your assembly. Once you are done, you can test your cluster scaling by deploying NGINX deployments like this:

```
kubectl create deployment autoscaler-demo --image=nginx
kubectl scale deployment autoscaler-demo --replicas=100
kubectl get deployment autoscaler-demo --watch
```

The third command will let you watch replica creation, and meanwhile you can go to your Autoscaling Groups menu in EC2 to see the nodes scaling up. Nodes may take a couple of minutes to scale up and (by default) exactly 10 minutes in the case of scaling down, so be patient.

Let me know if you are stuck somewhere.
