### ISSUE TITLE
cluster-autoscaler not scaling down unready nodes if utilization is over threshold

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/autoscaler#227]
Not sure if this is expected...

I have a node that has been unready for over 20 mins, and is therefore eligible for scale-in, but it isn't getting scaled in because the last reported utilization (before the kubelet stopped sending updates) was 60%.  

Would it make sense to have an unready node ignore utilization when determining if it can scale in?

**Comment by MaciekPytel** [comment]
AFAIK CA calculates utilization based on sum of requests of all pods running on a node and it has nothing to do with the utilization reported by kubelet. When a node becomes unready the pods will eventually be moved to other nodes, at which point the utilization of the node in CA should drop and the node will be able to scale down. I don't remember exactly how long it takes before the pods are moved to other nodes, but it takes a while (I think it was on the order of magnitude of 5-10 minutes).

I think it makes sense that we wait with scale down until k8s decides the node is down for good and drains it. We still wait for 20 minutes (controlled by `scale-down-unready-time` flag, so you can change it). That feels a bit excessive, maybe we should reduce the default. WDYT @mwielgus?

**Comment by ryanwalls** [comment]
@MaciekPytel Makes sense, except I didn't see the the pods "moved" to other nodes.  New pods were spun up on other nodes, but the existing pods were not stopped on the unready node.  So even after waiting an hour, the node was never eligible for scale down.

**Comment by MaciekPytel** [comment]
The pods should be evicted from unready node by node controller. Not sure why it wouldn't happen in your case, but my knowledge of node controller is very limited.

**Comment by mwielgus** [comment]
How much "unready" the node was? Do you have any logs/status?

**Comment by ryanwalls** [comment]
@mwielgus Not sure I understand your question.  Unfortunately, don't have any logs/status but the node was unready for a little over 60 minutes when I manually terminated it.

**Comment by mwielgus** [comment]
@ryanwalls as @MaciekPytel wrote the node controller should remove pods from nodes that are broken. Moreover if your cluster size was above min, CA should remove the broken node.
Any logs or output from kubectl get nodes -o yaml would shed some light why it didn't work as expected. Right now we are a bit clueless. We can double check if the code works on gce/gke but we may broke the node in a different way.

**Comment by ryanwalls** [comment]
@mwielgus Roger.  I'll try to watch for another occurrence of this and will capture more logs.  In my case the kubelet stopped responding and reporting status.  So if the node controller tries to remove pods by talking to the kubelet, that could explain why it didn't work.

**Comment by ryanwalls** [comment]
@mwielgus @MaciekPytel I've got another node that has the same problem.  It became unready about 8 hrs ago.  I'll keep it up until we can diagnose.  Let me know what logs/details you want to see.  

Here is the output of the node details as yaml:
```
Name:			ip-172-31-0-88.us-gov-west-1.compute.internal
Role:			
Labels:			3dsim.com/type=memory-optimized
			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=m4.xlarge
			beta.kubernetes.io/os=linux
			compute=true
			failure-domain.beta.kubernetes.io/region=us-gov-west-1
			failure-domain.beta.kubernetes.io/zone=us-gov-west-1b
			instanceid=i-09955258ca9cbe4c8
			instancetype=m4.xlarge
			io.rancher.host.docker_version=1.12
			io.rancher.host.linux_kernel_version=4.4
			io.rancher.host.provider=aws
			io.rancher.host.region=us-gov-west-1
			io.rancher.host.zone=us-gov-west-1b
			kubernetes.io/hostname=ip-172-31-0-88.us-gov-west-1.compute.internal
			publicdns=ec2-52-61-5-147.us-gov-west-1.compute.amazonaws.com
Annotations:		io.rancher.labels.3dsim.com/type=
			io.rancher.labels.compute=
			io.rancher.labels.instanceid=
			io.rancher.labels.instancetype=
			io.rancher.labels.io.rancher.host.docker_version=
			io.rancher.labels.io.rancher.host.linux_kernel_version=
			io.rancher.labels.io.rancher.host.provider=
			io.rancher.labels.io.rancher.host.region=
			io.rancher.labels.io.rancher.host.zone=
			io.rancher.labels.publicdns=
			node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			<none>
CreationTimestamp:	Mon, 21 Aug 2017 15:08:11 -0600
Phase:			
Conditions:
  Type			Status		LastHeartbeatTime			LastTransitionTime			Reason			Message
  ----			------		-----------------			------------------			------			-------
  OutOfDisk 		Unknown 	Mon, 21 Aug 2017 20:00:52 -0600 	Mon, 21 Aug 2017 20:01:38 -0600 	NodeStatusUnknown 	Kubelet stopped posting node status.
  MemoryPressure 	Unknown 	Mon, 21 Aug 2017 20:00:52 -0600 	Mon, 21 Aug 2017 20:01:38 -0600 	NodeStatusUnknown 	Kubelet stopped posting node status.
  DiskPressure 		Unknown 	Mon, 21 Aug 2017 20:00:52 -0600 	Mon, 21 Aug 2017 20:01:38 -0600 	NodeStatusUnknown 	Kubelet stopped posting node status.
  Ready 		Unknown 	Mon, 21 Aug 2017 20:00:52 -0600 	Mon, 21 Aug 2017 20:01:38 -0600 	NodeStatusUnknown 	Kubelet stopped posting node status.
Addresses:		172.31.0.88,172.31.0.88,52.61.5.147,ip-172-31-0-88.us-gov-west-1.compute.internal,ec2-52-61-5-147.us-gov-west-1.compute.amazonaws.com,ip-172-31-0-88.us-gov-west-1.compute.internal
Capacity:
 cpu:		4
 memory:	16431348Ki
 pods:		110
Allocatable:
 cpu:		4
 memory:	16328948Ki
 pods:		110
System Info:
 Machine ID:			
 System UUID:			EC2C4AE8-5A37-34B5-1A64-CC9C907B3A53
 Boot ID:			7dc9da82-65b3-4772-9d38-1fadd2bbaf4e
 Kernel Version:		4.4.0-45-generic
 OS Image:			Ubuntu 16.04.1 LTS
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.6.6-rancher1
 Kube-Proxy Version:		v1.6.6-rancher1
ExternalID:			i-09955258ca9cbe4c8
Non-terminated Pods:		(3 in total)
  Namespace			Name								CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----								------------	----------	---------------	-------------
  default			fluentd-jhrpb							0 (0%)		0 (0%)		0 (0%)		0 (0%)
  default			k8s-node-exporter-lk4q7						100m (2%)	200m (5%)	30Mi (0%)	50Mi (0%)
  default			newmechanicssolver-361--1503349413550135293-hgrmh		3500m (87%)	3900m (97%)	15Gi (96%)	15Gi (96%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  3600m (90%)	4100m (102%)	15390Mi (96%)	15410Mi (96%)
Events:		<none>
```

**Comment by ryanwalls** [comment]
And here is the output from describing the `newmechanicssolver-361--1503349413550135293-hgrmh` pod.  

```
Name:				newmechanicssolver-361--1503349413550135293-hgrmh
Namespace:			default
Node:				ip-172-31-0-88.us-gov-west-1.compute.internal/172.31.0.88
Start Time:			Mon, 21 Aug 2017 15:08:32 -0600
Labels:				controller-uid=315e1acb-86b4-11e7-ac41-021069d48891
				job-name=newmechanicssolver-361--1503349413550135293
Annotations:			kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"Job","namespace":"default","name":"newmechanicssolver-361--1503349413550135293","uid":"315e1acb-86b4-11e7-...
Status:				Terminating (expires Mon, 21 Aug 2017 20:06:31 -0600)
Termination Grace Period:	30s
Reason:				NodeLost
Message:			Node ip-172-31-0-88.us-gov-west-1.compute.internal which was running pod newmechanicssolver-361--1503349413550135293-hgrmh is unresponsive
IP:				10.42.92.210
Controllers:			Job/newmechanicssolver-361--1503349413550135293
Containers:
  newmechanicssolver:
    Container ID:	docker://9973a7235a1ac94a26419be3dc029d196cbcd6df5cd937204ac1078a4d353d74
    Image:		quay.io/3dsim/new-mechanics-solver-svc:0.14.23
    Image ID:		docker-pullable://quay.io/3dsim/new-mechanics-solver-svc@sha256:29e37d0a2a87a83eb4822c8347d9484a68210b1ea451af4e95854a153c2a770a
    Port:		
    Command:
      solver-svc
      run-task
    Args:
      3dsim-infrastructure-configuration
      temp/transferfiles/361__1503349413550135293.json
    State:		Running
      Started:		Mon, 21 Aug 2017 15:09:08 -0600
    Ready:		True
    Restart Count:	0
    Limits:
      cpu:	3900m
      memory:	15Gi
    Requests:
      cpu:	3500m
      memory:	15Gi
    Environment:
      ENV:	gov
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l10jc (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-l10jc:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-l10jc
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	3dsim.com/type=memory-optimized
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:		<none>
```

It looks like k8s is trying to terminate the pod, but can't because the node is unresponsive.

**Comment by mwielgus** [comment]
Looks like a problem in node controller + rancher + aws combination. We will ask one of our colleagues who did some changes to node controller in the past but most likely you will have to file a bug in the main kubernetes repo.

**Comment by ryanwalls** [comment]
@mwielgus Thanks.  What is the expected behavior?  Just so I can describe what I expect to see when I file issues in the main repo and with Rancher.

Another weird thing is that the pod described above is using more than its `15Gi` memory limit.  Looking at the exported metrics from `kube-state-metrics` it says the pod was allowed to use just over 16 GB.  So it seems like the Pod wasn't constrained, so it was able to overrun the box.

**Comment by ryanwalls** [comment]
Update:  Got on the node and inspected the running docker container and the HostConfig.Memory is set to `16106127360`.  Is that what `15Gi` would translate to?

**Comment by ryanwalls** [comment]
@MaciekPytel @mwielgus I believe I've figured out the issue!  Long story short, Rancher keeps tracks of nodes and runs a node controller.  When a node becomes unresponsive, it usually also stops reporting back status to Rancher.  We had an automated script that cleaned up these "disconnected" nodes from Rancher every 15 mins or so.  

I believe the problem arises when we delete the node from Rancher before the pods have been successfully evicted.  

Will close this.  Thanks for all the help!
