### ISSUE TITLE
aws EKS  , multiple asg with nodeselector

### ISSUE THREAD

**Issue by ViktorUJ** [kubernetes/autoscaler#2287]
Hello.
Autoscaler  add node and delete it .

 I use aws eks   with   2 asg  . 
asg 1  - have node label   work_type: "work1"
asg2 - have node label   works_type : "infra"

.......
  command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --nodes=1:10:k8s-worker-asg-1
            - --nodes=1:3:k8s-worker-asg-2
.......

 When i deploy pods on asg1 it works ,  but  when on asg2  - autoscaler   add new node  and delete it.

**Comment by bskiba** [comment]
What CA verison is it?
Do you have access to cluster autoscaler logs? They would be useful in troubleshooting.

When autoscaler adds node to asg2 and then deletes it, do pods go pending? What is the expected behavior?

**Comment by ViktorUJ** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
[root@ansible eks]# kubectl get node
NAME                                       STATUS   ROLES    AGE     VERSION
ip-10-0-1-83.us-west-2.compute.internal    Ready    <none>   2m54s   v1.13.8-eks-cd3eb0
ip-10-0-3-124.us-west-2.compute.internal   Ready    <none>   2m46s   v1.13.8-eks-cd3eb0

I have full access to  logs  and cluster. 



......

 1 aws_manager.go:157] Refreshed ASG list, next refresh after 2019-09-02 14:17:20.778852024 +0000 UTC m=+678.748481391
I0902 14:17:10.778955       1 static_autoscaler.go:168] 1 unregistered nodes present
I0902 14:17:10.778990       1 utils.go:552] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0902 14:17:10.779007       1 static_autoscaler.go:252] Filtering out schedulables
I0902 14:17:10.779850       1 static_autoscaler.go:262] No schedulable pods
I0902 14:17:10.779871       1 scale_up.go:263] Pod work-default-testwordpress/dev-ago-app-c56b4544c-5d8vn is unschedulable
I0902 14:17:10.779878       1 scale_up.go:263] Pod work-default-testwordpress/dev-ago-app-c56b4544c-cjvwj is unschedulable
I0902 14:17:10.779884       1 scale_up.go:263] Pod work-default-testwordpress/dev-ago-app-c56b4544c-8j9bk is unschedulable
I0902 14:17:10.779921       1 scale_up.go:300] Upcoming 1 nodes
I0902 14:17:10.779952       1 utils.go:208] Pod dev-ago-app-c56b4544c-5d8vn can't be scheduled on work-default-eks-spot1, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector
I0902 14:17:10.780049       1 utils.go:198] Pod dev-ago-app-c56b4544c-cjvwj can't be scheduled on work-default-eks-spot1. Used cached predicate check results
I0902 14:17:10.780122       1 utils.go:198] Pod dev-ago-app-c56b4544c-8j9bk can't be scheduled on work-default-eks-spot1. Used cached predicate check results
I0902 14:17:10.780137       1 scale_up.go:406] No pod can fit to work-default-eks-spot1
I0902 14:17:10.780144       1 scale_up.go:335] Skipping node group work-default-eks-spot2 - max size reached
I0902 14:17:10.780151       1 scale_up.go:335] Skipping node group work-default-eks-on-demand - max size reached
I0902 14:17:10.780438       1 scale_up.go:403] No need for any nodes in work-default-eks_workers_infra
I0902 14:17:10.780454       1 scale_up.go:411] No expansion options
I0902 14:17:10.780469       1 static_autoscaler.go:307] Calculating unneeded nodes
I0902 14:17:10.780493       1 utils.go:509] Skipping ip-10-0-3-124.us-west-2.compute.internal - node group min size reached
I0902 14:17:10.780543       1 scale_down.go:402] Node ip-10-0-1-83.us-west-2.compute.internal - utilization 0.980000
I0902 14:17:10.780557       1 scale_down.go:406] Node ip-10-0-1-83.us-west-2.compute.internal is not suitable for removal - utilization too big (0.980000)
I0902 14:17:10.780604       1 static_autoscaler.go:333] Scale down status: unneededOnly=true lastScaleUpTime=2019-09-02 14:15:17.86937005 +0000 UTC m=+555.838999459 lastScaleDownDeleteTime=2019-09-02 14:06:05.236820653 +0000 UTC m=+3.206449950 lastScaleDownFailTime=2019-09-02 14:06:05.236820738 +0000 UTC m=+3.206450030 scaleDownForbidden=false isDeleteInProgress=false
I0902 14:17:11.506719       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I0902 14:17:13.515581       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I0902 14:17:15.524508       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I0902 14:17:17.540054       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I0902 14:17:19.550396       1 leaderelection.go:227] successfully renewed lease kube-system/cluster-autoscaler
I0902 14:17:20.791510       1 static_autoscaler.go:121] Starting main loop
W0902 14:17:20.853357       1 aws_manager.go:199] Found multiple availability zones, using us-west-2a
W0902 14:17:20.892277       1 aws_manager.go:199] Found multiple availability zones, using us-west-2a
I0902 14:17:20.915196       1 auto_scaling_groups.go:320] Regenerating instance to ASG map for ASGs: [work-default-eks-spot1 work-default-eks-spot2 work-default-eks-on-demand work-default-eks_workers_infra]
I0902 14:17:21.012723       1 aws_manager.go:157] Refreshed ASG list, next refresh after 2019-09-02 14:17:31.01271371 +0000 UTC m=+688.982343097
I0902 14:17:21.012809       1 static_autoscaler.go:168] 1 unregistered nodes present
I0902 14:17:21.012842       1 utils.go:552] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0902 14:17:21.012855       1 static_autoscaler.go:252] Filtering out schedulables

**Comment by bskiba** [comment]
Thanks. Can you also post the result of
kubectl get -n kube-system configmap cluster-autoscaler-status -o yaml

Also can you describe 
1. what behaviour you expected
2. what actually happened

**Comment by ViktorUJ** [comment]
[root@ansible ci]# kubectl get -n kube-system configmap cluster-autoscaler-status -o yaml
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2019-09-02 14:57:47.683724023 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleUp:     InProgress (ready=2 registered=2)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:57:06.260551893 +0000 UTC m=+197.031081183
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

    NodeGroups:
      Name:        work-default-eks-spot1
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=1, maxSize=7))
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

      Name:        work-default-eks-spot2
      Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=0 (minSize=0, maxSize=0))
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     NoActivity (ready=0 cloudProviderTarget=0)
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

      Name:        work-default-eks-on-demand
      Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=0 (minSize=0, maxSize=0))
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     NoActivity (ready=0 cloudProviderTarget=0)
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

      Name:        work-default-eks_workers_infra
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=2 (minSize=1, maxSize=4))
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleUp:     InProgress (ready=1 cloudProviderTarget=2)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:57:06.260551893 +0000 UTC m=+197.031081183
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2019-09-02 14:57:47.683724023 +0000
      UTC
  creationTimestamp: "2019-09-02T14:53:50Z"
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "1585"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: 7995d86f-cd91-11e9-b5aa-0235c922729e


........
 
[root@ansible ci]# kubectl get -n kube-system configmap cluster-autoscaler-status -o yaml
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2019-09-02 14:58:28.576283209 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleUp:     InProgress (ready=2 registered=2)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:57:06.260551893 +0000 UTC m=+197.031081183
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

    NodeGroups:
      Name:        work-default-eks-spot1
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=1, maxSize=7))
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

      Name:        work-default-eks-spot2
      Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=0 (minSize=0, maxSize=0))
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     NoActivity (ready=0 cloudProviderTarget=0)
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

      Name:        work-default-eks-on-demand
      Health:      Healthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=0 (minSize=0, maxSize=0))
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     NoActivity (ready=0 cloudProviderTarget=0)
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

      Name:        work-default-eks_workers_infra
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=2 (minSize=1, maxSize=4))
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
      ScaleUp:     InProgress (ready=1 cloudProviderTarget=2)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:57:06.260551893 +0000 UTC m=+197.031081183
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-09-02 14:58:28.384201661 +0000 UTC m=+279.154730920
                   LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2019-09-02 14:58:28.576283209 +0000
      UTC
  creationTimestamp: "2019-09-02T14:53:50Z"
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "1673"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: 7995d86f-cd91-11e9-b5aa-0235c922729e



......................
when  i add pods with nodeselector =wokr1   - autoscaler add node asg1   - it works
 
 when  i add pods with  nodeselector =infra   - autoscaler add node asg2   - it don't  work    ->  autoscaler add node  ,  and delete it

**Comment by bskiba** [comment]
`
  Name:        work-default-eks_workers_infra
  Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=2 (minSize=1, maxSize=4))
               LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
               LastTransitionTime: 2019-09-02 14:54:02.209305948 +0000 UTC m=+12.979835247
  ScaleUp:     InProgress (ready=1 cloudProviderTarget=2)
               LastProbeTime:      2019-09-02 14:57:47.467422992 +0000 UTC m=+238.237952298
               LastTransitionTime: 2019-09-02 14:57:06.260551893 +0000 UTC m=+197.031081183
`

This fragment suggests that Cluster Autoscaler is trying to scale up, but the node is not coming up or not registering correctly with Kubernetes. It would be good to confirm if Cluster Autoscaler is actually deleting any nodes.
@losipiuk what would be a good log line to grep for to see if Cluster Autoscaler removed any nodes?

**Comment by ViktorUJ** [comment]
Hello.
I added logs , video ,  etc  on my google disk.
https://drive.google.com/drive/folders/1UxZUTzIkFDq5rlKWKaWZ7pcPmZINheE_

**Comment by ViktorUJ** [comment]
Hi, guys.
Do You have any news ?

**Comment by losipiuk** [comment]
> ```
>   Name:        work-default-eks_workers_infra
>   ScaleUp:     InProgress (ready=1 cloudProviderTarget=2) 
> ```
> 
> This fragment suggests that Cluster Autoscaler is trying to scale up, but the node is not coming up or not registering correctly with Kubernetes. It would be good to confirm if Cluster Autoscaler is actually deleting any nodes.
> Łukasz Osipiuk what would be a good log line to grep for to see if Cluster Autoscaler removed any nodes?

I looked into the logs you provided what seems to happen is what @bskiba wrote.
Cluster autoscaler is triggering scalup of `work-default-eks_workers_infra`
```
I0903 08:21:09.458423       1 scale_up.go:501] Final scale-up plan: [{work-default-eks_workers_infra 1->2 (max: 4)}]
```

New node is reported by cloud provider:
```
I0903 08:21:19.741637       1 scale_up.go:300] Upcoming 1 nodes
```

But crosschecking with `Nodes`, reported by k8s apiserver, shows that there is no matching node registered
```
I0903 08:21:40.179927       1 static_autoscaler.go:168] 1 unregistered nodes present
```

The logic for crosschecking is here: https://github.com/kubernetes/autoscaler/blob/ac2d9fc9287ec3fea3e8b4c5cf68b406e9cc2a99/cluster-autoscaler/clusterstate/clusterstate.go#L648
We are basically iterating over all instances reported by cloudprovider and checking if there is `Node` object with matching `Spec.ProviderId`.

If node fails to register for 15 minuts CA kills it. I cannot see that in logs as they are truncated 10 minutes after scaleup. 
The log when CA removes unregistered node is `Removing unregistered node`.
See: https://github.com/kubernetes/autoscaler/blob/ac2d9fc9287ec3fea3e8b4c5cf68b406e9cc2a99/cluster-autoscaler/core/utils.go#L486)

Do you see logs that CA is deleting nodes?

If we are actually deleting nodes the question is why nodes are not registering themselves. Or why the Ids reported by k8s `Node` objects do not match those reported by cloudprovider. Could you make an experiment and run 
```
kubectl get no -o yaml
```
in the period when CA is reporting `1 unregistered nodes present` in logs.
If you could run it multiple times (every couple minutes) and attach the result to this bug it could help understand the situation better.

PS. Is your your problematic ag configured in a way that kubelet is started with `--provider-id` flag? That is required for CA.

**Comment by ViktorUJ** [comment]
hello.
thanks.
