### ISSUE TITLE
GKE minimum node configuration.

### ISSUE THREAD

**Issue by nilo19** [kubernetes/autoscaler#2288]
When the number of nodes in the nodepool is less than min value preset, GKE waits to take effect until a new node is needed in the node pool. What if automatically upscale the node to the minimum value because for users it's intuitive that after he/she set the min, the number of nodes will never be out of the range.

/area provider/gcp

**Comment by MaciekPytel** [comment]
This is not specific to GKE, it's in general how CA works.
The main rationale for this is around maximum size limit. It'd be easy to add nodes when below min, but what if cluster is above max and there are no nodes that can be safely removed? CA promises to never remove a node if it would cause to go pending, never remove a node with scale-down-disabled annotation, never violate PDB, etc. You can't enforce max size limit and unconditionally keep those promises, so we chose to focus on safely scaling down and not enforcing the max limit. 
I think that treating min and max limits differently would be very confusing, so we've decided not to enforce either.
