### ISSUE TITLE
AWS EKS: Update the AWS Go SDK version to support Web Identity providers for IAM credentials

### ISSUE THREAD

**Issue by barryib** [kubernetes/autoscaler#2301]
Update the AWS Go SDK version to support Web Identity providers for IAM credentials

More infos here:
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by devkid** [comment]
See #2323

**Comment by marcincuber** [comment]
When is the planned released of this feature?

**Comment by johnjeffers** [comment]
Also waiting on this. Fingers crossed it's in 1.14.6 since that is the version we need for EKS. 🤞

**Comment by Jeffwan** [comment]
We backport #2428 and #2358 to to 1.14. Next release team will publish new versions.

**Comment by Jeffwan** [comment]
This is done and I will close the issue. 

/close
