### ISSUE TITLE
Wrong utilization calculation?

### ISSUE THREAD

**Issue by jrubenc** [kubernetes/autoscaler#2303]
Hello,

EKS using K8s 1.12, using HPA.

Cluster's ASG min number of instances is 4, of c5.xlarge type (so far). After a deployment a pair of hours ago, the numbers of instances went to 7. And the weird thing is that doesn't look it's going down again. 

CA logs say:

    Node ip-172-31-141-237.eu-west-1... is not suitable for removal - utilization too big (0.975250)
    Node ip-172-31-121-15.eu-west-1... is not suitable for removal - utilization too big (0.978750)
    Node ip-172-31-120-134.eu-west-1... is not suitable for removal - utilization too big (0.753750)
    Node ip-172-31-213-143.eu-west-1... is not suitable for removal - utilization too big (0.636250)
    Node ip-172-31-153-250.eu-west-1... is not suitable for removal - utilization too big (0.957500)
    Node ip-172-31-244-94.eu-west-1... is not suitable for removal - utilization too big (0.957500)

But (and in the same order shown before) kubectl top node says:

    ip-172-31-141-237.eu-west-1.compute.internal   2492m        62%    2023Mi          26%
    ip-172-31-121-15.eu-west-1.compute.internal    1808m        45%    2373Mi          31%
    ip-172-31-120-134.eu-west-1.compute.internal   634m         15%    3281Mi          43%
    ip-172-31-213-143.eu-west-1.compute.internal   1148m        28%    2353Mi          31%
    ip-172-31-153-250.eu-west-1.compute.internal   1425m        35%    1167Mi          15%
    ip-172-31-244-94.eu-west-1.compute.internal    482m         12%    1083Mi          14%

So except for 172-31-141-237 the rest of the nodes are way under a 50% usage, yet CA won't trigger a scale down. The instance type means CPU can go up to 4000m.

And the biggest "requests" for a deployment is 1500m. So instead of fitting an upcoming new pod triggered by HPA in any of the nodes with more than free 1500m, CA just requests a new node:

    Evaluation ip-172-31-244-94.eu-west-1.... for prod/deployment-XXXXX -> 
    PodFitsResources predicate mismatch, reason: Insufficient cpu

But

    ip-172-31-244-94.eu-west-1.compute.internal    426m         10%    1080Mi          14%

that node has more than 3500m free CPU units yet fails to be elected for a pod that requests 1500m.

**Comment by bskiba** [comment]
CA looks at the sum of resource request over node allocatable. AFAIR Kubectl top looks at real cpu usage. 

You can take a look at node statistics by doing 
`kubectl describe node ip-172-31-244-94.eu-west-1.compute.internal`

This should give you sth like:
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                   Requests             Limits
  --------                           --------                ------
  cpu                             572m (60%)        1209m (128%)
  memory                     661280Ki (24%)  1285920Ki (47%)
  ephemeral-storage          0 (0%)            0 (0%)

CA looks at the Request column from these stats.

**Comment by jrubenc** [comment]
Absolutely. So in fact setting requests equal to limits leads might lead to an overprovisioning and waste of resources. Thanks for your reply.
