### ISSUE TITLE
Cluster Autoscaler in Azure using Kubespray

### ISSUE THREAD

**Issue by amruthapbhat** [kubernetes/autoscaler#2314]
Hi,

I have created a K8s cluster in Azure using Kuberspray and enabled autoscaling for the same. When the number of pods are increased, the new nodes are running in the vmss but they are not attaching to the k8s cluster.

Could you please let me know if there is anyway to attach them directly from vmss.

**Comment by feiskyer** [comment]
new nodes should join the cluster on node provisioning. I'm not sure how Kuberspray provisioning nodes, but if there're additional steps outside of the VM, then you should run the same steps.

**Comment by feiskyer** [comment]
this is out scope of CA.

/close
