### ISSUE TITLE
Please release a autoscaler version for k8 1.15.3

### ISSUE THREAD

**Issue by vijaygos** [kubernetes/autoscaler#2321]
We are looking to upgrade our clusters to 1.15.3 and would like the autoscaler version to have parity with the kubernetes version (I know that 1.15.1 works with kubernetes version 1.15.3).
Could you guys please push a new image for 1.15.2 and 1.15.3 ?

Thank.

**Comment by vijaygos** [comment]
Do we have a ETA for 1.15.3 release? This is becoming a pressing issue with the security bug that requires us to move to 1.15.3.

**Comment by vijaygos** [comment]
@losipiuk Any chance you could help with this?

**Comment by losipiuk** [comment]
@vijaygos generally you are good with using CA 1.15.1 with k8s 1.15.3. What must match is the minor version of k8s and CA (15 in this case). The release cycle of patch versions of k8s/kubernetes and CA is independent.

As for the security issue I sent out the PRs to update go version we use for building CA. The attack surface is not huge for CA as only HTTP endpoint we are exposing are metrics. And that I expect is not directly available to hostile parties most of the time. Nevertheless next patch release will be built with patched golang.

As for the ETA we my build new release set some time next week I think.

cc: @MaciekPytel

**Comment by vijaygos** [comment]
Thanks, @losipiuk
