### ISSUE TITLE
Build patch releases of Cluster Autoscaler

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/autoscaler#2325]

**Comment by losipiuk** [comment]
To happen sometime early next week.

**Comment by tghartland** [comment]
No changes in magnum.

**Comment by feiskyer** [comment]
@losipiuk  any plans of next set of patch releases?

**Comment by andrewsykim** [comment]
cc @timoreimann

**Comment by losipiuk** [comment]
> Łukasz Osipiuk thanks, created a cherry pick PR for 2237.

We are planning to do those in week of 25th

**Comment by losipiuk** [comment]
Closing this issue. Will open new one couple days before we will be doing releases.
