### ISSUE TITLE
cluster able to autoscale [spawn new aws instance] but fails to add it to k8s-cluster

### ISSUE THREAD

**Issue by Parag08** [kubernetes/autoscaler#233]
I created a asg group and its profile using terraform then I created a kubernetes cluster using kargo. When i try to autoscale it successfully start the instances in aws but never adds it to kubernetes cluster. Can anyone point me to code where how exactly a node is added to kubernetes cluster is.

**Comment by Parag08** [comment]
logs:-

 static_autoscaler.go:145] 1 unregistered nodes present
I0818 07:14:47.461642       1 static_autoscaler.go:213] Filtering out schedulables
I0818 07:14:47.461714       1 static_autoscaler.go:221] No schedulable pods
I0818 07:14:47.461728       1 scale_up.go:50] Pod default/cassandra-2 is unschedulable
I0818 07:14:47.477624       1 scale_up.go:71] Upcoming 1 nodes
I0818 07:14:47.500840       1 scale_up.go:138] No need for any nodes in asg
I0818 07:14:47.500908       1 scale_up.go:146] No expansion options



config map
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2017-08-18 07:18:12.703723707 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1)
                   LastProbeTime:      2017-08-18 07:18:12.400186209 +0000 UTC
                   LastTransitionTime: 2017-08-18 07:09:19.470969259 +0000 UTC
      ScaleUp:     InProgress (ready=1 registered=1)
                   LastProbeTime:      2017-08-18 07:18:12.400186209 +0000 UTC
                   LastTransitionTime: 2017-08-18 07:13:45.785192672 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2017-08-18 07:18:12.703494953 +0000 UTC
                   LastTransitionTime: 2017-08-18 07:09:19.659109091 +0000 UTC

    NodeGroups:
      Name:        asg
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 cloudProviderTarget=2 (minSize=1, maxSize=5))
                   LastProbeTime:      2017-08-18 07:18:12.400186209 +0000 UTC
                   LastTransitionTime: 2017-08-18 07:09:19.470969259 +0000 UTC
      ScaleUp:     InProgress (ready=1 cloudProviderTarget=2)
                   LastProbeTime:      2017-08-18 07:18:12.400186209 +0000 UTC
                   LastTransitionTime: 2017-08-18 07:13:45.785192672 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2017-08-18 07:18:12.703494953 +0000 UTC
                   LastTransitionTime: 2017-08-18 07:09:19.659109091 +0000 UTC

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2017-08-18 07:18:12.703723707 +0000
      UTC
  creationTimestamp: 2017-08-18T07:09:09Z
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "1993"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: xxxxxxxxxxxxxxxx

**Comment by MaciekPytel** [comment]
In kubernetes nodes register themselves in cluster. The only thing Cluster-Autoscaler does is start a new instance.

So in your case CA worked as expected, but for some reason kubelet failed to register the node. Most likely cause would be some problem with connectivity to master, but really it could be anything. I would start by looking into kubelet log on the node that failed to register - usually there are some clues there.

**Comment by Parag08** [comment]
In newly started nodes kube is not installed. Its a stock Ubuntu image. About connectivity there is no issue as i have created a 3 node cluster previously without any issues on the same subnet and vpc

**Comment by MaciekPytel** [comment]
As I said CA only adds new instances. You need instances to come up with kubelet and all necessary configuration to register themselves in cluster if you want to use CA.

I don't know much about kargo, but I think kops or kube-aws create ASGs for you so that any new instance is already kubernetes ready (I only use GCP myself, so don't quote me on this).

**Comment by Parag08** [comment]
okay got it I thought CA also make other configuration's on instances that come up. You may close the issue.
