### ISSUE TITLE
VPA cluster role system:admission-controller is too ambiguous

### ISSUE THREAD

**Issue by phsiao** [kubernetes/autoscaler#2334]
I'd like to suggest rename the cluster role `system:admission-controller` to something more specific, like `system:vpa-admission-controller`, in the [rbac definition](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-rbac.yaml#L228).

**Comment by bskiba** [comment]
That sounds very reasonable, would you be willing to contribute the change?

**Comment by phsiao** [comment]
Of course, PR is prepared for review.  I did a quick grep and I did not see any other dependency on the clusterrole's name.

One potential problem is, if someone already created the clusterrole and clusterrolebinding with the old name, and want to delete/cleanup using the new files, they will be leaving those two objects behind, whether they were created by VPA or not.

**Comment by bskiba** [comment]
That is true, but I'd rather not add deleting the admission-controller role in teardown scripts, since they might end up deleting an account used by sth else. Could you add a warning in the cleanup script to check if these objects are still around and delete if needed?

**Comment by phsiao** [comment]
That is reasonable.  I have added the warning text in the vpa-down.sh script if those objects still exist and is likely created by vpa-up.sh.

**Comment by bskiba** [comment]
Fixed.
