### ISSUE TITLE
Getting kubectl tls: internal error on worker nodes scaled up by Cluster Autoscaler

### ISSUE THREAD

**Issue by shray-chadha** [kubernetes/autoscaler#2337]
I created a k8s cluster using eksctl & then created Cluster Autoscaler deployment on it.

For the pods running on new worker nodes that were scaled out by Cluster Autoscaler, **kubectl logs** & **kubectl exec** is not working. Below error is thrown

> Error from server remote error: tls: internal error

I checked the kubelet logs on these scaled worker node, and found these logs :

> http: TLS handshake error from 172.XX.X.XX:48784: no serving certificate available for the kubelet

I also observed that the CSR generated by these nodes were in PENDING state. After manually approving these CSRs, **kubectl logs/exec** command threw this error

> Error from server: Get https://172.XXX.X.XX:10250/containerLogs/kube-system/container-name: x509: cannot validate certificate for 172.XXX.X.XX because it doesn't contain any IP SANs

This happens only when the Cluster Autoscalar provisions new worker node in the nodegroup.
Everything works fine if I manually change the desired count in the ASG group of the nodes.

I did made appropriate changes in the Cluster Autoscalar deployment yaml for the sslCert file path location as per eksctl

> command:
>         - ./cluster-autoscaler
>         - --v=4
>         - --stderrthreshold=info
>         - --cloud-provider=aws
>         - --skip-nodes-with-local-storage=false
>         - --expander=least-waste
>         - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/my-cluster
>       volumeMounts:
>         - name: ssl-certs
>           mountPath: /etc/eksctl/ca.crt
>           readOnly: true
>       imagePullPolicy: "Always"
>   volumes:
>     - name: ssl-certs
>       hostPath:
>         path: "/etc/eksctl/ca.crt"

**Comment by sudip-moengage** [comment]
@shray-chadha How did you overcome the problem? I'm facing same.
