### ISSUE TITLE
Cluster autoscaler scales up and scale down before GPU is become available

### ISSUE THREAD

**Issue by navi86** [kubernetes/autoscaler#2338]
/kind bug
autoscaler AWS version 1.12.7 doesn't have updates related to waiting 15 minutes before GPU instance become available

bug fr GCE
https://github.com/kubernetes/kubernetes/issues/54959

1.12 release doesn't have updates related for GPU instance label:
https://github.com/kubernetes/autoscaler/blob/5ac5736053aed8a60575f53a7a0bbb1b2449a41d/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L36
but it exists in master:
https://github.com/kubernetes/autoscaler/blob/bcbf50459e7a39fbf8d6e68e6dec74821f713bdf/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L37

updates related to GPU instance do not exist in the following releases:
- 1.12
- 1.13
- 1.14

**Comment by Jeffwan** [comment]
Hi, this is some feature we add to CA in the past and basically we just cherry-pick bug fix to previous versions. 

Can you try to upgrade your kubernetes cluster and then user higher level CA?

**Comment by navi86** [comment]
I can't upgrade Kubernetes cluster, I have to use CA 1.12.7 which is the latest version for k8s 1.12

**Comment by Jeffwan** [comment]
If you really need it, you can try cherry-pick https://github.com/kubernetes/autoscaler/pull/1584 to your branch and build container image by yourself. Normally, we only suggest to use image from community. You need to take risks for customized image.

**Comment by navi86** [comment]
@Jeffwan,
thanks for information.
