### ISSUE TITLE
Update documentation: AWS now supports ARNs for autoscaling groups

### ISSUE THREAD

**Issue by simnalamburt** [kubernetes/autoscaler#234]
In the past, AWS did not support ARNs for autoscaling groups.

> Unfortunately AWS does not support ARNs for autoscaling groups yet so you must use "*" as the resource. More information here.
>
> ###### Reference: [autoscaler/cluster-autoscaler/cloudprovider/aws/README.md](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#permissions)

Now, however, AWS seems to have started supporting ARNs for the Autoscale group.

> ### Auto Scaling Resources
>
> For actions that support resource-level permissions, you can control the Auto Scaling group or launch configuration that users are allowed to access.
>
> To specify an Auto Scaling group, you must specify its Amazon Resource Name (ARN) as follows:
>
> ```
> "Resource": "arn:aws:autoscaling:region:123456789012:autoScalingGroup:uuid:autoScalingGroupName/asg-name"
> ```
>
> ###### Reference: [Controlling Access to Your Auto Scaling Resources - Auto Scaling Resources](https://docs.aws.amazon.com/autoscaling/latest/userguide/control-access-using-iam.html#policy-auto-scaling-resources)

Documentation of this repository is also likely to require updates. Shall we?

**Comment by MaciekPytel** [comment]
If the docs are outdated and you want to fix it than by all means go for it. Probably @mumoshu would be the best person to review, as both me and @mwielgus use only GCP and don't know much details on how AWS works.

**Comment by simnalamburt** [comment]
Excuse me the corresponding PR has been submitted https://github.com/kubernetes/autoscaler/pull/527 and waiting to be merged.
