### ISSUE TITLE
Cluster Autoscaler's AWS EC2 instance type catalog needs to be updated

### ISSUE THREAD

**Issue by seh** [kubernetes/autoscaler#2376]
On 20 September 2019, [AWS announced](https://aws.amazon.com/about-aws/whats-new/2019/09/introducing-amazon-ec2-g4-instances-the-most-cost-effective-gpu-platform/) that a new EC2 instance family is available: [the G4](https://aws.amazon.com/ec2/instance-types/g4/). At present, [the cluster autoscaler's generated EC2 instance type catalog](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.16/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go) lacks members of this new instance family. Regenerate and commit that catalog to include the G4 family and any other newly added but unaccounted instance types.

Related: #2240 and #2249.

**Comment by Jeffwan** [comment]
Hi @seh Let me update PR and we can dynamically fetch instances

**Comment by Jeffwan** [comment]
/close

PR is out and we also enable to load instance dynamically in latest ca version
