### ISSUE TITLE
VPA does not restart pods unless there is more than one replica.

### ISSUE THREAD

**Issue by Leluke** [kubernetes/autoscaler#2388]
I have found duplicates of this issue without answers, so I am trying to find more information about it. 

It would be very useful if I could have the VPA recommend and update pods of deployments that run only one replica of their pods. We have a development environment where multiple namespaces are used to separate the different teams working in the same cluster.

Most of our development stack keeps our replicas to 1 to preserve resources and make debugging easier.

With VPA working or single replicas, we could take advantage of this and CA in order to keep our cluster as well utilized as possible. Nowadays, we have a over-requesting problem.

**Comment by bskiba** [comment]
If you are running VPA by yourself, you can modify the [flag in updater](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/main.go#L42) to lower the minimum count of replicas.

**Comment by Leluke** [comment]
I did only the basics of the installation, executed ./hack/vpa-up.sh then created some VPA objects following the hamster.yaml example. 
I have tried altering this value and recreate the Docker image but without success.

**Comment by bskiba** [comment]
Apologies, I thought that the current installation allows for this but it does not :(

I've sent #2395 to fix this in the latest release branch (0.6). Once that merges and tests run successfully, I'll make a new release (0.6.2) that will have ability to override default arguments for VPA containers. Then in your updater deployment you will just have to add
```
  args:
    - "--min-replicas=1"
```

**Comment by bskiba** [comment]
(One more note, if you specify args here, they will override the default ones, so if you would still like to pass for example --v=4, you will have to add it to the args as well)

**Comment by bskiba** [comment]
The 0.6.3 VPA release contains ability to override VPA container args.
#2416 will make the vpa-up script default to this version.
