### ISSUE TITLE
VPA: Accuracy of the estimation of the target value

### ISSUE THREAD

**Issue by Avanpourm** [kubernetes/autoscaler#2389]
The current target value is the percentile value of the histogram based on historical statistics. And this part of the data has no time limit, and the weight of each sample is the same, which leads to a problem: after the "user's service" runs for a long time, "Target" will converge to a certain value, and the latest The collected value has a very small effect on it. If the service demand becomes larger for some reason (probably the QPS is rising or a new version is released), then the "VPA" will calculate the correct Target after a long time.

For example, Service A has been running for 60 days. The user released a new version, and the CPU usage of the service has doubled. It may take 1.2 days for the VPA to calculate the correct Target value.

Can you consider two aspects:
1. Only take the latest data from the most recent period of time to calculate Targe (eg 1 month)
2. Set different weights for samples taken at different times. For example, the weight of the last week is even greater, and the weight of 30 days ago is very small.

**Comment by bskiba** [comment]
We're actually effectively using 8 days of history (covers weekly patterns), with weighted samples that have sort of 1 day half-decay - the yesterday sample is twice as important as the sample from two days ago. 

Having said that the target may take some time to converge, especially on scaledown, but with CPU doubling I would expect the target to converge in the order of hours, not days. 
Is this something that you actually observe happening? If yes, looks like I have some testing to do.

**Comment by Avanpourm** [comment]
@bskiba  
Thank you for your reply

There is another questions. storage When using checkpoint mode, the historical data is not only 8d, the history-length option is only valid for prometheus.

"ContainersInitialAggregateState" is only updated at initialization time and is not updated afterwards. Historical data is merged each time MergeCheckpointedState is called, so data from 8 days ago will be merged.

If the container is still running, the GC does not clear the data from the container 8 days ago, the data is always stored in memory and the target is calculated.

**Comment by bskiba** [comment]
To reiterate my question: 
Do you actually observe VPA taking more that 1 day to scale a service up on CPU?

To answer your comment:
The weights of samples will go down with time, due to the decaying histogram. In addition to that, there is a (mechanism which ignores samples with weight < epsilon)[https://github.com/kubernetes/autoscaler/blob/249aeab201bc97a8307f2f87d7e74ed16bfd15f7/vertical-pod-autoscaler/pkg/recommender/util/histogram.go#L213:21] so eventually those samples do fall out of the histogram.
The checkpoints that you mention are just compressed data from the decaying histogram, saved regularly by recommender.

Not sure if this addresses your concerns.

**Comment by Avanpourm** [comment]
> To reiterate my question:
> Do you actually observe VPA taking more that 1 day to scale a service up on CPU?
> 
---------------
1 day is not the observed data, only the assumed value.

**Comment by bskiba** [comment]
From our tests, if a stable service starts using more CPU that before, VPA will stabilize with a higher target in <4h. If you have a use case that shows worse performance, we would be very interested inreproducing and taking a look.

**Comment by Avanpourm** [comment]
From my test observation, after the program runs stably for a long time, if the CPU demand increases, the “Recommender” will calculate the correct Target value after 6 hours.

Some records：

Start to increase CPU usage
```
## 2019/09/27 20:20:47 CST
## kubectl top
vpa-example-668c79df66-dxk9c   251m         540Mi
## vpa
{"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"autoscaling.k8s.io/v1beta2\",\"kind\":\"VerticalPodAutoscaler\",\"metadata\":{\"annotations\":{},\"name\":\"vpa-example\",\"namespace\":\"dev-test\"},\"spec\":{\"targetRef\":{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"name\":\"vpa-example\"},\"updatePolicy\":{\"updateMode\":\"Recreate\"}}}\n"},"creationTimestamp":"2019-08-12T08:29:57Z","generation":5824,"name":"vpa-example","namespace":"dev-test","resourceVersion":"64199305","selfLink":"/apis/autoscaling.k8s.io/v1beta2/namespaces/dev-test/verticalpodautoscalers/vpa-example","uid":"5e111cda-bcdb-11e9-a608-44a8422aff3f"},"spec":{"targetRef":{"apiVersion":"extensions/v1beta1","kind":"Deployment","name":"vpa-example"},"updatePolicy":{"updateMode":"Recreate"}},"status":{"conditions":[{"lastTransitionTime":"2019-08-12T08:30:58Z","status":"True","type":"RecommendationProvided"}],"recommendation":{"containerRecommendations":[{"containerName":"vpa-example","lowerBound":{"cpu":"25m","memory":"262144k"},"target":{"cpu":"25m","memory":"671629701"},"uncappedTarget":{"cpu":"25m","memory":"671629701"},"upperBound":{"cpu":"25m","memory":"678936200"}}]}}}

## checkpoint
{"apiVersion":"autoscaling.k8s.io/v1beta2","items":[{"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscalerCheckpoint","metadata":{"creationTimestamp":"2019-08-12T08:29:58Z","generation":66250,"name":"vpa-example-vpa-example","namespace":"dev-test","resourceVersion":"64199308","selfLink":"/apis/autoscaling.k8s.io/v1beta2/namespaces/dev-test/verticalpodautoscalercheckpoints/vpa-example-vpa-example","uid":"5eaf4243-bcdb-11e9-8652-44a842311735"},"spec":{"containerName":"vpa-example","vpaObjectName":"vpa-example"},"status":{"cpuHistogram":{"bucketWeights":{"0":10000,"16":2},"referenceTimestamp":"2019-08-12T00:00:00Z","totalWeight":41232648227322990},"firstSampleStart":null,"lastSampleStart":"2019-09-27T12:20:00Z","lastUpdateTime":null,"memoryHistogram":{"bucketWeights":{"21":2812,"6":10000},"referenceTimestamp":"2019-08-13T00:00:00Z","totalWeight":455978409930086.4},"totalSamplesCount":132368,"version":"v3"}}],"kind":"VerticalPodAutoscalerCheckpointList","metadata":{"continue":"","resourceVersion":"64199411","selfLink":"/apis/autoscaling.k8s.io/v1beta2/namespaces/dev-test/verticalpodautoscalercheckpoints"}}

```

Recommender finally calculates the correct target
```
## 2019/09/28 03:13:09 CST
## kubectl top
vpa-example-668c79df66-dxk9c   290m         543Mi

## vpa
{"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"autoscaling.k8s.io/v1beta2\",\"kind\":\"VerticalPodAutoscaler\",\"metadata\":{\"annotations\":{},\"name\":\"vpa-example\",\"namespace\":\"dev-test\"},\"spec\":{\"targetRef\":{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"name\":\"vpa-example\"},\"updatePolicy\":{\"updateMode\":\"Recreate\"}}}\n"},"creationTimestamp":"2019-08-12T08:29:57Z","generation":6236,"name":"vpa-example","namespace":"dev-test","resourceVersion":"64299811","selfLink":"/apis/autoscaling.k8s.io/v1beta2/namespaces/dev-test/verticalpodautoscalers/vpa-example","uid":"5e111cda-bcdb-11e9-a608-44a8422aff3f"},"spec":{"targetRef":{"apiVersion":"extensions/v1beta1","kind":"Deployment","name":"vpa-example"},"updatePolicy":{"updateMode":"Recreate"}},"status":{"conditions":[{"lastTransitionTime":"2019-08-12T08:30:58Z","status":"True","type":"RecommendationProvided"}],"recommendation":{"containerRecommendations":[{"containerName":"vpa-example","lowerBound":{"cpu":"25m","memory":"262144k"},"target":{"cpu":"296m","memory":"671629701"},"uncappedTarget":{"cpu":"296m","memory":"671629701"},"upperBound":{"cpu":"353m","memory":"678913529"}}]}}}

## checkpoint
{"apiVersion":"autoscaling.k8s.io/v1beta2","items":[{"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscalerCheckpoint","metadata":{"creationTimestamp":"2019-08-12T08:29:58Z","generation":66662,"name":"vpa-example-vpa-example","namespace":"dev-test","resourceVersion":"64299813","selfLink":"/apis/autoscaling.k8s.io/v1beta2/namespaces/dev-test/verticalpodautoscalercheckpoints/vpa-example-vpa-example","uid":"5eaf4243-bcdb-11e9-8652-44a842311735"},"spec":{"containerName":"vpa-example","vpaObjectName":"vpa-example"},"status":{"cpuHistogram":{"bucketWeights":{"0":10000,"16":2,"17":23,"18":800,"19":288},"referenceTimestamp":"2019-08-12T00:00:00Z","totalWeight":45812516438464184},"firstSampleStart":null,"lastSampleStart":"2019-09-27T19:12:00Z","lastUpdateTime":null,"memoryHistogram":{"bucketWeights":{"21":2812,"6":10000},"referenceTimestamp":"2019-08-13T00:00:00Z","totalWeight":455978409930086.4},"totalSamplesCount":132780,"version":"v3"}}],"kind":"VerticalPodAutoscalerCheckpointList","metadata":{"continue":"","resourceVersion":"64299998","selfLink":"/apis/autoscaling.k8s.io/v1beta2/namespaces/dev-test/verticalpodautoscalercheckpoints"}}
```

**Comment by davidquarles** [comment]
@bskiba I just wanted to verify my understanding here – the decayed weights are discretely bucketed by age in *days*, right?  I'm hoping to put a bunch of our async workloads (MQ consumers) behind VPA, but I'm a little worried about the implications of doing so with highly bursty queues (e.g. those that idle for ~24h before receiving a nondeterministic amount of jobs to process).  Once we get to 1.16, we should be able to scale these deployments to 0 with object metrics and this becomes a non-issue, but I'm hoping there's some interim path to VPA here.

**Comment by bskiba** [comment]
@Avanpourm 6 hours sounds possible. While not ideal, the VPA is not suite for fast reaction time, this is what the Horizontal Pod Autoscaling will achieve for you. You will see faster VPA reactions for scaling up memory, which is way more crucial as the non-compressible resource. CPU is less crucial and is also more problematic in a way as we don't currently detect CPU throttling. If you find that the current algorithm is not satisfactory, you can try to tweak some histogram parameters to make sure that the newer samples are even more important, but you may loose important historical samples then.

@davidquarles In general the solution will try to make sure that the CPU target recommendation for your workload is above your usage around 90% of the time. So if your workloads are active for <10% of the time, you may find VPA not working well for you. In general I recommend trying it out in the recommendation-only mode ("Off") and taking a look if the recommendation matches you expectations.

**Comment by elfhack** [comment]
@bskiba Sorry to hijack the thread, but could you explain in a bit how does vpa actually relate to metrics gotten from metrics-server to the buckets in a VerticalPodAutoscalerCheckpoint? I'm trying to follow the code in histogram.go but I don't understand how buckets are calculated and scaled.

**Comment by bskiba** [comment]
Sorry for the long silence here. I've filed #2747 to document the current recommendation algorithm. Please add pieces that you would like documented there.
/close
