### ISSUE TITLE
Ability to Source VPA through Kustomize

### ISSUE THREAD

**Issue by KyleMasterson** [kubernetes/autoscaler#2390]
I am using Kustomize to make cluster deployments, however since VPA is not a natively available, I would like to source the required configuration files using a remote target. However, Kustomize currently requires that the source at the remote target be configured with a `kustomization.yaml` file and that will be used to run `kustomize build`.

I would like to request that these configuration files be added to support this functionality.

Kustomize example of using remote targets:

- https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#remote-targets

**Comment by bskiba** [comment]
Since we don't really have experience with kustomize here, we'd gladly accept contributions on this one if anyone is interested.

**Comment by tyrken** [comment]
Looks like this has been done in https://github.com/kubernetes/autoscaler/pull/3434 ?
