### ISSUE TITLE
AWS Unknown instance type g4dn

### ISSUE THREAD

**Issue by Luke035** [kubernetes/autoscaler#2399]
Hi all,

I'm experimenting AWS g4dn instance types but those are still unknown for the autoscaler: 

```
Unable to build proper template node for REDACTED: ASG "REDACTED" uses the unknown EC2 instance type "g4dn.xlarge"
```

If those are not supported I've to revert to p2 types for ML inference, any clue on how to perform a temporary hotfix while waiting for official support? 

Thanks

**Comment by Luke035** [comment]
It was quite easy, I've just create a pull request for it https://github.com/kubernetes/autoscaler/pull/2401

**Comment by seh** [comment]
Related: #2376.

**Comment by Jeffwan** [comment]
Let's close this one since static file has been updated and g4dn is available.

/close
