### ISSUE TITLE
Old Version of scheduler/algorithm/predicates

### ISSUE THREAD

**Issue by ahmad-diaa** [kubernetes/autoscaler#2402]
As part of  https://github.com/kubernetes/kubernetes/issues/71859, we are moving all `factory.NewConfigFactory` to `scheduler.New`. `cluster-autoscaler/simulator/predicates.go` is one of the users, however it is using an old version of `k8s.io/kubernetes/pkg/scheduler/algorithm/predicates`.

As a result, the following line 
https://github.com/kubernetes/autoscaler/blob/f33bc5bafff2a5302398fbb0a5ac89fa65869cf6/cluster-autoscaler/simulator/predicates.go#L195 is going to be changed to `metadataProducer := predicates.GetPredicateMetadata`.  Using an old version of `k8s.io/kubernetes/pkg/scheduler/algorithm/predicates` blocks this change.

Are there any plans to move to a newer version?

**Comment by ahmad-diaa** [comment]
cc @alculquicondor @ahg-g

**Comment by alculquicondor** [comment]
cc @MaciekPytel

**Comment by ahg-g** [comment]
/close

https://github.com/kubernetes/autoscaler/issues/2449
