### ISSUE TITLE
Failed to regenerate ASG cache: cannot autodiscover ASGs.

### ISSUE THREAD

**Issue by xinxingliu90** [kubernetes/autoscaler#2429]
I deployed cluster-autoscaler successfully before adding `--node-group-auto-discovery ` flag.

But after adding this flag, the following error indicates that : "Failed to create AWS Manager: cannot autodiscover ASGs: MissingRegion: could not find region configuration"

Because of that, I added environment variables like 
```
env:
        - name: AWS_REGION
          value: "us-west-2"
```

Eventually, I hit following error:

```
Failed to regenerate ASG cache: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F1007 22:47:24.143458       6 cloud_provider_builder.go:149] Failed to create AWS Manager: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Could anyone help me on that so that I can deploy cluster-autoscaler.yaml successfully?

**Comment by xinxingliu90** [comment]
Add @Jeffwan to this channel .

**Comment by Jeffwan** [comment]
@xinxingliu90 
Need your CA version to double check. It's mostly because of credential issue. you need to make sure either your node group has IAM roles with right policies or CA has AWS environment variables.

**Comment by xinxingliu90** [comment]
@Jeffwan You are right it is my ip rules prevents the deployment from getting credentials. Thanks for the answer!

**Comment by Jeffwan** [comment]
As you figure it out, I will close this issue

/close

**Comment by AnandKrishna44** [comment]
> @Jeffwan You are right it is my ip rules prevents the deployment from getting credentials. Thanks for the answer!

Hi , can you please ellaborate how you resolved this?

**Comment by vsivaguru** [comment]
Hi, In my case, our network firewall blocked the resolution for domain eks-auth.eu-west-3.api.aws
The following endpoint provides the Amazon EKS Auth API. The EKS Pod Identity Agent on your nodes connects to this endpoint to get the credentials for each pod. https://docs.aws.amazon.com/general/latest/gr/eks.html
