### ISSUE TITLE
CA minSize has no effect

### ISSUE THREAD

**Issue by mariojacobo** [kubernetes/autoscaler#2438]
We run CA inside AKS and have noticed some strange behavior (unless I'm misunderstanding the default one). 

If I change the minSize of the CA deployment to be greater than the cloudProviderTarget size, nothing happens.  The logs just show "node group min size reached". 

```
$ kubectl -n kube-system describe configmap cluster-autoscaler-status | grep minSize
  Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0 cloudProviderTarget=2 (minSize=3, maxSize=10))

I1010 13:27:51.081869       1 utils.go:521] Skipping aks-agentpool-32800724-2 - node group min size reached
I1010 13:27:51.081890       1 utils.go:521] Skipping aks-agentpool-32800724-0 - node group min size reached
```

If I change the minSize of CA deployment to be lower than the cloudProviderTarget size, then it will try to scale down, but if there's a kube-system POD on the particular node, then it will complain: 

```
cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: coredns-45565gd-bvhgj 
```
This happens with other kube-system pods, such as tunnelfront, tiller-deploy, etc... 

The workaround we have is to first increase the cluster size from the Azure side, then match the minSize in the CA as well. This takes care of the scaling up part. To scale down, we changed the CA deployment to use "--skip-nodes-with-system-pods=false".  

So, shouldn't the CA automatically scale up when changing the minSize ? It seems to totally ignore it, but will scale up properly if there are pending PODs.

**Comment by feiskyer** [comment]
NO, this is working as expected. See the [FAQ ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md) for details.
/area provider/azure
/close
