### ISSUE TITLE
Autoscaling GPU based node on AWS doubled

### ISSUE THREAD

**Issue by Luke035** [kubernetes/autoscaler#2446]
Hi all, 

I have 2 ASGs configured in an EKS cluster, one with p3.xlarge machine and one with g4dn.xlarge machine. 

In order to differentiate between the two the only solution I found was to discriminate the number of required CPUs in order to trigger g4dn or p3 machines (with CPU less than 4vCPUs g4dn ASG will be triggered given a higher priority on the autoscale configuration.

Here you can find the priority config map I used

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    #Lower priority to most expensive nodes
    10: 
      - p3.2xlarge
    20:
      - g4dn.xlarge
    30:
      - cpubase
    50: 
      - cpubased
```

When I trigger a deployment with 1GPU and 3 vCPU g4dn ASG is triggered correctly 

```
I1011 13:55:37.029029       1 scale_up.go:415] No pod can fit to REDACTED
I1011 13:55:37.029254       1 priority.go:118] Successfully loaded priority configuration from configmap.
W1011 13:55:37.029297       1 priority.go:91] Priority expander: node group REDACTED not found in priority expander configuration. The group won't be used.
I1011 13:55:37.029307       1 priority.go:167] priority expander: REDACTED chosen as the highest available
I1011 13:55:37.029318       1 scale_up.go:427] Best option to resize: REDACTED
I1011 13:55:37.029327       1 scale_up.go:431] Estimated 1 nodes needed in REDACTED
I1011 13:55:37.029344       1 scale_up.go:533] Final scale-up plan: [{REDACTED 0->1 (max: 5)}]
[...]
```

Just some few seconds before new node is powered on, upcoming node become 0, and p3 2xlarge ASG is triggered
```
I1011 13:57:08.231671       1 scale_up.go:304] Upcoming 0 nodes
I1011 13:57:08.231690       1 utils.go:226] Pod REDACTED can't be scheduled on REDACTED, predicate failed: PodFitsResources predicate mismatch, reason: Insufficient nvidia.com/gpu
I1011 13:57:08.231706       1 scale_up.go:415] No pod can fit to REDACTED
I1011 13:57:08.231721       1 utils.go:226] Pod REDACTED can't be scheduled on REDACTED, predicate failed: PodFitsResources predicate mismatch, reason: Insufficient nvidia.com/gpu
I1011 13:57:08.231736       1 scale_up.go:415] No pod can fit to REDACTED
I1011 13:57:08.231748       1 utils.go:226] Pod REDACTED, predicate failed: PodFitsResources predicate mismatch, reason: Insufficient nvidia.com/gpu
I1011 13:57:08.231760       1 scale_up.go:415] No pod can fit to REDACTED
I1011 13:57:08.231886       1 priority.go:118] Successfully loaded priority configuration from configmap.
I1011 13:57:08.231896       1 priority.go:167] priority expander: REDACTED chosen as the highest available
I1011 13:57:08.231903       1 scale_up.go:427] Best option to resize: REDACTED
I1011 13:57:08.231909       1 scale_up.go:431] Estimated 1 nodes needed in REDACTED
I1011 13:57:08.231919       1 scale_up.go:533] Final scale-up plan: [{REDACTED 1->2 (max: 2)}]
I1011 13:57:08.231932       1 scale_up.go:699] Scale-up: setting group REDACTED size to 2
I1011 13:57:08.231949       1 auto_scaling_groups.go:203] Setting asg REDACTEED size to 2
I1011 13:57:08.232429       1 event.go:258] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"REDACTED", APIVersion:"v1", ResourceVersion:"26586556", FieldPath:""}): type: 'Normal' reason: 'ScaledUpGroup' Scale-up: setting group REDACTED size to 2
I1011 13:57:08.374803       1 event.go:258] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"REDACTED", APIVersion:"v1", ResourceVersion:"26586556", FieldPath:""}): type: 'Normal' reason: 'ScaledUpGroup' Scale-up: group REDACTED size set to 2
I1011 13:57:08.374828       1 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kubeflow", Name:"REDATCED", UID:"REDACTED", APIVersion:"v1", ResourceVersion:"26586586", FieldPath:""}): type: 'Normal' reason: 'TriggeredScaleUp' pod triggered scale-up: [{REDACTED 1->2 (max: 2)}]
I1011 13:57:18.385223       1 static_autoscaler.go:187] Starting main loop
```

After few moments POD is scheduled in the g4dn node, and p3.2xlarge is eventually powered off due to unuse. 

Is this behavior correct? It seems like an autoscaler bug

**Comment by Jeffwan** [comment]
hey @Luke035, it takes time for GPU to become ready. During that time, if your pod can not be fit on that G4 instance node, CA will consider G4 node group is not able to schedule your pod, it will go to p3 to bring up nodes. I solve this problem in https://github.com/kubernetes/autoscaler/pull/1584

In order for CA to wait GPU ready on G4, you need to label node. Check PR for details and let me know if something is wrong.

**Comment by Luke035** [comment]
Hi @Jeffwan  thanks a lot for you support. Can you please indicate me some documentation regarding node labeling? I'm struggling in understanding how to label nodes if they're not created yet.

**Comment by Jeffwan** [comment]
@Luke035 

Can you check this section?
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#scaling-a-node-group-to-0


1. Make sure your cluster has some label like this
--kubelet-extra-args --node-labels=k8s.amazonaws.com/accelerator=nvidia-tesla-v100

2. Make sure your ASG has tag
"Key": "k8s.io/cluster-autoscaler/node-template/label/k8s.amazonaws.com/accelerator" “Value”: “nvidia-tesla-v100”

**Comment by Luke035** [comment]
Hi @Jeffwan 
thanks for the support.

1- Is `node-labels` a parameter that should be added to kubelet? If so is it possible to add it through eksctl without having to restart the whole cluster?

2- OK

**Comment by Jeffwan** [comment]
@Luke035 you can definitely add to eksctl setups. For existing cluster, you need to change ASG user data to make sure argument is added there. Otherwise, even you label existing nodes, new node created by ASG won't have the label

**Comment by Jeffwan** [comment]
This issue has been resolved. We can close it. Feel free to reopen if you still have the problem
