### ISSUE TITLE
Want to know some concepts of node group?

### ISSUE THREAD

**Issue by qibobo** [kubernetes/autoscaler#2457]
I am new to the cluster autocaler. When I read the code I found that there are "node group" related things in the code. But I do not find a place what does these mean?
NodeGroup
NodeGroup MinSize
NodeGroup MaxSize
When doing scale down, func "getPotentiallyUnneededNodes" was called. The nodes "in groups with size > min size" are selected. What does the "node size" mean and how to calculate it?

**Comment by MaciekPytel** [comment]
Sorry, I've missed this before. NodeGroup is a re-sizable set of identical VMs. In most cases it corresponds to some managed instance feature of a given cloud provider (ex. ASG on AWS, MIG on GCE, VMSS on Azure). 
You can define min and max number of VMs in each NodeGroup (via --nodes flag or various autodiscovery settings). Those are used for constraining how far CA can scale-up/down a given NodeGroup (ex. "I want to have as many nodes as are needed to run all pods, but no more than 10").
/remove-lifecycle rotten
