### ISSUE TITLE
Priority expander not supported on AWS

### ISSUE THREAD

**Issue by pedrogimenez** [kubernetes/autoscaler#2469]
Hey,

We're trying to use `expander=priority` on AWS in order to use spot nodes whenever possible instead of using on-demand nodes. However, it doesn't seem to be supported on AWS. We've seen a few issues that suggest that it is, but we can't make it work.

**Version**: k8s.gcr.io/cluster-autoscaler:v1.13.8
**Logs**:

```
I1019 09:27:41.651381       1 auto_scaling_groups.go:128] Registering ASG irrelevant-asg
I1019 09:27:41.651416       1 auto_scaling_groups.go:128] Registering ASG irrelevant-spot-asg
I1019 09:27:41.651426       1 aws_manager.go:160] Refreshed ASG list, next refresh after 2019-10-19 09:28:41.651422649 +0000 UTC m=+62.479410211
F1019 09:27:41.651454       1 main.go:292] Failed to create autoscaler: Expander priority not supported
```

Is there any way to make this work? CA neither supports `preferredDuringSchedulingIgnoredDuringExecution` so we're wondering how can we implement this —I think pretty common— use case.

Thank you!

**Comment by MaciekPytel** [comment]
Priority expander should work with any cloudprovider, but it was only added in 1.15.

**Comment by pedrogimenez** [comment]
I didn't see the release in https://github.com/kubernetes/autoscaler/releases. I got it working using taints anyway. Thank you!

**Comment by Jeffwan** [comment]
Here's the recent release for 1.15 https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.3. You're using 1.13.

/close

**Comment by reubenavery** [comment]
EKS only goes up to Kubernetes 1.14.. any chance of this being backported to CA 1.14.x?

**Comment by Jeffwan** [comment]
@reubenavery This is a large feature we normally won't back port to 1.14 and previous versions. You can wait to late Jan or Feb for 1.15.
