### ISSUE TITLE
Use apps/v1 in stead of post 1.16.x deprecated apis (extensions/v1beta1)

### ISSUE THREAD

**Issue by drewboswell** [kubernetes/autoscaler#2473]
TLDR; "extensions/v1beta1" bad, "apps/v1" good.

There are references to extensions/v1beta1 everywhere in this repository including in the go code.
These will not work for 1.16.x + k8s clusters.

using "apps/v1" allows for compatibility for clusters 1.9.x+.

**Comment by bskiba** [comment]
The only references left are the ones in tests for object references, which should be fine.
Closing
/close
