### ISSUE TITLE
extending node similarity check to cluster autoscaler provider

### ISSUE THREAD

**Issue by arahamad** [kubernetes/autoscaler#2488]
as of now cluster autoscaler is checking node similarity on the basis of node labels and its static check in the core ca. Although provider can register comparator but that also need to be part of core ca i.e in main.go file which does not looks good. it would be good if we can extend node similarity functionality to provider so that let provider decide node similarity.

although kubernets also provide capability to kube-cluster provider to add their own customer labels hence to align to that it will be good if ca can have interface for ca provider to implement node similarity rather then core ca implement that.

**Comment by MaciekPytel** [comment]
A more generic solution would be to allow cloudproviders to register their own processors. Maybe pass AutoscalingProcessors to cloudprovider builder and allow the builder to mutate it?

**Comment by MaciekPytel** [comment]
cc: @losipiuk I think you mentioned something similar on one of the previous issues about customizing NodeGroupSetProcessor?
