### ISSUE TITLE
Missing events on status config map

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#2495]
Even though `Scale-up: group` events (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scale_up.go#L715) should have been triggered as well for the status configMap as shows the log:

```
Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"test", Name:"cluster-autoscaler-status", UID:"6f9ba031-9377-4984-8a91-a8f6ef363f63", APIVersion:"v1", ResourceVersion:"225776", FieldPath:""}): type: 'Normal' reason: 'ScaledUpGroup' Scale-up: group test/e2e-d6645-w-2 size set to 2
```
I can always only see/receive one single `Scale-up: setting` (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scale_up.go#L701) event:

```
kubectl describe configmap cluster-autoscaler-status

Events:
  Type    Reason         Age   From                Message
  ----    ------         ----  ----                -------
  Normal  ScaledUpGroup  50s   cluster-autoscaler  Scale-up: setting group test/e2e-d6645-w-1 size to 2
```

Not sure what I'm missing.

**Comment by enxebre** [comment]
If I revert https://github.com/kubernetes/autoscaler/commit/6601bf0598140884ed06d37123da6d1c310a45fa I see all the events coming through.

**Comment by MaciekPytel** [comment]
@vivekbagade Can you take a look?

**Comment by vivekbagade** [comment]
@MaciekPytel Sure

**Comment by vivekbagade** [comment]
Hi @enxebre. The PR you mentioned aggregates events so that CA for scalability reason where we don't want to send a lot of similar events which might happen if we have too many unschedulable pods.

We'll fix this by having a different config for the logrecoder. Expect the fix some time next week

**Comment by marwanad** [comment]
@vivekbagade any updates on this issue? It seems that since 1.16, scale up failures are also not logged on the configmap properly. Reverting this change seems to make things work as normal though.

**Comment by marwanad** [comment]
@vivekbagade @MaciekPytel gentle ping on this issue. It seems that the events are restricted to one per nodegroup.

**Comment by elmiko** [comment]
/remove-lifecycle rotten

@vivekbagade and @marwanad i am looking into making some progress on this, do you remember what the logrecorder fix referenced earlier was referring to?

> We'll fix this by having a different config for the logrecoder.

i have some time to create a patch here, but i'm a little confused about that statement. alternatively we could revert the change. curious to hear any thoughts if folks remember this ;)

**Comment by elmiko** [comment]
/remove-lifecycle rotten

i'm still interested in seeing the ability to get the duplicated messages. i know adding a flag is not an ideal solution, but i would like to propose a solution where the user has the ability to disable de-duplication of messages.

**Comment by elmiko** [comment]
we talked about this issue at the sig meeting today, i am going to propose a patch with a flag to enable de-duplication of messages.
