### ISSUE TITLE
Should cordon and drain before deleting Azure VMSS node

### ISSUE THREAD

**Issue by mboersma** [kubernetes/autoscaler#2505]
We've noticed scenarios where Azure VMSS nodes in a certain state may become stuck in such a way that can pin stateful workloads to them after cluster-autoscaler requests them to be deleted.

A more robust approach would be to cordon and drain the VMSS node before CA deletes it, so that a stuck node cannot drag a stateful workload down with it.

**Comment by feiskyer** [comment]
@mboersma CA already drain the node before deleting the VM. Do you have CA and k8s logs that we could have a look?

/area provider/azure

**Comment by nilo19** [comment]
@mboersma is the issue still there? If so could you help to provide more info for us to gain insight into it?

**Comment by mboersma** [comment]
I don't have a repro of this issue any longer, and we may have been assuming CA wasn't already draining the node before deleting the VM. I'll close this and we can open if we find a reproducible csae.
