### ISSUE TITLE
Feature request: Incorporate nearest billing hour into scale down algorithm

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/autoscaler#251]
AWS bills instances by the hour, so if we scale down an instance after it has been up for 15 minutes, we still get billed for 60 minutes.  Ideally, the cluster autoscaler could take into account when the next billing hour is.  E.g. have a `scale-down-minutes-before-billing-hour` parameter that when set to a non-negative number, only makes the node eligible to scale down when it is within `x` mins of the billing hour.

Not sure if the billing hour is something we can determine... so this may be hard/impossible.

**Comment by mwielgus** [comment]
It can be assumed, with high probability, that an instance was "bought" couple minutes before node CreateTime. However `scale-down-minutes-before-billing-hour` will work only on small clusters - it can take a minute (or two) to delete a not-completely-empty node and during that time we will not do other delete operations (empty nodes are deleted in bulk). So if you have 30 unneeded nodes that are not completely empty and you specify `scale-down-minutes-before-billing-hour` to 10 min it will take more than 3h to get rid of them, so effectively you will pay more.

**Comment by ryanwalls** [comment]
@mwielgus Yeah, I figured it might not be useful for some cases, so I would think we would set `scale-down-minutes-before-billing-hour` to `-1` by default, which would indicate to ignore the parameter.  

It would just give us one more lever to try and fine tune the optimal scaling solution.   

Currently we are running a small cluster with low/sporadic volume, so this could potentially save us 20-30% a month.  

If you're ok with it, I could work on a PR.

**Comment by johanneswuerbach** [comment]
I think prioritising the instance to be deleted based on the distance to the next billing hour could already be quite helpful.

AWS ASGs have a similar concept called Termination Policy `ClosestToNextInstanceHour`  
http://docs.aws.amazon.com/autoscaling/latest/userguide/as-instance-termination.html#custom-termination-policy 

Sounds a bit like all of those could be provided as different termination strategies similar to the current expander strategies.

**Comment by mwielgus** [comment]
cc: @mumoshu @MaciekPytel @aleksandra-malinowska @bskiba 

Ideally we would like to have some kind of interface that:
* gets a list of nodes that are OK-ish to be deleted 
* removes the nodes that are not so OK to to be deleted
* sorts the remaining nodes according to some criteria so that the nodes at the front should be removed first, if possible. 

As we are just couple days to feature freeze we won't have this interface for K8S 1.8 but I'm happy to have it for the next release.

**Comment by ryanwalls** [comment]
Overtaken by events.  https://aws.amazon.com/blogs/aws/new-per-second-billing-for-ec2-instances-and-ebs-volumes
