### ISSUE TITLE
Is the expander named most-pods really working during scaling up?

### ISSUE THREAD

**Issue by wccsama** [kubernetes/autoscaler#2513]
1、build two group
   group1: min 0 max 5 cpu 1 MEM 1, currentSize 4, left 1 quota
   group2: min 0 max 5 cpu 4 MEM 4

2、create a pod request 0.7 cpu , try to trigger scaling up

3、set expander=“most-pods”

4、CA may scale up using either group1 or group2

I have saw the code like following:

```
func (m *mostpods) BestOption(expansionOptions []expander.Option, nodeInfo map[string]*schedulernodeinfo.NodeInfo) *expander.Option {
	var maxPods int
	var maxOptions []expander.Option

	for _, option := range expansionOptions {
		if len(option.Pods) == maxPods {
			maxOptions = append(maxOptions, option)
		}

		if len(option.Pods) > maxPods {
			maxPods = len(option.Pods)
			maxOptions = []expander.Option{option}
		}
	}

	if len(maxOptions) == 0 {
		return nil
	}

	return m.fallbackStrategy.BestOption(maxOptions, nodeInfo)
}
```

I think there may be something wrong with the code.

CA version:1.15.0

**Comment by MaciekPytel** [comment]
Sorry, I missed this before. most-pods expander picks up a scale-up that will help the largest number of pending pods in one go. It doesn't optimize for efficient packing.

**Comment by wccsama** [comment]
> oesn't op

Got it，Thanks~

**Comment by wccsama** [comment]
> Sorry, I missed this before. most-pods expander picks up a scale-up that will help the largest number of pending pods in one go. It doesn't optimize for efficient packing.

Got it，Thanks~
