### ISSUE TITLE
CA in Azure Does Not Propagate Node Labels to New Nodes

### ISSUE THREAD

**Issue by reddog335** [kubernetes/autoscaler#2519]
I added a tag named ‘**k8s.io_cluster-autoscaler_node-template_label_nodesize**’ with a value of ‘**large**’ to the VMSS pool.  When I triggered another cluster autoscaler event, the newly provisioned node (aks-nodepool1-26580627-vmss00001m) did not have the nodesize label (labels from aks-nodepool1-26580627-vmss00001m below).
 
Name:          aks-nodepool1-26580627-vmss00001m
Roles:           agent
Labels:         agentpool=nodepool1
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_DS3_v2
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=centralus
                    failure-domain.beta.kubernetes.io/zone=3
                    kubernetes.azure.com/cluster=rg-inf-enterpriseaksnodes-dynamic-itg
                    kubernetes.azure.com/role=agent
                    kubernetes.io/hostname=aks-nodepool1-26580627-vmss00001m
                    kubernetes.io/role=agent
                    node-role.kubernetes.io/agent=
                    storageprofile=managed
                    storagetier=Premium_LRS

Is this feature not supported in Azure?  Thanks!

**Comment by feiskyer** [comment]
@reddog335  CA won't propagate node labels to new nodes, it only uses the label to build the node template when there're no nodes in the nodepool.

**Comment by reddog335** [comment]
@feiskyer   Is it possible to make this functionality a feature request?

**Comment by feiskyer** [comment]
@reddog335 I don't think this is a supported scenario as CA won't make changes to the nodes after scaling. Could you run a daemonset and update the labels when new nodes presents?

**Comment by reddog335** [comment]
@feiskyer That's a great suggestion, I'll explore that.  I'm closing the issue, thanks for your time.
