### ISSUE TITLE
AWS: Sample AWS IAM role should contain a condition for region.

### ISSUE THREAD

**Issue by echoboomer** [kubernetes/autoscaler#2529]
This is purely opinion. Referencing the doc located [here](https://github.com/kubernetes/autoscaler/blob/3da8964ead179c471f6a2d17dde9b35b935df2ab/cluster-autoscaler/cloudprovider/aws/README.md).

Adding in a block to specify region in the minimum IAM policy sample may be helpful:
```
"Condition": {
  "StringEquals": {
    "aws:RequestedRegion": "us-foobar-1"
    }
}
```

A sample of this in use can be found [here](https://aws.amazon.com/blogs/security/easier-way-to-control-access-to-aws-regions-using-iam-policies/).

I feel like this would benefit others who may run into issues. Specifically, when rolling `cluster-autoscaler` out to an EKS cluster using the [Helm chart](https://github.com/helm/charts/tree/master/stable/cluster-autoscaler), it is entirely possible to neglect to update the variable for `awsRegion` which defaults to `us-east-1`. If running single-region in `us-east-1` and then deploying to another region, this could result in disrupting an existing cluster in `us-east-1` unintentionally via scaling an autoscaling group to 0, etc.

While the onus is on consumers to verify that usage of variables is accurate, this would provide an additional layer of protection.

**Comment by Jeffwan** [comment]
@echoboomer Thanks for the suggestion. The condition needs to be added into policy but I think someone may prefer region neutral configuration. Do you think this is a change you can make on helm chart side?
