### ISSUE TITLE
Set up HTTP Proxy

### ISSUE THREAD

**Issue by dignajar** [kubernetes/autoscaler#2532]
Hi,
my Kubernetes cluster is in a subnet without internet access so I need to go through a HTTP proxy.

I'm using VPC Endpoints to avoid connect to the internet and reach the AWS services but the endpoint `autoscaling.eu-central-1.amazonaws.com` is not possible to set up in VPC endpoints so need to go through the HTTP proxy.

```
E1113 10:39:21.362613       1 aws_manager.go:154] Failed to regenerate ASG cache: cannot autodiscover ASGs: RequestError: send request failed
caused by: Post https://autoscaling.eu-central-1.amazonaws.com/: dial tcp 54.239.55.230:443: i/o timeout
F1113 10:39:21.362646       1 cloud_provider_builder.go:149] Failed to create AWS Manager: cannot autodiscover ASGs: RequestError: send request failed
caused by: Post https://autoscaling.eu-central-1.amazonaws.com/: dial tcp 54.239.55.230:443: i/o timeout
```

It's possible to set up HTTP proxy?

Regards

**Comment by maust** [comment]
There is now a VPC enpoint for autoscaling available. So autoscaling.eu-central-1.amazonaws.com can be made available within the VPC without any need for a proxy. So this could be closed as I would see.
