### ISSUE TITLE
Explain how buckets are calculated in VerticalPodAutoscalerCheckpoint

### ISSUE THREAD

**Issue by elfhack** [kubernetes/autoscaler#2542]
We would like to know how exactly buckets in VerticalPodAutoscalerCheckpoint are mapped to cpu/memory usage. As in, how do various usages of cpu/memory are placed in which bucket, and does one calculate it from the checkpoint?

```yaml
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscalerCheckpoint
metadata:
  creationTimestamp: 2019-11-15T13:35:11Z
  generation: 1
  name: xx
  namespace: x
  resourceVersion: "95172875"
  selfLink: /apis/autoscaling.k8s.io/v1beta1/namespaces/x/verticalpodautoscalercheckpoints/xx
  uid: bfa72938-07ac-11ea-819e-02691b95edbc
spec:
  containerName: xx
  vpaObjectName: xx
status:
  cpuHistogram:
    bucketWeights:
      "0": 10000
      "1": 133
      "2": 96
      "3": 29
      "4": 4
      "5": 5
      "7": 2
    referenceTimestamp: 2019-11-16T00:00:00Z
    totalWeight: 4396.8574
  firstSampleStart: null
  lastSampleStart: 2019-11-19T12:09:24Z
  lastUpdateTime: null
  memoryHistogram:
    bucketWeights:
      "10": 324
      "11": 10000
    referenceTimestamp: 2019-11-17T00:00:00Z
    totalWeight: 23.46872
  totalSamplesCount: 11337
  version: v3```

**Comment by bskiba** [comment]
Please note that the VPA algorithm might change in the future, so this is not guaranteed to stay the same.

The checkpoint contains a summary of observed usage and is compressed to be as small as possible, to not take up space in the etcd.  The clue to understanding the histogram is the [decaying histogram](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/util/decaying_histogram.go#L34) with [exponential buckets](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/util/histogram_options.go#L61). It is not possible to reconstruct the exact samples that were put into histogram (these are approximated by the bucket ranges). 

Samples are placed in a given bucket if bucket_start < sample_value < bucket_end. Bucket starts and ends currently used are defined [here](https://github.com/kubernetes/autoscaler/blob/59e36a2fb33f8656931e086ed7306f9fd21110fd/vertical-pod-autoscaler/pkg/recommender/model/aggregations_config.go#L63). In the buckets we don't keep samples count but the total weight of the samples in the bucket. The weight of the samples is decreasing with time (older are less important). See [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/util/decaying_histogram.go#L34) for an excellent description of how this mechanism works.

**Comment by nikimanoledaki** [comment]
It would be really helpful if we could add this and more info about the VPA Recommender's calculations to the docs. WDYT @bskiba (+cc @voelzmo)?

**Comment by voelzmo** [comment]
This sound like a good addition to the docs, yeah. I'm happy to look at a PR adding this as a section, maybe to the FAQ?
