### ISSUE TITLE
vpa-recommender: no way to easily debug issues with cluster state

### ISSUE THREAD

**Issue by milesbxf** [kubernetes/autoscaler#2552]
Whilst testing my changes to improve the Prometheus history provider, it's been very difficult to verify that the right samples are being added and introspect how these samples are being linked to running pods.

I think it'd be really useful to be able to inspect the vpa-recommender's internal state. Initially a simple HTTP endpoint that returns a blob of JSON would be good, but we could potentially have some kind of UI that lets you filter and dig into things.

**Comment by kcmartin** [comment]
@milesbxf Not sure if this meets your requirements, but the VPA Recommender metrics are now exposed through kube-state-metrics:

https://github.com/kubernetes/kube-state-metrics/pull/791

**Comment by milesbxf** [comment]
> @milesbxf Not sure if this meets your requirements, but the VPA Recommender metrics are now exposed through kube-state-metrics:
> 
> [kubernetes/kube-state-metrics#791](https://github.com/kubernetes/kube-state-metrics/pull/791)

Hey @kcmartin, I actually raised that PR 😁thanks though! The problem we're really having to being able to work out and understand how calculations are being made. For example - how many data points of history do we have? What are the last 10 data points?

**Comment by bskiba** [comment]
Thanks for raising, this looks useful. If anyone is willing to take this up, I'll be happy to review/discuss.

**Comment by yashbhutwala** [comment]
can we use the VPA checkpoint object for this and collect metrics for it in kube-state-metrics?

**Comment by yashbhutwala** [comment]
still relevant and important.

/remove-lifecycle stale

**Comment by ThaSami** [comment]
it would be great to see this as I am building a machine learning model on top of VPA...
