### ISSUE TITLE
`git restore` command only in git 2.23+

### ISSUE THREAD

**Issue by jaypipes** [kubernetes/autoscaler#2560]
The `git restore` command debuted in git version 2.23.0, which was released on Aug 16, 2019:

https://github.com/git/git/releases/tag/v2.23.0

When running the `cluster-autoscaler/hack/update-vendor.sh` script on machines without such a modern Git, such as the latest Ubuntu distribution 19.10 which has git 2.20.1 as of Nov 26, 2019, the script fails with:

```
++ git restore --staged .
git: 'restore' is not a git command. See 'git --help'.
```

Recommend replacing the use of `git restore` with `git reset <PATHS>` until git 2.23+ is more mainstream.

**Comment by losipiuk** [comment]
This is fixed. Right?

**Comment by jaypipes** [comment]
Yup, fixed.
