### ISSUE TITLE
[cluster-autoscaler] secondary expander option

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/autoscaler#2564]
User can specify node group expanders by setting `--expander`. By default. it's `random`. 
If we get multiple qualified node groups, CA will use `random` strategy to pick one of them. 

We get some feedbacks and sometimes users want to have more control on the selection. For example, users use `priority expander` first and then chose `least waste`. This is something CA doesn't support it now. 

I am trying to see if it makes sense to add secondary expander option or if there's some other solutions can address this requirement.

**Comment by Rajesh-Ayaldasani** [comment]
I am looking for a similar feature set. I am using a cluster autoscaler running with `priority expander` so it's first tries to launch pod on spot asg ( if not spot available ) it fallbacks to on-demnad and i also want the pods to schedule on the correct host type so that the nodes should not be left under-utilized in terms of cpu and memory. 
@Jeffwan Anything i can use with cluster autoscaler `priority expander` to maximize the node utilization too ?

**Comment by adrienjt** [comment]
The most-pods, least-waste and priority expanders already have a `fallbackStrategy expander.Strategy` field, but it is hardcoded to be the random expander. Why not configure expanders as a chain, e.g., `--expander=priority,least-waste`, and make the fallbackStrategy a constructor parameter (with random as the default value).

https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/expander/priority/priority.go#L59

https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/expander/waste/waste.go#L34

https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/expander/mostpods/mostpods.go#L31

The price expander is the exception. Is it deterministic when there's a tie (first max score), which might not be a good thing by the way. It could be slightly modified to allow a fallback in case of a tie.

https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/expander/price/price.go#L172
