### ISSUE TITLE
Create "concept" documentation to explain autoscaling

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/autoscaler#26]
We should have overall description of autoscaling and more detailed docs for HPA, VPA and cluster autoscaling.

**Comment by fgrzadkowski** [comment]
https://kubernetes.io/docs/concepts/

**Comment by fgrzadkowski** [comment]
We should also provide "task" for "How to autoscale my application" that would combine using both cluster autoscaler and HPA. Something like the blogpost we published some time ago.

**Comment by fgrzadkowski** [comment]
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by DirectXMan12** [comment]
> We should also provide "task" for "How to autoscale my application" that would combine using both cluster autoscaler and HPA

I'm not certain combining those two is the best idea -- cluster autoscaler is an admin tool, HPA is a user tool.  We don't want users thinking the need/should try the cluster autoscaler on clusters that they don't own.

**Comment by DirectXMan12** [comment]
I can totally see a VPA/HPA combo doc, though

**Comment by fgrzadkowski** [comment]
I'm not convinced. I think that even for large organizations, cluster
admins will have to understand how those different types of autoscaling are
working together and what are the options and how to completely solve the
problem of resource management. That way user will see that they don't need
to think about resources anymore.

I imagine this more as an example with link to more detailed pages about
HPA, VPA or Cluster Autoscaler.

--
Filip
