### ISSUE TITLE
CA / Azure - Failed to scale up - CPU Quota limit

### ISSUE THREAD

**Issue by StianOvrevage** [kubernetes/autoscaler#2607]
Cluster autoscaler installed on an `aks-engine` cluster fails to scale up because it tries to go immediately from 2 to 10 nodes resulting in a rejection:

`
E1203 10:35:27.111510       1 azure_scale_set.go:256] virtualMachineScaleSetsClient.CreateOrUpdate for scale set "k8s-workers-x-vmss" failed: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="The operation couldn't be completed as it results in exceeding quota limit of standardDSv3Family Cores. Maximum allowed: 1000, Current in use: 986, Additional requested: 72. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/....."
`

There is room for 1 additional node (Standard_D8s_v3, 8 vCPU) but not 8. I would expect CA to be able handle this with either gradual scaling, intelligently parsing the rejection and adjusting or some kind of staggered/slow-start type of scaling up.

This error also leads to overloading Azure APIs and being denied even requesting changes:

`
E1203 10:39:46.362032       1 azure_scale_set.go:256] virtualMachineScaleSetsClient.CreateOrUpdate for scale set "k8s-workers-x-vmss" failed: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{\"operationGroup\":\"CreateVMScaleSet30Min\",\"startTime\":\"2019-12-03T10:39:46.2787438+00:00\",\"endTime\":\"2019-12-03T10:54:46.2787438+00:00\",\"allowedRequestCount\":300,\"measuredRequestCount\":373}","target":"CreateVMScaleSet30Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}
`

**Comment by ircnelson** [comment]
@StianOvrevage I found this docs about quotas:
https://docs.microsoft.com/en-us/azure/azure-portal/supportability/resource-manager-core-quotas-request

https://docs.microsoft.com/en-us/azure/azure-portal/supportability/classic-deployment-model-quota-increase-requests

**Comment by StianOvrevage** [comment]
Thanks @ircnelson . We're aware that we can request higher quotas, but that has to go through corporate channels so is not done in a jiffy :)
