### ISSUE TITLE
Feature request: CA emitting proper Events on scale up/downs

### ISSUE THREAD

**Issue by reubenavery** [kubernetes/autoscaler#2619]
It would be very useful to hear from cluster-autoscaler when scaling events occur.  I am aware of these events being recorded within the cluster-autoscaler-status configmap but it would be much more useful (imho) to have also proper Events created and emitted so that these could be collected along with the rest of our clusters' Events (eg `kubectl get events -n kube-system`).  

We stream our cluster Events into a central dashboard.  We recently were experiencing issues with HPA scaling up replicasets but with pods not able to find tenancy.. It was tricky to tie things together with what cluster-autoscaler was doing (or in this case, not doing, as a result of a configuration issue).

**Comment by MaciekPytel** [comment]
Scale-ups and scale-downs are registered as Events attached to status configmap. They actually do show up if you run `kubectl get events -n kube-system`. Example output from my cluster:

```
> kubectl get events -n kube-system
LAST SEEN   TYPE     REASON             OBJECT                                MESSAGE
110s        Normal   ScaledUpGroup      configmap/cluster-autoscaler-status   Scale-up: setting group <redacted> size to 2
```

Closing as I believe this FR is already done. Please re-open if you think there is some more work here.
