### ISSUE TITLE
v1.15.1 Azure: Cluster Autoscaler gets stuck in an error loop after scale in, and can't make progress without being restarted

### ISSUE THREAD

**Issue by Starblade42** [kubernetes/autoscaler#2620]
# Cluster autoscaler stops making progress after certain scale in events. It ceases to do any work until the CA is restarted.

## Expected behavior:
After the scale in, the cluster autoscaler should resume normal operations of evaluating the cluster to see if it needs to be scaled in or out.

## Actual behavior:
The CA stops evaluating cluster status at all, and gets stuck looking at the size of a particular ASG (VMSS in this case in Azure) and is fixated on the fact that it's not the size that some part of the CA thinks it should be.

**The CA will not exit this error condition without being restarted.**

# Description:
We've run into a problem recently where our clusters stop scaling in/out based on demand.

- When we detect this issue, it's usually due to a huge pile-up of `pending` pods that are waiting for the Cluster Autoscaler (CA) to increase the cluster size nodes.
- Restarting the Cluster Autoscaler when its in this state result in nearly instant scale up and successful node provisioning, so it's not a cloud provider issue preventing progress
-  In the example I'm presenting here, the CA was stuck in this error loop for ~15 hours before operator intervention restarted the CA.
- After the CA was restarted, it that 29 nodes were created by the CA to meet the demand of the unscheduled pods.

The distinctive "error loop" log output looks like this, over and over until the leading CA po is restarted (including just the "message" for brevity):
```
"message":"I1108 02:43:28.931235       1 utils.go:538] Decreasing size of vmss-agent-worker0-11prodva7-ieoin, expected=18 current=13 delta=-5\n"

"message":"E1108 02:43:28.931267       1 static_autoscaler.go:288] Failed to fix node group sizes: failed to decrease vmss-agent-worker0-11prodva7-ieoin: attempt to delete existing nodes targetSize:18 delta:-5 existingNodes: 18\n"
```

# More information
## Logs leading up to this error state
- Here's a GIST with a CSV of the ~500 events exported from Splunk leading up to this repeating error state: https://gist.github.com/Starblade42/882661e8c326e9eefa6928603d51ea59

## Cluster Autoscaler Deployment YAML
- Here's a GIST with our deployment YAML: https://gist.github.com/Starblade42/f602d3157b5b4858a8b75d551ccbfb7d

The relevant code generating the error messages appears to be here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler.go#L497-L519

and 

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler.go#L291-L302

Please let me know if there's anymore information that I can provide to make this easier to track down.

**Comment by Starblade42** [comment]
Duplicate of #2538 and #2594 it appears. Cool. I should have checked the issues first!

Could be fixed by #2613

**Comment by nilo19** [comment]
Are you using AKS or manually-created k8s cluster through aks-engine? @Starblade42

**Comment by nilo19** [comment]
You mean you run into the trouble during `scale up`, doesn't it? So is the `scale down` free from problem?

**Comment by nilo19** [comment]
I can build up a private ca image with some extra logs for you to gain insight into the issue if it is convenient to you. @Starblade42
