### ISSUE TITLE
Add multiple clusters support to CA  

### ISSUE THREAD

**Issue by sshukun** [kubernetes/autoscaler#2624]
Some of our customers are running multiple clusters on bare metal. Each cluster has different purpose (e.g. one for production, one for test) with different configuration (k8s version, physical network, etc.). As in a bare metal environment, physical servers keep running at all time, scaling up a cluster when necessary cannot be easily done by adding a new node. Instead we need to first scale down another cluster temporarily, reconfigure the server and then join to the target cluster. 
Currently, all the operations are done manually and we want to automate them through CA, cluster API and metal3. With cluster API and metal3, it is possible to manage a bare metal cluster's life-cycle, but I have noticed that current CA does not support multiple clusters. Consider that we have other customers who also run bare metal clusters, such a multiple cluster auto-resizer can be very useful. So can we make the CA support multiple clusters and add other functions which enable the node steal stuff.

**Comment by MaciekPytel** [comment]
Currently CA treats scale-up and scale-down as independent problems. Not only that, it treats scale-down of each node as a separate problem.
What you're asking for makes sense as a use-case, but it seems like it would require solving a problem that is significantly harder than what CA currently does (and, most likely, rewriting a lot of current CA). So, unless someone shows a concrete, simple way to achieve this, I don't think it's likely to happen.

**Comment by MaciekPytel** [comment]
Closing this as non actionable, please reopen if you have any suggestions on how that could be implemented.
