### ISSUE TITLE
Updater evicts pods in a CronJob test is failing

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#2626]
Testgrid link: https://testgrid.k8s.io/sig-autoscaling-vpa#autoscaling-vpa-updater
Test fails since 12/05/2019 07:20 PST

Looks like https://github.com/kubernetes/autoscaler/pull/2537 introduced the problem.

**Comment by piotrnosek** [comment]
Solved by https://github.com/kubernetes/autoscaler/pull/2634.

**Comment by krzysied** [comment]
Thanks!
