### ISSUE TITLE
Failed to list *v1.CSINode

### ISSUE THREAD

**Issue by masterkain** [kubernetes/autoscaler#2628]
I deploy on AWS EKS, kubernetes 1.14.

I upgraded to image `k8s.gcr.io/cluster-autoscaler:v1.17.0` and updated my RBAC to avoid permission errors:

```
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
```

```
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resourceNames: ["cluster-autoscaler"]
    resources: ["leases"]
    verbs: ["get", "update"]
```

However I'm getting spammed by this message:

```
│ I1208 09:27:14.811469       1 reflector.go:188] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
│ E1208 09:27:14.812998       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource
```

**Comment by left4taco** [comment]
Same error here.

**Comment by zhuhesheng** [comment]
Same error here.

**Comment by MaciekPytel** [comment]
I've seen the same on GCE.

@losipiuk I think you recently looked into CSINodes? Can you take a look?

**Comment by losipiuk** [comment]
I am pretty sure that the reason you are seeing those is fact that k8s 1.14 has no `v1.storage.k8s.io.csinode` objects. AFAIK the API was promoted to `v1` from `v1beta1` in k8s 1.17

**Comment by losipiuk** [comment]
CA 1.17 is not supposed to be used on k8s 1.14

**Comment by michael-burt** [comment]
@losipiuk do you know what the latest CAS supported on EKS is? The latest EKS version is 1.14.

**Comment by hectorj2f** [comment]
@michael-burt I'd say https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-1.14.7/cluster-autoscaler

**Comment by michael-burt** [comment]
Thanks @hectorj2f 

I see on the CAS documentation for 1.17 that they list a bunch of notes related to AWS but I guess this is not for EKS.
