### ISSUE TITLE
Add support for reserved empty nodes

### ISSUE THREAD

**Issue by chiefzor** [kubernetes/autoscaler#2630]
Usually, it takes ~10 minutes for a node to be provisioned in the cloud provider, sometimes it's a crucial time for an immediate scaling issue.
Please add the feature to support reserved nodes for a peak scaling incident.

**Comment by TBBle** [comment]
@chiefzor Are you able to achieve this with the [overprovisioning instructions](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler)?

**Comment by chiefzor** [comment]
Hi @TBBle,
I will try it and I will close the ticket meanwhile.

Thx
