### ISSUE TITLE
VPA - admission e2e test race condition

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#2631]
Current implementation of vpa admission test has a problem with race condition.

The scenario is:
1. VPA object is created.
2. Deployment object is create.
3. VPA watch on deployments is lagging so it takes ~1s to observe new deployment
4. New pods are sent to admission webhook and due to deployment not being observed they don't get the recommendations.
5. Test expects resource recommendations and flakes.

There was [a fix](https://github.com/kubernetes/autoscaler/pull/2504) created by @jbartosik that separates deployment creation and scale-up. It solved half of the problem. However, creating deployment and getting created object from etcd can still be faster then observing deployment with a watch.

**Comment by bskiba** [comment]
@krzysied What is the current status of this issue? Is it resolved, or are we still missing pieces?

**Comment by krzysied** [comment]
I think we can close it.
Current status:
- Tests will not be flaky.
- Race condition still exists, although it doesn't affect the correctness in normal clusters.

**Comment by bskiba** [comment]
Thanks!
/close
