### ISSUE TITLE
Delete node after drain

### ISSUE THREAD

**Issue by sylr** [kubernetes/autoscaler#2640]
Unless I'm mistaken, after a drain the cluster autoscaler remove the nodes on the cloud provider before removing the "kubernetes nodes".

This flow provokes my monitoring to throw alerts because the ratio daemonset instances ready / daemonset instances desired goes below 100% for a certain amount of time.

So I'm wondering if the CA could delete the node from kubernetes once drained before removing the Azure instance.

**Comment by MaciekPytel** [comment]
CA doesn't remove Node objects at all. It doesn't create them or manage them in any way either. Node object are generally owned by NodeController and kubelet and those components are responsible for removing them once the VM disappears. Even if CA was to delete Node object I suspect it would be recreated anyway. 
So, unfortunately, this is WAI.
