### ISSUE TITLE
Toggle JSON formatting for logs

### ISSUE THREAD

**Issue by cabrinha** [kubernetes/autoscaler#2646]
It'd be great if we had a way to enable json logging format.

**Comment by morsok** [comment]
Hello, we would love to have that feature ! We are using Datadog and right now there is no way to differentiate as far as i'm aware between debug, warning error logs etc...

**Comment by cep21** [comment]
To give some context on this, structured logging is very popular and useful.  It allows users to group and search logs across services.  The most common structured logging format is currently JSON.  There are lots of resources that talk about the usefulness of structured logging, such as [this one](https://engineering.grab.com/structured-logging).  It's understandable by most third party SaaS platforms as well, such as datadog or [gcp](https://cloud.google.com/logging/docs/structured-logging)

**Comment by lgg42** [comment]
Oh yes please! we just found out that all of cluster-autoscaler logs are displayed in datadog as ERROR logs, whey they are in fact INFO. +1 to this feature.
Maybe adding an Env var to the deployment for switching the output into json format?

**Comment by morganchristiansson** [comment]
https://github.com/sirupsen/logrus has example of JSON logging in README

**Comment by dr460neye** [comment]
Is there any update about this?

**Comment by MaciekPytel** [comment]
I don't believe anyone is working on this. Cluster Autoscaler uses klog for logging and we've recently moved on to klog v2, which has support for structured logging. However, updating all logging in CA would be a large task and so far no one has stepped up to take it.

**Comment by cep21** [comment]
Hi, any update on why this was closed?

**Comment by cabrinha** [comment]
> Hi, any update on why this was closed?

I went ahead and opened this issue on Dec 14, 2019 -- I just went through and cleaned up my open issues.

Based on this comment: https://github.com/kubernetes/autoscaler/issues/2646#issuecomment-702014967 I don't think this will get picked up anytime soon.

**Comment by morganchristiansson** [comment]
It would be really nice to query logs for pods have blocked scaledown.

I found a blog post which details support for `--loging-format` support in k8s 1.19 https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/

And a guide to migrating https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

Quote
> The first step is to introduce structure to the high percentage of logs generated in Kubernetes by changing only a small number of logs API calls. Based on criteria described in the selecting most important logs section, the selected 22 log calls are estimated to impact 99.9% of log volume.

Having json logs with log level.. and scaledown loop logs with node and pod name as json fields would be super useful.

**Comment by manku211** [comment]
is there way to use --logging-format flag in pod of cluster autoscaler , I want see as info logs also in my datadog
