### ISSUE TITLE
Take terminating pods into account before scaling up

### ISSUE THREAD

**Issue by leeavital** [kubernetes/autoscaler#2648]
We are running into an interesting issue with the autoscaler where we have a deployment being binpacked onto a nodegroup. It has the following settings:

```
maxSurge: 1
maxUnavailable: 50%
```

When we create a new rollout for the deployment, this happens:

- 50% of the pods become unavaible
- 50% + 1 new pods get created
- we now have 150% of the original number of pods created (50% each are in pending/running/terminated + 1 more in pending)
- the autoscaler sees a bunch of unschedulable pods, and decides to scale up the nodegroup
- at the end of the deploy we have extra un-needed which slowly get scaled down

Ideally the autoscaler could see that the nodegroup that it's scaling up is about to free up some space by terminating some pods and would wait for pods to schedule on existing nodes.

Ideally we would like to avoid using the global autoscaler flag `--new-pod-scale-up-delay` because it slow down the scaling up of other workloads

**Comment by MaciekPytel** [comment]
It would make sense to filter out pods that are already in terminating state (if CA doesn't already do that, which I suspect it is). 

I'd like to avoid making core CA understand deployment's rolling update logic. To be fully correct it would need to predict not only how many pods will be removed by deployment, but also exactly which pods will be deleted. That seems both complex and fragile.
A much better way to implement this would be a custom PodListProcessor that would keep track of how many pods will be deleted and filter out a corresponding number of pending pods. It's a heuristic, but I suspect it should work pretty fine in practice and it shouldn't be terribly difficult to implement. 

If anyone feels like implementing this I'm happy to help / review.
One note: as we migrate from scheduler predicates to Filter functions (and more generally scheduling framework) in 1.18 PodListProcessor interface will need to change a bit, so it may be better to wait until the interface stabilizes before implementing that.
