### ISSUE TITLE
Ignore pods from specific namespace?

### ISSUE THREAD

**Issue by ilyache** [kubernetes/autoscaler#2652]
I'm wondering if there's an option to mark a certain namespace as one that cluster-autoscaler should ignore pods from when trying to reschedule pods. While I can mark the pods as not-safe-to-evict, or set a PDB per each one, I'd like to make sure there's no way to just tag an entire namespace as not safe to evict (similar to how `kube-system` is, by default).

**Comment by skbly7** [comment]
@ilyache Did you find solution for the same, given this is now closed?

**Comment by ilyache** [comment]
@skbly7 - I went with a PDB for the relevant deployments.
