### ISSUE TITLE
Scale-down: Node is terminated before pods are in "Running" state in the other node

### ISSUE THREAD

**Issue by oak13** [kubernetes/autoscaler#2666]
I am working on Kubernetes Cluster (v.1.14.8). I'm using Horizontal Pod Autoscaling and Cluster Autoscaling.

I'm experiencing an issue during scale-down, and I'm not sure whether this is expected behaviour or a bug:

- The cluster has two node pools, the node pool that the application resides, scales from 1 node to 3 nodes (no issues here). (let's call them node1,node2,node3)
- When the load is reduced, some of the extra pods are terminated, and one of the nodes (node3) is not running any pods anymore. 
- When it is time to scale down the cluster, all pods on the node2 are issued a terminate command at the same time a create command on the node3. 
- Since termination happens quicker than container creation, there is impact to the service.
- My expectation was the empty node (node3) would be terminated, but if that would not be the case, then the pods should be created first on node3, and then the matching pod to be terminated on node2, so emptying node2 gradually and terminating it.
- This did not happen, termination was initiated for all pods on node2 before there were matching pairs on node3.

My questions are: 

1. Should the cluster terminate the empty node (node3) instead of moving all pods from a utilised node (node2) on to the empty node (node3)

2. Should the cluster check the newly created pods on the other to be in Running state before draining a node for cluster scale down?

Thank you

**Comment by aleksandra-malinowska** [comment]
> Should the cluster terminate the empty node (node3) instead of moving all pods from a utilised node (node2) on to the empty node (node3)

If both nodes have been unused for the same time, then empty node should be removed first. However, if node2 became underutilized before node3, then it'd be drained and deleted first. 

> Should the cluster check the newly created pods on the other to be in Running state before draining a node for cluster scale down?

Cluster Autoscaler uses eviction API to drain nodes. More precisely:
1. Node is tainted with effect NoSchedule.
2. Eviction is created for each pod on drained node. Kubernetes controller manager performs eviction steps: checks if eviction is within disruption budget, terminates the pod, creates a new one if needed.
3. Cluster Autoscaler waits for the pod to be gone from node before deleting the node.

You can limit evictions by creating a PodDisruptionBudget. Then, even if though evictions are issued at once, pods will be terminated only within those limits. Note that if you don't allow for at least 1 pod to be disrupted at a time, drain will fail.
