### ISSUE TITLE
IBM cloud / Softlayer support

### ISSUE THREAD

**Issue by posix4e** [kubernetes/autoscaler#2670]
Curious what it would take to get IBM/Softlayer support going.

**Comment by MaciekPytel** [comment]
To add a new provider you'd need to implement interfaces in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go. Unfortunately we still don't have any documentation on how to do that, but at least there are plenty of existing providers to use as example.
