### ISSUE TITLE
Feature: Option to expire old nodes after X days and deploy fresh nodes

### ISSUE THREAD

**Issue by mcandre** [kubernetes/autoscaler#2672]

**Comment by MaciekPytel** [comment]
CA doesn't have any mechanism to replace an existing node with a different node. Scale-up and scale-down are two completely separate pieces of logic that work mostly independently of each other. We'd love to have moving for things like reducing resource fragmentation, but it's much more complex than current CA and unlikely to happen anytime soon.

So, I don't think we're in position to satisfy this FR. A best-effort option would be a function that prioritizes older nodes in scale-down (opt-in, it's probably not a good choice for most people).
I don't think we'll manage to work on it anytime soon, but if anyone wants to give it a shot feel free to ping me.
