### ISSUE TITLE
'No candidates for scale down' fills the logs

### ISSUE THREAD

**Issue by AndreaGiardini** [kubernetes/autoscaler#269]
The message:

```
scale_down.go:246] No candidates for scale down
```

Is repeated several time in our logs and gives no valuable information. Is it possible to exclude it from logging? If not, should we introduce a verbosity level for it?

**Comment by MaciekPytel** [comment]
This particular message is only logged once per loop (so assuming default configuration once / 10s), so it's not very spammy. And it means that scale-down logic decided there are no nodes that can be removed and it returns immediately, without executing a few hundred LOC worth of logic, which is a reasonably useful information when debugging. We can add a V() to this log, but it would end up being pretty high priority anyway (probably V(1) or V(2)).

I think revisiting some log priorities is definitely on our radar, though at least initially we'll focus on logs inside loops, etc (for example `cluster.go:224] Looking for place for <pod_name>` can account for 10k+ log lines / loop in very large clusters).
