### ISSUE TITLE
Autoscaler Healthy Pod Transfer

### ISSUE THREAD

**Issue by gusta095** [kubernetes/autoscaler#2691]
provider: AWS
kubectl: v1.15.0
kops: v1.12.2

we are having the following problem: autoscaler is relocating healthy pods for no apparent reason, it's a very punctual situation, it erases the source pod without ensuring it is healthy in its destination, this occurs when he does the scalerdown.

example log:
"
I1109 00:02:28.138372    1 cluster.go:225] Pod example/api-5555f58707-6g8kl can be moved to ip-10-5-3-74.sa-east-1.compute.internal
I1109 00:02:28.138466    1 scale_down.go:707] Scale-down: removing node ip-10-25-30-129.sa-east-1.compute.internal, utilization: {0.0775 0.08084144597105607 0.08084144597105607}, pods to reschedule: example/api-5555f58707-6g8kl
I1109 00:02:28.141390    1 factory.go:33] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"f668bc21-037f-11ea-9ecf-02a6be9438aa", APIVersion:"v1", ResourceVersion:"51923222", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' Scale-down: removing node ip-10-5-3-129.sa-east-1.compute.internal, utilization: {0.0775 0.08084144597105607 0.08084144597105607}, pods to reschedule: example/api-5555f58707-6g8kl
I1109 00:02:28.405908    1 factory.go:33] Event(v1.ObjectReference{Kind:"Pod", Namespace:"example", Name:"api-5555f58707-6g8kl", UID:"90b28233-0283-11ea-9ecf-02a6be9438aa", APIVersion:"v1", ResourceVersion:"51902215", FieldPath:""}): type: 'Normal' reason: 'ScaleDown' deleting pod for node scale down
"

**Comment by MaciekPytel** [comment]
CA doesn't restart a pod (or validate it was successfully restarted) at scale-down. All it does is pick a node for scale-down, evict pods from that node and remove the node. It assumes the relevant controller (ex. ReplicaSet) will take care of restarting the pod. 

So every scale-down temporarily reduces capacity of any deployment (the pods are only recreated after they're deleted). You can control how many replicas CA can take down at any given time by using a PodDisruptionBudget. Non-disruptive scale-down of single pod deployments is not supported.

**Comment by MaciekPytel** [comment]
Closing the issue as it seems this is WAI. Please re-open if needed.
