### ISSUE TITLE
Cluster Autoscaler occasionally requires restarts to scale up ASG

### ISSUE THREAD

**Issue by ddseapy** [kubernetes/autoscaler#2721]
We recently migrated from 1.13.1 to 1.16.3, and have noticed every few days one of our AWS ASGs stop being used.

They contain nvidia gpus, and the logs say "Pod <pod-name> can't be scheduled on <asg-name>, predicate failed: PodFitsResources predicate mismatch, reason: Insufficient nvidia.com/gpu

Deleting the cluster autoscaler pod fixes the issue for a few days, and then it happens again.

Is something cached in the pod that might not be refreshing?

**Comment by MaciekPytel** [comment]
cc: @Jeffwan 

This seems specific to AWS provider. Some combination of GPU label workaround not working correctly with caching instance template?

**Comment by LobsterMan** [comment]
@ddseapy  Did you find a solution to this?

**Comment by ddseapy** [comment]
Without doing anything on our side, this hasn't occurred in the last couple months.  I'll close as it's not happening anymore.  Will re-open if happens again.
