### ISSUE TITLE
Kubernetes VPA failed to fetch list of containers. Reason: context deadline exceeded. Last server error: <nil>

### ISSUE THREAD

**Issue by timusri** [kubernetes/autoscaler#2725]
Hi I am trying to deploy a VPA object for one of my deployment but when describing the conditions are failing with error

Status:
 Conditions:
   Last Transition Time:  2020-01-08T13:03:55Z
   Message:               Fetching history failed: Failed to fetch list of containers. Reason: context deadline exceeded. Last server error: <nil>
   Reason:                2020-01-08T13:03:55Z
   Status:                False
   Type:                  FetchingHistory
   Last Transition Time:  2020-01-08T13:03:55Z
   Status:                False
   Type:                  LowConfidence
   Last Transition Time:  2020-01-08T13:03:55Z
   Message:               No pods match this VPA object
   Reason:                NoPodsMatched
   Status:                True
   Type:                  NoPodsMatched
   Last Transition Time:  2020-01-08T13:03:55Z
   Status:                True
   Type:                  RecommendationProvided

Here is my VPA file:
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: xtenter-vpa
  namespace: mynamespace
spec:
  targetRef:
    apiVersion: "extensions/v1beta1"
    kind:       Deployment
    name:       mydeploy
  updatePolicy:
    updateMode: "Auto"

One more scenario I found is that when I run the VPA with updatePolicy mode as "Off" I got a different error in the status of VPA.

Conditions:
    Last Transition Time:  2020-01-10T06:53:55Z
    Message:               Fetching history failed: Failed to fetch list of containers. Reason: Failed to listTimeSerises with retries. Last server error: rpc error: code = InvalidArgument desc = Name must begin with '{resource_container_type}/{resource_container_id}', got: projects/
    Reason:                2020-01-10T06:53:55Z
    Status:                False
    Type:                  FetchingHistory
    Last Transition Time:  2020-01-10T06:44:55Z
    Status:                False
    Type:                  LowConfidence
    Last Transition Time:  2020-01-10T06:44:55Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2020-01-10T06:44:55Z
    Status:                True
    Type:                    ##RecommendationProvided

Cluster details : version: 1.13.11-gke.14 
Stackdriver Kubernetes Engine Monitoring: Disabled 
Legacy Stackdriver Logging: Enabled

Could you please help me understand what is the root cause here?

**Comment by bskiba** [comment]
The history fetching tries to fetch data from Stackdriver. If you have it disabled, will probably not work. However, it is not strictly necessary for the VPA to work, VPA is able of fetching current metrics from Metrics Server. Do you have a recommendation provided for this VPA object?

**Comment by timusri** [comment]
@bskiba  Hey Sorry for the delayed response.
Yes I am getting the recommendation for the first time. Here the full description I got

###
Name:         test-vpa
Namespace:    mynamespace
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"test-vpa","namespace":"enig...
API Version:  autoscaling.k8s.io/v1beta2
Kind:         VerticalPodAutoscaler
Metadata:
  Creation Timestamp:  2020-01-10T07:31:59Z
  Generation:          112
  Resource Version:    298025636
  Self Link:           /apis/autoscaling.k8s.io/v1beta2/namespaces/mynamespace/verticalpodautoscalers/test-vpa
  UID:                 49629849-337b-11ea-9603-42010a800095
Spec:
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         test-deploy
  Update Policy:
    Update Mode:  Off
Status:
  Conditions:
    Last Transition Time:  2020-01-10T07:42:55Z
    Message:               Fetching history failed: Failed to fetch list of containers. Reason: Failed to listTimeSerises with retries. Last server error: rpc error: code = InvalidArgument desc = Name must begin with '{resource_container_type}/{resource_container_id}', got: projects/
    Reason:                2020-01-10T07:42:55Z
    Status:                False
    Type:                  FetchingHistory
    Last Transition Time:  2020-01-10T07:32:55Z
    Status:                False
    Type:                  LowConfidence
    Last Transition Time:  2020-01-10T07:32:55Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2020-01-10T07:32:55Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  test-deploy
      Lower Bound:
        Cpu:     62m
        Memory:  262144k
      Target:
        Cpu:     93m
        Memory:  262144k
      Uncapped Target:
        Cpu:     93m
        Memory:  262144k
      Upper Bound:
        Cpu:     104m
        Memory:  262144k
Events:          <none>
###

**Comment by bskiba** [comment]
Thank you for the details. 
The point I would like to stress the most is that the recommendation you get is still valid and you don't have to worry about it's quality, VPA observes what is happening in the cluster and will recommend appropriate values for you. 
However, I am looking into reproducing the error that you get, this does seem like an issue with fetching history.

**Comment by bskiba** [comment]
I can reproduce with a 1.13 cluster. We'll work on fixing this.
