### ISSUE TITLE
VPA - Implementing automatic detection of injected sidecars

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#2726]
There will be new feature added to VPA dedicated to detecting injected sidecars and omitting them during making pod eviction decision.
This feature assumes that containers handled by Admission Controller will be listed in additional pod annotation. Containers not listed in this annotation will not be taken into account by the Updater.

**Comment by krzysied** [comment]
Implementation plan:
- [ ] Adding annotation module.
- [ ] Adding annotation creation to Admission Controller.
- [ ] Adding omitting not listed containers by Updater.

**Comment by bskiba** [comment]
Please add an e2e test as a way of verifying the feature works.

**Comment by krzysied** [comment]
I agree that an e2e test is something nice to have.
Assuming that we need a custom mutating webhook to test this change, I need to do some research about whether to implement a testing webbook or to use an available opensource one...
I will update the issue when I come up with the solution.

**Comment by krzysied** [comment]
@aleksandra-malinowska suggest brilliant idea that webhooks should already be tested by k8s e2e tests.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/webhook.go
It looks like there is a pod mutation webhook test. I will try to re-use some of its components/code.

**Comment by krzysied** [comment]
The Agnhost webhook (used by k8s e2e tests) adds initContainer instead of standard container. -_-'
I will try add sidecar injection functionality to Agnhost. https://github.com/kubernetes/kubernetes/issues/87383

**Comment by krzysied** [comment]
The e2e test pr was merged. I will wait for two green runs of https://testgrid.k8s.io/sig-autoscaling-vpa#autoscaling-vpa-actuation and then I will close the issue.

**Comment by krzysied** [comment]
The test is passing. Nothing more to do here.
I'm closing the issue.
