### ISSUE TITLE
VPA - Admission Controller status

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#2738]
It can potentially happen that Admission Controller is down. When this happens, we don't want to evict pods (recommendation will not be applied).
Admission Controller should have a status object. This status object should be observed by Updater. If status object has not been updated for a long time, Updater should stop evictions.

**Comment by krzysied** [comment]
Implementation plan:
- [ ] Generic status util. (#2742)
- [ ] Status updating by Admission Controller
- [ ] Status checking by Updater

**Comment by krzysied** [comment]
Tests seem to work https://testgrid.k8s.io/sig-autoscaling-vpa#autoscaling-vpa-updater.
Closing the issue.

**Comment by hjkatz** [comment]
We were also affected by something similar to #2633 and #2715. Our solution was to restart the admission controller pod and then the recommendation targets seemed to be applied correctly. When will these merged changes be cut into a new release?

**Comment by krzysied** [comment]
@bskiba Do we have any estimation for a new release?
