### ISSUE TITLE
Cluster Autoscaler releases 1.17.1, 1.16.4 and 1.15.5

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/autoscaler#2755]
Scheduled to be build on Thu, 2020-01-23.

If you have any cherry-pick PRs which you believe should be included in those releases, please leave a comment here.

**Comment by marwanad** [comment]
Is it possible to get a 1.14.8 release as well?

**Comment by marwanad** [comment]
@aleksandra-malinowska I am aware that there are no more K8s 1.14 releases but there are some fixes in Azure that would be good to have in a 1.14.8 release.

**Comment by marwanad** [comment]
@aleksandra-malinowska @losipiuk ping on the above

**Comment by Starblade42** [comment]
We're now on Kubernetes 1.16, and we've been waiting for a release that has this fix in it:
https://github.com/kubernetes/autoscaler/pull/2613 

We'll probably be on 1.17 within a month or so, but I'd guess the fix would be there too.

**Comment by Starblade42** [comment]
@aleksandra-malinowska Thanks so much for this. Do you think a release forthcoming, or should I look at doing a build on our own to limp along?

**Comment by Jeffwan** [comment]
newer versions have been releases. Check detail here. https://github.com/kubernetes/autoscaler/issues/2988 This can be closed
