### ISSUE TITLE
How do i pass the Digitalocean Access Token to Cluster-Autoscaler?

### ISSUE THREAD

**Issue by kycfeel** [kubernetes/autoscaler#2757]
Hi there.

I'm struggling to setup a `cluster-autoscaler` for my Digitalocean managed Kubernetes cluster. My `cluster-autoscaler` is complaining that I didn't pass the DO access token, but I don't see any guide or option to pass the token to it. 

`digitalocean_cloud_provider.go:181] Failed to create DigitalOcean manager: access token is not provided`

I believe that the general documents should be improved for running CA on DOKS. But for now, does anyone know how to pass the token to it?

Thanks.

**Comment by Sh4d1** [comment]
ping @timoreimann :)

**Comment by timoreimann** [comment]
(thanks for the ping, @Sh4d1) 

👋 @kycfeel 

Cluster autoscaler comes pre-installed on DigitalOcean's managed Kubernetes offering, so you normally shouldn't need to pass the token or even install it yourself. (One potential exception being that you want to tune it beyond what DOKS exposes, though I personally haven't heard of such a case yet; let me know though if that's what you're looking for.) We also [provide documentation](https://www.digitalocean.com/docs/kubernetes/how-to/autoscale/) on how to get started with autoscaler on DOKS.

Let me know if you have more questions.
