### ISSUE TITLE
Deprecate AlgorithmSource from scheduler ComponentConfig

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/autoscaler#2769]
AlgorithmSource was meant to be a bridge to allow specifying a Policy file in ComponentConfig. Now that all Policy configuration is available through ComponentConfig directly, AlgorithmSource is not needed. This is the first step towards deprecating scheduler Policy file.

/assign @alculquicondor 
/cc @ravisantoshgudimetla @Huang-Wei @damemi

**Comment by alculquicondor** [comment]
If agreed, we can do this as part of https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20200114-multi-scheduling-profiles.md

#85737

**Comment by MaciekPytel** [comment]
cc: @losipiuk

**Comment by ahg-g** [comment]
oh, sorry, that meant to be in the k/k repo :)
