### ISSUE TITLE
Unclear documentation on down scaling a node group to 0

### ISSUE THREAD

**Issue by fardin01** [kubernetes/autoscaler#2775]
In AWS, I have 2 node groups/ASGs per Availability Zone, and with min number of instances set to 1, it amounts to 6 worker nodes at minimum at all times. During nights/weekends, the cluster can get by with 2 nodes in terms of resources. So I'm trying to have the Autoscaler downscale some of the node groups to 0, but I'm getting confusing information from the documentation.

Under [Auto-Discovery Setup](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup) section, it's written:
`... cluster-autoscaler will respect the current min and max values of the ASG being targeted, and it will adjust only the "desired" value.`

Then immediately after it, there is a section called [Scaling a node group to 0](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0) 

My questions are as follows:

1. Does the ASG min instance have to be 0 for Autoscaler to scale down a node group to 0? Trial and error suggests that it works, but I'm not quite sure if it's intended this way.

2. The documentation says `If you are using nodeSelector you need to tag the ASG ...`. What if my pods are not using nodeSelector? Can Autoscaler still downscale a node group to 0? 

I'll make a PR to improve the documentation once this is clear to me.

Thanks.

**Comment by fardin01** [comment]
@sethpollack Could you please take a look once you get a chance?

**Comment by sethpollack** [comment]
@fardin01 

1. the asg needs the min to be 0.
2.  normally the autoscaler would pull info like `nodeSelector` labels from the live instances for scale up calculations, in the case of scale to 0, it may not have nodes to get the info from, therefore you need to add that info as tags.

**Comment by paranoidsp** [comment]
@sethpollack I'd like to have some more clarity on this: 
* If the asg is at 0, and a pod has a nodeSelector that matches the asg (according to the tags on the asg), will the cluster autoscaler scale up a node and add labels and taints?

**Comment by sethpollack** [comment]
Adding the labels and taints is not done by the autoscaler.  

But it will not scale up without the `k8s.io/cluster-autoscaler/node-template/label` and `k8s.io/cluster-autoscaler/node-template/taint/` tags because it will not be aware that these asgs have those labels/taints.

**Comment by paranoidsp** [comment]
Thanks! This is clear now. To clarify it for others reading this:
Adding the labels and taints is the responsibility of the node kubelet bootstrapper, which is part of how the underlying cloud service scales instances.
For anyone using EKS managed nodegroups - this is not supported yet, you'll have to manually edit the Launch templates associated with your AutoScaling Group and add the register-with-taint or label argument to the bootstrap script under userdata.

**Comment by Jeffwan** [comment]
@paranoidsp Yes, user need to manage ASG tags to make it.  Do you have any suggestion on better support from EKS managed node groups?
