### ISSUE TITLE
Autodiscovery chooses all clusters if no match for multiple tags

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes/autoscaler#278]
Yesterday, we wanted to turn off the autoscaling from ASGs in one of our clusters. We currently use two tags for Autodiscovery, `cluster-autoscaler/enabled` and `cluster/<CLUSTER_NAME>`.

To disable the autoscaling, we changed the tag `cluster-autoscaler/enabled` to `cluster-autoscaler/disabled` (Helps us know what's going on). Then CA regenerates it's config as it has detected changes, as it should.

Once we had changed this on all ASGs in the cluster, we noticed a bunch of nodes got turned off in other clusters. Inspecting the logs, the CA instance on this cluster now had awareness of all of the ASGs in our environment.

This morning I have been playing around and believe there is a problem with the code here https://github.com/kubernetes/autoscaler/blob/927021dbfad86c8833f3ffd03b9f2badf0077e9c/cluster-autoscaler/cloudprovider/aws/auto_scaling.go#L164-L174

If no ASG has both tags, then `asgNames` is empty when we call `m.getAutoscalingGroupsByNames(asgNames)`

As demonstrated by these log lines I collected earlier:
```
I0830 08:26:56.511613       1 auto_scaling.go:96] Starting getAutoscalingGroupsByTag with keys=[cluster-autoscaler/enabled cluster/<CLUSTER_NAME>]
I0830 08:26:56.765726       1 auto_scaling.go:58] Starting getAutoscalingGroupsByNames with names=[]
```

In the case this list is empty, `nameRefs` on line 83 is also empty and so CA then calls `DescribeAutoScalingGroups` with an empty filter. This returns all ASGs and thus causes the problem I've described above.
https://github.com/kubernetes/autoscaler/blob/927021dbfad86c8833f3ffd03b9f2badf0077e9c/cluster-autoscaler/cloudprovider/aws/auto_scaling.go#L82-L86

I would like to suggest that we add a check to `getAutoscalingGroupsByNames` that verifies that the list it is passed is non-empty

**Comment by JoelSpeed** [comment]
I'm working on a fix for this today and will open a PR once I am happy that it solves the issue

**Comment by MaciekPytel** [comment]
cc: @mumoshu

**Comment by mumoshu** [comment]
@JoelSpeed You're a genius! I really appreciate your efforts.

I have received an issue in kube-aws+cluster-autoscaler setup from 2 individuals as in https://github.com/kubernetes-incubator/kube-aws/issues/800, which definitely seems to be explained by this.

I fully agree with your analysis and the proposed fix. Please go ahead :+1:
