### ISSUE TITLE
CA adds toBeDeletedTaint before checking AWS ASG settings

### ISSUE THREAD

**Issue by stk0vrfl0w** [kubernetes/autoscaler#2781]
In some clusters, we're noticing that CA is tainting nodes without properly taking into consideration the ASG's minSize and the current desiredSize.  Since the CI/CD systems deploy regularly to these clusters, what is observed is a mass exodus of pods from the chosen node(s) ~ 10 minutes after deployment.

From the logs, it appears that CA reads the ASGs settings when it first starts up and caches those values for determining taints for the lifetime of the pod.  If the ASG settings are later adjusted, CA only utilizes the new values immediately prior to terminating the node flagging a ValidationError.  However, this condition should have been determined prior to tainting.

For reference:
AWS EKS version - 1.14
CA image - k8s.gcr.io/cluster-autoscaler:v1.13.1

Log snippet:
```
I0128 21:34:32.796974       1 delete.go:64] Successfully added toBeDeletedTaint on node ip-10-1-227-215.us-west-2.compute.internal
I0128 21:34:42.799880       1 static_autoscaler.go:128] Starting main loop
I0128 21:34:42.799949       1 auto_scaling_groups.go:320] Regenerating instance to ASG map for ASGs: [eks-dev-02-uw-2]
I0128 21:34:42.880714       1 auto_scaling_groups.go:102] Updating ASG eks-dev-02-uw-2
I0128 21:34:42.880743       1 aws_manager.go:152] Refreshed ASG list, next refresh after 2020-01-28 21:34:52.880741008 +0000 UTC m=+2924706.358748567
I0128 21:34:42.880903       1 utils.go:526] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0128 21:34:42.880918       1 static_autoscaler.go:261] Filtering out schedulables
I0128 21:34:42.881305       1 static_autoscaler.go:271] No schedulable pods
I0128 21:34:42.881321       1 static_autoscaler.go:279] No unschedulable pods
I0128 21:34:42.881334       1 static_autoscaler.go:333] Calculating unneeded nodes
I0128 21:34:42.881578       1 scale_down.go:376] Scale-down calculation: ignoring 4 nodes unremovable in the last 5m0s
I0128 21:34:42.881609       1 scale_down.go:407] Node ip-10-1-207-27.us-west-2.compute.internal - utilization 0.982226
I0128 21:34:42.881619       1 scale_down.go:411] Node ip-10-1-207-27.us-west-2.compute.internal is not suitable for removal - utilization too big (0.982226)
I0128 21:34:42.881626       1 scale_down.go:387] Skipping ip-10-1-227-215.us-west-2.compute.internal from delete considerations - the node is currently being deleted
I0128 21:34:42.881896       1 static_autoscaler.go:360] Scale down status: unneededOnly=true lastScaleUpTime=2020-01-15 07:09:32.184066685 +0000 UTC m=+1749585.662074267 lastScaleDownDeleteTime=2020-01-08 08:19:06.03745375 +0000 UTC m=+1148959.515461355 lastScaleDownFailTime=2020-01-28 21:18:30.158011888 +0000 UTC m=+2923723.636019518 scaleDownForbidden=false isDeleteInProgress=true
I0128 21:34:43.206233       1 scale_down.go:1005] All pods removed from ip-10-1-227-215.us-west-2.compute.internal
I0128 21:34:43.356746       1 delete.go:120] Releasing taint {Key:ToBeDeletedByClusterAutoscaler Value:1580247272 Effect:NoSchedule TimeAdded:<nil>} on node ip-10-1-227-215.us-west-2.compute.internal
I0128 21:34:43.364991       1 delete.go:139] Successfully released toBeDeletedTaint on node ip-10-1-227-215.us-west-2.compute.internal
E0128 21:34:43.365038       1 scale_down.go:727] Failed to delete ip-10-1-227-215.us-west-2.compute.internal: failed to delete ip-10-1-227-215.us-west-2.compute.internal: ValidationError: Currently, desiredSize equals minSize (6). Terminating instance without replacement will violate group's min size constraint. Either set shouldDecrementDesiredCapacity flag to false or lower group's min size.
I0128 21:34:43.365457       1 factory.go:33] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-1-227-215.us-west-2.compute.internal", UID:"fd0e74ea-37e2-11ea-b58d-0657c6362996", APIVersion:"v1", ResourceVersion:"75610358", FieldPath:""}): type: 'Warning' reason: 'ScaleDownFailed' failed to delete the node
I0128 21:34:52.892357       1 static_autoscaler.go:128] Starting main loop
```

**Comment by sodul** [comment]
This issue is causing outages for us, any idea on workaround ?

**Comment by otterley** [comment]
Hi @stk0vrfl0w and @sodul ! Can you please provide some steps to reproduce the problem?

**Comment by stk0vrfl0w** [comment]
Hi @otterley.  I don't have a test case that can consistently reproduce this issue.  That said, I can walk you through the steps the Ops team more recently followed for an EKS upgrade & deployment; a little after which we'd experienced the bug.

- Update the EKS control plane from the web console
- Upgrade all core components  as necessary (i.e. coredns, CNI & kube-proxy)
- Change the ASG's associated Launch Config with an Amazon Linux AMI to match the cluster version
- Disable ClusterAutoscaler by setting the replica count to 0
- Increase the ASG's desired size to roll in new nodes
- Cordon old nodes
- Deploy our app to the cluster
- Re-enable ClusterAutoscaler by setting the replica count to 1

Given the ASG's min size was never touched, this invalidates my original hypothesis that tweaking the ASGs values were a possible trigger.

**Comment by gyuho** [comment]
> If the ASG settings are later adjusted

Can you share how ASG settings were adjusted?

**Comment by stk0vrfl0w** [comment]
Sure @gyuho.  Per the upgrade & deployment mentioned above, the team used the aws command line:

```
aws autoscaling update-auto-scaling-group \
    --auto-scaling-group-name <asg_name> \
    --desired-capacity <new_value>
```

**Comment by Jeffwan** [comment]
@stk0vrfl0w 

> Cordon old nodes

Do you cordon node by your self?  Basically, if you want CA to manage lifecycle, any manual settings may make CA come into an undesired state.  Like manual cordon/drain the node, adjust size of ASG. This results in a different state compares to the CA cache and CA need to wait for a period to refresh those changes. Decision before that may be inaccurate. 


Could you share use case why you need to change min/max of ASG using AWS command?  and why do you cordon the code? 

I can help check decision part and make sure there's no bug in ASG implementation

**Comment by stk0vrfl0w** [comment]
Hi @Jeffwan , thanks for looking into this!  As to your questions:

> @stk0vrfl0w
> 
> > Cordon old nodes
> 
> Do you cordon node by your self? Basically, if you want CA to manage lifecycle, any manual settings may make CA come into an undesired state. Like manual adjust size of ASG. This results in a different state compares to the CA cache and CA need to wait for a period to refresh those changes. Decision before that may be inaccurate.

On occasion, nodes are cordoned for various reasons (node flapping between Ready/NotReady state, preparation of upgrade, etc.).  That said, I'm curious to understand how that would affect the EKS upgrade & deployment scenario listed above -- CA was disabled/terminated by setting its replica count to 0 and the `cluster-autoscaler-status` ConfigMap is usually re-written upon startup.  Do caches persist across pod instances in other locations?

> 
> Could you share use case why you need to change min/max of ASG using AWS command?
> 

Sure.

The most common case of us raising the max ASG value is for our CI/CD clusters.  Over time, the number of services, developers and PRs have naturally increased and so has our need for more systems to accommodate the load.

As to raising the min ASG value, that's happened in APP clusters where the capacity was on the edge of being handled by X to X+1 nodes.  Today, we use HPA to scale service replicas based on memory usage.  When the ASG min value was too low and HPA scaled up, what would occasionally happen is:

* CA increase the ASG's desired count
* Pending pods get scheduled on to the new node
* CPU utilization on new node was lower than CA threshold
* Service process load decreases
* Memory pressure decreases and HPA scales down pods randomly (https://github.com/kubernetes/kubernetes/issues/4301), sometimes all the oldest replicas
* CA drains & terminates newest node due to lack of utilization

This lead to scenarios such as: pod_A on old node terminated while processing request X => pod_B on new node terminated while processing request X => pod_C on old node process request X.  Given each pod/service can handle many concurrent requests, we'd see a significant spike in retries.  We choose to increase the min ASG size vs changing the utilization threshold to work around this scenario.

Finally, as to changing the desired value manually, that's usually done as part of a cluster upgrade -- the process is already detailed above.

> Please also recreate and give steps to reproduce. If you pod has other labels, tolerations or nodes has any taints. please let us know

Our setup is fairly vanilla -- no node taints or tolerations for any of the clusters.

Currently, I do not have a guaranteed test case to reproduce the issue despite it occurring during various scenarios.  That said, I do have logs (attached) over several hours where no ASG values were modified but CA keep trying to terminate a particular node.
[ca-dev-02-uw-2.log.gz](https://github.com/kubernetes/autoscaler/files/4322301/ca-dev-02-uw-2.log.gz)


> 
> I can help check decision part and make sure there's no bug in ASG implementation
