### ISSUE TITLE
Cluster failed to scale-up after adding number of pods

### ISSUE THREAD

**Issue by amitsehgal** [kubernetes/autoscaler#2783]
Error:
I0129 18:57:28.535326       1 reflector.go:370] k8s.io/client-go/informers/factory.go:132: Watch close - *v1.Service total 0 items received
I0129 18:57:35.157353       1 reflector.go:370] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:319: Watch close - *v1.DaemonSet total 0 items received
I0129 18:57:37.957252       1 static_autoscaler.go:138] Starting main loop
I0129 18:57:37.957559       1 utils.go:595] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0129 18:57:37.957578       1 static_autoscaler.go:294] Filtering out schedulables
I0129 18:57:37.957650       1 static_autoscaler.go:311] No schedulable pods
I0129 18:57:37.957666       1 scale_up.go:263] Pod default/autoscaler-demo-779f4f6ffc-dlhj9 is unschedulable
I0129 18:57:37.957675       1 scale_up.go:263] Pod default/autoscaler-demo-779f4f6ffc-l2kbr is unschedulable
I0129 18:57:37.957680       1 scale_up.go:263] Pod default/autoscaler-demo-779f4f6ffc-5ng6k is unschedulable
I0129 18:57:37.957685       1 scale_up.go:263] Pod default/autoscaler-demo-779f4f6ffc-bmdkn is unschedulable
I0129 18:57:37.957690       1 scale_up.go:263] Pod default/autoscaler-demo-779f4f6ffc-d8522 is unschedulable
I0129 18:57:37.957717       1 scale_up.go:300] Upcoming 0 nodes
W0129 18:57:37.957727       1 scale_up.go:325] Node group eks-20b7f445-e65a-733a-83c0-5948bab952a6 is not ready for scaleup - backoff
I0129 18:57:37.957738       1 scale_up.go:416] No expansion options
I0129 18:57:37.957827       1 static_autoscaler.go:366] Calculating unneeded nodes
I0129 18:57:37.957839       1 utils.go:552] Skipping ip-10-135-180-170.ec2.internal - node group min size reached
I0129 18:57:37.957848       1 utils.go:552] Skipping ip-10-135-181-197.ec2.internal - node group min size reached
I0129 18:57:37.957918       1 static_autoscaler.go:393] Scale down status: unneededOnly=false lastScaleUpTime=2020-01-29 18:18:36.511300932 +0000 UTC m=+0.444576773 lastScaleDownDeleteTime=2020-01-29 18:18:36.511302374 +0000 UTC m=+0.444578171 lastScaleDownFailTime=2020-01-29 18:18:36.511303703 +0000 UTC m=+0.444579475 scaleDownForbidden=false isDeleteInProgress=false
I0129 18:57:37.957943       1 static_autoscaler.go:403] Starting scale down
I0129 18:57:37.957974       1 scale_down.go:706] No candidates for scale down
I0129 18:57:37.958218       1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"autoscaler-demo-779f4f6ffc-bmdkn", UID:"4880396d-42c8-11ea-9cb6-0a60dae348f7", APIVersion:"v1", ResourceVersion:"271032", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up
I0129 18:57:37.958243       1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"autoscaler-demo-779f4f6ffc-l2kbr", UID:"48800abb-42c8-11ea-9cb6-0a60dae348f7", APIVersion:"v1", ResourceVersion:"271011", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up
I0129 18:57:37.958253       1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"autoscaler-demo-779f4f6ffc-d8522", UID:"48804d6d-42c8-11ea-9cb6-0a60dae348f7", APIVersion:"v1", ResourceVersion:"271038", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up
I0129 18:57:37.958262       1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"autoscaler-demo-779f4f6ffc-dlhj9", UID:"48800f90-42c8-11ea-9cb6-0a60dae348f7", APIVersion:"v1", ResourceVersion:"271018", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up
I0129 18:57:37.958274       1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"autoscaler-demo-779f4f6ffc-5ng6k", UID:"4880217c-42c8-11ea-9cb6-0a60dae348f7", APIVersion:"v1", ResourceVersion:"271028", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up

Config-Map statuc:

apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2020-01-29 19:13:42.574149116 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0)
                   LastProbeTime:      2020-01-29 19:13:42.439761298 +0000 UTC m=+3306.373037189
                   LastTransitionTime: 2020-01-29 18:18:46.511794436 +0000 UTC m=+10.445070290
      ScaleUp:     NoActivity (ready=2 registered=2)
                   LastProbeTime:      2020-01-29 19:13:42.439761298 +0000 UTC m=+3306.373037189
                   LastTransitionTime: 2020-01-29 18:18:46.511794436 +0000 UTC m=+10.445070290
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2020-01-29 19:13:32.428536656 +0000 UTC m=+3296.361812700
                   LastTransitionTime: 2020-01-29 18:18:46.511794436 +0000 UTC m=+10.445070290

    NodeGroups:
      Name:        eks-20b7f445-e65a-733a-83c0-5948bab952a6
      Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0 cloudProviderTarget=2 (minSize=2, maxSize=3))
                   LastProbeTime:      2020-01-29 19:13:42.439761298 +0000 UTC m=+3306.373037189
                   LastTransitionTime: 2020-01-29 18:18:46.511794436 +0000 UTC m=+10.445070290
      ScaleUp:     Backoff (ready=2 cloudProviderTarget=2)
                   LastProbeTime:      2020-01-29 19:13:42.439761298 +0000 UTC m=+3306.373037189
                   LastTransitionTime: 2020-01-29 18:38:32.428454744 +0000 UTC m=+1196.361730610
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2020-01-29 19:13:32.428536656 +0000 UTC m=+3296.361812700
                   LastTransitionTime: 2020-01-29 18:18:46.511794436 +0000 UTC m=+10.445070290

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2020-01-29 19:13:42.574149116 +0000
      UTC
  creationTimestamp: "2020-01-29T17:06:22Z"
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "275319"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: ace573e9-42b9-11ea-ad26-0e8653154473

**Comment by amitsehgal** [comment]
CA versoin 6.3.0 kube 1.41 EKS

**Comment by mrPsycho** [comment]
@amitsehgal  have you found solution?

**Comment by mfriedman1-chwy** [comment]
any updates?
