### ISSUE TITLE
Add VPA e2e tests for recommender respecting Min and MaxAllowed

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#2784]
VPA Spec allows to specify minimum and maximum amount that can be recommended:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L206

We should have a test checking that these constraints are not violated.
@krzysied

**Comment by krzysied** [comment]
I assume this is the correct link to what we want to test:
https://github.com/kubernetes/autoscaler/blob/668470fe9d235489227593bb007277341d6512f7/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L142-L149

**Comment by krzysied** [comment]
Let's do the cleanup first: #2816
