### ISSUE TITLE
Unexpected instance terminated

### ISSUE THREAD

**Issue by caiohasouza** [kubernetes/autoscaler#2787]
Hello,

I'm having unexpected terminated instances, on ASG log i have:

> Description:DescriptionTerminating EC2 instance: i-02a01283e1ef6b08d
> Cause:CauseAt 2020-01-30T21:13:17Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 6 to 5. At 2020-01-30T21:13:17Z instance i-02a01283e1ef6b08d was selected for termination.

On CAS i haven't any log about terminated instance, i have only this:
> Nodegroup is nil for aws:///us-east-1d/i-02a01283e1ef6b08d

This behavior is causing cluster problems because the instance are shutdown before the Kubernetes reeschedule the pods and respect the pdb.

The action (instance terminated) is generating by CAS? Or by AWS?

Thank you!

**Comment by caiohasouza** [comment]
Hello,

I have news update about this issue, i added to ASG "[Suspended Process](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html)" the "Terminate" option, with this config the ASG don't terminate instance on Desired changes. After this change the problem not happened anymore, all downscale actions were made by by CAS and i can't saw the error here described.

Today i removed the "Terminate" option and the problem back to happen.

Has someone the same problem? It's "safe" disable the Terminate process?

Regards

**Comment by otterley** [comment]
Something (possibly not Cluster AutoScaler) is decreasing the Auto Scaling Group's desiredCount value.  That value is the number of EC2 instances that belong to the Group. 

If the value is decreased (6 to 5 in this case), and there are more than 5 instances in the Group, EC2 Auto Scaling will choose an instance to terminate, and then terminate it.  

But this isn't normally the way Cluster Autoscaler works - it doesn't blindly reduce the desiredCount.  Instead, it tries to cleanly terminate the instance by identifying a specific instance to terminate, cordon and drain the node associated with the instance, and then --  after it's drained -- terminate that specific instance.  So I'm not exactly sure why you're experiencing this.

I would check your CloudTrail logs to see what might be manipulating the Auto Scaling Group's desiredCount value (other than CA).  Perhaps there's something else in the way, like an EC2 Auto Scaling policy attached to the Group.

**Comment by caiohasouza** [comment]
@otterley thank you.

I understand.I search on cloudtrail with this query:

> fields @timestamp, eventTime, eventName, @message
| filter requestParameters.desiredCapacity=5
| sort eventTime desc

But no result is displayed, very strange...

**Comment by zagr0** [comment]
hi, have the same issue

happens regularly once a day during CA scales down the cluster in AWS
from CA logs I see that there is usual scale down, node is evicted and then removing, there is desired count changed 5->4 on ASG
during the node actual removing, somehow desired count changed back 5->4, ASG bring new node to the cluster
in CA logs there is
```
Jul 21, 2020 @ 22:58:19.508 | I0721 19:58:19.508362       1 static_autoscaler.go:255] 1 unregistered nodes present
```
after node removing have been finished desired count again changed 5->4
that triggers unexpected random node removing by ASG that is not controlled by CA

![image](https://user-images.githubusercontent.com/19431669/88259993-225aeb80-cccc-11ea-8150-16d0d5301f4e.png)

can we have issue reopen?

**Comment by shtamura** [comment]
@caiohasouza @zagr0 
We had the same problem and solved it.

We accidentally associated the same ASG of our cluster with the CA of another cluster, causing conflicting requests to  the ASG and causing an unexpected termination.

Specifically, startup parametes of the CA in another cluster was set follows ...
`--node-group-auto-discovery = asg: tag = k8s.io / cluster-autoscaler / enabled, k8s.io / cluster-autoscaler / {same name of our cluster}`

It's a funny story, but I hope it helps you.
