### ISSUE TITLE
Scheduler Framework based PredicateChecker - followups

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/autoscaler#2797]
This is an umbrella issue to list followup items to be addressed after merging in https://github.com/kubernetes/autoscaler/pull/2796

 - [x] Do not return errors from ClusterSnapshot methods for which it does not make sense (Cleare, Revert?, Get*, RemovePod?, RemoveNode?)
 - [x] Pass nodeName to RemovePod to avoid costly iteration over all nodes
 - [x] Refactor errors in basic_cluster_snapshot.go.
 - [x] Remove deprecated_scheduler_snapshot
 - [x] N/A - already resolved ~~Add list of nodes (node names?) to FitsAny. Use that to optimize number of PreFilter calls in binpacking.~~
 - [x] Remove SnapshotClusterState() and all related code (ex. keeping listers in PredicateChecker).
 - [x] Add unit tests for BasicClusterSnaphsot (share with DeltaClusterSnapshot)
   - [x] Assert cached lists are invalidated on Commit()/modify (including the scenario described in https://github.com/kubernetes/autoscaler/pull/2799#discussion_r378348879)
 - [x] Address TODOs in predicates_checker_interface.go
   - [x] Forget FakeNodeInfoForNodeName ever existed
 - [x] Address every TODO(scheduler_framework_migration).
 - [x] Cleanup mess in scale-down so we always use ClusterSnapshot as source of truth (see comments below)
 - [x] Clean up how we calculate podDestinations list so it works with snapshot.
 - [ ] Consider if we could do a single FitsAny call in findPlaceFor (instead of tryNodeForPod in a loop) .
 - [x] Investigate what happens if there is "pending" pod in cluster with nodeName pointing to node which does not exist in cluster; fix if needed
 - [x] Check if GPU hack still works after removing IsNodeReadyAndSchedulablePredicate
 - [ ] Pass context Estimate(), rather that PredicateChecker and ClusterSnapshot to EstimateBuilder
 - [x] Create issue for AWS about failing `TestGetRegion`
 - [ ] kubernetes/kubernetes#87822

**Comment by gjtempleton** [comment]
I've already got a fix for the failing `TestGetRegion` in the closed PR #2750 - will open a separate PR for that now.
