### ISSUE TITLE
What does 'optimize utilization' in the GKE autoscaling docs represent in terms of configuring this software?

### ISSUE THREAD

**Issue by sjmiller609** [kubernetes/autoscaler#2798]
Our organization is assessing installing this project into our cluster vs using the GKE-provided autoscaling option. I had previously assumed that this project is the same software used by GKE for autoscaling their users' clusters.

There is a new feature called "optimize utilization" documented by GKE (https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler), but I don't see any such feature in the release notes of this project. That has prompted me to question if these are the same software or not. Any tips?

**Comment by sjmiller609** [comment]
GKE docs do link back to this project in a few places. Is it just a configuration for scale down that GKE is abstracting?

**Comment by MaciekPytel** [comment]
GKE uses a fork of cluster autoscaler, with GKE-specific features and optimizations. As per GKE documentation you linked "optimize utilization" makes autoscaler scale-down more aggressively, but it doesn't directly map to any single feature or configuration of CA.

**Comment by sjmiller609** [comment]
Thanks!
