### ISSUE TITLE
Support for NodeGroups in Magnum

### ISSUE THREAD

**Issue by brtknr** [kubernetes/autoscaler#2802]
Now that Magnum Train has NodeGroups support, can the cluster-autoscaler work with new nodegroups that are added to a cluster?
https://github.com/kubernetes/autoscaler/blob/1d2f183dc739b3ba03496dee6f458c4c8990a130/cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment.yaml#L31

**Comment by tghartland** [comment]
It's something I'm working on, the main functionality is done but there are some situations that still don't work properly.

For example, to give the autoscaler information about nodes which are being created, the cloudprovider is querying Heat to find the stacks for those nodes. When one of those nodes fails (e.g quota error) the autoscaler tries to remove the node immediately, but the entry in Heat is not removed until any other in progress nodes have finished creating. The autoscaler keeps seeing the failed node, and keeps trying to delete it - continuously decreasing the node count until it reaches the minimum allowed value, and wrongly removing other nodes which should not be removed. I'm still trying different ways to solve this.

Sorry it's taking a while to get this done. We've just upgraded our Magnum to Train so it's a high priority, and I can work on this much easier than in devstack now.

And can I ask what your thoughts are about node group autodiscovery? At the moment the only viable strategy would be selecting node groups based on their Role, but here we've also discussed changing Magnum to add an "Autoscaling" property to each node group or something similar, which would be mutable after creation (Role is not).

**Comment by tghartland** [comment]
And regarding your question, the autoscaler will continue to work when Magnum is upgraded to Train, but **not** if extra node groups are added to clusters.

Say you have a cluster with two worker node groups, one node each. The autoscaler only sees the total node count **2**. If it wanted to add one node to the cluster it would make a resize request for **3** nodes, but this would be directed to the default-worker node group, where two nodes would be added instead of one, making the new total size **4**.

**Comment by brtknr** [comment]
Sorry for the slow reply. Are you planning to use the cluster resize API for Magnum rather than going via Heat? It would make things a lot more reliable than they are now. I am happy to work together on this.

**Comment by tghartland** [comment]
Yes, the resize API is used to make scaling requests. It is definitely more reliable than using heat.

The one thing that heat is still necessary for is to be able to track the progress of a resize after it has been requested. The autoscaler uses this information to know when nodes have failed to be created and react to that.

The downside as I mentioned is that heat can only really do one thing at once, so when there are multiple operations queued the heat state is not always up to date with what the autoscaler thinks the state should be, and this causes problems.

**Comment by brtknr** [comment]
Can we not track the progress by using gophercloud nodegroups API? you can retrieve status of a nodegroup there right?

Slightly out of scope of this discussion, I was wondering if you can shed a light on what is happening here as I am not 100% sure about how the cluster-autoscaler behaves: http://paste.openstack.org/show/790032/. It looks like the autoscaler waits for the pod to complete and when the pod is not successfully evicted, it moves on to the next node and tries to evict all the pods... this is slightly causing problems for us.

**Comment by tghartland** [comment]
With the node group API it is possible to check the overall state of a scale operation (basically `IN_PROGRESS` or `COMPLETE`), but the cloud provider should implement a `Nodes()` method which will return a full list of instances belonging to a particular node group (including `IN_PROGRESS` ones which have not yet been registered in the cluster), and the individual state of each instance. This information is not available from the node group API, is has to be retrieved from Heat. Currently this is unimplemented in the magnum cloud provider, and trying to make a working implementation leads me to the problems with Heat.

In your logs, the "Not deleted yet" lines are part of the eviction process, yes. But the problem might be that the autoscaler and magnum are out of sync on the size of the cluster.

If you do `kubectl -n kube-system describe cm cluster-autoscaler-status` you can see the current size of the cluster according to the autoscaler. There is a "cluster-wide" section which includes the master node, but there should be a node groups section with a single node group that has the same size as the cluster.
```
NodeGroups:
  Name:        default-worker
  Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=1, maxSize=4))
```
Where the `ready=1` is the number of minion nodes that there should be.
If that number is lower than the number of minions according to Magnum, then it would be unable to delete nodes. This could happen if you scaled the cluster manually or the autoscaler restarted while a scaling operation was in progress, but I wrote it to be frequently checking the size in Magnum so it should sort itself out.

**Comment by brtknr** [comment]
Thanks @tghartland. Is there any reason why we shouldn't implement `Nodes()` method upstream? Looks like it would be a fairly small change to update the code on magnum side as we already extract INSTANCE_NAME.

**Comment by sgoggins** [comment]
Upstream integration seems like a good idea to me.

**Comment by tghartland** [comment]
Having a way to directly query the list of nodes belonging to a node group in Magnum is something I discussed with Theodoros when he was finishing up node groups, but we decided it wasn't a priority. In the end it would just be another way for the autoscaler to access (some of) the information that is already available from Heat.

On the other hand it could be useful to expand this as a user facing API, to have something like:
```
$ openstack coe cluster nodes list kube-01
+-------------------------------------+----------------+--------------------+---------+
| Name                                | Node group     | Status             | Health  |
+-------------------------------------+----------------+--------------------+---------+
| kube-01-wngxn7kxxo5q-master-0       | default-master | UPDATE_COMPLETE    | Healthy |
| kube-01-wngxn7kxxo5q-node-0         | default-worker | UPDATE_COMPLETE    | Healthy |
| kube-01-wngxn7kxxo5q-node-1         | default-worker | CREATE_COMPLETE    | Healthy |
| kube-01-staging-da2edql6xwux-node-0 | staging        | CREATE_IN_PROGRESS | None    |
+-------------------------------------+----------------+--------------------+---------+
```
with filters for node group, etc.

If data like the server ID of each node could be aggregated into this, it would simplify some things that are required for the autoscaler such as finding which node group a node belongs to.

**Comment by brtknr** [comment]
Hi Thomas, the reason that Magnum does have have info on nodes that still in progress is because in the current implementation, the detailed query only takes place once a Stack becomes "COMPLETE". I believe this behavior was implemented in order to limit the number of regular queries to the Heat API.

**Comment by tghartland** [comment]
The defaults in the autoscaler are to request information on running nodes every 2 minutes when idle, and after scaling up it will change to make the request on every main loop (every 10 seconds by default) until all new nodes are running.

If this is too much for heat we can adjust the `--scan-interval` that Magnum installs the autoscaler with, to reduce how often the main loop is run. But that would increase the latency of reacting to new pods that require a cluster scale up.

Do you have a link to the code where Magnum makes the detailed request to Heat after a node is completed?

**Comment by brtknr** [comment]
Yep the detailed request is made here: https://github.com/openstack/magnum/blob/c8cc8f0aef6eb606d52f5db1fdfca4a614302fa9/magnum/drivers/heat/driver.py#L512

**Comment by brtknr** [comment]
@tghartland I wonder if the autoscaler can assume that the requested number of nodes are being added while the status is _IN_PROGRESS?
