### ISSUE TITLE
addon-resizer v1.8.4 or v2.1 doesn't work on v1.16.x of kubernetes

### ISSUE THREAD

**Issue by rpenugonda** [kubernetes/autoscaler#2803]
we ran into this issue when we are upgrading a cluster. The issue seems to be deprecation
 of api groups in v1.16.4
do you have a version which works with 1.16.x?
error is 
`
I0206 16:31:22.150820       1 nanny_lib.go:118] Resources are not within the expected limits, updating the deployment. Actual: {Limits:map[] Requests:map[]} New: {Limits:map[memory:{i:{value:0 scale:0} d:{Dec:0xc420ca11a0} s:2270Mi Format:BinarySI} cpu:{i:{value:0 scale:0} d:{Dec:0xc420ca0b40} s:2110m Format:DecimalSI}] Requests:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc420ca0b40} s:2110m Format:DecimalSI} memory:{i:{value:0 scale:0} d:{Dec:0xc420ca11a0} s:2270Mi Format:BinarySI}]}
`
when we used debug with verbose logging it clearly shows it can't find the deployment
`
0206 16:31:22.151805       1 round_trippers.go:318] GET https://10.96.0.1:443/apis/extensions/v1beta1/namespaces/monitoring/deployments/kube-state-metrics 404 Not Found in 0 milliseconds
I0206 16:31:22.151816       1 round_trippers.go:324] Response Headers:
I0206 16:31:22.151820       1 round_trippers.go:327]     Content-Length: 174
I0206 16:31:22.151823       1 round_trippers.go:327]     Audit-Id: 431c0062-12f4-4be5-8155-8f1c1ab2b4fd
I0206 16:31:22.151826       1 round_trippers.go:327]     Cache-Control: no-cache, private
I0206 16:31:22.151829       1 round_trippers.go:327]     Content-Type: application/json
I0206 16:31:22.151831       1 round_trippers.go:327]     Date: Thu, 06 Feb 2020 16:31:22 GMT
I0206 16:31:22.151856       1 request.go:891] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
`
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ is the depreciation list

**Comment by bskiba** [comment]
https://github.com/kubernetes/autoscaler/releases/tag/addon-resizer-1.8.7

**Comment by rpenugonda** [comment]
thank you, my bad i missed it.

**Comment by bskiba** [comment]
No problem, let me know if it doesn't work as expected
