### ISSUE TITLE
[Cluster-autoscaler] Custom max volume count setting possible? 

### ISSUE THREAD

**Issue by cliles** [kubernetes/autoscaler#2806]
How does cluster-autoscaler determine node max volume count?

When using a custom volume count limit, via KUBE_MAX_PD_VOLS, seems that scale up is skipped.

```
1 scheduler_binder.go:651] All bound volumes for Pod "namespace/some-pod-wvlvv" match with Node "ip-1-1-1-1.us-west-2.compute.internal"

filter_out_schedulable.go:107] Pod some-pod-wvlvv marked as unschedulable can be scheduled on ip-1-1-1-1.us-west-2.compute.internal. Ignoring in scale up.
```

This would be true if a custom volume limit was not active. In such a configuration the pod is not scheduled by the scheduler because all nodes have exhausted their number of volumes.

**Comment by MaciekPytel** [comment]
CA basically takes scheduler predicates (or, in 1.18+ filters) and runs them in default configuration to determine what is schedulable and what would be schedulable if more nodes were added. Custom configurations are currently not supported.

**Comment by paurosello** [comment]
Were could we start working on this? Kubernetes 1.16 with autoscaler 1.16.4

On the pod we get:
```
Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 3 node(s) exceed max volume count.
```

On the autoscaler:
```
cluster-autoscaler I0408 14:57:29.119700       1 predicates.go:445] PVC default/pod-pvc3 is not bound, assuming PVC matches predicate when counting limits
cluster-autoscaler I0408 14:57:29.119823       1 scheduler_binder.go:678] No matching volumes for Pod "default/pod-pvc3", PVC "default/pod-pvc3" on node "ip-10-1-6-7.eu-central-1.compute.internal"
cluster-autoscaler I0408 14:57:29.119833       1 scheduler_binder.go:733] Provisioning for claims of pod "default/pod-pvc3" that has no matching volumes on node "ip-10-1-6-7.eu-central-1.compute.internal"
cluster-autoscaler I0408 14:57:29.119853       1 filter_out_schedulable.go:124] Pod pod-pvc3 marked as unschedulable can be scheduled on existing node ip-10-1-6-7.eu-central-1.compute.internal. Ignoring in scale up.
```

We have tried setting up the env KUBE_MAX_PD_VOLS in the scheduler but the featuregate AttachVolumeLimit might be overriding it

**Comment by cliles** [comment]
For kube 1.11 with CAS 1.15.x - KUBE_MAX_PD_VOLS seems to just work. It must also be set as environment var for CAS.

**Comment by MaciekPytel** [comment]
Cluster Autoscaler doesn't interact with scheduler binary running in cluster, it imports some of scheduler code and runs that. So any config change must be applied to CA and not scheduler. If the embedded code happens to look at this env var than setting it as per @cliles comment may work. 
Note that if it works its only due to luck and we give no guarantees on it whatsoever. It may stop working in any version if the underlying scheduler code changes and the env variable check is moved to the part of code that we don't happen to call.

For the feature to be officially supported by Cluster Autoscaler the value would need to be explicitly passed to embedded scheduler code (probably somewhere around https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go#L65?).

**Comment by hobti01** [comment]
> Cluster Autoscaler doesn't interact with scheduler binary running in cluster, it imports some of scheduler code and runs that. So any config change must be applied to CA and not scheduler.

Yes, the environment variable has been applied to CAS and it is read with `os.Getenv(KubeMaxPDVols)` imported from 
https://github.com/kubernetes/kubernetes/blob/v1.16.4/pkg/scheduler/algorithm/predicates/predicates.go#L401

But the problem happens just after the environment variable is read when the enabled feature gate overwrites the value https://github.com/kubernetes/kubernetes/blob/v1.16.4/pkg/scheduler/algorithm/predicates/predicates.go#L536-L543
```
utilfeature.DefaultFeatureGate.Enabled(features.AttachVolumeLimit)
```

Is there a method to disable/enable the feature gates used by CAS scheduler simulation?

**Comment by MaciekPytel** [comment]
> Is there a method to disable/enable the feature gates used by CAS scheduler simulation?

Not that I know of. You may get lucky with some other env variable or similar, but there is no explicit mechanism. CA generally only supports default scheduler configuration.

**Comment by hobti01** [comment]
I'm going to try again :)
> CA generally only supports default scheduler configuration.
CA is coded to only support the default scheduler or is there any mechanism for modifying the configuration?

Could anyone identify the code section(s) that are determining this?

We'd really like to resolve this even if it means a PR or fork but are having a difficult time finding the right sections.

**Comment by MaciekPytel** [comment]
> CA is coded to only support the default scheduler or is there any mechanism for modifying the configuration?
> Could anyone identify the code section(s) that are determining this?

I don't think there is any section in CA that determines or modifies any scheduler config. Or any other logic related in any way to feature gates. CA just creates scheduler framework (in scheduler_based_predicates_checker.go linked above) and relies that whatever happens behind the scenes will yield a working framework with default settings.

PredicateChecker is really the single integration point between CA and scheduler.
(technically speaking we also re-use some scheduler structs and utils all over the codebase, but it's not really calling into scheduling logic).
