### ISSUE TITLE
Cluster Autoscaler: Specifying allocatable resources with node-template tags

### ISSUE THREAD

**Issue by tbarrella** [kubernetes/autoscaler#2809]
When scaling up from 0 on AWS, it doesn't appear that CA has any way of knowing about `--kube-reserved` or `--system-reserved` resources. It seems like it would be hard for CA to know about this in general without using tags from the ASG. The `k8s.io/cluster-autoscaler/node-template/label/ephemeral-storage` tag can already be used to specify allocatable ephemeral storage. If there aren't foreseen issues, I want to propose also being able to use these tags for cpu and memory at https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.17.0/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L368

**Comment by tbarrella** [comment]
Note on the priority: Because of this, for an unschedulable pod, CA might scale up a node from zero whose capacity fits the pod but not its allocatable resources, causing the pod to remain unschedulable. Depending on the expander, CA might never scale up the right node for the pod

**Comment by Jeffwan** [comment]
@tbarrella Yes. 

> CA might scale up a node from zero whose capacity fits the pod but not its allocatable resources

Agree. Originally in that PR,  we plan to override it but later on we concentrate on ephemeral-storage issue. I think what we can have two options.

1. override `cpu` and `memory` directly and set this value as `node.Status.Capacity`

2. provide new label like `k8s.io/cluster-autoscaler/node-template/reserved` , user can use `system` or `kube` as suffix of Tag Key, use value they set in kubelet.In the node template construction, we just set `node.Status.Allocatable`.  using Instance Resource minus reserved value.

**Comment by rimaulana** [comment]
Hi @Jeffwan 

Options number 1 would be easier but implementing it on an infrastructure as code (IAC) would be a little bit difficult as the IAC needs to be able to calculate the resources based on the instance type to get the base capacity (CPU and Memory) then subtracts it with the value that will be passed in **--system-reserved** and/or **--kube-reserved**.

While option 2 we can offload the calculation mentioned on option 1 on CA side and it is pretty straightforward on IAC side, ASG tag and flag  **--system-reserved** and/or **--kube-reserved** will have the same value. One thing with option 2 though, I don't believe there is an easy way to override the **--kube-reserved** value that is dynamically calculated by EKS bootstrap script on EKS Optimized AMI.

**Comment by jaypipes** [comment]
> 1. override `cpu` and `memory` directly and set this value as `node.Status.Capacity`

But we wouldn't have a `Node` object yet in the case of scale-from-zero, which I believe is the source of this bug, right?

> 2. provide new label like `k8s.io/cluster-autoscaler/node-template/reserved` , user can use `system` or `kube` as suffix of Tag Key, use value they set in kubelet.In the node template construction, we just set `node.Status.Allocatable`.  using Instance Resource minus reserved value.

@rimaulana is correct that, for EKS at least, determining `--kube-reserved` would be problematic due to the dynamic calculation of this (based on the underlying instance type) in the bootstrap script for the EKS AMI. We would need to copy or emulate this logic within the AWS cloud provider in CA...

**Comment by Jeffwan** [comment]
> > 1. override `cpu` and `memory` directly and set this value as `node.Status.Capacity`
> 
> But we wouldn't have a `Node` object yet in the case of scale-from-zero, which I believe is the source of this bug, right?

Yes. We don't have a real node for simulation in scale-from-zero case and we have to build a node template from ASG. As we have resources spec for all available instances. From capacity wide, this is accurate.

> > 1. provide new label like `k8s.io/cluster-autoscaler/node-template/reserved` , user can use `system` or `kube` as suffix of Tag Key, use value they set in kubelet.In the node template construction, we just set `node.Status.Allocatable`.  using Instance Resource minus reserved value.
> 
> @rimaulana is correct that, for EKS at least, determining `--kube-reserved` would be problematic due to the dynamic calculation of this (based on the underlying instance type) in the bootstrap script for the EKS AMI. We would need to copy or emulate this logic within the AWS cloud provider in CA...

I think there're two requests. 
1. Provide override option for `k8s.io/cluster-autoscaler/node-template/reserved` like what we did for other resources. Calculate node allocatable resources based on the Tag value user set.

User can override `--kube-reserved` in EKS optimized AMI in bootstrap scripts as well. User can use exact same setting in CA and EKS optimized AMI. 

2. Whether we want to have default logic that if `k8s.io/cluster-autoscaler/node-template/reserved` doesn't exist. 

If people would like to use default reserved value from EKS optimized AMI. It would be hard.  Similarly like EKS optimized AMI take cares the calculation, the easiest way is to copy the same logic like what we did inside AMI to CA. 

If we do both, I think it meets needs for most of the cases, not just EKS but other self-managed AWS cluster. (In this case, they have to override configs)

**Comment by jbg** [comment]
Did this, or something similar, ever get implemented? We're customising the kube-reserved cpu & memory on some node pools (reducing it due to the default logic reserving excessive resources) and finding that cluster-autoscaler doesn't scale up because it thinks the pod won't fit.

**Comment by jbg** [comment]
For anyone interested, it looks like this was in fact implemented: https://github.com/kubernetes/autoscaler/blob/f87dbe5fc65ae6a6c550b0c22d7910ec192e7cfb/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L439

You can specify tags on the ASG in the format `k8s.io/cluster-autoscaler/node-template/resources/RESOURCE_TYPE` where `RESOURCE_TYPE` is e.g. `cpu` or `memory` and the value is a quantity in the usual k8s format.
