### ISSUE TITLE
Nodes that are scheduled for removed are marked unreachable

### ISSUE THREAD

**Issue by omerlh** [kubernetes/autoscaler#2811]
See kubernetes-monitoring/kubernetes-mixin#300

I noticed that when cluster autoscaler decides to delete a node, it adds a taint "unreachable" to it - which is reserved for indicating a problematic node. It would be better to have a specific taint here instead - something like `cluster-autoscaler-scaledown`.

Thoughts?

**Comment by MaciekPytel** [comment]
Cluster Autoscaler already uses a [custom taint][1] (which is also mentioned in the issue you linked). And it doesn't set "unreachable" taint.
I think "unreachable" taint popping up is an artifact of the way nodes are cleaned up in Kubernetes. CA doesn't directly manage lifecycle of Node objects (ie. it doesn't create or delete them). All CA does is add or delete VMs on cloudprovider side. 
So the flow of CA deleting a node is:
1. CA picks a node, taints it and evicts all pods.
2. CA deletes underlying VM.
3. Kubernetes figures it out and removes the Node object corresponding to that VM. 

My guess is that "unreacheable" is set sometime between 2 and 3, as Kubernetes loses connectivity with the deleted VM (I also suspect the details will depend on which cloud provider you're using).
Unfortunately I see no easy fix here. An obvious approach would be for CA to notify NodeController (and/or other k8s components) that it plans to delete a node. However, there is currently no prescribed way CA could use to do that. 
An alternative solution would be for Kubernetes itself to try and somehow distinguish whether a VM is deleted or if there is some problem with it. That would have the benefit of working both with CA and any other way of removing nodes (other autoscaler, manual deletion). I suspect that would be pretty hard though, so it's unlikely to happen.

[1]: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/deletetaint/delete.go#L35

**Comment by omerlh** [comment]
Thanks for the detailed answer! May I ask - why does cluster autoscaler not removing the node before deleting the VM?

**Comment by hectorj2f** [comment]
@omerlh that is something that should be done by the providers, however that brings a problem related to awareness when a deletion failed. How would you be able to know that machine is still there even if it was already drained ?

In my opinion it should be done by the providers code, although you can avoid that and wait until the apiserver considers it as gone once the hearbeat timed out ?
