### ISSUE TITLE
CA / Azure - Autoscaler fails to respect 429 API Rate limits, and will exhaust API allowed requests

### ISSUE THREAD

**Issue by Starblade42** [kubernetes/autoscaler#2817]
Cluster Autoscaler in Azure fails to respect the 429's that are returned from the Azure API, and will continue to query across multiple functions, further depleting and extending the exhaustion time for Azure API Rate limits:

In these example logs, the API returns a 429 for all attempts to use the Azure API to get the latest information, and the requests ignore the header to tell them when they can safely retry.

This depletes the available quota, and increases the time that the API is throttled for the Cluster Autoscaler service principal in Azure.

In the attached logs you can see several methods that all have this same sub-optimal behavior:

- getVMSSInfo()
- GetScaleSetVms()
- VirtualMachineScaleSetVMsClient.List

And there are likely other methods that aren't currently respecting rate limiting in Azure.

[2020-02-05 azure_429_autoscaler_not_backing_off.csv.zip](https://github.com/kubernetes/autoscaler/files/4183420/2020-02-05.azure_429_autoscaler_not_backing_off.csv.zip)

```

W0205 09:20:50.771433       1 azure_scale_set.go:188] getVMSSInfo() is throttled with message compute.VirtualMachineScaleSetsClient#List: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet3Min","startTime":"2020-02-05T09:20:50.7291783+00:00","endTime":"2020-02-05T09:22:50.7291783+00:00","allowedRequestCount":281,"measuredRequestCount":661}","target":"HighCostGetVMScaleSet3Min"},{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet30Min","startTime":"2020-02-05T09:20:50.7291783+00:00","endTime":"2020-02-05T09:40:00+00:00","allowedRequestCount":1405,"measuredRequestCount":3607}","target":"HighCostGetVMScaleSet30Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}, would return the cached vmss size
--
W0205 09:20:50.717387       1 azure_scale_set.go:585] GetScaleSetVms() is throttled with message compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet3Min","startTime":"2020-02-05T09:20:50.6823037+00:00","endTime":"2020-02-05T09:22:50.6823037+00:00","allowedRequestCount":281,"measuredRequestCount":660}","target":"HighCostGetVMScaleSet3Min"},{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet30Min","startTime":"2020-02-05T09:20:50.6823037+00:00","endTime":"2020-02-05T09:40:00+00:00","allowedRequestCount":1405,"measuredRequestCount":3606}","target":"HighCostGetVMScaleSet30Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}, would return the cached instances
E0205 09:20:50.717317       1 azure_scale_set.go:307] VirtualMachineScaleSetVMsClient.List failed for vmss-agent-worker2-11prodaus5-qkymw: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet3Min","startTime":"2020-02-05T09:20:50.6823037+00:00","endTime":"2020-02-05T09:22:50.6823037+00:00","allowedRequestCount":281,"measuredRequestCount":660}","target":"HighCostGetVMScaleSet3Min"},{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet30Min","startTime":"2020-02-05T09:20:50.6823037+00:00","endTime":"2020-02-05T09:40:00+00:00","allowedRequestCount":1405,"measuredRequestCount":3606}","target":"HighCostGetVMScaleSet30Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}
W0205 09:20:50.679303       1 azure_scale_set.go:188] getVMSSInfo() is throttled with message compute.VirtualMachineScaleSetsClient#List: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet3Min","startTime":"2020-02-05T09:20:50.651072+00:00","endTime":"2020-02-05T09:22:50.651072+00:00","allowedRequestCount":281,"measuredRequestCount":659}","target":"HighCostGetVMScaleSet3Min"},{"code":"TooManyRequests","message":"{"operationGroup":"HighCostGetVMScaleSet30Min","startTime":"2020-02-05T09:20:50.651072+00:00","endTime":"2020-02-05T09:40:00+00:00","allowedRequestCount":1405,"measuredRequestCount":3605}","target":"HighCostGetVMScaleSet30Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}, would return the cached vmss size
```

**Comment by alexeldeib** [comment]
Could you share the versions of both Kubernetes and CA you’re using? Is this a managed cluster (AKS) or unmanaged?

@marwanad fyi

**Comment by marwanad** [comment]
There's one cache improvement that targets GET calls - still pending official release. A change to respect Retry-After headers is also in the plans.

Could you share your cluster details as well? How many VMSS and how many clusters running autoscaler in your subscription?

**Comment by Starblade42** [comment]
Very happy to hear about the issues you highlighted! 😄 

They've been causing us a ton of pain recently. An accompanying bug in the CA (still gathering details) leaves NotReady nodes in the cluster API even after the nodes have been deleted by the CA, and even having 1 NotReady (non-existent) node will exhaust our API allowance because of the current deficiencies in the Azure cloud provider, which appear to have been fixed in the merged items you cited.

cluster details:

The clusters are self-provisioned and managed in Azure:

- cluster autoscaler: v1.16.3
- Kubernetes v1.16.4

**Each and every cluster is provisioned into its own Azure subscription.** This is to avoid the absurd/extreme API usage of the current versions of these packages of the Azure API just for scale in/scale out operations, and to limit the impact to a single cluster.

A typical cluster has:
- 5 VMSS for the Workers (multi-AZ where available)
- 1 VMSS for the Masters (multi-AZ where available)
-  3 VMs running etcd placed into Availability Zones (where available)

So a typical total of 6 VMSS for the cluster, plus 3 vms. We're running something like 20 of these clusters and plan to make more. Typical (soft) max cluster size is ~200 nodes, but go up to ~250 during upgrades, which are performed basically every week.

**Comment by Starblade42** [comment]
That does sound like it will resolve our issue with the API specifically. Closing.
