### ISSUE TITLE
Azure - Cluster Autoscaler - Scale in: CA sometimes fails to delete nodes from kube-API though cloud deletion completes

### ISSUE THREAD

**Issue by Starblade42** [kubernetes/autoscaler#2821]
We've got ~20 clusters running Kubernetes on non-AKS clusters:

- cluster soft max size of ~200 nodes (most are steady state below this
- kubernetes `v1.16.4`
- cluster-autoscaler `v1.16.3`
- We typically have 5 VMSS for workers in Azure, and they are all multi-AZ enabled.

We've had a problem recently, especially with clusters that scale out and in very often that we end up with a nodes in a `NotReady` state.

Upon investigation, it was found that basically all of these nodes that are stuck `NotReady` don't exist in the cloud provider.

I'm not sure when the CA is supposed to complete removing the node from the API server, but it appears that it sometimes does not do this, leaving it in the `kube-API` as a registered node indefinitely. For context:

- We alert on the `NotReady` state of nodes if it's been going on for too long
- The alert continues to fire until we manually resolve it in the case that I'm describing here.
[2020-02-04_vmss-agent-worker1-11stageaus5-prxez00000z_deleted_from_cloud_left_in_kubernetes_API.csv.zip](https://github.com/kubernetes/autoscaler/files/4189203/2020-02-04_vmss-agent-worker1-11stageaus5-prxez00000z_deleted_from_cloud_left_in_kubernetes_API.csv.zip)
- This problem appears to have started when we went from a version of `v1.15` of CA and K8s to `v1.16`.

Here's an example from the `CA` logs:

```
{"message":"I0204 23:40:53.798184       1 scale_down.go:448] Skipping vmss-agent-worker1-11stageaus5-prxez00000z from delete considerations - the node is currently being deleted\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
```

After the cloud deletion completes, we'll see log messages like these until a person intervenes (so, this will go on for hours and hours):

```

{"message":"I0205 00:01:14.937701       1 scale_down.go:724] vmss-agent-worker1-11stageaus5-prxez00000z was unneeded for 0s\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
--

{"message":"I0205 00:01:04.626308       1 delete.go:110] ToBeDeletedByClusterAutoscaler already present on node vmss-agent-worker1-11stageaus5-prxez00000z, taint: {ToBeDeletedByClusterAutoscaler 1580859361 NoSchedule <nil>}\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
--
{"message":"I0205 00:01:04.620054       1 delete.go:110] ToBeDeletedByClusterAutoscaler already present on node vmss-agent-worker1-11stageaus5-prxez00000z, taint: {ToBeDeletedByClusterAutoscaler 1580859361 NoSchedule <nil>}\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
{"message":"I0205 00:01:04.619986       1 scale_down.go:966] Scale-down: removing empty node vmss-agent-worker1-11stageaus5-prxez00000z\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
{"message":"I0205 00:01:04.618004       1 scale_down.go:724] vmss-agent-worker1-11stageaus5-prxez00000z was unneeded for 20m0.769106873s\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
{"message":"I0205 00:00:54.580926       1 scale_down.go:724] vmss-agent-worker1-11stageaus5-prxez00000z was unneeded for 19m50.690807794s\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}
{"message":"I0205 00:00:44.496951       1 scale_down.go:724] vmss-agent-worker1-11stageaus5-prxez00000z was unneeded for 19m40.64752233s\n","stream":"stderr","pod_name":"cluster-autoscaler-6dfbc67574-5s99m","pod_uid":"f55fa6e9-73bc-4bf8-a273-c6de475a6b2a","pod_ip":"172.16.98.76","namespace":"kube-system","provider":"azure","region":"australiaeast","ethos_cluster":"ethos11stageaus5","node_name":"vmss-master-11stageaus5-jbafc000000","node_ip":"10.22.12.24","instance_id":"a701d730-d656-48d1-b055-739c29748aee"}

```

This doesn't always happen on a scale in, which leads me to believe its some kind of race condition in the Cluster Autoscaler, where it will sometimes "forget" that it just completed deleting the Azure instances from the VMSS.

**Comment by marwanad** [comment]
Kube-controller manager is the entity responsible for clearing the nodes from etcd as part of node lifecycle controller. Cluster-autoscaler deletes the nodes directly from Azure but leaves the Node object cleanup job to controller-manager.

My guess is because of your API calls being throttled, it's unable to do the cleanup because it needs to do an Azure API call on its side as well. [This](https://github.com/kubernetes/kubernetes/pull/87531) and the earlier CA issue linked specifically address this scenario.

Feel free to keep the issue open until you confirm the issue is gone with both fixes.

**Comment by nilo19** [comment]
Seems not an issue of CA, would you take a look at the logs of controller-manager? @Starblade42

**Comment by Starblade42** [comment]
Yeah, I'll take a look at our logs from the controller manager during this same window.

**Comment by marwanad** [comment]
@Starblade42 just wanted to follow-up, are you still seeing issues with the latest CAS and K8s minor releases? The changes should be available in 1.15+.

**Comment by Starblade42** [comment]
I believe that things have improved greatly. Thanks!

**Comment by marwanad** [comment]
Glad to hear that!

/close
