### ISSUE TITLE
Support for stop / start as opposed to node deletion?

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/autoscaler#283]
Has there been discussion (could not find it in issues or docs) about supporting alternate scaler mode that can stop/start nodes rather than created delete them?  We'd like to start using the autoscaler and help support it, but node creation is still fairly complicated (because of security requirements) and not suitable for autoscaling?

I'd be happy to get warm bodies around it.

**Comment by mwielgus** [comment]
@smarterclayton So far nobody has requested any support for starting/stopping instances. Moreover, it seems that, for example, GKE is not particularly compatible with stopping instances. After I stopped an instance it got back to life after couple minutes :).

So my question would be: what is the exact use case? In which environment do you want to run Cluster Autoscaler? How are the stopped machines visible to K8S? Are they marked as not ready or completely removed from the node list?

BTW, we have a sig-autoscaling meeting tomorrow, feel free to drop in.

**Comment by smarterclayton** [comment]
If you have a managed instance group, then yes, stopping the instance will result in

a) the instance being deleted and recreated (from a fresh boot dir)
b) the instance starting

If you run an unmanaged instance group, then this won't happen.

The use case is that the cluster autoscaler deals only with clusters where nodes are totally recreateable from images or launch config.  That's not the only way instances work - in this case, we configure a pool of nodes post startup and we simply want to control whether the machines are started or not.  The limit of the pool is the number of nodes we've already configured (rather than whatever an instance group might be configured to).  This has the advantage of working on any environment where individual machines don't need to come and go, but when not in use can be stopped to release resources (so more traditional VM environments).  On GCE it's specifically because machine configuration post startup is managed by an external process that can't be invoked on startup (doesn't have access to the right keys, is locked down, etc).

**Comment by mhausenblas** [comment]
Let's discuss in today's meeting, yes.

**Comment by davidopp** [comment]
Seems somewhat related to https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/ibVxgdLkeiM/TLhykRj8BgAJ (at least the idea of supporting different types of underlying node management models)

**Comment by smarterclayton** [comment]
Just to capture discussion from sig-autoscaling meeting:

1. In the long term, having autoscaler call out to another API is desirable
  1. APIs can be difficult to implement in all environments - we may want to use a similar extension to let shell scripts to be invoked (instead of an API)
2. I'll prototype something using the existing cloud provider abstraction with an eye for how it would may to 1.1 above
