### ISSUE TITLE
Kops Cluster on AWS fails to scale down

### ISSUE THREAD

**Issue by grohan2002** [kubernetes/autoscaler#2836]
Kops Cluster on AWS version  v1.14.8

`kubectl get cm cluster-autoscaler-status -o yaml -n kube-system                                                                                                                                        1 ↵
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2020-02-17 17:17:40.059509655 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=13 unready=0 notStarted=0 longNotStarted=0 registered=13 longUnregistered=0)
                   LastProbeTime:      2020-02-17 17:17:39.713415181 +0000 UTC
                   LastTransitionTime: 2020-01-07 07:53:41.919208334 +0000 UTC
      ScaleUp:     NoActivity (ready=13 registered=13)
                   LastProbeTime:      2020-02-17 17:17:39.713415181 +0000 UTC
                   LastTransitionTime: 2020-02-13 08:53:06.144390856 +0000 UTC
      ScaleDown:   CandidatesPresent (candidates=7)
                   LastProbeTime:      2020-02-17 17:17:39.713415181 +0000 UTC
                   LastTransitionTime: 2020-02-13 09:20:46.2127656 +0000 UTC`

    `NodeGroups:
      Name:        ***************************
      Health:      Healthy (ready=12 unready=0 notStarted=0 longNotStarted=0 registered=12 longUnregistered=0 cloudProviderTarget=12 (minSize=1, maxSize=20))
                   LastProbeTime:      2020-02-17 17:17:39.713415181 +0000 UTC
                   LastTransitionTime: 2020-01-07 07:53:41.919208334 +0000 UTC
      ScaleUp:     NoActivity (ready=12 cloudProviderTarget=12)
                   LastProbeTime:      2020-02-17 17:17:39.713415181 +0000 UTC
                   LastTransitionTime: 2020-02-13 08:53:06.144390856 +0000 UTC
      ScaleDown:   CandidatesPresent (candidates=7)
                   LastProbeTime:      2020-02-17 17:17:39.713415181 +0000 UTC
                   LastTransitionTime: 2020-02-13 09:20:46.2127656 +0000 UTC`

**Comment by Jeffwan** [comment]
Can you share the logs?
