### ISSUE TITLE
Add Oracle Cloud Infrastructure as provider

### ISSUE THREAD

**Issue by pranaypratyush** [kubernetes/autoscaler#2857]
Kinda surprised no one asked this already.

**Comment by MaciekPytel** [comment]
Support for different cloud providers is generally added by people involved with given platform, not CA developers. We're happy to accept it if Oracle Cloud (or an OSS contributor) wants to contribute one.

**Comment by pranaypratyush** [comment]
Sorry, I didn't know about this policy. Correct me if I am wrong, this module basically uses the provider SDK to scale node groups based on Kubernetes cluster state. If so then what's stopping someone from implementing this for OCI?

**Comment by MaciekPytel** [comment]
Nothing :) 
I'm not aware of any formal reasons stopping anyone from adding a provider to CA (assuming they sign Kubernetes CLA, etc). It's just a lot of work to add (and maintain) cloud provider integration (though amount of work depends on how many features you want to support, what are your scalability requirements, etc).
There are only so many core CA developers and we're no longer actively involved even in maintaining existing integrations. Rather every existing cloudprovider has it's own owner who maintains it. So for a new provider integration to happen someone needs to step up, implement it and own it later on.

**Comment by pranaypratyush** [comment]
Ah, I see.
Not to take your time even further, is there a guide or something to help
me get started on implementing OCI provider?
(Can't promise anything, I am new to kubernetes, 95% odds I won't be able
to do this)

**Comment by MaciekPytel** [comment]
There is no documentation unfortunately (if you end up implementing OCI provider and you feel like writing down some notes that would be very appreciated). 

In general what you need to do is implement the interfaces in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go. Probably the best way is using one of existing providers as a reference. I'd recommend either digitialocean (a young and relatively simple implementation) or GCE (first implementation, it's maintained by core CA developers, e2e tests used to qualify new CA release run on GCE - all of this makes it a good reference implementation, but it's also one of more complex with lots of features, caching, etc).

**Comment by caiohasouza** [comment]
+1
