### ISSUE TITLE
missing addon-resizer 2.3 images for non-amd64 architectures

### ISSUE THREAD

**Issue by edmondsw** [kubernetes/autoscaler#2869]
https://github.com/kubernetes/autoscaler/commit/069fa4d917b5ec9a7b5787bf6f036fc37636ec4f added multi-arch support for addon-resizer, but so far the only release for which images have been published to k8s.gcr.io/addon-resizer (as viewable at https://console.cloud.google.com/gcr/images/google-containers/GLOBAL) for other architectures has been version 2.1. There is a newer version 2.3 that was only published for amd64, indicating a reversion of the release process to no longer handle multi-arch. Can we get multi-arch images published for 2.3 and all releases going forward?

**Comment by mkumatag** [comment]
can someone please help us pushing these images for non-amd64 architectures? @aleksandra-malinowska , @listx, @ixdy 
steps:

```
make all-container
make all-push
```

**Comment by mkumatag** [comment]
@bskiba can you or someone can help us pushing these images?

**Comment by bskiba** [comment]
Yup, I'm on it.

**Comment by mkumatag** [comment]
> Yup, I'm on it.

I'm wondering if we can have some job which does take care of this automatically whenever there is a new release.

**Comment by bskiba** [comment]
We will move to the new k8s image staging/release process soon which should help with that: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos

**Comment by mkumatag** [comment]
> We will move to the new k8s image staging/release process soon which should help with that: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos

cool.

**Comment by bskiba** [comment]
Images should be available now. Let me know if there issues.
/close
