### ISSUE TITLE
Fix flaky admission controller unit test

### ISSUE THREAD

**Issue by bskiba** [kubernetes/autoscaler#2886]
I've seen multiple instances of this on unrelated PRs: 

?   	k8s.io/autoscaler/vertical-pod-autoscaler/common	[no test files]
?   	k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller	[no test files]
--- FAIL: TestGetPatchesForResourceRequest_TwoReplacementResources (0.00s)
    server_test.go:396: 
        	Error Trace:	server_test.go:396
        	Error:      	Should be true
        	Test:       	TestGetPatchesForResourceRequest_TwoReplacementResources
FAIL
FAIL	k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller/logic	0.097s

**Comment by bskiba** [comment]
Seen this again on #2895

**Comment by jbartosik** [comment]
This flake happens very rarely when I try to reproduce it locally. I'm runing

```bash
$ for i in $(seq 1 1000); do echo $i; make test-unit; ret=$?; if [ $ret -ne 0 ]; then echo fail: $ret; break; fi; done
```

but saw the flake only once so far.

**Comment by jbartosik** [comment]
In #2905 I just saw a failure with new [logs](https://travis-ci.org/kubernetes/autoscaler/jobs/660079355?utm_medium=notification&utm_source=github_status):

```
--- FAIL: TestGetPatchesForResourceRequest_TwoReplacementResources (0.00s)
    server_test.go:136: 
        	Error Trace:	server_test.go:136
        	            				server_test.go:410
        	Error:      	Should be true
        	Test:       	TestGetPatchesForResourceRequest_TwoReplacementResources
        	Messages:   	got {Op:add Path:/metadata/annotations/vpaUpdates Value:Pod resources updated by name: container 0: unobtanium request, cpu request}, want: {Op:add Path:/metadata/annotations/vpaUpdates Value:Pod resources updated by name: container 0: cpu request, unobtanium request}

```

**Comment by krzysied** [comment]
This bug is fixed, but I would like to add additional context for why it happened:
This problem is caused by https://github.com/kubernetes/autoscaler/blob/4317838e1971d7c7cda6649f96c68c5a1720f160/vertical-pod-autoscaler/pkg/admission-controller/logic/server.go#L168
Golang assumes that map can be iterated in any order. This makes our test result non-deterministic.
This was a problem regarding our test assumptions, not a vpa admission controller issue.
