### ISSUE TITLE
Scales up nodes unnecessarily as soon as node becomes available

### ISSUE THREAD

**Issue by ddseapy** [kubernetes/autoscaler#2894]
We are running autoscaler 1.16.3.

When an unschedulable pod gets created an ASG correctly gets it's size increased.  However as soon as the node is ready, the cluster autoscaler will scale out additional ASGs (it seems to be the number of ASGs we have - so 3 AZ/ASG spins up 2 unnecessary nodes, 2 AZ/ASG spins up 1 unnecessary nodes, and 1 AZ/ASG spins up 0 unnecessary nodes.

The logs seem to indicate that the pod is still unschedulable (presumably kubernetes hasn't updated yet), and the very next main loop there are no unschedulable pods since the pod has now started running.  After 10 minutes of being on, the unecessary nodes scale down.

**Comment by ddseapy** [comment]
tried both with and without `balance-similar-node-groups` but doesn't seem to matter.

maybe there is some setting to wait a bit after a node is available to check for unschedulable pods again?  Haven't tried increasing `scan-interval`, but that doesn't seem like the correct solution, even if it works.

**Comment by ddseapy** [comment]
turns out not related to ASG size.  gjtempleton  in slack said it may be a lag in labelling.  so far increasing `scan-interval` to 1 min has solved the problem.

I'm not sure if there is a better work-around though:
* up-to a 1 min delay in spinning up GPUs isn't ideal for some of our workfloads that care more about latency
* not yet sure if this simply decreases the likelyhood of it happening or completely eliminates the issue

**Comment by ddseapy** [comment]
Seems to still happen quite regularly :(

**Comment by wvivek** [comment]
Has this issue been fixed? Increasing the scanning interval does not look to be the idle solution.

**Comment by MaciekPytel** [comment]
This will happen with nodes that have GPUs unless you add a specific label to them: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#special-note-on-gpu-instances.
