### ISSUE TITLE
increase memory limit for CA

### ISSUE THREAD

**Issue by shimajiro1111** [kubernetes/autoscaler#2903]
I use autoscaler in production env. 
Thank you for giving great product & information.

Problem
cluster autoscaler is increasing memory usage.

cloud provider: AWS EKS
version:v1.13.7
confirmation: Datadog

Please help . Thank you.

**Comment by shimajiro1111** [comment]
![cluster-sutoscaler-leak](https://user-images.githubusercontent.com/38030876/76185597-00783500-6213-11ea-90cc-1a0783935c74.png)

**Comment by Jeffwan** [comment]
You'd better adjust your title to more descriptive words.. I thought you are asking to increase memory limit for CA

Can you share some logs for us to debug? I would be great to know your cluster size (No. of Nodes, Pods) If your pod size is growing as well.

**Comment by shimajiro1111** [comment]
@Jeffwan 
Thank you!

4-6 node(EC2:c5.2xlarge)
6 api-server(mcpu:5000 memory:7000)

**Comment by Jeffwan** [comment]
@shimajiro1111  How can you have 6 apiservers? I am actually confused here. By default we only provide 2 api-server instance. What's number of your pods?

**Comment by shimajiro1111** [comment]
@Jefftree 

CA server is 1 pod. Sorry, I thought that api-server is my application server(scala).

But I update ca version v1.13.7 -> v1.14.7, this memory leak is stoped.
so this issue close.

Thank you for helping.
