### ISSUE TITLE
AWS: How to add log level in log of cluster-autoscaler

### ISSUE THREAD

**Issue by kellyhyomin** [kubernetes/autoscaler#2913]
There is no level marking in the logs of the cluster-autoscaler on AWS EKS. 
![image](https://user-images.githubusercontent.com/29850624/76281616-f3257e00-62d8-11ea-8984-fe5701d4bf7c.png)
I want to mark log level like INFO, ERROR in log of cluster-autoscaler on AWS. Is there a way?

**Comment by Jeffwan** [comment]
You can set log level here. 

https://github.com/kubernetes/autoscaler/blob/a469c854ccf005e72cd2d9ed1bcc50fe39491ec0/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml#L151-L152

Which CA version are you using? Latest version uses klog and support log level

**Comment by kellyhyomin** [comment]
@Jeffwan 
Than you for your help.
The CA version I am using is 1.14.7.
Can I add log level if I change the number of v in the source you gave me?
When I changed it to 5, nothing changed.

**Comment by albertocsm** [comment]
same here
setting up `stderrthreshold` to `error` does not seem to produce the expected result
```
  - command:
    (...)
    - --cloud-provider=aws
    - --namespace=kube-system
    - --logtostderr=true
    - --stderrthreshold=error
    - --v=4
    image: k8s.gcr.io/cluster-autoscaler:v1.14.6

```

**Comment by kellyhyomin** [comment]
The issue was resolved after updating to the latest version.
