### ISSUE TITLE
Let the CAPI group be overridden and discover the preferred version

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#2932]
We are currently hardcoding the CAPI groups/version supported by the provider https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L41

We should make the group overridable via env variable and let the version be discovered via discovery client.

**Comment by enxebre** [comment]
@MaciekPytel would you please create a label for `area/provider/capi`, I don't have perms for that.

**Comment by MaciekPytel** [comment]
I created area/provider/cluster-api. Is that ok? I can rename if you prefer, but I think it's more clear compared to capi.

**Comment by enxebre** [comment]
thanks @MaciekPytel sgtm. I don't seem to have perms to add a label manually via GH UX. Is there any automation we can use for this? e.g:
/area provider/cluster-api

**Comment by MaciekPytel** [comment]
Apparently yes :)
Looking at bot code it seems to just match anything starting with "area/".
