### ISSUE TITLE
Create readme for CAPI provider

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#2933]
We should have a readme for CAPI provider https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi
similar to other providers https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws

We should include at minimum:
- How to use it.
- Limitations.
- Support level.
- Overall design.
- Roadmap.

**Comment by onesolpark** [comment]
I'm trying to test cluster autoscaler with cluster-api provider and it would be really nice have a readme on installation and etc.

**Comment by onesolpark** [comment]
@enxebre before the readme comes out is there a sample or a guide on how to use autoscaler with CAPI?

**Comment by enxebre** [comment]
>@enxebre before the readme comes out is there a sample or a guide on how to use autoscaler with CAPI?

Hey @onesolpark We'll include some docs with a quickstart guide so people can start to test this out and we can all collaborate here effectively. We plan to have something during the next week.

Meanwhile you can find me on kubernetes slack I'd be happy to help.

**Comment by elmiko** [comment]
hi @onesolpark i am working on a readme, should have a pr up early next week. i am also on kubernetes slack, happy to help =)
