### ISSUE TITLE
Autoscaler doesn't recognize instances as part of a node group

### ISSUE THREAD

**Issue by autarchprinceps** [kubernetes/autoscaler#2936]
We are using the cluster autoscaler on AWS. It worked once, but right now, it doesn't seem to recognize our nodes as part of any node group and is skipping them. Logs look like this:
```
1 static_autoscaler.go:366] Calculating unneeded nodes
1 utils.go:543] Skipping ip-10-0-1-104.eu-central-1.compute.internal - no node group config
```
And the same for all other nodes as well.
As I said, it worked with the same configuration for us, but for context. We have cluster autoscaler deployed via helm, currently in chart version 6.2.0, which installs app-version 1.14.6. This should be fairly current. Our AWS Nodegroups are setup using eksctl and running Kubernetes 1.15, they are tagged with k8s.io/cluster-autoscaler/_name_: owned (and k8s.io/cluster-autoscaler/enabled: "true"). An eksctl get nodegroups does still succeed
As values we have setup autoDiscovery.enabled true and .clusterName to the same name as our EKS is named, alongside cloudProvider aws. The logs do not otherwise look problematic or different from what we're used to.

**Comment by autarchprinceps** [comment]
Just verified, we have the same issue in one of our clusters still on Kubernetes 1.14, so its not tied to EKS just adding support for Kubernetes 1.15

**Comment by autarchprinceps** [comment]
What may be relevant, is we have a nodegroup for each AZ, but as I said, it did use to work, and with the same settings as well.

**Comment by autarchprinceps** [comment]
Tried updating to newest Helm Chart 7.1.0 as well as balance-similar-node-groups: true, but problem persists.

**Comment by autarchprinceps** [comment]
Tried updating to newest Helm Chart 7.1.0 as well as balance-similar-node-groups: true, but problem persists.

**Comment by JoaquinScript** [comment]
Same here with EKS 1.15 and chart v 7.2.0

**Comment by JoaquinScript** [comment]
it was my bad, I mistakenly add k8s labels instead of EC2 tags to the nodes.

**Comment by hendrikhalkow** [comment]
> Same here with latest chart: EKS 1.15, chart 7.2.0, CA 1.17.1 and with EKS 1.15, chart 7.0.0, CA 1.14.6. It appears there isn't a chart covering CA 1.15.x

When you combine CA 1.17.1 with EKS 1.15, I don't even get until that issue because the CSINode API group changed: `Failed to list *v1.CSINode: the server could not find the requested resource`

The documentation states that you need to use the same autoscaler minor version as your Kubernetes, means you need to run cluster autoscaler v1.15.6. However, I still get this issue using the latest chart (7.2.2) with the latest autoscaler:

```sh
$ helm get values cluster-autoscaler --namespace kube-system               
USER-SUPPLIED VALUES:
autoDiscovery:
  clusterName: xxx
cloudProvider: aws
image:
  repository: eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
  tag: v1.15.6
rbac:
  create: true
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ClusterAutoscaler-xxx
```

**Comment by ccampo133** [comment]
I'm also running into this same issue on Amazon EKS (k8s 1.14.9 and auto scaler version 1.14.6):

```
I0421 16:47:19.432967       1 static_autoscaler.go:138] Starting main loop
I0421 16:47:19.433139       1 utils.go:595] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0421 16:47:19.433151       1 static_autoscaler.go:294] Filtering out schedulables
I0421 16:47:19.433294       1 static_autoscaler.go:311] No schedulable pods
I0421 16:47:19.433311       1 static_autoscaler.go:319] No unschedulable pods
I0421 16:47:19.433322       1 static_autoscaler.go:366] Calculating unneeded nodes
I0421 16:47:19.433335       1 utils.go:543] Skipping ip-172-31-12-66.ec2.internal - no node group config
I0421 16:47:19.433344       1 utils.go:543] Skipping ip-172-31-11-148.ec2.internal - no node group config
I0421 16:47:19.433352       1 utils.go:543] Skipping ip-172-31-1-176.ec2.internal - no node group config
I0421 16:47:19.433360       1 utils.go:543] Skipping ip-172-31-2-26.ec2.internal - no node group config
I0421 16:47:19.433367       1 utils.go:543] Skipping ip-172-31-0-28.ec2.internal - no node group config
I0421 16:47:19.433374       1 utils.go:543] Skipping ip-172-31-12-231.ec2.internal - no node group config
I0421 16:47:19.433547       1 static_autoscaler.go:393] Scale down status: unneededOnly=false lastScaleUpTime=2020-04-21 15:46:09.809181357 +0000 UTC m=+17.819654332 lastScaleDownDeleteTime=2020-04-21 15:46:09.809181439 +0000 UTC m=+17.819654415 lastScaleDownFailTime=2020-04-21 15:46:09.809181535 +0000 UTC m=+17.819654509 scaleDownForbidden=false isDeleteInProgress=false
I0421 16:47:19.433604       1 static_autoscaler.go:403] Starting scale down
I0421 16:47:19.433651       1 scale_down.go:706] No candidates for scale down
I0421 16:47:20.523438       1 reflector.go:370] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:190: Watch close - *v1.Pod total 20 items received
```

**Comment by hendrikhalkow** [comment]
I just solved it for me: I forgot to set the AWS region. With the awsRegion parameter in my Helm values the combination above works fine.

**Comment by ccampo133** [comment]
Looking into this a big more, it appears that `fetchAutoAsgNames` in `auto_scaling_groups.go` may not be returning any values, which is strange. This would indicate to me that there's either an issue with the AWS API (e.g. IAM permissions), the autoscale tag is somehow misconfigured on the nodes themselves, or the AWS SDK is somehow returning empty results when filtering by tag key, somewhere in this function:

```go
func (m *autoScalingWrapper) getAutoscalingGroupNamesByTags(kvs map[string]string) ([]string, error) {
	// DescribeTags does an OR query when multiple filters on different tags are
	// specified. In other words, DescribeTags returns [asg1, asg1] for keys
	// [t1, t2] when there's only one asg tagged both t1 and t2.
	filters := []*autoscaling.Filter{}
	for key, value := range kvs {
		filter := &autoscaling.Filter{
			Name:   aws.String("key"),
			Values: []*string{aws.String(key)},
		}
		filters = append(filters, filter)
		if value != "" {
			filters = append(filters, &autoscaling.Filter{
				Name:   aws.String("value"),
				Values: []*string{aws.String(value)},
			})
		}
	}

	tags := []*autoscaling.TagDescription{}
	input := &autoscaling.DescribeTagsInput{
		Filters:    filters,
		MaxRecords: aws.Int64(maxRecordsReturnedByAPI),
	}
	if err := m.DescribeTagsPages(input, func(out *autoscaling.DescribeTagsOutput, _ bool) bool {
		tags = append(tags, out.Tags...)
		// We return true while we want to be called with the next page of
		// results, if any.
		return true
	}); err != nil {
		return nil, err
	}

	// According to how DescribeTags API works, the result contains ASGs which
	// not all but only subset of tags are associated. Explicitly select ASGs to
	// which all the tags are associated so that we won't end up calling
	// DescribeAutoScalingGroups API multiple times on an ASG.
	asgNames := []string{}
	asgNameOccurrences := make(map[string]int)
	for _, t := range tags {
		asgName := aws.StringValue(t.ResourceId)
		occurrences := asgNameOccurrences[asgName] + 1
		if occurrences >= len(kvs) {
			asgNames = append(asgNames, asgName)
		}
		asgNameOccurrences[asgName] = occurrences
	}

	return asgNames, nil
}
```

If this were an IAM issue I would expect to see an error in the logs, which I do not, so I'm a bit perplexed without any deeper way to debug this.

**Comment by skadem07** [comment]
I'm running into the same issue, My autoscaler has those tags, should my nodes (ec2-instances) also should have the tag?

**Comment by ccampo133** [comment]
@skadem07 try assigning them to the nodes, but ensure that the config on the k8s side matches the tags EXACTLY. Ensure the tags on the AWS side don't have any whitespace, etc.

**Comment by PhilThurston** [comment]
@Jeffwan this is still an issue and I see it was assigned to you.

**Comment by matti** [comment]
@PhilThurston what exactly is an issue? 

For example this comment in this thread "solved" this for me:

>I just solved it for me: I forgot to set the AWS region. With the awsRegion parameter in my Helm values the combination above works fine.

This cluster autoscaler is just kinda hard to get running right with these kind of shitty error messages

**Comment by PhilThurston** [comment]
@matti I'm unsure what exactly fixed it for us but I can give you a rundown.

We are using eksctl to deploy the cluster. We installed the autoscaler and it would only recognize a single node-group of our three total as something that could be scaled. We would get the exact same errors as above. I couldn't resolve the issue so I took a shot in the dark and recreated each node-group with just different names all other settings were the same. From that point on auto-scaler started scaling all three node-groups instead of just one and the error disappeared. 

Keep in mind that the original node-groups were made about 15m before the autoscaler was installed and were unmodified from how eksctl installed them. Somehow just adding fresh node-groups post install resolved the issue but that doesn't make much sense since nothing else besides the node group name changed.

**Comment by franklinoa** [comment]
In the case that you use EC2 Auto Scaling groups, you will need to add the following tags (replace example-cluster-name with the name of the cluster):

k8s.io/cluster-autoscaler/example-cluster-name owned Yes
k8s.io/cluster-autoscaler/enabled true Yes
![image](https://user-images.githubusercontent.com/48762803/103647250-48630800-4f5b-11eb-87ec-61cbe57f07aa.png)


If you use terraform add this to your aws_autoscaling_group config

resource "aws_autoscaling_group" "example-eks-nodes-" {
...
   tag {
     key = "k8s.io/cluster-autoscaler/example-cluster-name"
     value = "owned"
     propagate_at_launch = true
   }

   tag {
     key = "k8s.io/cluster-autoscaler/enabled"
     value = "true"
     propagate_at_launch = true
   }

I hope it helps. Regards.

**Comment by shinebayar-g** [comment]
> I just solved it for me: I forgot to set the AWS region. With the awsRegion parameter in my Helm values the combination above works fine.

Is that helm chart specific thing? I don't see that env is mentioned anywhere in [docs](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html#ca-deploy).

Our ec2 instances have correct tags 

```
k8s.io/cluster-autoscaler/my-cluster: owned
k8s.io/cluster-autoscaler/enabled: true
```

Still seeing exact same error.

```
I0316 13:47:31.499205       1 static_autoscaler.go:449] Calculating unneeded nodes
I0316 13:47:31.499215       1 pre_filtering_processor.go:57] Skipping ip-172-27-10-15.ec2.internal - no node group config
I0316 13:47:31.499223       1 pre_filtering_processor.go:57] Skipping ip-172-27-11-201.ec2.internal - no node group config
...
```

**Comment by MiguelLucas** [comment]
I'm seeing the exact same error as shinebayar-g, and the tags are set correctly, but can't figure out why this happens

**Comment by obenziane2** [comment]
Sucks! No one knows how to fix this.

**Comment by shinebayar-g** [comment]
To future readers here are some tips if you're on AWS. I'm using [cluster-autoscaler-autodiscover.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml) template.

1. Make sure your IAM role has correct permissions.
2. Make sure your EC2 **AutoScalingGroup** has necessary tags like `k8s.io/cluster-autoscaler/enabled = true, k8s.io/cluster-autoscaler/<cluster_name> = owned`. (If you're on EKS managed node group this is done by EKS.)
3. Make sure cluster autoscaler's `--node-group-auto-discovery` flag is correct. It should look like this (step 2's tags has to be matching)
`--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<cluster_name>`

**Comment by gotchipete** [comment]
This probably doesn't help, but I ran into this same issue when I used the helm chart for AWS (and verified that all the IAM permissions were present where they should be, and the tags were correct with no whitespaces)... ultimately when I installed myself with kubectl, following https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup ... it worked great!

**Comment by MartinEmrich** [comment]
I just had the same issue, and discovered this: #4934 

You might double-check the the Deployment generated by the Helm chart. If it renders an env: block with AWS_REGION, it should be the correct one. If no AWS_REGION env var is set, the IAM serviceaccount is used to detect the local region.

**Comment by seanfariacustomink** [comment]
Just solved this issue the AWS_region env var is case-sensitive. Make sure your cluster-autoscaler.yaml has the region in camel case: i.e. `awsRegion`
