### ISSUE TITLE
pods scheduled during taint DeletionCandidateOfClusterAutoscaler crash when node deleted

### ISSUE THREAD

**Issue by mvz27** [kubernetes/autoscaler#2967]
Gitlb-runner (kubernetes executer) with pod annotation safe-to-evict: false,
are STARTED on nodes after these nodes are marked for scale down  (during 10 minutes graceful period).
When nodes is actual deleted (after 10 minutes) these pods (gitlab-runner jobs) crash (are deleted).
Reproduced on AWS,EKS 1.14, cluster-autoscaler 1.14.5

**Comment by MaciekPytel** [comment]
Before draining the node CA marks it with a taint to prevent any new workload from being scheduled on that node (ie. prevent the exact problem you're describing). Is it possible that your pod have either toleration for CA taint or some wildcard toleration that allows it to schedule on those nodes?

**Comment by mvz27** [comment]
pod is created via gitlab-runner helm chart using tolerations: []
i do however use a node selector.

kubectl describe pod shows :
```
  Node-Selectors:  nodegroup-av=mixed_ab
  Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                  node.kubernetes.io/unreachable:NoExecute for 300s
```

**Comment by mvz27** [comment]
I "described" the node which was scaling down.
 First it is tainted with: 
```
Taints:             DeletionCandidateOfClusterAutoscaler=1585040698:PreferNoSchedule
After a couple of minutes i see also:
Taints:             ToBeDeletedByClusterAutoscaler=1585041300:NoSchedule
```
According to kubernetes documentation i can understand why pods get scheduled during the first couple of minutes (No other nodes available).

Is there a way to let gitlab-runner generate pods which do NOT run on nodes tainted with PreferNoSchedule ?

**Comment by mvz27** [comment]
Or better:

Is their a possibility to start a graceful period from moment of NoSchedule - taint  ?
My short CI-jobs will get time to finish that way.

**Comment by MaciekPytel** [comment]
Pod's gracefulTerminationSeconds only starts counting after pod is evicted (which happens after NoSchedule taint is added). By default gracefulTerminationSeconds only works for up to 10 minutes, but you can change it with --max-graceful-termination-sec flag.

That being said - PreferNoSchedule taint only means CA is considering deleting node, but it haven't decided yet. If a pod with safe-to-evict: false is scheduled on that node it should prevent scale-down. Are you sure that the annotation is correctly specified (should be: "cluster-autoscaler.kubernetes.io/safe-to-evict": "false")?

**Comment by mvz27** [comment]
>> Pod's gracefulTerminationSeconds only starts counting after pod is evicted (which happens after NoSchedule taint is added).

I doubt if this is the case.  Alsmost sure count starts from PrefereNoschedule !, But i will re-check.

>> "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
Yes i am sure. 
Set this in the gitlab-runner helm chart and checked via describe pod.

**Comment by mvz27** [comment]
09:04:58     1 delete.go:102] Successfully added DeletionCandidateTaint on node ...
09:15:00     1 delete.go:102] Successfully added ToBeDeletedTaint on node ...
09:00:01     AWS EKS Auto-scalegroup history shows node-scale down

I am missing something.  I used --max-graceful-termination-sec=1500
Still i see 10 minutes from moment of DeletionCandidateTaint (PreferShedule) !?

**Comment by MaciekPytel** [comment]
Those are 2 different things, that just happen to have the same default value:
 - CA only deletes node if it continuously matches criteria for deletion over some period (default: 10 minutes, controlled by --scale-down-unneeded-time).
 - Pod's gracefulTermination is the delay between sending SIGTERM and SIGKILL to the process (pod can use that time to clean up). This is set individually in each pod's spec, however, CA will only respect value up to a certain limit (by default 10 minutes, controlled by  --max-graceful-termination-sec).

Term gracefulTermination is generally understood as the latter.

**Comment by mvz27** [comment]
my gitlab-runner helmchart has terminationGracePeriodSeconds: 3600   
I do not see anything in the pod's spec.  Looking at the chart, i think this is written to the Deployment's spec.
Maybe Kubernetes only checks the Pod's spec and if missing terminationGracePeriodSeconds there, it defaults to 30 seconds.

**Comment by mvz27** [comment]
Gitlab runner helm chart has terminationGracePeriodSeconds: 3600.

But appearantly the deployed jobs by this runner have terminationGracePeriodSeconds : 0 

I think this is the cause !

**Comment by mvz27** [comment]
Fixed this via adding env var in helm chart:
```
envVars:
   - name: KUBERNETES_TERMINATIONGRACEPERIODSECONDS
     value: 900
```
Now build pods are annotated, so hope this fixes my problems.
(Although only question still is why annotation "cluster-autoscaler.kubernetes.io/safe-to-evict": "false" does not work)

**Comment by mlushpenko** [comment]
We have exactly the same issue (I think):

```
k8s 1.16.7
CA eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.16.5
```

The only difference, that for the crashing pods, they seem to be started just before the node deletion. Taint is supposedly respected, but not always (based on pods getting crashed sometimes):

```
I0518 13:50:17.580930       1 cluster.go:107] Fast evaluation: node ip-172-22-5-173.eu-central-1.compute.internal cannot be removed: gitlab/runner-asfgsthu-project-29-concurrent-4wdzbr is not replicated
I0518 13:55:18.757487       1 scale_down.go:468] Node ip-172-22-5-173.eu-central-1.compute.internal - cpu utilization 0.018750
I0518 13:55:18.758851       1 static_autoscaler.go:429] ip-172-22-5-173.eu-central-1.compute.internal is unneeded since 2020-05-18 13:55:18.599735531 +0000 UTC m=+1950669.051907841 duration 0s
I0518 13:55:18.759162       1 scale_down.go:724] ip-172-22-5-173.eu-central-1.compute.internal was unneeded for 0s
I0518 13:55:18.779244       1 delete.go:102] Successfully added DeletionCandidateTaint on node ip-172-22-5-173.eu-central-1.compute.internal
I0518 13:55:28.786559       1 scale_down.go:468] Node ip-172-22-5-173.eu-central-1.compute.internal - cpu utilization 0.018750
I0518 13:55:28.787603       1 static_autoscaler.go:429] ip-172-22-5-173.eu-central-1.compute.internal is unneeded since 2020-05-18 13:55:18.599735531 +0000 UTC m=+1950669.051907841 duration 10.184373488s
I0518 13:55:28.787735       1 scale_down.go:724] ip-172-22-5-173.eu-central-1.compute.internal was unneeded for 10.184373488s
I0518 13:55:38.793217       1 utils.go:467] Removing autoscaler soft taint when creating template from node ip-172-22-5-173.eu-central-1.compute.internal
I0518 13:55:38.795595       1 scale_down.go:468] Node ip-172-22-5-173.eu-central-1.compute.internal - cpu utilization 0.018750
I0518 13:55:38.795859       1 cluster.go:93] Fast evaluation: ip-172-22-5-173.eu-central-1.compute.internal for removal
I0518 13:55:38.795933       1 cluster.go:124] Fast evaluation: node ip-172-22-5-173.eu-central-1.compute.internal may be removed
I0518 13:55:38.796031       1 static_autoscaler.go:429] ip-172-22-5-173.eu-central-1.compute.internal is unneeded since 2020-05-18 13:55:18.599735531 +0000 UTC m=+1950669.051907841 duration 20.192842963s
I0518 13:55:38.796173       1 scale_down.go:724] ip-172-22-5-173.eu-central-1.compute.internal was unneeded for 20.192842963s
I0518 13:55:48.821325       1 pre_filtering_processor.go:66] Skipping ip-172-22-5-173.eu-central-1.compute.internal - node group min size reached
I0518 13:55:48.821887       1 delete.go:192] Releasing taint {Key:DeletionCandidateOfClusterAutoscaler Value:1589810118 Effect:PreferNoSchedule TimeAdded:<nil>} on node ip-172-22-5-173.eu-central-1.compute.internal
I0518 13:55:48.835566       1 delete.go:219] Successfully released DeletionCandidateTaint on node ip-172-22-5-173.eu-central-1.compute.internal
..............
I0518 13:58:59.615988       1 pre_filtering_processor.go:66] Skipping ip-172-22-5-173.eu-central-1.compute.internal - node group min size reached
I0518 13:59:01.333363       1 node_tree.go:113] Removed node "ip-172-22-5-173.eu-central-1.compute.internal" in group "eu-central-1:\x00:eu-central-1c" from NodeTree
```

I don't understand how node is skipped for a long time and the next second it is just deleted. Compared with some other nodes and on other nodes I can at least see `ToBeDeletedTaint` properly and autoscaler status configmap updates.

We will try `KUBERNETES_TERMINATIONGRACEPERIODSECONDS` env var, but something is still not looking good.

**Comment by dignajar** [comment]
@mlushpenko have you figure it out? I feel I have the same issue.

https://github.com/kubernetes/autoscaler/issues/3243

**Comment by mlushpenko** [comment]
I think @mvz27 fix did it for us.
