### ISSUE TITLE
In CA's code, AKS node's gpu label may be wrong.

### ISSUE THREAD

**Issue by ydye** [kubernetes/autoscaler#2987]
I found in the [source code](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_cloud_provider.go#L33) the GPU label of azure is ```"cloud.google.com/gke-accelerator"```. However in aks cluster, the label of node with GPU resource is  ```accelerator=nvidia```.

**Comment by marwanad** [comment]
hey @ydye good catch, the GPU label should be "accelerator" - would you like to open a PR for it?

**Comment by ydye** [comment]
Hi @marwanad , I have opened a PR to fix it. https://github.com/kubernetes/autoscaler/pull/3019

**Comment by feiskyer** [comment]
Thanks for reporting the issues.

/kind bug
/area provider/azure
