### ISSUE TITLE
Cluster Autoscaler releases 1.18.1, 1.17.2, 1.16.5, 1.15.6, 1.14.8

### ISSUE THREAD

**Issue by towca** [kubernetes/autoscaler#2988]
We plan to prepare a new set of Cluster Autoscaler patch releases on Monday, 2020-03-30. If you have any bugfix cherry-pick PRs you want included, please leave a comment here.

cc: @feiskyer, @Jeffwan, @ringtail, @hello2mao, @tghartland

**Comment by feiskyer** [comment]
@towca could you have a look at #2981?

**Comment by 2ZZ** [comment]
Hi @towca, please consider #2851

**Comment by marwanad** [comment]
@towca, can we get this in 1.14: https://github.com/kubernetes/autoscaler/pull/2957

**Comment by Jeffwan** [comment]
AWS backport list and I will also upgrade SDK version to support regional sts. Feel free to add more PRs. I will finish PR by Monday. 

#2462 
#2249 
#2737 
#2851 
#2929

**Comment by Jeffwan** [comment]
BTW, I would suggest to share release plan easier next time. If we will have a new release on Monday, and it's hard to find someone to approve PRs during the weekend

**Comment by towca** [comment]
#2981, #2851 and #2957 are merged and will be included.

@Jeffwan noted, sorry for that. Don't worry, we can push the release to Tuesday/Wednesday so you don't have to rush the approvals on the weekend.

**Comment by towca** [comment]
Since it appears everything mentioned is already approved and merged, I'm going forward with cutting the release today.

**Comment by Jeffwan** [comment]
@towca Can you check these two as well? 

It help to address #2829 

https://github.com/kubernetes/autoscaler/pull/3002
https://github.com/kubernetes/autoscaler/pull/3003

**Comment by towca** [comment]
The releases are out, thanks for the contributions!

* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.14.8
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.6
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.16.5
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.17.2
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.18.1
