### ISSUE TITLE
Eviction Rate Limiter on latest VPA releases

### ISSUE THREAD

**Issue by evnsio** [kubernetes/autoscaler#2996]
A colleague of mine contributed an eviction rate limiter back in October (#2326), and I've noticed while upgrading our VPA components that it's not in the latest 0.7 branch release.  Is there a plan to add this at some point?  We can continue running on a fork, but it'd be nice to be using the main releases if possible.

Original PR: https://github.com/kubernetes/autoscaler/pull/2326/files

Thanks.

**Comment by bskiba** [comment]
I've been inconsistent with the VPA releases over the last year, I apologise. I'll prepare a release in the next two weeks.

**Comment by evnsio** [comment]
Thank you 🙏

**Comment by bskiba** [comment]
I've started working on the release, currently testing it, will publish after that's finished

**Comment by bskiba** [comment]
https://github.com/kubernetes/k8s.io/pull/760 will promote images.

**Comment by bskiba** [comment]
Release created: https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.8.0
I am in progress of merging PRs to make sure deployment works as expected (see #3070)

/close
