### ISSUE TITLE
CAPI: Automation for deepcopy and audit internal types

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#3011]
Currently the deepcopy code for the internal CAPI types i.e machineSet and machineDeployment is harcoded here https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/zz_generated.deepcopy.go.
We need to: 
-Provide automation to generate the script.

-Auditing. For this there are two options:
1- Mirror the CAPI types into our internal types and fuzzy test round trips API server->unstructure->internal type -> unstructure.

2- Drop any field from the internal types which is not needed/supported in the autoscaler provider, gate on it and unit test those. This won't hide any issue for a developer trying to leverage a new field of the public CAPI types as this wouldn't exist in the internal types, therefore preventing golang from compiling.

**Comment by enxebre** [comment]
cc @JoelSpeed @elmiko

**Comment by benmoss** [comment]
Can we close this since we meregd https://github.com/kubernetes/autoscaler/pull/3312 ?

**Comment by elmiko** [comment]
certainly seems like we can to me.

plus, we can always re-open if need be ;)
/close
