### ISSUE TITLE
Cluster Autoscaler Version 1.15.6 doesn't respect log level

### ISSUE THREAD

**Issue by stafot** [kubernetes/autoscaler#3033]
Platform: `AWS EKS`
Kubernetes version: `1.15.10`
The issue is the following. 

**How to reproduce:** 

I used to have `cluster-autoscaler:v1.13.1`. 
I increased the log level from `info` to `error`. _Worked as expected._ 

Updated to `cluster-autoscaler:v1.15.6`.   _Stopped respecting the log level change._
My setup is the following.  
```
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=error
            - --cloud-provider=aws
```
Is something changed on flags so  `stderrthreshold` is not working anymore? 
Thanks for any clarification. 
I didn't find anything related on changelog or on documentation.

**Comment by voxmaster** [comment]
Same problem with cluster-autoscaler:**v1.14.6**

**Comment by kamsz** [comment]
This is still an issue.
