### ISSUE TITLE
after upgrading my EKS cluster from 14 to 15 version cluster is not scaling the nodes when load increase..

### ISSUE THREAD

**Issue by paramacharya** [kubernetes/autoscaler#3041]
after upgrading my EKS cluster from 14 to 15 version cluster is not scaling the nodes when load increase..

I0413 06:11:47.507386       1 static_autoscaler.go:412] Starting scale down
I0413 06:11:47.507426       1 scale_down.go:706] No candidates for scale down
I0413 06:11:57.520472       1 static_autoscaler.go:147] Starting main loop
I0413 06:11:57.603999       1 auto_scaling_groups.go:354] Regenerating instance to ASG map for ASGs: []
I0413 06:11:57.604025       1 aws_manager.go:263] Refreshed ASG list, next refresh after 2020-04-13 06:12:57.604021295 +0000 UTC m=+49071.312409868
I0413 06:11:57.604398       1 utils.go:626] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0413 06:11:57.604443       1 static_autoscaler.go:303] Filtering out schedulables
I0413 06:11:57.604578       1 static_autoscaler.go:320] No schedulable pods
I0413 06:11:57.604613       1 static_autoscaler.go:328] No unschedulable pods
I0413 06:11:57.604636       1 static_autoscaler.go:375] Calculating unneeded nodes
I0413 06:11:57.604650       1 utils.go:574] Skipping ip-192-168-13-133.us-east-2.compute.internal - no node group config
I0413 06:11:57.604661       1 utils.go:574] Skipping ip-192-168-154-48.us-east-2.compute.internal - no node group config
I0413 06:11:57.604669       1 utils.go:574] Skipping ip-192-168-95-73.us-east-2.compute.internal - no node group config
I0413 06:11:57.604700       1 utils.go:574] Skipping ip-192-168-81-229.us-east-2.compute.internal - no node group config
I0413 06:11:57.604852       1 static_autoscaler.go:402] Scale down status: unneededOnly=false lastScaleUpTime=2020-04-12 16:35:27.250488213 +0000 UTC m=+20.958876770 lastScaleDownDeleteTime=2020-04-12 16:35:27.250488317 +0000 UTC m=+20.958876875 lastScaleDownFailTime=2020-04-12 16:35:27.250488411 +0000 UTC m=+20.958876963 scaleDownForbidden=false isDeleteInProgress=false
I0413 06:11:57.604878       1 static_autoscaler.go:412] Starting scale down
I0413 06:11:57.604942       1 scale_down.go:706] No candidates for scale down
I0413 06:12:07.617629       1 static_autoscaler.go:147] Starting main loop
I0413 06:12:07.617749       1 utils.go:626] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0413 06:12:07.617761       1 static_autoscaler.go:303] Filtering out schedulables
I0413 06:12:07.617859       1 static_autoscaler.go:320] No schedulable pods
I0413 06:12:07.617876       1 static_autoscaler.go:328] No unschedulable pods
I0413 06:12:07.617888       1 static_autoscaler.go:375] Calculating unneeded nodes
I0413 06:12:07.617904       1 utils.go:574] Skipping ip-192-168-81-229.us-east-2.compute.internal - no node group config
I0413 06:12:07.617913       1 utils.go:574] Skipping ip-192-168-13-133.us-east-2.compute.internal - no node group config
I0413 06:12:07.618180       1 utils.go:574] Skipping ip-192-168-154-48.us-east-2.compute.internal - no node group config
I0413 06:12:07.618192       1 utils.go:574] Skipping ip-192-168-95-73.us-east-2.compute.internal - no node group config
I0413 06:12:07.618333       1 static_autoscaler.go:402] Scale down status: unneededOnly=false lastScaleUpTime=2020-04-12 16:35:27.250488213 +0000 UTC m=+20.958876770 lastScaleDownDeleteTime=2020-04-12 16:35:27.250488317 +0000 UTC m=+20.958876875 lastScaleDownFailTime=2020-04-12 16:35:27.250488411 +0000 UTC m=+20.958876963 scaleDownForbidden=false isDeleteInProgress=false
I0413 06:12:07.618364       1 static_autoscaler.go:412] Starting scale down
I0413 06:12:07.618421       1 scale_down.go:706] No candidates for scale down
I0413 06:12:17.631783       1 static_autoscaler.go:147] Starting main loop
I0413 06:12:17.631918       1 utils.go:626] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0413 06:12:17.631931       1 static_autoscaler.go:303] Filtering out schedulables
I0413 06:12:17.632032       1 static_autoscaler.go:320] No schedulable pods
I0413 06:12:17.632050       1 static_autoscaler.go:328] No unschedulable pods
I0413 06:12:17.632062       1 static_autoscaler.go:375] Calculating unneeded nodes
I0413 06:12:17.632074       1 utils.go:574] Skipping ip-192-168-81-229.us-east-2.compute.internal - no node group config
I0413 06:12:17.632083       1 utils.go:574] Skipping ip-192-168-13-133.us-east-2.compute.internal - no node group config
I0413 06:12:17.632091       1 utils.go:574] Skipping ip-192-168-154-48.us-east-2.compute.internal - no node group config
I0413 06:12:17.632099       1 utils.go:574] Skipping ip-192-168-95-73.us-east-2.compute.internal - no node group config
I0413 06:12:17.632255       1 static_autoscaler.go:402] Scale down status: unneededOnly=false lastScaleUpTime=2020-04-12 16:35:27.250488213 +0000 UTC m=+20.958876770 lastScaleDownDeleteTime=2020-04-12 16:35:27.250488317 +0000 UTC m=+20.958876875 lastScaleDownFailTime=2020-04-12 16:35:27.250488411 +0000 UTC m=+20.958876963 scaleDownForbidden=false isDeleteInProgress=false
I0413 06:12:17.632286       1 static_autoscaler.go:412] Starting scale down
I0413 06:12:17.632326       1 scale_down.go:706] No candidates for scale down
I0413 06:12:27.646622       1 static_autoscaler.go:147] Starting main loop
I0413 06:12:27.646749       1 utils.go:626] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0413 06:12:27.646761       1 static_autoscaler.go:303] Filtering out schedulables
I0413 06:12:27.646867       1 static_autoscaler.go:320] No schedulable pods
I0413 06:12:27.646896       1 static_autoscaler.go:328] No unschedulable pods
I0413 06:12:27.646907       1 static_autoscaler.go:375] Calculating unneeded nodes
I0413 06:12:27.646920       1 utils.go:574] Skipping ip-192-168-81-229.us-east-2.compute.internal - no node group config
I0413 06:12:27.646929       1 utils.go:574] Skipping ip-192-168-13-133.us-east-2.compute.internal - no node group config
I0413 06:12:27.646936       1 utils.go:574] Skipping ip-192-168-154-48.us-east-2.compute.internal - no node group config
I0413 06:12:27.646943       1 utils.go:574] Skipping ip-192-168-95-73.us-east-2.compute.internal - no node group config
I0413 06:12:27.647080       1 static_autoscaler.go:402] Scale down status: unneededOnly=false lastScaleUpTime=2020-04-12 16:35:27.250488213 +0000 UTC m=+20.958876770 lastScaleDownDeleteTime=2020-04-12 16:35:27.250488317 +0000 UTC m=+20.958876875 lastScaleDownFailTime=2020-04-12 16:35:27.250488411 +0000 UTC m=+20.958876963 scaleDownForbidden=false isDeleteInProgress=false
I0413 06:12:27.647177       1 static_autoscaler.go:412] Starting scale down
I0413 06:12:27.647215       1 scale_down.go:706] No candidates for scale down
I0413 06:12:30.163304       1 reflector.go:370] k8s.io/client-go/informers/factory.go:132: Watch close - *v1beta1.PodDisruptionBudget total 0 items received
I0413 06:12:31.159457       1 reflector.go:370] k8s.io/client-go/informers/factory.go:132: Watch close - *v1.Node total 36 items received

**Comment by Jeffwan** [comment]
/assign @Jeffwan 

```
I0413 06:12:17.632099 1 utils.go:574] Skipping ip-192-168-95-73.us-east-2.compute.internal - no node group config
``

duplicate issue. https://github.com/kubernetes/autoscaler/issues/2936

**Comment by ccampo133** [comment]
@paramacharya ensure that the tags specified in the `--node-group-auto-discovery` match the actual tags on the ASG(s) in question.
