### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by bradleyd** [kubernetes/autoscaler#3044]
We are running CA 1.15.5 with k8s 1.15.7. We are seeing memory gradually grow over time. We have the limits set to 1G but it will eventually reach that in about a day then get oom'd.

<img width="2546" alt="Screen Shot 2020-04-13 at 2 07 10 PM" src="https://user-images.githubusercontent.com/151280/79164624-aaad2480-7d9e-11ea-85ce-173362fc62fd.png">

Here is our config in the deployment

```
 44       - command:
 45         - ./cluster-autoscaler
 46         - --v=4
 47         - --stderrthreshold=info
 48         - --cloud-provider=aws
 49         - --skip-nodes-with-local-storage=false
 50         - --balance-similar-node-groups
 51         - --expander=random
 52         - --nodes=5:20:nodes-us-west-2b.cluster.foo.com
 53         - --nodes=5:20:nodes-us-west-2c.cluster.foo.com
 54         - --nodes=5:20:nodes-us-west-2d.cluster.foo.com
 55         - --nodes=1:18:pgpool-nodes.cluster.foo.com
 56         - --nodes=2:16:postgres-nodes.cluster.foo.com
 57         - --nodes=1:4:api-nodes-us-west-2b.cluster.foo.com
 58         - --nodes=1:4:api-nodes-us-west-2c.cluster.foo.com
 59         - --nodes=1:4:api-nodes-us-west-2d.cluster.foo.com
 60         - --nodes=0:5:cicd-nodes-us-west-2b.cluster.foo.com
 61         - --nodes=0:5:cicd-nodes-us-west-2c.cluster.foo.com
 62         - --nodes=0:5:cicd-nodes-us-west-2d.cluster.foo.com
 63         - --nodes=0:5:haproxy-nodes-us-west-2b.cluster.foo.com
 64         - --nodes=0:5:haproxy-nodes-us-west-2c.cluster.foo.com
 65         - --nodes=0:5:haproxy-nodes-us-west-2d.cluster.foo.com
 66         env:
 67         - name: AWS_REGION
 68           value: us-west-2
 69         image: k8s.gcr.io/cluster-autoscaler:v1.15.5
 70         imagePullPolicy: Always
 71         name: cluster-autoscaler
 72         resources:
 73           limits:
 74             cpu: 100m
 75             memory: 1Gi
 76           requests:
 77             cpu: 100m
 78             memory: 500Mi
```

Any thoughts?

**Comment by marwanad** [comment]
curious about the workload you're running? How many pods are running and the number of pending pods you see during those spikes?

**Comment by bradleyd** [comment]
@marwanad thanks for responding. Those spikes take about a day to manifest. We have a pretty steady workflow so about 700+ pods up to 1900 if you count cron jobs.

**Comment by marwanad** [comment]
@bradleyd interesting, I've hit weird memory behaviour with the increasing number of unschedulable pods (as logged inCA). In most cases, around 3k pods or so would hit anywhere between 500-700Mi. Haven't got to running pprof yet.

From what @MaciekPytel mentioned on Slack, it seems like this is not unexpected given that watches cache all nodes and pods in memory.

**Comment by MaciekPytel** [comment]
I would definitely expect CA memory to grow with cluster size (#pods, #nodes and especially #ASGs), but the number of pods mentioned is not that large, this seems like more memory than I'd expect. Note that I only run clusters in GCP/GKE, so my intuition may be way off for memory use of AWS provider.

**Comment by bradleyd** [comment]
@MaciekPytel that was my thoughts too. I get that memory will grow in proportion to the cluster size, but this seems like a lot &trade;

**Comment by marwanad** [comment]
@bradleyd do you have pods using affinity/anti-affinity rules by any chance? I ran a quick pprof and it seems that `MatchInterPodAffinity` predicate has some heavy footprint.

**Comment by bradleyd** [comment]
<img width="2923" alt="image" src="https://user-images.githubusercontent.com/151280/79472891-a0b73b80-7fc1-11ea-8e53-f159a322aee8.png">

Here is the change (after an oom). Two days went 400MB to over 900MB. This seems a lot like bloat or a leak to me.

**Comment by srspnda** [comment]
I'm seeing the same issue on a 6 node cluster, Amazon EKS v1.15, k8s.gcr.io/cluster-autoscaler:v1.15.5. CA runs into the memory limit, runs out of memory, and is then restarted. Looks like this behavior is on a ~7d schedule.

**Comment by stefansedich** [comment]
We just upgraded to 1.15.6 from 1.14.x and CA was OOMing on startup based on our requests and limits we had previously set, had to significantly increase these to get CA to start up.

Has anything changed to greatly increase the memory footprint?

**Comment by nitrag** [comment]
30-40 pods, 10-15 nodes (another 15 terminated nodes). AWS. `cluster-autoscaler` is using 800mb+ of memory.

My other two clusters which have 6-8 nodes use only 200mb.

**Comment by nitrag** [comment]
I have another cluster with 100+ pods, 20+ nodes where `cluster-autoscaler` uses <200mb, running 1.14.6.

**Comment by infa-ddeore** [comment]
any updates on this? `1.15.7` CA is getting killed by k8 due to high memory usage.
CA reached to 1.3G memory utilisation with cluster of ~80 nodes but was killed by k8 

so the option we tried is `--aws-use-static-instance-list=true` and now the memory utilisation dropped down to ~250MB

there is no issue with 1.14 CA

**Comment by MaciekPytel** [comment]
@Jeffwan @jaypipes Based on comments above this seems like it may be a memory leak in AWS provider.

**Comment by nitrag** [comment]
> so the option we tried is --aws-use-static-instance-list=true (Should CA fetch instance types in runtime or use a static list. AWS only) and now the memory utilisation dropped down to ~250MB 

I tried @infa-ddeore suggestion of static instance list. On my two clusters with minimal load I get average around 250mb before/after. On my production cluster memory was ~650-750mb past few days but after enabling static instance list it jumped to 950mb.

**Comment by nitrag** [comment]
Well now after reverting it starts at 500mb and within 15 seconds it climbs to 950mb before k8s kills it for exceeding memory requests. HELP!

**Comment by jaypipes** [comment]
> any updates on this? `1.15.7` CA is getting killed by k8 due to high memory usage.
> CA reached to 1.3G memory utilisation with cluster of ~80 nodes but was killed by k8
> 
> so the option we tried is `--aws-use-static-instance-list=true` (Should CA fetch instance types in runtime or use a static list. AWS only) and now the memory utilisation dropped down to ~250MB
> 
> there is no issue with 1.14 CA

I'm going to have to bisect to see what changed between the 1.14 and 1.15 CAS w/AWS release. At this point, I'm just not sure; I didn't think there were many changes actually to the AWS-specific code between 1.14 and 1.15.

**Comment by varunpalekar** [comment]
We are also getting a similar issue, in starting memory will go high around 1 GB but after 5 min it's 100 MB only.

cluster autoscaler image: tried both `1.15.6` and `1.15.7`
k8s version: `v1.15.10`
cloud-provider: `aws`
Cluster Size: `approx 40 nodes`

**Comment by nitrag** [comment]
`--aws-use-static-instance-list=true`
Didn't help us.

Holy crap. `Container aws-cluster-autoscaler was using 1149444Ki, which exceeds its request of 900Mi.` 
@jaypipes I'm going to reach out to you via email so we can troubleshoot this 1:1.

**Comment by nitrag** [comment]
I upgraded cluster-autoscaler to 1.16.7 (from 1.15.7) and the memory 1min after boot is 375MiB. Will continue to monitor.

Simultaneously I was removing 55k completed Batch Jobs (cronjobs) that were just lingering on the API server as complete. Anyone else with this issue have similar latent storage? `kubectl get jobs --all-namespaces`

**Comment by seamusabshere** [comment]
```
--aws-use-static-instance-list=true
```

this does not fix it.

```
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 09 Dec 2020 09:41:39 -0500
      Finished:     Wed, 09 Dec 2020 09:43:50 -0500
    Ready:          True
    Restart Count:  1
    Limits:
      memory:  6Gi
```

**Comment by nitrag** [comment]
I'd like to point out an observation. We just upgraded the last of our production clusters last Friday (-4 days) and I noticed something:

EKS Upgrade to 1.18.
Cluster-Autoscaler to 1.17.4.
 
Memory usage for the entire weekend, pod reboots, different nodes, latest AMI, etc....`aws-cluster-autoscaler` and 30 seconds it would scale up to **1.6GB MEM USAGE via `docker stats`.**
 
Looking at our logs we noticed a logs we had not seen before:
 ```
 I0515 13:23:27.351494       1 trace.go:116] Trace[1286906120]: "Reflector ListAndWatch" name:k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:328 (started: 2021-05-15 13:23:13.91257067 +0000 UTC m=+37587.395469158) (total time: 13.43885801s):
Trace[1286906120]: [13.283242498s] [13.283242498s] Objects listed
Trace[1286906120]: [13.283243098s] [600ns] Resource version extracted
Trace[1286906120]: [13.330326445s] [47.083347ms] Objects extracted
Trace[1286906120]: [13.43885412s] [108.527675ms] SyncWith done
Trace[1286906120]: [13.43885526s] [1.14µs] Resource version updated
Trace[1286906120]: [13.43885801s] [2.75µs] END
```

This led me to investigate how large our job history was (because EKS does not clean up Jobs once they complete! you should enable this AWS team, I think it's the TTL variables)

`kubectl get jobs --all-namespaces | wc -`

answer: **83339**

Eighty thousand!

It took me 2+ days to clean these up. I had to write a python program to do it via Kube API. 

It's now down to a reasonable 4500 (I programmed it to keep -15 day history).

Fast forward to today: I checked `aws-cluster-autoscaler` pod today and it was still 1.6GB of memory usage (`docker stats`)... I deleted the pod. It re-provisioned the new pod on the same node and **it has been running for 30+min at 330MB. WOW!**

@jaypipes

**Comment by edgan** [comment]
I just saw this with `Cluster Autoscaler 1.20.0`. It is a jenkins/kube master running in AWS with an ASG. Two pods, jenkins slave agents, run jenkins jobs every half hour. So 2 jobs * 24 hours * 2(half hour) = 96 jobs daily. The instance in the ASG is fairly static given the frequency of the jenkins jobs. 

The cluster-autoscaler is installed via helm, and had been running for about 15 days.

The pod had no resource limits, which I am fixing now. But this will just cause it to be auto-restarted. It did out of memory the host.

    kernel: Out of memory: Killed process 2056769 (cluster-autosca) total-vm:1340256kB, anon-rss:383832kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:992kB oom_score_adj:1000
    1340256kb / 1024 / 1024 = 1.27816772460937500000gb
    
    The instance is a m5.large with 7749mb.

**Comment by xavipanda** [comment]
There is a leak for sure. we got OOMK at 1G limit...
our older version of autoscaler was fine, avg 250m~

**Comment by fblgit** [comment]
same here, using AWS. there is no way this could justify 1G of consumption...

there is a leak. it's related to the provider AWS. It can be reproduced with multiples ASG's, multiple nodes on each, and add/delete ASG's: nodes in and nodes out contribute to the effect.

Unfortunately, to reproduce and eventually fix this..u have to spend a reasonable amount of $ in AWS.

**Comment by jaredhancock31** [comment]
Any updates on this? Or any established workarounds for large clusters?

**Comment by dalvarezquiroga** [comment]
I think there is an issue with same problem described here: 

https://github.com/kubernetes/autoscaler/issues/3506

It looks like that is fixed with new version of Cluster Autoscaler.

Some message users:
**I've deployed v1.22.1** into a cluster which was previously seeing an oomkill with a memory limit of 300Mi. It's fixed the problem for us.
