### ISSUE TITLE
Need some advice on aws autoscaler to select different machine types

### ISSUE THREAD

**Issue by anupash147** [kubernetes/autoscaler#3058]
Hello Everyone greetings,

I am here reaching out to the community to solve a problem that i am unable to address.
So what i have done so far.
- I have an EKS cluster version 1.15 with stable/cluster-autoscaler 7.1.0 cloudprovider=aws and autodiscover mode for ASG, I have this working and autoscaling also works good.
- my ASG group has 10% on demand base and 90% spot. The ASG is a mixed mode instance model all fall under a common CPU & memory group.

What is the problem
- For most general cases the autoscaling creates pod but when machine learning use cases come to picture which needs variety of cpu/memory i have to consider below options
+ have different autoscaling groups with different memory requirement that can be invoked via taints and tolerants
+ manually change the autoscaling group to higher type of instances each time i have to work with large instances.
Both of the above cases defeat the purpose of automation. Kindly make suggestion for how do i have or configure AWS asg so that my autoscaler can query based on memory / cpu and get the most desired instances..

**Comment by anupash147** [comment]
@Jeffwan : any thoughts?

**Comment by Jeffwan** [comment]
> have different autoscaling groups with different memory requirement that can be invoked via taints and tolerants

Do you need manually work here?

> manually change the autoscaling group to higher type of instances each time i have to work with large instances.

I don't quite understand this, you are supposed to have multiple groups right? 


Can you explain more details on the real world cases for `query based on memory / cpu and get the most desired instances` Does current expander work for you or not?

**Comment by anupash147** [comment]
@Jeffwan : Thanks for taking a look. Right now am using different autoscaling for different memory group but it is turning out to be a nightmare. The possibilities and requests are getting multiplied. 

So to give you a real life example is using GPU machines, Some training take 1-4 GPU so i call in a autoscaling group of 4 GPU but only see 1 getting used but since user tolerated it autoscaling gives it. On another occassion some one wants 8 GPU's and i send them to a larger group that has 8 GPU's this is the same problem back in olden days when you had to remember IPS for websites. Manually selecting the autoscaling group by Datascientists is a pain. What is my ask is if we can have some options where based on machine / job / GPU requirement like below
![image](https://user-images.githubusercontent.com/8271182/81993487-64501d00-960b-11ea-9f9a-391c58b004c9.png)
we can select machines from the autoscaling group

**Comment by Jeffwan** [comment]
@anupash147 

> Some training take 1-4 GPU so i call in a autoscaling group of 4 GPU. On another occassion some one wants 8 GPU's and i send them to a larger group that has 8 GPU's.So for each groups i have to make a separate ASG;

Em.. We do suggest this way, That's the most cost efficient way to use GPU node groups. 


> What is my ask is if we can have some options where based on machine / job / GPU requirement, we can select machines from the autoscaling group.

Do you mean from one ASG or multiple? One ASG only support Mixed Instance Group but there's no guarantee what nodes comes out, this is a known problem. That's why we alway put instances with same specs (cpu, memory) in one goup. GPU doesn't work well in this case.

If you mean multiple ASGs, I think 2 ASGs with 4 or 8 GPUs will be scale up candidates for your pending pods. If you use least-waste expander, it should find ASG with 4 GPUs if pod request 4.  If you have a pod request 8 gpu, it will only scale up ASG with 8 because 4 won't fit. 

Is it not good enough for your case?

**Comment by anupash147** [comment]
I am satisfied with your answer, just wanted to confirm if my observations and learning are same 
seems like there is no better answer as we cannot get mixed cpu / memory instances

**Comment by Jeffwan** [comment]
@anupash147 Thanks for sharing your observations and it's helpful for us to understand your use case. As we don't have control on the instance type ASG bring to us, currently, there's no perfect solution on MixedInstacnePolicy support in one ASG.  

Please let us know if you meet other GPU problems and I'd love to help.
