### ISSUE TITLE
allow vpa recommender to be run as namespace scoped

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes/autoscaler#3062]
I would like to deploy the recommender per namespace, this should be configurable.

some things seem to be configured to be expecting clusterScoped privileges: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L170

**Comment by yashbhutwala** [comment]
I see PR #3049 !! thanks @povilasv 😄

**Comment by bskiba** [comment]
Fixed by #3227
