### ISSUE TITLE
vpa and vpacheckpoint CRDs have KubernetesAPIApprovalPolicyConformant condition from MissingAnnotation

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/autoscaler#3069]
The CRDs for `vpa` and `vpacheckpoint` are missing annotations referring to their API review, which is causing the CRDs to have the condition `KubernetesAPIApprovalPolicyConformant` set to `false` with a reason of `MissingAnnotation`.

```
$ kubectl get crd verticalpodautoscalers.autoscaling.k8s.io -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  ..............8<...snip...8<........................
spec:
  ..............8<...snip...8<........................
status:
  acceptedNames:
    ..............8<...snip...8<........................
  conditions:
  - lastTransitionTime: "2020-04-16T06:49:00Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
```

You'll get similar output from `kubectl get crd verticalpodautoscalercheckpoints.autoscaling.k8s.io`

According to https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190612-crd-group-protection.md (which was created by the https://github.com/kubernetes/enhancements/pull/1111 PR referenced in the condition) an API review is required for these CRDs.

I spoke with @deads2k who said that if we have already done an API review, we just need to add the annotation to the CRD metadata with a link to the PR where the review was performed, but if we haven't, the API would need to get an API review and approval from the API team. Another option is to move the CRDs to groups to `x-8s.io`.

**Comment by bskiba** [comment]
Thanks Joel
FTR - I think currently you can use following annotation to suppress the working.
```
 annotations:
    "api-approved.kubernetes.io": "unapproved.*"
```

I will proceed on getting the approval, since we have performed review of this API quite some time ago.

**Comment by bskiba** [comment]
The relevant pr with API review is here: https://github.com/kubernetes/kubernetes/pull/63797
There was also extensive discussion on the initial design proposal: https://github.com/kubernetes/community/pull/338
