### ISSUE TITLE
VPA: different architecture support

### ISSUE THREAD

**Issue by povilasv** [kubernetes/autoscaler#3074]
It would be amazing if we could add `amd64`, `arm`, `arm64`, `ppc64le`, `s390x` support.

Multiple kubernetes projects has started adding that support. For example `metrics-server`:

https://github.com/kubernetes-sigs/metrics-server/commit/d0bc9eb4b869a7db280a1cde6066cda4245ac58a

Roughly we could add:
```
ALL_ARCHITECTURES=amd64 arm arm64 ppc64le s390x
export DOCKER_CLI_EXPERIMENTAL=enabled

.PHONY: push-multi-arch
push-multi-arch:
	docker manifest create --amend $(REGISTRY)/metrics-server:$(GIT_TAG) $(shell echo $(ALL_ARCHITECTURES) | sed -e "s~[^ ]*~$(REGISTRY)/metrics-server\-&:$(GIT_TAG)~g")
	@for arch in $(ALL_ARCHITECTURES); do docker manifest annotate --arch $${arch} $(REGISTRY)/metrics-server:$(GIT_TAG) $(REGISTRY)/metrics-server-$${arch}:${GIT_TAG}; done
	docker manifest push --purge $(REGISTRY)/metrics-server:$(GIT_TAG)

```

Work plan change make files:

- https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/Makefile
- https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/Makefile
- https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Makefile
- 

When I did similiar change for https://github.com/povilasv/systemd_exporter, I first had to create multiple empty repos in quay:

- https://quay.io/repository/povilasv/systemd-exporter-linux-ppc64le
- https://quay.io/repository/povilasv/systemd-exporter-linux-arm64
- https://quay.io/repository/povilasv/systemd-exporter-linux-amd64

So not sure whats needed from google container registry.

The change is a bit risky as it might break the build. This happened when I did the change and I think same thing happened metrics-server did the change.

FYI I have a running arm/arm64 cluster where I can test the changes.

What do you think? If VPA changes are successfully I could find some time to do cluster-autoscaler changes too.

**Comment by bskiba** [comment]
If there is need for multi-arch support, then we'll gladly accept pull requests.
I think there should not be issues with google container registry for this.

For Cluster Autoscaler @MaciekPytel can let you know if they'd like support for multiple architectures there as well.

**Comment by povilasv** [comment]
Anyone has time to take a look :eyes:  at https://github.com/kubernetes/autoscaler/pull/3123 PR? :bow:
