### ISSUE TITLE
Cluster Autoscaler 1.15.6 AWS has problem with start in region cn-northwest-1

### ISSUE THREAD

**Issue by fradee** [kubernetes/autoscaler#3076]
After update version to 1.15.6 on clusters in China region cn-northwest-1 (is present change **Load AWS EC2 Instance Types dynamically**)
I've got error:

> W0421 13:07:06.686353       1 aws_util.go:86] Error unmarshalling https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/cn-northwest-1/index.json, skip...
> F0421 13:07:06.686381       1 aws_cloud_provider.go:366] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

But after set parameter **aws-use-static-instance-list** in _true_ CA start in normal state

**Comment by fradee** [comment]
It seems in China is not present pricing service, so the link does not work
`https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/{offer_code}/current/index.{format}`
@Jeffwan ^^^^

**Comment by Jeffwan** [comment]
@fradee Thanks for reporting the issue. Em. That could be a problem. Let me run some tests and see how to improve for this case

**Comment by gjtempleton** [comment]
Looks related to the existing issue #2696 which I have (still) failed to do the required work to move away to the `DescribeInstanceTypes` API.

**Comment by marians** [comment]
This looks like what we encounter in `cn-north-1` with cluster-autoscaler v1.16.5:

```
W0525 11:38:00.735889       1 aws_util.go:86] Error unmarshalling https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/cn-north-1/index.json, skip...
F0525 11:38:00.735910       1 aws_cloud_provider.go:363] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list
```

**Comment by Jeffwan** [comment]
@marians 

Please use this in cn region. https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#use-static-instance-list

Seems pricing API is not available there. We probably can have some improvement on fall back.

**Comment by marians** [comment]
@Jeffwan Yep, that's what we are doing.

**Comment by jordan-huangwei** [comment]
> @marians
> 
> Please use this in cn region. https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#use-static-instance-list
> 
> Seems pricing API is not available there. We probably can have some improvement on fall back.

cn pricing api is https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/cn/index.json

**Comment by jordan-huangwei** [comment]
> It seems in China is not present pricing service, so the link does not work
> `https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/{offer_code}/current/index.{format}`
> @Jeffwan ^^^^

https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/cn/index.json

**Comment by Jeffwan** [comment]
I approve PR https://github.com/kubernetes/autoscaler/pull/3528. I will do a cherry-pick for next release
