### ISSUE TITLE
[VPA] Scale up and down paused

### ISSUE THREAD

**Issue by shubhambadkur** [kubernetes/autoscaler#3077]
Hi folks, 

We started using vertical pod autoscalers so that our pods can scale up and down during peak and off peak hours. But looks like VPA is not scaling down the pods attaching the CPU and memory usage of pods in last 24 hours. We have metrics showing usage, request and limit in last 24 hours.  
![image](https://user-images.githubusercontent.com/42832137/79937727-415b9e80-848d-11ea-8520-afe016580216.png)

We use vpa with auto update mode 

```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "App.fullname" . }}-vpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{ template "common.labels" . }}
  annotations:
    {{ template "common.annotations" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       {{ template "App.fullname" . }}
  updatePolicy:
    updateMode: Auto
```

**Comment by shubhambadkur** [comment]
We are using EKS version 1.12 for our cluster and VPA version **0.70**

**Comment by shubhambadkur** [comment]
As of 22/04/2020 12:25 PM GMT +8. I dont see any new recommendation coming.
![image](https://user-images.githubusercontent.com/42832137/79940488-76b7ba80-8494-11ea-9707-6f16c6b14e0f.png)

**Comment by bskiba** [comment]
VPA in its current implementation is targeted more towards improving reliability than cost saving. It provisions for memory peak, so scale downs for memory may take days to happen. For CPU it roughly targets a request that will be higher than usage for 85 percent of time (it's a bit of a simplification but I think it's good enough to describe what VPA does).
VPA tries more to detect trends (hence looks at 8 days of historical usage) than to follow usage closely. This is especially important as every resize means a pod restart.

**Comment by shubhambadkur** [comment]
@bskiba understood though 85% of CPU is creating some problems for us. Whenever we deploy application to kubernetes the app upstart sometimes takes more resources then app usually takes during regular functioning. Since our applications are written in golang and usually upstart involves init of lot of sdks and modules hence the pods seems to be very slow even stuck in crashloop during upstart. Now vpa would optimise the resources over the period of time considering steady utilisation.

**Comment by shubhambadkur** [comment]
Also @bskiba can I keep this value as 75% or configure it at our end. Our load across all the replicaset of the deployment is not balanced hence we would like to keep 70-75% as the avg cpu utilisation

**Comment by bskiba** [comment]
We are aware of the issue with hot startup, but we don't have a good answer for it as of now unfortunately. It's especially difficult as we don't have in-place pod resizes in Kubernetes - to cover the initialisation phase we would have to recommend a cpu request big enough to cover initialisation, which will be wasteful later.

If your issue is with not enough resources at startup, why would you want to lower the targeted percentile? If you lowered it to 75th percentile, it would effectively mean a lower recommendation and a lower request, causing the issues on startup to be even worse.

**Comment by bskiba** [comment]
Not a lot of activity, so I'll close the issue, but please reopen if more discussion is needed.

**Comment by monotek** [comment]
We run in the same issue.
We now have pods which were upscaled during load spikes by vpa to memory resource requests of 4.7GB but memory usage is now only about 400mb :/

**Comment by monotek** [comment]
We solved it by adding an additional faster recommender and adjusting the updater via
"--in-recommendation-bounds-eviction-lifetime-threshold=2h"

**Comment by Gilk260** [comment]
@monotek 
Hello, can you be a little bit more explicit about what you have changed?

**Comment by owseaman** [comment]
@Gilk260, this should help.
https://github.com/kubernetes/autoscaler/issues/3077
