### ISSUE TITLE
[VPA] Incorrect OOM handling

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#3078]
It often happens that OOM memory values are not recorder.
In logs there are many entries like:

W0421 16:47:20.131118       1 cluster_feeder.go:406] Failed to record OOM {Timestamp:2020-04-21 16:46:24 +0000 UTC Memory:476450463 ContainerID:{PodID:{Namespace:vertical-pod-autoscaling-4228 PodName:hamster-6ddf9fb54d-wzzzd} ContainerName:hamster}}. Reason: error while recording OOM for {{vertical-pod-autoscaling-4228 hamster-6ddf9fb54d-wzzzd} hamster}, Reason: adding OOM sample failed

**Comment by krzysied** [comment]
Based on extensive debugging and deep code analysis I found following logic assumptions:
- OOM are treated as metric samples
https://github.com/kubernetes/autoscaler/blob/40d5205c1035bde49f7761bd30196e8bcbddb1df/vertical-pod-autoscaler/pkg/recommender/model/container.go#L206
- If sample is older that the newest processed one, the sample skipped
https://github.com/kubernetes/autoscaler/blob/40d5205c1035bde49f7761bd30196e8bcbddb1df/vertical-pod-autoscaler/pkg/recommender/model/container.go#L137-L139
- Metrics are processed before OOMs
https://github.com/kubernetes/autoscaler/blob/40d5205c1035bde49f7761bd30196e8bcbddb1df/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L377-L413

**Comment by krzysied** [comment]
The problematic scenario looks like:
- There is OOM at 00:00:44
- We have metric sample from 00:00:00 till 00:00:45
- Metrics are not as precise as OOM values.

Recommender will process metrics, setting lastMemorySampleStart to 00:00:45. It will process OOM after metrics. OOM sample will be skipped due to its measurement time being before lastMemorySampleStart.

This results with lower memory value being stored.

Moreover there is always a chance for this unwanted behavior, so there can exist a scenario where memory is never correctly bumped up.

**Comment by krzysied** [comment]
Quick update on the impact of the change:
- We are not loosing OOM memory samples. This allows VPA to achieve correct memory recommendation a few cycles (minutes) faster.
- VPA has more deterministic behavior. Previously there was some chance to record a sample, so test duration varied. This often resulted with tests timing out.

Test duration consistently keeps below 5 minutes.

**Comment by QuentinBisson** [comment]
@krzysied would it make sense to make a release for this fix? VPA has not been released since January

**Comment by krzysied** [comment]
@QuentinBisson The fix was picked up in the newer versions of VPA. It's definitely available in VPA 0.8.1 and VPA 0.9.x. \
I assume most people use k8s that has version above 1.13, so VPA 0.8.1 can be used -https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#compatibility. \
IMHO I don't feel a strong need  for new 0.7 release.

**Comment by QuentinBisson** [comment]
Oh I'm sorry you are right. I did not notice this was from 2020 🤦🏻
