### ISSUE TITLE
Do I have to use image - k8s.gcr.io/cluster-autoscaler:v1.15.n (where n is release version) all the time for deployment?

### ISSUE THREAD

**Issue by aashishgoyal246** [kubernetes/autoscaler#3081]
Hi there,

I am using cluster-autoscaler in AWS to autoscale my node groups and I am using the file `cluster-autoscaler-autodiscover.yaml` for deploying it. I have a doubt in this file that in container section an image - `k8s.gcr.io/cluster-autoscaler:v1.14.7` is used with certain commands, so my question is that if I only want to use an `nginx` image for deployment than do I always have to include the container with the same image - `k8s.gcr.io/cluster-autoscaler:v1.14.7` in my deployment? or I can use only `nginx` image container so that if I want to scale only my nginx deployment to 50 then the autoscaling in node group will work or not?

**Comment by gjtempleton** [comment]
Hi,

Is this the file you're referring to? https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml

I'm not clear on what you're asking - if you want to scale your cluster dynamically you should be using a cluster-autoscaler image (though adjust the minor release branch to match your k8s version). The cluster-autoscaler is only intended to dynamically scale your cluster up and down to meet pod demand in a configurable way.

That file is a good example of an AWS deployment of the cluster autoscaler auto discovering appropriately tagged ASGs so that it can scale them when there are pending pods (i.e. if your cluster needed more nodes to place all your nginx deployment's pods.)

Does that make things any clearer?

**Comment by chaitushiva** [comment]
The original question might be that , is this format works all the time
inside deployment file

I.e., spec.template.spec.containers.image :
k8s.gcr.io/cluster-autoscaler:v1.15.n

Standard repository k8s.gcr.io?

**Comment by brycecarman** [comment]
From your original question, it sounds like you want to be able to automatically increase or decrease the number of nginx pods in your cluster. For that, check out Horizontal Pod Autoscaler. https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/. 

Cluster Autoscaler is for increasing/decreasing the number of worker nodes in response to how many pods are running. If you are asking which repository to use for each version of Cluster Autoscaler, check out the releases page for the project https://github.com/kubernetes/autoscaler/releases. Each version has an **Images** section that shows where the image can be pulled from.

**Comment by chaitushiva** [comment]
Am not the original requestor! I just tired guess their intention

**Comment by aashishgoyal246** [comment]
@gjtempleton thanks for replying to my question. I have searched about my doubt and I got my answer is that - We deploy the node groups on eks cluster then I applied the file `cluster-autoscaler-autodiscover.yaml` into my cluster, this enables the cluster to perform autoscaling and then I created a deployment file only for `nginx` image and it starts scaling up or down according to load on the nodes.

**Comment by gjtempleton** [comment]
Good to hear @aashishgoyal246 
In that case are you fine with me closing this issue as it sounds like you've found the answer to your query?

**Comment by rehevkor5** [comment]
For some unexpected reason which is not clear to me, v1.15.6 is not available in the same repo as other versions for example gcr.io/google-containers/cluster-autoscaler:v1.15.5

Instead it's on:
eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.15.6
us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.15.6
asia.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.15.6

Not sure why that is.

**Comment by gjtempleton** [comment]
Hey @rehevkor5 that's an unrelated issue due to a known ongoing piece of work that's unfortunately taken longer than initially expected due to dependencies discovered during the work, but I've raised #3093 to track this issue.

**Comment by aashishgoyal246** [comment]
@gjtempleton I am OK if you close this issue and I got my answer.
