### ISSUE TITLE
Latest Cluster-Autoscaler & VPA Releases Currently unavailable from k8s.gcr.io

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#3093]
The latest release of Cluster-Autoscaler and VPA (see list of images below) are currently unavailable from the usual `k8s.gcr.io` vanity domain pending the completion of the domain flip work discussed here: https://groups.google.com/forum/#!topic/kubernetes-dev/MkXnkTSJ_vs

As per the above thread this domain flip is currently expected to complete in May, currently the images can be retrieved as per the [releases page](https://github.com/kubernetes/autoscaler/releases) by using the underlying registry addresses of `{asia,eu,us}.gcr.io/k8s-artifacts-prod/autoscaling/` rather than `k8s.gcr.io`

**Cluster-autoscaler**:

* 1.18.1
* 1.17.2
* 1.16.5
* 1.15.6
* 1.14.8

**vpa-admission-controller**:

* 0.8.0

**vpa-updater**:

* 0.8.0

**vpa-recommender**:

* 0.8.0

**Comment by gjtempleton** [comment]
Discussed at SIG Autoscaling meeting today and decided no action to be taken, will be resolved once vanity domain flip completes: https://docs.google.com/document/d/1RvhQAEIrVLHbyNnuaT99-6u9ZUMp7BfkPupT2LAZK7w

**Comment by alberto** [comment]
This hit us this week while upgrading our cluster. Unfortunately, this means helm chart can't find the latest version (which we need because of a bug fix)

**Comment by gjtempleton** [comment]
Vanity domain flip has now completed and images can be pulled from `k8s.gcr.io/autoscaling/{component}:{tag}`

Closing as resolved.

**Comment by yogeek** [comment]
Hi @gjtempleton 

Seems that all tags are not available :
```
docker pull k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.6
Error response from daemon: manifest for k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.6 not found: manifest unknown: Failed to fetch "v1.17.6" from request "/v2/autoscaling/cluster-autoscaler/manifests/v1.17.6".

docker pull k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.5
Error response from daemon: manifest for k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.5 not found: manifest unknown: Failed to fetch "v1.17.5" from request "/v2/autoscaling/cluster-autoscaler/manifests/v1.17.5".

docker pull k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.4
Error response from daemon: manifest for k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.4 not found: manifest unknown: Failed to fetch "v1.17.4" from request "/v2/autoscaling/cluster-autoscaler/manifests/v1.17.4".
```

Is it normal please ?
I have a cluster in 1.17.6 and according to the documentation I have to deploy the exact same version of cluster-autoscaler but I can't find the corresponding image.
