### ISSUE TITLE
Support AWS Inferentia chips 

### ISSUE THREAD

**Issue by RobertLucian** [kubernetes/autoscaler#3095]
It appears that even though Inferentia instances have been added to [cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L655-L678](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.18/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L655-L678), they still don't have support for the actual Inferentia chips. 

This is what I'm getting when I try to scale:
`1 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"api-api-0-67b4b9665f-rw7zm", UID:"808d2f5b-4c66-47cc-af1b-d66144ce5959", APIVersion:"v1", ResourceVersion:"31577", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 2 Insufficient hugepages-2Mi, 2 Insufficient aws.amazon.com/infa, 1 max node group size reached`.

For reference, here are the instructions to get the k8s setup for neuron (Inferentia chips):
https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/tutorial-k8s.md#steps

Is there anyone that can help us with a patch? Or at least with a bit of info as to what parts of the codebase have to be modified to accomodate Inferentia chips.

**Comment by gjtempleton** [comment]
Could you tell us which version of k8s and the CA you're running?

Also, are there any Inf1 instances running at the point the CA produces this message? If so could you provide the output (appropriately obfuscated) of describing one of those nodes?

**Comment by RobertLucian** [comment]
@gjtempleton Thanks for coming back with a reply. The version of k8s is 1.15.11 (the highest possible on EKS) and that of the CA is 1.18.1. 

No, no Inf1 instances are running at that point. The node(s) are not up because the CA can't find any nodes matching the requested resources and so, no node can be spun up. I can force one to scale-up though and then copy-paste the output.

**Comment by RobertLucian** [comment]
@gjtempleton I've done a bit more testing on this matter and here's what I've found:

1. On the current version of EKS (1.15) and CA (1.18.1), the auto-scaling mechanisms work just fine on `inf1.xlarge` instances. So, whether the cluster already starts with a node or not, the auto-scaling thing works. That's good. Mind you, when I deploy a pod, I either ask for non-inf resource or inf resources. 
1. While using `inf1.6xlarge` instances, the auto-scaling mechanism doesn't work when there are no nodes to start with - this when I request inf resources. But if I request non-inf resources (CPU and/or memory), the cluster auto-scales and I get my node(s). Subsequent pods that require either non-inf or inf resources lead to a scale-up, so that's good. So it doesn't work when it starts at 0.

I suspect that when there is more than 1 inf chip on a given instance, the CA doesn't know how to bring that up (and I get that above error from my first message). Somehow it works when there's at least one node running. In the same vein, I suspect it's the same case for `inf1.24xlarge` - but I can't test on that because my quota is too low. I haven't tested on `inf1.2xlarge`, but I suspect it's going to work because it still only has a single inf chip as opposed to multiple. 

One important observation is that in my previous node description, the log should have described an `inf1.6xlarge` instance and not an `inf1.xlarge`. The reported error is only logged when I use `inf.6xlarge` instances.

Maybe there's an incompatibility between CA (version 1.18.1) and EKS (version 1.15) due to their mismatch in version numbers. I know they ought to run on the same version (1.15.x on CA with 1.15 on EKS), but I really had to update it to 1.18.1 to get the support for inf instances. And EKS can't be updated to a higher version because 1.15 is already the highest. If https://github.com/kubernetes/autoscaler/pull/2550 is patched onto version 1.15.6 of CA (to get a 1.15.7), then maybe this issue will go away. Not to mention the error I keep getting on 1.18.1 about CSI nodes not existing. Do you think that would solve something? What's your take on this? What do you think there's to be done here?

**Comment by gjtempleton** [comment]
I have an inkling on the 1.15.6 issue you've seen, but need to double check this in a cluster before I can say for sure.

In terms of the main issue though, can I ask what tags you have on the ASG when you're trying to scale from zero? Are there any tags on the ASG itself at the AWS level along the lines of 

```
k8s.io/cluster-autoscaler/node-template/resources/aws.amazon.com/infa:         1
k8s.io/cluster-autoscaler/node-template/resources/hugepages-2Mi:               256Mi
```
?

**Comment by RobertLucian** [comment]
@gjtempleton I have something along the lines of
```
k8s.io/cluster-autoscaler/cortex-dev-1 | owned | Yes |  
k8s.io/cluster-autoscaler/enabled | true | Yes |  
k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/infa | true | Yes |  
k8s.io/cluster-autoscaler/node-template/label/workload | true | Yes |  
k8s.io/cluster-autoscaler/node-template/taint/dedicated | aws.amazon.com/infa=true
```

I see there was a bug regarding the dynamically generated instance types in https://github.com/kubernetes/autoscaler/issues/3109. This may make my issue go away since I could revert back to `1.15.x`. That's really great!

Is there a timeline of when this could make it in as patch for `1.15.7`? Or do you think it would be better to build my own version and use that instead? I'd need this fixed ASAP.

**Comment by RobertLucian** [comment]
@gjtempleton applying https://github.com/kubernetes/autoscaler/pull/3110 to version `1.16.5` and then adding the `k8s.io/cluster-autoscaler/node-template/resources/` tags to ASGs seemed to have fixed my problem. I transitioned to EKS 1.16 anyway, so that's why I didn't use 1.15 anymore.

I'm still testing, so I might be back with some more feedback. Until then, I wouldn't close the ticket.

**Comment by Jeffwan** [comment]
inf1 has not been officially supported on EKS, it will be ready pretty soon (next week). Thanks for reporting issues here.

**Comment by allamand** [comment]
Hi, I'm also having thie problem 

```
E0616 13:21:18.348242       1 utils.go:321] Unable to build proper template node for NodeGroup-112HT3JOFIPYR: ASG "NodeGroup-112HT3JOFIPYR" uses the unknown EC2 instance type "inf1.2xlarge"
```

I'm using cluster-autoscaler:v1.15.6, do you have recommendation ?

**Comment by Jeffwan** [comment]
@allamand 

Can you use this option? It will load all instance types in runtime

https://github.com/kubernetes/autoscaler/blob/f029a381602baf4a9f375096524c3b67178bfcc9/cluster-autoscaler/main.go#L171

**Comment by Jeffwan** [comment]
`aws-use-static-instance-list` is not enabled in some CA versions. We won't patch new instance types in every release 

Check here for more details. Feel free to reopen the issue
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#use-static-instance-list

/close
