### ISSUE TITLE
Feature Question/Request: Support other metrics when determining "scale-up"

### ISSUE THREAD

**Issue by rsmitty** [kubernetes/autoscaler#31]
Hello,

I wasn't sure where the best place to ask this question would be, as I am not sure what Slack channel the cluster-autoscaler tool falls under. Hope this works. 

I was wondering if there could be any other metrics used to determine when a cluster is scaled up. Specifically, I was hoping to see something along the lines of "okay, let's scale up when the average utilization across the cluster is greater than 80%" in addition to the current "scale when pods are pending" approach. Has there been any discussion around this? Our current scale-up takes a few minutes and I want to be able to scale in anticipation of more Pods coming online in addition to when they've already been requested.

Thanks!

**Comment by mumoshu** [comment]
Hi @rsmitty,
I believe if you'd just like CA to scale nodes out "faster", [adding some slack/buffer in resources](https://github.com/kubernetes/contrib/issues/2251) is the way to go for now.
Does it seem to solve your issue?
Would you mind sharing us more about use-case if it actually requires custom metrics for scaling decisions?

**Comment by rsmitty** [comment]
Sorry for the delayed response! Some combination of kubelet flags and the slack/buffer of resource creation might get us where we're wanting to go. Let me take a closer look. I'll close for now and reopen if needed.
