### ISSUE TITLE
In eks-1.13 cluster auto scale down is not working

### ISSUE THREAD

**Issue by nandeeshb09** [kubernetes/autoscaler#3100]
Hi Team,

Here we are using cluster auto scaler in EKS cluster , the issue is  scale up of node is happening but scale down is not happening.

Is there any extra flags we have to set in cluster autoscaler deployment?

Please guide us here ,below are the annotations details and version of CA.

 containers:
      - command:
        - ./cluster-autoscaler
        - --v=4
        - --stderrthreshold=info
        - --cloud-provider=aws
        - --skip-nodes-with-local-storage=false
        - --expander=least-waste
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/eks-dev
        env:
        - name: AWS_REGION
          value: us-east-1
        image: gcr.io/google-containers/cluster-autoscaler:v1.13.9

**Comment by gjtempleton** [comment]
The cluster autoscaler at that verbosity level should be telling you which nodes it is considering for scale down, and why it doesn't think it should scale them down.

E.g. Utilization too high, violating a deployment's pod disruption budget etc.

**Comment by ellistarn** [comment]
@nandeeshb09 were you able to get this working?
