### ISSUE TITLE
capi: Replicas can go stale in nodeGroup causing erratic behaviour

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#3104]
DeleteNodes() is sometimes called in subroutines https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scale_down.go#L1067-L1090

But our implementation does not account for that properly https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go#L84-L149. And subroutines might compete to call setSize() with different values and getting stale replicas(). 

Also when we call `setSize()` we leave stale the replicas number in the machineSet for the scalableResource struct used by `replicas()` https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go#L63-L85.

We need to:
- Ensure replicas() does never return an stale number and unit test it.
- Ensure multiple subroutines calls to deleteNodes() never use an stale replicas number. We should probably lock deleteNodes so any upcoming routine pick a valid replicas().
- Also we need to make the deleteNodes() logic more robust by comparing against minSize here https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go#L106 rather than with 1.

/area provider/cluster-api

**Comment by enxebre** [comment]
cc @elmiko

**Comment by elmiko** [comment]
++, thanks Alberto!
