### ISSUE TITLE
[Bug] - CA AWS Dynamic InstanceTypes Generation Ignored

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#3109]
* #2249 introduced functionality for the generation of EC2 instance type knowledge at runtime - however this functionality is currently ignored when running the CA - this means we incur the cost of calling the pricing service API and parsing the large (10s of megs+) returned JSON, but then throw the result away, using the hardcoded list

* Affects all versions with this dynamic functionality:
  * 1.15.6+
  * 1.16.5+
  * 1.17.0+
  * 1.18.0+

Discovered whilst investigating #3095

**Comment by deliahu** [comment]
@gjtempleton I was wondering if you have plans on addressing this bug in an upcoming release? We are building off of our own fork of the CA for now (which includes https://github.com/kubernetes/autoscaler/pull/3110), but we'd like to switch back to the official images. Thanks!

**Comment by gjtempleton** [comment]
Resolved by #3185
