### ISSUE TITLE
Failed to create AWS Manager: NoCredentialProviders: no valid providers in chain. Deprecated.

### ISSUE THREAD

**Issue by hieu29791** [kubernetes/autoscaler#3117]
My cluster has 2 node groups, I following this [guide](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html). It works fine if my cluster doesn't have **kube2iam**. When my cluster had already install **kube2iam**, error happen: `Failed to create AWS Manager: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.`   
I try to figure it out by remove those line: **- --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<YOUR CLUSTER NAME>** and add role of one node group to kube2iam annotation, it works, but because of that it only triggers auto-scaling of that node group, not others.  
Anyone have an idea to figure it out, thanks.

**Comment by abdennour** [comment]
Upgrade to autoscaler 7.0.0 namely with the latest EKS (1.16)

**Comment by hieu29791** [comment]
I resolved the problem. Problem is I installed kube2iam, so I need to create CA's role and define it in the deployment of the CA.

**Comment by abhassine** [comment]
Hello @hieu29791 

Could you please provide more details by sharing your manifests please ?

Best
