### ISSUE TITLE
No scale down of nodes with Succeeded Pods

### ISSUE THREAD

**Issue by shahar-lev** [kubernetes/autoscaler#3121]
CA 1.14 refuses to scale down said nodes although they only have Succeeded Pods and Active kube-system pods (I have PDBs in place for the latter).
Checking the logs reveal messages of this kind:

> Node prep-pool-4391495a-8b7s is not suitable for removal - memory utilization too big (0.845758)

After deleting the Succeeded Pods, CA scaled down the relevant nodes.
It seems that CA also takes Succeeded Pods into account when calculating utilization. Why is that?

**Comment by vivekbagade** [comment]
Ack. I'm investigating this.

**Comment by vivekbagade** [comment]
I tried reproducing this and the scale down wasn't blocked on Succeded pods which makes sense looking at the code at https://github.com/kubernetes/autoscaler/blob/972e30a5d9eece175a54fa5dfc0ed902b34f02b1/cluster-autoscaler/simulator/cluster.go#L253.

We get the allocatable from the node and node allocatable already accounts for Completed pods.

**Comment by vivekbagade** [comment]
I'm closing this issue for now. Please feel free to reopen if you have more info or reproduction steps.
