### ISSUE TITLE
No image tag for release 1.14.8

### ISSUE THREAD

**Issue by janavenkat** [kubernetes/autoscaler#3126]
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.14.8

Am not able to get the docker image because it's not available

```docker pull http://k8s.gcr.io/cluster-autoscaler:v1.14.8```

**Comment by lpszBar** [comment]
AFAIK there is a tempory problem with repo domain

try this instead 

`docker pull eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler`

using {asia,eu,us} depending on your location

More info: https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md

**Comment by pallasite99** [comment]
Hey @janavenkat, @abelgvidal 

Would you know if the image for k8s registry was just removed and we should just use the other ones?
