### ISSUE TITLE
cluster_autoscaler_last_activity metrics stops updating

### ISSUE THREAD

**Issue by dharmab** [kubernetes/autoscaler#3130]
Sometimes, the `cluster_autoscaler_last_activity` metric stops updating even though the cluster autoscaler is still logging activity.

![Screen Shot 2020-05-13 at 1 06 05 PM](https://user-images.githubusercontent.com/4450708/81854239-ddbc1280-951a-11ea-804a-3da3ab6a8110.png)

**Comment by dharmab** [comment]
Kubernetes: 1.16.9
Cloud: Azure (haven't seen this on AWS)
CA: 1.16.5

**Comment by MaciekPytel** [comment]
The metric is updated by CA main loop. All the logs on the screen are coming from Azure provider implementation. My guess would be either some provider call has blocked for a really long time or the main goroutine is stuck and some helper gorutine inside provider is logging. Either way it doesn't look like main CA logic is really running.

cc: @feiskyer 
/area provider/azure

**Comment by marwanad** [comment]
@dharmab unregistered node deletions happens synchronously and sometime this takes a long time. so this blocks the main routine.

Right before, the stall do you see any logs along "removing unregistered node"?

**Comment by marwanad** [comment]
@MaciekPytel on that note, is there a reason why the `removeOldUnregisteredNodes` doesn't happen asynchronously? Empty node deletions happen in bulk so I'm wondering if unregistered nodes should be treated similarly. Also, the `removedAny` flag to skip the iteration if those are deleted.

**Comment by MaciekPytel** [comment]
The expectation is that deleting node from cloudprovider is non-blocking so there shouldn't between doing it sequentially and in parallel. Given that removeOldUnregisteredNodes is error handling logic that isn't expected to happen super often there isn't much incentive to optimize it.
For scale-down empty the throughput is critical as we expect to delete hundreds of empty nodes in rapid succession and there are features like delay-deletion that contribute to total time on top of cloudprovider call.

**Comment by lxnch** [comment]
> Right before the stall do you see any logs along "removing unregistered node"?

No, `Info` log line containing`removing unregistered node` is not seen before this behavior.

**Comment by dharmab** [comment]
@lxnch and I saw this happen again this morning and captured logs in the 15 minute period leading up to and including the point at which the metric stopped updating.

![Screen Shot 2020-06-04 at 7 18 37 AM](https://user-images.githubusercontent.com/4450708/83761513-a92c0a00-a633-11ea-93ea-2c74de261782.png)

In this screenshot, the `main` and `autoscaling` activities go to zero between 1142 and 1145. The large spike is when we received an alert for this condition and restarted the CA.

Logs for the period 1132-1147 are attached. Note that the last log was at 1144; there are three minutes of "silence" after that.

[2020-06-04-cluster-autoscaler.log](https://github.com/kubernetes/autoscaler/files/4730270/2020-06-04-cluster-autoscaler.log)

**Comment by dharmab** [comment]
@marwanad Unfortunately it's kind of intermittent, seems to happen at infrequent random times across our fleet of clusters.

**Comment by dharmab** [comment]
A brief update, we've increased log verbosity but haven't seen this happen in a while. I ❤️  heisenbugs!

**Comment by marwanad** [comment]
@dharmab Sorry for the delay, was planning on updating once the PRs merge so I did a few runs with pprof and looked at the goroutine and blocking profile. It took a while to reach a blocking state but basically I did find possible paths that can cause lock contention and block the CA main loop.

One was fixed in 1.18 and above but wasn't cherry-picked in 1.16: https://github.com/kubernetes/autoscaler/pull/3274. This could have either a `DeleteInstances` call hanging or a `Nodes` based on the ordering of events. 

There are other improvements recently cherry-picked in 1.16 around making sure we don't block or hold locks longer than necessary.

I've been running a soak cluster for a week with alert manager configured and it seems fine so far. Also, did a stress test on the hot paths with large scale up and scale down volumes. 

I'll keep the issue open for now but it would be great if you can test with the latest build off `cluster-autoscaler-release-1.16`.

**Comment by dharmab** [comment]
We've actually just started upgrading to 1.17 and will be moving to 1.18 shortly afterwards (there were a lot of Azure fixes in 1.18). So we may just move directly to CA 1.18 as well

**Comment by marwanad** [comment]
@dharmab sounds good! The fixes should be in all the latest release branches.

**Comment by marwanad** [comment]
@dharmab just checking in to see if you've hit the issue again?

**Comment by dharmab** [comment]
We haven't seen this since upgrading to 1.18. I'll close this issue for now.
