### ISSUE TITLE
CA 1.14: Missing AWS instance types

### ISSUE THREAD

**Issue by TwinProduction** [kubernetes/autoscaler#3134]
CA 1.14.8 is missing several instance types, which master already has.

I'm fine with taking care of it myself, but just to clarify, should I just execute
```
go run ec2_instance_types/gen.go
```
and create a PR to merge the newly generated file into the `cluster-autoscaler-release-1.14` branch, or should I look for the last commit that generated the ec2 instance types and create a PR to cherry pick it into `cluster-autoscaler-release-1.14`?

**Comment by marians** [comment]
Duplicate of https://github.com/kubernetes/autoscaler/issues/3006 ?

**Comment by TwinProduction** [comment]
Good call @marians, I searched for it before I created an issue, but apparently I didn't search hard enough.
