### ISSUE TITLE
Azure CA 1.17.2 - problems authenticating with aadClientId+aadClientSecret when passing id+secret as env vars using secret

### ISSUE THREAD

**Issue by hamburgerbun** [kubernetes/autoscaler#3137]
Issue: 

when using 1.17.2 cluster-autoscaler in azure on a custom k8s cluster not using AKS, where my client id and client secret are set as secrets used in environment like suggested in the README, authorizations with the following message
E0514 19:40:46.228528       1 azure_manager.go:312] Failed to fetch ASGs: cannot autodiscover ASGs: compute.VirtualMachineScaleSetsClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<aad client object id>' with object id '<aad client object id>' does not have authorization to perform action 'Microsoft.Compute/virtualMachineScaleSets/read' over scope '/subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Compute' or the scope is invalid. If access was recently granted, please refresh your credentials."

However, it works if i instead of using base64-encoded secrets just set the environment variables directly using name: value: pairs.

Expected: 
azure compute rest calls shouldn't error out

Actual: 
the error mentioned above, once every minute. 

Steps:
for simplicity, let's say i mostly followed this, so it's all using 1.17.3-00 ubuntu packages for kubeadm kubelet, etc. 
https://github.com/Azure/azure-quickstart-templates/tree/master/kubernetes-on-ubuntu-vmss
but in both master and workers there is no cloudconfig and cloud is not set to azure (was hitting autorest issues that i'm still looking at). 

I believe this leads to missing providerID so CA can't actually do its job, but one thing at a time. 

Other notes:

note that when i print out the environment from /proc/<docker proc id>/environ, there is actually a difference in my output, like new lines vs. ^@ (at least when you look through vim, the ^@ doesn't show in prompt)

working environment without using secrets
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin^@HOSTNAME=cluster-autoscaler-66fcbfc4c-xksk5^@ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000^@ARM_RESOURCE_GROUP=resource-group-1^@ARM_TENANT_ID=00000000-0000-0000-0000-000000000000^@ARM_CLIENT_ID=00000000-0000-0000-0000-000000000000^@ARM_CLIENT_SECRET=0000ITSASECRET0000^@ARM_VM_TYPE=vmss^@KUBERNETES_SERVICE_PORT=443^@KUBERNETES_PORT_443_TCP_PROTO=tcp^@KUBERNETES_PORT_443_TCP_PORT=443^@KUBE_DNS_SERVICE_HOST=10.96.0.10^@KUBE_DNS_PORT=udp://10.96.0.10:53^@KUBERNETES_SERVICE_HOST=10.96.0.1^@KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443^@KUBE_DNS_PORT_53_UDP=udp://10.96.0.10:53^@KUBE_DNS_PORT_53_UDP_PORT=53^@KUBE_DNS_PORT_53_UDP_ADDR=10.96.0.10^@KUBE_DNS_PORT_53_TCP_ADDR=10.96.0.10^@KUBE_DNS_PORT_9153_TCP=tcp://10.96.0.10:9153^@KUBERNETES_PORT=tcp://10.96.0.1:443^@KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1^@KUBE_DNS_SERVICE_PORT_METRICS=9153^@KUBE_DNS_PORT_53_TCP=tcp://10.96.0.10:53^@KUBE_DNS_PORT_9153_TCP_PROTO=tcp^@KUBE_DNS_PORT_9153_TCP_PORT=9153^@KUBE_DNS_PORT_9153_TCP_ADDR=10.96.0.10^@KUBERNETES_SERVICE_PORT_HTTPS=443^@KUBE_DNS_SERVICE_PORT=53^@KUBE_DNS_SERVICE_PORT_DNS=53^@KUBE_DNS_SERVICE_PORT_DNS_TCP=53^@KUBE_DNS_PORT_53_UDP_PROTO=udp^@KUBE_DNS_PORT_53_TCP_PROTO=tcp^@KUBE_DNS_PORT_53_TCP_PORT=53^@SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt^@HOME=/root^@
```

trying to use secrets like the README and azure kubernetes ubuntu vmss templates suggest
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin^@HOSTNAME=cluster-autoscaler-6b7bcfbcdb-kws9r^@ARM_VM_TYPE=vmss
^@ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
^@ARM_RESOURCE_GROUP=resource-group-1
^@ARM_TENANT_ID=00000000-0000-0000-0000-000000000000
^@ARM_CLIENT_ID=00000000-0000-0000-0000-000000000000
^@ARM_CLIENT_SECRET=0000ITSASECRET0000
^@KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443^@KUBERNETES_PORT_443_TCP_PORT=443^@KUBE_DNS_SERVICE_PORT_DNS=53^@KUBE_DNS_SERVICE_PORT_METRICS=9153^@KUBE_DNS_PORT_53_UDP_ADDR=10.96.0.10^@KUBE_DNS_PORT_53_TCP_ADDR=10.96.0.10^@KUBE_DNS_PORT_9153_TCP=tcp://10.96.0.10:9153^@KUBE_DNS_PORT_9153_TCP_ADDR=10.96.0.10^@KUBERNETES_SERVICE_PORT_HTTPS=443^@KUBERNETES_PORT=tcp://10.96.0.1:443^@KUBE_DNS_SERVICE_PORT=53^@KUBE_DNS_SERVICE_PORT_DNS_TCP=53^@KUBE_DNS_PORT_53_TCP=tcp://10.96.0.10:53^@KUBE_DNS_PORT_53_TCP_PROTO=tcp^@KUBE_DNS_PORT_53_TCP_PORT=53^@KUBE_DNS_PORT_9153_TCP_PORT=9153^@KUBERNETES_SERVICE_HOST=10.96.0.1^@KUBERNETES_SERVICE_PORT=443^@KUBERNETES_PORT_443_TCP_PROTO=tcp^@KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1^@KUBE_DNS_SERVICE_HOST=10.96.0.10^@KUBE_DNS_PORT_53_UDP=udp://10.96.0.10:53^@KUBE_DNS_PORT_53_UDP_PROTO=udp^@KUBE_DNS_PORT_9153_TCP_PROTO=tcp^@KUBE_DNS_PORT=udp://10.96.0.10:53^@KUBE_DNS_PORT_53_UDP_PORT=53^@SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt^@HOME=/root^@
```

note sure if it's just a matter of trimming whitespace or something to account for a new line?

**Comment by marwanad** [comment]
The service principal you're using doesn't seem to have the appropriate permissions. Try assigning it contributor role over the subscription and restart the CA pod.

```
 az role assignment create --assignee-object-id {{the_object_id_in_error_message}} --scope {{scope_in_error_message}} --role contributor
```

/area provider/azure

**Comment by hamburgerbun** [comment]
the app registration in question is Contributor actually, so it does work if i explicitly set the environment variables myself using name:value pairs in the yml; using secrets to set the environment variables seems to be causing a problem for me though, and that's what's suggested in both clusteer-autoscaler azure docs and in the azure quickstart template i linked https://github.com/Azure/azure-quickstart-templates/tree/master/kubernetes-on-ubuntu-vmss

**Comment by marwanad** [comment]
I'd guess that the the base64 encoded secret might be malformed, extra spaces, etc - how are you encoding those?

**Comment by hamburgerbun** [comment]
the script has a big ol EOL section the generates a cluster-autoscale yaml, and this is in it
---
apiVersion: v1
data:
  ClientID: '$(echo $CLIENT_ID | base64)'
  ClientSecret: '$(echo $CLIENT_SECRET | base64)'
  ResourceGroup: '$(echo $RESOURCE_GROUP | base64)'
  SubscriptionID: '$(echo $SUB | base64)'
  TenantID: '$(echo $TENANT | base64)'
  VMType: '$(echo $VMTYPE | base64)'
kind: Secret
metadata:
  name: cluster-autoscaler-azure
  namespace: kube-system

as far as I can tell though, the only difference i could visibly tell were newlines that i didn't expect

**Comment by marwanad** [comment]
oh can you try with `echo -n` to make sure its not printing the trailing line character?

**Comment by hamburgerbun** [comment]
ok now i added -n to the echos, verified my base64 outputs actually changed so the new-line char does matter, but i still get the error. output from /proc/pid/environ actually matches the "good" case now, no new lines.

i guess it's not the newlines then, hmmm. i now have three versions of the yaml, secrets w/ new lines, secrets w/o newlines, and just direct environment name/value pairs, and only the env name/value pair one works correctly.

**Comment by hamburgerbun** [comment]
i'm gonna chalk it up to a messed up copy paste job that had also given me trouble in a different auth bug, i had some unicode chars that i spent hours uncovering with my previous setup, i'm going to assume i dealt with all of that because my secrets seem to work now.

**Comment by hamburgerbun** [comment]
ugh. i guess as a final note, i have it working with secrets in a custom built cluster autoscaler image from the cluster-autoscaler-1.17.2 tag, but i just do an image swap with the us.gcr.io 1.17.2 pre-built and everything falls apart. i don't know what's going on there.
