### ISSUE TITLE
vpa-recommender: getUrlWithQuery does not account for basePath in prom address

### ISSUE THREAD

**Issue by andsens** [kubernetes/autoscaler#3142]
When passing an arg like `--prometheus-address=http://prometheus-operated.metrics:9090/prometheus` to the recommender, `getUrlWithQuery`:
https://github.com/kubernetes/autoscaler/blob/0255c1152773ecfcc532fe6ca494414351a946df/vertical-pod-autoscaler/pkg/recommender/input/history/prometheus_client.go#L54-L64

Does not take the path component of the original adress into account. I'm not a go expert, but I would expect that you instead should have something like this:
```
url.Path = path.join(url.Path, "api/v1/query")
```

**Comment by MadhavJivrajani** [comment]
Hey @andsens!

According to the docs for `net/url`, the [`URL`](https://golang.org/pkg/net/url/#URL) type has an attribute `Path`. When a call to `Query()` is made, the `RawPath` of the parsed `url` (which contains the original address as well) is [used](https://golang.org/src/net/url/url.go?s=31036:31064#L1099) internally.

This might help further: https://play.golang.org/p/MtBl4PP8sQV
