### ISSUE TITLE
VPA:  V1beta2 version no longer existent in k8s <= 1.17 ?

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/autoscaler#3144]
Hello. I am a maintainer of the `kube-state-metrics` project and it has come to our notice that the `autoscaling/v1beta2` is no longer supported from k8s `1.17.x`. 

Can anyone confirm this? There was no deprecation notice for this either. If we were to remove this apiVersion support, shouldn't this have been removed in `k8s.io/api@v.0.17.x` as well?

@kubernetes/autoscaler-admins @kubernetes/api-reviewers

**Comment by tariq1890** [comment]
I don't see any info on this from the release notes either: https://v1-17.docs.kubernetes.io/docs/setup/release/notes/

When I check for the supported apiVersions in the k8s 1.17 server, i get this

```bash
% kubectl api-versions|grep autoscaling
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
```

cc @bskiba

**Comment by liggitt** [comment]
VPA types are not built into the kubernetes API server and have never been included in k8s.io/api. They are defined as custom resources under the autoscaling.k8s.io API group at various versions and must be installed into a kubernetes API server. See the installation instructions at https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

**Comment by tariq1890** [comment]
Why close the issue so soon?

There still is no declaration that `v1beta2` is no longer around. At the very least, the [migration doc](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/MIGRATE.md) should mention that we need to migrate out of `v1beta2`.

**Comment by liggitt** [comment]
`autoscaling.k8s.io/v1beta2` is still defined in the VPA CRD (see https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml)
