### ISSUE TITLE
a question about how hard affinity is handled in AWS/CA.

### ISSUE THREAD

**Issue by jurgenweber** [kubernetes/autoscaler#3145]
The scenario, this is just a theoretical question. I have not tried to prove it yet.

I have an ASG, LT + MixedInstance types, I have lots of instance types defined so I can tap into many SpotInst pools. A pod comes up to be scheduled and it has a hard affinity to the instance-type=mysuperfuninstancetypeX. The scheduler can not schedule it because there are non available so CA goes and scales one?

**Comment by MaciekPytel** [comment]
It's random. CA is designed with the assumption that all nodes in NodeGroup (CA abstraction for ASG) are identical for scheduling purposes. It just picks a random existing node from the group and assumes any new node will look exactly identical. If the pod would be able to schedule on this randomly chosen node, CA will resize nodegroup.
MixedInstance is not supported, though it should work as long as all instance types you use are ~identical for the purposes of scheduling. Using a label selector on a label that differs between nodes in the same group is definitely not supported and will result in random behavior.

**Comment by jurgenweber** [comment]
Thank you
