### ISSUE TITLE
cluster autoscaler can not build when enable go mod

### ISSUE THREAD

**Issue by Dingshujie** [kubernetes/autoscaler#3146]
i have two questions:
- when enabled go mod, cluster autoscaler build failed, it seems go.mod is faked go mod file
- another question is cluster autoscaler update vendor using kubernetes master, for example, cluster-autoscaler 1.17.2 using github.com:kubernetes/kubernetes.git:master (711790af23a231ade04c6c39d6bc5dcf1a996f73), this commit not contained by any kubernetes release tags. so should we update vendor use an release version?

**Comment by lsytj0413** [comment]
Please see https://github.com/kubernetes/autoscaler/issues/2858#issuecomment-591372524

**Comment by Dingshujie** [comment]
> Please see [#2858 (comment)](https://github.com/kubernetes/autoscaler/issues/2858#issuecomment-591372524)

thank you for your reply
