### ISSUE TITLE
CA doesn't scale down because of metrics-server

### ISSUE THREAD

**Issue by danielyaa5** [kubernetes/autoscaler#3163]
Logs indicate cluster refuses to scale down because of metrics-server, readme suggests not adding a PDB for metrics-server but without a PDB on metrics-server how do I get scale-down working...? Very frustrating

**Comment by MaciekPytel** [comment]
Restarting metrics-server will break all HPAs in your cluster for a few minutes. There is no way to scale-down a node running MS without causing this disruption.
It's a tradeoff between availability and efficiency - if you're ok with HPA periodically going down you can set PDB for MS. If you're not CA will not be able to scale-down this node. The default settings and recommendations in FAQ strongly prioritize availability above all else, but it's up to you how you want to balance the two.

One trick that may be useful is to run your system pods on a separate node pool (using a combination of nodeSelector and taints). That way your system pods would run on separate nodes and they won't block scale-down of your other nodes.

**Comment by danielyaa5** [comment]
Thanks for the info, what exactly will break when you scale down a node with metrics-server? Looking at the metrics-server readme, I'm thinking I might not even need it.
```
Don't use Metrics Server when you need:

Non-Kubernetes clusters
An accurate source of resource usage metrics
Horizontal autoscaling based on other resources then CPU/Memory
```

My HPA is autoscaling off pubsub unacked messages

**Comment by danielyaa5** [comment]
Cool, thanks, I think we can close this issue, I got all the info I needed, but it would be nice if someone added more detail to the readme in the why wont scale down work section.

**Comment by harshmanvar** [comment]
what should be way ? on the whole node, there is a **metrics server** and **heapster-gke** running. 

Should i set deployment replicas to **2** instead of **1** and set **PDB** so CA starts working as expected?
