### ISSUE TITLE
Anyway to force vpa to work with rc with only 1 pod

### ISSUE THREAD

**Issue by mscrivo** [kubernetes/autoscaler#3167]
Trying out VPA in our cluster and it's working great with RC's that have more than 1 replica, but for those that only have one, discovered that it's doing anything. Looking at the logs, it appears these messages explain why:

`1 pods_eviction_restriction.go:209] too few replicas for ReplicationController`

Was wondering if there was a way to override that behaviour and allow it to apply updates when there is only 1 replica?

**Comment by bskiba** [comment]
You can modify [minreplicas flag of updater](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/main.go#L44) to 1. 
We would be very grateful if you found time to add this to our [FAQ](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md).
