### ISSUE TITLE
EKS K8s -- Hamster VPA example doesn't update?

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/autoscaler#3170]
I'm testing the VPA on an EKS cluster running 1.15. 

I'm following Amazon's own guide here: https://docs.aws.amazon.com/eks/latest/userguide/vertical-pod-autoscaler.html

I've added the metric-server using 

`kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml`

Then checked out the repo and used `./hack/vpa-up.sh` to install the vpa resources

The running pods in my cluster at this stage are:

```
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   aws-node-w9cht                             1/1     Running   0          2m6s
kube-system   coredns-576d9b7d78-b9xhv                   1/1     Running   0          5m58s
kube-system   coredns-576d9b7d78-gvdwm                   1/1     Running   0          5m58s
kube-system   kube-proxy-66phn                           1/1     Running   0          2m6s
kube-system   metrics-server-7668599459-s8tt5            1/1     Running   0          63s
kube-system   vpa-admission-controller-f565bd55c-gtkzn   1/1     Running   0          21s
kube-system   vpa-recommender-7b77784f68-gnz4l           1/1     Running   0          24s
kube-system   vpa-updater-6754d65d8d-kwq6s               1/1     Running   0          24s
```

I install the Hamster example using

`kubectl apply -f examples/hamster.yaml`

It installs two replicas, and according to the guide, it's meant to respin the replicas with modified resource requests, but it does not.

In the VPA, the recommender does not show any recommendations:

```
$ kubectl describe vpa hamster-vpa
Name:         hamster-vpa
Namespace:    default
Labels:       <none>
Annotations:  API Version:  autoscaling.k8s.io/v1
Kind:         VerticalPodAutoscaler
Metadata:
   ...
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  *
      Controlled Resources:
        cpu
        memory
      Max Allowed:
        Cpu:     1
        Memory:  500Mi
      Min Allowed:
        Cpu:     100m
        Memory:  50Mi
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         hamster
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2020-05-30T15:12:42Z
    Status:                False
    Type:                  RecommendationProvided
  Recommendation:
Events:  <none>

```

and in the logs for both the recommender and updater, I see this:

`metrics_client.go:69] 0 podMetrics retrieved for all namespaces`

So, I'm not sure, but is the VPA not getting the metrics from the metric server in order to make its recommendations? There are no obvious errors in the VPA pod logs.

Am I missing something or have I not installing something correctly? I'm installing on a clean, unused cluster

**Comment by bskiba** [comment]
Can you check what you get running 
```
kubectl get --raw /apis/metrics.k8s.io/v1beta1/pods
```
If this is empty, it means Metrics Server is not exposing your pod metrics through the metrics API. VPA relies on metrics api to fetch cpu and memory usage metrics for containers.

For issues with metrics server installation I suggest reaching out to [sig-instrumentation](https://github.com/kubernetes/community/tree/master/sig-instrumentation)

**Comment by huang-jy** [comment]
```
$ kubectl get --raw /apis/metrics.k8s.io/v1beta1/pods
{"kind":"PodMetricsList","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/metrics.k8s.io/v1beta1/pods"},"items":[]}
```

**Comment by bskiba** [comment]
Yup, it's empty. The issue is somewhere in Metrics Server deployment. I suggest reaching out to [sig-instrumentation](https://github.com/kubernetes/community/tree/master/sig-instrumentation)
/close
