### ISSUE TITLE
VPA 0.8 may not work with Kubernetes 1.11?

### ISSUE THREAD

**Issue by mscrivo** [kubernetes/autoscaler#3174]
I tried deploying VPA to our cluster using the `vpa-up.sh` script and it completed successfully, but it was not providing any recommendations. Upon closer inspection, the admission controller logs are filled with this:

> E0602 14:17:10.800550       1 status_updater.go:56] Status update by vpa-admission-controller-6cc7d4cf6b-pzpj9 failed: the server could not find the requested resource (post leases.coordination.k8s.io)

We're using Kubernetes 1.11.6 and I tried using the 0.6.3 release of VPA and it that one works perfectly fine.

**Comment by bskiba** [comment]
Since Kubernetes is currently at 1.18 already, that is expected. I will add that information to the README.md

**Comment by bskiba** [comment]
I'll close this one out since the compatibility matrix is in the documentation now.
/close
