### ISSUE TITLE
Question - Can we extend Cluster Autoscaler and trigger scaling actions?

### ISSUE THREAD

**Issue by tomkerkhove** [kubernetes/autoscaler#3182]
Is there a way where other processes can trigger scaling actions on the Cluster Autoscaler for scenarios that are not covered out-of-the-box?

We are currently checking with [KEDA](https://keda.sh) if we can extend cluster autoscaler to eventually see if they can be proposed to Cluster Autoscaler, but I am checking if we can integrate and trigger the actions from outside the CA.

Relates to https://github.com/kedacore/keda/issues/637

**Comment by MaciekPytel** [comment]
CA model is that it looks at all pods in the cluster and provides enough (and ideally just enough) nodes so they can all schedule. There isn't really any notion of trigger or action. I guess you could think about it as a sort of reconciling controller, where the desired state is the number of nodes needed to schedule all the pods.
I guess you could technically expose CAs cloudprovider integration and ask it to create a node, but there would be no benefit over just calling provider API directly to create more nodes. And there would be nothing stopping CA from scaling-down soon after you triggered scale-up this way (as you'd now have more nodes than needed for scheduling of existing pods).

The closest thing we have to what you're asking is triggering scale-up by creating dummy pods as described in [1]. There were many proposals in the past to extend CA with an API that would provide similar capability, but the conclusion was that the API would have to include full pod spec and there is no clear benefit for creating CRD with podSpec inside over just creating low-priority pods.

[1] https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler

**Comment by tomkerkhove** [comment]
Thanks for that. Are there plans to be able to provide integration from other components s that CA would be the central point for cluster autoscaling inside the cluster; while being open to other components?

Simple example, if KEDA detects that there is a high spike in work and it will scale the deployments to 1000 instances we could schedule them all and wait for CA to kick in; or we notify the CA about this and pro-actively scale-out to reduce the time-to-scale.

**Comment by MaciekPytel** [comment]
Sorry for just reiterating what I said above during kubecon Q&A. To give you a slightly more detailed answer: CA uses pending pods as a signal and I'm not aware of any plan to fundamentally change that. It would likely require complete refactoring of the current logic. 

So the signal needs to somehow fit into the existing algorithm. Also a big issue is how to prevent CA from scaling-down those extra nodes? How would it know for how long it's supposed to keep them around? One idea for triggering scale-up faster that has popped up a few times was to inject fake pod objects into CA logic and those fake pods could trigger scale-up. That can certainly be done (though it's not super simple to implement) - some sort of CRD API could allow creating those fake pods. 

The reason why we haven't done it is that we haven't found any clear advantage of such API over just creating low-priority pods I mentioned above. After all the CRD would need a pod spec (or at least parts related to scheduling) and you'd need to remove it once the extra capacity is no longer needed. At this point it feels like there is no significant difference between that and using pods.

Regarding your example - if the spike has already hit you may as well add those 1000 pods. CA will react to them next time it runs its loop, I don't think calling it directly would significantly speed things up (presumably CA would still need to run its binpacking logic to figure out how many nodes are needed). If you know ahead of time, using low-priority pods is the most popular solution. I'm happy to revisit adding an API to autoscaler if we can come up with a way to make it better than low-priority pods, while still fitting into the general pod-binpacking model.

**Comment by tomkerkhove** [comment]
Thanks for the thorough answer and sorry for not responding.

I'll look at the fake pod route. The only argument for the API would be to make this transparent to users by not having random pods show up to trigger the scaling which would make the user experience better, but that might not be enough for the effort to implement it.
