### ISSUE TITLE
Cluster Autoscaler CAPI provider only supports merged clusters

### ISSUE THREAD

**Issue by elmiko** [kubernetes/autoscaler#3196]
The CAPI project defines multiple ways to deploy the controllers and resources that define its behavior. The primary method described in the [quickstart documentation](https://cluster-api.sigs.k8s.io/user/quick-start.html) involves creating a kubernetes management cluster which hosts the CAPI resources, and then using that management cluster to create workload clusters (these are separate kubernetes installations). This presents some challenges when a user wants to integrate a cluster autoscaler into their workload clusters.

The CAPI project does support users moving their management configuration into their workload clusters, essentially joining the two into a single cluster (see the [clusterctl move command](https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html)). This joining operation will allow a user to run a cluster autoscaler in their workload cluster, but it effectively reduces one of the primary use cases for CAPI.

This issue is being created to help track the efforts around creating a plan to address this gap in functionality. There are several ways to address this problem, and it is possible that a solution could be reached without changing the autoscaler, but as this issue is primarily with autoscaler integration this issue is being created here.

**user story**

as a CAPI user, i would like to be able to utilize cluster autoscaling in my workload clusters while retaining a separate management cluster to track and control the lifecycle of my workload clusters.

/area provider/cluster-api

**Comment by detiber** [comment]
Related PRs: https://github.com/kubernetes/autoscaler/pull/3314 https://github.com/kubernetes/autoscaler/pull/3203

With the above PRs, you should be able to deploy a copy of the autoscaler for each workload cluster you have. The simplest deployment method would be to deploy the autoscaler deployments to the management cluster, mounting the kubeconfig secret for the workload cluster, and setting the appropriate command line flags (the README updates should cover how to set them).

**Comment by elmiko** [comment]
that's a good distinction to draw out Ben. imo, it _sounds_ like a large architectural undertaking given that currently the autoscaler is assumed to be in a mostly 1:1 relationship with the cluster it manges (1 autoscaler per cluster). i know folks are able to run multiple autoscalers and that there are ways to label and segment the nodes and pods they watch. changing the autoscaler to have the ability to watch multiple clusters sounds intimidating to me, perhaps i'm over-complicating it though.
