### ISSUE TITLE
CA MAAS provider proposition

### ISSUE THREAD

**Issue by miguescri** [kubernetes/autoscaler#3204]
I miss a simple baremetal provider for Cluster Autoscaler and I'm thinking about coding a provider for Canonical's [MAAS](https://maas.io/) to spin up physical servers in your datacenter.

- Would this be interesting enough to be merged and maintained?
- Is there someone interested in providing me mentoring and guidance to build a MVP?
- In order to connect to the MAAS server, I intended to use the [Go bindings](https://github.com/juju/gomaasapi) developped by Juju's team. This library, however, doesn't appear to have any release system or CI in place. Would this be a no-no as a dependency? Should it be forked or integrated into the provider's codebase?

Thanks.

**Comment by MaciekPytel** [comment]
Sorry, I missed this earlier. We're happy to accept more provider integrations, but we (core developers) are unable to even support existing ones anymore. Instead each provider has its own owners who maintain it. So a prerequisite to accepting a new provider would be to have someone willing to take responsibility for it.

/remove-lifecycle rotten

**Comment by miguescri** [comment]
Understood. And about this?

>
>  In order to connect to the MAAS server, I intended to use the [Go bindings](https://github.com/juju/gomaasapi) developped by Juju's team. This library, however, doesn't appear to have any release system or CI in place. Would this be a no-no as a dependency? Should it be forked or integrated into the provider's codebase?
>

**Comment by Bessonov** [comment]
Hey @miguescri I would like to invite you to collaborate on https://github.com/kubernetes/autoscaler/pull/3140 .
