### ISSUE TITLE
CA - Shows master nodes when are not tagged

### ISSUE THREAD

**Issue by dignajar** [kubernetes/autoscaler#3212]
I noticed in Prometheus metrics `cluster_autoscaler_nodes_count` is equal to the total of nodes of the cluster (masters + workers), looks stupid my assumption but why the CA is aware of the master nodes when I didn't tag them.

I have 3 ASG for master nodes:
```
master-a
master-b
master-c
```

I have 1 ASG for worker nodes which is tagged with the labels `k8s.io/cluster-autoscaler/mysupercluster` and `k8s.io/cluster-autoscaler/enabled`
```
workers-a
```

CA command
```
command:
  - ./cluster-autoscaler
  - --v=4
  - --stderrthreshold=info
  - --cloud-provider=aws
  - --skip-nodes-with-local-storage=false
  - --expander=least-waste
  - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/mysupercluster
```

Prometheus metric
```
sum(cluster_autoscaler_nodes_count) = 5
```

CA logs
```
I0609 08:41:58.738627       1 auto_scaling_groups.go:354] Regenerating instance to ASG map for ASGs: [workers-a]
I0609 08:41:58.919515       1 auto_scaling_groups.go:116] Updating ASG workers-a
....
I0609 08:42:08.964532       1 pre_filtering_processor.go:57] Skipping ip-172-10-44-188.eu-west-1.compute.internal - no node group config
I0609 08:42:08.964555       1 pre_filtering_processor.go:57] Skipping ip-172-10-46-214.eu-west-1.compute.internal - no node group config
I0609 08:42:08.964565       1 pre_filtering_processor.go:57] Skipping ip-172-10-45-209.eu-west-1.compute.internal - no node group config
I0609 08:42:08.964545       1 pre_filtering_processor.go:66] Skipping ip-172-10-44-140.eu-west-1.compute.internal - node group min size reached
I0609 08:42:08.96478
```

The logs show the master nodes as `no node group config` and the worker nodes `node group min size reached`, also the ASG is correctly detected `Regenerating instance to ASG map for ASGs: [workers-a]`

I don't understand why the master nodes appear in the logs and also the Prometheus metrics show them.

**Comment by MaciekPytel** [comment]
Cluster Autoscaler gets all nodes from Kubernetes API. It only autoscales the tagged ASGs, but its logic needs to take into account all nodes.
For example you may have autoscaled and non-autoscaled worker nodes in the cluster. If there is a pending pod CA needs to check if it can be scheduled on existing nodes before triggering scale-up. Maybe a pod can be scheduled on one of existing non-autoscaled nodes and scheduler just haven't done it yet? In this case no scale-up should happen.
Similarly when scaling-down CA checks if pods can be moved to other nodes in the cluster, including on non-autoscaled nodes.

**Comment by dignajar** [comment]
Who decided to which node goes the pods is the Kubernetes scheduler and not the CA.

The CA is only for scale-down (when the nodes are idle) and scale-up (when the pods don't fits in any of the current nodes).

Or I have the wrong idea about the CA ?

**Comment by MaciekPytel** [comment]
Correct on what CA does. But the way CA works is by embedding scheduler code and predicting what would scheduler do in a given scenario. It can take scheduler time to schedule pod and in order to avoid races CA checks if a pod is schedulable on some of existing nodes.
And the criteria for scale-down is whether all the pods can be rescheduled on other node in the cluster. Checking that requires full list of nodes.
