### ISSUE TITLE
Question - add burst capacity

### ISSUE THREAD

**Issue by mattyev87** [kubernetes/autoscaler#3213]
is it possible to add burst capacity to the autoscaler, or change that scaling sensitivity (similar to how a standard auto scaling rule allows you too target an average CPU%)?

I'd like to over provision the cluster to allow for burst in traffic.
which mean either constantly having a couple of extra nodes in the k8s cluster, or some how leaving a percentage of each node unused. 
is either of these option possible?

**Comment by MaciekPytel** [comment]
We recommend using scheduler priority and preemption feature for this use-case: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler.

The feature was discussed many times in the past, but the conclusion was that it's very hard to define what something like "20% overprovisioning" means in a cluster with many node pools with conflicting labels and taints, spots / preemptibles and resource fragmentation (is it ok if I have 10 nodes with 20% CPU free on each of those? or do I need 2 empty nodes? how would we even achieve the latter given that scheduler prefers equal spreading of pods?).
The consensus was it's hard to define a simple definition that works across different use-cases and running dummy pods that represent overprovisioning buffer seems to work well enough.

**Comment by mattyev87** [comment]
cheers.
that answers my question 👍
