### ISSUE TITLE
CA cannot authenticate 

### ISSUE THREAD

**Issue by pysiekytel** [kubernetes/autoscaler#3215]
I installed `autoscaler` using latest `helm chart` (https://github.com/helm/charts/tree/master/stable/cluster-autoscaler).

My config looks like:

```
  - command:
    - ./cluster-autoscaler
    - --cloud-provider=aws
    - --namespace=kube-system
    - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/test-a
    - --logtostderr=true
    - --stderrthreshold=info
    - --v=4
    env:
    - name: AWS_REGION
      value: us-east-1
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::XXX:role/test-a-cluster-autoscaler_role
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.16.5
```

Container exits with error:
```
E0609 12:10:41.324379       1 aws_manager.go:259] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-1.amazonaws.com/id/XXX
    status code: 400, request id: XXX
F0609 12:10:41.324403       1 aws_cloud_provider.go:376] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.us-east-1.amazonaws.com/id/XXX
    status code: 400, request id: XXX
```

I don't have any OpenIDConnect provider configured in AWS. I want to authenticate with IAM role.
How can I achieve this?

**Comment by ellistarn** [comment]
There are instructions here for authenticating using OIDC: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/CA_with_AWS_IAM_OIDC.md

Alternatively, IIUC, as long as your pod's IAM role has access to the necessary CA required permissions, it should "just work".

**Comment by pysiekytel** [comment]
OK it was my fault, because I was setting `rbac.serviceAccountAnnotations.eks.amazonaws.com/role-arn` in helm chart.
Because of that `cluster autoscaler` tries to authenticate with `OIDC`.

**Comment by jesher** [comment]
> OK it was my fault, because I was setting `rbac.serviceAccountAnnotations.eks.amazonaws.com/role-arn` in helm chart.
> Because of that `cluster autoscaler` tries to authenticate with `OIDC`.

@pysiekytel  how did you solve it? I have the same problem

**Comment by donovanmuller** [comment]
@jesher if you want to use IRSA and you get this error see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/965#issuecomment-694750904 this solved it for me. I am using Terraform, so the below is all I needed to add:

```hcl
data "tls_certificate" "example" {
  url = aws_eks_cluster.example.identity[0].oidc[0].issuer
}

resource "aws_iam_openid_connect_provider" "example" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.example.certificates[0].sha1_fingerprint]
  url             = aws_eks_cluster.example.identity[0].oidc[0].issuer
}
```

**Comment by hbceylan** [comment]
If you are using [EKS terraform module](https://github.com/terraform-aws-modules/terraform-aws-eks) you just need to enable irsa by adding the following; 

`enable enable_irsa=true`

**Comment by qbasicer** [comment]
> If you are using EKS terraform module you just need to enable irsa by adding the following;
> `enable enable_irsa=true`

This isn't working for me.  IRSA is already enabled and still seeing errors.

**Comment by Snehil03** [comment]
enable_irsa=true will create OIDC connect for you.

**Comment by fanchuanster** [comment]
I encountered the same issue, 

Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

resolved by strictly following the guide to create/override serviceaccount for the CA
https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html#create-service-account-iam-policy

I got the error when created a role and policy manually, and annotate the role to the serviceaccount.
Hope it helps.

**Comment by mbeaucha** [comment]
ALCON, note that you can also get this exact same error (despite having OIDC/role/policy setup correctly) if you don't correctly set the awsRegion value, which defaults to us-east-1 (in Helm deployment). When following Amazon's Docs originally and directly applying the config I didn't have an issue (running in GovCloud), but when I changed over to using the Helm deployment this issue bit me.
