### ISSUE TITLE
missing release and tag for addon resizer 1.8.10

### ISSUE THREAD

**Issue by sozercan** [kubernetes/autoscaler#3218]
release is cut https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/addon-resizer@sha256:0f3211a5a72030291f06d56b3c2bd10a942f54e4752ba6ba710dfafd5d44a9f3/details?tab=info

but 

https://github.com/kubernetes/autoscaler/tree/addon-resizer-1.8.10 and https://github.com/kubernetes/autoscaler/releases/tag/addon-resizer-1.8.10 is missing

**Comment by bskiba** [comment]
Fixed, sorry for the delay!
/close
