### ISSUE TITLE
cluster-autoscaler: vendored scheduler dependency must be updated ASAP

### ISSUE THREAD

**Issue by aermakov-zalando** [kubernetes/autoscaler#3224]
In https://github.com/kubernetes/kubernetes/pull/89222, the scheduler algorithm was slightly tweaked to consider init containers when calculating how many resources a pod takes on a node. This went into [at least 1.17.6](https://github.com/kubernetes/kubernetes/pull/90414) (which we currently run) and I guess the corresponding 1.18.x/1.19.x versions. CA has the scheduler as a vendored dependency and there was no corresponding release, which means that every cluster running Kubernetes 1.17.6 can easily go into a situation where CA won't scale up even though the pods can't be scheduled. This happens if you have pods whose initContainer requests are bigger than their main container requests; the scheduler in this case will refuse to schedule but CA will also not do anything since it'll think that a pod could be scheduled.
Other than updating the dependencies, I'd suggest collaborating more closely with sig-scheduling, because any changes in the scheduler might affect CA and they might need to be released in lockstep.

**Comment by MaciekPytel** [comment]
Thanks for bringing this up. I'm discussing with sig-scheduling how to handle this. 
It's should be a straightforward dependency bump for all versions _except_ 1.17. 1.17 CA relies on a commit that is not on 1.17 branch in k/k, so we can't update dependencies there. We're looking to see if we can cherry-pick the required changes on 1.17 branch in k/k, but that will probably take a while.

**Comment by aermakov-zalando** [comment]
We run our own fork (still based on 1.12.2) and we already [fixed it there](https://github.com/zalando-incubator/autoscaler/pull/40) by just patching the vendored dependency, so it's not very relevant for us. You might want consider doing the same in CA until you can update the dependencies properly so it works for other users.

**Comment by MaciekPytel** [comment]
1.18.2 and 1.17.3 should have fix for this issue.

**Comment by yurrriq** [comment]
This can be closed now, yeah?

**Comment by MaciekPytel** [comment]
Correct. Sorry, I forgot to close it.
