### ISSUE TITLE
Cannot get resource "cronjobs/scale" in API group "batch/v1beta1"

### ISSUE THREAD

**Issue by caslurjf** [kubernetes/autoscaler#3235]
I'm getting "ConfigUnsupported" error message. My VPA setting is:

---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: my-cronjob-name-vpa
spec:
  targetRef:
    apiVersion: "batch/v1beta1"
    kind: CronJob
    name: my-cronjob-name
  updatePolicy:
    updateMode: "Off"  
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1
          memory: "1Gi"
        maxAllowed:
          cpu: 2
          memory: "3Gi"
        controlledResources: ["cpu", "memory"]
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob-name
  namespace: <KUBE_NAMESPACE>
...
am I doing wrong ?

**Comment by bskiba** [comment]
Which VPA version is it? 
CronJob support was introduced in [0.7 release](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.7.0)

**Comment by caslurjf** [comment]
> Which VPA version is it?
> CronJob support was introduced in [0.7 release](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.7.0)

I'm using [0.8 release](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.8.0)
![image](https://user-images.githubusercontent.com/45827406/85564261-7e1a5200-b604-11ea-9a82-4631fb46049d.png)

**Comment by bskiba** [comment]
Hm, that is unexpected, we actually have e2e tests confirming we provide recommendations for CronJobs:
![image](https://user-images.githubusercontent.com/3731277/85565331-555b8200-b62f-11ea-8ad7-3f6c6e83a9d6.png)

Could you share the status of VPA object and/or vpa-recommender logs?

**Comment by caslurjf** [comment]
![image](https://user-images.githubusercontent.com/45827406/85593374-5be0fe00-b61d-11ea-93a4-6f9f4f91fa7d.png)

**Comment by bskiba** [comment]
Can you try 
`
$ kubectl get ClusterRole system:vpa-target-reader -o yaml
`

**Comment by bskiba** [comment]
Ah, wait, the Kind is actually Cron**J**ob and your targetRef form VPA object is Cron**j**ob. Can you check if fixing that helps?

**Comment by caslurjf** [comment]
@bskiba looks it worked, but now the message is "No matching VPA found"
![image](https://user-images.githubusercontent.com/45827406/85728356-37912a00-b6ce-11ea-9ed0-6b9f0f1ccc8e.png)

**Comment by bskiba** [comment]
Is your updateMode "Off" like in screenshot here: https://github.com/kubernetes/autoscaler/issues/3235#issuecomment-648921752

If you want VPA to apply recommendations you should either set the mode to Initial or Auto. See description of modes here: https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#quick-start

**Comment by caslurjf** [comment]
Changed to updateMode "Auto"
![image](https://user-images.githubusercontent.com/45827406/85746372-cad15c00-b6dc-11ea-89bf-bbd35a1b07df.png)
![image](https://user-images.githubusercontent.com/45827406/85746486-de7cc280-b6dc-11ea-9670-29d2fbe26992.png)

**Comment by caslurjf** [comment]
Any idea about why the message "No matching VPA found" continues being show ?

**Comment by caslurjf** [comment]
@bskiba , looks like vpa-recommender is looking for a deployment, not a cronjob. Is it right ?
![image](https://user-images.githubusercontent.com/45827406/86272059-5e56d100-bba4-11ea-81ad-4f21503c4e82.png)

**Comment by bskiba** [comment]
It's looking for both, you seem to have a VPA object configured on deployment in the default namespace, and the CronJob one in uat01 namespace.

For the problem of pods not matching the VPA object, could you paste spec of CronJob, Job and a pod in that job? I am interested specifically in labelSelectors and labels of the object.

**Comment by caslurjf** [comment]
I deleted VPA from default namespace, now VPA is only in uat01. Below is described job and cronjob, I uploaded the yaml file too if necessary to check further information.
![image](https://user-images.githubusercontent.com/45827406/86384818-ad186f80-bc65-11ea-8f5c-ecdd4a7a5cca.png)
![image](https://user-images.githubusercontent.com/45827406/86385290-66774500-bc66-11ea-96e2-2a46a36dbe87.png)

[rcj-homebroker-bolsa.zip](https://github.com/kubernetes/autoscaler/files/4865533/rcj-homebroker-bolsa.zip)

**Comment by caslurjf** [comment]
@bskiba Is the latest posted information enough to continue analysis?

**Comment by bskiba** [comment]
VPA looks at apiObj.Spec.JobTemplate.Spec.Template.Labels field of the cronjob to determine which pods the cronjob controlls. Is it possible for you to add that to your cronjob definition?

**Comment by caslurjf** [comment]
@bskiba In this case, how should I specify this field inside spec template

  jobTemplate:
    spec:
      activeDeadlineSeconds: 18000
      backoffLimit: 0
      **template:**
        spec:
          containers:
          - name: rcj-homebroker-bolsa
            image: <DOCKER_TAG>
            command: ["/bin/bash"]
            args: ["./processBolsa.sh"]

**Comment by bskiba** [comment]
Following should work I think:

jobTemplate:
spec:
activeDeadlineSeconds: 18000
backoffLimit: 0
template:
**metadata:
          labels:
                <label-name>: <label-value>**
spec:
containers:
- name: rcj-homebroker-bolsa
image: <DOCKER_TAG>
command: ["/bin/bash"]
args: ["./processBolsa.sh"]

template:

**Comment by caslurjf** [comment]
@bskiba , here is my updated VPA settings, unfortunately is not working properly I guess. Could you check what I'm doing wrong ? 
![image](https://user-images.githubusercontent.com/45827406/90527296-c27b2780-e147-11ea-9cc5-6ad31d06da4e.png)
![image](https://user-images.githubusercontent.com/45827406/90527563-0f5efe00-e148-11ea-9988-b012fc6df137.png)

**Comment by bskiba** [comment]
Just to double check, can you share the output of 
`kubectl get -n development cronjob`

**Comment by caslurjf** [comment]
Sure! Here it is:
![image](https://user-images.githubusercontent.com/45827406/90544057-f6147c80-e15c-11ea-9ac2-da7a73538035.png)

**Comment by caslurjf** [comment]
@bskiba any idea about what I'm doing wrong ?

**Comment by bskiba** [comment]
Honestly don't know
@krzysied @kgolab maybe you can spot some issues I am missing?
Can you maybe take a look at vpa-recommender logs to see if it has any permission issues getting the cron jobs?

**Comment by caslurjf** [comment]
@bskiba Any update about this case ?

**Comment by caslurjf** [comment]
@krzysied @kgolab @jbartosik Can you help me ?
