### ISSUE TITLE
AWS ASG | Clsuter Autoscaler | Start Instance Refresh implementation?

### ISSUE THREAD

**Issue by thunder-spb** [kubernetes/autoscaler#3238]
Hey guys,

Is there any plans to implement [Instance Refresh](https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/) for ASG? 

That would be helpful if I change instance type or launch template, for example, while upgrading AWS EKS cluster to newer version.

**Comment by ellistarn** [comment]
Hi Alexzander,
I'm trying to best understand the feature request here. As I understand it, instance refresh is best used in conjunction with an autoscaler, but not the responsibility of the autoscaler itself. The CA manages the size of your ASGs, but doesn't own the lifecycle of the ASG itself. 

Are you using managed nodes for EKS?

**Comment by thunder-spb** [comment]
Hi, not sure what managed nodes means here. if Node Group -- then no, we create ASG with Launch Templates. So since CA already controls min/max size of ASG, it can also watch Instance Type change. 
Currently to change Instance type of running nodes, I need change it in ASG, then manually `drain` them, and then, if required by resource requests, CA will scale up/down worker nodes. Actually, this feature should be optional. So CA should watch Intance Type change and "refresh" running nodes with changes.
Same for the Launch Template change.

**Comment by ellistarn** [comment]
What happens if you simply execute an InstanceRefresh on your ASG. Won't it slowly replace the nodes with your latest machinetype/amis? Why does the Cluster Autoscaler need to be involved? I'm new to this space, so I apologize if I'm misunderstanding something.

**Comment by thunder-spb** [comment]
CA remove node with `drain`, ASG InstanceRefresh will just terminate node without any pods migration.
