### ISSUE TITLE
AWS example deployments wrong?

### ISSUE THREAD

**Issue by mgier** [kubernetes/autoscaler#3239]
Hi,

we are upgrading our k8s clusters from 1.15 to 1.17 and therefor want to upgrade the cluster-autoscaler as well. I checked the example deployments for the 1.17 release and found an image tagged with v1.12.3. Is this really the right manifest for the 1.17 release? 

https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.17/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml

The image tagged with v1.12.3 is also used within the example deployments of version 1.16:

https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.16/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml

The 1.15 release contains an image tagged with v1.15:

https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.15/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-run-on-master.yaml

Best regards!

**Comment by Jeffwan** [comment]
EKS version is behind k8s version. We didn't maintain this well in examples. Please check latest https://github.com/kubernetes/autoscaler/releases  and choose the up to date version. Sorry for the confusion and I will make an update to 1.17 in master at least
