### ISSUE TITLE
Azure: cluster autoscaler incorrectly scales down cluster when Azure API calls get throttled

### ISSUE THREAD

**Issue by ArchangelSDY** [kubernetes/autoscaler#3240]
Recently we had an outage in our production environment. Cluster autoscaler incorrectly scaled down a VMSS size to a very small number which deleted almost all nodes in that VMSS.

# What happend

1. VMSS GET/LIST APIs get throttled.
2. Cluster autoscaler somehow gets restarted.
3. When cluster autoscale starts up again, the default pool size is `-1`: https://github.com/kubernetes/autoscaler/blob/67dce2e82416e8d9ffdbc95d5b70f542e591a640/cluster-autoscaler/cloudprovider/azure/azure_scale_set.go#L90-L101
4. Then when it tries to get current pool size, it calls VMSS API. However, it is throttled, so cached value is used and `-1` is returned.
https://github.com/kubernetes/autoscaler/blob/67dce2e82416e8d9ffdbc95d5b70f542e591a640/cluster-autoscaler/cloudprovider/azure/azure_scale_set.go#L197-L208
5. When it later applies the new size to VMSS, since PUT requests are not throttled, it succeeds, but with a very small `newSize`.
6. Most nodes in that VMSS are deleted.

# A real case

1. Initially we have 200 nodes in VMSS.
2. Cluster autoscaler gets restarted.
3. VMSS GET API is throttled. Pool size falls back to the default initial value `-1`.
4. Autoscaler estimates `4` new nodes are needed.
5. Autoscaler set the new VMSS size to `-1 + 4 = 3`.
6. `197` nodes are incorrectly deleted.

Logs:
```
W0624 08:20:02.462415       1 azure_scale_set.go:581] GetScaleSetVms() is throttled with message compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="OperationNotAllowed" Message="The server rejected the request because too many requests have been received for this subscription." Details=[{"code":"TooManyRequests","message":"{\"operationGroup\":\"HighCostGetVMScaleSet3Min\",\"startTime\":\"2020-06-24T08:20:02.4497053+00:00\",\"endTime\":\"2020-06-24T08:22:02.4497053+00:00\",\"allowedRequestCount\":187,\"measuredRequestCount\":220}","target":"HighCostGetVMScaleSet3Min"}] InnerError={"internalErrorCode":"TooManyRequestsReceived"}, would return the cached instances
I0624 08:20:04.178312       1 scale_up.go:434] Estimated 4 nodes needed in xxxxx-vmss
I0624 08:20:04.178330       1 scale_up.go:538] Final scale-up plan: [{xxxxx-vmss -1->3 (max: 999)}]
```

# Expected behavior

I think if we can not get current VMSS size, we should stop doing anything. We should not make any decision based on an outdated value.

**Comment by ArchangelSDY** [comment]
/kind bug
/area provider/azure

cc @feiskyer

**Comment by feiskyer** [comment]
@ArchangelSDY thanks for reporting issue. @nilo19 has opened PR #3242 to fix the bug
