### ISSUE TITLE
Full vpa e2e test is flaky 

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#3249]
Full vpa test is flaky.
https://testgrid.k8s.io/sig-autoscaling-vpa#autoscaling-vpa-full

The main contributor is "Pods under VPA have cpu requests growing with usage" (both v1 and v1beta2).
Recommender is epxected to provide recommendation between 500 and 900[mCPU], however it often is above 900.

**Comment by krzysied** [comment]
There are two things that are causing the flakiness:
- Hamster workload doesn't created perfect resource usage.
  Hamster is expected to use specific amount of resources, however the created resource usage varies. For example for required 600mCPU, hamster can temporarily create 780mCPU.
- VPA is using buckets in histograms.
  VPA doesn't store concrete value of samples; it's placing them in buckets. When value reaches the beginning of bucket range, it is stored as a value between beginning and end of the bucket range. During returning percentile for given histogram, returned value is estimated, therefore can be higher then the real sample.

**Comment by krzysied** [comment]
In the test case hamster is producing sample with value ~780mCPU. When calculating 95th percentile algorithm estimates result based on bucket ranges and samples in them. Based on VPA histogram configuration, 800mCPU is returned. This value is still below 900mCPU, however there is one additional factor in target calculation. VPA adds safety margin to the resource request - additional 15%. The final result is above 900mCPU
```
800 * 1.15 = 920[mCPU]
```

**Comment by bskiba** [comment]
Thanks @krzysied for looking into this
