### ISSUE TITLE
Getting error while running `make build` cluster autoscaler code

### ISSUE THREAD

**Issue by arashadahamad** [kubernetes/autoscaler#325]
Following are the steps which I followed

1- Get k8s.io/kubernetes and k8s.io/autoscaler source code via `go get`
2- Ran `godep restore` for k8s.io/kubernetes
3- Deleted `Godeps` and `vendor` dir from k8s.io/autoscaler/cluster-autoscaler
4- ran `fix-gopath.sh`
5- Ran `godep save ./...` in k8s.io/autoscaler/cluster-autoscaler
6- Then I ran `make build`

I am getting following error, 2-3 days before I was getting some other error and I fixed that manually  after that I was able to build now this errors is different.

rm -f cluster-autoscaler
go get github.com/tools/godep
GOOS=linux godep go build ./...
vendor/github.com/google/cadvisor/container/crio/factory.go:24:2: no buildable Go source files in /home/ubuntu/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/google/cadvisor/container/libcontainer
godep: go exit status 1
make: *** [build] Error 1

Please suggest the build steps if these are not the correct one.

**Comment by mwielgus** [comment]
I updated the godeps last Thursday. I didn't run into any issues. 
BTW, what system are you compiling your stuff on?

**Comment by arashadahamad** [comment]
I am compiling on MAC Darwin Kernel Version 16.7.0

**Comment by mwielgus** [comment]
Then please run make build-in-docker. Some packages CA transitively depends on are linux only and can be compiled only on linux. GOOS=linux is not enough.

**Comment by arashadahamad** [comment]
Thanks @mwielgus  for your help, I tried the same but getting following build error 
1st I build the `autoscaling-builder` image and then build in container(which is same as make build-in-docker). am I missing any steps ?

docker run -v `pwd`:/gopath/src/k8s.io/autoscaler/cluster-autoscaler/ autoscaling-builder:latest bash -c 'cd /gopath/src/k8s.io/autoscaler/cluster-autoscaler && make build-binary'
rm -f cluster-autoscaler
go get github.com/tools/godep
GOOS=linux godep go build -o cluster-autoscaler
# k8s.io/autoscaler/cluster-autoscaler/simulator
simulator/predicates.go:100: cannot use isNodeReadyAndSchedulablePredicate (type func(*"k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/api/core/v1".Pod, interface {}, *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error)) as type algorithm.FitPredicate in assignment
simulator/predicates.go:131: cannot use metadataProducer (type algorithm.PredicateMetadataProducer) as type algorithm.MetadataProducer in field value
simulator/predicates.go:150: cannot use isNodeReadyAndSchedulablePredicate (type func(*"k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/api/core/v1".Pod, interface {}, *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error)) as type algorithm.FitPredicate in field value
simulator/predicates.go:215: cannot use predicateMetadata (type interface {}) as type algorithm.PredicateMetadata in argument to predInfo.predicate:
	interface {} does not implement algorithm.PredicateMetadata (missing AddPod method)
godep: go exit status 2
make: *** [build-binary] Error 1
Makefile:16: recipe for target 'build-binary' failed

**Comment by ntfrnzn** [comment]
Is there a resolution here?  I see a different set of errors when running `build-in-docker` from a mac, 
```
docker run -v `pwd`:/gopath/src/k8s.io/autoscaler/cluster-autoscaler/ autoscaling-builder:latest bash -c 'cd /gopath/src/k8s.io/autoscaler/cluster-autoscaler && make build-binary'
rm -f cluster-autoscaler
go get github.com/tools/godep
GOOS=linux godep go build -o cluster-autoscaler
# k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/rancher/go-rancher/client
vendor/github.com/rancher/go-rancher/client/generated_client.go:84: undefined: LoadBalancerCookieStickinessPolicyOperations
vendor/github.com/rancher/go-rancher/client/generated_client.go:85: undefined: LoadBalancerServiceOperations
# k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/docker/docker/client
vendor/github.com/docker/docker/client/interface_stable.go:10: cannot use Client literal (type *Client) as type APIClient in assignment:
	*Client does not implement APIClient (missing ServiceLogs method)
godep: go exit status 2
make: *** [build-binary] Error 1
Makefile:16: recipe for target 'build-binary' failed
```
