### ISSUE TITLE
Required field in verticalpodautoscalers.autoscaling.k8s.io CRD is identified as diff by ArgoCD

### ISSUE THREAD

**Issue by ribbybibby** [kubernetes/autoscaler#3251]
A diff is continually identified when applying the `verticalpodautoscalers.autoscaling.k8s.io` CRD with ArgoCD. It seems to me that because the `/spec/validation/openAPIV3Schema/properties/spec/required` field is an empty list (`required: []`) it is stripped from the schema when it is applied. 

ArgoCD identifies this as a difference between git and the live state (which it technically is).

This obviously isn't technically an issue with the autoscaler but perhaps it's possible to remove what seems to me to be a redundant field?

**Comment by albertyfwu** [comment]
@ribbybibby did you ever find a workaround for this?
