### ISSUE TITLE
Update Allocatable logic for scale from 0

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#326]
cc: @bskiba @aleksandra-malinowska

**Comment by bskiba** [comment]
This affects both scale up from 0 and node autoprovisioning.

**Comment by bskiba** [comment]
Since the Node Autoprovisioning case is different technically and significantly less urgent, I will file a separate issue for it.

**Comment by mwielgus** [comment]
Fixed in #343
