### ISSUE TITLE
Does cluster autoscaler support customized cloud provider?

### ISSUE THREAD

**Issue by hustclf** [kubernetes/autoscaler#3260]
I want to use CA in private cloud,  can I develop a private cloud provider and specify it for running CA?

**Comment by MaciekPytel** [comment]
Technically - sure, you need to implement the interfaces in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go. I'd recommend using DigitalOcean provider as an example - I think it's the simplest one we have.

However, I think you will have to develop it in a fork. We're generally happy to accept support for public cloud providers or common private clouds (ex. openstack) into this repo. But if the implementation is limited to your specific private cloud I don't think we can merge it.

**Comment by hustclf** [comment]
Thanks for you advice. :)
