### ISSUE TITLE
vpa-recommender: lots of duplicate scale calls

### ISSUE THREAD

**Issue by chenchun** [kubernetes/autoscaler#3266]
All workloads are extended workloads "tapp" in my cluster. Each time vpa-recommender runs a single loop of recommendation, it calls scale api three times for each tapp. I have 2400+ tapp in my cluster, and most time of a loop are spent in [get selector and validate target ref of vpa](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L475-L477).  I have set `--kube-api-qps=1000` `--kube-api-burst=2000` to speed the loop, but it increases the pressure for kube-apiserver.

Since workloads may run for a long time, I think it's reasonable to cache scale resource with cache time tunnable.
And it seems we can't list-watch scale resource via client-go, can we add a cache for scale resource ourself?

![image](https://user-images.githubusercontent.com/985861/86310210-0a092b00-bc50-11ea-9be5-2f6459f38206.png)

**Comment by bskiba** [comment]
@chenchun Could you summarise your takeaways from the discussions in the PRs/issues around supporting watch and list for subresources? I gather the idea did not go through but I am interested in the reasons behind that.

**Comment by chenchun** [comment]
Because they think 
> `GET /apis/apps.tkestack.io/v1/namespaces/default/tapps//scale` This doesn't follow Kubernetes API conventions. The subresource endpoints belong to one resource instance, and do not support LIST operation. This is true for both built-in types and custom resources.

In my opinion, `GET /apis/apps.tkestack.io/v1/namespaces/default/tapps//scale` represents listing all tapps scale objects or `GET /apis/apps.tkestack.io/v1/watch/namespaces/default/tapps//scale` for watching all tapps scale objects  is indeed not a good idea and I can't think of a better restful uri than this. `//` is valid but don't use it. Refer [Is a URL with // in the path-section valid?](https://stackoverflow.com/questions/20523318/is-a-url-with-in-the-path-section-valid) But I do think supporting list and watch subresource for custom resources is valuable and I don't know why we can't break this convention in a way that is compatible with current usage.
