### ISSUE TITLE
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 max limit reached

### ISSUE THREAD

**Issue by YYashwanth** [kubernetes/autoscaler#3268]
Hello Team,

My cluster autoscaler is throwing up error like 

`I0702 12:46:14.945401       1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"hello-world-699d84fcc5-7c4pr", UID:"5c8782a9-0d02-4863-abc1-575ff64de782", APIVersion:"v1", ResourceVersion:"99786677", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 max limit reached`

I was not seeing this problem before upgrading EKS to 1.15.

**My previous configuration was:**
EKS: 1.14
Cluster autoscaler : 1.14.5 (Installed via helm)

**Current config:**
EKS: 1.15
Cluster autoscaler: 1.15.6 (installed by following this doco https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html)

I did not upgrade CA immediately after upgrading EKS to 1.15. When I started to see the above error, I came across this issue https://github.com/kubernetes/autoscaler/issues/2320 and they said it might be because of version mismatch. So I upgraded CA to 1.15.6 and I still see this error.

I have the tags setup as defined in the above AWS document.

Can anyone please help me understand the cause behind this and a potential solution?

Attached files:
- cluster autoscaler logs
- cluster autoscaler deployment yaml
- cluster autoscaler status configmap
[Archive.zip](https://github.com/kubernetes/autoscaler/files/4864374/Archive.zip)

**Comment by YYashwanth** [comment]
@Jeffwan @exdx Just tagging you as you have responded actively to similar issues. Sorry for tagging you this way.

**Comment by MaciekPytel** [comment]
Newer versions of Cluster Autoscaler actually describe the reason why it's not scaling-up. Previously it would just say it can't scale-up, without additional explanaition and there could be any number of very different root causes (including some caused by version mismatch).
 
In this case the reason is the "1 max limit reached" part. The way to read it is:
- 1 ASG can't be scaled-up because it already reached max size

If you had mulitple ASGs in your cluster you could see multiple reasons instead (if different ASGs couldn't be scaled-up for different reasons).

**Comment by santhoshtricon** [comment]
I too ran into same issue with  aws-eks-1.17
1 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"autoscaler-demo-ccd97bd7d-zzsrx", UID:"fc50f103-5cd8-440a-adee-eed129ab4c66", APIVersion:"v1", ResourceVersion:"14553220", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 in backoff after failed scale-up

**Comment by santhoshtricon** [comment]
@MaciekPytel @Jeffwan @exdx Please let me know if you have any solution for this issue

**Comment by MaciekPytel** [comment]
@santhoshtricon It's a different issue than the one mentioned originally - "NotTriggeredScaleUp" part is just a catch-all error for any problem that prevents autoscaling. The meaningful part of the message is what comes after the colon. In your case it says a scale-up was attempted recently (withing the last few minutes) and it failed, therefore autoscaler will temporarily avoid scaling up that particular node group.
You need to find in logs the actual attempt to scale-up and look for errors in there. I'd recommend grepping for "Final scale-up plan" in logs and checking the logs following it.

**Comment by ZiaUrRehman-GBI** [comment]
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 6 max cluster memory limit reached
