### ISSUE TITLE
"scale-down-delay-after-delete" parameter doesn't work properly

### ISSUE THREAD

**Issue by oguzhanaygn** [kubernetes/autoscaler#3273]
Hi,
I'm using cluster autoscaler on my prod EKS cluster. I'm using the config below. I'm trying to make autoscaler slower. But it doesn't wait for 10 mins to make another scale down. Scaling down is working still based on my scan-interval which is two minutes. I have two questions;
1 - Is there something wrong on my config?
2- Is there a possibility to dictate nodes to scale down one by one?
spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --v=4
        - --stderrthreshold=info
        - --cloud-provider=aws
        - --scan-interval=120s
        - --max-empty-bulk-delete=1
        - --**scale-down-delay-after-delete=600s**
        - --scale-down-unneeded-time=14m
        - --skip-nodes-with-local-storage=false
        - --scale-down-utilization-threshold=1
        - --skip-nodes-with-system-pods=true
        - --nodes=16:32:<node group 1>
        - --nodes=3:10:<node group 2>

Best Regards.

**Comment by Ahmad-AWS** [comment]
@oguzhanaygn  were you able to solve the problem ?
