### ISSUE TITLE
Unable to scale down a node when running custom controller managed pod。

### ISSUE THREAD

**Issue by QCU266** [kubernetes/autoscaler#3300]
I define a CRD that has a custom pod controller managers the pod directly. I found cluster-autoscaler are unable  to scale down a node when running the custom controller managed POD。

----
In [FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node)
```
What types of pods can prevent CA from removing a node?

* Pods that are not backed by a controller object (so not created by deployment, replica set, job, stateful set etc). *
```

**Comment by MaciekPytel** [comment]
Adding "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" annotation to your pods is the recommended solution to this problem. CA will not perform controller checks for any pods that have this annotation.

**Comment by QCU266** [comment]
> Adding "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" annotation to your pods is the recommended solution to this problem. CA will not perform controller checks for any pods that have this annotation.

@MaciekPytel  thanks，it works.
