### ISSUE TITLE
Autoscaler doesn't scale autoscaling group evenly

### ISSUE THREAD

**Issue by es1o** [kubernetes/autoscaler#3309]
I have 3 autoscaling groups:
A, B, C.

Current state:

Cluster autoscaler scales groups:
A from 1 to max
next B to max
last C to max
each group has 5 nodes max.

as result I have e.g. 5 nodes in A, 4 nodes in B and 0 in C.

Desired state:
3 nodes in A, 3 in B and 3 in C.

Is it possible to achieve that? I'd like the same number of nodes in each autoscaling group.

**Comment by tmatias** [comment]
@es1o which [expander option](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders) are you using?

**Comment by es1o** [comment]
@tmatias I use default, random.

**Comment by x13n** [comment]
Cluster Autoscaler will balance similar nodegroups when configured to do so, see [this entry in FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-that-supported-by-cluster-autoscaler). What exactly "similar" means may vary between cloud providers though.
