### ISSUE TITLE
Missing EC2 instance types

### ISSUE THREAD

**Issue by jamiebuxxx** [kubernetes/autoscaler#3310]
Hello,

I was trying to use the `c5a.large` instance type for a secondary ASG/Worker group on my K8s cluster. I'm see the following error when the CAS tries to spin up an instance:

```
Unable to build proper template node for *: ASG * uses the unknown EC2 instance type "c5a.large"
```

This is similar to #2179. I don't see this instance type listed in config on master either.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L157-L324

This isn't a blocker for me as I will just use another instance type, but I just wanted to bring this to your attention as other newer instance types could be missing as well.

Thanks!

**Comment by dschunack** [comment]
This was reported with #3256 

https://github.com/kubernetes/autoscaler/issues/3256

**Comment by gjtempleton** [comment]
This should also be resolved for those using the static instance list by #3259

**Comment by jamiebuxxx** [comment]
@gjtempleton thanks for the heads up. Will close this issue as #3259 will take care of this once merged.
