### ISSUE TITLE
Removing node even if node is not suitable for removal in EKS

### ISSUE THREAD

**Issue by milosbackonja** [kubernetes/autoscaler#3316]
I0713 23:20:01.678658       1 scale_down.go:472] Node ip-10-123-0-10.ec2.internal is not suitable for removal - cpu utilization too big (0.808290)
I0713 23:20:07.481854       1 node_tree.go:113] Removed node "ip-10-123-0-10.ec2.internal" in group "us-east-1:\x00:us-east-1a" from NodeTree

Not sure why this happened, but I believe it happened couple of times in past.
EKS 1.16.8, autoscaler 1.16.5
- command:
        - ./cluster-autoscaler
        - --v=4
        - --stderrthreshold=info
        - --cloud-provider=aws
        - --skip-nodes-with-local-storage=false
        - --nodes=9:20:some-name

**Comment by dimilov** [comment]
i had similar issue. Looks like CA ignores annotation 
cluster-autoscaler.kubernetes.io/safe-to-evict="false"
