### ISSUE TITLE
Cluster Autoscaler patch releases

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#3317]
I'm planning to build a series of Cluster Autoscaler patch releases on Tuesday 2020-07-21. Patch releases will involve bumping kubernetes dependencies to address https://github.com/kubernetes/autoscaler/issues/3224. 
If you have any other bugfix cherry-pick PRs you want included, please leave a comment here.

Tagging all cloudprovider owners for visibility:
cc: @ringtail @Jeffwan @jaypipes @feiskyer @marwanad @nilo19 @hello2mao @frobware @enxebre @elmiko @hardikdr @detiber @ncdc @andrewsykim @MorrisLaw @tghartland @mwielgus @gjtempleton (really sorry if I missed anyone)

**Comment by gjtempleton** [comment]
From the AWS side, I think we definitely want to ensure that https://github.com/kubernetes/autoscaler/pull/3185 is Cherry-picked as far back as possible as a bug fix (@Jeffwan could you confirm?)

**Comment by marwanad** [comment]
Can we get this #3326 merged to master before the 1.19 cut? Tests pass but master is in a broken state.

**Comment by MaciekPytel** [comment]
@gjtempleton @Jeffwan @jaypipes Can you open cherry-picks if you think this is needed? I can wait until tomorrow or Thursday if needed with cutting the release.

@marwanad Merged, sorry for the presubmit issue.

**Comment by MaciekPytel** [comment]
Status update - I've started to do dependency updates required to fix #3224, however, it has proved problematic for 1.17 (apparently go.mod in kubernetes/kubernetes lists the wrong go version, which breaks our vendoring process). There may be some additional delay, as I fix this issue.

**Comment by nigelellis** [comment]
Can we also please pull in https://github.com/kubernetes/autoscaler/pull/3124?   A cherrypick for 1.16 was already opened as https://github.com/kubernetes/autoscaler/pull/3248.

Thanks.

**Comment by johanneswuerbach** [comment]
Could you also pull in https://github.com/kubernetes/autoscaler/pull/3359? Sadly this isn't easily applicable to 1.17.

**Comment by MaciekPytel** [comment]
@nigelellis @johanneswuerbach Done.

Are there any changes anyone would like to highlight in release notes?
@feiskyer @marwanad - You had a lot of cherry-pick for Azure, do you like to highlight anything?
@frobware @enxebre @elmiko @hardikdr @detiber @ncdc - For Cluster API.
@gjtempleton @Jeffwan - For AWS.

**Comment by marwanad** [comment]
@MaciekPytel "bug fixes and improvements" 😆 . I think "Various improvements to scale down scenarios" would capture them all.

**Comment by MaciekPytel** [comment]
@marwanad I was wondering about cherry-picks of #3019. I guess that's just a bugfix on AKS, but I wonder if it won't require updating labels in some self-hosted clusters running on Azure. WDYT?

**Comment by marwanad** [comment]
@MaciekPytel So this [label](https://github.com/Azure/aks-engine/blob/a1870f9a3ec6668515065df1bd41c6d37bff132b/pkg/api/types.go#L1752-L1754) comes from AKS-Engine (which is what most people use for self-hosted K8s on Azure) and isn't AKS specific. We should definitely call that out in the release, though.

**Comment by MaciekPytel** [comment]
I released 1.18.2 and 1.17.3. Please let me know if any release notes are missing or need to be corrected and I'll fix it.
I'm planning to do 1.16 release in the next few days, but this is blocked on unittests failing on 1.16 branch. Hopefully it should be fixed in the next few days.

**Comment by nigelellis** [comment]
Thank you @MaciekPytel, much appreciated!

**Comment by nigelellis** [comment]
I deployed the 1.17.3 release and can confirm that https://github.com/kubernetes/autoscaler/pull/3124 has fixed my lopsided AWS auto-scaler issues.   I now see an even spread of nodes provisioned across SPOT compute ASGs in AWS.  Thanks again for the backport and to @joelsmith for the original fix.

**Comment by Jeffwan** [comment]
Working on other stuffs and have some delay on this. I will double check cherry-pick candidates for 1.16 and below. i will come back asap.

**Comment by MaciekPytel** [comment]
I released 1.16.6 and 1.15.7 and so I'm closing this issue. 

If I missed anything important in release notes or you otherwise think they need to be corrected please let me know and I'll update them.

**Comment by Jeffwan** [comment]
@MaciekPytel Thanks.
