### ISSUE TITLE
Adopt Cluster Autoscaler Helm chart

### ISSUE THREAD

**Issue by sc250024** [kubernetes/autoscaler#3318]
# Description

Since the Helm stable channel will be deprecated eventually, I'm wondering if it's possible that this repository can adopt the [`stable/cluster-autoscaler`](https://hub.helm.sh/charts/stable/cluster-autoscaler) Helm chart into this repository?

Other projects are doing the same, notably NGINX Ingress (https://github.com/kubernetes/ingress-nginx) and Kubernetes dashboard (https://github.com/kubernetes/dashboard) as simple examples.

**Comment by gjtempleton** [comment]
Hi @sc250024 thanks for raising this

We've discussed it at the SIG Autoscaling meeting earlier today and we don't have any objection to adopting the chart going forward as long as there are people willing to maintain it going forward. I'm willing to take this on, but if there are any others who want to contribute to this please let us know.

We'll need to discuss the specifics of how we do this in more detail.

**Comment by sc250024** [comment]
@gjtempleton I would be willing to maintain it. I can open a PR for it soon.

I've noticed that the current CI process for the autoscaler is using Travis. Do you mind if the Helm chart uses GitHub actions? The reason is because there are already automated actions which handle this quite well.

- https://github.com/helm/chart-testing-action
- https://github.com/helm/chart-releaser-action

Other notable Kubernetes projects (dashboard, nginx-ingress) use these actions as well.

**Comment by gjtempleton** [comment]
I don't have an objection to Github actions given they're being used elsewhere in the k8s org already, and as you point out those seem to be well supported paths for this.

Best to get input from @MaciekPytel as well.

**Comment by MaciekPytel** [comment]
I don't have any experience with github actions, but based on the comment above I don't see any reason against using them.

**Comment by sc250024** [comment]
@MaciekPytel Cool. I'll open a PR.

**Comment by sc250024** [comment]
PR here: https://github.com/kubernetes/autoscaler/pull/3341

**Comment by stevehipwell** [comment]
We've done the same thing on the descheduler project and had the same issue around chart naming and CI (waiting on tide to support the testing action).

https://github.com/kubernetes-sigs/descheduler/issues/248

**Comment by hakman** [comment]
Hi. Quick question in case I am missing something. Should adding the `autoscaler` repo work?
```bash
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

$ helm repo add autoscaler https://kubernetes.github.io/autoscaler
Error: looks like "https://kubernetes.github.io/autoscaler" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes.github.io/autoscaler/index.yaml : 404 Not Found
```

**Comment by gjtempleton** [comment]
Hey, not yet no, we've run into some issues due to the branch protections etc. with the official chart-publisher action so haven't managed to successfully publish the required `index.yaml` to the `gh-pages` branch.

I'm currently trying to find a workaround in #3403

**Comment by hakman** [comment]
Ah. Thanks for the explanation @gjtempleton :).

**Comment by searsaw** [comment]
@gjtempleton is the recommendation to just keep using the previous chart in `stable` then for now until the 404 issue is resolved?

**Comment by stevehipwell** [comment]
@gjtempleton I think the maintainers on the descheduler project worked around this to get a release out.

**Comment by gjtempleton** [comment]
@stevehipwell yeah, as far as I'm aware from having had a brief look, that initial release was done via a manual PR pointing at a file generated and uploaded by the chart-releaser action. I was hoping to find a simple solution to allow an automated workflow, but I'll follow their example and publish manually as a first step as this is seemingly causing people issues.

@searsaw / others I'll generate the required PR to manually publish the initial release and try to get it merged as soon as possible.

**Comment by gjtempleton** [comment]
#3413 has now been merged and I've just validated that I can fetch the chart.

It's not ideal but a manual process will work for now, so I think this issue can now be closed.

**Comment by lexsys27** [comment]
I confirm the error is solved on my side.

```
$ helm repo add autoscaler https://kubernetes.github.io/autoscaler
"autoscaler" has been added to your repositories
```

**Comment by searsaw** [comment]
Also, I can confirm it worked for me as well. Thank you, @gjtempleton

**Comment by yurrriq** [comment]
Same. Thanks, everyone! stable/cluster-autoscaler will soon be marked deprecated by https://github.com/helm/charts/pull/23305

**Comment by stevehipwell** [comment]
The chart releaser action has been updated so it should now be possible to remove the `-chart` post-fix from the chart name while still having the tags include this.

https://github.com/helm/chart-releaser/pull/74
