### ISSUE TITLE
CA bails early if taints can't be found in GCE cloud provider

### ISSUE THREAD

**Issue by seeruk** [kubernetes/autoscaler#3322]
Due to GKE not making the cluster autoscaler configurable I've spent this evening looking into manually deploying cluster autoscaler into a GKE cluster using the GCE cloud provider. Getting it running was fine, and it was able to scale down my cluster (as I was able to configure it not to skip nodes with system pods or pods with local storage, rather than adding annotations to almost every single pod we run in the cluster).

Upon inspecting the logs though I could see an error. It was being logged several times in a row:

```
E0715 21:45:28.252965       1 templates.go:233] node_taints not found via AUTOSCALER_ENV_VARS due to error, will try NODE_TAINTS: var node_taints not found in AUTOSCALER_ENV_VARS: kube_reserved=cpu=70m,memory=1019Mi,ephemeral-storage=5Gi;node_labels=cloud.google.com/gke-netd-ready=true,cloud.google.com/gke-nodepool=standard-1a3f,cloud.google.com/gke-os-distribution=cos,cluster_name=product-cluster,iam.gke.io/gke-metadata-server-enabled=true,node.kubernetes.io/masq-agent-ds-ready=true,node_pool=standard,projectcalico.org/ds-ready=true;os=linux
E0715 21:45:28.262249       1 templates.go:233] node_taints not found via AUTOSCALER_ENV_VARS due to error, will try NODE_TAINTS: var node_taints not found in AUTOSCALER_ENV_VARS: kube_reserved=cpu=70m,memory=1019Mi,ephemeral-storage=5Gi;node_labels=cloud.google.com/gke-netd-ready=true,cloud.google.com/gke-nodepool=standard-1a3f,cloud.google.com/gke-os-distribution=cos,cluster_name=product-cluster,iam.gke.io/gke-metadata-server-enabled=true,node.kubernetes.io/masq-agent-ds-ready=true,node_pool=standard,projectcalico.org/ds-ready=true;os=linux
E0715 21:45:28.267422       1 templates.go:233] node_taints not found via AUTOSCALER_ENV_VARS due to error, will try NODE_TAINTS: var node_taints not found in AUTOSCALER_ENV_VARS: kube_reserved=cpu=70m,memory=1019Mi,ephemeral-storage=5Gi;node_labels=cloud.google.com/gke-netd-ready=true,cloud.google.com/gke-nodepool=standard-1a3f,cloud.google.com/gke-os-distribution=cos,cluster_name=product-cluster,iam.gke.io/gke-metadata-server-enabled=true,node.kubernetes.io/masq-agent-ds-ready=true,node_pool=standard,projectcalico.org/ds-ready=true;os=linux
```

From taking a look around the code it doesn't actually look like the code needs to bail if it hits an issue retrieving the taints. In fact, it seems like not having any taints in the Kube Env is fine (especially given GKE doesn't put any taints in it by default). From taking a look at how the other Cloud Providers work (e.g. the AWS one), their functions for retrieving taints don't return errors, and the code just continues on without them if no taints are returned.

I've applied this same logic to the GCE cloud provider locally in a fork, packaged it up into a Docker image, and deployed it into our GKE cluster; but we're operating on a cluster using Kubernetes 1.16 so the change would have to be updated for master if I were to open a pull request - I am happy to do this, but I figured it would be better to discuss what the implications of such a change could be. I may be missing some context as to why the GCE cloud provider bails early, but if it is un-necessary then I think it'd be a good step forward in allowing the autoscaler to be configurable on GKE.

This is the diff: https://github.com/kubernetes/autoscaler/compare/cluster-autoscaler-1.16.5...kurokocms:kuroko

**Comment by MaciekPytel** [comment]
IIRC this error is actually handled and it doesn't really do anything other than log on error level (the function returns an error, but that error is safely handled 2 or 3 stack frames above). I'm pretty sure those errors in logs can be just safely ignored. 
I keep meaning to clean this up, but it's been stuck in my backlog for a long time now. I'm happy to accept contributions, but your link doesn't work for me so I can't review the particular change.

Few words of warning:
 * Providers are implemented differently, they support different feature set and often have different UX (ex. autodiscovery vs static node group config), just because one provider does something in one way doesn't mean much for how other providers should work;
 * It's possible to use a GCE provider to autoscale a GKE cluster, but it only works due to implementation details of GKE and it's untested. It's not officially supported and it may stop working at any time.
   * CA can't handle various edge cases such as potential race conditions between autoscaling and GKE node upgrade. GKE autoscaler is specialized for GKE (it's not just a cloudprovider implementation).

**Comment by seeruk** [comment]
Strange about the link, it works even in incognito mode for me!

> * Providers are implemented differently, they support different feature set and often have different UX (ex. autodiscovery vs static node group config), just because one provider does something in one way doesn't mean much for how other providers should work;

Yeah, this makes sense. It does genuinely seem like this error in particular doesn't actually need to be an error. It's logged where the issue is found _and_ returned (handled twice?), and the code following it doesn't seem to depend on it (i.e. from what I can tell, it's fine for taints to be an empty slice).

Appreciate the words of warning. I am a bit uncomfortable with using this fork, but it has allowed me to at least scale down my cluster for the time being without having to fork a bunch of Helm Charts and manually spam safe-to-evict on everything. We're only really hitting this particular issue because we're using Linkerd and it creates an `emptyDir` volume. Istio does the same thing though actually, and in a cluster I have in AWS I did just add `skip-nodes-with-local-storage=false` to the startup options of our manually deployed CA there. It's just a shame we can't configure that on GKE with the built-in autoscaler.

I think in the absence of being able to provide more configuration to the GKE autoscaler I might actually instead look into creating a mutating admission controller instead that applies the `safe-to-evict` annotation unless the pod / namespace has an `unsafe-to-evict` annotation or something similar (the solution I mentioned here https://github.com/kubernetes/autoscaler/issues/966).

**Comment by MaciekPytel** [comment]
Mutating admission controller is what I usually suggest as a workaround for this issue. Unfortunately I'm not aware of a better one :(
It's a known issue and hopefully we'll have a better solution for it soon-ish.

**Comment by bcouetil** [comment]
> Due to GKE not making the cluster autoscaler configurable I've spent this evening looking into manually deploying cluster autoscaler into a GKE cluster using the GCE cloud provider. Getting it running was fine, and it was able to scale down my cluster (as I was able to configure it not to skip nodes with system pods or pods with local storage, rather than adding annotations to almost every single pod we run in the cluster).

@seeruk can you share the exact process please ? thanks ! 🙏

**Comment by seeruk** [comment]
Aah this was a good while ago now I'm afraid haha. It wasn't too dissimilar to how it worked on GCE, but it didn't work out well for us in the end, we had quite a few weird issues caused by it. In the end I did make a mutating admission controller that basically flips the default of "nothing is safe to evict" to "everything is safe to evict" unless otherwise specified. This solutions has been working much better for us, and we don't have to worry about maintaining a fork of the autoscaler.

**Comment by bcouetil** [comment]
Thank you for your quick response.

Understood. So for now I will set every deployment's pod templates of kube-system to safe-to-evict :

```
for deploy in $(kubectl -n kube-system get deployment --no-headers -o custom-columns=":metadata.name"); do
  kubectl -n kube-system patch deployment $deploy -p '{"spec":{"template":{"metadata":{"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"}}}}}'
done
```
