### ISSUE TITLE
VPA recommendation status memory unit

### ISSUE THREAD

**Issue by lli-hiya** [kubernetes/autoscaler#3323]
I set up the VPA components (release-0.8) and it mostly works but I find that the recommendation field in the VPA objects shows memory in pure Integer without any unit. 

```Status:
  Conditions:
    Last Transition Time:  2020-07-16T00:46:04Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  hamster
      Lower Bound:
        Cpu:     108m
        Memory:  52428800
      Target:
        Cpu:     126m
        Memory:  52428800
      Uncapped Target:
        Cpu:     126m
        Memory:  52428800
      Upper Bound:
        Cpu:     700m
        Memory:  52428800
```

Is there any way I can change the way Memory is represented here to something like `52Mi`?

**Comment by bskiba** [comment]
We don't have any mechanism to change that atm. It could be fixed on the presentation side in kubectl, but since VPA is a custom resource and not part of core Kubernetes, we don't have custom handling for it in kubectl.
