### ISSUE TITLE
Addon-resizer images are not promoted correctly for all architectures.

### ISSUE THREAD

**Issue by tong-luo1** [kubernetes/autoscaler#3329]
We have been looking for version `1.8.11` of the `addon-resizer-s390x` image on Google Cloud Registry.  However, we have only found version `2.1` and `2.3` at the following address - https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/addon-resizer-s390x?gcrImageListsize=30

Please let us know where we are supposed to look for the image if weren't looking at the right place.  Otherwise, we would really appreciate it if the repo owner could push version `1.8.11` of `addon-resizer-s390x` to a public cloud.  Thank you!

**Comment by bskiba** [comment]
Kubernetes is switching to a [new registry](https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/addon-resizer-s390x?gcrImageListsize=30) used to host images, as per
https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md

However the images are not there either. I am not sure why, as they should have been promoted there from [autoscaling staging repo](https://console.cloud.google.com/gcr/images/k8s-staging-autoscaling/GLOBAL/addon-resizer-s390x?gcrImageListsize=30) thanks to [this PR](https://github.com/kubernetes/k8s.io/pull/1009)/ I'll try to figure out what went wrong.

**Comment by bskiba** [comment]
Ah, wait, I know what happened. 
The images are available here: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/autoscaling/addon-resizer-s390x?gcrImageListsize=30
(note this points to the US repo, but EU and ASIA are also available)

**Comment by tong-luo1** [comment]
Thank you for your help!
