### ISSUE TITLE
AWS: unexpected ASG node termination during CA scaledown 

### ISSUE THREAD

**Issue by zagr0** [kubernetes/autoscaler#3342]
hi, we have regular issue happens once a day during CA scales down the cluster in AWS (not every scaledown, ~1 of 10-20)

from CA logs I see that there is usual scale down, node is evicted and then removing, there is desired count changed 5->4 on ASG
during the node actual removing, somehow desired count changed back 4->5, ASG bring new node to the cluster
in CA logs there is

```Jul 21, 2020 @ 22:58:19.508 | I0721 19:58:19.508362       1 static_autoscaler.go:255] 1 unregistered nodes present```
after node removing have been finished desired count again changed 5->4
that triggers unexpected random node removing by ASG that is not controlled by CA

![image](https://user-images.githubusercontent.com/19431669/88263904-80d79800-ccd3-11ea-9e22-ab23f2c3ecd6.png)

**Comment by zagr0** [comment]
cluster-autoscaler:v1.15.6
kubernetes v1.15.10

the issue looks very similar to
https://github.com/kubernetes/autoscaler/issues/2787

**Comment by hrzbrg** [comment]
Hey @zagr0,

did you find any solution for this so far? I'm experiencing the same behavior in our ASGs at the moment and by now suspended the `Termination` process on the ASG as mentioned in #2787. 

cluster-autoscaler:v1.17.2
kubernetes v1.17.9

**Comment by zagr0** [comment]
> Hey @zagr0,
> 
> did you find any solution for this so far? I'm experiencing the same behavior in our ASGs at the moment and by now suspended the `Termination` process on the ASG as mentioned in #2787.
> 
> cluster-autoscaler:v1.17.2
> kubernetes v1.17.9

Hi, yes, we applied a workaround. You will not face the issue if enable scale-in protection on ASG and instances
