### ISSUE TITLE
VPA: Recommender Prometheus memory-save mode

### ISSUE THREAD

**Issue by povilasv** [kubernetes/autoscaler#3348]
Currently Prometheus memory-save mode works in a bit non optimal way.

We first get the whole cluster state:

https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L208

and then filter out objects that have VPA.

This will fill memory with quite a lot of metrics and has a huge impact on recommender memory usage.

I suggest we add method to `HistoryProvider`:

```
type HistoryProvider interface {
	GetClusterHistory() (map[model.PodID]*PodHistory, error)
        GetVPAClusterHistory(*VPA) (map[model.PodID]*PodHistory, error)
}
```

and then basically make Prometheus History Provider to query for each VPA's pods seperately using that method, using VPA pod selector labels.

Then memory save mode will do something like:
```
feeder.LoadVPAs()
for vpa := range vpas {
  history := GetVPAClusterHistory(vpa) 
 ....
}
```

similiar to current `InitFromCheckpoints` function https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L248
```
	feeder.LoadVPAs()

	namespaces := make(map[string]bool)
	for _, v := range feeder.clusterState.Vpas {
		namespaces[v.ID.Namespace] = true
	}

	for namespace := range namespaces {
                ...
        }
```

Thoughts?

cc @bskiba

**Comment by estahn** [comment]
The VPA query to fetch CPU metrics is currently bringing down Prometheus due to the massive amount of data being fetched.

I already reduced the history length to 1d, but it still fetches 10-thousands of samples.

```
        - --v=4
        - --stderrthreshold=info
        - --storage=prometheus
        - --prometheus-address=http://prometheus-operator-prometheus.devops.svc:9090
        - --prometheus-cadvisor-job-name=kubelet
        - --pod-namespace-label=namespace
        - --pod-name-label=pod
        - --pod-label-prefix=""
        - --container-name-label=name
        - --container-namespace-label=namespace
        - --container-pod-name-label=pod
        - --history-length=1d
        - --memory-saver
```

**Comment by povilasv** [comment]
I don't think this is getting implemented any time soon, so closing :)
