### ISSUE TITLE
CA panic (NodesHaveSameTopologyKey) in large clusters with high node churn 

### ISSUE THREAD

**Issue by CAR6807** [kubernetes/autoscaler#3368]
**CA Version:** 1.16.5
**Kubernetes Version:** 1.16.13
**Cloud Provider:** AWS

We Recently deployed CA 1.16.5 (upgraded from 1.15.4) to a 1.16.13 cluster
Cluster Autoscaler immediately ran into a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x26c6521]
goroutine 147 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util.NodesHaveSameTopologyKey(...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util/topologies.go:58
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).podMatchesPodAffinityTerms(0xc0013f7980, 0xc034264c00, 0xc0095f0000, 0xc0321a1930, 0xc02eb705a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go:1315 +0x271
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).satisfiesPodsAffinityAntiAffinity(0xc0013f7980, 0xc034264c00, 0x0, 0x0, 0xc0321a1930, 0xc032b0a720, 0x0, 0x0, 0x0, 0xc005be7d70)
```

Panic seems to coincide with known 1.16 Kube-scheduler bug:
https://github.com/kubernetes/kubernetes/issues/89410
and 
https://github.com/kubernetes/kubernetes/issues/89006

which is attributed to underlying changes in how `listing node `is implemented in 1.16 which become problematic in clusters with high node churn
https://github.com/kubernetes/kubernetes/issues/89410#issuecomment-603359361

In our case nodes are constantly added/removed due to our usage of spots instances in our cluster.

The bug is fixed in the upstream 1.16 Kubernetes(https://github.com/kubernetes/kubernetes/pull/89437/files), but it looks like CA vendor code is still on 1.16.0 

**Workaround**
We were able to workaround the issue by updating the Kubernetes Vendor packages to **v1.16.13** and building the image from source. 

Looking for this issue to be hopefully fixed in 1.16.6 CA release

**Comment by MaciekPytel** [comment]
Thanks for reporting this and testing the fix. I'm already planning to update vendor for 1.16.6 to address #3224, it seems like it should solve this one as well.
