### ISSUE TITLE
Unable to generate AWS EC2 Instance Types

### ISSUE THREAD

**Issue by cburza** [kubernetes/autoscaler#3372]
I am currently running `k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.3` in AWS region `af-south-1`. On container startup I get the following error:

```
aws_util.go:166] Error unmarshalling http://169.254.169.254/latest/dynamic/instance-identity/document, skip...
aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list
```

I am not sure if the two are related, but `curl http://169.254.169.254/latest/dynamic/instance-identity/document` produces:

```
{
  "accountId" : "--redacted--",
  "architecture" : "x86_64",
  "availabilityZone" : "af-south-1a",
  "billingProducts" : null,
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : [ "--redacted--" ],
  "imageId" : "--redacted--",
  "instanceId" : "--redacted--",
  "instanceType" : "c5.xlarge",
  "kernelId" : null,
  "pendingTime" : "2020-07-28T17:26:17Z",
  "privateIp" : "10.0.21.44",
  "ramdiskId" : null,
  "region" : "af-south-1",
  "version" : "2017-09-30"
}
```

I suspect it is the AWS CLI that is not aware of the new `af-south-1` region?

**Comment by Jeffwan** [comment]
em. That could be an issue. In this case, please try static list. I will try best to update static list for every release @cburza

**Comment by git-heera** [comment]
I am getting similar issue

W0806 09:25:36.445902       1 a1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-east-1/index.json skipping...ws_util.go:71] Error fetching https://pricing.us-east-
F0806 09:25:36.445941       1 aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

Can you please advise

**Comment by jbrouwers** [comment]
I had the same issue on the af-south-1 region using the cluster autoscaler v1.17.3
adding --aws-use-static-instance-list=true to the command arguments seems to work fine.

**Comment by joe-carpenter** [comment]
i am also seeing this in `af-south-1`, and can confirm that the flag: `--aws-use-static-instance-list=true` gets autoscaler to start, but seems the static instance list is pretty old..

```
W0323 21:54:04.515678       1 aws_cloud_provider.go:349] Use static EC2 Instance Types and list could be outdated. Last update time: 2019-10-14
```

**Comment by fitchtech** [comment]
/reopen 

1 aws_util.go:79] Error fetching https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-west-2/index.json skipping...
aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

Using AWS autodiscovery enabled. Autoscaler image tag v1.20.0
