### ISSUE TITLE
Release notes for patch release

### ISSUE THREAD

**Issue by vivekbagade** [kubernetes/autoscaler#3383]
Hey everyone. I've created the release-1.19 branch for CA and before publishing the release I wanted to check with everyone to collect the release notes specific to cloud providers.

Please comment below with the release notes you want included so I don't miss it.

@ringtail @Jeffwan @jaypipes @feiskyer @marwanad @nilo19 @hello2mao @frobware @enxebre @elmiko @hardikdr @detiber @ncdc @andrewsykim @MorrisLaw @tghartland @mwielgus @gjtempleton

**Comment by vivekbagade** [comment]
I'm planning to publish the release tomorrow, so early responses would be greatly appreciated :) Sorry for the short notice, but we're already a bit late for the release.

**Comment by elmiko** [comment]
i created this doc with the release notes for the CAPI provider, i tried to capture all our changes since the 1.18.2 release.

@detiber ptal

https://gist.github.com/elmiko/436f559278214a8b37cb218c040ec9f7

**Comment by detiber** [comment]
@elmiko that changelog looks good to me, thanks for putting it together

**Comment by tghartland** [comment]
For magnum:

* Update to support Magnum node groups (introduced in Magnum Train).
* Add node group autodiscovery based on the group's role property.
* Cluster Autoscaler v1.19 and onwards will require Magnum Train or a later version.
  * Note on [compatibility](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-release-1.19/cluster-autoscaler/cloudprovider/magnum#compatibility).

**Comment by marwanad** [comment]
For Azure:

- Fixed the label CA uses to detect nodes with GPUs from to "accelerator" (previously was an incorrect "cloud.google.com/gke-accelerator").
- Various improvements to scale down scenarios.

cc @feiskyer @nilo19 if I missed anything.
