### ISSUE TITLE
Unable to get autoscaler to work with VMSS (unregistered nodes present)

### ISSUE THREAD

**Issue by ackerr01** [kubernetes/autoscaler#3392]
Hi I am running into a issue getting autoscaler to work correctly with vmss. Autoscaler will deploy new instances of the vmss. the new instance launches and runs the rancher import command to join the cluster however autoscaler is never able to detect that they joined the cluster and than deletes them.

I0731 14:52:03.835798       1 static_autoscaler.go:311] 1 unregistered nodes present
I0731 14:52:03.836415       1 static_autoscaler.go:389] No unschedulable pods
I0731 14:52:03.836466       1 scale_down.go:867] No candidates for scale down

NAME                      STATUS   ROLES                      AGE     VERSION
k8s-cluster1-vmss00000b   Ready    worker                     8m21s   v1.17.4
tp001                     Ready    controlplane,etcd,worker   23h     v1.17.4
tp002                     Ready    controlplane,etcd,worker   23h     v1.17.4
tp003                     Ready    controlplane,etcd,worker   23h     v1.17.4

I0731 14:56:08.675365       1 static_autoscaler.go:579] Removing unregistered node azure:///subscriptions/{removed}/resourceGroups/autoscaling/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-cluster1/virtualMachines/11

What am I missing here?

**Comment by marwanad** [comment]
Not super familiar with the rancher internals but can you paste the node spec here? Particularly, looking at the `providerId` part there.

**Comment by ackerr01** [comment]
it does not appear to have one...

apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"72:a9:a8:ab:79:31"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ip: 10.216.128.134
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4IPIPTunnelAddr: 10.42.3.1
    rke.cattle.io/external-ip: 10.216.128.134
    rke.cattle.io/internal-ip: 10.216.128.134
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2020-07-31T14:44:25Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: k8s-cluster1-vmss00000b
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: "true"
  name: k8s-cluster1-vmss00000b
  resourceVersion: "301757"
  selfLink: /api/v1/nodes/k8s-cluster1-vmss00000b
  uid: e3055f45-4394-455c-8d3c-889cc287076c
spec:
  podCIDR: 10.42.3.0/24
  podCIDRs:
  - 10.42.3.0/24
status:
  addresses:
  - address: 10.216.128.134
    type: InternalIP
  - address: k8s-cluster1-vmss00000b
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: "30436094312"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 7020540Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 33025276Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 7122940Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2020-07-31T16:56:58Z"
    lastTransitionTime: "2020-07-31T14:44:25Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2020-07-31T16:56:58Z"
    lastTransitionTime: "2020-07-31T14:44:25Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2020-07-31T16:56:58Z"
    lastTransitionTime: "2020-07-31T14:44:25Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2020-07-31T16:56:58Z"
    lastTransitionTime: "2020-07-31T14:45:25Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/rancher/hyperkube@sha256:70487c2f23337c5fa1c0e4bba06600cae3ce2bfc998adc2e17100862fad4e6c3
    - docker.io/rancher/hyperkube:v1.17.4-rancher1
    sizeBytes: 1546932268
  - names:
    - docker.io/rancher/nginx-ingress-controller@sha256:b5b59d579b7e5ff3a032db0f6dfc405dd4b7e1961307dd0926574d7182e7caf6
    - docker.io/rancher/nginx-ingress-controller:nginx-0.25.1-rancher1
    sizeBytes: 505984747
  - names:
    - docker.io/rancher/rancher-agent@sha256:a6b416d7e5f89d28f8f8a54472cabe656378bc8c1903d08e1c2e9e453cdab1ff
    - docker.io/rancher/rancher-agent:v2.4.4
    sizeBytes: 291518940
  - names:
    - docker.io/rancher/calico-node@sha256:a7c4a36eb9e71be6f007013e74b2f795d8f659eb232516df84af6f75c97fb7b1
    - docker.io/rancher/calico-node:v3.13.0
    sizeBytes: 259909302
  - names:
    - docker.io/rancher/calico-cni@sha256:4fc7a1fc57da4fce36fe4383270ad46371a4c1a74dfbf7ceaaf7ff3c1b5bf9a6
    - docker.io/rancher/calico-cni:v3.13.0
    sizeBytes: 206912767
  - names:
    - docker.io/rancher/rke-tools@sha256:167abae626d0ef9547170ba73183ef1f9b3548e6d61d590b8dfe5148f32ef0bf
    - docker.io/rancher/rke-tools:v0.1.56
    sizeBytes: 131689292
  - names:
    - docker.io/rancher/calico-pod2daemon-flexvol@sha256:43e36c722733d2e2c7a93d2b297fb2047534d11c58dd776e0cf65f2aecf8a806
    - docker.io/rancher/calico-pod2daemon-flexvol:v3.13.0
    sizeBytes: 111340826
  - names:
    - docker.io/rancher/coreos-flannel@sha256:bd76b84c74ad70368a2341c2402841b75950df881388e43fc2aca000c546653a
    - docker.io/rancher/coreos-flannel:v0.11.0
    sizeBytes: 52567296
  - names:
    - docker.io/rancher/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144
    - docker.io/rancher/pause:3.1
    sizeBytes: 742472
  nodeInfo:
    architecture: amd64
    bootID: f1055495-4043-4b35-bae7-6684761d3ace
    containerRuntimeVersion: docker://1.13.1
    kernelVersion: 3.10.0-1062.1.1.el7.x86_64
    kubeProxyVersion: v1.17.4
    kubeletVersion: v1.17.4
    machineID: 311936e2303b034fe7ef70182235b8cb
    operatingSystem: linux
    osImage: Red Hat Enterprise Linux Server 7.7 (Maipo)
    systemUUID: 88ADBA77-48DF-F748-946A-5C55F5BB88D1

**Comment by marwanad** [comment]
CA expects the `providerId` to be in the format `azure://` and it seems to be empty in this case. Again, not super familiar on the Rancher internals but it seems like a possible misconfiguration.


/area provider/azure

**Comment by ackerr01** [comment]
That's what I needed. Thanks you!!!

So I spun up a  new node & added the providerID before CA had a chance to remove it & it did come up healthy I guess I will script that in for now and look to rancher for an update in the future.

Thanks!

**Comment by marwanad** [comment]
Great! Glad that worked.

/close
