### ISSUE TITLE
Feature request: Add skip-nodes-with-jobs flag

### ISSUE THREAD

**Issue by ryanwalls** [kubernetes/autoscaler#340]
We are running many long running jobs on our infrastructure.  If utilization drops below the threshold, the node gets scaled down and the jobs get restarted.  Would be nice to have a `skip-nodes-with-jobs` flag to avoid this issue.

**Comment by mwielgus** [comment]
Please specify a restrictive pod disruption budget for your long-running jobs. Should do the trick.

**Comment by ryanwalls** [comment]
After reading up on it, I think I can get what I want with PodDisruptionBudget.  Will close.  Thanks!

**Comment by gurock-rops** [comment]
@ryanwalls were you able to get PDBs to work? As far as I can tell, PDBs don't work with Jobs (because Jobs don't have a controller that defines replicas).

@mwielgus Am I missing anything there? If not, should we re-open this for consideration?

**Comment by ryanwalls** [comment]
@gurock-rops It did work for us.  I forget what all we had to do, unfortunately.  But it is working in production today.
