### ISSUE TITLE
cluster-autoscaler for arm64

### ISSUE THREAD

**Issue by arashkaffamanesh** [kubernetes/autoscaler#3419]
how can one build the cluster-autoscaler for arm64?

**Comment by xUnholy** [comment]
Relevant issue worked on here: https://github.com/raspbernetes/multi-arch-images/issues/135

Available ARM64 image here: raspbernetes/cluster-autoscaler:cluster-autoscaler-chart-1.0.1

This would be a great addition to provide upstream support if the maintainers are willing.

**Comment by alittlec** [comment]
hi xUnholy - your image didnt' work for me. I've rebuilt one for version 1.15.7 (eks on arm preview version 1.15).

its available here alittlec/cluster-autoscaler:1.15.7

**Comment by xUnholy** [comment]
I'm only compiling for the most recent kubernetes version - good work!

**Comment by hakman** [comment]
@gjtempleton Any idea if there are any plans for this or if a PR would be accepted?

**Comment by gjtempleton** [comment]
There's not any plans to add support from it that I'm aware of currently, though I can't see why we wouldn't accept a PR for it given there's obviously a demand for it.

@MaciekPytel is the best person to confirm though.

**Comment by hakman** [comment]
Thanks @gjtempleton. Let's see what @MaciekPytel says also. Should be pretty simple to add this, I guess.

**Comment by hakman** [comment]
@MaciekPytel any thoughts on this?

**Comment by autarchprinceps** [comment]
This should be made available as a multi arch image, otherwise it randomly fails either way if run in a mixed cluster.
