### ISSUE TITLE
Failed to regenerate ASG cache: cannot autodiscover ASGs: RequestError: send request failed caused by: Post https://autoscaling.us-east-1.amazonaws.com/: x509: failed to load system roots and no roots provided; open /etc/ssl/certs/ca-certificates.crt: permission denied

### ISSUE THREAD

**Issue by b2jude** [kubernetes/autoscaler#3422]
I'm getting pod container error log  below when I deploy cluster autoscaler  deployment on EKS Cluster using terraform kubernetes provider. All autoscaler pod end with CrashLoopBackOff  status 

cluster-autoscaler-7b975f56b9-2d2d9   0/1     CrashLoopBackOff   25         115m
cluster-autoscaler-7b975f56b9-qtbbc   0/1     CrashLoopBackOff   25         115m

Failed to regenerate ASG cache: cannot autodiscover ASGs: RequestError: send request failed
caused by: Post https://autoscaling.us-east-1.amazonaws.com/: x509: failed to load system roots and no roots provided; open /etc/ssl/certs/ca-certificates.crt: permission denied

Worker Nodes Policies
===============
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}

ASG Tags applied
============
Key: k8s.io/cluster-autoscaler/enabled
Key: k8s.io/cluster-autoscaler/awsExampleClusterName

Module :  Cluster-Autoscaler module files
===========================

local.tf
====
locals {
  kubernetes_resources_labels = {
    k8s-app = "cluster-autoscaler",
    k8s-addon = "cluster-autoscaler.addons.k8s.io"
  }

  kubernetes_deployment_labels_selector = {
     "app" = "cluster-autoscaler"
  }

  kubernetes_deployment_labels = "${local.kubernetes_deployment_labels_selector}"
  kubernetes_deployment_image = "${var.kubernetes_deployment_image_registry}:${var.kubernetes_deployment_image_tag}"

  kubernetes_deployment_container_command = [
    "./cluster-autoscaler",
    "--v=4",
    "--stderrthreshold=info",
    "--cloud-provider=aws",
    "--skip-nodes-with-local-storage=${var.skip_nodes_with_local_storage}",
    "--expander=${var.expander}",
    #"--node-group-auto-discovery=asg:tag=${join(",", var.asg_tags)}",
    "--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${var.cluster_name}",
    "--aws-use-static-instance-list=true"
  ]
}

main.tf
=====
I used the input value of  the cluster-autoscler deployment manifest yaml file in this demo to create the terraform kubernetes cluster-autoscaler configuration below
wget https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml

https://aws.amazon.com/premiumsupport/knowledge-center/eks-cluster-autoscaler-setup/

resource "kubernetes_deployment" "cluster_autoscaler" {
  metadata {
    name = "${var.kubernetes_resources_name_prefix}cluster-autoscaler"
    namespace = "${var.kubernetes_namespace}"
    labels = "${local.kubernetes_resources_labels}"
  }

  spec {
    replicas = 2

    selector {
      match_labels = "${local.kubernetes_deployment_labels_selector}"
    }

    template {
      metadata {
        labels = "${local.kubernetes_deployment_labels}"
        
      }
      
      spec {
        #service_account_name = kubernetes_service_account.cluster_autoscaler.metadata.0.name
        automount_service_account_token = true
        #service_account_name = "${kubernetes_service_account.cluster_autoscaler.metadata.0.name}"
        #service_account_name = "cluster-autoscaler"
        service_account_name = "${var.kubernetes_resources_name_prefix}autoscaler-svc"
        container {
          image = "${local.kubernetes_deployment_image}"
          name = "cluster-autoscaler"

          resources{
            limits {
              cpu = "100m"
              memory = "300Mi"
            }
            requests {
              cpu = "100m"
              memory = "300Mi"
            }
          }

          command = ["${local.kubernetes_deployment_container_command}"]
          
          volume_mount {
            name = "ssl-certs"
            mount_path = "/etc/ssl/certs/ca-certificates.crt"
            read_only = true
          }
          image_pull_policy = "Always"
        }

        volume {
          name = "ssl-certs"
          host_path {
            path = "/etc/ssl/certs/ca-bundle.crt"
          }
        }

         node_selector = "${var.kubernetes_deployment_node_selector}"
      }
    }
  }
}

variables.tf
=======
variable "asg_tags" {
  type = "list"
  default = ["k8s.io/cluster-autoscaler/enabled"]
  description = "AWS AutoScalingGroup tags."
}

variable "skip_nodes_with_local_storage" {
  #type = "bool"
  default = false
  description = "Skip nodes with local storage."
}

variable "expander" {
  type = "string"
  default = "least-waste"
  description = "Expanders provide different strategies for selecting the node group to which new nodes will be added. Possible values and info here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders"
}

variable "kubernetes_namespace" {
  type = "string"
  default = "kube-system"
  description = "Kubernetes namespace to deploy cluster autoscaler."
}

variable "kubernetes_namespace_create" {
  #type = "bool"
  default = false
  description = "Do you want to create kubernetes namespace?"
}

variable "kubernetes_resources_name_prefix" {
  type = "string"
  default = ""
  description = "Prefix for kubernetes resources name. For example `tf-module-`"
}

variable "kubernetes_resources_labels" {
  type = "map"
  default = {}
  description = "Additional labels for kubernetes resources."
}

variable "kubernetes_deployment_image_registry" {
  type = "string"
  #default = "k8s.gcr.io/cluster-autoscaler"
  default = "k8s.gcr.io/autoscaling/cluster-autoscaler"
}

variable "kubernetes_deployment_image_tag" {
  type = "string"
  #default = "v1.15.1"
  default = "v1.17.3"
}

variable "kubernetes_deployment_node_selector" {
  type = "map"
  default = {}
  description = "Node selectors for kubernetes deployment"
}

variable "aws_create_iam_policy" {
  #type = "bool"
  default = true
  description = "Do you want to create AWS IAM policy?"
}

variable "aws_iam_policy_name" {
  type = "string"
  default = "KubernetesClusterAutoscaler"
  description = "Name of AWS IAM policy"
}

variable "aws_iam_role_for_policy" {
  type = "string"
  default = ""
  description = "AWS IAM Role name for attaching AWS IAM policy."
}

variable "cluster_name" {
  
}

Example.tf   Cluster-autoscaler module call
module "kubernetes_autoscaler" {
  source = "../modules/terraform-kubernetes-cluster-autoscaler-aws-master"
  cluster_name = "${module.eks.cluster_name}"
  kubernetes_deployment_image_tag = "v1.17.2"
}

**Comment by zopanix** [comment]
Hey, if you are using the AWS AMI's, you need to change the mount path of the root CA's.

Example: https://scm.dazzlingwrench.fxinnovation.com/fxinnovation-public/terraform-module-kubernetes-cluster-autoscaler
