### ISSUE TITLE
Helm Chart AWS auto discovery labels doesn't work with EKS 1.17.6

### ISSUE THREAD

**Issue by llnformer** [kubernetes/autoscaler#3423]
hi autoscaler contributors,
I have tried to follow the guide about AWS auto discovery guide mentioned here : https://github.com/helm/charts/tree/master/stable/cluster-autoscaler#aws
the tag ```k8s.io/cluster-autoscaler/enabled``` and ```node.kubernetes.io/cluster-autoscaler/enabled=true``` doesn't seem to work with EKS version 1.17.6
I have created the worker with the example provided from this terraform module: 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md
and I tried to add the tag mentioned before which result in join fail of Kubelet.
```  worker_groups_launch_template = [
    {
      name                    = "spot-1"
      override_instance_types = var.spot_instance_type_list
      spot_instance_pools     = 4
      asg_max_size            = 10
      asg_desired_capacity    = 1
      kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot,node.kubernetes.io/cluster-autoscaler/enabled=true"
      public_ip               = true
      enable_nat_gateway      = true
    }```

**Comment by ellistarn** [comment]
Were you able to get this working on another EKS version? 

As I understand it, if you try to get the kubelet to apply --node-labels, the kubelet fails to come up? Do you have any errors or logs for this kubelet? 

I wonder if perhaps --node-labels is being applied from multiple sources in this EKS version, which could lead to a conflict.

**Comment by llnformer** [comment]
It was confusion from my end about that I tried to label the nodes with the kubelet node labels argument instead to add tags to the AWS Autoscaling group directly, but I still don't know why the kubelet failed and I didn't have time for setting ssh to get the kubelet log, but I can tell the labels follow the allowed prefixes mentioned here: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction
```
  worker_groups_launch_template = [
    {
      name                    = "spot-1"
      override_instance_types = var.spot_instance_type_list
      root_volume_size        = var.k8s_root_volume_size
      spot_instance_pools     = 4
      asg_max_size            = 10
      asg_desired_capacity    = 1
      kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot"
      public_ip               = true
      enable_nat_gateway      = true
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled",
          "value"               = true,
          "propagate_at_launch" = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${local.k8s_cluster_name}",
          "value"               = "owned",
          "propagate_at_launch" = "true"
      }]
    }
  ]
```
