### ISSUE TITLE
cluster-autoscaler expose max-nodes-total as a metric

### ISSUE THREAD

**Issue by duritong** [kubernetes/autoscaler#3425]
Currently it is not easy to include the use `max-nodes-total`cli option within any metrics, except for putting it there manually.

It would be nice if the metrics endpoint also exposes the value passed to `max-nodes-total` as it could then easily be queried in prometheus e.g. to generate alerts if the amount of nodes is coming close to that value?

Why is the manual configuration not enough? `max-nodes-total` is used as a safe-guard from the cluster to go crazy and provision too many resources. But sometimes the newly demanded resources are really needed and one will tune that setting. Meaning it always need to be set in two places.

**Comment by elmiko** [comment]
although this metric would be static per deployment of the autoscaler, i think having this would also help empower users to create more alerts around this value too. thanks for the suggestion!

**Comment by MaciekPytel** [comment]
It should be fairly easy to add this and I'm happy to help review/etc.

**Comment by habibrosyad** [comment]
Exposed via #3435 as `cluster_autoscaler_max_nodes_count`.
