### ISSUE TITLE
Rebuild autoscaler binary

### ISSUE THREAD

**Issue by git-heera** [kubernetes/autoscaler#3426]
Hi,

I need to rebuild the autoscaler binary
Need to rebase image with proxy and CA cert in dockerfile

Can you please guide me steps to do the same.

Thanks
Heera

**Comment by elmiko** [comment]
assuming you are talking about the cluster-autoscaler, there is a Makefile in the cluster-autoscaler directory which can help you to build a binary and image.

the `build` target will create a binary in the local directory, the `build-in-docker` target will use a container to do the binary build (this can help if you don't have the build toolchain installed), and the `make-image` target will create a container image for you.

there is also a Dockerfile in the cluster-autoscaler directory that is used to build the container image. if you need to modify how your image is produced this is where you should look.

**Comment by git-heera** [comment]
Thanks Buddy, I completely missed the Makefile. Your answer really helped.
