### ISSUE TITLE
[VPA] New release?

### ISSUE THREAD

**Issue by hjkatz** [kubernetes/autoscaler#3427]
Is there a way to track new releases or fixes for vpa 0.8+ versions? Is there a 0.9 milestone or anything?

I'm seeing some fixes to the VPA post-0.8 for quick OOM cycles and we'd like to try out this new version to see if the vpa recommender will update recommendations faster than every ~10mins for OOM cycles.

**Comment by bskiba** [comment]
I'd like to release VPA 0.9 in the next two weeks.
