### ISSUE TITLE
Extra Ignored Labels for --balance-similar-node-groups

### ISSUE THREAD

**Issue by nalbury-handy** [kubernetes/autoscaler#3436]
While researching some proposed changes to our kube worker autoscaling groups in AWS, I was looking into using a single ASG/AZ as suggested [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-that-supported-by-cluster-autoscaler). 

We unfortunately have a service running in our cluster, which grabs all ec2 instance tags and adds them as node labels (mostly for nodeAffinity settings and prometheus queries), and because the instance "Name" tag is one of those labels, when testing the `balance-similar-node-groups` flag, cluster autoscaler sees each instance as it's own node group. 

After looking through some github issues, I saw that in the past, [kops/EKS specific labels have been added](https://github.com/kubernetes/autoscaler/pull/2207) to the default `BasicIgnoredLabels` list, and looking at the code, it appears that there's already an argument to the `CreateGenericNodeInfoComparator` function to provide `extraIgnoredLabels`?

Is there any way to provide these extra ignored labels somehow? Or even better, is there a way to ignore an entire prefix (we prefix all of the instance tag labels with `cloud.ec2`)? 

Thanks in advance!

**Comment by MaciekPytel** [comment]
I think you can just specify extra labels using CA flag: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/main.go#L173.

**Comment by nalbury-handy** [comment]
Ah didn't see those, thanks!
