### ISSUE TITLE
I want to know what the recommended values mean, which value is more suitable for me to put into my POD as the average value. In addition, what is the value of this 262144K converted into Mi and how to calculate it

### ISSUE THREAD

**Issue by zhaocheng173** [kubernetes/autoscaler#3442]
Here are my vPA recommended values
```
      Lower Bound:
        Cpu:     25m
        Memory:  262144k
      Target:
        Cpu:     25m
        Memory:  262144k
      Uncapped Target:
        Cpu:     25m
        Memory:  262144k
      Upper Bound:
        Cpu:     2651m
        Memory:  2771500k
```

**Comment by bskiba** [comment]
The values are in bytes. There is room for improvement in presentations.
The recommended value is target:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L221

/close

**Comment by zhaocheng173** [comment]
Can I change the recommended value K to M

**Comment by bskiba** [comment]
Not at the moment: https://github.com/kubernetes/autoscaler/issues/3323

**Comment by zhaocheng173** [comment]
Could you please help me calculate how much Mi is this 262144K? I don't know how to calculate it, thank you
