### ISSUE TITLE
Automatic certificate renewal for VPA

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/autoscaler#3458]
**Issue:**

I am trying to use cert-manager to manage certificates for VPA. once I update the certs I can see following error logs on `vpa-admission-controller`.

```
$ kubectl logs vpa-admission-controller-5d59454f78-6vp52 -n kube-system
I0825 13:04:06.444257       1 api.go:92] Initial VPA synced successfully
I0825 13:04:06.545592       1 fetcher.go:99] Initial sync of Job completed
I0825 13:04:06.645852       1 fetcher.go:99] Initial sync of CronJob completed
I0825 13:04:06.746085       1 fetcher.go:99] Initial sync of DaemonSet completed
I0825 13:04:06.846334       1 fetcher.go:99] Initial sync of Deployment completed
I0825 13:04:06.946585       1 fetcher.go:99] Initial sync of ReplicaSet completed
I0825 13:04:07.046803       1 fetcher.go:99] Initial sync of StatefulSet completed
I0825 13:04:07.147081       1 fetcher.go:99] Initial sync of ReplicationController completed
2020/08/25 13:06:23 http: TLS handshake error from 10.64.50.61:40156: remote error: tls: bad certificate
2020/08/25 13:06:23 http: TLS handshake error from 10.64.50.61:40164: remote error: tls: bad certificate
```

**Cause**

when we renew the certificate, it updates the secret and mutating webhook configuration. but there are still old certs in memory while VPA admission controller is running

**Resolution/Feature Request**

Adding the functionality of dynamic certificate reload will be helpful

**Comment by surajnarwade** [comment]
I would like to work to on this issue :smile_cat:

**Comment by bskiba** [comment]
/assign @surajnarwade 
Thanks, that's appreciated! Let me know if you need support, otherwise please send PRs our way :)

**Comment by rmb938** [comment]
Did this ever get worked on? If not we should re-open this issue.

**Comment by jbg** [comment]
Having the same issue here, and it doesn't seem it was ever resolved. @bskiba could this be reopened?

**Comment by L1ghtman2k** [comment]
This is likely related to this PR never getting finished https://github.com/kubernetes/autoscaler/pull/3462.

I assume a workaround could be a configuration tracking controller like wave, which would restart VPA upon cert renewal
