### ISSUE TITLE
gpuLabel detected but not used, causing additional node scale-up

### ISSUE THREAD

**Issue by ddseapy** [kubernetes/autoscaler#3464]
On aws using 1.16.3 CA after adding the gpu label/tag I can see the log indicating it's picking it up:
https://github.com/kubernetes/autoscaler/blob/e93af84596451b0a57be385ab4043cbea7c6274b/cluster-autoscaler/utils/gpu/gpu.go#L65

However it's still scaling up an additional node.

**Comment by MaciekPytel** [comment]
Is it possible that GPU driver initialization takes too long? With default settings CA would timeout scale-up after 15 minutes (ie. 15 minutes until the node is fully ready, this includes both VM creation and GPU driver installation).

**Comment by ddseapy** [comment]
That's a good thought.  However, the GPU machines successfully join the cluster and pods start running within 4-6 minutes.  I've never seen them take much longer than that, so I don't think that is the cause.
