### ISSUE TITLE
Vertical Pod Autoscaler: option to change pollInterval

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3468]
Is there an option to make pollInterval configurable? If so, are there documents on how to do this? via ENV var or another setting?

Reason being vpa-recommender is making a lot of requests and I want to reduce that by increasing the PollInterval to every minute or so.

**Comment by bskiba** [comment]
I'm not sure I understand, what kind of pollInterval are you talking about? What are we making to many requests to? Is it the API server?

**Comment by grosser** [comment]
yes, the api server.
seeing ~300 rpm

**Comment by bskiba** [comment]
You can try tweaking two parameters:
- [metricsFetcherInterval](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/main.go#L37) - determines how often the vpa-recommender calculates recommendations, you can go above the 1 minute period
- [kubeApiQps and kubeApiBurst](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/main.go#L42) - configuration of the kuberenetes client we use for sending requests to api server, lowering kubeApiQps will cause throttling the request on the client side.

Note that these may affect the freshness of recommendations, if you're seeing 300rpm then vpa-recommender is already throttled (5 requests per second is the default kubeApiQps setting). Do you know for what resource most of the requests are? How many VPA objects do you have in the cluster?

**Comment by grosser** [comment]
thx for the pointers!
we have 100+ vpa objects (one for each deployment)
it would be great if vpa could do some batch requests (stats for all
deployments) instead of doing 1 request per vpa,
but idk how hard that would be to implement.

**Comment by bskiba** [comment]
It does only 1 query for the metrics. Most calls come from modifying the VPA object status (can't be done in bulk, at most one request per VPA object) and saving checkpoint objects (can't be done in bulk, one request per VPA object) which is needed for recommendations to stay unchanged if vpa-recommender restarts. There's also a bunch of calls from informers, but those are relatively low volume list calls.

**Comment by grosser** [comment]
thx again, great info!
