### ISSUE TITLE
Correctly taint empty nodes (bring PR #333 to 0.6.x release)

### ISSUE THREAD

**Issue by markine** [kubernetes/autoscaler#347]
@mwielgus Please cherrypick/port https://github.com/kubernetes/autoscaler/pull/333 to the 0.6.x release branch. I'm debugging v0.6.0 for a race between an empty node being terminated and the k8s scheduler placing new pods on the node as it is going down. The empty vs non-empty node drain code paths are distinct. The lack of a taint on the empty node during that process causes unexpected loss of one-shot job pods. Thank you!

**Comment by mwielgus** [comment]
Fixed in #348

**Comment by aleksandra-malinowska** [comment]
@mwielgus I thought we didn't intend to merge that PR after all?
