### ISSUE TITLE
Duplicate arguments in values.yaml

### ISSUE THREAD

**Issue by neha-viswanathan** [kubernetes/autoscaler#3481]
The `values.yaml` file has duplicate arguments :

- https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler-chart/values.yaml#L119
- https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler-chart/values.yaml#L132

**Comment by gkarthiks** [comment]
corrected in the #3487 PR. So closing this issue.

/close
