### ISSUE TITLE
Request for VPA generated.proto files

### ISSUE THREAD

**Issue by Capstan** [kubernetes/autoscaler#3486]
In the Google mono-repo, we have a tool that configures Kubernetes by filling out these proto messages as an intermediate step. https://github.com/kubernetes/api includes a `generated.proto` file for each API version as generated by https://github.com/kubernetes/code-generator, and we'd like autoscaler to provide the same.

/cc @pawelz

**Comment by Capstan** [comment]
FWIW, I tried building or running `go-to-protobuf` manually but it's not quite clear how it is intended to be used, or where one comes by the `hack/boilerplate.go.txt` files. If there were some instructions, I could try to contribute it directly.

**Comment by bskiba** [comment]
I assume we would need a simplified script similar to 
https://github.com/kubernetes/kubernetes/blob/master/hack/update-generated-protobuf-dockerized.sh
with arguments as in 
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/update-codegen.sh

Is this what you had in mind?

**Comment by Capstan** [comment]
Yes, I believe so. The first definitely looks like the right avenue.
