### ISSUE TITLE
Chart release 1.0.3 not available in Repository

### ISSUE THREAD

**Issue by forsberg** [kubernetes/autoscaler#3488]
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-1.0.3 lists Chart release as 1.0.3, but it's not in the chart repository at https://kubernetes.github.io/autoscaler/index.yaml

Intended, or problem with CI/CD?

**Comment by gjtempleton** [comment]
Unfortunately the publishing to the `gh-pages` branch is currently a separate action to the CI triggered publish of the release. I've raised a PR to publish it now as I didn't have time to do so yesterday evening.

**Comment by gjtempleton** [comment]
Just been merged and confirmed it can be pulled successfully.

/close
