### ISSUE TITLE
Will there be a rancher provider?

### ISSUE THREAD

**Issue by Heiko-san** [kubernetes/autoscaler#3493]
Hi,

will there be a provider for the [Rancher](https://rancher.com/) Clustermanager in the near future?
Actually Rancher provides a simple API for scaling nodes up and down, but doesn't implement autoscaling itself.

**Comment by MaciekPytel** [comment]
That really depends on whether someone will volunteer to create and maintain it. We are happy to accept new providers integrations, but we're no longer able to even maintain existing integrations without the help of community, much less add new ones. 

Similar discussion regarding other provider: https://github.com/kubernetes/autoscaler/issues/2857.

**Comment by Heiko-san** [comment]
Is there any good Howto out there about how to create a cloud provider for this autoscaler?

**Comment by MaciekPytel** [comment]
Unfortunately there isn't one. I'd recommend using digitalocean as an example - I think it's the simplest one we have, certainly less complex than AWS.

In general the complexity of provider heavily depends on what features you want to support (scale-from-0 is where a lot of complexity come from) and what size of clusters you want to support (you need a lot of optimizations/caching if you want to go into thousands of nodes). Adding those features is probably much more complex than just implementing a basic provider.

If you do end up writing a provider and you feel like writing down the steps and documenting the process that would be very, very welcome.

**Comment by nitingadekar** [comment]
You can create custom rancher nodes and add them in the cluster, and use cluster-autoscaler based on your cloud provider. https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cluster-autoscaler/amazon/

I did this setup, but was able to achieve scaleup in rancher. I have 7 different ASGs and a cluster autoscaler for AWS ASG. 
Event always says `  Normal   NotTriggerScaleUp  49s        cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 5 node(s) didn't match node selector, 3 Insufficient cpu, 3 Insufficient memory
` 

I have verified that the pod resources request is way less than the node size, and max scalable capacity for ASG is also sufficient. 

Raising this issue separately. Any thoughts on the above will be appreciated.

**Comment by nitingadekar** [comment]
@Heiko-san Let me know if the above suggestion helps you.

**Comment by Heiko-san** [comment]
No, since we run Rancher on-premise on a vSphere platform, it doesn't really help, but thanks anyway.
