### ISSUE TITLE
Force scale down after certain amount of time

### ISSUE THREAD

**Issue by Moshem123** [kubernetes/autoscaler#3494]
I have an autoscaling group that has a very expensive instance type.
I use cluster-autoscaler to create instances if needed, however, I want to know if there's an option to force a scale-down on those instances after a certain amount of time using a label or something similar?
Alternatively, if there's no such option, I wonder if there's a way to trigger cluster-autoscaler to scale down manually instead of automatically?
Thanks.

**Comment by MaciekPytel** [comment]
No such features. CA only autoscales based on pods and there are no other triggers for it.

The usual way of dealing with this problem would be to use a combination of nodeSelector/nodeAffinity and taints to only allow pods that really need those expensive nodes to run on them and force other pods go to cheaper nodes. This way, once the pods that need expensive instances are gone those nodes will remain empty and CA will scale them down.
