### ISSUE TITLE
Whether to support the switch after deployment of VPA, similar to sidecar configuration, can globally effect my POD, otherwise I have to add in YAML myself, which seems very troublesome

### ISSUE THREAD

**Issue by zhaocheng173** [kubernetes/autoscaler#3495]
Whether to support the switch after deployment of VPA, similar to sidecar configuration, can globally effect my POD, otherwise I have to add in YAML myself, which seems very troublesome

**Comment by bskiba** [comment]
Closing in favour of #3497
/close
