### ISSUE TITLE
There is no switch for VPA. After I configure it, my POD can take effect globally, just like global parameters in K8S. Otherwise, I have to manually add the CONFIGURATION of VPA in YAML of each POD, which is very troublesome

### ISSUE THREAD

**Issue by zhaocheng173** [kubernetes/autoscaler#3497]

**Comment by zhaocheng173** [comment]
If vpa cannot take effect globally on my pod, I can only use scripts to export each configuration file, and then add the template, replace the vpa name, and then apply it. This looks very complicated, this is me I wrote a script to export the cluster file and apply it. I want to add the configuration of vpa to my original yaml, and then replace kube-system and name.

Export my cluster's existing deployment statefulset pod type yaml
```
#!/bin/env bash


i=$((0))
for n in $(kubectl get -o=custom-columns=NAMESPACE:.metadata.namespace,KIND:.kind,NAME:.metadata.name deployment,statefulset,pod --all-namespaces | grep -v 'secrets/default-token')
do
    if (( $i < 1 )); then
        namespace=$n
        i=$(($i+1))
        if [[ "$namespace" == "PersistentVolume" ]]; then
            kind=$n
            i=$(($i+1))
        fi
    elif (( $i < 2 )); then
        kind=$n
        i=$(($i+1))
    elif (( $i < 3 )); then
        name=$n
        i=$((0))
        if [[ "$namespace" != "NAMESPACE" ]]; then
            mkdir -p $namespace

            yaml=$((kubectl get $kind -o=yaml $name -n $namespace ) 2>/dev/null)
            if [[ $kind != 'Secret' || $yaml != *"type: kubernetes.io/service-account-token"* ]]; then
                echo "Saving ${namespace}/${kind}.${name}.yaml"
                kubectl get $kind -o=yaml --export $name -n $namespace > $namespace/$kind.$name.yaml
            fi
        fi
    fi
done
path=$(pwd)
for n in $(ls -d */)
do
      echo 
done

```
This is my script that uses the current yaml
```
#!/bin/env bash
path=$(pwd)
for n in $(ls -d */)
do
        for yaml in $(ls $path/$n)
        do
                echo -e "\t Importing $yaml"
                kubectl apply -f $path/$n$yaml -n ${n:0:-1}
        done
done

```
Now I want to import this vpa template into my yaml, and replace the name and kube-system with the resource objects associated with the original yaml template, so that my vpa can work normally, eliminating the need for me to manually Hundreds of pods in the cluster, added one by one
```
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: xxxx
  namespace: xxxx
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: xxxx
  updatePolicy:
    updateMode: "Off"
---
```
Who can help me add this vpa template to each yaml, and replace the related xxxx resources. The original yaml labels of the xxx source itself may also be app-k8s or app and the name seems to be uncertain. I'm very troublesome

Who has a better way？

**Comment by zhaocheng173** [comment]
Now that I'm scripting the VPA template into all current YAML, how should I replace the field of name Namespace? Who can support to write this script
```
#!/bin/env bash
for i in `ls -d */* |grep -v kube-system` ;do cat demo.txt >> $i; done
```

**Comment by zhaocheng173** [comment]
Now that I'm scripting the VPA template into all current YAML, how should I replace the field of name Namespace? Who can support to write this script
```
#!/bin/env bash
for i in `ls -d */*` ;do cat demo.txt >> $i; done
```

**Comment by bskiba** [comment]
I've seen people in the community use [Goldilocks](https://github.com/FairwindsOps/goldilocks) which can create VPA objects for all deployments in a given namespace. Would that work for you?
