### ISSUE TITLE
Prometheus alert rules for cluster autoscaler metrics

### ISSUE THREAD

**Issue by KR411-prog** [kubernetes/autoscaler#3507]
I want to create a Prometheus alert rules for below scenarios,

- Max capacity reached for the cluster
- Unusual Scaling activity

I think "Max capacity reached for the cluster" can be obtained with combination of following metrics,
1.cluster_autoscaler_unscheulable_pods_count >0
2. sum(cluster_autoscaler_unneeded_nodes_count)==0

And,"Unusual Scaling activity" can be obtained from sum(cluster_autoscaler_scaled_up_nodes_total) .

I have enabled metrics for Cluster autoscaler.However I am not sure how to create prometheus rule expressions with these metrics.Should I create any Service monitors? how to combine these metrics for the scenarios mentioned above? Do you already have examples of Prometheus rules for the Cluster autoscaler metrics?

Cluster autoscaler chart version - "1.0.2"
Kubernetes version -1.15  (EKS)

**Comment by alisachen** [comment]
@KR411-prog How to enable the metrics for cluster autoscaler?

**Comment by MaciekPytel** [comment]
I think they should be on by default, with Prometheus endpoint available on localhost:8085/metrics (you can change port with flags).

**Comment by KR411-prog** [comment]
We are installing cluster autoscaler using helm chart
https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler-chart/values.yaml#L19

And servicemonitor is enabled in the values.yaml file.
```
serviceMonitor:
  # serviceMonitor.enabled -- If true, creates a Prometheus Operator ServiceMonitor.
  enabled: false
```

**Comment by hectorj2f** [comment]
@KR411-prog Once you have the service monitor enabled, it is a matter of configuring prometheus to scrape those using that monitor. I recommend this link https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/troubleshooting.md.

**Comment by hectorj2f** [comment]
@kovalyukm From our usage, I would recommend to set alerts related SLO such as scaling above thresholds, and measuring the scaling up/down response times to be under certain boundaries.
