### ISSUE TITLE
Upgrade VPA CRD version from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by Ladicle** [kubernetes/autoscaler#3508]
CRD apiextensions.k8s.io/v1beta1 has already been deprecated in v1.16. And now that 3 versions have passed, I'd like to migrate it to v1.

**Comment by bskiba** [comment]
Sounds reasonable. 
1. Do you know if we need an upgrade story when we switch? i.e. what will happen with existing objects?
2. Are you interested in contributing? :)

**Comment by Ladicle** [comment]
> 1. Do you know if we need an upgrade story when we switch? i.e. what will happen with existing objects?

CRD v1beta1 will be removed v1.22+, so we need to support v1 before that. 
For upgrades, applying the rewritten v1 manifests does not affect an existing object. (at this time `preseveUnknownFields` is true.) This is because of k8s support API conversion. Of course, it's better to keep the v1beta1 manifest for backwards compatibility.

However, `preseveUnknownFields` became false by default at GA, so we need to set `true` or define an `openAPIV3Scheme`. Considering the future, the latter is recommended. In that case, if someone misses specifying the field, the value will be prune. I think it's better to generate `openAPIV3Schema` from `types.go` using `controller-tools`.

> 2. Are you interested in contributing? :)

Yes! I'd like to contribute. :)

**Comment by bskiba** [comment]
If you're interested, we welcome contributions :) Let me know if you need help.
