### ISSUE TITLE
Changes to scheduler Snapshot interface in k8s v1.18+

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/autoscaler#3527]
We are submitting a patch to 1.18 and 1.19 that changes the scheduler Snapshot interface: https://github.com/kubernetes/kubernetes/pull/94805

This is to help the autoscaler perform PreFilter computations faster in cases where clusters have preferred affinity pods (basically eliminate their overhead completely).

/cc @MaciekPytel

**Comment by jkaniuk** [comment]
Great!

Patches to [1.18](kubernetes/kubernetes#94805) and [1.19](https://github.com/kubernetes/kubernetes/pull/94804) have already merged.

**Comment by ahg-g** [comment]
is this done?

**Comment by jkaniuk** [comment]
/assign  @MaciekPytel 

Maciek, could you triage this?

**Comment by MaciekPytel** [comment]
I believe it's already implemented in Cluster Autoscaler in https://github.com/kubernetes/autoscaler/pull/3526.

**Comment by jkaniuk** [comment]
What you have linked was done before scheduler changes were backported.

Was #3526 included in releases for 1.18/1.19?
