### ISSUE TITLE
helm chart for Kubernetes version 1.15 and 1.16

### ISSUE THREAD

**Issue by infa-ssaurabh** [kubernetes/autoscaler#3529]
Can some one help on which helm chart should I use in EKS 1.15 and 1.16?

**Comment by neha-viswanathan** [comment]
@infa-ssaurabh maybe this can help - https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases

**Comment by tanujd11** [comment]
Adding to the same point I can't find cluster-autoscaler on a public helm repo. Why is that the case? Can anyone please clear?

**Comment by infa-ssaurabh** [comment]
@neha-viswanathan more over  the link https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases just say about the k8 version and ca version mapping. I couldn't find a guide which I can refer for 1.15 or 1.16 version installation.
