### ISSUE TITLE
Autoscaler on AWS does not scale up

### ISSUE THREAD

**Issue by zenbones** [kubernetes/autoscaler#3538]
I have an ASG with min=2, max=4. The group is composed of t3.2XLarge nodes (8 cpu). I have 2 nodes up (the min) and waiting (pending) on a pod requesting 4 cpu. I know there's enough cpu in the group if 1 more node is added, and I know this because atuo-scaling this cluster has worked and everything fits in 3 nodes, and we can get 4. The cluster was not scaling and I made some change (can't remember now) and it started scaling. I have made no changes to the setup since then. The only change was to code in a container, and now the cluster is failing to scale up once more on the latest release. I'd love to know why.

Here's the autoscaler status...

apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2020-09-23 22:55:35.15219191 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0)
                   LastProbeTime:      2020-09-23 22:55:35.151190731 +0000 UTC m=+905.054355702
                   LastTransitionTime: 2020-09-23 22:41:01.726159417 +0000 UTC m=+31.629324399
      ScaleUp:     NoActivity (ready=2 registered=2)
                   LastProbeTime:      2020-09-23 22:55:35.151190731 +0000 UTC m=+905.054355702
                   LastTransitionTime: 2020-09-23 22:41:01.726159417 +0000 UTC m=+31.629324399
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2020-09-23 22:55:35.151190731 +0000 UTC m=+905.054355702
                   LastTransitionTime: 2020-09-23 22:41:01.726159417 +0000 UTC m=+31.629324399

    NodeGroups:
      Name:        eks-18ba4bf2-c40e-822b-da5a-62f26380849b
      Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0 cloudProviderTarget=2 (minSize=2, maxSize=4))
                   LastProbeTime:      2020-09-23 22:55:35.151190731 +0000 UTC m=+905.054355702
                   LastTransitionTime: 2020-09-23 22:41:01.726159417 +0000 UTC m=+31.629324399
      ScaleUp:     NoActivity (ready=2 cloudProviderTarget=2)
                   LastProbeTime:      2020-09-23 22:55:35.151190731 +0000 UTC m=+905.054355702
                   LastTransitionTime: 2020-09-23 22:41:01.726159417 +0000 UTC m=+31.629324399
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2020-09-23 22:55:35.151190731 +0000 UTC m=+905.054355702
                   LastTransitionTime: 2020-09-23 22:41:01.726159417 +0000 UTC m=+31.629324399

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2020-09-23 22:55:35.15219191 +0000
      UTC
  creationTimestamp: "2020-09-23T21:35:36Z"
  name: cluster-autoscaler-status
  namespace: default
  resourceVersion: "16136413"
  selfLink: /api/v1/namespaces/default/configmaps/cluster-autoscaler-status
  uid: f4aebebf-50ac-4a35-ab12-5ba767adf667

-------

The relevant log excerpt...

I0923 23:09:08.587533       1 scale_down.go:867] No candidates for scale down
I0923 23:09:18.599028       1 static_autoscaler.go:226] Starting main loop
I0923 23:09:18.599423       1 filter_out_schedulable.go:60] Filtering out schedulables
I0923 23:09:18.599488       1 filter_out_schedulable.go:116] 0 pods marked as unschedulable can be scheduled.
I0923 23:09:18.599507       1 filter_out_schedulable.go:77] No schedulable pods
I0923 23:09:18.599517       1 scale_up.go:322] Pod default/absolute-epicenter-platform-s5kth is unschedulable
I0923 23:09:18.599549       1 scale_up.go:360] Upcoming 0 nodes
I0923 23:09:18.599623       1 scale_up.go:284] Pod absolute-epicenter-platform-s5kth can't be scheduled on eks-18ba4bf2-c40e-822b-da5a-62f26380849b, predicate checking error: Insufficient cpu; predicateName=NodeResourcesFit; reasons: Insufficient cpu; debugInfo=
I0923 23:09:18.599651       1 scale_up.go:433] No pod can fit to eks-18ba4bf2-c40e-822b-da5a-62f26380849b
I0923 23:09:18.599675       1 scale_up.go:437] No expansion options
I0923 23:09:18.599724       1 static_autoscaler.go:436] Calculating unneeded nodes
I0923 23:09:18.599745       1 pre_filtering_processor.go:66] Skipping ip-10-0-3-78.ec2.internal - node group min size reached
I0923 23:09:18.599753       1 pre_filtering_processor.go:66] Skipping ip-10-0-2-147.ec2.internal - node group min size reached
I0923 23:09:18.599778       1 static_autoscaler.go:490] Scale down status: unneededOnly=false lastScaleUpTime=2020-09-23 22:40:51.725772233 +0000 UTC m=+21.628937157 lastScaleDownDeleteTime=2020-09-23 22:40:51.725772304 +0000 UTC m=+21.628937229 lastScaleDownFailTime=2020-09-23 22:40:51.725772381 +0000 UTC m=+21.628937305 scaleDownForbidden=false isDeleteInProgress=false scaleDownInCooldown=false
I0923 23:09:18.599812       1 static_autoscaler.go:503] Starting scale down
I0923 23:09:18.599860       1 scale_down.go:867] No candidates for scale down
I0923 23:09:18.599848       1 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"absolute-epicenter-platform-s5kth", UID:"28749668-eb9a-4ebd-bf17-0d5f00d50ed2", APIVersion:"v1", ResourceVersion:"16134233", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 Insufficient cpu

---

And the pending pod description...

Name:           absolute-epicenter-platform-s5kth
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=epicenter-platform
                chart=epicenter-operator-1.0.0
                release=absolute
Annotations:    kubernetes.io/psp: eks.privileged
Status:         Pending
IP:
IPs:            <none>
Controlled By:  DaemonSet/absolute-epicenter-operator-bx5wb
Containers:
  epicenter-platform:
    Image:       docker.forio.com/k8s/epicenter/eks/bastille-platform:3.1.1
    Ports:       9008/TCP, 9015/TCP, 8178/TCP, 1599/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Limits:
      cpu:     4
      memory:  4160M
    Requests:
      cpu:     4
      memory:  1088M
    Environment:
      HELM_JVM_MEMORY_INIT_MB:  1024
      HELM_JVM_MEMORY_MAX_MB:   4096
      HELM_RELEASE_NAME:        absolute
      POD_NAME:                 absolute-epicenter-platform-s5kth (v1:metadata.name)
      POD_NAMESPACE:            default (v1:metadata.namespace)
      NODE_NAME:                 (v1:spec.nodeName)
    Mounts:
      /opt/epicenter/.m2/local.yaml from config (ro,path="local.yaml")
      /var/files/epicenter/projects from data (rw)
      /var/log/epicenter from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fspv2 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      epicenter-config
    Optional:  false
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-fspv2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fspv2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason             Age                    From                Message
  ----     ------             ----                   ----                -------
  Normal   NotTriggerScaleUp  4m17s (x121 over 24m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 Insufficient cpu
  Warning  FailedScheduling   42s (x17 over 24m)     default-scheduler   0/2 nodes are available: 2 Insufficient cpu.

----

Any help appreciated.

**Comment by inge4pres** [comment]
Hi @zenbones 
Reading this message
```
type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 Insufficient cpu
```
it seems that the type of instances you are trying to scale up would not suffice to schedule the workload.
You should revise the deployment/pod limits or use a bigger instance class in your ASG.

**Comment by nucleusv** [comment]
@zenbones maybe it is similar issue https://github.com/kubernetes/autoscaler/issues/3535
How do you create your ASG?

**Comment by zenbones** [comment]
In answer to inge4pres, and nice handle btw, the autoscaler is lying. The exact load I am attempting to run, was running in exactly the same ASG, not 20 minutes before this problem began. This is a helm release. I shut down the release (helm delete), made some changes to the code of one of the services running in one of the pods, changes which could have no bearing on the cpu or memory consumed, and without changing anything about the resource requests or limits, or in fact, anything at all about the structure of the release from  the perspective of either helm or k8s, simple restarted the release  (helm install), and got this problem. And this load ran fine in 3 of the 4 available nodes. The pod which will not schedule is requesting 4 cpu. The nodes have 8 cpu each. There are some daemon sets, but with what is already successfully running in the 2 nodes which are the minimum for the ASG, I know there's room because at least 4 cpu of non daemon pods are running on each of those nodes. All the nodes are the same, t3.2XLarge, and they are not spot instances. The ASG was setup through the AWS EKS online web interface by filling in the min (2), max(4) and instance type, and providing the tags for autoscaling (and they did autoscale).

**Comment by zenbones** [comment]
To be fair, I lowered the resource requirement of the pending pod to 2 cpu, and the cluster autoscaled... so now I need to figure out the math. I'll have to calculate what's running on each node and see why 4 cpu would not fit where it fit before.

**Comment by zenbones** [comment]
Odd, because looking at the 'kubectl describe node <node name>' data for each of the running nodes, which is surprisingly complete (should have done this before), the autoscaler was lying. The new node could as easily have fit the 4 cpu originally requested as it fit the 2 cpu that did autoscale. The 2 other nodes are each running a load equivalent to the 4 cpu (failed) request plus the required daemon set pods, and the node that did autoscale has more than 2 cpu still available. This looks like a bug in the autoscaler to me. Or a bug somewhere. Could easily be an interaction between the autoscaler and the way AWS is hosting it.

**Comment by ivanfoo** [comment]
Hi! We are facing a very similar issue, I think.

We have 3 ASGs that scales from/to 0 and they have been working just fine until Wednesday 23th. We checked the activity of those ASGs and the scaling up events stopped at around 6:00 GMT. It seems the autoscaler is no longer able to describe the instance specs from the ASGs (launch-configuration based). As you said, it works again when you increase the ASGs sizes by hand. In our case, we configured a min size of 1 instead of 0. The cluster-autoscaler can add and remove nodes as usual after that.

To fix it, we ended up adding extra tags to the ASGs so the cluster-autoscaler can actually have information about these groups. But it wasn't necessary until some days. At lest, it seems like that. Also, the cluster-autoscaler documentation suggests this is an optional setting: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#auto-discovery-setup

The added tags are like the following:

```
k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage: 100G
k8s.io/cluster-autoscaler/node-template/resources/cpu: 8
k8s.io/cluster-autoscaler/node-template/resources/memory: 32G
```
The ASGs are tagged with the labels used in nodeSelector/affinity rules like this:

```
k8s.io/cluster-autoscaler/node-template/label/foo: bar
```

My hope was that maybe the policy attached to the cluster-autoscaler was broken, but it is OK according to the docs: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeLaunchTemplateVersions",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:DescribeTags",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeAutoScalingGroups"
            ],
            "Resource": "*"
        }
    ]
}
```

We are running kubernetes 1.15.11 on EKS with cluster-autoscaler version 1.15.7. We tried 1.15.6 and we got the same result.

**Comment by zenbones** [comment]
I'm running 1.17.x with an autoscaler at1.18.1, which is within 1 version which should be ok. In my case lowering the cpu requirement kicked off the autoscaler and it's been fine, but tat should not have been necessary. Maybe I'll try to downgrade to autoscaler 1.17?

**Comment by MaciekPytel** [comment]
For future reference - we don't officially support any version skew in terms of minor version. Usually 1 minor is unlikely to cause any issues (but we don't promise anything). However, 1.18 had a major refactor in how scheduler and autoscaler work together and mixing pre-1.18 with post-1.18 is very likely to cause all sorts of problems.
