### ISSUE TITLE
No pods match this VPA object, targetRef controller has a parent but it should point to a topmost well-known or scalable controller

### ISSUE THREAD

**Issue by abudavis** [kubernetes/autoscaler#3539]
**Version: Deployed from master branch on 24.9.2020.
Platform: Openshift 4.5.12
"Deployment" is spun by a custom Operator**

Reference case: https://github.com/kubernetes/autoscaler/pull/2275

VPA gives the following error on startup. Any ideas? 

`$ oc describe vpa timerapp-is
Name:         timerapp-is
Namespace:    ace
Labels:       <none>
Annotations:  <none>
API Version:  autoscaling.k8s.io/v1
Kind:         VerticalPodAutoscaler
Metadata:
  Creation Timestamp:  2020-09-24T12:35:55Z
  Generation:          2
  Managed Fields:
    API Version:  autoscaling.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:resourcePolicy:
          .:
          f:containerPolicies:
        f:targetRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
        f:updatePolicy:
          .:
          f:updateMode:
    Manager:      oc
    Operation:    Update
    Time:         2020-09-24T12:35:55Z
    API Version:  autoscaling.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:recommendation:
    Manager:         recommender
    Operation:       Update
    Time:            2020-09-24T12:36:36Z
  Resource Version:  52508288
  Self Link:         /apis/autoscaling.k8s.io/v1/namespaces/ace/verticalpodautoscalers/timerapp-is
  UID:               057e017f-894a-4be3-b333-ccbd1896421d
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  *
      Controlled Resources:
        cpu
        memory
      Max Allowed:
        Cpu:     8
        Memory:  8Gi
      Min Allowed:
        Cpu:     100m
        Memory:  300Mi
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         timerapp-is
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2020-09-24T12:36:36Z
    Message:               The targetRef controller has a parent but it should point to a topmost well-known or scalable controller
    Status:                True
    Type:                  ConfigUnsupported
    Last Transition Time:  2020-09-24T12:36:36Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2020-09-24T12:36:36Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                False
    Type:                  RecommendationProvided
  Recommendation:
Events:  <none>
`

**Comment by bskiba** [comment]
Could you also provide more information on the deployment and the custom operator?
Can you provide the output of
$ kubectl describe -n kube-system vpa-recommender

**Comment by abudavis** [comment]
Tried to use the Operator version of the VPA, same error when application is a 'Deployment', see permission error below:
It however does work when application is in a 'StatefulSet'

`# oc describe pod vpa-recommender-default-68766dfb49-xrrhd 
Name:                 vpa-recommender-default-68766dfb49-xrrhd
Namespace:            apic
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 dummycluster-f5q6r-master-0/10.244.163.5
Start Time:           Mon, 05 Oct 2020 11:11:32 +0000
Labels:               app=vpa-recommender
                      pod-template-hash=68766dfb49
                      vertical-pod-autoscaler=default
Annotations:          openshift.io/scc: restricted
                      release.openshift.io/version: 0.0.1-snapshot
                      scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Running
IP:                   10.128.0.10
IPs:
  IP:           10.128.0.10
Controlled By:  ReplicaSet/vpa-recommender-default-68766dfb49
Containers:
  vertical-pod-autoscaler:
    Container ID:  cri-o://57dae74d9b2c529fb9cb09b856aa4494c09b66948e27586f6ee25382725b6729
    Image:         registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4765bbea4d65e500986aad97df2e421322bd741b7049670f6e379cf204bd57d3
    Image ID:      registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4569ed03305d8ab2e78a5a24bb1f20e6bd5f5ecc3159494a9756144c9cdcc9f9
    Port:          <none>
    Host Port:     <none>
    Command:
      recommender
    Args:
      --logtostderr
      --v=1
      --recommendation-margin-fraction=0.15
      --pod-recommendation-min-cpu-millicores=25
      --pod-recommendation-min-memory-mb=250
    State:          Running
      Started:      Mon, 05 Oct 2020 11:12:07 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        25m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from vpa-recommender-token-6l7jp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  vpa-recommender-token-6l7jp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vpa-recommender-token-6l7jp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
                 node-role.kubernetes.io/master=
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                  Message
  ----    ------     ----  ----                                  -------
  Normal  Scheduled  103m  default-scheduler                     Successfully assigned apic/vpa-recommender-default-68766dfb49-xrrhd to dummycluster-f5q6r-master-0
  Normal  Pulling    102m  kubelet, dummycluster-f5q6r-master-0  Pulling image "registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4765bbea4d65e500986aad97df2e421322bd741b7049670f6e379cf204bd57d3"
  Normal  Pulled     102m  kubelet, dummycluster-f5q6r-master-0  Successfully pulled image "registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4765bbea4d65e500986aad97df2e421322bd741b7049670f6e379cf204bd57d3"
  Normal  Created    102m  kubelet, dummycluster-f5q6r-master-0  Created container vertical-pod-autoscaler
  Normal  Started    102m  kubelet, dummycluster-f5q6r-master-0  Started container vertical-pod-autoscaler
# 
`

Error:

`# oc describe vpa dummy
Name:         dummy
Namespace:    apic
Labels:       <none>
Annotations:  <none>
API Version:  autoscaling.k8s.io/v1
Kind:         VerticalPodAutoscaler
Metadata:
  Creation Timestamp:  2020-10-05T12:18:45Z
  Generation:          2
  Managed Fields:
    API Version:  autoscaling.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:resourcePolicy:
          .:
          f:containerPolicies:
        f:targetRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
        f:updatePolicy:
          .:
          f:updateMode:
    Manager:      oc
    Operation:    Update
    Time:         2020-10-05T12:18:45Z
    API Version:  autoscaling.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:recommendation:
    Manager:         recommender
    Operation:       Update
    Time:            2020-10-05T12:19:26Z
  Resource Version:  8709242
  Self Link:         /apis/autoscaling.k8s.io/v1/namespaces/apic/verticalpodautoscalers/dummy
  UID:               4d323ccc-0372-456a-8153-e28285401885
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  *
      Controlled Resources:
        cpu
        memory
      Max Allowed:
        Cpu:     4
        Memory:  16Gi
      Min Allowed:
        Cpu:     10m
        Memory:  1Gi
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         minimum-mgmt-apim
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2020-10-05T12:19:26Z
    Message:               Error checking if target is a topmost well-known or scalable controller: Unhandled targetRef management.apiconnect.com/v1beta1 / ManagementCluster / minimum-mgmt, last error managementclusters.management.apiconnect.com "minimum-mgmt" is forbidden: User "system:serviceaccount:apic:vpa-recommender" cannot get resource "managementclusters/scale" in API group "management.apiconnect.com" in the namespace "apic"
    Status:                True
    Type:                  ConfigUnsupported
    Last Transition Time:  2020-10-05T12:19:26Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2020-10-05T12:19:26Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                False
    Type:                  RecommendationProvided
  Recommendation:
Events:  <none>`

**Comment by bskiba** [comment]
For the following error:
> managementclusters.management.apiconnect.com "minimum-mgmt" is forbidden: User "system:serviceaccount:apic:vpa-recommender" cannot get resource "managementclusters/scale" 

Please make sure VPA can access scale subresource:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-rbac.yaml#L162

I still don't know which VPA version this is, can you take a look at vpa-recommender logs, it should print the version number there.

**Comment by abudavis** [comment]
@bskiba : That was it, works now, Thank you !

**Comment by abudavis** [comment]
I deployed a different application and this time, got the same error back, any ideas? 

```
Manager:         recommender
    Operation:       Update
    Time:            2020-10-14T18:18:00Z
  Resource Version:  44381148
  Self Link:         /apis/autoscaling.k8s.io/v1/namespaces/ace/verticalpodautoscalers/sftp-rest-timer-is
  UID:               46341839-975b-4782-9c94-8c342b7664fc
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  *
      Controlled Resources:
        cpu
        memory
      Max Allowed:
        Cpu:     8
        Memory:  8Gi
      Min Allowed:
        Cpu:     100m
        Memory:  300Mi
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:        sftp-rest-timer-is
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2020-10-14T18:16:40Z
    Message:               The targetRef controller has a parent but it should point to a topmost well-known or scalable controller
    Status:                True
    Type:                  ConfigUnsupported
    Last Transition Time:  2020-10-14T18:16:40Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2020-10-14T18:16:40Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                False
    Type:                  RecommendationProvided
  Recommendation:
Events:  <none>
```
I tried an oc describe and found this :

```
oc describe pod vpa-recommender-default-68766dfb49-9pkq9
Name:                 vpa-recommender-default-68766dfb49-9pkq9
Namespace:            ace
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 test-xyz3p-master-1/10.244.164.7
Start Time:           Wed, 14 Oct 2020 18:01:28 +0000
Labels:               app=vpa-recommender
                      pod-template-hash=68766dfb49
                      vertical-pod-autoscaler=default
Annotations:          k8s.v1.cni.cncf.io/network-status:
                        [{
                            "name": "openshift-sdn",
                            "interface": "eth0",
                            "ips": [
                                "10.130.0.24"
                            ],
                            "default": true,
                            "dns": {}
                        }]
                      k8s.v1.cni.cncf.io/networks-status:
                        [{
                            "name": "openshift-sdn",
                            "interface": "eth0",
                            "ips": [
                                "10.130.0.24"
                            ],
                            "default": true,
                            "dns": {}
                        }]
                      openshift.io/scc: restricted
                      release.openshift.io/version: 0.0.1-snapshot
                      scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Running
IP:                   10.130.0.24
IPs:
  IP:           10.130.0.24
Controlled By:  ReplicaSet/vpa-recommender-default-68766dfb49
Containers:
  vertical-pod-autoscaler:
    Container ID:  cri-o://5eae69e4aad666b06d62bf4cdbbd67f654108062f8bbeb69867eb08f643d70c3
    Image:         registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4765bbea4d65e500986aad97df2e421322bd741b7049670f6e379cf204bd57d3
    Image ID:      registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4569ed03305d8ab2e78a5a24bb1f20e6bd5f5ecc3159494a9756144c9cdcc9f9
    Port:          <none>
    Host Port:     <none>
    Command:
      recommender
    Args:
      --logtostderr
      --v=1
      --recommendation-margin-fraction=0.15
      --pod-recommendation-min-cpu-millicores=25
      --pod-recommendation-min-memory-mb=250
    State:          Running
      Started:      Wed, 14 Oct 2020 18:01:39 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        25m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from vpa-recommender-token-vmr6c (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  vpa-recommender-token-vmr6c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vpa-recommender-token-vmr6c
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
                 node-role.kubernetes.io/master=
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age   From                          Message
  ----    ------          ----  ----                          -------
  Normal  Scheduled       24m   default-scheduler             Successfully assigned ace/vpa-recommender-default-68766dfb49-9pkq9 to test-xyz3p-master-1
  Normal  AddedInterface  24m   multus                        Add eth0 [10.130.0.24/23]
  Normal  Pulling         24m   kubelet, test-xyz3p-master-1  Pulling image "registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4765bbea4d65e500986aad97df2e421322bd741b7049670f6e379cf204bd57d3"
  Normal  Pulled          24m   kubelet, test-xyz3p-master-1  Successfully pulled image "registry.redhat.io/openshift4/ose-vertical-pod-autoscaler-rhel7@sha256:4765bbea4d65e500986aad97df2e421322bd741b7049670f6e379cf204bd57d3"
  Normal  Created         24m   kubelet, test-xyz3p-master-1  Created container vertical-pod-autoscaler
  Normal  Started         24m   kubelet, test-xyz3p-master-1  Started container vertical-pod-autoscaler
```

**Comment by abudavis** [comment]
This has been told to be a problem with the Operator, closing the issue.
