### ISSUE TITLE
External metric autoscale best practices

### ISSUE THREAD

**Issue by geraldoramos** [kubernetes/autoscaler#3543]
Hi Guys,

I have a `HorizontalPodAutoscaler` (v2beta1) setup to scale based on a custom external metric, which is based on the number of undelivered messages in my pubSub subscription, divided by currently running pods. The idea is to keep running replicas in alignment with the demand, I've been playing with `1-1.3` targets. These tasks are memory/CPU intensive and take anywhere from 5 to 15 minutes. The current implementation is working well, but I'm wondering how the scale down works. I know it has a 5 min reaction window by default, but how the priority of forced terminated pods works in this case? Is the autoscaler selecting pods that are using fewer resources (therefore, are probably idle) or I need to set up this on my own? 

Any suggestions on how to better optimize for this scenario? The idea is that whenever a scale down operation happens, mitigate the chances of terminating a pod that is processing a task (which will cause it to restart in another pod). The ideal scenario would be to somehow configure the system to only scale down pods in certain conditions (memory/CPU usage threshold or something like that).

Is this a good approach? Any suggestions?

Thanks!

**Comment by bskiba** [comment]
@josephburnett FYI
