### ISSUE TITLE
VPA takes too long for modifications

### ISSUE THREAD

**Issue by tvvignesh** [kubernetes/autoscaler#3553]
Hi. I use GKE Private cluster (1.18.6-gke.4801) and terraform for deploying or modifying my cluster.

Interestingly, when I try to toggle VPA (either enable or disable it), it takes too long for the changes to take effect in the cluster,

**Case 1 (Just Switching VPA off)**

<img width="300" alt="Capture" src="https://user-images.githubusercontent.com/1165845/94485483-9c8f7b00-01fb-11eb-8789-2d787f3d9c7a.png">

Just this 1 change took 28 minutes and 54s to apply (had no other changes)

<img width="205" alt="1" src="https://user-images.githubusercontent.com/1165845/94485529-b5982c00-01fb-11eb-83ca-e68dd8c8e89a.png">

**Case 2 (Switching Back on)**

<img width="214" alt="2" src="https://user-images.githubusercontent.com/1165845/94485614-d6608180-01fb-11eb-9622-52d30a191d7e.PNG">

Just 1 change again took 28 minutes and 24s to apply (no other changes)

<img width="206" alt="3" src="https://user-images.githubusercontent.com/1165845/94485637-df515300-01fb-11eb-82bd-b5c2285e310f.PNG">

This means it is a consitent behavior. Initial deployment took very less time, only modifications take too long.

**PS:** Not sure if this is the right place to share this issue (since I am not sure if the issue is with GKE or VPA, but anyways, thought I should share.

**Comment by bskiba** [comment]
I doubt this is a problem specific to VPA, could you report the issue to GKE? I'm not entirely familiar with terraform, it would be good to understand what it executes during these 28 minutes. Is it just calling the GKE API to modify the VPA enabled setting?

I'll close this issue as it's unlikely to be a problem within VPA itself, but please do report with GKE if you can.
