### ISSUE TITLE
Add native support for autoscaler in Digital Ocean

### ISSUE THREAD

**Issue by pablokbs** [kubernetes/autoscaler#3556]
Right now is not possible to run CA in Digital Ocean because the tags required for it to work are tied with the DO version of CA, enabling the tags and node pools will enable the built-in DO CA which will collide with the vanilla version.

Pinging @timoreimann. Apologies if this issue is not clear enough, you can find more info [here](https://github.com/kubernetes/autoscaler/issues/3469)

**Comment by MorrisLaw** [comment]
/assign @MorrisLaw

Assigning myself this issue. But @timoreimann will be working on it.

**Comment by timoreimann** [comment]
I'll tackle this one.

**Comment by jadelafuente** [comment]
> I'll tackle this one.

Could it be possible to develop CA integration to Terraform Enterprise to abstract from the different cloud providers?

**Comment by pablokbs** [comment]
@timoreimann Any news on this one?

**Comment by timoreimann** [comment]
@pablokbs apologies, I got side-tracked by other tasks. This is still on my agenda though. I expect to carve out some time within the next 2 weeks.

**Comment by timoreimann** [comment]
@jadelafuente 

>Could it be possible to develop CA integration to Terraform Enterprise to abstract from the different cloud providers?

Are you asking for CA support in Terraform across cloud providers like DO, AWS, GCE, and so on? That's probably beyond the scope of this ticket which is very much focused on CA integration in DOKS only. But let me know if you think I'm misunderstanding.

**Comment by jadelafuente** [comment]
Thanks for your reply Timo, I've opened a generic ticket with the scope you mention #3569

**Comment by timoreimann** [comment]
I'm struggling right now to find the time to work on this feature. If anyone is interested to talk through the design and implement the change, please ping here.

/unassign

**Comment by PrakashTrove** [comment]
By following this issue #3469, finally, I guess I am in the right place.

I'm adding my request as well.

DOKS's default Cluster-Autoscaler(CA) supports node scaling down after 10 minutes.
However, I intended to adjust the parameter values to one minute.
[Parameters](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca) —delay-after-add and —unneeded-time

It appears that there are no alternatives for that.
It would be beneficial if there was further support.

**Comment by marcbachmann** [comment]
I think the focus at the moment is to implement the cluster api with https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean. That could replace the specific autoscaler implementation in this repo.

**Comment by logileifs** [comment]
Is there any news on this? Is Digitalocean's built-in autoscaler the only autoscaler option so far?

**Comment by timoreimann** [comment]
@logileifs nobody is working on this currently. https://github.com/kubernetes/autoscaler/issues/3556#issuecomment-796653795 still holds.

**Comment by unixfox** [comment]
> Is there any news on this? Is Digitalocean's built-in autoscaler the only autoscaler option so far?

Meanwhile, you can use [machine-controller](https://github.com/kubermatic/machine-controller) from kubermatic.

**Comment by ShadowJonathan** [comment]
Currently it seems that https://github.com/kubermatic/machine-controller is indeed one of the ways to have a non-managed kubernetes cluster on DO, a bit of a shame, tbh.
