### ISSUE TITLE
addon-resizer does not preserve new seccompProfile field

### ISSUE THREAD

**Issue by jmcmeek** [kubernetes/autoscaler#3567]
I tried using the GA level seccompProfile with Kubernetes v1.19 - removed the alpha annotation and added seccompProfile to the container securityContext for a metrics-server deployment with addon-resizer.

After resizing neither the seccompProfile nor the alpha seccomp annotation appear in the containers.

Kubernetes v1.19.2
addon-resizer:1.8.1​1

**Comment by jmcmeek** [comment]
Metrics-server deployment yaml:
[metrics-server.yaml.txt](https://github.com/kubernetes/autoscaler/files/5307681/metrics-server.yaml.txt)

Deployment after initial resize:
[metrics-server-after.yaml.txt](https://github.com/kubernetes/autoscaler/files/5307686/metrics-server-after.yaml.txt)

**Comment by bskiba** [comment]
Thanks for reporting.
Is this only a problem with seccomp annotation or is it all annotations?
Would you be interested in contributing a fix?

**Comment by jmcmeek** [comment]
It would help if I had remember to include this:

`seccomp` graduated to GA in Kubernetes 1.19.  In 1.19 you should be able to create pods using the seccompProfile field in the securityContext as described in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#seccomp-graduates-to-general-availability

I suspect what is happening is that the Kubernetes go client used by the addon-resizer doesn't yet know about this.  When it builds the go Deployment from the Kube apiserver response it ignore fields it doesn't understand and when it updates the deployment it only writes fields it knows - and `seccompProfile` disappears.

Assuming that is right... it may be a matter of updating the client.  I don't know what ramifications that has for older releases you support.  This might be something that has to wait - but get done before Kubernetes drops the annotations in v1.22.

For now its acceptable to keep using the annotations.  Those are preserved and the Kubernetes apiserver supports both mechanisms for a few more releases.

**Comment by jmcmeek** [comment]
The [1.19 Kubernetes changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#seccomp-graduates-to-general-availability) said the support for seccomp.security.alpha.kubernetes.io/pod and container.seccomp.security.alpha.kubernetes.io/... annotations are deprecated, and will be removed in Kubernetes v1.22.0.

v1.22 is fast approaching.  Any chance this can be addressed before the v1.22 GA?

**Comment by bskiba** [comment]
#4004 should fix this, I'll work on merging/releasing in the next 2 weeks.

**Comment by jmcmeek** [comment]
@bskiba It looks like that PR requires a RBAC change as well: Add the verb "patch" to an appropriate role.  I assume that would be the `system:metrics-server` clusterrole in Kubernetes (whenever that addon gets to 1.8.13+) or the example default:pod-nanny.

`ERROR: logging before flag.Parse: E0519 19:33:36.949283       1 nanny_lib.go:162] deployments.apps "metrics-server" is forbidden: User "system:serviceaccount:kube-system:metrics-server" cannot patch resource "deployments" in API group "apps" in the namespace "kube-system"`

Once I added that verb, it worked nicely - patched in the new resources and the new seccompProfile was left intact.

**Comment by bskiba** [comment]
Glad it worked!

I do still need to update the example addon-resizer deployment with the additional permission and I should probably add that to the description of the release.
