### ISSUE TITLE
scale-down-delay-after-delete parameter doesn't work properly

### ISSUE THREAD

**Issue by marwanad** [kubernetes/autoscaler#3568]
I believe that started around the time the switch to the new scale down processor happened.

The parameter goes into effect and puts scaledown in cooldown mode based on the `lastScaleDownDeleteTime`.

https://github.com/kubernetes/autoscaler/blob/774390efc80625466794131418b95092a5e63741/cluster-autoscaler/core/static_autoscaler.go#L499

However, this is only set when the scale down status result is `ScaleDownNodeDeleted`

https://github.com/kubernetes/autoscaler/blob/774390efc80625466794131418b95092a5e63741/cluster-autoscaler/core/static_autoscaler.go#L532-L535

And it seems with the switch to the async deletions, this is no longer set:

https://github.com/kubernetes/autoscaler/blob/30719059bf89199a983fde72c3e061561d280672/cluster-autoscaler/core/scale_down.go#L943-L964

 
/kind bug

**Comment by marwanad** [comment]
@MaciekPytel @towca

**Comment by marwanad** [comment]
Should we be returning `ScaleDownNodeDeleted` instead of `ScaleDownNodeDeleteStarted` - it seems that the later isn't used around so it seems like the most straightforward fix

**Comment by towca** [comment]
Thanks for pointing this out Marwan! Although I'd stick to using `ScaleDownNodeDeleteStarted` since it better conveys what actually happens. I'll send out a fix shortly.

**Comment by towca** [comment]
The bug should be fixed by #3570.

**Comment by ryaneorth** [comment]
thanks @towca @marwanad for finding/fixing this issue! any idea when/if this will make it into a patch release for versions 1.16.x/1.17.x?

**Comment by ryaneorth** [comment]
@MaciekPytel - maybe you know the answer to the above question?

**Comment by marwanad** [comment]
@ryaneorth we can prepare the cherry-pick PRs. I'm guessing we'll have one set of patch releases before K8s 1.20 and another around 1.20.

**Comment by ryaneorth** [comment]
Sounds great, thanks @marwanad . I'm happy to perform the cherry-picks if you'd like - let me know!

**Comment by marwanad** [comment]
@ryaneorth that would be great, thanks!

**Comment by ryaneorth** [comment]
All of the above cherry-picks are complete. @MaciekPytel - do you have any information as to when the next patches will be released?

**Comment by marwanad** [comment]
@ryaneorth keep an 👀  on https://github.com/kubernetes/autoscaler/issues/3611
