### ISSUE TITLE
Plans to support Terraform Enterprise as a provider for the cluster autoscaler

### ISSUE THREAD

**Issue by jadelafuente** [kubernetes/autoscaler#3569]
Are there any plans to implement a Terraform cluster autoscaler provider? This would abstract the infrastructure autoscaling capability to be used on any of the cloud providers Terraform is having a provider and would simplify the evolution

**Comment by unixfox** [comment]
That's a very good idea because this would allow to deploy autoscaling on cheaper (managed) kubernetes solution like OVH, linode, vultr and more that don't support autoscaler yet.

**Comment by miguescri** [comment]
+1
