### ISSUE TITLE
feat: Include Helm chart repo into chartcenter.io

### ISSUE THREAD

**Issue by Eddman** [kubernetes/autoscaler#3571]
JFrog is hosting an aggregated central hub for different Helm repositories: [chartcenter.io](https://chartcenter.io). It has multiple advantages, incl. security scanning.

Please include/enlist chart repo to [chartcenter.io](https://chartcenter.io):
https://github.com/jfrog/chartcenter/blob/master/docs/inclusion.md

**Comment by cabrinha** [comment]
This should be a simple process and will help adoption and migration from the deprectated chart.

**Comment by cabrinha** [comment]
@gjtempleton if you could open the PR to get this chart added to chartcenter, it'd be a big help.

I might be able to open the PR myself and just get an owner here to approve it.

**Comment by gjtempleton** [comment]
@cabrinha I'd rather resolve the renaming of the chart from `cluster-autoscaler-chart` to `cluster-autoscaler` (i.e. get it back to the previous name) before raising the PR to get it included. I should have some time to look at achieving that again tomorrow.

Once that's done I'm happy to raise the PR.

**Comment by gjtempleton** [comment]
Hi @cabrinha, @Eddman and others,

I'm revisiting this now that we've successfully renamed the chart back to the original name.

There seems to be a move by the community, particularly with the helm stable registry redirecting there towards https://artifacthub.io/ as the new solution for a hub going forward rather than chartcenter.io. Do you still think we should also be ensuring we get included in chartcenter?

**Comment by Eddman** [comment]
Hi @gjtempleton,

I'm not saying one or the other is better, but https://artifacthub.io/ is Beta project. JFrog's https://chartcenter.io/ has some security related features like chat and image scanning. And has nice integration with JFrog's Artifactory used in many enterprise environments.

I'd say it is worth to have it integrated with both tools. AFAIK enlisting repo in  chartcenter.io is as simple as opening a PR, the rest is done automatically, eg. syncing charts, scanning, etc.

**Comment by cabrinha** [comment]
> Hi @cabrinha, @Eddman and others,
> 
> I'm revisiting this now that we've successfully renamed the chart back to the original name.
> 
> There seems to be a move by the community, particularly with the helm stable registry redirecting there towards https://artifacthub.io/ as the new solution for a hub going forward rather than chartcenter.io. Do you still think we should also be ensuring we get included in chartcenter?

Yes, I think chartcenter is still worth while.

**Comment by Eddman** [comment]
Closing as https://jfrog.com/center-sunset/
