### ISSUE TITLE
CRD: bad map key type: map keys must be strings

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/autoscaler#3574]
I tried to use kubebuilder controller-tools to generate CRD YAML for VPA but I am getting the error
`bad map key type: map keys must be strings`.

The problem is VPA uses `map[int]uint32` as seen here:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L355-L356

It seems that this will require an api data type change. 

xref: https://github.com/kubernetes/kubernetes/issues/95250

**Comment by bskiba** [comment]
Thanks a lot for reporting.
Is there a Kubernetes version in which this will stop working in the current form?
If we want to change this, we need to do it carefully, possibly avoiding issues with reading the old objects after upgrade.

**Comment by tamalsaha** [comment]
I think it will affect from k8s 1.16 and later versions if users want to use CRD openapi validation.

**Comment by bskiba** [comment]
I'm not seeing any errors in 1.16, is CRD openapiv3 validation with structural schema an opt-in feature? If yes, how do you turn it on?

**Comment by tamalsaha** [comment]
From https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

`With apiextensions.k8s.io/v1 the definition of a structural schema is mandatory for CustomResourceDefinitions. In the beta version of CustomResourceDefinition, the structural schema was optional.`

**Comment by bskiba** [comment]
I see, so does #3606 sort of mitigate the issue? Changing the histogram type at this point might cause data loss for some users if we're not very careful.

**Comment by tamalsaha** [comment]
I replied in the pr .
