### ISSUE TITLE
REGISTRY variable supported for VPA doesn't honour private registries

### ISSUE THREAD

**Issue by infa-vmannam** [kubernetes/autoscaler#3634]
exporting REGISTRY variable for vpa-up.sh doesn't really solve downloading images from private ones. I checked deployment definitions for the components, and pullSecrets is missing. Strongly believe if the REGISTRY is exported there must be some way to pass pull secrets as well.

expected change:
* if Registry is set, please also take docker secrets name to render pull secret in deployment definition
* We can feed in the secrets to Kubernetes ns outside VPA deployment

**Comment by bskiba** [comment]
The vpa-up.sh script is mostly there to deploy the released version of VPA, which is in a pubic registry. If pulling from a private registry is part of your workflow, we may accept contributions that enable it, but as sig-autoscaling we don't plan to work on this.
