### ISSUE TITLE
Add chart repo to Artifact Hub

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/autoscaler#3638]
The [Artifact Hub](https://artifacthub.io) is a place discover cloud native artifact (Helm charts, operators, etc). This is a request to add the autoscaler chart repo you are running to it. Specifically, https://kubernetes.github.io/autoscaler.

Currently, when people search the Artifact Hub they will discover the cluster autoscaler as presented by banzaicloud with an out of date version. It would be great to have newer versions listed and from the official source.

There is an existing Kubernetes organization and nginx ingress is listed in it. This should likely go in that organization.

**Comment by gjtempleton** [comment]
Hi, thanks for raising this!

Thanks to a helping hand from @scottrigby there's now an initial publish of it at https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler

Unfortunately, as I hadn't fully anticipated the way Artifact Hub would perform indexing I've had to go back and raise a PR to mark the intermediate chart we published `cluster-autoscaler-chart` as deprecated under #3719 however I've started the ball rolling on this.

**Comment by gjtempleton** [comment]
Resolved and [available on artifact hub](https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler), with the [previous chart naming deprecated](https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler-chart).

/close
