### ISSUE TITLE
Generic API based cluster autoscaler

### ISSUE THREAD

**Issue by Bessonov** [kubernetes/autoscaler#3644]
There is a high demand to allow custom cloud autoscaler provider:
- https://github.com/kubernetes/autoscaler/issues/191
- https://github.com/kubernetes/autoscaler/issues/984
- https://github.com/kubernetes/autoscaler/issues/1050
- https://github.com/kubernetes/autoscaler/issues/2053

Well, I'm not able to reopen any of them. This request goes beyond the hard coding every possible provider into autoscaler source code base. And I'm not sure why every provider must be integrated into source code, follow the same unpredictable release schedule, review process and follow the same licence (although Apache is fine). It set a limit to scale development.

Furthermore, the integrated providers are very limited to some "standard" things. Some use cases are missing:
- For example I need an autoscaler integration for hetzner. The fresh PR https://github.com/kubernetes/autoscaler/pull/3640 wouldn't fit, because I must (automatically) run some operations in rescue mode before giving the node to the pool. This process, probably, would be never integrated into autoscaler source code.
- The API can be "send an email to the administrator to provide new nodes". In fact, it's how many companies work. And this could be an interface to include dedicated servers. For example netcup send a mail with credentials if a server is ready for provisioning.
- Other side effects like custom billing, slack messages, inventory etc.
- Another programming languages instead of go.
- Interaction with non-kubeadm clusters. Currently, I'm experimenting with [microk8s](https://github.com/ubuntu/microk8s/).

A more generic solution could send desired actions to a (single) configurable REST endpoint, possibly to a service inside the cluster. It would allow a decentralized and powerful way to create own autoscaler providers.

I'm aware of [Cluster API](https://cluster-api.sigs.k8s.io/) and the [Cluster API Provider](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi). But I'm not sure how it contribute to above use cases.

Maybe I'm just not aware of an existing solution. Is there any workaround for above use cases? Any pointers are appropriate.

**Comment by Bessonov** [comment]
Found another two use cases:
- https://github.com/kubernetes/autoscaler/issues/3614
- https://github.com/kubernetes/autoscaler/issues/3204

And a relevant [quote](https://github.com/kubernetes/autoscaler/issues/3204#issuecomment-703503904) from @MaciekPytel  about scaling development:

> We're happy to accept more provider integrations, but we (core developers) are unable to even support existing ones anymore. Instead each provider has its own owners who maintain it. So a prerequisite to accepting a new provider would be to have someone willing to take responsibility for it.

I think it shows how an generic interface could help.

**Comment by Bessonov** [comment]
Found a proposal for generic (gRPC) API: https://github.com/kubernetes/autoscaler/pull/3140 .

**Comment by technicianted** [comment]
What's the status of [plugable-provider-grpc.md](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/plugable-provider-grpc.md)? Seems to be the most promising.

@hectorj2f

**Comment by dbonfigli** [comment]
you might want to review / test this: https://github.com/kubernetes/autoscaler/pull/4654

**Comment by Bessonov** [comment]
Oh, wow, thank you very much for your work and pointing to the implementation! I think now this issue can be closed.

**Comment by unixfox** [comment]
Why closing? The PR wasn't merged.

**Comment by AverageMarcus** [comment]
As that PR isn't merged in yet would it be best to leave this issue open?

**Comment by Bessonov** [comment]
Hey guys, I think this issue should be closed already after #3140 was merged. But I've no stakes to reopen it :)

**Comment by dbonfigli** [comment]
https://github.com/kubernetes/autoscaler/pull/4654 has been merged and now the cluster autoscaler has a gRPC based plugin system, probably this issue can be closed.
