### ISSUE TITLE
AWS examples : set pod priority in podSpec 

### ISSUE THREAD

**Issue by suket22** [kubernetes/autoscaler#3645]
I ran into a situation where my ClusterAutoscaler pods were stuck in `Pending` on an EKS cluster, because my existing nodes were full and didn't have any space to take on any more pods.

[EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html) refers to the [examples here](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws/examples) so I think we should consider setting the `priorityClassName: system-cluster-critical` property in the podSpec. 

I'll make the change if this makes sense.

**Comment by huang-jy** [comment]
FWIW, I had a similar situation. The autoscaler pods were booted off when I had to upsize the nodes in my EKS cluster and they couldn't reschedule because they were considered "normal" workload and not cluster critical. I believe PodPriority should fix this too.

**Comment by huang-jy** [comment]
Quick hack if you want to use it:

```
curl -s https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml | \
  sed s/'<YOUR CLUSTER NAME>'/'{replace-me-with-your-cluster-name}'/g | \
  sed '/serviceAccountName: cluster-autoscaler/a\      priorityClassName: system-cluster-critical' | kubectl apply -f -
```
