### ISSUE TITLE
Cluster Autoscaler: v1.18.1 - unknown EC2 instance type "c5a.2xlarge"

### ISSUE THREAD

**Issue by darrenfurr** [kubernetes/autoscaler#3650]
I'm attempting to use the cluster autoscaler with the latest helm chart (8.0.0) & image v1.18.1 using the c5a.2xlarge EC2 nodes in our ASG, however the autoscaler pod is returning:
`
static_autoscaler.go:268] Failed to get node infos for groups: ASG "eks-12020082019553778640000000a" uses the unknown EC2 instance type "c5a.2xlarge"
`

Oddly enough, this works in 2 other AWS accounts - with the same EKS cluster (created by Terraform) 🤷‍♂️

Log attached:
[aws-cluster-autoscaler.log](https://github.com/kubernetes/autoscaler/files/5455599/aws-cluster-autoscaler.log)

**Comment by sanjeevpandey19** [comment]
@darrenfurr got any solution of this issue ? i'm also experiencing the same behavior

**Comment by darrenfurr** [comment]
@sanjeevpandey19 - Unfortunately no. I have one AWS account the c5a works fine. Another account, which happens to be Prod, it does not. 👎

**Comment by sanjeevpandey19** [comment]
> @sanjeevpandey19 - Unfortunately no. I have one AWS account the c5a works fine. Another account, which happens to be Prod, it does not.

having exactly same issue, working in 2 accounts but does't work another one

**Comment by pre** [comment]
Maybe you have different version of the cluster-autoscaler running in each cluster?

**Comment by sanjeevpandey19** [comment]
@darrenfurr is it still not solved for you ?

**Comment by sanjeevpandey19** [comment]
I updated the cluster autoscaler and it started working in my environment

**Comment by darrenfurr** [comment]
@sanjeevpandey19 - We're running EKS 1.18 & Cluster Autoscaler 1.18.1 in each environment. Are you saying we can upgrade to 1.22 of the Autoscaler on EKS 1.18?

**Comment by darrenfurr** [comment]
@sanjeevpandey19 - We updated to the latest cluster autoscaler (1.22.0) & are no longer having this issue. We did have to remove & re-create the LaunchConfig & ASG with c5a, but it is now working.
