### ISSUE TITLE
Not delete node with specific pod during scale down

### ISSUE THREAD

**Issue by kpiyush17** [kubernetes/autoscaler#3659]
Hi,

I wanted to know if there is a way in autoscaler to not delete the node if there is a particular pod running on that node during the scaled-down event.
Or, is there a way to do that outside of the autoscaler tool, maybe change something in the deployment yaml file?

Thanks

**Comment by MaciekPytel** [comment]
The usual ways would be to either create a PodDisruptionBudget that doesn't allow any disruptions or use CA's [safe-to-evict annotation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node).
