### ISSUE TITLE
Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

### ISSUE THREAD

**Issue by roy-tonal** [kubernetes/autoscaler#3668]
Hi, 

I'm facing the below problem with CA, I have deployed CA with proper ASG tags for auto-discovery. I have used `nodeSelector` to deploy CA in my dedicated nodes, but its not able to fetch the instances list, i'm getting below error.
`aws_util.go:71] Error fetching https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-west-2/index.json skipping...
Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list`

Pod goes in crasbackloop. One thing i noticed that if i dont use `nodeSelector` then it works after sometime but with `nodeSelector` its giving error.

I did tried to set `--aws-use-static-instance-list=true`, but here also i was getting timeout error.
`Failed to regenerate ASG cache: cannot autodiscover ASGs: RequestError: send request failed
caused by: Post https://autoscaling.us-west-2.amazonaws.com/: dial tcp: i/o timeout`

EKS version :- 1.17
CA version: using chart version `1.0.3` with CA image as `1.17.3`

Is there anything else i need to do, does CA works by specifying `nodeSelector` to schedule CA pods in dedicated nodes? 

CA info.
```
dnsPolicy: ClusterFirst
     - command:
    - ./cluster-autoscaler
    - --cloud-provider=aws
    - --namespace=admin
    - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/devops-eks-2
    - --balance-similar-node-groups=true
    - --logtostderr=true
    - --scale-down-delay-after-add=15m
    - --scale-down-delay-after-delete=10m
    - --scale-down-delay-after-failure=3m
    - --skip-nodes-with-local-storage=true
    - --stderrthreshold=info
    - --v=4
    env:
    - name: AWS_REGION
      value: us-west-2
    image: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.17.3

**Comment by jcsferraz** [comment]
Hi! 

in my case it was the deployment of 'core-dns' generating the behavior you showed here. I needed to ping the URL that you entered through the nodegroup and then tried to 'ping' the container (pod) the same URL, so when I realized that it was not recovering I installed coredns again at: https://docs.aws.amazon.com /eks/latest/userguide/coredns.html

**Comment by roy-tonal** [comment]
Thanks for the reply @jcsferraz 
It resolved on its own, I don't know what caused this, as the API was working fine, my cluster was also working fine. I did tried after a day or two on multiple clusters and didn't face any issue. Will close this now.
