### ISSUE TITLE
Helm chart limits setting balancing-ignore-label flag to a single label

### ISSUE THREAD

**Issue by sbuzonas** [kubernetes/autoscaler#3673]
The snippet in the chart to set extra arguments is in the format of key=value pairs.  For arguments that can be passed multiple times, this limits you to only setting one value.

```
          {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
```

Switching it from a hash to an array would solve the problem, but would break backwards compatibility and complexity to the existing configuration.  I think accepting a separate block of multi use arguments would keep the configuration simple.

```
extraMultiUseArgs:
  balancing-ignore-label:
    - some-label
    - and-another
```

**Comment by gjtempleton** [comment]
Hi @sbuzonas,

Thanks for raising this issue and proposing a solution for it.

What you're proposing sounds like a reasonable approach to me, keeping the complexity of the arrays only where they're needed. If you want to raise a PR to add this functionality I'd be more than happy to give it a review.

**Comment by stevehipwell** [comment]
Could this issue get re-opened as it's a pretty major defect in the CA chart considering how many labels need to be ignored by CA to make it actually work?

**Comment by stevehipwell** [comment]
Thanks @gjtempleton, I'm just writhing a simple PR to solve this.

**Comment by gjtempleton** [comment]
No problem, give me a ping once it's ready, and I'll happily review it.

Depending on when you raise it, you may need to cherry-pick [this commit](https://github.com/kubernetes/autoscaler/commit/38e77bec8263aae7ac937cc2562a02461c4b2f0f) in as Github actions not running by default for first-time contributors has bitten us. Looking to move to ensure they always run in the SIG meeting this afternoon.

**Comment by infa-ddeore** [comment]
> Thanks @gjtempleton, I'm just writhing a simple PR to solve this.

any chance it will be available in next ~5-10 days?

**Comment by stevehipwell** [comment]
@infa-ddeore this has already been merged and released.

**Comment by gjtempleton** [comment]
The fix was implemented by [this PR.](https://github.com/kubernetes/autoscaler/pull/4226) It should be available as of the release of version `9.10.3` 3 days ago, have you tried that version?

**Comment by infa-ddeore** [comment]
didnt see github `merged` message, will try the chart, thx

**Comment by infa-ddeore** [comment]
> The fix was implemented by [this PR.](https://github.com/kubernetes/autoscaler/pull/4226) It should be available as of the release of version `9.10.3` 3 days ago, have you tried that version?

it adds `_1` and `_2` to `--balancing-ignore-label` arguments, will it work with cluster-autoscaler?

```
$ helm template --repo https://charts.helm.sh/stable cluster-autoscaler --version 9.10.3 -f /tmp/values.yaml |grep balancing
            - --balancing-ignore-label_1=first-label-to-ignore
            - --balancing-ignore-label_2=second-label-to-ignore
```

**Comment by stevehipwell** [comment]
@infa-ddeore the chart values explains how this works and the deployment template has the implementation in it. Basically the `extraArgs` chart value is a map type meaning that a key can only appear once which would not work for an argument called multiple times; so the workaround is for you to suffix the argument with an underscore and anything else to make it unique which will be removed in the template.

I can confirm that this is working correctly for me, could you share the values that you're using?

**Comment by infa-ddeore** [comment]
my bad, i found the problem, my command was using `https://charts.helm.sh/stable` repo which  doesnt have `9.10.3` chart, however helm didnt error out with chart not found message because my current working dir had `cluster-autoscaler` folder with old version of chart so helm was using that.

this now looks fine:
```
helm template --repo https://kubernetes.github.io/autoscaler cluster-autoscaler -f values.yaml --version 9.10.3 | grep balancing
            - --balancing-ignore-label=first-label-to-ignore
            - --balancing-ignore-label=second-label-to-ignore
```

which helm repo should we use moving forward, https://charts.helm.sh/stable or  https://kubernetes.github.io/autoscaler ?

**Comment by stevehipwell** [comment]
https://charts.helm.sh/stable is [deprecated](https://helm.sh/blog/charts-repo-deprecation/).
