### ISSUE TITLE
[VPA] Bump klog to klog/v2

### ISSUE THREAD

**Issue by lilic** [kubernetes/autoscaler#3683]
Hello, we use this project as a dependency in[ kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/) and since this project still uses klog v1 but we switched to klog/v2, we now have mixed klog versions which cause potential problems. 

I am proposing that klog is bumped to klog/v2, I am happy to do the changes, just wanted to make sure this is okay? If it's okay I would also like to bump to latest client-go & co, as it seems this project is still on 1.18 version.

**Comment by MaciekPytel** [comment]
This repo has multiple independent projects with different sets of maintainers, not sure which one you're referring to? From my side I've already migrated cluster autoscaler to klog/v2 a few months back.

**Comment by lilic** [comment]
Hey @MaciekPytel thanks for reply, sorry for not clarifying the issue is in the VPA. https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/go.mod#L18

**Comment by MaciekPytel** [comment]
cc: @bskiba

**Comment by bskiba** [comment]
Bumping to klog/v2 sounds fine, thanks for checking.

For client-go, I'm not sure bumping to latest is the best idea, however, we might consider bumping to 1.19
