### ISSUE TITLE
vpa-recommender: configurable options to lower weights for low CPU usages on the weekends to not cause a dip in the recommendation.

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3684]
UseCase:

I have an app with low CPU usages over the weekends and the VPA CPU recommendation dips respectively. However, is it possible to configure the recommender in a way to not be influenced by the two day dip? I'd like to keep the recommendation the same as during regular usage days.

Here is a chart of my CPU usage / VPA CPU recommendation: 
CPU usage - solid line
VPA CPU recommendation - dotted line
![Screen Shot 2020-11-10 at 11 01 39 AM](https://user-images.githubusercontent.com/4632428/98719081-2165cc80-2344-11eb-918a-9ac8a29127ef.png)

The reason I don't want the recommended CPU limit to dip is a risk factor because of how much business value the app brings and I'm willing to "waste" the CPUs over the weekend to prepare for anything. 

Expected:

VPA CPU limit recommendation to stay consistent to the majority of the usages and not dip due to the two days of low usage on weekends.

cc @bskiba

**Comment by bskiba** [comment]
I see that you found a solution to fine-tune the half life decay: https://github.com/kubernetes/autoscaler/issues/3698

There is also a not very pretty solution to set MinAllowed CPU for the VPA object - recommendation will not go lower than that value.

The problem with fine tuning is that we run all tests with the default settings, and that's the config that we can reason about with confidence.

@kgolab
