### ISSUE TITLE
Set "--cpu-histogram-decay-half-life" to be "72h" by default

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3698]
UseCase:

I have an app that receives less traffic on the weekends so with the "24h" default decay setting, the cpu recommendation looks like:

![Screen Shot 2020-11-16 at 9 52 50 AM](https://user-images.githubusercontent.com/4632428/99289325-a2fca500-27f1-11eb-9015-d7f5aa44751e.png)

There is a drastic dip in the recommendation starting from Saturday over to Monday due to the lowered CPU usage. 
But as this service is critical to the infrastructure, I'd like to maintain the recommendation to be about the same as during normal traffic hours on the weekdays. 

After configuring the decay to be 72h, the chart looks like this after a week of test time:
![Screen Shot 2020-11-16 at 9 59 06 AM](https://user-images.githubusercontent.com/4632428/99289870-62e9f200-27f2-11eb-99a1-f301ae9912a0.png)

The longer the decay is set, the less the current cpu usage will factor into the calculation of the recommendation but with this, I'm able to maintain a similar recommendation as during average traffic on the weekdays.

Question:
Is there anything that can go awry with this setting or any blindspots that will happen due to this? Thanks.

**Comment by bskiba** [comment]
The reaction to any spike that is higher than the spikes seen before will be slower with the longer halflife.

Nothing else comes to mind immediately, but all the testing we've done was with the default as it is now, 24 hours so it's all speculative.

**Comment by thowan** [comment]
How do you set the --cpu-histogram-decay-half-life flag in the first place? Could someone tell me? Thanks!

**Comment by bskiba** [comment]
This [FAQ entry](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#how-can-i-use-prometheus-as-a-history-provider-for-the-vpa-recommender) shows how to modify the arguments for recommender. You can pass  the --cpu-histogram-decay-half-life value the same way by modifying the [recommender manifest](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/recommender-deployment.yaml):
