### ISSUE TITLE
Upgrade tzdata package in addon-resizer image

### ISSUE THREAD

**Issue by jonesbr17** [kubernetes/autoscaler#3699]
[DLA-2424-1](https://www.tenable.com/plugins/nessus/142169) is a vulnerability impacting the addon-resizer image. The tzdata package will need to be upgraded to resolve.

**Comment by bskiba** [comment]
Can you let me know which addon-resizer image we are talking about?
I think we migrated addon-resizer to distroless so I wouldn't expect this issue to come up.

**Comment by rtheis** [comment]
@jonesbr17  is referring to https://github.com/kubernetes/autoscaler/releases/tag/addon-resizer-1.8.11

**Comment by jonesbr17** [comment]
Update: the change to fix the vulnerability has been merged: https://github.com/kubernetes/kubernetes/pull/98401
I do not see new images published yet however, will keep an eye out for that.

**Comment by jonesbr17** [comment]
@bskiba New base images are available. Publishing a new release at this point should resolve the vulnerabilities.

**Comment by rtheis** [comment]
https://github.com/kubernetes/autoscaler/releases/tag/addon-resizer-1.8.12 should resolve this.
