### ISSUE TITLE
Packet Autoscaler Example fixes

### ISSUE THREAD

**Issue by justgotthis** [kubernetes/autoscaler#3709]
- cloudinit needs to be changed as the kubeadm command was wrong: 
kubeadm join --discovery-token-unsafe-skip-ca-verification --token {{.BootstrapTokenID}}.{{.BootstrapTokenSecret}} {{.APIServerEndpoint}}

- nodeSelector for the Cluster Autoscaler pod needed to be changed to this:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""

- Need a toleration in deployment for nodeSelecting masters to run Autoscaler:
      tolerations:
      - key: kubeadmNode
        operator: "Equal"
        value: "master"
        effect: "NoSchedule"

**Comment by larrymapacket** [comment]
Hi Luis, for the "toleration" comment above, what if the cluster is setup with the controller node not being tainted?

**Comment by justgotthis** [comment]
Hello Larry, if the controller node is not tainted then there would be no
need for the toleration. Maybe we can still have the toleration code but
commented out just to not assume that the controller is tainted with an
explanation in the example.

**Comment by larrymapacket** [comment]
that's a good idea!

**Comment by detiber** [comment]
I have addressed the toleration and scheduling for the deployment should be addressed (albeit in a slightly different way) in https://github.com/kubernetes/autoscaler/pull/3483

As far as I can tell the `kubeadm join` command in the base64 encoded cloud-init configuration is the same as you have above, though I could very well be overlooking the difference
