### ISSUE TITLE
safe-to-evict annotation prevents autoscaler from calculating unneeded nodes

### ISSUE THREAD

**Issue by paranoidsp** [kubernetes/autoscaler#3712]
Setup:
A few pods with safe-to-evict: "false" spread across several nodes, mixed in with other pods that are safe to evict.

Expected behaviour:
* Autoscaler will note the unsafe pods and mark those nodes as needed, and calculate if pods from other nodes can be moved into these nodes.

What actually happens:
* Autoscaler notes the unsafe pods, marks them as needed, and completely ignores their utilization in calculating if pods in other nodes can be moved.
* This results in situations with some nodes with unsafe pods (A) having very low utilization, but other nodes with utilization slightly higher than threshold (B) will still remain, despite the possibility of the pods in those nodes being moved from B to A. 

Tested on EKS 1.16, with cluster-autoscaler image version v1.16.7.

**Comment by MaciekPytel** [comment]
The threshold is not some average utilization CA tries to achieve. On scale-up CA always packs nodes as tightly as possible regardless of threshold. Instead the semantic of threshold is literally "do not consider deleting any node with utilization above the threshold". Given the above, it seem that behavior you describe is WAI. You should be able to achieve the behavior you want just by increasing the threshold via the flag. CA will not trigger scale-down if it would result in any pod going pending and increasing the threshold would result in exactly the behavior you describe.
