### ISSUE TITLE
Using VPA version 0.9 autoincrements k8s.io/client-go to v0.18.3

### ISSUE THREAD

**Issue by r3d00** [kubernetes/autoscaler#3715]
This shouldn't be the case since in the README.md, compatibility of version 0.9 is with Kubernetes 1.16+.

If you build code with existing dependencies with for example k8s.io/client-go 0.17.5, it automatically changes the version in go.mod to 0.18.5

In commit https://github.com/kubernetes/autoscaler/commit/221b2ab362a084adfa038a9a81a5adf206072a5f , only the version 0.18.5 is in required modules, but it should also support older versions (like 17.3 or 16+).

This could be fixed by adding those versions in the go.mod file as well.

**Comment by bskiba** [comment]
I have just tried out BPA 0.9 version with Kubernetes 1.16 and it works for me.
The [compatibilty matrix fro client-go](https://github.com/kubernetes/client-go#compatibility-matrix) doesn't say that 1.18 is incompatible with 1.16. Only that there may be differences in capabilities. AFAIK, we are not using any capabilities not present in 1.16.

Are you experiencing issues?
