### ISSUE TITLE
False node selector limitation

### ISSUE THREAD

**Issue by autarchprinceps** [kubernetes/autoscaler#3733]
Cluster autoscaler says, it won't trigger a resize, because supposedly it cannot schedule my pod on it. Looking at the logs, it thinks so, because of mismatching node selector. The only node selector my pod has is kubernetes.io/os: linux, which is present on the node as well. Indeed, if I change the desired value on the autoscaling group myself the pod does schedule onto that very node. Sometimes it does even work to scale up via this autoscaler, but most of the time we get this:
```
1 pod_schedulable.go:165] Pod somepod can't be scheduled on correct-nodegroup, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector,
```

**Comment by MaciekPytel** [comment]
Is it scale-up from 0 nodes that is failing? When at least 1 node is present in a given nodegroup CA will assume that the new node will look the same as the existing node. When scaling from 0 it has no node to use as example and so it tries to guess how a new node will look like. I suspect the problem would be that scale-from-0 logic doesn't include kubernetes.io/os label and so CA is not aware the node will have it.

Scale-from-0 logic is implemented differently by each provider so, assuming my guess is correct, we'd need to know which provider you're using. Also - core CA developers don't maintain provider implementations, so the issue would need to be handled by owners of a particular provider.

**Comment by autarchprinceps** [comment]
Yes, scale up from 0 and on AWS. I'll try to remove the node selector, as it isn't providing any additional benefit. I'll just have to see how, as Jenkins is the one starting these instances, so I don't have immediate kubernetes yaml access.
Thanks a lot for the details.

**Comment by autarchprinceps** [comment]
@MaciekPytel Jenkins doesn't easily support removing the nodeSelector. Can I do something to enable the cluster autoscaler to better spot the valid nodegroups? I can add a tag to the autoscaling group, if that helps. How does the AWS provider make the determination that it is or isn't linux? The ami in use should tell it that definitively, so the fact that it has to scale-from-0 shouldn't impede its ability to check that, just like it does correctly determine, that my instance type selection on that node group makes it the only one with sufficient cpus/memory, even if it doesn't have a running node to check how much resources a node gets.

**Comment by MaciekPytel** [comment]
Adding AWS provider owners to comment. 

cc: @Jeffwan @jaypipes

**Comment by autarchprinceps** [comment]
In the Jenkins Kubernete Plugin, I can replace the nodeSelector with a preferred affinity. I assume not being able to fulfil (or check fulfilment of) a preferred affinity won't prevent the autoscaler from using a certain nodegroup, right?
