### ISSUE TITLE
[VPA] Updater deployment missing NAMESPACE env var

### ISSUE THREAD

**Issue by nairb774** [kubernetes/autoscaler#3736]
The updater looks in a particular namespace to see if the admission controller is happy and healthy. The current admission controller sets the `NAMESPACE` environment variable correctly: https://github.com/kubernetes/autoscaler/blob/7a0731b51eec6396ee4a07ecec9a1aeb8472d50f/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml#L25-L29 but the updater doesn't have a similar value being set. Both need to be looking in the same namespace for this behavior to work. Configuring the `NAMESPACE` env var in the updater resolved the problem for us (we run the VPA outside of the `kube-system` namespace).

**Comment by bskiba** [comment]
Thanks Brian, would you be OK with contributing this fix?
