### ISSUE TITLE
Cluster Autoscaler doesn't delete unneeded nodes with no errors

### ISSUE THREAD

**Issue by abaskakau** [kubernetes/autoscaler#3753]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

v1.20.0

Component version:

Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

Nodes should be deleted in 5 minutes after cluster-autoscaler fresh restart.
According to passed params: 
`          - --scale-down-utilization-threshold=0.6
            - --scale-down-unneeded-time=5m
            - --scale-down-delay-after-add=5m`

**What happened instead?**:

Nodes are still alive and there are no error messages in cluster-autoscaler logs.
`
I1209 08:51:26.409338       1 static_autoscaler.go:492] ip-11-1-66-255.eu-central-1.compute.internal is unneeded since 2020-12-09 08:34:30.141977117 +0000 UTC m=+57.010667868 duration 16m56.262034032s
I1209 08:51:26.409359       1 static_autoscaler.go:492] ip-11-1-67-192.eu-central-1.compute.internal is unneeded since 2020-12-09 08:34:30.141977117 +0000 UTC m=+57.010667868 duration 16m56.262034032s
I1209 08:51:26.409374       1 static_autoscaler.go:492] ip-11-1-70-130.eu-central-1.compute.internal is unneeded since 2020-12-09 08:34:30.141977117 +0000 UTC m=+57.010667868 duration 16m56.262034032s
I1209 08:51:26.409391       1 static_autoscaler.go:492] ip-11-1-76-2.eu-central-1.compute.internal is unneeded since 2020-12-09 08:34:30.141977117 +0000 UTC m=+57.010667868 duration 16m56.262034032s
I1209 08:51:26.409409       1 static_autoscaler.go:492] ip-11-1-70-42.eu-central-1.compute.internal is unneeded since 2020-12-09 08:34:30.141977117 +0000 UTC m=+57.010667868 duration 16m56.262034032s
I1209 08:51:26.409425       1 static_autoscaler.go:503] Scale down status: unneededOnly=true lastScaleUpTime=2020-12-09 08:49:45.827022192 +0000 UTC m=+972.695712991 lastScaleDownDeleteTime=2020-12-09 08:34:20.141721714 +0000 UTC m=+47.010412455 lastScaleDownFailTime=2020-12-09 08:34:20.141721836 +0000 UTC m=+47.010412567 scaleDownForbidden=true isDeleteInProgress=false scaleDownInCooldown=true
`

Nodes are drained with SchedulingDisabled status. Both skip-nodes-with-system-pods and skip-nodes-with-local-storage are set to false

**How to reproduce it (as minimally and precisely as possible)**:

Just run the autoscaler in according environment and drain some nodes. Then wait

**Anything else we need to know?**:

Sometimes autoscaler deletes the group of unused nodes but I cannot find any time pattern between these deletions.
I checked every parameter passed to autoscaler and all delays seems to be ok.
The issue may present on k8s 1.17 too. Noticed that behaviour while upgrading to 1.18

**Comment by MaciekPytel** [comment]
The answer would be in `scaleDownForbidden=true` part of the log. That value usually means that there are pending pods present in cluster. CA will not scale-down until all the pending pods have been scheduled. You can find more details on technical reasons for blocking scale-down in the discussion https://github.com/kubernetes/autoscaler/pull/3547#discussion_r496803677.

**Comment by abaskakau** [comment]
Thanks for the rapid answer. I'll check this in an hour

**Comment by abaskakau** [comment]
Yep, there was a pod in Pending state that affected cluster-autoscaler. Thanks for your help

**Comment by abaskakau** [comment]
BTW, I see the mention from #3547 
We have node limits set in AWS that helps us not to cross the cost line. And yeah, right now we are at our node capacity.
Behaviour on scaling down when there are some pending pods looks absolutely reasonable to me. We use HPA for scaling workloads, and hitting max nodes (costs line) is breaking scaling down which means that costs are not falling back on low capacity level. So we spend extra $3000 this month because of this unexpected behaviour.
