### ISSUE TITLE
CA autoscaling wrong ASG (GPU) after hitting max size of one of the ASG (CPU)

### ISSUE THREAD

**Issue by n3o-Bhushan** [kubernetes/autoscaler#3767]
**Which component are you using?**: 

Cluster Autoscaler

**What version of the component are you using?**:

v1.17.2

**What k8s version are you using (`kubectl version`)?**: 

Client Version: v1.18.0
Server Version: v1.17.12-eks-7684af

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:11Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: AWS

**What did you expect to happen?**: 
Cluster Autoscaler is triggering ASG with CPU nodes.

**What happened instead?**: Cluster Autoscaler triggered ASG with CPU nodes but in the process also scaled ASG with GPU nodes.

**How to reproduce it (as minimally and precisely as possible)**: Schedule enough pods to hit the upper limit of a particular ASG. CA will end up scaling other ASG in the process.

**Anything else we need to know?**:

We have spark enabled on our cluster which works only on CPUs. Whenever a spark job ends up creating new pods, it triggers CA which correctly starts CPU nodes but if it hits the max size for that ASG (CPU Nodes) then it scales up GPU ASGs in the process. 
Logs where it triggers the correct ASG and hits the upper limit
```
 No pod can fit to cluster-1-eks-worker-m5.xlarge
I1207 23:23:50.481849       1 waste.go:57] Expanding Node Group cluster-1-eks-gpu-worker-p2.8xlarge would waste 50.00% CPU, 98.05% Memory, 74.03% Blended
I1207 23:23:50.481928       1 waste.go:57] Expanding Node Group cluster-1-eks-gpu-worker-p3.8xlarge would waste 50.00% CPU, 96.11% Memory, 73.05% Blended
I1207 23:23:50.481996       1 waste.go:57] Expanding Node Group cluster-1-eks-worker-m5.2xlarge would waste 50.00% CPU, 92.33% Memory, 71.16% Blended
I1207 23:23:50.482040       1 scale_up.go:430] Best option to resize: cluster-1-eks-worker-m5.2xlarge
I1207 23:23:50.482063       1 scale_up.go:434] Estimated 4 nodes needed in cluster-1-eks-worker-m5.2xlarge
I1207 23:23:50.482121       1 balancing_processor.go:111] Requested scale-up (4) exceeds node group set capacity, capping to 2
I1207 23:23:50.482140       1 scale_up.go:538] Final scale-up plan: [{cluster-1-eks-worker-m5.2xlarge 1->3 (max: 3)}]
I1207 23:23:50.482199       1 scale_up.go:699] Scale-up: setting group cluster-1-eks--worker-m5.2xlarge size to 3
I1207 23:23:50.482233       1 auto_scaling_groups.go:221] Setting asg cluster-1-eks--worker-m5.2xlarge size to 3
```

Here are the logs when it triggers GPU autoscaling after failing to schedule some pods due to upper limit on CPU ASG

```No pod can fit to cluster-1-eks-worker-m5.xlarge
I1207 23:24:00.672302       1 waste.go:57] Expanding Node Group cluster-1-eks-gpu-worker-p2.8xlarge would waste 75.00% CPU, 99.03% Memory, 87.01% Blended
I1207 23:24:00.672316       1 waste.go:57] Expanding Node Group cluster-1-eks-gpu-worker-p3.8xlarge would waste 75.00% CPU, 98.05% Memory, 86.53% Blended
I1207 23:24:00.672329       1 scale_up.go:430] Best option to resize: cluster-1-eks-gpu-worker-p3.8xlarge
I1207 23:24:00.672340       1 scale_up.go:434] Estimated 1 nodes needed in cluster-1-eks-gpu-worker-p3.8xlarge
I1207 23:24:00.672359       1 scale_up.go:538] Final scale-up plan: [{cluster-1-eks-gpu-worker-p3.8xlarge 0->1 (max: 3)}]
I1207 23:24:00.672370       1 scale_up.go:699] Scale-up: setting group cluster-1-eks-gpu-worker-p3.8xlarge size to 1
I1207 23:24:00.672406       1 auto_scaling_groups.go:221] Setting asg cluster-1-eks-gpu-worker-p3.8xlarge size to 1
```

**Comment by umialpha** [comment]
Is it expected? CA tries to find best node group to scale. what would you expect? Do you want GPU node group only be scaled up when GPU required?

**Comment by n3o-Bhushan** [comment]
Hey @umialpha thanks for the response. Yes, I expect GPU node group to be scaled only when GPU is required. I do have appropriate taints and labels set up for that. 

I am scaling all node groups from 0 and seeing similar line very often in logs
```Could not get a CSINode object for the node "template-node-for-cluster-1-eks-gpu-worker-p2.xlarge-2037444365075013849-0": csinode.storage.k8s.io "template-node-for-cluster-1-eks-gpu-worker-p2.xlarge-2037444365075013849-0" not found```

I am also seeing random GPU node scaling when CA is redeployed. But it works fine afterwards.

I don't know if the above line is related to this behavior?

**Comment by umialpha** [comment]
Could you provide your config. e.g. how did you set up your taints and labels.

**Comment by n3o-Bhushan** [comment]
@umialpha I have setup taints and labels using terraform using `kubelet_extra_args = --node-labels=abc, --register-with-taints=xyz`.

Has anything changed in CA (since version 1.14) when it scales from 0 ?

**Comment by umialpha** [comment]
IIUC CA uses scheduler pkg to predict. So CA(in fact, scheduler) should respect taints. I run some unit tests and it did respect taints.

Could you please copy and paste your node yaml with command "kubectl get node <gpu node name> -o yaml"

**Comment by n3o-Bhushan** [comment]
Hi @umialpha it does respect taints in general. The only unexpected behavior happens when scaling from 0 for the first time and when ASG hits the limit. What particular part you want to look from `kubectl get node <gpu node name> -o yaml`

**Comment by umialpha** [comment]
But from the logs you offered, "waste.go" checks "cluster-1-eks-gpu-worker-p2.8xlarge". However it shouldn't because gpu node should not be a option for scaling up. ScaleUp logic runs as follows,
1. Choose options of node groups to scale up.
2. Choose best option of one node group to scale up. (where "waste.go" takes place)
3. If "BalanceSimilarNodeGroups", find similar node groups.

IIUC gpu node group should be filtered out in the first round. So I want to check the gpu node info, e.g. its taints.
