### ISSUE TITLE
Helm chart : expanderPriorities in values are object but string expected in template

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/autoscaler#3776]
In `values.yaml` it looks like `expanderPriorities` should be passed as an `object`

https://github.com/kubernetes/autoscaler/blob/04b2ae823cf3369d9ba4b98b3be52450a0a7bead/charts/cluster-autoscaler/values.yaml#L126

But the template expects it to be a string

https://github.com/kubernetes/autoscaler/blob/04b2ae823cf3369d9ba4b98b3be52450a0a7bead/charts/cluster-autoscaler/templates/priority-expander-configmap.yaml#L11

**Comment by brennerm** [comment]
For anyone encountering this. A simple workaround is to use a YAML literal:
```yaml
expanderPriorities: |-
  10:
    - asg10
  0:
    - asg0
```

**Comment by eddycharly** [comment]
@brennerm why not change the template to:
```
 {{- toYaml .Values.expanderPriorities | nindent 4 }}
```
instead ?

**Comment by brennerm** [comment]
@eddycharly Cause the chart expects the value to be a string. Try passing the YAML object and it'll fail.

**Comment by eddycharly** [comment]
@brennerm yeah sure, i meant changing the template (not the values).

That is, changing https://github.com/kubernetes/autoscaler/blob/04b2ae823cf3369d9ba4b98b3be52450a0a7bead/charts/cluster-autoscaler/templates/priority-expander-configmap.yaml#L11 with:
```
 {{- toYaml .Values.expanderPriorities | nindent 4 }}
```

And then use an object in the values instead of a string literal:
```yaml
expanderPriorities:
  10:
    - asg10
  0:
    - asg0
```

I feel like an object would be more natural than a string literal in this case.

**Comment by brennerm** [comment]
Ahh, yeah that would fix it but would introduce a breaking change. :+1:

**Comment by eddycharly** [comment]
Unfortunately yes.
Not sure if it is possible to check if the value is a string in the template and then adapt to support both string or map.
It would allow to change the template while preserving backward compatibility. 
Will check that tomorrow.

**Comment by stevehipwell** [comment]
Either the docs or the template needs updating so this is consistent.

**Comment by jbilliau-rcd** [comment]
much thanks @brennerm , i've spent 2 hours trying to figure out wtf is the syntax for this since it's not documented. Your suggestion of the YAML literal fixed it for me.

**Comment by bwhaley** [comment]
Just noticed this issue after opening the PR! Any chance of cutting a backward release to fix this? My use case is to use the chart with the Terraform Helm provider. The code looks like this:

```
variable "expander_priorities" {
  description = "If scaling_strategy is set to 'priority', you can use this variable to define cluster-autoscaler-priority-expander priorities. See: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md"
  type        = map(list(string))
  default     = {}
  # Example:
  #
  # expander_priorities = {
  #   10 = [".*"]
  #   50 = ["foo.*"]
  # }
}

variable "priority_config_map_annotations" {
  description = "If scaling_strategy is set to 'priority', you can use this to specify annotations to add to the cluster-autoscaler-priority-expander ConfigMap."
  type        = map(string)
  default     = {}
}

resource "helm_release" "k8s_autoscaler" {
  repository = "https://kubernetes.github.io/autoscaler"
  name       = local.release_name
  chart      = local.chart_name
  version    = var.cluster_autoscaler_chart_version
  namespace  = local.chart_namespace

  values = [yamlencode(local.chart_values)]

  depends_on = [
    aws_eks_fargate_profile.cluster_autoscaler,
    null_resource.dependency_getter,
  ]
}

locals {
  chart_values = merge(
    {
      ... <snip> ...
      expanderPriorities           = var.expander_priorities
      priorityConfigMapAnnotations = var.priority_config_map_annotations

      extraArgs = merge(
        {
          expander                    = var.scaling_strategy
          balance-similar-node-groups = "true"
        },
        var.container_extra_args,
      )
    },
      ... <snip> ...  
  )
}
```

It's a nice clean interface with types for `expander_priorities` and `priority_config_map_annotations`. To make it work with this work around, I think I'll have to make `expander_priorities` a string and pass in the workaround as a heredoc, explain it in the docs, etc. e.g.

```
variable "expander_priorities" {
  description = "If scaling_strategy is set to 'priority', you can use this variable to define cluster-autoscaler-priority-expander priorities. See: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md"
  type        = string
  default     = "
  # Example:
  #
  # expander_priorities = <<EOF
  #   10 = [".*"]
  #   50 = ["foo.*"]
  # EOF
}
```

I _think_ this will work, but not sure yet, and anyway it's not ideal as it will be easy to pass in the wrong value.

WDYT about `toYaml`?

**Comment by stevehipwell** [comment]
I do this in terraform at the moment and just capture it as a string.

```terraform
locals {
  expander_config = <<-EOT
    100:
      - .*-spot-.*
    10:
      - .*
  EOT
}
```

I stand by my comment above that either the docs or the implementation need changing; it wouldn't be too complicated to change the implementation to support both formats (see [example](https://github.com/stevehipwell/helm-charts/blob/1b7f1cc1882a8dd859b129d5a76a746c41525570/charts/tigera-operator/templates/installation.yaml#L10)).

**Comment by bwhaley** [comment]
Good point, @stevehipwell! Updated my PR with your idea.

I hope this will be merged. I burned a couple of hours on this issue.

**Comment by gjtempleton** [comment]
I believe this can be closed given your PR has been merged and the new version of the chart released, any objection @bwhaley ?

**Comment by bwhaley** [comment]
Yup, agreed!
