### ISSUE TITLE
Support enable/disable of the Pod Disruption Budget

### ISSUE THREAD

**Issue by loreleimccollum-work** [kubernetes/autoscaler#3779]
**Which component are you using?**: cluster-autoscaler helm chart

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

**Describe the solution you'd like.**:
We are using terraform and helm to roll out cluster autoscaler, and finding that we do not want the PDB that comes by default with the cluster autoscaler. We would rather define our own. Because Terraform merges the values, we cannot just say use minAvailable instead because it defaults to https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml#L207 maxUnavailable. And helm fails because the spec does not allow both minAvailable and maxUnavailable to be set at the same time.
I have seen other projects have an podDisruptionBudget enable/disable flag

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by Chili-Man** [comment]
I would like to see this supported in the Helm chart as well;

**Comment by mataneja** [comment]
@loreleimccollum-work For my and other's benefit, would love to understand your use case requiring a custom PDB... What would you like to set it to instead?

**Comment by loreleimccollum-work** [comment]
@mataneja  the current helm chart hardcodes maxUnavailable on by default. We would rather use minAvailable option to configure out PDB, but since Terraform helm release merges your values you want to set ( we set the minAvailable) with the existing values which has the other one, the helm release fails because per policy of PDB, you are not allowed to have both set

**Comment by voidlily** [comment]
I was able to work around this with the following

```
podDisruptionBudget = {
  minAvailable = 1
  maxUnavailable = null
}
```

**Comment by tommylindgren-plejd** [comment]
Issue still exist, unable to set only minAvailable using helm chart.
If setting:
```
podDisruptionBudget:
    minAvailable: 1
```
The generated template will be:
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
  ...
  name: <name>
spec:
  selector:
    matchLabels:
    ...
  
  maxUnavailable: 1
  minAvailable: 1
```
Which is not allowed.
