### ISSUE TITLE
Cluster downsizing not working due to cluster proportional autoscaler dummy pod consuming more than 50%

### ISSUE THREAD

**Issue by pc-rshetty** [kubernetes/autoscaler#3791]
**Which component are you using?**:

Cluster Proportioanal autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
As per the documents 
`The sum of cpu and memory requests of all pods running on this node is smaller than 50% of the node's allocatable. (Before 1.1.0, node capacity was used instead of allocatable.)`

Cluster downsizing not working due to cluster proportional autoscaler dummy pod consuming more than 50%. Technically this cab be evicted to other node

```
  Namespace                               Name                                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                               ----                                                               ------------  ----------  ---------------  -------------  ---
  cluster-proportional-autoscaler-system  cluster-proportional-autoscaler-p-default-overprovisionzf74m    8 (51%)       0 (0%)      8G (12%)         0 (0%)         22h
```
**Describe the solution you'd like.**:

Have a mechanism to evict a specific , may be use an annotation  ? 

**Describe any alternative solutions you've considered.**:

May be i need to add this annotation to cluster proportinal autoscaler ? 
```
"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
```

**Additional context.**:

**Comment by umialpha** [comment]
AFAIK, [Cluster Proportioanal Autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) is another autoscaler which does not belong to this repo.

**Comment by MaciekPytel** [comment]
You can change the 50% utilization threshold using `--scale-down-utilization-threshold` flag. There is no mechanism to ignore utilization of a single pod (safe-to-evict annotation bypasses other checks, such as checks if pod is owned by controller, but it doesn't impact utilization calculation).

**Comment by pc-rshetty** [comment]
@umialpha i know that :) . Think of it as any other pod. What i had to do is add the annotation then it let that pod evict.


@MaciekPytel yes so right now there is a  way at pod level is to mark this annotation and it works
```
"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
```

**Comment by MaciekPytel** [comment]
As per my previous comment - safe-to-evict annotation bypasses some checks that would otherwise prevent a pod from being restarted, but the pod with the annotation counts normally for the purposes of utilization check.
