### ISSUE TITLE
Failed to scale up: AadProfile.ClientAppID value can not be null

### ISSUE THREAD

**Issue by ychanaa** [kubernetes/autoscaler#3795]
**Which component are you using?**:
Cluster-autoscaler

**What version of the component are you using?**:
Image:v1.18.1, helm chart:1.18.1

Component version:

**What k8s version are you using (`kubectl version`)?**:
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AKS

**What did you expect to happen?**:
It is able to AKS up or down

**What happened instead?**:
Failed to scale up and down with below error:
1 static_autoscaler.go:415] Failed to scale up: failed to increase node group size: containerservice.ManagedClustersClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.ManagedClusterProperties.AadProfile.ClientAppID constraint=Null value=(*string)(nil) details: value can not be null; required paramete

**How to reproduce it (as minimally and precisely as possible)**:
I am using AKS version v1.17.11, and enabled AKS managed AAD

**Anything else we need to know?**:
The AKS was created with terraform, and recently enabled AKS managed AAD. I suspect this is the cause but not sure.

**Comment by monaka** [comment]
same here. AKS. recently enabled managed AAD. 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by iojas** [comment]
Any resolution for this ? I am facing the same issue in my infra pipeline.
