### ISSUE TITLE
Update documentation to use “control plane” term

### ISSUE THREAD

**Issue by sftim** [kubernetes/autoscaler#3796]
**Which component are you using?**:

`cluster-autoscaler`

**What version of the component are you using?**:

_not applicable_ (issue is about primary GitHub branch)

**Component version**:

_not applicable_

**What environment is this in?**:

_not applicable_

**What did you expect to happen?**:

Documentation talks about “control plane”

**What happened instead?**:

Documentation talks about a “master” or “master node”

**How to reproduce it (as minimally and precisely as possible)**:

View the cluster autoscaler readme

**Anything else we need to know?**:

/wg naming

**Comment by sftim** [comment]
https://github.com/kubernetes/autoscaler/tree/a346d772a3a872faee149ce244e95806b73b9aba/cluster-autoscaler#readme

**Comment by gjtempleton** [comment]
Thanks for raising this!

I've raised #3803 to capture all of our doc references to the old terminology.
