### ISSUE TITLE
Cluster Autoscaler Deployment link in README for GCE is wrong?

### ISSUE THREAD

**Issue by jatin-pathangi** [kubernetes/autoscaler#3798]
**Which component are you using?**:
Cluster Autoscaler

**What version of the component are you using?**:
1.16.x

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.16
<details><summary><code>kubectl version</code> Output</summary><br><pre>

</pre></details>

**What environment is this in?**:
GCE

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The link for GCE here https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment is this: https://kubernetes.io/docs/tasks/administer-cluster/, which doesn't seem to contain any relevant information about deploying cluster autoscaler on a GCE cluster, whereas every other supported Cloud Provider has their own README page. I'm wondering why the discrepancy and if this is an oversight? I'm trying to set up Cluster Autoscaler on a kubernetes cluster in GCE (not GKE, but a self-managed cluster), and was looking targeted documentation similar to what's present for AWS/Azure etc.

**Comment by unixfox** [comment]
I'm also trying to deploy autoscaler on GCE (not GKE) and I just don't find any documentation for that.

Did you manage to install it anyway?

**Comment by MoSheikh** [comment]
I'm experiencing difficulties with the same issue as well. It would be extremely helpful having some documentation for GCE since all other major cloud providers do. Thank you!

**Comment by MiguelLucas** [comment]
Would also appreciate if some kind of documentation was provided, as there is tons of information on deploying the cluster autoscaler on GKE but not on GCE only. Thank you

**Comment by js-max** [comment]
Checking https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/gce I'm not able to see any README or related info.

Am I missing something?
