### ISSUE TITLE
vpa-admission-controller: generate tls certs automatically

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3816]
https://github.com/open-policy-agent/gatekeeper

Deploys the mutatingwebhook manually which allows end users to configure all the settings they want and automatically handles cert creation. Can we get that here too?

Problem is having to manually run gen_certs.sh and having to run that command against all clusters doesn't work with our gitops approach.

**Comment by bskiba** [comment]
Sounds like a nice improvement, would you be interested in contributing?

**Comment by JESWINKNINAN** [comment]
@bskiba Can you please assign this task to me?

**Comment by JESWINKNINAN** [comment]
@bskiba Can you please share development guide of VPA, I have the non-tested code which requires best approach to test the functionality.
