### ISSUE TITLE
Chart releases no longer working

### ISSUE THREAD

**Issue by barrydobson** [kubernetes/autoscaler#3819]
Helm Chart for Cluster Auto Scaler

Helm Chart

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

Helm uses latest release

Pulling latest version

Latest available chart version is 9.3.0

The GitHub action failed releasing 9.3.1 and since then the chart releaser action is unable to determine changes.

**Comment by gjtempleton** [comment]
Hey, thanks for raising this.

It's actually a known issue with the chart releasing action we use, as it attempts an automated push to the `gh-pages` branch and we have branch protection enforced on all branches.

This means we have to rely on a manual PR creation process post merging to add the new charts to the `index.yaml`

I've just raised #3826 to push out the 9.3.1 and 9.3.2 releases.

**Comment by barrydobson** [comment]
Great, thanks. I needed a fix that was in 9.3.1. I'll close the issue.
