### ISSUE TITLE
Travis-ci.org Shutdown - Migration to Travis-ci.com

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#3825]
**Which component are you using?**:
N/A

**What version of the component are you using?**:

N/A

**What k8s version are you using (`kubectl version`)?**:

N/A

**What environment is this in?**:

N/A

**What did you expect to happen?**:

Travis CI builds should be processed through https://travis-ci.com

**What happened instead?**:

The deprecated https://travis-ci.org is still used, potentially breaking our builds once the old domain is switched off.

**How to reproduce it (as minimally and precisely as possible)**:

Visit a travis build from a PR to this repository:
https://travis-ci.org/github/kubernetes/autoscaler/builds/752730430

**Anything else we need to know?**:

Travis' announcement of the intended shutdown of travis-ci.org:
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

Travis' instructions for moving to travis-ci.com:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by gjtempleton** [comment]
cc: @MaciekPytel

**Comment by MaciekPytel** [comment]
I tried to click through migration process and it seems that it requires activating "Github Apps Integration". This involves approving github permissions for travis as Kubernetes organization (it seems there is an option to only give travis permissions for kubernetes/autoscaler, though I have no idea if that will actually work or not).
I have no idea what process would be involved to grant those. I think the next step should be finding the group that is responsible for managing the github org and ask them for help. cc: @mwielgus

**Comment by mwielgus** [comment]
As not that many Kubernetes subprojects seems to be using travis, we may take this opportunity and migrate to some more popular option. I'm checking the options right now.
