### ISSUE TITLE
Create a well-defined RBAC role for cluster-autoscaler

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/autoscaler#383]
FWIU currently cluster-autoscaler runs as part of the master node's hostNetwork talking to the apiserver over localhost, bypassing auth. It has cluster-admin powers.
It should instead use a least privilege role (with corresponding binding), just like other control-plane components and addons.

cc @MaciekPytel @bskiba @aleksandra-malinowska @mwielgus

**Comment by mwielgus** [comment]
We can think about restricting CA privileges in apisever. However, please remember that CA, by design, has more than enough privileges to ruin your cluster completely (for example - delete arbitrary nodes and pods).

**Comment by shyamjvs** [comment]
> However, please remember that CA, by design, has more than enough privileges to ruin your cluster completely (for example - delete arbitrary nodes and pods).

There are other control-plane components which are also privileged enough to ruin the cluster. For e.g scheduler can handicap the whole cluster if it stops scheduling, node-controller can mark all the nodes unschedulable or delete node objects, route-controller (which also talks to cloud-provider) can handicap pod-to-pod communication. But we still have roles defined for them (ref https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go#L191, https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L340). In general, we want to give only as much powers as required to the components. For e.g we don't want CA to delete services accidentally.

**Comment by mwielgus** [comment]
I understand, just saying why it not our top priority at this moment. However, we will try to do it for 1.9.

**Comment by shyamjvs** [comment]
Sure.. Just noticed while reviewing @bskiba 's PR on kubemark CA.
