### ISSUE TITLE
Cluster autoscaler dosent work in AWS region eu-south-1 (Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list)

### ISSUE THREAD

**Issue by kakarotbyte** [kubernetes/autoscaler#3830]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

 Tested 
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.18.3",
"eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.18.1", 
"gcr.io/google-containers/cluster-autoscaler:v1.18.0" 
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.3
and "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.16.7

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
Test

**What did you expect to happen?**:

 cluster autoscaler pod in running state

**What happened instead?**:

NAME                                 READY   STATUS             RESTARTS   AGE
cluster-autoscaler-bfbcb7458-57w22   0/1     CrashLoopBackOff   752        2d16h

**How to reproduce it (as minimally and precisely as possible)**:

 create cluster autoscaler in eu-south-1 region

**Anything else we need to know?**:

Logs from POD **cluster-autoscaler-bfbcb7458-57w22**
 I0116 22:18:20.185757       1 cloud_provider_builder.go:29] Building aws cloud provider.
I0116 22:18:20.185779       1 aws_util.go:150] fetching http://169.254.169.254/latest/dynamic/instance-identity/document
I0116 22:18:20.382299       1 reflector.go:150] Starting reflector *v1beta1.PodDisruptionBudget (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.382323       1 reflector.go:185] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.382705       1 reflector.go:150] Starting reflector *v1.PersistentVolume (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.382714       1 reflector.go:185] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383000       1 reflector.go:150] Starting reflector *v1.StatefulSet (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383008       1 reflector.go:185] Listing and watching *v1.StatefulSet from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383275       1 reflector.go:150] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383283       1 reflector.go:185] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383529       1 reflector.go:150] Starting reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383538       1 reflector.go:185] Listing and watching *v1.Service from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383760       1 reflector.go:150] Starting reflector *v1.ReplicationController (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383768       1 reflector.go:185] Listing and watching *v1.ReplicationController from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383959       1 reflector.go:150] Starting reflector *v1.ReplicaSet (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.383967       1 reflector.go:185] Listing and watching *v1.ReplicaSet from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.384209       1 reflector.go:150] Starting reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.384216       1 reflector.go:185] Listing and watching *v1.Node from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.384462       1 reflector.go:150] Starting reflector *v1.StorageClass (0s) from k8s.io/client-go/informers/factory.go:135
I0116 22:18:20.384470       1 reflector.go:185] Listing and watching *v1.StorageClass from k8s.io/client-go/informers/factory.go:135
F0116 22:18:20.384509       1 aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

- **cause of our error is coming from the** [line63](https://github.com/kubernetes/autoscaler/blob/d5214ad4d2f8585ac11fb94a89077b534a9dc056/cluster-autoscaler/cloudprovider/aws/aws_util.go#L63).  As `region= eu-south-1` and `r.ID()` value is not present.

			if region != "" && region != r.ID() {
				continue
			}
- we get r. ID() from [endpoints/defaults.go](https://github.com/kubernetes/autoscaler/blob/d5214ad4d2f8585ac11fb94a89077b534a9dc056/cluster-autoscaler/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go#L18).  And we can see that  **eu-south-1** is missing. 

    const (
        ApEast1RegionID      = "ap-east-1"      // Asia Pacific (Hong Kong).
        ApNortheast1RegionID = "ap-northeast-1" // Asia Pacific (Tokyo).
        ApNortheast2RegionID = "ap-northeast-2" // Asia Pacific (Seoul).
        ApSouth1RegionID     = "ap-south-1"     // Asia Pacific (Mumbai).
        ApSoutheast1RegionID = "ap-southeast-1" // Asia Pacific (Singapore).
        ApSoutheast2RegionID = "ap-southeast-2" // Asia Pacific (Sydney).
        CaCentral1RegionID   = "ca-central-1"   // Canada (Central).
        EuCentral1RegionID   = "eu-central-1"   // EU (Frankfurt).
        EuNorth1RegionID     = "eu-north-1"     // EU (Stockholm).
        EuWest1RegionID      = "eu-west-1"      // EU (Ireland).
        EuWest2RegionID      = "eu-west-2"      // EU (London).
        EuWest3RegionID      = "eu-west-3"      // EU (Paris).
        MeSouth1RegionID     = "me-south-1"     // Middle East (Bahrain).
        SaEast1RegionID      = "sa-east-1"      // South America (Sao Paulo).
        UsEast1RegionID      = "us-east-1"      // US East (N. Virginia).
        UsEast2RegionID      = "us-east-2"      // US East (Ohio).
        UsWest1RegionID      = "us-west-1"      // US West (N. California).
        UsWest2RegionID      = "us-west-2"      // US West (Oregon).
    )

**Comment by lomluca** [comment]
I’ve noticed this bug has been fixed in CA v1.20. Is it possible to cherrypick backwards?

**Comment by kakarotbyte** [comment]
@lomluca 
Yes! it has beed resolved in latest images. Thank you for confirming.

 [endpoints/defaults.go. ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go#L19)
