### ISSUE TITLE
prevent from k8s resource (deployment/statefulset) to perform node scale-up

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes/autoscaler#3843]
**Which component are you using?**:

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

my problem is related to a scenario which I have a scale group with `zero` nodes, those nodes will be scaled up only when a specific `Deployment` called `foo` are applied which will deploy `pods` with the relevant `nodeSelector`. The thing is that I want that other `Deplyment` with the same `nodeSelector` called `bar` will be also applied, but that the pods will stay in `Pending` until a new node will be created by the k8s autoscaler because of the `Deployment` `foo` .
Why? because the `bar` pods are only serve the `foo` pods

**Describe the solution you'd like.**:

Add new annotation for the k8s resources (deployment/statefulset) that you don't want that will trigger new node sacle-up, like `"cluster-autoscaler.kubernetes.io/enable-scale-up": "false"`
In this way we will be able to exlude / ingore nodes from saclling up by resources that are not supposed to do it
The autoscaler should also detect that if no pods from `foo` exist on the node and only `bar` pods exist, it will trigger scalw-down to the node, just like daemonsets behavior.

workaround:
create a daemonset, but it's a waste of recources

**Comment by MaciekPytel** [comment]
Can you explain why creating DS is a waste of resources? It seems like a DS with nodeSelector would behave exactly the way you want deployment bar to behave?

Alternatively setting podPriority below --expendable-pods-priority-cutoff may be another way to achieve what you want. This will make the deployment ~invisible to CA - it will not trigger scale-up and it will not block scale-down.

I see adding annotation as a last resort for common problems with no alternative solution. From our side it is effectively an API that we will have to maintain, test and fix effectively forever and hence the bar for adding one should be very high.

**Comment by dsaydon90** [comment]
Hi @MaciekPytel ,
> Can you explain why creating DS is a waste of resources? It seems like a DS with nodeSelector would behave exactly the way you want deployment bar to behave?

Because I need 1 replica of that service. For instance, 4 nodes that contains 1 pod with dind (docker in docker) and 6 jenkins agent pods . DS in this case will create 4 dind pods instead of 1.

It will try to test your solution with the  --expendable-pods-priority-cutoff.
It will be awesome if you have any link to some docs that explains how to achieve that
