### ISSUE TITLE
HPA and VPA combo in mode "off"

### ISSUE THREAD

**Issue by reggie-k** [kubernetes/autoscaler#3858]
I see that if using  VPA auto-update combo with HPA is not supported, and it is clear why.
We intend to use VPA in recommendation mode only. In that case, can it be combined with HPA? Will the recommendations provided be correct?

**Comment by reggie-k** [comment]
Any news on this?

**Comment by jnimety** [comment]
I’m curious about this too. Any chance a dev can chime in and answer this question?
