### ISSUE TITLE
Cluster autoscaler CAPI support to watch specific namespaces

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#3870]
**Which component are you using?**:

cluster autoscaler CAPI Provider

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Cluster autoscaler in multi tenancy environments

**Describe the solution you'd like.**:

Ability for CAPI provider to watch a particular namespace.

For multi tenancy environments where CAPI scalable resources and so machines for different cluster should belong to different namespaces I want an instance of the cluster autoscaler CAPI provider to watch only a particular namespace so it's only aware of scalable resources for a single cluster and it's able to operate as expected.

Related to https://github.com/kubernetes-sigs/cluster-api/issues/4139

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by enxebre** [comment]
cc @JoelSpeed @elmiko

**Comment by JoelSpeed** [comment]
Does the [Autodiscovery](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi#configuring-node-group-auto-discovery) selection solve this use case?

Can we use this option plus RBAC to limit the autoscaler to only be able to get scalable resources from a single namespace/cluster?

**Comment by enxebre** [comment]
Yeh autodiscovery could be leveraged for that though I think having the ability to lock down the controller to  watch a particular ns would be sensible

**Comment by JoelSpeed** [comment]
In particular, to add some detail to this, you can't currently restrict the autoscaler to a particular namespace using RBAC because the informer watches all namespaces

https://github.com/kubernetes/autoscaler/blob/3690aaa2e31016ea00793266295f81dae6247276/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L322

If we can parse the autodiscovery spec and then set up the informer to watch the namespace set by the autodiscovery I think that would solve this problem

**Comment by CecileRobertMichon** [comment]
> and so machines for different cluster should belong to different namespaces

I don't think that's true. There's no requirement in CAPI for each cluster to belong to a different namespace.

**Comment by JoelSpeed** [comment]
> There's no requirement in CAPI for each cluster to belong to a different namespace.

While there's no explicit requirement, I think there is a recommendation coming from the multi-tenancy work that the namespace is the security boundary for clusters.

As I see it, in a multi-tenant environment, we need to be able to support multiple clusters from the same tenant in the same namespace, but assume that another namespace is owned by a separate tenant and as such, there should be no crossover of permissions

CC @randomvariable perhaps you could add some more context on the namespace security boundary discussion

**Comment by elmiko** [comment]
just reviewing these comments again. i agree with Joel about adjusting to watch singular namespaces, it seems like the informer would need to be restricted in what it watches for.

as for the cluster identifier part, ideally we can use the cluster label[0] with the node autodiscovery filtering to help confine the machine[set|deployment] lists.

[0] https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go#L33
