### ISSUE TITLE
[AWS] AutoScaling API throttling from DescribeTags calls when using Cluster Autoscaler

### ISSUE THREAD

**Issue by shahadc** [kubernetes/autoscaler#3877]
**Which component are you using?**: 
AWS Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: 
On medium/large environments, the default recommended settings (using auto-discovery; 2 tags, one for "enabled" and one for "cluster-id") causes large amounts of API throttling (and thus slower pod scaling) when making calls to AutoScaling since the DescribeTags call only allows OR operations when searching for multiple tag keys.  

As an example, lets take an account with 100 clusters enabled, each with 4 ASGs/node groups.  Every time a scaling event for any cluster needs to happen, there would be 6 API calls to AutoScaling 
* 5 DescribeTags (100 results per API call, and 100 "enabled" tags + the 4 for the cluster-id)
* 1 DescribeASGs

**Describe the solution you'd like.**:
Have "Enabled" or "Disabled" be tag values on the tag Key <cluster-ID>.  This would mean only the <cluster-id> would be returning in DescribeTags and there shouldn't ever be more than 100 ASGs in a single cluster.  This wouldn't be a breaking change since currently from what I can tell the tag value isn't being looked at in CA and thus would allow for backwards compatibility.  

**Describe any alternative solutions you've considered.**:

1) Have the AWS DescribeAutoScalingGroups API call add a filter option added to it so that only ASG(s) with a given set of tags are returned.  
2) Modify the guidance to mention large accounts shouldn't use the "Enabled" tag or should use the single/multi ASG specifications instead of auto-discovery

**Additional context.**:
- I am an AWS employee and can put in a request with the AutoScaling team to consider making the DescribeASG API change if that would be the ideal fix for this problem if the other solutions would cause issues.

**Comment by johanneswuerbach** [comment]
Hey @AustinSiu thanks for the ping, I've updated my PR.

**Comment by shahadc** [comment]
Done, sorry for that, I don't have much experience with public projects and didn't realize it being closed mattered after the PR was created

**Comment by AustinSiu** [comment]
> Done, sorry for that, I don't have much experience with public projects and didn't realize it being closed mattered after the PR was created

No worries at all :)

**Comment by shahadc** [comment]
@AustinSiu or @johanneswuerbach , is there any other action needed to get one of the linked PRs for this issue pushed?

**Comment by johanneswuerbach** [comment]
Yes, the updated aws sdk need for this API is currently pending review https://github.com/kubernetes/autoscaler/pull/4424#discussion_r784908748

**Comment by shahadc** [comment]
/remove-lifecycle stale
Waiting on SDK update in: https://github.com/kubernetes/autoscaler/pull/4950

**Comment by johanneswuerbach** [comment]
@AustinSiu yes, updated my PR.
