### ISSUE TITLE
Replace large node with a smaller one when using least-waste

### ISSUE THREAD

**Issue by komljen** [kubernetes/autoscaler#389]
I would like for autoscaler to be able to replace the larger node with a smaller one. For example, I have one pod running on m3.large and another one on m3.medium. Those nodes are two IGs in the same zone. Both can scale up to 5 nodes (0->5).

It should probably start another node in m3.medium IG, move pod to it and terminate the larger instance.

AC 0.6.2 with Kubernetes 1.6.6.

**Comment by MaciekPytel** [comment]
Hi @komljen,
Ideally this is something we would like CA to do, but we're still far away from being able to do this sort of cluster optimization. I don't think we're likely to get there in 1.9 or 1.10 timeframe.

**Comment by komljen** [comment]
I understand. As a workaround, I added https://github.com/cristim/autospotting in the mix. It seems to work nicely for now. Basically, it replaces on-demand instances with spot when available.
