### ISSUE TITLE
cluster-autoscaler: Helm Chart Release for 1.19 doesn't exist

### ISSUE THREAD

**Issue by SatoruItaya** [kubernetes/autoscaler#3901]
**Which component are you using?**:

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Helm Chart Release for 1.19 doesn't exist.
[9.5.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.5.0) is for 1.20, and [9.4.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.4.0) is for 1.18. 

**Describe the solution you'd like.**:

I would like you to release Charts for 1.19.

**Comment by bobmacks** [comment]
+1 - looking to upgrade to EKS 1.19 but can't find an autoscaler chart version to support this cluster rev...

**Comment by indreek** [comment]
+1

**Comment by gjtempleton** [comment]
Hi there, 

What functionality do you think is missing from the chart to prevent you achieving what you want by overriding the default image tag value to a 1.19 release of the cluster autoscaler, e.g. passing a values file with:

```yaml

image:
  tag: v1.19.1
```

As far as I'm aware there should be nothing preventing you from overriding this to the version you desire.

**Comment by SatoruItaya** [comment]
@gjtempleton 
Thanks for your response.
I will try the way you taught us on the chart for 1.18.
