### ISSUE TITLE
Auto scaling with network connection

### ISSUE THREAD

**Issue by smling** [kubernetes/autoscaler#3908]
Currently using K8S Aautoscaler to scale REST API service with CPU and RAM.

Found that even network connection increase but CPU / RAM still in low process and it resulted request timeout.

Therefore, I would like to have a feature which can get pod's network loading (e.g. incoming / outgoing / current connection count) as auto scaling criteria by default.

**Comment by gjtempleton** [comment]
Hey, this functionality should already be possible using [custom metrics autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics). 

You'd just need to ensure you were exposing the relevant metric under the custom metrics API, either on a per pod or per object (e.g. load balancer) basis via whichever implementation of the custom metrics API you used.
