### ISSUE TITLE
Autoscaler scales down AWS ASGs unrelated to cluster.

### ISSUE THREAD

**Issue by orkhanM** [kubernetes/autoscaler#391]
Noticed kube-autoscaler was scaling ASGs unrelated to the cluster. I spun up a cluster with kube-aws with kube-autoscaler enabled in an existing VPC and subnet. Noticed Autoscaling groups being scaled by kube-autoscaler that shouldn't have been.

**Comment by MaciekPytel** [comment]
@orkhanM Can you provide your Cluster Autoscaler configuration and Cluster Autoscaler logs with the scale-up that shouldn't have happened?

**Comment by orkhanM** [comment]
@MaciekPytel Unfortunately I no longer have any logs tied to this event, I'll try reproducing the issue in a staging environment and open another ticket with clearer definition. My apologies, i'm going to close this issue out.
