### ISSUE TITLE
Need support for customized recommender in Vertical Pod Autoscaler (VPA)

### ISSUE THREAD

**Issue by wangchen615** [kubernetes/autoscaler#3913]
**Which component are you using?**:
Vertical Pod Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Today, the current VPA recommends CPU/Mem requests and limits based on one recommender, 
which recommends the future requests/limits based on the historical usage observed in a 
rolling time window. As there is no universal recommendation policy that applies to all 
types of workload, this feature requests supporting multiple customized recommenders in VPA.

**Describe the solution you'd like.**:
The support of a customized recommender can be implemented via a first-citizen approach. Namely, a dedicated field `recommenderName` can be added to the VPA object to indicate which recommender to use.

**Describe any alternative solutions you've considered.**:
- Develop a plugin framework for customizable recommenders.
- Develop a label selector approach.

**Additional context.**:
This issue is created to obtain a KEP number.

**Comment by bskiba** [comment]
Shouldn't we keep open for implementation? Or do you want to track separately?

**Comment by wangchen615** [comment]
> Shouldn't we keep open for implementation? Or do you want to track separately?

Yes, let's keep it open until the implementation is merged.

**Comment by Jeffwan** [comment]
@wangchen615 What's the status of this VPA KEP? Is there a PR going on?

**Comment by wangchen615** [comment]
@Jeffwan , I am still working on the implementation. Will create the PR soon, in 2 weeks.

**Comment by Jeffwan** [comment]
/remove-lifecycle stale

We are still working on this
