### ISSUE TITLE
[VPA] Support AdditionalPrintColumns for VPA & VPACheckpoint CRs

### ISSUE THREAD

**Issue by Ladicle** [kubernetes/autoscaler#3917]
**Which component are you using?**: vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently, `kubectl get` only shows vpa & vpacheckpoint resource name and age. However, I would like to check other information such as whether the recommended value has been provided.

```bash
$ kubectl get vpacheckpoint
NAME               AGE
redis-vpa-master   0s

$ kubectl get vpa
NAME        AGE
redis-vpa   8s
```

**Describe the solution you'd like.**:

Set additional-print-columns like the following information to custom resources.

```bash
$ kubectl get vpa -w
NAME        MODE   CPU   MEM       PROVIDED   AGE
redis-vpa   Auto   25m   262144k   True       8m58s

$ kubectl get vpacheckpoint
NAME               VERSION   TOTAL   FIRST   LAST
redis-vpa-master   v3        24      8m22s   82s
```

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by bskiba** [comment]
I'd love to see this for VPA objects, not very keen about checkpoints as they are really meant as an internal object for vpa-recommender with no promises on the contents.

**Comment by Ladicle** [comment]
@bskiba Thank you for your feedback. Certainly vpa checkpoints shouldn't show much content. How about displaying only the time when the sample was last taken and the age of the resource?

**Comment by bskiba** [comment]
That sounds good, thanks!
