### ISSUE TITLE
Cloud provider instance-type tags break --balance-similar-node-groups behaviour

### ISSUE THREAD

**Issue by awh** [kubernetes/autoscaler#3919]
Kubelet cloud providers [add](https://kubernetes.io/docs/reference/labels-annotations-taints/#nodekubernetesioinstance-type) a `node.kubernetes.io/instance-type` label (formerly `beta.kubernetes.io/instance-type`) which, as far as I can tell, is not ignored by the comparator used by the cluster autoscaler to find similar node groups (see [here](https://github.com/kubernetes/autoscaler/blob/19f97f775ea1b7af977002ef1569d0fe077bd35a/cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go#L43-L49) and [here](https://github.com/kubernetes/autoscaler/blob/19f97f775ea1b7af977002ef1569d0fe077bd35a/cluster-autoscaler/processors/nodegroupset/aws_nodegroups.go#L28-L32)). As a consequence, node groups with mixed instance types might not be considered similar even if the types in question have identical resource capacities. Is this an oversight?

**Comment by stevehipwell** [comment]
Is this actually an issue?
