### ISSUE TITLE
Handle autoscaling of GPUs in GKE

### ISSUE THREAD

**Issue by vishh** [kubernetes/autoscaler#392]
Instance templates have accelerators included in them. The resource type expected to be used for GKE clusters to access GPUs is `nvidia.com/gpus`. Autoscalar should add to and remove from node-pools that have `nvidia-tesla-[k80|p100]` accelerator type included in them.

If the node pool containing GPUs is not the only node pool it is preferrable to scale all the way down to zero.
Output from gcloud instance-templates describe
```
guestAccelerators:
  - acceleratorCount: 8
    acceleratorType: nvidia-tesla-k80
```

cc @mwielgus

**Comment by bskiba** [comment]
Fixed with #401
