### ISSUE TITLE
[magnum] Cluster autoscaler breaks when the minimum node count is 0

### ISSUE THREAD

**Issue by brtknr** [kubernetes/autoscaler#3928]
**Which component are you using?**:

**What version of the component are you using?**:

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by brtknr** [comment]
@tghartland

**Comment by tghartland** [comment]
It's disabled here:
https://github.com/kubernetes/autoscaler/blob/31e2b4313ad4ff8a00d329e52c84ca541af982fb/cluster-autoscaler/cloudprovider/magnum/magnum_util.go#L27

Can you try it with this image that has it flipped to true?
```
thartland/cluster-autoscaler:v1.20.0-3928-01-amd64
```

**Comment by brtknr** [comment]
Yes it works thanks, would you like to propose this change?
