### ISSUE TITLE
Does the use of cluster autoscaler require cloud provider to be specified for the whole cluster or just for the autoscaler deployment?

### ISSUE THREAD

**Issue by mattdornfeld** [kubernetes/autoscaler#393]
I don't see this anywhere in the docs. Maybe this could be made a little clearer? Thanks!

**Comment by MaciekPytel** [comment]
Not sure I understand your question @mattdornfeld. Cluster Autoscaler has a flag --cloud-provider that needs to be set for CA binary (so in CA deployment or manifest file, depending on how you run CA). You may need to set other flags for other components to get kubernetes to work in the first place, but CA only cares about its own flags.

**Comment by mwielgus** [comment]
Closing. No further comments/questions.
