### ISSUE TITLE
VPA: option to opt-out of CPU/MEM limit change

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3931]
we prefer to set our own cpu and memory limits to have a strict ceiling for each app.
with vpa recommend mode enabled to be auto mode, vpa modifies both the cpu/mem requests and limits. 

Is there a way to only let vpa modify the requests? the request values are visible in the vpa object itself but we have no eyes into the values for the limits.

due to the issue filed in https://github.com/kubernetes/autoscaler/issues/3930. i prefer a flag to disable limit modification entirely.

**Comment by bskiba** [comment]
You can use [controlledValues] (https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L165) to choose to only modify requests. However, this causes VPA to be unable to scale up your containers above the limit even if your pods need it.

Also, I responded in #3930 how we calculate limits. If the calculated value is incorrect, we'd love to fix it.
