### ISSUE TITLE
VPA EKS non stop pod restarting and failure to set requests

### ISSUE THREAD

**Issue by requiem31** [kubernetes/autoscaler#3934]
VPA version : 0.8
kubernetes: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

followed deployment docs here: https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
there are no error logs in any of the 3 components and they are running. 

looking at `kubectl describe vpa`:
```
  Recommendation:
    Container Recommendations:
      Container Name:  hamster
      Lower Bound:
        Cpu:     100m
        Memory:  131072k
      Target:
        Cpu:     587m
        Memory:  131072k
      Uncapped Target:
        Cpu:     587m
        Memory:  131072k
      Upper Bound:
        Cpu:           1
        Memory:        500Mi
      Container Name:  istio-proxy
      Lower Bound:
        Cpu:     100m
        Memory:  131072k
      Target:
        Cpu:     100m
        Memory:  131072k
      Uncapped Target:
        Cpu:     12m
        Memory:  131072k
      Upper Bound:
        Cpu:     1
        Memory:  500Mi
```

its making the correct recommendation but every ~3 minutes it keeps restarting the example hamster pod and not setting any new requests/limits. Every restart the pod gets a new name. 

Looking at grafana this is what each pods lifecycle looks like:
![image](https://user-images.githubusercontent.com/7875133/110517782-493e2480-80d9-11eb-9f9e-a19aafe6a6f1.png)
![image](https://user-images.githubusercontent.com/7875133/110517880-6bd03d80-80d9-11eb-9d6f-6d934aab6c07.png)

Ive left it running for a few hours and theres no change, VPA refuses to update resources.

**Comment by bskiba** [comment]
Have you tried following https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#vpa-restarts-my-pods-but-does-not-modify-cpu-or-memory-settings ?

Also, istio-proxy is an injected sidecar which might be problematic - if the sidecar is injected after VPA looked at the pod, there is no way VPA can modify the sidecar's requests. The mitigation there is to turn autoscaling off for only the sidecar container.

**Comment by requiem31** [comment]
hey @bskiba, AWS support has been able to replicate the problem and its an EKS issue. They have elevated the ticket and their internal teams are aware. Im closing the issue for now as I do not think theres anything that can be done from this side. Thank-you
