### ISSUE TITLE
Documentation for behavior when deployment is unhealthy

### ISSUE THREAD

**Issue by gaurav1086** [kubernetes/autoscaler#3946]
Documentation is unclear what happens if we have a deployment has "not ready" pods. Does it still delete pods ? For example I have a deployment with 3 replicas and 1 is unhealthy. Will it kill another running pod or not ?

**Comment by bskiba** [comment]
Which autoscaler are we talking about?

**Comment by gaurav1086** [comment]
@bskiba vertical pod autoscaler.
