### ISSUE TITLE
[AKS] [cluster-autoscaler] Allow vmTypeAKS for autodiscovery

### ISSUE THREAD

**Issue by VijayRod** [kubernetes/autoscaler#3948]
**Which component are you using?**: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/azure

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: I want to use autodiscovery, for an AKS cluster, as it has more flexibility for scaling.

**Describe the solution you'd like.**: Allow vmTypeAKS for autodiscovery.

**Describe any alternative solutions you've considered.**: AKS cluster-autoscaler in https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler.

**Additional context.**: Currently only vmTypeVMSS is allowed for autodiscovery. https://github.com/kubernetes/autoscaler/blob/7af23baf76d2e85573771dd1a96cef2bf5246359/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L251
```
	if m.config.VMType == vmTypeVMSS {
		return m.getFilteredScaleSets(filter)
	}

	return nil, fmt.Errorf("vmType %q does not support autodiscovery", m.config.VMType)
}
```

**Comment by marwanad** [comment]
This is by design. `vmType` AKS is also there for availability set support. If you'd like to use autodiscovery, then you should just use VMSS as the type and set up the necessary tags on the AKS-backing scale sets.


/close
