### ISSUE TITLE
Impossible to use AWS managed node groups by name tag

### ISSUE THREAD

**Issue by Fodoj** [kubernetes/autoscaler#3955]
When AWS EKS creates and ASG for managed node group, it sets a tag in a form "eks:nodegroup", with a value being the name of the node group - this tag would be perfect to use inside autoscaler, because AWS managed node groups don't allow any other kind of tags propagation. 

Unfortunately, cluster autoscaler (up till current master branch state) won't work with this tag, due to the way parsing of auto discovery flag is implemented - if there is more than one colon, it will just fail, see:

https://github.com/kubernetes/autoscaler/blob/99936f3f3971c91b30def913c1c807c42c4b87a7/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L493

This makes it impossible to use auto scaler only to scale single managed node group in EKS.

**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

latest

Component version:

1.17

**What environment is this in?**:

AWS

**What did you expect to happen?**:

**Comment by gjtempleton** [comment]
Thanks for raising this. This is definitely an issue we should handle.

/remove-lifecycle rotten
