### ISSUE TITLE
VPA : memory recommedation is lower than the usage

### ISSUE THREAD

**Issue by gaurav1086** [kubernetes/autoscaler#3961]
**Which component are you using?**:
Vertical Pod Scaler

**What version of the component are you using?**:
v0.9.2

Component version:
v0.9.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
Linux

**What did you expect to happen?**:
The memory recommendation should be above the usage.

**What happened instead?**:
The memory recommendation is lower than the usage.

**How to reproduce it (as minimally and precisely as possible)**:

The manifest contains:

```
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
```

The current usage stats:

```
$kubectl -n app-namespace describe pod my-pod-name

    Restart Count:  0
    Limits:
      cpu:     25390m
      memory:  731815514666m
    Requests:
      cpu:      2539m
      memory:   548861636

```

![Screen Shot 2021-03-19 at 5 46 37 PM](https://user-images.githubusercontent.com/1029926/111845451-19093980-88c2-11eb-8827-ebbfc672e0d9.png)

The cpu recommendation (2.54 cores) looks fine as its above the usage (dotted line), however the memory recommendation (523 MB as the dotted line) is below the current usage. How often is the memory recommendation done and how does it calculate the most optimum value ? How can we ensure that the recommendation is always above the usage ?

**Anything else we need to know?**:

**Comment by eatwithforks** [comment]
I'm also noticing this behavior. See screenshot of memory usage vs. memory target recommendation.

The **yellow** line is the memory usage of the container and the **dotted purple line** is the vpa memory target recommendation.
The recommendation is consistently lower than the usage with several spikes but coming back down for 
![Screen Shot 2021-05-11 at 12 26 52 PM](https://user-images.githubusercontent.com/4632428/117873022-315b5c00-b254-11eb-81b5-069538bda14e.png)

The yellow usage line (usage) averages between 2.5 to 3 GB.
The dotted purple line (recommendation) averages between 2 to 2.5 GB.

### Expectation

I expect the recommendation to be always higher than the usage with the exception of a usage spike. 

cc @bskiba

**Comment by bskiba** [comment]
Is the number of pods in the autoscaled collection changing over time?

**Comment by eatwithforks** [comment]
I discovered the pod in question is short-lived with a lifespan of ~4 hours (internal pod logic) before it self evicts and a new pod gets created to take its place. 

That explains the lowered memory recommendation because the frequent self-evictions registers as 0 usage and therefore brings the average memory usage calculation down.

For pods that behave in this manner, what can I tune to make sure the memory request recommendation is higher than the usage despite the frequent restarts? If not, is it possible to disable memory request auto-mode entirely?
