### ISSUE TITLE
[AKS] [cluster-autoscaler] Allow node-group-auto-discovery without hard-coded VMSS name(s)

### ISSUE THREAD

**Issue by VijayRod** [kubernetes/autoscaler#3963]
**Which component are you using?**: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/azure

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: I want to use autodiscovery, for an AKS (VirtualMachineScaleSets-based) cluster, as it has more flexibility for scaling.

**Describe the solution you'd like.**: Allow node-group-auto-discovery without hard-coded VMSS name(s). Ref: [cluster-autoscaler-vmss.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml).

**Describe any alternative solutions you've considered.**: AKS cluster-autoscaler in https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler.

**Additional context.**:

- cluster-autoscaler configured with node-group-auto-discovery parameter, and without nodes parameter, does not seem to autoscale.

```
- ./cluster-autoscaler
- --v=3
- --logtostderr=true
- --cloud-provider=azure
- --skip-nodes-with-local-storage=false
- --node-group-auto-discovery=label:cluster-autoscaler-enabled=true,cluster-autoscaler-name=testaks

I0322 07:38:00.433326       1 scale_up.go:441] No expansion options
```

- cluster-autoscaler configured with node-group-auto-discovery and nodes parameters works, however this means VMSS name is hard-coded.

```
- ./cluster-autoscaler
- --v=3
- --logtostderr=true
- --cloud-provider=azure
- --skip-nodes-with-local-storage=false
- --nodes=1:10:aks-agentpool-31772138-vmss
- --node-group-auto-discovery=label:cluster-autoscaler-enabled=true,cluster-autoscaler-name=testaks
```

- Noting this is with vmTypeVMSS indicated in https://github.com/kubernetes/autoscaler/issues/3948.

**Comment by marwanad** [comment]
did you add the appropriate tags on the VMSS?
![image](https://user-images.githubusercontent.com/7871596/112029571-a03ef300-8af6-11eb-83e5-d42165e87e00.png)

**Comment by VijayRod** [comment]
Below command in [cluster-autoscaler-vmss.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss.yaml):

```
- ./cluster-autoscaler
- --v=3
- --logtostderr=true
- --cloud-provider=azure
- --skip-nodes-with-local-storage=false
- --node-group-auto-discovery=label:cluster-autoscaler-enabled=true,cluster-autoscaler-name=testaks
```

Added below using Tags in VMSS resource menu. Now _node-group-auto-discovery scales as expected i.e. without nodes parameter_.

```
cluster-autoscaler-enabled=true cluster-autoscaler-name=testaks max=20 min=1
```
