### ISSUE TITLE
[BUG] VPA updater: index out of range durring vpa.applyPodLimitRange()

### ISSUE THREAD

**Issue by hjkatz** [kubernetes/autoscaler#3966]
**Which component are you using?**: vpa

**What version of the component are you using?**: v0.9.2

**What k8s version are you using (`kubectl version`)?**: 1.17.9

**What environment is this in?**: on-prem

**What did you expect to happen?**: No panic

**What happened instead?**:

```
I0322 16:13:35.702335       1 update_priority_calculator.go:133] not updating a short-lived pod customer-communication-hub/customer-communication-hub-5788cbbf6b-8lx8k, request within recommended range
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa.applyPodLimitRange(0xc01ba96fc0, 0x3, 0x4, 0xc01ca86040, 0x15e9123, 0x3, 0xc01fd69bc0, 0xc01fd69bf0, 0x0, 0x0, ...)
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/capping.go:397 +0x111a
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa.(*cappingRecommendationProcessor).capProportionallyToPodLimitRange(0xc022e674a0, 0xc01ba96fc0, 0x3, 0x4, 0xc01ca86040, 0x451c41, 0x2139c6b, 0xfafdd, 0xfafdd, 0xc01edd2fa0)
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/capping.go:423 +0x2ae
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa.(*cappingRecommendationProcessor).Apply(0xc022e674a0, 0xc01ee1b3e0, 0xc01ee1b3c0, 0xc01b55fd40, 0x1, 0x1, 0xc01ca86040, 0xc01fd44e80, 0xc01fd690b0, 0x0, ...)
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/capping.go:71 +0xa2
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/priority.(*UpdatePriorityCalculator).AddPod(0xc01edd3610, 0xc01ca86040, 0xc00e4e6be9dcf98f, 0x111c9dfae4, 0x22b4340)
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go:86 +0x98
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic.(*updater).getPodsUpdateOrder(0xc01780e3c0, 0xc005ce76b0, 0x2, 0x2, 0xc01ee28f20, 0xc005ce76b0, 0x2, 0x2)
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:257 +0x192
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic.(*updater).RunOnce(0xc01780e3c0, 0x182c200, 0xc01c22dce0)
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:200 +0x10aa
main.main()
        /gopath/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/main.go:120 +0x785
```

**How to reproduce it (as minimally and precisely as possible)**: unclear, I'll begin looking into it

**Comment by hjkatz** [comment]
Line of code where the panic occurs: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L397

**Comment by bskiba** [comment]
/assign @jbartosik 
Joachim, can you take a look?

**Comment by hjkatz** [comment]
It feels like a case of the recommendations have X number of containers and the admitted Pod having Y number of containers, therefore there's a mismatch between containers. I think a safe approach would be either double looping through by `Pod.spec.containers` _and_ `resources` at the same time while comparing container names, or some other method to ensure the containers match.

We use a sidecar injector pattern and I'm thinking that maybe some injection is not happening on Pod admission time, therefore we have this mismatch between the currently running Pod (and its containers' recommendations) vs. the new Pod being admitted (if injection wasn't quite working properly yet, or something). I'm digging around for which Namespace and Pod is causing this panic, but I'm not having much luck.

**Comment by umialpha** [comment]
Hi @hjkatz, could you show the pod spec into in detail? e.g, `kubectl get pod XXX -o yaml`

**Comment by hjkatz** [comment]
@umialpha Which Pod spec are you interested in? We were unable to determine precisely which Pod or workload was causing the `vpa-updater` to crash (we have some ~4000 Pods in our cluster). I turned up the debugging level to `--v=10` sometime last week, but since then we haven't seen the `vpa-updater` Pod crash again... so we haven't gotten any new information. Perhaps you would have ideas about what state a Pod that would cause the crash would be in so that we could maybe do some `kubectl` fu to find or create an example Pod?

**Comment by jbartosik** [comment]
/remove-lifecycle rotten
I didn't have bandwidth to look into this but I think it would be good to do that

**Comment by jbartosik** [comment]
/remove-lifecycle stale

I took a look I think that @hjkatz was right in [this comment](https://github.com/kubernetes/autoscaler/issues/3966#issuecomment-804209585) the function should use [`getContainer`](https://github.com/kubernetes/autoscaler/blob/ca6ed150671afa0eadb78510ae740d8b93a5b1de/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L271) function instead of relying on indexes matching (also [a bit above](https://github.com/kubernetes/autoscaler/blob/ca6ed150671afa0eadb78510ae740d8b93a5b1de/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L355)).

**Comment by jbartosik** [comment]
I'm working on a PR to fix this. It'll take some more time:

- I want to add some more (unit) tests
- [this line](https://github.com/kubernetes/autoscaler/blob/ca6ed150671afa0eadb78510ae740d8b93a5b1de/vertical-pod-autoscaler/pkg/utils/vpa/capping.go#L397) looks weird to me; we're taking value of recommendation (and we're recommending requests not limits) and then using it as a limit

**Comment by jbartosik** [comment]
There's [a test](https://github.com/kubernetes/autoscaler/blob/538c055e083dc24e6cebaf1698faa8918ef1e2e8/vertical-pod-autoscaler/pkg/admission-controller/resource/pod/recommendation/recommendation_provider_test.go#L174) that expects no error when there is no matching recommendation for a container; I'll check why is that and if I can fix the way I intended to

**Comment by jbartosik** [comment]
For now I sent PR with e2e that reproduce the problem and which I plan to use later to make sure my fix fixes the problem and doesn't break things.
