### ISSUE TITLE
PollingAutoscaler leaking memory and goroutines?

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#400]
In AWS cloudprovider newAutoScalingGroups is creating a goroutine for regenerating ASG cache, which is never stopped. After cursory glance at PollingAutoscaler and surrounding code it looks as if a new such goroutine is created in every loop (as part of creating AWS cloudprovider). If that's the case we're probably leaking a goroutine + autoScalingGroups data structure every loop. 
@mumoshu am I missing something?

**Comment by bismarck** [comment]
This is the same thing I am seeing in #252

**Comment by MaciekPytel** [comment]
You're right @bismarck. I'll close this issue as it duplicates #252.
