### ISSUE TITLE
Provide observability for unregistered nodes

### ISSUE THREAD

**Issue by dharmab** [kubernetes/autoscaler#4001]
**Which component are you using?**:

Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

The metric `cluster_autoscaler_nodes_count` can be used to track if VMs created by the Cluster Autoscaler are not joining the clusters as Nodes in a timely manner. However, the metric and logs only report the number of unregistered nodes. In a large cluster with many ASGs/scale sets, it is difficult to find the specific VMs which are not joining the cluster.

**Describe the solution you'd like.**:

The cluster autoscaler should provide a way to determine which VMs are not registered. This could be a log containing the VM names, or a metric with a label for each Node and its state.

**Describe any alternative solutions you've considered.**:

We could write a script that uses the cloud provider API and compares the VMs in the cloud provider to those in Kubernetes. This would have to be different for each cloud provider, and it seems that CA has all the necessary access and information to do this anyway.

**Additional context.**:

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/metrics.md#cluster-autoscaler-operations

**Comment by gjtempleton** [comment]
Hey, thanks for raising this as a feature request!

I'd be worried about adding metrics with node names/identities as labels given the potential for high cardinality in large clusters. To me using logs seems like the sensible way to go instead to provide this functionality.

You're welcome to raise a PR adding this functionality if you want to.
