### ISSUE TITLE
Observed that node.kubernetes.io/instance-type is not respected while scaling from 0

### ISSUE THREAD

**Issue by chaitushiva** [kubernetes/autoscaler#4002]
**Which component are you using?**: v1.19.1 on EKS 1.19.1

cluster-autoscaler
**What version of the component are you using?**: v1.19.1

Component version: v1.19.1

**What k8s version are you using (`kubectl version`)?**: N/A

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: Production

**What did you expect to happen?**:

Cluster autoscaler should look for pending pods which have nodeSelector  node.kubernetes.io/instance-type and scale the respective node group from 0 to the desired number 

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by chaitushiva** [comment]
Also though the scaling triggered by updating the nodeselector to beta.kubernetes.io/instance-type: r4.8xlarge, we still see the below message from the CA 

Pod busybox-deployment-6dfd578f5d-mkg7b can't be scheduled on xxxxxxxxxxxxxx-r4.8xlarge-verified-insect20210408043840503400000008, predicate checking error: node(s) didn't match node selector; predicateName=NodeAffinity; reasons: node(s) didn't match node selector; debugInfo=

**Comment by chaitushiva** [comment]
Please find the fix [https://github.com/kubernetes/autoscaler/pull/3977/files](url) .

Yet to be tested

**Comment by alexmnyc** [comment]
I have a similar problem where I manually label my ASG's nodes with "instance-type: m5.large" and when scheduling pods with nodeSelector: instance-type: m5.large" i get that message "node(s) didn't match node selector"
