### ISSUE TITLE
Cloudprovider Hetzner firewall feature

### ISSUE THREAD

**Issue by gris-gris** [kubernetes/autoscaler#4008]
**Which component are you using?**: 

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: 

cluster-autoscaler for Hetzner currently doesn't provide firewall support for node-pools. 

**Describe the solution you'd like.**: 

cluster-autoscaler for Hetzner cloudprovider should have environment variable with Firewall ID, that will be applied to hosts running within node-pool

**Comment by sergeyshevch** [comment]
I also interested in this feature. Maybe i will try to work on it later

**Comment by sergeyshevch** [comment]
Sorry for delay. I will work on it on this week

**Comment by marvinpinto** [comment]
I believe it might already be possible to do what you need. When you supply a nodegroup argument such as `--nodes=1:10:CPX11:FSN1:my-node-group-1`, the autoscaler attaches a label like `hcloud/node-group=my-node-group-1` to each server it brings up. You can use this as a label selector to automatically assign these nodes to the firewall (see applying resources by labels).

**Comment by sergeyshevch** [comment]
Yeah. This is anothernoption how to do it. But i guees it will be better if we can specify firewall ID on cluster autoscaler.

I also guees that we need a way how to define taints that will be used by nodegroup on This level

**Comment by sergeyshevch** [comment]
I added PR that will add support for hcloud firewall
