### ISSUE TITLE
How to use this library in python

### ISSUE THREAD

**Issue by ivishalvarshney** [kubernetes/autoscaler#4013]
Hello Team,
Please let us know the way to use this library in python, so that we can integrate it in our project.
Like we have [kubernetes-client](https://github.com/kubernetes-client/python/tree/master/kubernetes) library, which provide many functions or REST API's to use kubernetes capabilities in our applications.

**Comment by saeid93** [comment]
Hi, I'm having the same problem, were you able to figure out a way?
