### ISSUE TITLE
Autoscaler removes nodes not marked for deletion

### ISSUE THREAD

**Issue by AndyMender** [kubernetes/autoscaler#4021]
**Which component are you using?**: 
The Cluster Autoscaler image `k8s.gcr.io/autoscaling/cluster-autoscaler:v1.17.3` in a AWS Kubernetes cluster (EKS) with 2 node groups:
- a maintenance group with regular CPU nodes (instance type: `t3.small`)
- a workload group with GPU nodes (instance type: `p3.2xlarge`), scalable to/from 0 nodes

The Autoscaler deployment is the same as provided in this repository with slight modifications to target Autoscaling Groups in our AWS setup: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml

**What version of the component are you using?**:
v1.17.3

Component version: v1.17.3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS Linux 2 or similar on all nodes (Kubernetes master node is provided by AWS)

**What did you expect to happen?**:
The Autoscaler scaling down / removing only nodes which are no longer in use (not running any jobs/workloads).

**What happened instead?**:
The Autoscaler selected a node which had a running job, even though it deemed it not suitable for removal.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the setup from this article: https://itnext.io/eks-gpu-cluster-from-zero-to-hero-8df92cf720a5

**Anything else we need to know?**:
Here are the logs which show how the Autoscaler selected a node which was actually in use:
```shell
I0420 14:01:18.290641       1 utils.go:328] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0420 14:01:18.290652       1 filter_out_schedulable.go:66] Filtering out schedulables
I0420 14:01:18.290765       1 filter_out_schedulable.go:131] 0 other pods marked as unschedulable can be scheduled.
I0420 14:01:18.290851       1 filter_out_schedulable.go:131] 0 other pods marked as unschedulable can be scheduled.
I0420 14:01:18.290864       1 filter_out_schedulable.go:91] No schedulable pods
I0420 14:01:18.290883       1 static_autoscaler.go:343] No unschedulable pods
I0420 14:01:18.290898       1 static_autoscaler.go:390] Calculating unneeded nodes
I0420 14:01:18.290935       1 pre_filtering_processor.go:66] Skipping ip-1.ec2.internal - node group min size reached
I0420 14:01:18.291062       1 scale_down.go:462] Node ip-2.ec2.internal - nvidia.com/gpu utilization 1.000000
I0420 14:01:18.291080       1 scale_down.go:466] Node ip-2.ec2.internal is not suitable for removal - nvidia.com/gpu utilization too big (1.000000)
I0420 14:01:18.291090       1 scale_down.go:462] Node ip-3.ec2.internal - nvidia.com/gpu utilization 1.000000
I0420 14:01:18.291096       1 scale_down.go:466] Node ip-3.ec2.internal is not suitable for removal - nvidia.com/gpu utilization too big (1.000000)
I0420 14:01:18.291104       1 scale_down.go:462] Node ip-4.ec2.internal - nvidia.com/gpu utilization 1.000000
I0420 14:01:18.291110       1 scale_down.go:466] Node ip-4.ec2.internal is not suitable for removal - nvidia.com/gpu utilization too big (1.000000)
I0420 14:01:18.291121       1 scale_down.go:462] Node ip-5.ec2.internal - nvidia.com/gpu utilization 0.000000
I0420 14:01:18.291130       1 scale_down.go:462] Node ip-6.ec2.internal - nvidia.com/gpu utilization 0.000000
I0420 14:01:18.291138       1 scale_down.go:462] Node ip-7.ec2.internal - nvidia.com/gpu utilization 1.000000
I0420 14:01:18.291145       1 scale_down.go:466] Node ip-7.ec2.internal is not suitable for removal - nvidia.com/gpu utilization too big (1.000000)
I0420 14:01:18.291344       1 static_autoscaler.go:428] ip-5.ec2.internal is unneeded since 2021-04-20 13:59:57.498695498 +0000 UTC m=+2758875.282322671 duration 1m20.750872972s
I0420 14:01:18.291365       1 static_autoscaler.go:428] ip-6.ec2.internal is unneeded since 2021-04-20 13:59:57.498695498 +0000 UTC m=+2758875.282322671 duration 1m20.750872972s
I0420 14:01:18.291378       1 static_autoscaler.go:439] Scale down status: unneededOnly=false lastScaleUpTime=2021-04-20 09:23:25.039746722 +0000 UTC m=+2742282.823373910 lastScaleDownDeleteTime=2021-03-19 15:39:18.257392899 +0000 UTC m=+36.041020052 lastScaleDownFailTime=2021-03-19 15:39:18.257392987 +0000 UTC m=+36.041020136 scaleDownForbidden=false isDeleteInProgress=false scaleDownInCooldown=false
I0420 14:01:18.291398       1 static_autoscaler.go:452] Starting scale down
I0420 14:01:18.291440       1 scale_down.go:716] ip-5.ec2.internal was unneeded for 1m20.750872972s
I0420 14:01:18.291449       1 scale_down.go:716] ip-6.ec2.internal was unneeded for 1m20.750872972s
I0420 14:01:18.291461       1 scale_down.go:776] No candidates for scale down
I0420 14:01:22.335722       1 node_tree.go:100] Removed node "ip-6.ec2.internal" in group "us-east-1:\x00:us-east-1f" from NodeTree
I0420 14:01:22.451805       1 node_tree.go:100] Removed node "ip-3.ec2.internal" in group "us-east-1:\x00:us-east-1f" from NodeTree
I0420 14:01:22.665814       1 node_tree.go:100] Removed node "ip-5.ec2.internal" in group "us-east-1:\x00:us-east-1f" from NodeTree
```

Node `ip-3.ec2.internal` had a job running on it and the Autoscaler reports this correctly, however it still decided to remove the node. The other 2 nodes had their jobs removed and are correctly reported as unneeded for a certain duration, however they also should not have been removed, because the unneeded timeout of 10 min was not exceeded.

**Comment by AndyMender** [comment]
Just a quick update on this - it looks like we were not using the `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` annotation in our `Job`/`Pod` definitions, as recommended here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

I will close the ticket accordingly if the solution works.

**Comment by supereagle** [comment]
@AndyMender Does "cluster-autoscaler.kubernetes.io/safe-to-evict": "false" annotation work?
