### ISSUE TITLE
Ungraceful node shutdown during scale in

### ISSUE THREAD

**Issue by lrouquette** [kubernetes/autoscaler#4029]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
1.20.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:13:35Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS & Azure

**What did you expect to happen?**:
During node scale-in, I expect "regular" pods to be evicted first, and "critical" pods to be terminated last. The definition of regular vs. critical is the same as the one used in this recent [blog](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/#how-does-it-work).

**What happened instead?**:
We have logging-related pods that are removed immediately, resulting in lost logs. In certain cases, we have seen that pods providing networking (Cilium, Calico etc.) are terminated earlier than the workload pods, resulting in various network problems.

**How to reproduce it (as minimally and precisely as possible)**:
Simply observe pods removal during a node scale down.

**Anything else we need to know?**:
Not that I can think of

**Comment by dharmab** [comment]
Other examples:

- kube2iam/AAD Pod Identity Pods being terminating early resulting in application Pods on that Node losing their ability to authenticate to public cloud APIs 
- node local DNS pods being terminated, interrupting DNS requests in flight from application pods

**Comment by lrouquette** [comment]
/remove-lifecycle rotten

We addressed this issue by removing non-daemonset pods first and then the rest; it's been working pretty well for us, so I'll look at filing a PR shortly.
