### ISSUE TITLE
Pathological behavior when scaling down makes sets of `Job`s take much longer than they should to run, with lots of restarting

### ISSUE THREAD

**Issue by adamnovak** [kubernetes/autoscaler#4048]
**Which component are you using?**:

Cluster Autoscaler

**What version of the component are you using?**:

Component version: 1.19.0

**What k8s version are you using (`kubectl version`)?**:

This is in a whole class of automatically provisioned clusters, all of which are currently de-provisioned, but I install Kubernetes v1.19.3.

**What environment is this in?**:

AWS, but not EKS

**What did you expect to happen?**:

I gave my cluster a large number of Kubernetes `Job` objects, each describing a task that takes a long time (several hours) to run. Some would take longer to run than others, and no new work or other pods would be generated until the original batch of `Job`s completed.

I didn't use the `Job` controller's internal restart mechanism, but if a `Job` failed (for example due to its pod being evicted) it would be deleted and recreated by my application.

I expected the autoscaler to scale up enough nodes to run the `Job`s, let them run, and scale down nodes when they were no longer needed.

**What happened instead?**:

The autoscaler scaled up the cluster fine, but exhibited pathological behavior when scaling down. As jobs finish, node utilization drops. When the autoscaler sees a node at low utilization, and another node that could take the pods, it will scale away the low-utilization node and move the pods, even if those pods are `Job` pods embodying the state of a computation that would take several wall clock hours to reconstruct. Then, having packed the work onto fewer nodes (and forcing a lot of jobs to restart in the process), when jobs finally get to finishing again and *those* nodes become underutilized, the process repeats again.

If I run *n* jobs that take *k* time each, and my maximum cluster size is sufficiently large, I expect all the jobs to finish in *O(k)* time. With this behavior, it actually takes more like *O(k log(n))* time, because every time half my jobs finish, the other half have to restart.

**How to reproduce it (as minimally and precisely as possible)**:

Make ~50 of `Job` objects that sleep for random numbers of thousands of seconds (with `Job`-managed restart), throw them at the autoscaler (allowing it to make enough nodes, fitting ~10 jobs each, to run the jobs all at once), and time how long the cluster takes to clear the queue. It will be a lot longer than the longest job takes to run, because nodes will be scaled away and force the longer-running half of their jobs to restart.

When I encountered this problem I was running [this script](https://github.com/vgteam/giraffe-sv-paper/blob/572bd0100d33d2e7f9bef51d286fa578d733d7b8/scripts/indexing/09_make_1000GPlons_GRCh38_graph.sh), but that needs a bunch of input files from our lab's private S3 buckets. We can share them if someone really wants to rerun the whole workflow.

**Anything else we need to know?**:

There is the `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` tag that can be applied to pods, and similarly the utilization threshold for scaling away nodes can be reduced from its default of 50% to something less than the size of one of my jobs. However, I suspect that changing these will produce bad behavior in the case of a continuous stream of jobs. If the cluster scales up, but then the rate of job submission decreases, I think the scheduler will keep spraying jobs evenly across all the nodes. All the nodes will be about equally under-utilized, but the cluster autoscaler won't be able to get rid of any of them because it won't be willing to terminate a job.

Our lab's previous Mesos-based solution included some sophisticated logic for identifying that the cluster as a whole is under-utilized, picking a node to get rid of, and then blocking further jobs from landing on that node while waiting for its existing jobs to finish. I'm looking for a way to get similar behavior from the Kubernetes cluster autoscaler. It would be ideal if the result sensibly handled mixed workloads of `Job`s and more traditional service-providing pods (that can be safely rescheduled).

Could I achieve something like our old Mesos system with a very long `max-graceful-termination-sec`? Will the autoscaler behave well if `max-graceful-termination-sec` is on the order of days? Or will it e.g. pick a node to scale down, wait for all of its jobs to finish, and only then realize that 3 other nodes are now empty and waiting to be deleted?

**Comment by MaciekPytel** [comment]
>  Or will it e.g. pick a node to scale down, wait for all of its jobs to finish, and only then realize that 3 other nodes are now empty and waiting to be deleted?

That. Once autoscaler starts to drain node it will not delete any other nodes until it is done, so long max-graceful-termination-sec is very much not recommended.

My recommendation for your case would be to switch scheduler from NodeResourcesLeastAllocated to NodeResourcesMostAllocated. That way scheduler will aim to schedule new pods on nodes that are already highly utilized and not spread them around.
Combine this with PDB or safe-to-evict:false if you want no restarts at all or lower utilization threshold if you want autoscaler to restart jobs if the nodes are very lowly utilized.

For something more fancy you can try to play with long scale-down-unneeded-time - CA will soft taint nodes it sees as potential deletion candidates, which should prevent scheduler from adding new pods to those nodes and the long scale-down delay can give your jobs chance to finish.

**Comment by adamnovak** [comment]
It looks like `NodeResourcesMostAllocated` and `safe-to-evict:false` were the right way to explain to Kubernetes that scaling down the nodes as soon as a large fraction of their jobs finish is a Bad Idea. When I adopted those the problem went away.

I would still suggest changing the defaults, but I suspect that's unlikely to happen.
