### ISSUE TITLE
What's the chart version for cluster-autoscaler-1.19.1 ?

### ISSUE THREAD

**Issue by cebidhem** [kubernetes/autoscaler#4054]
Hi community,

So far we are using forked chart from yours, and we would like to use upstream directly for consistency across our platform.
Our clusters are running EKS 1.19, so we are running `cluster-autoscaler-1.19.1`.

Now I was looking at the chart, and I found that there is no chart meant specifically for 1.19.1. Indeed, `cluster-autoscaler-chart-9.4.0` has `appVersion: 1.18.1` (https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-chart-9.4.0/charts/cluster-autoscaler/Chart.yaml#L2) 

and `cluster-autoscaler-chart-9.5.0` has `appVersion: 1.20.0`
(https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-chart-9.5.0/charts/cluster-autoscaler/Chart.yaml#L2)

Could one let us know which one we should use ? Even if it's only about overriding the `image.tag` in `cluster-autoscaler-chart-9.5.0` for example.

Thanks for your support!

**Comment by Unichron** [comment]
Would be also nice if the compatibility between the chart and the app versions were mentioned somewhere in the docs (even if it is trivial like 'all chart versions can be used with any autoscaler version', although I doubt it's that simple).

**Comment by draeath** [comment]
Hi there. I'm setting up some infrastructure myself and ran into this same ambiguity (re: kubernetes 1.21) where the appVersion in Chart.yaml is a version behind the version number placed into the release tag's name.

**Comment by BeyondEvil** [comment]
I'm also interested in this. Should be an easy and quick answer from contributors.

**Comment by keifgwinn** [comment]
I'm also in need of being able to identify the matching pair of chart to kubernetes version, a simple table somewhere would be helpful
