### ISSUE TITLE
VPA Updator not evicting pods

### ISSUE THREAD

**Issue by rmb938** [kubernetes/autoscaler#4057]
**Which component are you using?**: vertical-pod-autoscaler,

**What version of the component are you using?**: v0.9.2

Component version: v0.9.2

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: On-Prem K8s cluster dpelyoed via kubeadm

**What did you expect to happen?**:

The updater is not evicting pods when they need their memory resources updated.

**What happened instead?**:

It logs this

```
Admission Controller status has been refreshed more than 1m0s ago. Skipping eviction loop
```

**How to reproduce it (as minimally and precisely as possible)**:

Deploy VPA 0.9.2.

I think there is a bug in this part of the code https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/vertical-pod-autoscaler/pkg/utils/status/status_object.go#L137

It seems this code is looking for the lease to not expire exactly 1 minute from the time the code is ran. What I've see is the controller for example renews at 07:05:00, then that code block runs at 07:05:05 which is a few seconds later after the lease happened to be renewed. So when the 1 minute check happens, it thinks it'll be expired because it's checking at exactly that 1 minute but a few seconds have past already.

The lease expiration check should probably be more forgiving because the lease renew loop in the controller may not be perfectly in-sync with the updater so the updater does not think the lease will expire when it won't.

**Comment by krzysied** [comment]
Sure. I will take a look.

**Comment by krzysied** [comment]
> Admission Controller status has been refreshed more than 1m0s ago. Skipping eviction loop

It means that there is a problem with admission controller not updating the status

> The lease expiration check should probably be more forgiving because the lease renew loop in the controller may not be perfectly in-sync with the updater so the updater does not think the lease will expire when it won't.

Updater checks is if status was updated during last minute. Admission controller should be updating status every 10s. It means that Admission controller has 5-6 attempts of updating status before it is considered not valid.

**Comment by krzysied** [comment]
@rmb938 You can look at the admission controller logs. There should be logs like `Status update by %s failed` if the status updates are failing.

**Comment by rmb938** [comment]
@krzysied There are no such logs. Watching the lease object does show it is getting updated every 10 seconds correctly. However the causes a race I explained in the main issue because if when the updater checks it just so happens to be within that 1 minute period the updater thinks the lease will expire when it isn't.

**Comment by krzysied** [comment]
@rmb938  I still don't understand the explanation regarding the race. Could you explain it by describing a specific case?

IIUC you are saying that lease is updated correctly (it is expected to be at most 10s old then). Based on that [the status check](https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/vertical-pod-autoscaler/pkg/utils/status/status_object.go#L156) should be satisfied - the difference between lease renew time and present time should be ~10s which << 60s.
Moreover, updater [retrieves the current status versions](https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/vertical-pod-autoscaler/pkg/utils/status/status_object.go#L149). There is  no informer, watch or anything that can create a lag.

IMHO it will be worth looking at the history of get lease calls in apiserver logs. Maybe they are taking too long?
