### ISSUE TITLE
EKS Cluster Autoscaler  - WebIdentityErr: failed to retrieve credentials - caused by: InvalidIdentityToken: Incorrect token audience

### ISSUE THREAD

**Issue by myvelmurugan** [kubernetes/autoscaler#4074]
i installed eks through terraform and enabled the OIDC connector as per the document https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

I have gone throught the steps in the cluster-autoscaler and added the proper role and mapped the service account to the aws role. 
ASG group has proper tagging.

Getting the below error from the cluster-autoscaler pod and not sure what I am doing wrong.

E0512 07:27:20.361028       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: Incorrect token audience
        status code: 400, request id: 2b8d1095-29f8-4641-aa68-579630a3062e
F0512 07:27:20.361054       1 aws_cloud_provider.go:382] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: Incorrect token audience

**Comment by hypnoce** [comment]
I have the same experience. I've done all the steps on the management console.

**Comment by cabrinha** [comment]
I was affected by this same issue until I looked closely at the OIDC provider for the EKS cluster.

Running in cn-north-1, OIDC provider Audience is set to `sts.amazonaws.com.cn`, you need to manually add `sts.amazonaws.com` to the audience list.

**Comment by ekamdz** [comment]
@hypnoce @cabrinha , any update on this ? I am facing the same. 
My OIDC provider Audience is set to **sts.amazonaws.com**

**Comment by hypnoce** [comment]
@ekamdz yes we had a typo in the audience name `amzonaws.com` instead of `amazonaws.com`. Maybe you have another issue in your config.
