### ISSUE TITLE
gobizflycloud go.mod breaks go mod vendor

### ISSUE THREAD

**Issue by avorima** [kubernetes/autoscaler#4076]
The bizflycloud provider (#4009) introduced an SDK with a `go.mod` that's not vendored which causes failures.

```
$ cd cluster-autoscaler
$ go mod vendor
go: finding module for package k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud/gobizfly
go: found k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud/gobizfly in k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud/gobizfly v0.0.0-20210511160736-2e6ccacee698
go: k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud imports
        k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud/gobizfly: k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud/gobizfly@v0.0.0-20210511160736-2e6ccacee698: parsing go.mod:
        module declares its path as: github.com/bizflycloud/gobizfly
                but was required as: k8s.io/autoscaler/cluster-autoscaler/cloudprovider/bizflycloud/gobizfly
```

My current local solution is to remove the `go.mod` that's causing problems.

I couldn't find the OWNERS of said cloudprovider, but pinging @lmq1999 since they contributed the code.

**Comment by towca** [comment]
Thanks for catching this, I was just going to create the same issue. It's also preventing us from updating vendor in the repository. I'm going to delete the `go.mod` file for now. @lmq1999 - I think ultimately leaving just the go source files makes the most sense, but I'll leave it up to you.

**Comment by avorima** [comment]
@towca Thanks!
