### ISSUE TITLE
CA 1.0 - Unable to scale p2.xlarge or p2.8xlarge from 0

### ISSUE THREAD

**Issue by chhibber** [kubernetes/autoscaler#408]
Running into the exact same issue documented here: https://github.com/kubernetes/autoscaler/issues/346

The AWS json file being pulled down still has missing data regarding GPUs.  The p2.16xlarge has the GPU enumerated and scales up, the rest do not.   

Logs...
```
I1013 22:10:11.784396       1 scale_up.go:140] Scale-up predicate failed: PodFitsResources predicate mismatch, cannot put default/tf-deployment-84fffcbdc-vnkl2 on template-node-for-gpunodes.gpu.sono-k8.xxxxx-2740376916591569721, reason: Insufficient alpha.kubernetes.io/nvidia-gpu
I1013 22:10:11.784519       1 scale_up.go:140] Scale-up predicate failed: PodFitsResources predicate mismatch, cannot put default/tf-deployment-6d6fd6cd-k77r5 on template-node-for-gpunodes.gpu.sono-k8.xxxxx-2740376916591569721, reason: Insufficient alpha.kubernetes.io/nvidia-gpu
I1013 22:10:11.784553       1 scale_up.go:140] Scale-up predicate failed: PodFitsResources predicate mismatch, cannot put default/tf-deployment-6d6fd6cd-nnhjr on template-node-for-gpunodes.gpu.sono-k8.xxxxx-2740376916591569721, reason: Insufficient alpha.kubernetes.io/nvidia-gpu
```

I applied the the fix described in issue 346,  though I added info explicitly for all p2 instance types as I am not sure if this a general inconsistency with the AWS json file.   After the fix I was able to scale P2 instances up from 0.

Diff:

```
diff --git a/cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go b/cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
index 6f8b347e..4537037c 100644
--- a/cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
+++ b/cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go
@@ -144,6 +144,15 @@ func main() {
 					if attr.GPU != "" {
 						instanceTypes[attr.InstanceType].GPU = parseCPU(attr.GPU)
 					}
+					if attr.InstanceType == "p2.xlarge" {
+						instanceTypes[attr.InstanceType].GPU = 1
+					}
+					if attr.InstanceType == "p2.8xlarge" {
+						instanceTypes[attr.InstanceType].GPU = 8
+					}
+					if attr.InstanceType == "p2.16xlarge" {
+						instanceTypes[attr.InstanceType].GPU = 16
+					}
 				}
 			}
 		}
```

It might be worth leveraging something like http://www.ec2instances.info/ in the interim? As I understand it internal teams in AWS leverage the site even. 

I have a build that I put up and tested here:

- https://hub.docker.com/r/chhibber/cluster-scaler/
- or docker pull chhibber/cluster-scaler

**Comment by chhibber** [comment]
I can submit a PR if you are ok to pin these values for the moment?

**Comment by 7chenko** [comment]
Confirmed that AWS has now fixed the gpu data for p2.xxx:

https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-west-2/index.json

**Comment by mwielgus** [comment]
Fixed in https://github.com/kubernetes/autoscaler/pull/439
