### ISSUE TITLE
Does Autoscaler supports OKE (Oracle Kubernetes Engine)?

### ISSUE THREAD

**Issue by vickyvikas7988** [kubernetes/autoscaler#4080]
Hi team,

Does autoscaler support Oracle Kubernetes Engine (OKE) Oracle Cloud?

If yes, thanks a lot.

If no, can you please let us no ETA?

**Comment by towca** [comment]
Hi! I'm assuming you mean Cluster Autoscaler. You can find the supported cloud providers [here](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider) (keep in mind that the level of support varies). The core Cluster Autoscaler team is only maintaining the GCE provider and there are no plans to change that (though we welcome community contributions for other providers of course!).

Closing the issue, feel free to reopen if you have any more questions.
