### ISSUE TITLE
Emit logs for nodegroup size/instance count in the autoscaler cache and in the cloud provider after each cache refresh or scale up/down operations

### ISSUE THREAD

**Issue by ankurchoubeymsft** [kubernetes/autoscaler#4096]
**Which component are you using?**: Cluster Autoscaler 1.20.0

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Recently we had an outage in our production environment. Cluster autoscaler scaled down a VMSS size to a very small number - ~350 -> 30 with nodegroup min set as 10.  This deleted almost all nodes in that VMSS. All these nodes were in running state and were part of the cluster hosting actively running pods. From the cluster autoscaler logs it is not evident as to how it reached that number. The cluster autoscaler only logs lines like 
 - ```Final scale-up plan: [{nodegroup X->Y (max: 1000)}] ``` 
 - ```Node A was unneeded for``` -> ```Deleting vmss instances .. A ...``` -> ```Calling virtualMachineScaleSetsClient.DeleteInstancesAsync ... A ...``` 
 - ```Refreshed Azure VM and VMSS list, next refresh after ...```

There were some delete timeouts and throttling errors in between these delete, refresh and scaleup calls. With this information, it is still unclear how the autoscaler's cache for nodegroup size changes and how/why it ended up with such a low number. Counting the number of delete instances call in the logs does not add up to the above change in vmss size. 

**Describe the solution you'd like.**:
The logs should print the nodegroup size as seen in the cache and in the cloud provider after each cache refresh operation, and preferably scale-down operations. 
Something like 
 - ```virtualMachineScaleSetsClient.DeleteInstancesAsync ... A ... [{nodegroup-name, number of nodes in cache: X, number of nodes in cloud provider: Y}]```
 - ```Refreshed Azure VM and VMSS list, next refresh after .... [{nodegroup-name, number of nodes in cache: X, number of nodes in cloud provider: Y}]```
With these logs, we can see how the values change and how it ended up in such a low number.

**Describe any alternative solutions you've considered.**:
Emitting these numbers as metrics will also help.

**Additional context.**:
The cluster is hosted on azure vmscaleset. Nodegroup min size was set to 10. The current version includes the fixes in PR #3242 and PR #3036 

/area provider/azure

**Comment by marwanad** [comment]
Yeah we could log the number of nodes, before each operation. I suspect you might be hit by https://github.com/kubernetes-sigs/cloud-provider-azure/issues/635 though. 

Did you see a log line indicating `Final scale-up plan: [{nodegroup 350->30 (max: 1000)}]`? In other words, did CA trigger a `PUT` to downscale you? If not, then I'd suspect it's that cloudprovider bug above.
