### ISSUE TITLE
vertical-pod-autoscaler@v0.9.2 release is marked as `pre-release`

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/autoscaler#4100]
**Which component are you using?**:
vertical-pod-autoscaler

**What did you expect to happen?**:

Currently the vertical-pod-autoscaler/README.md states the following:

> The current default version is Vertical Pod Autoscaler 0.9.2

When I go to the corresponding release page, I see that vertical-pod-autoscaler@v0.9.2 release is marked as `pre-release` which means that the release is non-production ready. See https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.9.2

So which information is the true one - is 0.9.2 production ready or not?

**What happened instead?**:

If vertical-pod-autoscaler@v0.9.2 is production ready, the corresponding github release should not be marked as pre-release.

**Comment by ialidzhikov** [comment]
@bskiba, is the v0.9.2 release production ready?

**Comment by bskiba** [comment]
Recommendation generation and API are GA quality.
Updater and Admission Controller (automatic application of recommendations) is Beta quality.

So this is kind of blocking us from marking the entire release as GA.

**Comment by ialidzhikov** [comment]
I noticed that `vertical-pod-autoscaler@v0.9.0` is marked as pre-release as well - ref https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.9.0. So I assume we can update from 0.9.0 to 0.9.2 right?

> Recommendation generation and API are GA quality.
> Updater and Admission Controller (automatic application of recommendations) is Beta quality.
> 
> So this is kind of blocking us from marking the entire release as GA.

So these statements apply not particularly for 0.9.2 but for all vertical-pod-autoscaler versions, right?

**Comment by bskiba** [comment]
Yes, you're correct.

**Comment by ialidzhikov** [comment]
> Yes, you're correct.

Ok, thanks for clarifying. I will then close this issue.

/close
