### ISSUE TITLE
Autoscaler fails to scale up nodes with pending pods

### ISSUE THREAD

**Issue by mimmus** [kubernetes/autoscaler#4128]
**Which component are you using?**:
We are running D2iq Konvoy cluster with Kubernetes 1.19.8 and its 'integrated' cluster-autoscaler addon.

**What version of the component are you using?**:

<pre>
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
auto-provisioning       konvoy          63              2021-06-08 17:24:30.2755892 +0000 UTC   deployed        auto-provisioning-v1.7.1        v1.7.1
konvoy-v1-6-0           konvoy          62              2021-06-09 09:31:32.636612559 +0000 UTC deployed        cluster-autoscaler-7.2.2        1.17.1
</pre>

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS

**What did you expect to happen?**:
We scaled a test Deployment from 1 to 40, cluster-autoscaler creates a new node and Kubernetes is able to accomodate 39/40 pods.
Cluster should scale up with a further node because there is still a pod pending.

**What happened instead?**:
Cluster doesn't scale up furtherly and pod remains unscheduled.

**How to reproduce it (as minimally and precisely as possible)**:
Not simple.

**Anything else we need to know?**:
Log message is clear:
`Pod stampino-6696595bcf-l2xgv marked as unschedulable can be scheduled on existing node ip-1-2-3-4.eu-south-1.compute.internal. Ignoring in scale up.`
but root cause no.

Restarting CA doesn't solve the issue.
Cordoning/draining the indicated node is a workaround.
Scaling furtherly the Deployment (to 41, 42....) triggers a new node provisiong.

I suspect:
- there is inconsistency in what CA thinks and what scheduler thinks about cluster
- CA is making some mistake in calcluations (different approssimations?)

Almost exactly as issue #1049

**Comment by adonig** [comment]
In my case I had to delete my node groups and recreate them with different names.
