### ISSUE TITLE
Add firewall support to Hetzner cloud

### ISSUE THREAD

**Issue by vladimirtiukhtin** [kubernetes/autoscaler#4136]
**Which component are you using?**:

hetzner autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Currently nodes created by the sclaler has no firewall. I have to configure local iptables which is not very convenient

**Describe the solution you'd like.**:
I would like to have an environment variable where I can put firewall ID similar to how we are doing it for specifying network ID

**Comment by sergeyshevch** [comment]
I guess that it's duplicate of #4008

**Comment by vladimirtiukhtin** [comment]
@sergeyshevch indeed, sorry. I voted for it there
