### ISSUE TITLE
AWS IAM Policy

### ISSUE THREAD

**Issue by ruckc** [kubernetes/autoscaler#4139]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.21.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

I expected autodiscover to function on only the Resources listed in the IAM Policy.

**What happened instead?**:

autodiscover received AccessDenied error from AWS when calling DescribeTags with the specific ASG ARNs listed in the Resources section in the IAM Policy.
```
F0612 17:09:33.495900       1 aws_cloud_provider.go:382] Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::01234567890:assumed-role/role-name/01234567890 is not authorized to perform: autoscaling:DescribeTags
        status code: 403, request id: 3ccc4825-df05-4d91-a23b-1e27475c811b
```

**How to reproduce it (as minimally and precisely as possible)**:

Everytime

**Anything else we need to know?**:

The IAM Policy i am using is exactly from the [AWS Readme.md](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md).  The only difference between "working but not Resource constrained" and "not working with resource constrained" is the exact ARNs for the ASGs.

**Comment by guyromb** [comment]
Same on 1.20.4 (EKS)

**Comment by cslinuxfr** [comment]
try this policy:


{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "ec2:DescribeLaunchTemplateVersions"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
