### ISSUE TITLE
Is there a way to access VPA from Python code?

### ISSUE THREAD

**Issue by saeid93** [kubernetes/autoscaler#4140]
Hello everyone, Is there a way to use the [kubernetes python client](https://github.com/kubernetes-client/python/) api to access the vertical pod autoscaling functionalities through Python code? In the [documentation](https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md), I can only see API endpoints for [horizontal pod autoscaler](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AutoscalingV1Api.md#create_namespaced_horizontal_pod_autoscaler) not the vertical autoscaler. Is there a way to access VPA through Python code like the HPA?

**Comment by Jeffwan** [comment]
VPA is a CRD and you will need to use custom resource api and put Group Kind information. 
Check this for an example 

https://github.com/kubernetes-client/python/blob/master/examples/namespaced_custom_object.py

**Comment by saeid93** [comment]
Thanks! That solved my problem.
