### ISSUE TITLE
[VPA] Constantly updating recommendations lead to constant pod eviction

### ISSUE THREAD

**Issue by Niksko** [kubernetes/autoscaler#4148]
**Which component are you using?**:

VPA

**What version of the component are you using?**:

k8s.gcr.io/autoscaling/vpa-admission-controller:0.9.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

EKS 1.19

**What did you expect to happen?**:

The VPA recommended limits and requests for a single pod workload.

**What happened instead?**:

The VPA changed its recommendations every 30s or so, evicting and updating the pod every time. The requests and limits seemed to oscillate between two sets of recommendations.

**How to reproduce it (as minimally and precisely as possible)**:

This was using the `snyk-monitor` Helm chart, controlling the limits and requests.

**Anything else we need to know?**:

I was running the VPA with 3 replicas of each component, using Prometheus as a backend. When I scaled all of the components down to 1 replica each, the problem went away. This seemed to be localized to just this one workload.

Is running multiple replicas of each component not supported? Could it be an issue with Prometheus (we run 3 instances of prometheus behind a service, it's possible that each instance has slightly different data)? I'm not necessarily expecting a resolution to this issue, I suspect it might be hard to replicate.

**Comment by Jeffwan** [comment]
em.. I remember the sync period is 1min by default. What's your setting. Could you sharing VPA logs?
