### ISSUE TITLE
[VPA] issues with OOM events 

### ISSUE THREAD

**Issue by tx-kstav** [kubernetes/autoscaler#4152]
**Which component are you using?**:
VPA

**What version of the component are you using?**:

Component version: 0.9.2

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
</pre>
</details>

**What environment is this in?**: 
AWS EKS

**What did you expect to happen?**: 
I would expect OOM events to be handled with extra weight and increase the recommendation of memory, thus evicting the pod (update_mode="Auto") and creating a new one with updated memory request & limit.
Note that the recommendation was far less the maxAllowed value, so there was room for increase.

**What happened instead?**: 
There were multiple OOM events, and *some* of them were followed by a message "OOM event will be discarded - it is too old" (logs of vpa-recommender).
After the OOM events, the pods were being re-started with the same resources.
<pre>
I0617 14:56:11.153906       1 cluster_feeder.go:429] OOM detected {Timestamp:2021-06-17 14:55:19 +0000 UTC Memory:442809964 ContainerID:{PodID:{Namespace:my_namespace PodName:my_pod} ContainerName:my_container}}
W0617 14:56:11.153935       1 cluster_feeder.go:431] Failed to record OOM {Timestamp:2021-06-17 14:55:19 +0000 UTC Memory:442809964 ContainerID:{PodID:{Namespace:my_namespace PodName:my_pod} ContainerName:my_container}}. Reason: error while recording OOM for {{my_namespace my_pod} my_container}, Reason: OOM event will be discarded - it is too old (2021-06-17 14:55:19 +0000 UTC)
</pre>
To actually bypass the issue, I manually edited the VPA object to increase the minAllowed value, so that the recommendation/target is forced to also increase.

**How to reproduce it (as minimally and precisely as possible)**: 
Try creating OOM events for a pod that is handled by VPA. 

**Anything else we need to know?**:
Probably irrelevant to the above, but in vpa-recommender logs I have also observed other "Failed to record OOM" events:
<pre>
W0618 12:18:53.066254       1 cluster_feeder.go:431] Failed to record OOM {Timestamp:2021-06-18 12:18:01 +0000 UTC Memory:272061154 ContainerID:{PodID:{Namespace:my_namespace PodName:abcd-abc-abcdefgh-abcde-abcde-abcdefghijk-abcdef-abcdefghijklmn} ContainerName:abcd-abc-abcdefgh-abcde-abcde-abcdefghijk-abcdef}}. Reason: KeyError: {my_namespace abcd-abc-abcdefgh-abcde-abcde-abcdefghijk-abcdef-abcdefghijklmn}
</pre> 
Note: I replaced pod and container name, but with similar, equal in length, strings.

**Comment by bskiba** [comment]
@krzysied I know you fixed a similar issue with incorrectly discarded OOMs, but the version mentioned here is pretty recent (0.9.2). Can you take a look if it could be related?

**Comment by matt-demers** [comment]
Commenting because we are seeing the exact same issue with the exact same error messages. Also running VPA 0.9.2

We had an issue where one of our deployments was perfectly healthy and scaled up to match the needs of the cluster, but then a series of OOM errors put the VPA into a loop where it continually lowered the memory limits, and caused more OOM errors.

You can see this happening in our dashboards for the deployment. The recommendation was a decently high value, but a series of crashlooping pods kept lowering the target recommendation.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/43042197/156217722-1a43bb05-b729-4240-87cd-93a81a5ea2ca.png">
