### ISSUE TITLE
[Action Required] Scheduler moved default plugins to Component Config.

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/autoscaler#4160]
Scheduler made a recent change where the default set of plugins is now set in component config defaulting path. This means to get the default set of plugins, one need to start with a versioned component config type, pass that through the defaulting logic and convert it to the internal type to get the default plugins (default filters).

so the call to [algorithmprovider.GetDefaultConfig()]( https://github.com/kubernetes/autoscaler/blob/c70efcf7fca7dc279dd6c88f64e6d272c1c44082/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go#L50)

needs to be replaced with:

```
import(
	"k8s.io/kube-scheduler/config/v1beta2"
	"k8s.io/kubernetes/pkg/scheduler/apis/config"
	"k8s.io/kubernetes/pkg/scheduler/apis/config/scheme"
)

func getDefaultProfile()  (*config.KubeSchedulerProfile, error) {
        var versionedCfg v1beta2.KubeSchedulerConfiguration
	scheme.Scheme.Default(&versionedCfg)
	cfg := config.KubeSchedulerConfiguration{}
	if err := scheme.Scheme.Convert(&versionedCfg, &cfg, nil); err != nil {
		return nil, err
	}
        if len(cfg.Profiles) == 0 {
          return nil, fmt.Errorf("no default scheduler profile")
        }
	return &cfg.Profiles[0], nil
}
```

and then use the returned profile instead of instantiating [one here](https://github.com/kubernetes/autoscaler/blob/c70efcf7fca7dc279dd6c88f64e6d272c1c44082/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go#L52).

/cc @MaciekPytel

**Comment by ahg-g** [comment]
Perhaps CA should have a flag to pass in the scheduler's component config file.

**Comment by ahg-g** [comment]
I created https://github.com/kubernetes/kubernetes/pull/103130 to host this function in the scheduler pkg, lets see if the community accepts this.

**Comment by x13n** [comment]
Looks like this was resolved in https://github.com/kubernetes/autoscaler/pull/4187 by @MaciekPytel 

/close
