### ISSUE TITLE
Cluster Autoscaler: When scaling down I don't want a specific auto scaled deployment to block scaling down

### ISSUE THREAD

**Issue by tmjd** [kubernetes/autoscaler#4177]
**Which component are you using?**:

Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I have a deployment that is auto-scaled based on the number of nodes in the cluster but a minimum number of pods for the deployment are deployed if nodes are available. For example if there are 1-3 nodes available then the same number of pods are deployed, above 3 nodes the pod count is scaled (so you see something like nodes:pods of 1:1, 2:2, 3:3, 4:3, 5:3, 6:3, 7:4). The pods are hostNetworked and use a ContainerPort so more than one cannot run on the same node. The result of this is when there are 3 nodes or less the Cluster Autoscaler will not scale down the nodes because it cannot move any of the pods to other nodes.

**Describe the solution you'd like.**:

There are several solutions I think would work:
* If there was an annotation or label that could be added to the deployment to tell the Cluster Autoscaler to ignore pods from the  specific deployment if it was the only pod blocking scaling down a node.
* If there was configuration to tell the Cluster Autoscaler to ignore a specific deployment (Like the first bullet but set by configuring the Cluster Autoscaler)
* There might also be a solution possible if the Cluster Autoscaler could make its intentions known and my deployment scaling code could detect that and scale the deployment down by one.

**Describe any alternative solutions you've considered.**:

I've considered adjusting the scale to 1:1, 2:1, 3:2, 4:3, 5:3, 6:3..., so that it would be possible to scale down from 3 to 2 to 1 nodes but for High Availability purposes I don't want to reduce them.

**Additional context.**:

It would even be fine to remove the last node as far as my deployment goes because it is only present to provide an infrastructure service, but if there are no nodes then there is no need for the deployment.

**Comment by prashilgupta** [comment]
This issue is also blocking us to upgrade the managed node group when calico is installed. Is there a workaround @tmjd

**Comment by tmjd** [comment]
When upgrading a node group you could scale the operator to zero then do the upgrade and then scale back to 1. That would prevent the operator from scaling up the number of typha instances because of the temporary increase in nodes being available.

**Comment by MaciekPytel** [comment]
There are some side-effects to this solution that may not be desirable, but maybe setting pod priority below CA [priority cutoff](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-work-with-pod-priority-and-preemption) could be a solution? This will make CA completely ignore those pods, meaning they will not block scale-down and also not trigger scale-up.

Given that CA is mostly stateless it's hard to have "not blocking scale-down" without "not triggering scale-up", as CA would just scaling-up immediately after scaling-down.

**Comment by tmjd** [comment]
> it's hard to have "not blocking scale-down" without "not triggering scale-up"
I believe that "not triggering scale-up" would be a reasonable expectation too for this feature.

**Comment by tmjd** [comment]
I just looked at the priority cutoff and that would not be appropriate for what I'm trying to achieve.
Like I mentioned the deployment is an infrastructure service, by that I mean K8s nodes would not be functional if it was not allowed to be scheduled. So if nodes exist then the deployment needs to be deployed (should have high priority) but scales with the number of nodes.

**Comment by ThatDeveloper** [comment]
Hey, is there an update to this? @MaciekPytel @tmjd

**Comment by MaciekPytel** [comment]
I don't think there is any feature that just solves this problem. I think an implementation would require CA to essentially understand the scaling strategy of the deployment in question and predict the behavior. A generic non-blocking of scale-down seems like an endless source of edge cases (what if scale-down doesn't trigger deployment resize? some pod will remain pending and without lower pod priority it may very well be some other pod).

I'd consider putting those pods on separate ASG/nodepool using very small nodes (only large enough for those pods). This is not ideal from binpacking perspective, but at least this way they'll not block scale-down of other nodes. Or just make them a daemonset if the ratio of pods / nodes makes it acceptable.
