### ISSUE TITLE
ArtifactHub not updated with the latest releases of the chart

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/autoscaler#4188]
**Which component are you using?**:

helm-chart

**What version of the component are you using?**:

Component version: 9.9.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> not relevant</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

not relevant

**What did you expect to happen?**:

I expect to see the latest versions of the chart published. 

**What happened instead?**:

https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler

**How to reproduce it (as minimally and precisely as possible)**:

not relevant

**Anything else we need to know?**:

not relevant

**Comment by MarcusNoble** [comment]
@pierluigilenoci It's currently waiting on this PR being merged: https://github.com/kubernetes/autoscaler/pull/4180

**Comment by pierluigilenoci** [comment]
Thank you!
