### ISSUE TITLE
Chart release for cluster-autoscaler-chart in version 9.10.2 missing

### ISSUE THREAD

**Issue by elenz97** [kubernetes/autoscaler#4190]
**Which component are you using?**:

Helm chart `cluster-autoscaler-chart`

**What version of the component are you using?**:

[`cluster-autoscaler-chart`](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-chart-9.10.2) in version `9.10.2`

**What did you expect to happen?**:

Installation of the `9.10.2` helm chart should succeed.

**What happened instead?**:

Chart installation failed, as no `9.10.2` release was published, see: https://github.com/kubernetes/autoscaler/runs/3017939453
**How to reproduce it (as minimally and precisely as possible)**:

```
$ helm repo add autoscaler https://kubernetes.github.io/autoscaler
$ helm --debug install autoscaler -n default autoscaler/cluster-autoscaler --version 9.10.2
install.go:173: [debug] Original chart version: "9.10.2"
Error: chart "cluster-autoscaler" matching 9.10.2 not found in autoscaler index. (try 'helm repo update'): no chart version found for cluster-autoscaler-9.10.2
helm.go:81: [debug] no chart version found for cluster-autoscaler-9.10.2
[...]
chart "cluster-autoscaler" matching 9.10.2 not found in autoscaler index. (try 'helm repo update')
$ helm version 
v3.6.0
```

```
curl -s https://kubernetes.github.io/autoscaler/index.yaml | yq e '.entries.cluster-autoscaler[] | .version + " " + .appVersion' -
9.9.2 1.20.0
9.9.1 1.20.0
9.9.0 1.20.0
9.8.0 1.20.0
9.7.0 1.20.0
9.6.0 1.20.0
9.5.0 1.20.0
9.4.0 1.18.1
9.3.2 1.18.1
9.3.1 1.18.1
9.3.0 1.18.1
9.2.0 1.18.1
9.1.0 1.18.1
9.0.0 1.18.1
```

**Comment by haines** [comment]
This will be fixed in https://github.com/kubernetes/autoscaler/pull/4180.

**Comment by gjtempleton** [comment]
This should now be resolved, you should be able to fetch and install releases up to `9.10.3`.

As an extra point, I've kicked off [this PR](https://github.com/kubernetes/test-infra/pull/23024), which once merged should prevent this lag between releases being published and the charts being able to be installed happening in the future.

cc: @stevehipwell
