### ISSUE TITLE
VPA getting 504 errors from API Server when trying to get a list of cronjobs

### ISSUE THREAD

**Issue by MattJeanes** [kubernetes/autoscaler#4198]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: https://artifacthub.io/packages/helm/fairwinds-stable/vpa (0.3.4)

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"5a7170d3bbf1731483f4844c2222c70501717341", GitTreeState:"clean", BuildDate:"2021-05-25T17:36:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AKS on Azure

**What did you expect to happen?**:

The VPA component working normally without causing API errors

**What happened instead?**:

Intermittent calls to LIST `/apis/batch/v1beta1/cronjobs?resourceVersion=5365342` originating from the VPA recommender + updater result in 504 Gateway exceptions from the API server.

**How to reproduce it (as minimally and precisely as possible)**:

The issue is intermittent and we are not yet sure if it is the cluster or VPA at fault but we just have the VPA component and a single stateful set (Prometheus) which has a VPA applied. There are no cron jobs in the cluster.

**Anything else we need to know?**:

I'm actively investigating this with Azure support at the moment but they recommended I raise an issue here if nothing else to ask about the resourceVersion parameter that gets added onto these API calls - where it comes from and why it is there.

We have seen that setting a higher number than exists to the resourceVersion will result in a 504 and this is also documented inside Kubernetes documentation: https://kubernetes.io/docs/reference/using-api/api-concepts/#unavailable-resource-versions

We are not currently sure if the cluster is incorrectly responding with a 504 or if VPA is sending incorrect an resourceVersion parameter, and whether or not this has anything to do with the AKS Uptime SLA with multiple API Server replicas.

The errors we have seen have been intermittent but it seems to be in blocks, for example we saw an 8 hour block where both the VPA recommender and updater were trying to call the URL above every 5 seconds and it was resulting in a 504 Gateway Timeout but after then it calmed down again for a day or so before picking up again. You can see this behaviour in this graph from Prometheus clearly showing the elevated error rates which I have traced all back to VPA:

![image](https://user-images.githubusercontent.com/2363642/125799015-5d909fe4-065f-4ac6-901d-7431cdceb83c.png)

**Comment by bskiba** [comment]
Couple clarifications.
1. Can you provide some VPA logs around the issue?
2. Can you check the VPA version reported in the logs? I'm not sure the version you're using is based on this repository - there was no 0.3.4 version of VPA released. 

The resource version parameter most probably comes from informer code (we don't list CronJobs directly in VPA code).

**Comment by MattJeanes** [comment]
We are currently not experiencing the issue at this time (as it is an intermittent issue), so I will wait for it to re-appear and collect logs for you, assuming of course that it does re-appear.

The Helm chart version does not directly map to the VPA version, so the VPA images of the pods are:
- us.gcr.io/k8s-artifacts-prod/autoscaling/vpa-recommender:0.9.2
- us.gcr.io/k8s-artifacts-prod/autoscaling/vpa-updater:0.9.2
- us.gcr.io/k8s-artifacts-prod/autoscaling/vpa-admission-controller:0.9.2

Could you tell me a bit more about the informer code and what it's used for? I have had a look in the code and seen references to the CronJob informer but I am not sure how that translates to API calls every 5 seconds.

From what I can tell the `resourceVersion` appears to initially start at zero and then it caches and sends back the `resourceVersion` from the response metadata on future requests, does this sound correct?

This may be the wrong place to ask but I assume multiple replicas of the Kubernetes API Server should be able to accept the same `resourceVersion` for a particular call and that they don't have their own numbers for each replica that could result in the VPA calling the API Server with a `resourceVersion` higher than it knows, resulting in a 504

**Comment by jbartosik** [comment]
If you're affected by this please reopen.
