### ISSUE TITLE
feat(CA): EKS private cluster - update instance types

### ISSUE THREAD

**Issue by dpeer6** [kubernetes/autoscaler#4204]
Hi,

I'm using AWS EKS 1.18 with managed node group and CA 1.18.3 (aka the container image version/tag)

I'm using the cluster autoscaler, deployed by the manifest.

I would like to start and schedule pods on p4d.24xlarge instance types and I get the error:
static_autoscaler.go:268] Failed to get node infos for groups: ASG "eksctl-xxx-NodeGroup-xxxx" uses the unknown EC2 instance type "p4d.24xlarge"

Which can be expected since those are new instance types and our EKS cluster is private with NO internet access at all.
The autoscaler started with the following command args:
command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=priority
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/foo-bar-cluster
            - --balance-similar-node-groups
            - --skip-nodes-with-system-pods=false
            - --scale-down-unneeded-time=30m
            - --aws-use-static-instance-list=true

Again, the cluster autoscaler image used is: cluster-autoscaler:v1.18.3

I hope this is the right place to ask/raise the issue after lots of digging:

1. How can I update the instance type on such cluster? I tried to build it from source with no luck (go run ec2_instance_types/gen.go)
Or ask for one of the options to be able and copy the updated static list to the docker image, mount it as part of the deployment, or provide and alternative/private URL to fetch the updated file? (which will be downloaded manually to the alternate location)

2. How risky it is to use updated image version of the autoscaler, that includes updated instance types that does not match the K8s/EKS cluster version?
meaning, cluster-autoscaler:v1.20.n while the cluster is running 1.18.n
3. any other idea?

Many thanks!

**Comment by dpeer6** [comment]
Can someone help me and change the label to feature request?

**Comment by bpineau** [comment]
What issue did you encounter with `gen.go`? Did you provide aws creds, and pass a region name? eg.
```
# export AWS creds, or use aws-vault, etc then
go run cluster-autoscaler/cloudprovider/aws/ec2_instance_types/gen.go -region us-east-1
mv ec2_instance_types.go cluster-autoscaler/cloudprovider/aws/
(then build the cluster-autoscaler as usual)
```

Depending on your constraints (wether that account for internet access or not), a VPC endpoint might be an option?

I personally had no issues running recent cluster-autoscaler on older clusters, but that's not a supported configuration (misbehaviours are unlikely but not impossible); indeed [p4d.24xlarge](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L2034-L2039) support made its way to recent CA versions.

**Comment by dpeer6** [comment]
I could not get the docker image build, when I fetched the branch for 1.18.3 release.
I might be missing something but could not find to right docs/procedure to follow. can you guide me here?
I tried building it and failed (i'm not a go expert but build before go projects).

I do like to report that CA version 1.21.0 does the work for us for now, scaling up and down as expected, with the p4d.24xlarge support. So in that space we are good.

I do wonder if this kind of capability, of defining an alternate URL to download an updated URL would be something you can consider? If you do, I can try and contribute to have that capability for complete private clusters.
