### ISSUE TITLE
[VPA] Recommender recommends `request` > `limit`

### ISSUE THREAD

**Issue by umialpha** [kubernetes/autoscaler#4205]
**Which component are you using?**:
VPA
**What version of the component are you using?**:
0.9.2

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-BCS.patch.v3", GitCommit:"47a5f679b379dc6962fc0967069f4deb445093d2", GitTreeState:"clean", BuildDate:"2020-10-28T02:58:43Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-BCS.patch.v3", GitCommit:"47a5f679b379dc6962fc0967069f4deb445093d2", GitTreeState:"clean", BuildDate:"2020-10-28T02:58:43Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

On premise

**What did you expect to happen?**:

Recommender should not recommend `request` more than `limit`. For example, 
```yaml
requests:
  cpu: 10
limits:
  cpu: 10
```
The cpu usage is really high, say p90 == 9. Also, we set ContainerPolicy == UpdateRequestOnly. The targetEstimator == `WithMargin(*safetyMarginFraction, targetEstimator)` , in which `*safetyMarginFraction` == 0.15, then the result is 9 * 1.15 == 10.35

**Comment by bskiba** [comment]
By default, limit is kept proportional to the request (see [limits control section of readme](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#limits-control))

If this behavior doesn't work for you and you want the limit to stay unchanged and for it to be a maximum for recommended request, you can set [ControlledValues](https://github.com/kubernetes/autoscaler/blob/d74c8e3b11b3476d509aaae9fbd591eb6dd98960/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L165) to [RequestOnly](https://github.com/kubernetes/autoscaler/blob/d74c8e3b11b3476d509aaae9fbd591eb6dd98960/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L195).

**Comment by umialpha** [comment]
@bskiba  thanks for your reply. 
`for it to be a maximum for recommended request`
It is the problem, e.g. we have computer nodes with maximum of 30 cores. Users set `requests == limits == 30`, and p90 usage is 29 cores. The recommender will set `target == 29 * 1.15`  which is larger than 30. It causes the pod stuck in pending.

**Comment by bskiba** [comment]
In that case, please set the ControlledValues to RequestOnly as mentioned. In this mode VPA shouldn't recommend more than the limit.
Alternatively you can use [MaxAllowed](https://github.com/kubernetes/autoscaler/blob/d74c8e3b11b3476d509aaae9fbd591eb6dd98960/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L155) to control the maximum value of recommendation.

**Comment by umialpha** [comment]
> In that case, please set the ControlledValues to RequestOnly as mentioned. In this mode VPA shouldn't recommend more than the limit (if it does, it's a bug).
> Alternatively you can use [MaxAllowed](https://github.com/kubernetes/autoscaler/blob/d74c8e3b11b3476d509aaae9fbd591eb6dd98960/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L155) to control the maximum value of recommendation.

Indeed, I set ControlledValues to RequestOnly as you mentioned. So I doubt it is a bug.

**Comment by jbartosik** [comment]
Is this problem solved?

**Comment by jbartosik** [comment]
Please reopen fi this isn't solved yet.
