### ISSUE TITLE
[cluster-autoscaler] Additional expander options

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/autoscaler#4206]
Users are able to specify the `expander` [option](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders) to change which nodegroup (e.g. ASG) is selected when there are multiple that satisfy the scheduling requirements for a pod. The feature request is to allow selecting an additional expanders in the event that the chosen expander *still* arbitrarily ties multiple nodegroups. This is very similar to this closed ticket https://github.com/kubernetes/autoscaler/issues/2564.

For our specific use case, we are currently using the `least-waste` expander, but we want to have some nodegroups which are preferred. What we would then like is to use the `priority` expander but fall back to `least-waste` when multiple still match.

I see several ways this feature could be added, in my order of preference
1. Use a `list` of expanders to use, with some validation of course very similar to what @adrienjt mentions [here](https://github.com/kubernetes/autoscaler/issues/2564#issuecomment-825116554). Satisfying my above use case would look like setting `expander=priority,least-waste`.
1. Add a `priority-expander` option, specifically only used in the case where `expander=priority`. Satisfying the above use case would look like setting `expander=priority` and `priority-expander=least-waste`

I think the first option is cleaner / easier to understand but is perhaps more complicated to implement. I'd be happy to submit a PR for this but wanted to get any feedback first, thanks!

cc @Jeffwan @bpineau @adrienjt

**Comment by x13n** [comment]
`mostpods` and `waste` expanders, similarly to `priority`, have a notion of fallback strategy. Option 1 is much cleaner from API point of view, and also fairly easy to implement - we'd just need to update expander factory to allow chaining (and return an error if there's an expander configured after a one that doesn't need fallback).

**Comment by ryanmcnamara** [comment]
Thanks @x13n 
I'll probably take a shot at this over the next several days and push something else. Would you like to review or know who I should get for a review?

**Comment by x13n** [comment]
I'm happy to review the change, but you'll still need a repo owner to approve.

**Comment by x13n** [comment]
This was done in https://github.com/kubernetes/autoscaler/pull/4233

/close

**Comment by stevehipwell** [comment]
@x13n which versions of CA have this code?

I think there is a bigger question here on backporting vs recommending newer CA builds for supported K8s versions, does this need a separate issue opening?

**Comment by x13n** [comment]
None yet, it will be a part of 1.23 release. I think backporting should mostly be limited to bug fixes, not new features like this one, but if you disagree then yes, a separate issue sounds like a good starting point.
