### ISSUE TITLE
Scale down for any pod without configure pdb

### ISSUE THREAD

**Issue by chmodrs** [kubernetes/autoscaler#4217]
Hi,

I'm using CA (v1.17.3) in EKS (1.20) cluster and all of my applications (legacy cluster) can be deleted by autoscaler, i really want that if a node is unneeded, CA will remove independently of what pod is running.

I setup this configuration for CA:
          
```
 - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            - --scale-down-delay-after-add=5m
            - --scale-down-unneeded-time=5m
            - --skip-nodes-with-system-pods=false
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/mycluster
```

But CA can't scale down any nodes, the most of my nodes are using 10/12% of memory and 5% of cpu and CA still keeps nodes running.

I get this message of cluster autoscaler logs:

```
I0722 16:44:49.596036       1 static_autoscaler.go:452] Starting scale down
I0722 16:44:49.596133       1 scale_down.go:776] No candidates for scale down
```

Have some flag that allow CA to delete nodes independently pods running in my node even if it cause a downtime?

for information purposes, i have multiples nodegroups using spot instances, but in autoscaler documentation shows that CA will monitoring metrics of each ASG group e scale down/up based on each ASG, right?

Thanks!

**Comment by bpineau** [comment]
Scale downs might be held for various reasons. Are nogroups `minSize` reached? Have your workloads exceeded their `podDisruptionBudget`? did you account for daemonsets and mirror pods in actual usage (or tried to run with `--ignore-daemonsets-utilization`)?

You might see logs giving hints like that one (though I'm not 100% sure that was already logged by CA 1.17 time):
```
[scale_down.go:444] Node foo is not suitable for removal - cpu utilization too big (0.910256)
```
