### ISSUE TITLE
Scaling down with shared volume and safe-to-evict="true"

### ISSUE THREAD

**Issue by hryamzik** [kubernetes/autoscaler#4219]
**Which component are you using?**:

`cluster-autoscaler`

**What version of the component are you using?**:

Helm version is `9.4.0`

_UPDATE: upgraded to 9.9.2, no difference._

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
</pre></details>

**What environment is this in?**:
EKS

**What did you expect to happen?**:
Scale nodes down

**What happened instead?**:
Nodes not scaled down

**How to reproduce it (as minimally and precisely as possible)**:

Set up deployment with volumes:
```yaml
      volumes:
      - name: shared
        emptyDir: {}
```

Set `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` pod annotation as described in [docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node).

Get to a scale down scenario.

```
I0722 22:04:14.142969       1 cluster.go:148] Fast evaluation: ip-***.ec2.internal for removal
I0722 22:04:14.142977       1 cluster.go:168] Fast evaluation: node ip-***.ec2.internal cannot be removed: pod with local storage present: POD
I0722 22:04:14.142985       1 scale_down.go:591] 1 nodes found to be unremovable in simulation, will re-check them at 2021-07-22 22:09:14.141080417 +0000 UTC m=+79235.124404407
```

**Comment by hryamzik** [comment]
Looks like there's difference between `Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: true` and `Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"`. First one is not that trivial to set via helm cli, I didn't manage to make it,

**Comment by bpineau** [comment]
Note there's a `--skip-nodes-with-local-storage` option, defaulting to `true`:
> If true cluster autoscaler will never delete nodes with pods with local storage, e.g. EmptyDir or HostPath (default true)

**Comment by hryamzik** [comment]
This pod annotation should work:
> Adds support for safe-to-evict annotation on pod. Pods with this annotation can be evicted even if they don't meet other requirements for it.

**Comment by hryamzik** [comment]
Hey @bpineau can we keep this open until issue is resolved?
