### ISSUE TITLE
Chart from "https://kubernetes.github.io/autoscaler" version 9.10.3 is not properly config.

### ISSUE THREAD

**Issue by RiddlerKnight** [kubernetes/autoscaler#4232]
This is chart version 9.10.2
![2021-07-30_10-51-43](https://user-images.githubusercontent.com/15905772/127597800-5569c11f-e43b-40a9-9091-bb82014417c3.jpg)

but chart version 9.10.3, there are no files inside.
![2021-07-30_09-44-55](https://user-images.githubusercontent.com/15905772/127597857-db70506d-effb-487d-8e91-920e0d66f1df.jpg)

**Comment by gjtempleton** [comment]
Hey, thanks for raising this issue. 

Do you have any data on when this was (I assume) synced to whatever tool you're using? I suspect it may have performed a sync in a period where the link to the file for the 9.10.3 release was incorrect and would have resulted in the `versionUrls` you see in the second screenshot above. This should have been resolved by the merging of #4227, so if you're able to trigger a resync, this should now be resolved.

Please let me know if it isn't!

**Comment by RiddlerKnight** [comment]
> Hey, thanks for raising this issue.
> 
> Do you have any data on when this was (I assume) synced to whatever tool you're using? I suspect it may have performed a sync in a period where the link to the file for the 9.10.3 release was incorrect and would have resulted in the `versionUrls` you see in the second screenshot above. This should have been resolved by the merging of #4227, so if you're able to trigger a resync, this should now be resolved.
> 
> Please let me know if it isn't!

I added this chart to rancher since 11 jul 2021 as helm3 chart. I have re-add the chart again now it work properly.

Thanks.
