### ISSUE TITLE
Release Cluster Autoscaler 1.22

### ISSUE THREAD

**Issue by x13n** [kubernetes/autoscaler#4240]
Now that Kubernetes 1.22 [was released](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md), we should cut a new Cluster Autoscaler version.

**Comment by x13n** [comment]
Release branch was created: https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-release-1.22

**Comment by bpineau** [comment]
Let's remember [cluster-autoscaler/version/version.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/version/version.go#L20) update (missed the 1.21 release)

**Comment by x13n** [comment]
Yeah, I'll bump it on the release branch after fixing the deps, I wonder if it should be something like "head" on the master branch though.

**Comment by towca** [comment]
I think on master it should be bumped to whatever k8s version we're updating the vendor to (e.g. `1.23.0-alpha.0`). We could do that automatically in the update-vendor script, WDYT?

**Comment by x13n** [comment]
Yup, that's exactly why I sent https://github.com/kubernetes/autoscaler/pull/4245 :) Can you review it?

**Comment by x13n** [comment]
GitHub release created: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.0
