### ISSUE TITLE
Cluster Autoscaler patch releases

### ISSUE THREAD

**Issue by towca** [kubernetes/autoscaler#4251]
Hi! I want to cut new Cluster Autoscaler patch releases for 1.19, 1.20 and 1.21 (if needed) early next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

Tagging cloud provider owners for visibility:
@ringtail @Jeffwan @jaypipes @gjtempleton @feiskyer @nilo19 @marwanad @hello2mao @davidjumani @enxebre @elmiko @hardikdr @detiber @andrewsykim @MorrisLaw @kevin-wangzefeng @RainbowMango @avorima @ellistarn @tghartland @d-mo @detiber @deitch @displague @gianarb

**Comment by gjtempleton** [comment]
Thanks, there are a few on the AWS side that I'll get raised this week.

**Comment by feiskyer** [comment]
@marwanad could you cherry-pick the fix #4130 to these branches?

**Comment by tghartland** [comment]
Hello, is it possible to make a release for 1.22.1 this soon after the .0 release?
I enabled scale to zero for magnum in 1.22, but I missed a requirement on using a newer magnum API microversion.
It fails only for scaling to 0, any other scaling still works so it isn't incredibly urgent.

PR for the fix on master branch: #4261

**Comment by gjtempleton** [comment]
One thing this has thrown up is that we should also cherry-pick the Github actions switch back to the 1.19 and 1.20 release branches.

As you can see from the above cherry-pick PRs from me, if the actions aren't in the branches being merged to, they won't be triggered.

**Comment by detiber** [comment]
If the releases haven't been cut yet, then it would be nice to get cherry-picks for https://github.com/kubernetes/autoscaler/pull/4274 in as well.

/cc @ipochi

**Comment by michael-careplanner** [comment]
If possible it would also be great to get https://github.com/kubernetes/autoscaler/pull/4089 in too.

I think this would only need bringing in to the 1.21 release as it fixes an issue introduced in https://github.com/kubernetes/autoscaler/commit/9831623810aac0f85383dd509a36cb459363603e, after the 1.20 release.

**Comment by towca** [comment]
@gjtempleton Thanks for the Github actions PRs, I responded on one of them. Have you merged everything you wanted to?
@feiskyer Should I wait for the #4130 cherry-picks?
@tghartland Sure, could you prepare the PR?
@detiber Could you prepare the PRs?
@michael-careplanner I'll look into #4089, thanks for bringing it up!

**Comment by tghartland** [comment]
My cherry pick PR #4283.

Thanks.

**Comment by gjtempleton** [comment]
@towca Sorry, I've not had a chance to spend any more time looking into the Github action PRs and why they're failing this wekk, however all the AWS related ones I wanted to charry-pick back have been merged, so happy to go ahead with cutting releases from that side.

**Comment by ipochi** [comment]
> My Cherry pick PRs for #4274
> 
> #4291 - 1.19
> #4290 - 1.20
> #4288 - 1.21
> #4289 - 1.22
> 
> /cc @detiber

@towca @detiber 

can you please check if I've done everything correctly and nothing is pending from my end ?

**Comment by tulsluper** [comment]
Is it possible to get cherry-picks for https://github.com/kubernetes/autoscaler/pull/3924 ?

**Comment by matthias50** [comment]
@tulsluper, regarding #3924 I created #4319 for  1.20. I attempted to create one for 1.19 but it had merge conflicts.

**Comment by rbaybutt** [comment]
@towca If you don't have time to get to it I can create the cherry pick PR (just needed in v1.21) for https://github.com/kubernetes/autoscaler/pull/4089
I'm seeing issues with this in CA v1.21 so I'm happy to to create the PR but don't want want to duplicate effort if you're already on it.

**Comment by jcrowthe** [comment]
@feiskyer Can you drive a cherry-pick for #4130 back to at least 1.20? We have strong evidence that this is causing outages in production.

**Comment by feiskyer** [comment]
@jcrowthe  cherry-pick for #4130 (#4356 and #4355) have been merged now.

**Comment by towca** [comment]
@gjtempleton FYI I managed to backport Github Actions to 1.19 and 1.20 (#4366 , #4367). I think the issue was with the Go version - 1.20 should use go1.15, and 1.19 should use go1.13.
@rbaybutt #4089 has been cherry-picked to 1.21 in #4311
@tulsluper @matthias50 #3924 will only apply cleanly on 1.20. 1.19 doesn't have previous changes to the same logic. Thanks for the cherry-pick, merged!
@feiskyer @marwanad The cherry-picks for #4130 broke the build on 1.19 and 1.20 (CI was not running on these branches). Details: #4368. Please fix ASAP so we can proceed with cutting the release. Also - was not backporting #4130 to 1.21 intentional?

**Comment by gjtempleton** [comment]
@towca Thanks for that! Seems I'd not stumbled on the correct go versions somehow.

**Comment by marwanad** [comment]
@towca I missed the 1.21 cherry-pick. I'll do that now.

**Comment by towca** [comment]
Thanks to everyone for your contributions, the releases are here:
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.19.2
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.20.1
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.21.1
* https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.1
