### ISSUE TITLE
Missing namespaces RBAC permission for cluster-autoscaler

### ISSUE THREAD

**Issue by Tenzer** [kubernetes/autoscaler#4256]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.22.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
~ % kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

We are using AWS but I don't think that matters here.

**What did you expect to happen?**:

The output from the cluster-autoscaler pod shouldn't give any errors about missing permissions.

**What happened instead?**:

I am seeing log messages such as the following:

> k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "namespaces" in API group "" at the cluster scope

**How to reproduce it (as minimally and precisely as possible)**:

This is configured using the [cluster-autoscaler-autodiscover.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml) configuration, but I think it should be a problem for any cluster-autoscaler setup as none of the YAML files specifies permissions for it to access namespaces.

**Anything else we need to know?**:

I haven't been able to figure out which part of the code that tries to list namespaces so I haven't been able to figure out when this problem might have started. I only noticed it in the logs from the cluster-autoscaler pod in relation to upgrading it to version 1.22.0.

**Comment by jamesdehart** [comment]
I saw this same error and I'm running the same version as you. Just before that error I also see:

```
I0811 23:49:55.792818       1 request.go:597] Waited for 361.356292ms due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0
E0811 23:49:55.794467       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler-aws-cluster-autoscaler" cannot list resource "namespaces" in API group "" at the cluster scope
```

To help here is the method that is sending the error [newPodListerByNamespace](https://github.com/kubernetes/autoscaler/blob/master/addon-resizer/nanny/kubernetes_client.go#L138)

I hope this helps.

**Comment by darrenfurr** [comment]
I'm getting the same error, v1.22.0 on EKS 1.18.

**Comment by filintod** [comment]
I was hit with the same error. Needed to manually add namespaces to the clusterrole
