### ISSUE TITLE
[VPA] Updater may not works with a PDB

### ISSUE THREAD

**Issue by vflaux** [kubernetes/autoscaler#4284]
**Which component are you using?**:
VPA admission controller, recommender and updater.

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

With a Deployment, a VPA (in auto mode) and a PDB, if the containers get OOMKilled in loop and the pods all became unavailable, the vpa updater cannot kill the pods (and let the vpa admission controller increase memory requests) as it would violate the pod disruption budget.  
You end up with a permanent service disruption and the VPA is useless.

**Describe the solution you'd like.**:

The VPA updater should be able to kill pods that are not ready (and maybe with a restart count >0).
There is no harm in violating the PDB if the service is already down.

**Comment by jbartosik** [comment]
Hi,
VPA uses makes an [Evict](https://github.com/kubernetes/autoscaler/blob/f0eb6e8f78f582641f97a1d62aa5f8304a4586bd/vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go#L137) call so PDB can check if it's safe to delete the pod.

I think it's better to make a change to PDB than to add workarounds in VPA (working around PDB sounds error prone).
