### ISSUE TITLE
[Helmchart][Cluster-autoscaler]

### ISSUE THREAD

**Issue by MaxRink** [kubernetes/autoscaler#4297]
**Which component are you using?**:

cluster autoscaler helmchart
**What version of the component are you using?**:

Component version: latest helm chart, 9.10.5

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-07-16T17:16:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Cluster-API

**What did you expect to happen?**:

The helm chart allows me to set `--clusterapi-cloud-config-authoritative`
**What happened instead?**:

The helm chart doesnt allow to specify args without values, thus the autoscaler fails
```
invalid argument "" for "--clusterapi-cloud-config-authoritative" flag: parse error
```

**How to reproduce it (as minimally and precisely as possible)**:
set 
```
  extraArgs:
    clusterapi-cloud-config-authoritative: 

```
and run helm install 
**Anything else we need to know?**:

**Comment by ArchiFleKs** [comment]
have you tried setting:

```
  extraArgs:
    clusterapi-cloud-config-authoritative: ""
```

**Comment by MaxRink** [comment]
Yes, that produces the exact behaviour explained above
