### ISSUE TITLE
addon-resizer does not work

### ISSUE THREAD

**Issue by tanvp112** [kubernetes/autoscaler#4307]
I ran addon-resizer as a sidecar with a php-apache; suppose when the CPU goes beyond 200m for 5 consecutive times, I would expect addon-resizer to scale up the pod. But the CPU has ran over 200m for an hour and nothing happens. addon-resizer logs remain the same as the follow.

I ran the official addon-resizer example and see the same ERROR, are these really error or just message dump? I couldn't find any working example for addon-resizer that demonstrate it really scale pod. The document is really out of date and contains multiple erros... can anyone explain how to make this addon-resizer work?

```
NAME                              CPU(cores)   MEMORY(bytes)
metrics-server-7dd465f884-7nmrj   27m          34Mi
php-apache-6f6d97764d-cv8b2       220m         21Mi
```

```
ERROR: logging before flag.Parse: I0906 16:22:15.009886       1 pod_nanny.go:68] Invoked by [/pod_nanny --cpu=200m --extra-cpu=10m --memory=100Mi --extra-memory=10Mi --threshold=5 --deployment=php-apache --container=php-apache]
ERROR: logging before flag.Parse: I0906 16:22:15.009953       1 pod_nanny.go:69] Version: 1.8.14
ERROR: logging before flag.Parse: I0906 16:22:15.009964       1 pod_nanny.go:85] Watching namespace: kube-system, pod: php-apache-6f6d97764d-cv8b2, container: php-apache.
ERROR: logging before flag.Parse: I0906 16:22:15.009969       1 pod_nanny.go:86] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0906 16:22:15.107248       1 pod_nanny.go:189] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0906 16:22:15.107337       1 pod_nanny.go:116] cpu: 200m, extra_cpu: 10m, memory: 100Mi, extra_memory: 10Mi
ERROR: logging before flag.Parse: I0906 16:22:15.107354       1 pod_nanny.go:145] Resources: [{Base:{i:{value:200 scale:-3} d:{Dec:<nil>} s:200m Format:DecimalSI} ExtraPerNode:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI} Name:cpu} {Base:{i:{value:104857600 scale:0} d:{Dec:<nil>} s:100Mi Format:BinarySI} ExtraPerNode:{i:{value:10485760 scale:0} d:{Dec:<nil>} s:10Mi Format:BinarySI} Name:memory}]
```

**Comment by jbartosik** [comment]
Hi,
addon-resizer sets cpu and memory requests based on number of nodes in the cluster, see [README](https://github.com/kubernetes/autoscaler/tree/92751c4/addon-resizer#overview):

> On n-node cluster, the total CPU assigned to the addon will be computed as:
>
> `cpu + n * extra-cpu`
>
> On n-node cluster, the total memory assigned to the addon will be computed as:
> 
> `memory + n * extra-memory`


[Vertical Pod Autoscaler](https://github.com/kubernetes/autoscaler/tree/92751c4a5a461211d7666288fac3ed9473adbd68/vertical-pod-autoscaler) sets cpu and memory request based on usage in last 8 days, this sounds the closes to what you expected from addon-resizer.

There is also [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) but it doesn't change resource requests. It adds more instances of pod

**Comment by jbartosik** [comment]
Errors look unrelated - they are because addon resizer is logging before it calls  `flag.Parse`
