### ISSUE TITLE
[General question for guidance] Enable Autoscaling of Nodes based on GPU share

### ISSUE THREAD

**Issue by dempti** [kubernetes/autoscaler#4315]
**Which component are you using?**:
cluster-autoscaler -> cloudprovider -> aws -> GPU Nodes

cluster-autocaler
**What version of the component are you using?**:
latest

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.21

**What environment is this in?**:
EKS
 aws g4dn.2xlarge instance

**What did you expect to happen?**:
autoscale instance based on pods scheduling failed because of unavailable resources.

**What happened instead?**:
Nodes did not scale up with error ''NotTriggerScaleUp' pod didn't trigger scale-up: 1 Insufficient k8s.amazonaws.com/vgpu`
 enable GPU sharing based on following. This will require to add label 
 `k8s.amazonaws.com/accelerator=vgpu`  on gpu nodes.
[vgpu repository](https://github.com/awslabs/aws-virtual-gpu-device-plugin)
[vgpu article](https://aws.amazon.com/blogs/opensource/virtual-gpu-device-plugin-for-inference-workload-in-kubernetes/)

**Anything else we need to know?**:
 Error Logs
```
clusterautoscaler-aws-cluster-autoscaler-6dbcb4d4f7-fv5w7 aws-cluster-autoscaler I0908 02:56:58.534530       1 scale_up.go:288] Pod resnet-deployment-8978c7f89-2469s can't be scheduled on eks-clusterNodegroupclusterdefa-aTwrPbQ2r3sD-60bdce6a-2014-ffda-69e8-b6f67da592f2, predicate checking error: Insufficient k8s.amazonaws.com/vgpu; predicateName=NodeResourcesFit; reasons: Insufficient k8s.amazonaws.com/vgpu; debugInfo=


clusterautoscaler-aws-cluster-autoscaler-6696574c75-zf65d aws-cluster-autoscaler I0908 03:01:29.704188       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"resnet-deployment-8978c7f89-gtnf6", UID:"a147f1be-a9d7-45a0-bb72-cd26a783ef9c", APIVersion:"v1", ResourceVersion:"5616318", FieldPath:""}): type: 'Normal' reason: 'NotTriggerScaleUp' pod didn't trigger scale-up: 1 Insufficient k8s.amazonaws.com/vgpu
```

**Comment by bpineau** [comment]
Trying to help, but I'm not familliar with upscaling GPU-enabled nodes.

Assuming your pods have a `k8s.amazonaws.com/vgpu` resource request (or limit), is that correct?

From what I can see in cloudprovider/aws, it seems that virtual nodes templates from ASG (used when scaling-up from zero/empty ASGs, eg. no nodes from that ASG have joined the cluster yet) are built with a `nvidia.com/gpu` resource (dynamically infered from instance type), but no `k8s.amazonaws.com/vgpu`. Upscales when a node already exists will use that node as a template (and pick its allocatable resources as model, so a `k8s.amazonaws.com/vgpu` if the existing node exposes that allocatable).
* Are you upscaling from an empty ASG? if so, do you get a better outcome after labeling the ASGs with `k8s.io/cluster-autoscaler/node-template/resources/k8s.amazonaws.com/vgpu: 1`  (and restarting the autoscaler to refresh caches)?
* If you hit that issue while gpu-enabled nodes have already joined the cluster: do those nodes' allocatables exposes a `k8s.amazonaws.com/vgpu` resource right from the moment they join the cluster, or later?
* Does this resolve over time (slow but eventually working scale-up)? It seems the gpu driver might not be available by the time the autoscaler pick a model node (in which case the autoscaler will use resources from a template node (so `nvidia.com/gpu` if the node has a `k8s.amazonaws.com/accelerator` label on aws)

Maybe `utils/gpu/gpu.go` (and `cloudprovider/aws/aws_manager.go`) would benefit from an update to support alternate values for `ResourceNvidiaGPU`, and support clusters using `aws-virtual-gpu-device-plugin` instead of `k8s-device-plugin`. But that would likely mean a cloudprovider API change.

**Comment by M-A-N-I-S-H-K** [comment]
@bpineau to answer your question.
1. no, I am scaling from non-empty ASG. I did label the ASG with `k8s.io/cluster-autoscaler/node-template/resources/k8s.amazonaws.com/vgpu: 1` but still no luck. Also restart the autoscaler after update on ASG. 
2. yes, the nodes expose the labels `k8s.amazonaws.com/vgpu:10` (1 GPU is equal to 10vGPU). 
3. no it does not resolve overtime, I left the cluster on that state for more than 5/6 hours but the pods which were on pending state supposed to trigger scale up were still in the same state and no new nodes were added. The nodes did have a lable `k8s.amazonaws.com/accelerator` but still nothing. 

Here is the sample of the pod.yaml
```
apiVersion :  apps/v1
kind :  Deployment
metadata :
  name :  resnet-deployment
spec :
  replicas :  10
  selector :
     matchLabels :
       app :  resnet-server
  template :
    metadata :
      labels :
        app :  resnet-server
    spec :
      #  hostIPC is required for MPS communication
      hostIPC :  true
      containers :
      - name :  resnet-container
        image :  seedjeffwan/tensorflow-serving-gpu:resnet
        command: ["sh", "-c", "tail -f /etc/hosts"]
        args :
         #  Make sure you set limit based on the vGPU account to avoid tf-serving process occupy all the gpu memory
        -  --per_process_gpu_memory_fraction=0.2
        env :
        - name :  MODEL_NAME
          value :  resnet
        ports :
        -  containerPort :  8501
        #  Use virtual gpu resource here
        resources :
           limits :
             #k8s.amazonaws.com/vgpu :  1
             memory: 15Gi
             cpu: 4000m
        volumeMounts :
        - name :  nvidia-mps
          mountPath :  /tmp/nvidia-mps
      volumes :
      - name :  nvidia-mps
        hostPath :
          path :  /tmp/nvidia-mps
```

Any suggestion would be of great help

**Comment by dempti** [comment]
@bpineau to answer your question.
1. no, I am scaling from non-empty ASG. I did label the ASG with `k8s.io/cluster-autoscaler/node-template/resources/k8s.amazonaws.com/vgpu: 1` but still no luck. Also restart the autoscaler after update on ASG. 
2. yes, the nodes expose the labels `k8s.amazonaws.com/vgpu:10` (1 GPU is equal to 10vGPU). 
3. no it does not resolve overtime, I left the cluster on that state for more than 5/6 hours but the pods which were on pending state supposed to trigger scale up were still in the same state and no new nodes were added. The nodes did have a lable `k8s.amazonaws.com/accelerator` but still nothing. 

Here is the sample of the pod.yaml
```
apiVersion :  apps/v1
kind :  Deployment
metadata :
  name :  resnet-deployment
spec :
  replicas :  10
  selector :
     matchLabels :
       app :  resnet-server
  template :
    metadata :
      labels :
        app :  resnet-server
    spec :
      #  hostIPC is required for MPS communication
      hostIPC :  true
      containers :
      - name :  resnet-container
        image :  seedjeffwan/tensorflow-serving-gpu:resnet
        command: ["sh", "-c", "tail -f /etc/hosts"]
        args :
         #  Make sure you set limit based on the vGPU account to avoid tf-serving process occupy all the gpu memory
        -  --per_process_gpu_memory_fraction=0.2
        env :
        - name :  MODEL_NAME
          value :  resnet
        ports :
        -  containerPort :  8501
        #  Use virtual gpu resource here
        resources :
           limits :
             #k8s.amazonaws.com/vgpu :  1
             memory: 15Gi
             cpu: 4000m
        volumeMounts :
        - name :  nvidia-mps
          mountPath :  /tmp/nvidia-mps
      volumes :
      - name :  nvidia-mps
        hostPath :
          path :  /tmp/nvidia-mps
```
Here is the ASG tags.
![image](https://user-images.githubusercontent.com/87458408/133012563-52b97a07-aee8-4931-894b-428a76b0ab8a.png)

Here is the node label
![image](https://user-images.githubusercontent.com/87458408/133012646-102b3bb2-8d10-4cd0-b660-15ca3051aa75.png)


Any suggestion would be of great help.

**Comment by dempti** [comment]
@bpineau to answer your question.
1. no, I am scaling from non-empty ASG. I did label the ASG with `k8s.io/cluster-autoscaler/node-template/resources/k8s.amazonaws.com/vgpu: 1` but still no luck. Also restart the autoscaler after update on ASG. 
2. yes, the nodes expose the labels `k8s.amazonaws.com/vgpu:10` (1 GPU is equal to 10vGPU). 
3. no it does not resolve overtime, I left the cluster on that state for more than 5/6 hours but the pods which were on pending state supposed to trigger scale up were still in the same state and no new nodes were added. The nodes did have a lable `k8s.amazonaws.com/accelerator` but still nothing. 

Here is the sample of the pod.yaml
```
apiVersion :  apps/v1
kind :  Deployment
metadata :
  name :  resnet-deployment
spec :
  replicas :  10
  selector :
     matchLabels :
       app :  resnet-server
  template :
    metadata :
      labels :
        app :  resnet-server
    spec :
      #  hostIPC is required for MPS communication
      hostIPC :  true
      containers :
      - name :  resnet-container
        image :  seedjeffwan/tensorflow-serving-gpu:resnet
        command: ["sh", "-c", "tail -f /etc/hosts"]
        args :
         #  Make sure you set limit based on the vGPU account to avoid tf-serving process occupy all the gpu memory
        -  --per_process_gpu_memory_fraction=0.2
        env :
        - name :  MODEL_NAME
          value :  resnet
        ports :
        -  containerPort :  8501
        #  Use virtual gpu resource here
        resources :
           limits :
             #k8s.amazonaws.com/vgpu :  1
             memory: 15Gi
             cpu: 4000m
        volumeMounts :
        - name :  nvidia-mps
          mountPath :  /tmp/nvidia-mps
      volumes :
      - name :  nvidia-mps
        hostPath :
          path :  /tmp/nvidia-mps
```
Here is the ASG tags.
![image](https://user-images.githubusercontent.com/87458408/133014304-fb52873f-acec-439e-a2b9-23e0262daf0d.png)


Here is the node label
![image](https://user-images.githubusercontent.com/87458408/133012646-102b3bb2-8d10-4cd0-b660-15ca3051aa75.png)


Any suggestion would be of great help.

**Comment by nikskiz** [comment]
@dempti Could the labelling be wrong for `k8s.amazonaws.com/accelerator`? I can see you have set `vgpu` but available types are:

```
		"nvidia-tesla-k80":  {},
		"nvidia-tesla-p100": {},
		"nvidia-tesla-v100": {},
		"nvidia-tesla-t4":   {},
```

According to: https://github.com/kubernetes/autoscaler/blob/7e5f8f0045c195376d773fc64998e2f8b7566316/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L41


This is also outlined here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#special-note-on-gpu-instances

Not sure if that helps?

**Comment by dempti** [comment]
@nikskiz please refer to this section of the following github repository which is considered for sharing GPU nodes between multiple pods.
[repo](https://github.com/awslabs/aws-virtual-gpu-device-plugin#quick-start)
[article](https://aws.amazon.com/blogs/opensource/virtual-gpu-device-plugin-for-inference-workload-in-kubernetes/)

**Comment by amybachir** [comment]
@dempti I built a custom cluster-autoscaler image by changing this [line](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/gpu/gpu.go#L27) to `ResourceNvidiaGPU = "k8s.amazonaws.com/vgpu"` instead and that resolved the issue.

I suggest that both resources `k8s.amazonaws.com/vgpu` and `nvidia.com/gpu` should be supported!

**Comment by dempti** [comment]
@amybachir thank you.
can you confirm me the lables and nodes along with the tags to pass on cluster autoscaler for the changes.

**Comment by dempti** [comment]
> @dempti I built a custom cluster-autoscaler image by changing this [line](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/gpu/gpu.go#L27) to `ResourceNvidiaGPU = "k8s.amazonaws.com/vgpu"` instead and that resolved the issue.
> 
> I suggest that both resources `k8s.amazonaws.com/vgpu` and `nvidia.com/gpu` should be supported!

@amybachir did you also notice any strange logs similar to this? This issue is observed when image built locally is added but not if the image provided by autoscaler itself is used.
```
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler I0913 18:58:35.419366       1 reflector.go:255] Listing and watching *v1.CSIDriver from k8s.io/client-go/informers/factory.go:134
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:35.422150       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:clusterautoscaler" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler I0913 18:58:41.321444       1 reflector.go:535] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.Service total 3 items received
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler I0913 18:58:41.585221       1 reflector.go:255] Listing and watching *v1beta1.CSIStorageCapacity from k8s.io/client-go/informers/factory.go:134
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:41.590418       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: csistoragecapacities.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:clusterautoscaler" cannot list resource "csistoragecapacities" in API group "storage.k8s.io" at the cluster scope

clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.189958       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.190017       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.190071       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.190128       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
```

**Comment by amybachir** [comment]
> @amybachir thank you.
> can you confirm me the lables and nodes along with the tags to pass on cluster autoscaler for the changes.

The node tags and labels look good to me!

**Comment by amybachir** [comment]
> > @dempti I built a custom cluster-autoscaler image by changing this [line](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/gpu/gpu.go#L27) to `ResourceNvidiaGPU = "k8s.amazonaws.com/vgpu"` instead and that resolved the issue.
> > I suggest that both resources `k8s.amazonaws.com/vgpu` and `nvidia.com/gpu` should be supported!
> 
> @amybachir did you also notice any strange logs similar to this? This issue is observed when image built locally is added but not if the image provided by autoscaler itself is used.
> 
> ```
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler I0913 18:58:35.419366       1 reflector.go:255] Listing and watching *v1.CSIDriver from k8s.io/client-go/informers/factory.go:134
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:35.422150       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:clusterautoscaler" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler I0913 18:58:41.321444       1 reflector.go:535] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.Service total 3 items received
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler I0913 18:58:41.585221       1 reflector.go:255] Listing and watching *v1beta1.CSIStorageCapacity from k8s.io/client-go/informers/factory.go:134
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:41.590418       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: csistoragecapacities.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:clusterautoscaler" cannot list resource "csistoragecapacities" in API group "storage.k8s.io" at the cluster scope
> 
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.189958       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.190017       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.190071       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
> clusterautoscaler-aws-cluster-autoscaler-7dfb6488dc-zlw4m aws-cluster-autoscaler E0913 18:58:44.190128       1 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"default\" not found" namespace="default"
> ```

Yes, I did notice similar errors in my cluster-autoscaler log. However, I haven't noticed any problems with scaling up or down so I'm pretending these errors don't exist for now haha.

**Comment by amybachir** [comment]
@dempti unrelated to this topic, have you found a way to log and monitor vgpu usage? I asked this question in [aws-virtual-gpu-device-plugin](https://github.com/awslabs/aws-virtual-gpu-device-plugin/issues/19) but I haven't heard back.

**Comment by dempti** [comment]
@amybachir you might be able to use this to fetch the metrics per vgpu
[link for benchmark](https://github.com/awslabs/aws-virtual-gpu-device-plugin/tree/master/benchmark)

I am working on this currently, so can update you regarding this about my findings.
If you find anyother methods that would be great to know.

**Comment by admiral-srinjoy** [comment]
So is building the custom autoscaler image the only option @dempti @amybachir any updates or recent changes
