### ISSUE TITLE
Add Support for AWS Virtual GPU Device Plugin

### ISSUE THREAD

**Issue by amybachir** [kubernetes/autoscaler#4320]
There is currently only support for Nvidia device plugin because the `ResourceNvidiaDevice` is hardcoded to one value `nvidia.com/gpu`.  https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/gpu/gpu.go#L27

When using [AWS Virtual GPU Device Plugin](https://github.com/awslabs/aws-virtual-gpu-device-plugin), this value is `k8s.amazonaws.com/vgpu`

![image](https://user-images.githubusercontent.com/19543576/132768109-dddc1583-e978-459f-a909-8450dc54ece1.png)

To add support for AWS Virtual GPU Device Plugin, `ResourceNvidiaDevice` should probably be made a list and add an entry for `k8s.amazonaws.com/vgpu`

I'm happy to create a pull request for this!

**Comment by bpineau** [comment]
I think that's also the issue hit by #4315 ; beside gpu.go it seems [this](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L368) would also benefit from an update.

Can AWS users still run either aws-virtual-gpu-device-plugin (exposing a `k8s.amazonaws.com/vgpu` nodes resource) or k8s-device-plugin (-> `nvidia.com/gpu` resource), or is the later abandoned?

Deferring to the maintainers on the appropriate approach (eg. hardcoded in gpu.go, or cloudprovider API a la GPULabel()).

**Comment by nikskiz** [comment]
There is a special note on GPU instance for AWS documented here:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#special-note-on-gpu-instances

**Comment by amybachir** [comment]
> There is a special note on GPU instance for AWS documented here:
> https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#special-note-on-gpu-instances

@nikskiz Thank you for the note! This doesn't resolve the issue. Even if you apply the instructions in the link you provided, this [condition](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/gpu/gpu.go#L104) will still fail because [ResourceNvidiaGPU](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/gpu/gpu.go#L27) has one value only that should match the allocatable label on the node.

**Comment by amybachir** [comment]
> I think that's also the issue hit by #4315 ; beside gpu.go it seems [this](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L368) would also benefit from an update.
> 
> Can AWS users still run either aws-virtual-gpu-device-plugin (exposing a `k8s.amazonaws.com/vgpu` nodes resource) or k8s-device-plugin (-> `nvidia.com/gpu` resource), or is the later abandoned?
> 
> Deferring to the maintainers on the appropriate approach (eg. hardcoded in gpu.go, or cloudprovider API a la GPULabel()).

@bpineau I don't believe Nvidia device plugin (-> `nvidia.com/gpu` resource) is abandoned. AWS developed the  [AWS Virtual GPU Device Plugin](https://github.com/awslabs/aws-virtual-gpu-device-plugin) to resolve a limitation in Nvidia device plugin related to not being able to share GPUs or request fractional GPUs ([reference](https://aws.amazon.com/blogs/opensource/virtual-gpu-device-plugin-for-inference-workload-in-kubernetes/)).

I suggest that cluster-autoscaler aws provider should support both resources `k8s.amazonaws.com/vgpu` and `nvidia.com/gpu`

**Comment by pd-kcarrasco** [comment]
I'm also hitting this issue but I'm using the [k8s-directx-device-plugin](https://github.com/aarnaud/k8s-directx-device-plugin) on Windows EKS nodes to be able to use the GPU in windows containers. `k8s-directx-device-plugin` gives me a `microsoft.com/directx` GPU resource. 

Also as far as I'm aware the nvidia device plugin and the nvidia container toolkit only work on Linux so this hardcoded device left Windows EKS with GPU users out in the cold.

**Comment by admiral-srinjoy** [comment]
Any updates on this has this been fixed

**Comment by xeviknal** [comment]
Hello! We are hitting the same issue here. How did you guys fix it?

**Comment by admiral-srinjoy** [comment]
@xeviknal not really this is the only way we got it fixed you could make instead of hardcoding this value reading it off the ASG tag and using that value instead

**Comment by xeviknal** [comment]
thanks @admiral-srinjoy for the quick answer. I believe the solution you propose it would fit very much.
Unfortunately, we don't have bandwidth in our little team to contribute with an implementation just now. Therefore, and because we needed to move quickly, we proceeded with a fork.
