### ISSUE TITLE
Migrate vertical-pod-autoscaler to k8s.io/klog/v2

### ISSUE THREAD

**Issue by mrueg** [kubernetes/autoscaler#4340]
**Which component are you using?**:

vertical-pod-autoscaler 

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently vertical-pod-autoscaler uses k8s.io/klog and most packages depending on vpa have moved on to k8s.io/klog/v2. 
Please migrate vpa to k8s.io/klog/v2 so the number of dependencies can get reduced. This is probably a good-first-issue for folks wanting to contribute.

**Describe any alternative solutions you've considered.**:
None

**Additional context.**:
None

**Comment by jbartosik** [comment]
@mallow111 

I took a look at the repo and I think there are a few uses of klog v1 left:

```$ grep "k8s.io/klog" $(find . -name '*.go'|grep -v vendor)|grep -v "v2"
./e2e/v1/e2e.go:	"k8s.io/klog"
./e2e/v1/recommender.go:	"k8s.io/klog"
./e2e/v1beta2/e2e.go:	"k8s.io/klog"
./e2e/v1beta2/recommender.go:	"k8s.io/klog"
./pkg/updater/main.go:	"k8s.io/klog"
./pkg/recommender/model/cluster_test.go:	"k8s.io/klog"
./pkg/recommender/main.go:	"k8s.io/klog"
```



Do you want to remove them? I think it'd be nice to fully switch before next release (#4404).

**Comment by mallow111** [comment]
@jbartosik  I can try to fix it in the next  few days.

**Comment by mallow111** [comment]
I guess we can close this one now.

**Comment by jbartosik** [comment]
Thank you :)
