### ISSUE TITLE
Cluster Autoscaler doesn't scale up empty ASGs with podTopologySpread

### ISSUE THREAD

**Issue by evansheng** [kubernetes/autoscaler#4362]
**Which component are you using?**:

Cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.18.3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version 1.17

</pre></details>

**What environment is this in?**:

AWS

**What did you expect to happen?**:
All ASGs we have in the cluster to scale normally, according to priority expander. (Though this bug would happen with any expander type chosen)

**What happened instead?**:
We found that empty ASGs weren't scaling up, even when they were the highest tier in the priority expander configmap ladder.

The Cluster Autoscaler logs were citing the empty ASG nodes weren't matching PodTopologySpread predicate constraints. However, the ASG chosen to scale up has the same availability zone (which we specified in our PTS spec), as the one cited as failing. An example log line is shown below

```
scale_up.go:284] Pod overprovisioned-pause-pod-general-57f645b766-2lk6x can't be scheduled on k8s-node-mesh-b-ea1-us-m5d12xl-asg-us-east-1b, predicate checking error: node(s) didn't match pod topology spread constraints; predicateName=PodTopologySpread; reasons: node(s) didn't match pod topology spread constraints; debugInfo=
.
.
priority.go:166] priority expander: k8s-node-mesh-b-ea1-us-c5ad12xl-asg-us-east-1b chosen as the highest available
priority.go:166] priority expander: k8s-node-mesh-b-ea1-us-c5ad16xl-asg-us-east-1b chosen as the highest available
scale_up.go:452] Best option to resize: k8s-node-mesh-b-ea1-us-c5ad12xl-asg-us-east-1b
```

**How to reproduce it (as minimally and precisely as possible)**:

Add empty ASG and node type to cluster, while using pod topology spread constraints on all workloads across availability zones. Add the new node type to the top of the priority expander configmap ladder, and observe the logs.
Every scale up will trigger log lines saying the new node type does not fulfill pod topology spread constraints and fall back to a lower priority ASG that is not empty.

**Anything else we need to know?**:

I traced through the code and found the underlying issue.
When Cluster Autoscaler looks at node groups to scale, it does one of two things to fill out a [nodeInfo](https://github.com/kubernetes/autoscaler/blob/39b10bf7a73183fc3f66a88444c8e94dad96ff98/cluster-autoscaler/cloudprovider/baiducloud/baiducloud-sdk-go/cce/cluster.go#L320) object to use in the clusterSnapshot

[Reference](https://github.com/kubernetes/autoscaler/blob/39b10bf7a73183fc3f66a88444c8e94dad96ff98/cluster-autoscaler/processors/nodeinfosprovider/mixed_nodeinfos_processor.go#L106-L134)
1. If there is an existing example of the nodeGroup in the cluster, it copies the nodeInfo with existing labels, annotations and daemonsets
2. If there is not (empty ASG), it populates the nodeInfo object from the ASG template from the cloud provider.

However, certain labels (including `topology.kubernetes.io/zone`) are [applied by kubelet](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone) after node start. This means that the empty ASG nodeTemplates don't have the zone label applied, and will never fulfill the pod topology spread constraint.

We have worked around this by adding the zone label manually to all of our ASG templates, but it is not very intuitive that this must be done in order to use cluster autoscaler with pod topology spread.

I believe a fix for this would be to add all kubelet `Well-Known Annotations and Taints` to the nodeInfo structs when populating them from ASG, as they should be static and determinable from each ASG.

**Comment by jutley** [comment]
We did some investigating and believe this is fixed in v1.22+. Prior to this version, only the deprecated topology labels (such as `failure-domain.beta.kubernetes.io/zone`) were supported. #4053 adds support for the new labels. Anyone affected by this issue can either upgrade to v1.22 (which should involve upgrade the Kubernetes clusters to v1.22 as well) or use the deprecated labels until upgrades are possible.
