### ISSUE TITLE
Cluster Autoscaler: unit tests not passing on 1.19 and 1.20

### ISSUE THREAD

**Issue by towca** [kubernetes/autoscaler#4368]
The recent Azure cherry-picks to 1.19 and 1.20 (#4356, #4355) broke the Cluster Autoscaler build. It wasn't caught by CI because Github Actions hadn't been backported to 1.19 and 1.20. I tried fixing it, and there are 2 issues:
* Undefined `FakeNodeReasonAnnotation` and `FakeNodeUnregistered`. I think backporting #4119 should solve this.
* Undefined `manager.RegisterNodeGroup`. This method replaced `manager.RegisterAsg` in a large PR #3717. I tried replacing `RegisterNodeGroup` with `RegisterAsg` in the code manually, but the test that uses it still doesn't pass.

Github Actions are now running on 1.20 and 1.19.

Please fix ASAP.

@feiskyer @marwanad @nilo19

**Comment by marwanad** [comment]
Fixed in #4371 and #4370.

Sorry about that!
