### ISSUE TITLE
Make ResourceLimiter memory representation consistent

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#438]
Our API accepts memory limits in gigabytes, kubernetes keeps memory in bytes and we store it internally in megabytes. We should decide on one approach (bytes I think?) and update the code accordingly.

This issue is a follow up after discussion with @mwielgus on #429.

cc: @aleksandra-malinowska @krzysztof-jastrzebski

**Comment by aleksandra-malinowska** [comment]
@mwielgus can you PTAL at #495?

**Comment by aleksandra-malinowska** [comment]
/remove-lifecycle stale

cc @mwielgus
