### ISSUE TITLE
Does cluster autoscaler considers Pod Topology Constraints while scaling nodes ?

### ISSUE THREAD

**Issue by sanyamjain22** [kubernetes/autoscaler#4383]
I am trying to scale my deployment such that pods are equally distributed in different availability zones with maxskew of 1. I used pod topology constraints to achieve the same. It works fine if resources are already available, however if scaling is required , CA doesn't follow these constraints. I couldn't find any documentation regarding the same. If CA doesn't follow these constraints, is there any other way i can achieve the same?

**Comment by kamilzzz** [comment]
I see you closed this issue right after.
Is this supported?
