### ISSUE TITLE
Cluster Autoscaler: Having resource "slack" without overprovisioning

### ISSUE THREAD

**Issue by ivanilves** [kubernetes/autoscaler#4384]
Hi dear community,

I humbly ask for your help :pray:  with the puzzle I can not solve myself:

Can Cluster Autoscaler have some resource "slack" to have excess nodes always available ​without [overprovisioning](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler) ?

Or it has a fixed dependency on having "Pending" status pods as a scale up trigger? :thinking: 

Just curious if we can provide some resource slack without having a "ballast" load running on cluster? :innocent: 

Thank you very much!

**Comment by MaciekPytel** [comment]
CA only support scaling-up based on Pending pods and it calculates how many nodes are needed by using embedded scheduler code to simulate scheduling of those pods. There is no formula there and so the result can't be easily tweaked using some metrics.
There were attempts in the past to support overprovisioning directly in CA, but the way to implement those was always to just simulate existence of more pending pods. Ultimately it was never implemented, as there was no clear benefit simulating pending pods based on a CRD or similar vs just creating low-priority overprovisioning pods.
