### ISSUE TITLE
1.19.2 Does not start without env AWS_REGION

### ISSUE THREAD

**Issue by vainu-lauri** [kubernetes/autoscaler#4389]
**Which component are you using?**:

eu.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.19.2

**What version of the component are you using?**:

v1.19.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS

**What did you expect to happen?**:
Upgrade from 1.19.1 to 1.19.2 to work with existing configuration.

**What happened instead?**:
The 1.19.2 crashes with following:
```
F1006 07:46:04.699353       1 aws_cloud_provider.go:353] Failed to get AWS Region: EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: EC2MetadataError: failed to make EC2Metadata request
        status code: 404, request id:
caused by: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from 1.19.1 to 1.19.2 and do not have `AWS_REGION` environment variable set.

**Anything else we need to know?**:
I think this is due to change introduced in https://github.com/kubernetes/autoscaler/pull/4127 which was cherry-picked to 1.19.2 (and others) in PR https://github.com/kubernetes/autoscaler/pull/4265

It seems that there is a bug with the current version of `github.com/aws/aws-sdk-go v1.28.2` in 1.19.2.

I tested the `GetCurrentAwsRegion()` with that and it indeed seems to fail with the same 404. Although a newer version like `github.com/aws/aws-sdk-go v1.40.57` works as it should.

This probably affects other releases of cluster-autoscaler as well.

**Comment by gjtempleton** [comment]
Hey, thanks for raising this.

With a bit of testing it appears this only affects the 1.19.2 release as the 1.20 and onwards release branches are using `v1.35.24` or newer of the AWS SDK due to the upstream Kubernetes dependencies being updated.

I'll see if we can get a PR in to update the SDK enough to resolve this for the 1.19 release branch.

/area provider/aws

**Comment by tyen-brex** [comment]
Hi, is there a tagged release with this fix?

**Comment by mdkent** [comment]
Bumping as well, hitting this crash while upgrading a cluster to 1.19.

**Comment by yas-tchristie** [comment]
Getting a similar issue as well, but I am getting a 401 - not a 404.
