### ISSUE TITLE
Switch azure clients to use non-legacy repo clients

### ISSUE THREAD

**Issue by marwanad** [kubernetes/autoscaler#4393]
The Azure packages utilize clients and packages off: k8s.io/legacy-cloud-providers/azure. 

We should switch those over to use: https://github.com/kubernetes-sigs/cloud-provider-azure now that the legacy packages aren't updated anymore.

/area provider/azure

**Comment by jbartosik** [comment]
Is this about cluster autoscaler?

**Comment by marwanad** [comment]
closed in #4494
