### ISSUE TITLE
VPA recommender tests and full vpa tests are failing

### ISSUE THREAD

**Issue by krzysied** [kubernetes/autoscaler#4396]
Tests grid links:
- https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-recommender
- https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-full

Failing tests:
- All expect "Checkpoints with missing VPA objects are garbage collected"

Failing since Jul 23 18:15:50

**Comment by jbartosik** [comment]
Fixed now.
