### ISSUE TITLE
Can VPA set mem/cpu limits proportional to Node's size

### ISSUE THREAD

**Issue by vakalapa** [kubernetes/autoscaler#4397]
**Which component are you using?**:
Vertical Pod Autoscaler 

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Can the VPA update limits of a pod based on the size of the Node,. If a cluster has multiple node pools with varying VM Size, instead of using the smaller limit fits all, it would be useful to have limit defined proportional to node's size 

Not sure if this is possible with today VPA design

**Comment by jbartosik** [comment]
Could you tell me more about your use case?

Generally it would be hard with current design. VPA sets requests when pod is starting, as a web hook. It doesn't know on which node a pod it's handling will end up.  It could be possible with DeamonSets.

Again I'd like to know more about your specific use case, maybe in a specific situation we can do something better.
