### ISSUE TITLE
Cluster-Autoscaler not scaling up nodes

### ISSUE THREAD

**Issue by PascalKu** [kubernetes/autoscaler#4400]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:

Component version:
latest, checked out myself from this repository

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Virtual machines, Ubuntu

**What did you expect to happen?**:

I expected to spin up at least one virtual machine from hetzner cloud provider

**What happened instead?**:

I received the following log messages and it seems that the given pools won't be adjusted.

```
I1016 13:16:57.710455   94228 leaderelection.go:248] attempting to acquire leader lease kube-system/cluster-autoscaler...
I1016 13:16:57.884848   94228 leaderelection.go:258] successfully acquired lease kube-system/cluster-autoscaler
W1016 13:16:58.107500   94228 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W1016 13:16:58.207366   94228 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
I1016 13:16:58.980033   94228 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I1016 13:16:59.483777   94228 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 503.707779ms
I1016 13:17:09.221899   94228 hetzner_node_group.go:426] Set node group draining-node-pool size from 0 to 0, expected delta 0
I1016 13:17:09.449034   94228 hetzner_node_group.go:426] Set node group pool1 size from 0 to 0, expected delta 0
W1016 13:17:09.751048   94228 clusterstate.go:432] AcceptableRanges have not been populated yet. Skip checking
W1016 13:17:09.751210   94228 clusterstate.go:432] AcceptableRanges have not been populated yet. Skip checking
I1016 13:17:20.396527   94228 hetzner_node_group.go:426] Set node group draining-node-pool size from 0 to 0, expected delta 0
I1016 13:17:20.555474   94228 hetzner_node_group.go:426] Set node group pool1 size from 0 to 0, expected delta 0
```

**How to reproduce it (as minimally and precisely as possible)**:

Just run the autoscaler component with the following parameters:

```
--cloud-provider=hetzner
--stderrthreshold=info
--nodes=1:10:CPX11:FSN1:pool1
--expander=random
```

**Anything else we need to know?**:

No...

**Comment by timbrd** [comment]
Same issue here

**Comment by Eerosal** [comment]
Same issue and similar logs. No servers are provisioned with min-servers setting.

**Comment by BlakeB415** [comment]
I'm experiencing this on the latest version too. Had to downgrade to 1.22.0.

**Comment by phaniops** [comment]
Same issue. Any solution yet?

**Comment by eigood** [comment]
You have to create a pod with correct affinity or tolerations, such that the autoscaler knows that something is pending to be scheduled.  It won't just add a node until there is at least a Pending pod.
