### ISSUE TITLE
AKS: Bumping minimum nodes doesn't create extra node

### ISSUE THREAD

**Issue by psibi** [kubernetes/autoscaler#4401]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

```
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.19.1
```

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"abd6c80a2a7ad2abb79ed250047b72580f96b7ca", GitTreeState:"clean", BuildDate:"2021-08-23T18:11:34Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AKS in Azure cloud

**What did you expect to happen?**:

Additional nodes getting spawned when CLI argument is updated for the container.

**What happened instead?**:

No additional nodes spawned.

**How to reproduce it (as minimally and precisely as possible)**:

Steps to reproduce:

- Create an AKS cluster with a single node pool. Give node count an arbitrary number for the node pool. For our case, let's assume that it as 5. But it can be any number.
- Let's deploy the autoscaler. Make sure to pass the following argument:

``` shellsession
- --nodes=5:8:aks-default-xxxxx-vmss
```

 Now let's say, if I edit the deployment to increase the minimum node by one:

``` shellsession
- --nodes=6:8:aks-default-xxxxx-vmss
```

I see that the old autoscaler pod is terminated and a new one comes. This is the logs I see:

``` shellsession
I1018 08:11:55.092203       1 azure_manager.go:562] Refreshed ASG list, next refresh after 2021-10-18 08:12:55.09219277 +0000 UTC m=+197.998521701
I1018 08:11:55.093198       1 static_autoscaler.go:402] No unschedulable pods
I1018 08:11:55.093252       1 pre_filtering_processor.go:66] Skipping aks-default-xxxxxx-vmss000004 - node group min size reached
I1018 08:11:55.093303       1 pre_filtering_processor.go:66] Skipping aks-default-xxxxxx-vmss000000 - node group min size reached
I1018 08:11:55.093354       1 pre_filtering_processor.go:66] Skipping aks-default-xxxxxx-vmss000001 - node group min size reached
I1018 08:11:55.093406       1 pre_filtering_processor.go:66] Skipping aks-default-xxxxxx-vmss000002 - node group min size reached
I1018 08:11:55.093451       1 pre_filtering_processor.go:66] Skipping aks-default-xxxxxx-vmss000003 - node group min size reached
```

Even though there are only 5 nodes presents, it says that `node group min size reached` inspite of bumping it to `6` from `5`. I believe it's not taking the value `6` passed as arguments into consideration. It seems to be taking the initial node count which was passed during the AKS cluster creation as the minimum node count instead. The above behaviour seems like a bug to me.

**Comment by marwanad** [comment]
This isn't specific to AKS but rather the autoscaler behaviour. It operates within the min/max boundaries but doesn't interfere to enforce the minimum count if you change it for whatever reason.

I can't speak to ASG because I think they might be bubbling down the minimum count to the native field on the ASG properties but that's pretty much the case with any cloudprovider.

If you're using the managed AKS autoscaler, the behaviour is different and this part is handled for you.

**Comment by marwanad** [comment]
AKS-managaed autoscaler handles the minCount bump transparently as of few months ago.

If self-managed, then this is a limitation from upstream that doesn't force a scale-up on min-count change.

/close
