### ISSUE TITLE
[VPA] New release?

### ISSUE THREAD

**Issue by endzyme** [kubernetes/autoscaler#4404]
Hi there! Looks like there's been some changes sitting in the VPA for a while now since the last release. Any idea on when the next release of VPA will be shipped?

**Comment by xiazhan** [comment]
@jbartosik @bskiba do we have any plan?  :)

**Comment by jbartosik** [comment]
Hi, I just want to let you know I noticed this. I'll check what's the situation and let you know what's our plan (once there is one).

**Comment by jbartosik** [comment]
Before cutting a new release I'd like to merge https://github.com/kubernetes/autoscaler/pull/4131 and https://github.com/kubernetes/autoscaler/pull/4425 (and probably other open PRs tagged with vertical pod autoscaler).

I expect I'll cut a new release branch from master in about a month. If you need something faster please let me know and we can talk.

**Comment by adriananeci** [comment]
Any updates/ETA when the new release will be cut? Should we expect a new release before New Year's Eve?

**Comment by jbartosik** [comment]
There are some more things I'd like to get in before release.

First we need to fix our E2E tests (#4557).
Then it would be good to fix #4537 which I suspect broke those E2E tests and get it in.
I also want to merge #4488.

We might also get a fix for #3986 but I'm not yet sure if we're going to wait for that. When we have other stuff in place I'll see how long we'd have to wait and decide.

**Comment by PhilippeChepy** [comment]
It could be nice to have releases on a regular basis (if e2e tests pass, of course).
Something like a release every 3 month for example.
Because the latest release is not perfect too and it's very old now.

WDYT?

**Comment by jbartosik** [comment]
> We might also get a fix for #3986 but I'm not yet sure if we're going to wait for that. When we have other stuff in place I'll see how long we'd have to wait and decide.

#4560 looks like it will implement this.

**Comment by jbartosik** [comment]
> It could be nice to have releases on a regular basis (if e2e tests pass, of course). Something like a release every 3 month for example. Because the latest release is not perfect too and it's very old now.
> 
> WDYT?

Yeah, [0.9.2](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.9.2) is almost a year old.

I'll think about what we can do to have more frequent releases (how frequently, should we have some automaton remind us about it, how strict do we want schedule to be (I think at first not very strict so we can see how it works and adjust)).

**Comment by jbartosik** [comment]
Another issue we might want to address before cutting a release: #4562

**Comment by jbartosik** [comment]
I want release next week.

@PhilippeChepy We pull in dependencies from K8s so I think in the future it makes sense to have a new minor release each time K8s makes a new release (I think current schedule is 3 a year) + patch releases in the mean time if there is a reason to. I'll try to do that and see how that turns out.

**Comment by jbartosik** [comment]
New release is available: https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.10.0
