### ISSUE TITLE
CA seems to use panic verbosity regardless of --v and then filling up the logs

### ISSUE THREAD

**Issue by mdaniel** [kubernetes/autoscaler#4433]
**Which component are you using?**:

* cluster-autoscaler

**What version of the component are you using?**:

Component version: v1.21.0

**What k8s version are you using (`kubectl version`)?**:

v1.19 and v1.21 although that isn't relevant for this bug report

**What environment is this in?**:

AWS

**What did you expect to happen?**:

Log messages without 39 lines of golang panic output

**What happened instead?**:

```console
$ docker run --rm k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0 /cluster-autoscaler --v=0
F1029 20:34:13.683988       1 main.go:278] Failed to build Kubernetes client configuration: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00013a001, 0xc000936120, 0xc9, 0x11d)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1021 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x629c5a0, 0xc000000003, 0x0, 0x0, 0xc0005d4150, 0x617da51, 0x7, 0x116, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:970 +0x1a3
k8s.io/klog/v2.(*loggingT).printf(0x629c5a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x3e81b6d, 0x33, 0xc0002899e0, 0x1, ...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:751 +0x18b
k8s.io/klog/v2.Fatalf(...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1509
main.getKubeConfig(0xc00079ea20)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:278 +0x494
main.main()
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:415 +0x382

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x629c5a0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:418 +0xdd

goroutine 15 [chan receive]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/exoscale/internal/k8s.io/klog.(*loggingT).flushDaemon(0x629c3c0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/exoscale/internal/k8s.io/klog/klog.go:1026 +0x8b
created by k8s.io/autoscaler/cluster-autoscaler/cloudprovider/exoscale/internal/k8s.io/klog.init.0
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/exoscale/internal/k8s.io/klog/klog.go:427 +0xd6

goroutine 16 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0006a8d70)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 42 [runnable]:
github.com/cespare/xxhash/v2.(*Digest).WriteString(0xc0000e2b60, 0x3e477e1, 0x24, 0x5, 0xc0000e2d78, 0xc00047edb8)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go:39 +0xa5
github.com/prometheus/client_golang/prometheus.NewDesc(0x3e477e1, 0x24, 0x3ecb627, 0x4b, 0xc0003a88a0, 0x1, 0x1, 0x0, 0x40cf78)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/prometheus/client_golang/prometheus/desc.go:133 +0x8a6
github.com/prometheus/client_golang/prometheus.NewCounterVec(0x0, 0x0, 0x0, 0x0, 0x3e477e1, 0x24, 0x3ecb627, 0x4b, 0x0, 0xc0003a88a0, ...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/prometheus/client_golang/prometheus/counter.go:172 +0xd6
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor(0x7f9d258d1108, 0xc0000e8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:89 +0xad
k8s.io/component-base/metrics/legacyregistry.Handler(0x3e0d483, 0x12)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/component-base/metrics/legacyregistry/registry.go:58 +0x9d
main.main.func1(0xc00029c320)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:395 +0x5a
created by main.main
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:393 +0x277
```

**How to reproduce it (as minimally and precisely as possible)**:

```sh
docker run --rm k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0 /cluster-autoscaler --v=0
```

**Anything else we need to know?**:

This bad behavior has been around for a while, it just seems to be buried in comments for other issues, but since we pay by the logging byte, this is a first-class bug for us

* https://github.com/kubernetes/autoscaler/issues/1321#issuecomment-430622483
* https://github.com/kubernetes/autoscaler/issues/4422#issuecomment-951997649
* and likely [a bunch more](https://github.com/kubernetes/autoscaler/issues?q=is%3Aissue+goroutine+running)

That command above was the shortest possible example of the bad behavior, but in reality the situation is much, much, much worse when running in-cluster but with invalid AWS credentials, since `cluster-autoscaler` emits panic-y trace at high velocity if `AWS_ROLE_ARN` or `AWS_WEB_IDENTITY_TOKEN_FILE` are wrong in any way yet it would be equally served with a simple, one line, error and not the War and Peace of every goroutine while at `--v=0` or similar

```
E1029 21:32:54.637676       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed fetching WebIdentity token: 
caused by: WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token
caused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: no such file or directory
F1029 21:32:54.637689       1 aws_cloud_provider.go:389] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed fetching WebIdentity token: 
caused by: WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token
caused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: no such file or directory
goroutine 48 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc005032000, 0x172, 0x314)
...
```
and that continues for 1,925 lines of text, of which only those top 4 of the `E1029` and `F1029` are in any way relevant

Aside from the sheer :money_with_wings: of logging at that verbosity, it also makes finding _the problem_ in that sea of text harder than necessary

**Comment by mb-qco** [comment]
Bump

**Comment by gjtempleton** [comment]
The two instances you've highlighted are the intended behaviour of the call made to `klog.Fatalf`: https://github.com/kubernetes/klog/blob/9ad246211af1ed84621ee94a26fcce0038b69cd1/klog.go#L1528-L1533

I think there's a valid conversation to be had about whether that's the behaviour we want in the AWS example, or whether we could handle this with (for instance) `klog.Exitf` instead, which would still give us the desired restart behaviour to potentially recover from a bad state with a pod restart.

**Comment by mdaniel** [comment]
Is that "intended behavior" because the code uses `Fatalf` and thus klog is doing what it was told, or "intended behavior" meaning the cluster-autoscaler emits panic traceback by design?

I would certainly value having that conversation about using `Exitf` instead, because (as mentioned) it makes finding the signal amongst the noise hard, in my experience

If there was such a thing as _(pseudocde)_ `klog.Verbosity(5).Fatalf` as they do in `kubectl --v` that would be stellar, then folks could opt-in to the whole story if they were thus inclined, but (again, as mentioned) it wasn't my experience that changing `--v` caused any alteration in that behavior
