### ISSUE TITLE
The log prints abnormally after the updater is configured with "--min-replicas=1"

### ISSUE THREAD

**Issue by klayscool** [kubernetes/autoscaler#4435]
My question：
I deployed Vertical Pod Autoscaler (master branch, version 0.9.2) in my cluster.
There is a statefulset in my business that only needs 1 pod to run, so I follow the demo from  FAQ  to make  the below configuration to the yaml of vpa-updater  "I get recommendations for my single pod replicaSet, but they are not applied. Why?" (link: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#i-get-recommendations-for-my-single-pod-replicaset-but-they-are-not-applied) 

<img width="664" alt="WechatIMG821" src="https://user-images.githubusercontent.com/41819795/139630599-0a480460-9432-490c-bd4b-52784199c4a5.png">

After the configuration is complete, the updater seems to work normally (it can recommend and update the resources configuration of the pod normally)

<img width="1478" alt="WechatIMG832" src="https://user-images.githubusercontent.com/41819795/139630700-23dcc204-b96e-4a6d-b7ce-d45cbf65c7c3.png">

But there is a problem with the updater log:

<img width="1081" alt="WechatIMG843" src="https://user-images.githubusercontent.com/41819795/139630772-e516ea18-de39-4a00-9a51-7ff1fbabb78d.png">

I didn't find more information about this in the document, could you please kindly recommend ?  Thanks in advance. 

**Which component are you using?**:
vertical-pod-autoscaler

**What version of the component are you using?**:
0.9.2

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.18.4
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.18.4
</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

Print log normally
**What happened instead?**:

The updater log shows that the vpa objects cannot be recognized
W1101 02:26:16.161274       1 updater.go:153] no VPA objects to process
**How to reproduce it (as minimally and precisely as possible)**:
Follow https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#i-get-recommendations-for-my-single-pod-replicaset-but-they-are-not -applied Configure "--min-replicas=1" to the updater.

**Anything else we need to know?**:
I found 3 clusters(1.18.4) for testing, all of them must be present

Thanks

**Comment by jbartosik** [comment]
Did you create VPA objects in the cluster?

You can check that with:

```
kubectl get vpa --all-namespaces
```

[This](https://github.com/kubernetes/autoscaler/blob/a87e70cde0c68f13ed2022156dbd0cd711a00741/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L153) is the line which writes the log you're seeing. It triggers when updater sees no VPA objects with update mode `Auto` or `Recreate`.

The document you linked doesn't include instructions for creating a VPA object (only for starting VPA pods).

**Comment by klayscool** [comment]
Hello～

There is VPA objects in my cluster, as shown in the figure:
![image](https://user-images.githubusercontent.com/41819795/141268462-0201bc1f-f530-41ba-b8cd-95012f5ca40b.png)

And in my question above, the second picture is that the pod given to me by vpa upater has updated resources (you can see from annotations:), so I guess vpa-upater is working normally, but the log looks a little bit abnormal.
![image](https://user-images.githubusercontent.com/41819795/141269916-0b164154-b052-45f2-b188-6552990c95bc.png)
