### ISSUE TITLE
Metric for counting pods that remain unschedulable after attempting to scale up

### ISSUE THREAD

**Issue by richerve** [kubernetes/autoscaler#4437]
**Which component are you using?**:

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

The cluster-autoscaler(CA) currently publishes a metric for `unschedulable_pods_count`. This is a flat count of all unschedulable pods. We believe that there are two distinct categories of unschedulable pods:

1. Pods that cannot be scheduled on any node groups regardless of group capacity.
2. Pods that would normally be scheduled on at least one node group but cannot be due to capacity constraints.

These two classes of pod are different in that case 2. is normally scheduleable but cannot be due to cluster size. Case 1 will never be scheduled without the addition of new node groups the pod tolerates or the requests fit on. We believe these are different classes because in case 2., the work would have previously been scheduled and not because of reasons under the workloads control, but in case 1. if the pod would have never fit on any node group, it seems like a misconfiguration by the workload author.

Without this distinction it's difficult to use the `unschedulable_pods_count` reliably in a multi-tenant cluster without adding all the noise of badly configured deployments.

**Describe the solution you'd like.**:

A metric that counts pods that remain unschedulable after attempting to scale up with a catetory label for each of the described categories.

**Describe any alternative solutions you've considered.**:

Having custom tooling to query AWS ASG (if that's the cloud used) and k8s to understand cover the conditions explained above, but we think this kind of information pertains to the cluster-autoscaler as it's what it handles all cloud and k8s calls.

**Comment by richerve** [comment]
@jbartosik is there any interest on this?

**Comment by jbartosik** [comment]
I'm working on VPA. @MaciekPytel please take a look
