### ISSUE TITLE
Scale down to zero in ASG

### ISSUE THREAD

**Issue by kishore0709** [kubernetes/autoscaler#4439]
Hi Team,

I'm using EKS with ASG managed worker nodes and are using cluster autoscaler for nodes scale-in and scale-down.

Currently I'm looking for scale down to zero solution for decreasing the GPU worker nodes cost.
I made the ASG changes like min size to 0 in terraform eks module and we can't set the desired capacity to zero as it is managing by the cluster autoscaler. 

Please help how to achieve this scale down to zero using when there is no load on the machine.

Thanks!
Kishor.

**Comment by mbevc1** [comment]
Not a really a GA yet, but might be worth giving it a go: https://github.com/awslabs/karpenter
I've been using it for a bit and works great.

**Comment by gjtempleton** [comment]
Hi there, can I ask what you mean by:

```I made the ASG changes like min size to 0 in terraform eks module and we can't set the desired capacity to zero as it is managing by the cluster autoscaler.```

The cluster autoscaler supports scaling from 0 in ASGs, if this isn't working as expected due to the CA, it's a bug. You can see more information on the scale to zero support and gotchas to be aware of here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0

/area provider/aws

**Comment by kishore0709** [comment]
Hi,

I'm using aws ASG worker nodes(not nodegroup) and I'm managing eks cluster
using terraform module.

I tried to achieve scale down to zero solution by making asg min size as 0
and i can't make desired count to 0 as  we are using cluster autoscaler for
scaling operations. So here I'm looking how to implement scale down to zero
solution for worker nodes using Cluster autoscaler.

Please help me in achieving that

Thanks!
Kishor.

**Comment by kishore0709** [comment]
@gjtempleton 

Any inputs, please.

Thanks!
Kishor.

**Comment by varkey** [comment]
@kishore0709 If there are pods already scheduled on that node, then it will be scaled down only if the scale down conditions / thresholds are reached. If you want only certain workloads to use the GPU worker nodes, you need to add the appropriate taint on the node, and configure your workload with the right node-selectors and tolerations. This way when workload which needs the GPU worker nodes are removed, CA will automatically scale down the node as it would no longer be necessary. 

If you want do not want to use GPU nodes any more, remove that worker group configuration or set `min` and `max` to `0`

**Comment by imcom** [comment]
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0 is a bit out dated, although the configuration example is still working with latest cluster autoscaler. But the new configuration is available as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
