### ISSUE TITLE
How does cluster autoscaler calculate the node utilization

### ISSUE THREAD

**Issue by SteveL1** [kubernetes/autoscaler#4440]
I've noticed that even though the CPU usage for our EKS nodes is fairly low when I look on bit the AWS console and on kubectl top node (less that 40%) CAS is reporting CPU usage to be ~0.9.

This is leading to some unexpected scaling of the cluster.

I thought the a utilization of 1 would indicate that all resources were exhausted, is that not the case?

I'm using cluster-autoscaler.v1.22.1 on EKS 1.21

**Comment by gjtempleton** [comment]
The CA doesn't operate on raw utilisation of the CPU or Memory of nodes, instead, it calculates utilisation based on the resource requests of all the pods scheduled on a node. You can see more detail here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work

**Comment by SteveL1** [comment]
Ah, it's based on resource requests.  It makes sense now!

Thanks for your reply :)

**Comment by gjtempleton** [comment]
Assuming this is resolved.

/close
