### ISSUE TITLE
Pod in CrashLoopBackOff state due to container failure

### ISSUE THREAD

**Issue by seunggs** [kubernetes/autoscaler#4446]
**Which component are you using?**:

Using helm chart to install Cluster Autoscaler on aws eks cluster (but the same issue seems to happen if I follow the aws docs instructions without helm: https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html)

**What version of the component are you using?**:

helm chart version 9.10.8 and app version 1.21.1

Component version:

kubernetes version 1.21

**What environment is this in?**:

aws eks with managed node groups

**What did you expect to happen?**:

Cluster Autoscaler runs on eks cluster after following the helm installation instructions

**What happened instead?**:

The pod is in CrashLoopBackOff state due to container failure

**How to reproduce it (as minimally and precisely as possible)**:

Set up eks managed node groups (with t3.medium and 3 replicas) and install Cluster Autoscaler using helm charts (using aws instructions)

**Anything else we need to know?**:

I'm not using any resource limits and seeing this:

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  10m                  default-scheduler  Successfully assigned kube-system/cluster-autoscaler-release-aws-cluster-autoscaler-6d58fb855g84x to ip-10-0-16-212.us-west-1.compute.internal
  Normal   Pulled     10m                  kubelet            Successfully pulled image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1" in 368.005529ms
  Normal   Pulled     10m                  kubelet            Successfully pulled image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1" in 350.720347ms
  Normal   Pulled     9m43s                kubelet            Successfully pulled image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1" in 368.7982ms
  Normal   Created    9m (x4 over 10m)     kubelet            Created container aws-cluster-autoscaler
  Normal   Pulling    9m (x4 over 10m)     kubelet            Pulling image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1"
  Normal   Pulled     9m                   kubelet            Successfully pulled image "k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1" in 359.88954ms
  Normal   Started    8m59s (x4 over 10m)  kubelet            Started container aws-cluster-autoscaler
  Warning  BackOff    31s (x44 over 10m)   kubelet            Back-off restarting failed container
```

Here's the container logs (this goroutine message repeats forever):

```
goroutine 301 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc000908b40, 0x0)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000908b30)
        /usr/local/go/src/sync/cond.go:56 +0x9d
golang.org/x/net/http2.(*pipe).Read(0xc000908b28, 0xc000266400, 0x200, 0x200, 0x0, 0x0, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/pipe.go:65 +0x8f
golang.org/x/net/http2.transportResponseBody.Read(0xc000908b00, 0xc000266400, 0x200, 0x200, 0x0, 0x0, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc000908f20, 0xc00103e9e0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc000908f20, 0x0, 0x0, 0x36423c0)
        /usr/local/go/src/encoding/json/stream.go:140 +0x1e8
encoding/json.(*Decoder).Decode(0xc000908f20, 0x36e3ec0, 0xc00103e9e0, 0x3c0c180, 0x0)
        /usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc00105daa0, 0xc00095a400, 0x400, 0x400, 0x10, 0x37d1a20, 0x38)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x1a1
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc001056730, 0x0, 0x44ebba0, 0xc0008279c0, 0xc000ed1f98, 0x15b916f, 0xc000ed1e60, 0x453c8e0, 0xc000058018)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc00103e9c0, 0x3deeb27, 0x1, 0x0, 0x0, 0x0, 0x1f4)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000827980)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:105 +0xe5
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:76 +0xea
```

I'm not sure how to start debugging this?

**Comment by seunggs** [comment]
This was caused by the incorrect AWS role trust policy - would've been a bit easier to debug if there were helpful error messages but my fault for not following the aws instructions carefully.

Closing.

**Comment by b1n9s** [comment]
My case is using the wrong version

Better to [match the minor version of CA and the cluster](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases)

**Comment by CoatedMoose** [comment]
I had this issue when I upgraded to kubernetes 1.24 My issue was also with the IAM policy, but it's because the [setup instructions from aws](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#cluster-autoscaler) missed a key permission.

There are instructions to set this on the policy.

```
"autoscaling:DescribeAutoScalingInstances",
"autoscaling:DescribeAutoScalingGroups",
"ec2:DescribeLaunchTemplateVersions",
"autoscaling:DescribeTags",
"autoscaling:DescribeLaunchConfigurations"
```

 The mention for requiring `eks:DescribeNodegroup` is buried mid-paragraph a bit down the page (but _is_ there):
 
 > [...] This feature requires that you add the `eks:DescribeNodegroup` permission to the Cluster Autoscaler service account IAM policy. [...]

But that page doesn't mention `ec2:DescribeInstanceTypes` - I discovered that requirement from [this other issue](https://github.com/kubernetes/kops/pull/13532).

**Comment by karlroberts** [comment]
follow up from @CoatedMoose 's correct answer (thanks @CoatedMoose ) :- the `ec2:DescribeInstanceTypes` requirement is now shown in AWS's [Amazon EKS / Autoscaling page](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#ca-create-policy)  but it is not mentioned in the [kubernetes versions page](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.24) like it does for `eks:DescribeNodegroup`.  

make sure you have both permissions as well as the others in [the autoscaling page](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#ca-create-policy)
