### ISSUE TITLE
Helm chart PodDisruptionBudget using deprecated API

### ISSUE THREAD

**Issue by technotaff-nbs** [kubernetes/autoscaler#4450]
**Which component are you using?**:

Cluster-Autoscaler Helm Chart

**What version of the component are you using?**:

cluster-autoscaler-chart-9.10.8

Component version:

1.21.1

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

EKS 1.21

**What did you expect to happen?**:

PodDisruptionBudget should be using current API "policy/v1"

**What happened instead?**:

PodDisruptionBudget should be using current API "policy/v1beta1"

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/kubernetes/autoscaler/blob/821d6771b0222d3d84a76717065db4f53e3ea026/charts/cluster-autoscaler/templates/pdb.yaml#L2

**Anything else we need to know?**:

There is a simple workaround for this, using the common APIVersions pattern in your Helm chart:

{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{ end -}}

The schema of the resource hasn't changes significantly between v1beta1 and v1

**Comment by steven-esser** [comment]
This is still an issue.

**Comment by richardFontaine** [comment]
For anyone else who sees this, it was fixed in 9.18.1 https://github.com/kubernetes/autoscaler/commit/b57d917632e048bbe15e47d8a6084b8fd8a5919c
