### ISSUE TITLE
Cluster autoscaler views all nodes in the cluster as empty and beings bulk deleting them

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes/autoscaler#446]
This caused a cluster meltdown for us and unfortunately, we don't have enough data to exactly know what happened at that point. This was seen in the v0.5.4 release.

Also after we upgraded to 0.6.2, we saw log messages like 
```
I1025 18:52:49.810360       1 scale_down.go:156] Node ip-172-27-190-244.us-west-2.compute.internal - utilization 0.000000
I1025 18:52:49.810365       1 scale_down.go:156] Node ip-172-27-190-60.us-west-2.compute.internal - utilization 0.000000
I1025 18:52:49.810371       1 scale_down.go:156] Node ip-172-27-186-53.us-west-2.compute.internal - utilization 0.000000 
```
This happened for ~5s and then non-zero the utilization numbers started to show up. 

Were there any other reports of such behaviour from the cluster-autoscaler. If so, were there any specific changes targetting this either in 0.6.2 or the next release?

**Comment by ashish-amarnath** [comment]
From looking at the available flags, the following may be useful.
`max-graceful-termination-sec`, `max-empty-bulk-delete` and `scale-down-unneeded-time`
However, if the CA sees the nodes as empty then I don't think these flags can rescue the cluster nodes.

**Comment by mwielgus** [comment]
In the 0.6 scenario that you describe CA probably failed to fully sync the list of pod in time and started the first iteration with an empty list which got synced just afterwards. As the requirement for node deletion is 10 min of being under-utilised there is nothing to worry about.

As of 0.5 meltdown - without any logs or detailed description I'm unable to tell what happened.

**Comment by ashish-amarnath** [comment]
The 0.6 scenario isn't that big a cause of concern after looking at the code-the difference in how empty nodes and underutilized nodes are handled. 
On the 0.5 incident, I see this in the 0.6.1 release notes. Looking at the commit with this change for this would be awesome. Could you please point me to that commit? 
![ca-0 6 1-release-note](https://user-images.githubusercontent.com/22872138/32381847-f931bf96-c070-11e7-96bb-d19c0911c72f.png)

**Comment by MaciekPytel** [comment]
I think this part of release notes is referring to https://github.com/kubernetes/autoscaler/pull/202, which doesn't seem related to your problem (it fixes the problem with CA deleting empty nodes slower than intended).

AFAIK we haven't had any similar reports regarding CA and without a log or at least the list of nodes and pods at the time of 0.5.4 incident we don't even know if the CA was the source of the problem or not.

**Comment by ashish-amarnath** [comment]
Closing this issue.
