### ISSUE TITLE
how can use vpa  scale all the deployment within in a namespace?

### ISSUE THREAD

**Issue by tanguofu** [kubernetes/autoscaler#4460]
**Which component are you using?**:
vpa

vpa
**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

**Describe the solution you'd like.**:
we have lots of deployment  in the k8s, if every deployment write a VerticalPodAutoscaler CRD, its very hard to maintain。

can we use single VerticalPodAutoscaler CRD to scale all the deployment in the namespace?

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by tanguofu** [comment]
any one here？

**Comment by jbartosik** [comment]
Hi,
currently VPA supports only configuring it for each controller individually.

Using single VPA object to control multiple controllers requires significant API changes.

I'm not working on this currently but I'm happy to learn more (and contributions are always welcome).

Could provide some more details on what problems you see with maintaining a VPA object for each of your deployments?

**Comment by ctrought** [comment]
> any one here？

Sounds like this would accomplish what you want, all you have to do is label the namespace and it will create and manage VPA instances for all workloads (that you permit it to).

https://github.com/FairwindsOps/goldilocks

**Comment by SamSpiri** [comment]
You can try deploying this operator to automatically create VPA for all deployments in a namespace

https://github.com/SamSpiri/autovpa
