### ISSUE TITLE
CA suddenly tries to scale-up from min nodes instead of current node count on the VMSS node group

### ISSUE THREAD

**Issue by mdahamiwal** [kubernetes/autoscaler#4462]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
helm version 1.4.1

helm version 1.4.1

Component version:

**What k8s version are you using (`kubectl version`)?**:
v1.21.3

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T23:45:37Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
Azure VMSS

**What did you expect to happen?**:
CA should maintain the scale of the VMSS pool.

**What happened instead?**:

CA abruptly scaled down the agent pool of the cluster and remained in the same state for around 1/2 hour before correcting the scale. This led to all the running pods go into pending state for that time. There was no significant traffic spike or drop during this time which would cause this.

 It also auto-recovered and corrected the state.

CA somehow read the incorrect current usage and pod state incorrectly.

**How to reproduce it (as minimally and precisely as possible)**:
We are not sure how to reproduce this consistently. For the most part the CA runs as expected, but we have seen some rare occurrences of the same issue across multiple clusters without any noticeable traffic spike or drop.
 

**Anything else we need to know?**:

cluster autoscaler configuration: 

    Args:
      --v=3
      --logtostderr=true
      --cloud-provider=azure
      --cloud-config=/etc/kubernetes/azure.json
      --skip-nodes-with-local-storage=false
      --ignore-daemonsets-utilization
      --nodes=10:480:k8s-defpool1-36836756-vmss

Logs emitted:

![vmss_autoscaler](https://user-images.githubusercontent.com/12109362/141385171-ecaf5e63-6d47-4d1c-a804-d96b102df614.PNG)

**Comment by marwanad** [comment]
@mdahamiwal what CA version are you using? and where there unregistered node removal attempts before that kicked in?

**Comment by mdahamiwal** [comment]
@marwanad Yes, there were 2-3 unregistered node removal attempts running for a long time. Still doesn't explain why removal attempts for other 2 nodes would cause this miscalculation. Let me test the 1.21.1 version.

**Comment by marwanad** [comment]
@mdahamiwal 
If the cache kept decrementing for every removal attempt, you'll end up in this state. Keep me posted with the results. If you're able to reproduce this regularly, I'd be curious to take a look at the verbose(maybe v(5)) logs.

**Comment by mdahamiwal** [comment]
@marwanad I suspect there is something else (some weird bug) hidden in the calculation logic. We noticed this happening only once so far in some of our clusters in different regions. Also, the removal attempt was only for 3 nodes out of 75 nodes that the node group had before this issue. The weird part is it suddenly emits a plan to scale from 10 -> 11 nodes, 10 being our minimum setting passed to the CA arguments.  I'm attaching all the logs between the timestamps when the cluster was running healthy (73->74) and the first time we see (10 -> 11) scale plan. We also confirmed the the VMSS API team that there was no issue at their end and it was CA that triggered the drastic scale down in the capacity. Could you please take a look?
[autoscaler_logs.csv](https://github.com/kubernetes/autoscaler/files/7531612/autoscaler_logs.csv)

**Comment by marwanad** [comment]
@mdahamiwal please keep me posted on whether the fix addresses the issue for good. I am planning on adding more logs around the cache and cache refreshes with the capacity deals. My other theory would be stale data returned from the API. I think it's likely the CA bug though.

**Comment by marwanad** [comment]
/area provider/azure

Closing this for now but feel free to reopen if that above hasn't fixed your issue.

/close
