### ISSUE TITLE
possible to upgrade aws-sdk-go tp v1.8x?

### ISSUE THREAD

**Issue by etsangsplk** [kubernetes/autoscaler#447]
Looks like we are stil using v.1.6.10.... possible to update to v1.8.x?

**Comment by etsangsplk** [comment]
Never mind.
There is another issue on main k8s:
https://github.com/kubernetes/kubernetes/issues/54032
with Pr alreay merged to k8s
https://github.com/kubernetes/kubernetes/commit/e93b049be07c8c3a5ad6b11e79c6979e2ebab2d6

**Comment by mwielgus** [comment]
We will update all deps with the 1.9 release. CA deps are driven by K8S.
