### ISSUE TITLE
AWS EKS 1.21.2 cluster-autoscaler Failed to regenerate ASG cache ARN is invalid

### ISSUE THREAD

**Issue by orcutt989** [kubernetes/autoscaler#4471]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 1.21.1

**Kubernetes Version**: 1.21.2-eks-0389ca3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: Normal logs

**What happened instead?**:
```
I1116 19:10:37.306610       1 aws_cloud_provider.go:384] Successfully load 479 EC2 Instance Types [c5a.2xlarge m6gd.medium m5d.4xlarge c6gn.medium m5n.12xlarge i3en.12xlarge t3a │
│ E1116 19:10:37.466104       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials                        │
│ caused by: ValidationError: Request ARN is invalid                                                                                                                                │
│     status code: 400, request id: b59ed02f-1611-49d6-805a-c533eeed516e                                                                                                            │
│ F1116 19:10:37.466134       1 aws_cloud_provider.go:389] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials                   │
│ caused by: ValidationError: Request ARN is invalid
```

**How to reproduce it (as minimally and precisely as possible)**:

I followed https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

**Additional Information**: cluster-autoscaler pod is in CrashLoopBackoff

Service Account Description
```
│ Name:                cluster-autoscaler                                                                                                                                           │
│ Namespace:           kube-system                                                                                                                                                  │
│ Labels:              k8s-addon=cluster-autoscaler.addons.k8s.io                                                                                                                   │
│                      k8s-app=cluster-autoscaler                                                                                                                                   │
│ Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:policy/AmazonEKSClusterAutoscalerPolicy                                                                │
│ Image pull secrets:  <none>                                                                                                                                                       │
│ Mountable secrets:   cluster-autoscaler-token-dp62x                                                                                                                               │
│ Tokens:              cluster-autoscaler-token-dp62x                                                                                                                               │
│ Events:              <none>
```

**Comment by jeffqumata** [comment]
+1 on this with 1.21.5 on AWS China..
```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
Are there any workarounds? Its a pretty big issue

**Comment by jeffqumata** [comment]
Doing some more digging on this and I have the same issue on an otherwise identical cluster but with v.1.20.11

```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

I'm beginning to think my issue is caused by the cluster being in China

**Comment by jonmchu** [comment]
Is there any resolution to this issue? I'm running into a similar problem following the same guide

**Comment by sagarhonnungar** [comment]
The value for `eks.amazonaws.com/role-arn` annotation is incorrect. It is referring to an IAM policy, not an IAM role. You can set it to the correct role ARN using `kubectl annotate serviceaccount cluster-autoscaler   -n kube-system  --overwrite <correct-role-arn>`
