### ISSUE TITLE
cluster autoscaler 1.16.5 does not support Standard_E20s_v3 instance type in Azure

### ISSUE THREAD

**Issue by jatin-pathangi** [kubernetes/autoscaler#4472]
**Which component are you using?**: Cluster autoscaler 1.16.5

**What version of the component are you using?**: 1.16.5

Component version:

**What k8s version are you using (`kubectl version`)?**: 1.16.12

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:Azure

**What did you expect to happen?**: Autoscale the VMSS as expected

**What happened instead?**: Error message from autoscaler 
```
 Unable to build proper template node for <VMSS>: instance type "Standard_E20s_v3" not supported
```

**How to reproduce it (as minimally and precisely as possible)**: Create a vmss with Standard_E20s_v3 and add it to autoscaler.

**Anything else we need to know?**: The Standard_E20s_v3 is part of the instance_types.go file in release 1.16 https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.16/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go#L1093. I expect this behavior to work in 1.16.5. What is the reason it doesn't?

**Comment by gjtempleton** [comment]
That instance type wasn't included in a cut release of the Cluster Autoscaler until 1.16.7.

[Here's the file as of the tag you're using](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.16.5/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go), with no `Standard_E20s_v3` data.

[Here's the file as of the 1.16.7 release](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.16.7/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go#L1093-L1097), with the `Standard_E20s_v3` data.

Closing as expected.
