### ISSUE TITLE
support AWS "Instance type requirements"

### ISSUE THREAD

**Issue by garrygerber** [kubernetes/autoscaler#4479]
**Which component are you using?**: 

Cluster-Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

AWS added a new way of specifying instance types wanted.
they do this by specifying a set of instance characteristics - requirements.
which obsolete the need of specifying instance types, and in turn, breaks the CA when fetching the ASG info

**Describe the solution you'd like.**:

CA needs to support not knowing which instance type is used by the ASG

**Describe any alternative solutions you've considered.**:

CA will reed all the instance requirements from the ASG and calculate which instance type ASG will use when needed

**Additional context.**:

using CA v1.22.1 , error is:
`E1128 15:47:36.224041       1 static_autoscaler.go:286] Failed to get node infos for groups: ASG "......." uses the unknown EC2 instance type ""`

new settings in console looks:
<img width="1093" alt="Screen Shot 2021-11-28 at 17 50 31" src="https://user-images.githubusercontent.com/15626345/143775494-f9d87f81-a3f2-47f0-8a12-0608434f14c0.png">

**Comment by gjtempleton** [comment]
/area provider/aws

Hey, thanks for the suggestion. When raising feature requests like this, it helps us a huge amount if you fill out the answers to the questions in the [feature request issue template](https://github.com/kubernetes/autoscaler/issues/new?assignees=&labels=kind%2Ffeature&template=feature_request.md&title=) including linking to any relevant external documentation.

**Comment by garrygerber** [comment]
Hey @gjtempleton, it would help a lot if you can point me to the lines of code that handle the following logics:
- request for Auto Scaling Group details
- calculation of required resources and scaling the ASG accordingly

Thanks!

**Comment by AustinSiu** [comment]
@garrygerber thank you for opening the issue! I've submitted a PR to help address this issue.

**Comment by eptiger** [comment]
Good news @garrygerber  - a PR was just accepted a few days ago for supporting Instance Requirements: https://github.com/kubernetes/autoscaler/commit/fed54b5715c33a12c1f76cc3cc8a3e5b2fa6a73b
