### ISSUE TITLE
Cluster Autoscaler does not interpret labels specified with `k8s.io/cluster-autoscaler/node-template/label/*` tags on an AWS ASG unless those tags are set to propagate to the instances

### ISSUE THREAD

**Issue by adamnovak** [kubernetes/autoscaler#4490]
**Which component are you using?**:

`cluster-autoscaler`

**What version of the component are you using?**:

Component version:  `v1.17.3`

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

We're deploying nodes on Amazon AWS with Autoscaling Groups, using the cluster autoscaler's ability to automatically pick up ASGs tagged weith certain tags

**What did you expect to happen?**:

I expected the cluster autoscaler to read the tags of the ASG to determine what the tags on nodes that the ASG produces will be, when scaling from 0. I don't expect the value of the "Tag new instances" toggle on the tag to matter here.

In particular, I expect that if I tag an ASG with `k8s.io/cluster-autoscaler/node-template/label/eks.amazonaws.com/capacityType` with value `SPOT`, and don't set the tag to propagate to instances, then the cluster autoscaler will make a hypothetical node that will match a `nodeSelector` of `eks.amazonaws.com/capacityType: SPOT`.

(Note that I'm not using EKS here, just the label values they define, since Kubernetes itself has no standard for labeling or tainting preemptible nodes.)

**What happened instead?**:

When the labeling tag was set to not propagate to nodes, I got log messages like:

```
I1130 18:29:45.793842       1 pod_schedulable.go:165] Pod adamnovak-spot-pi-qsd9c can't be scheduled on cg-kubernetes-r5ad.8xlarge-spot, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't match node selector,
```

When I changed the tag to propagate to new instances, then I got a different error (because I'd misspelled my ephemeral storage limit tag):

When I fixed that tag, then the autoscaler started provisioning my node.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a working autoscaling group with the cluster autoscaler.
2. Scale it down to 0.
3. Give it a tag that starts with `k8s.io/cluster-autoscaler/node-template/label/`, and specifies a unique label, but set it not to propagate to nodes. (Also, optionally configure the node to really have that label when it comes up.)
4. Launch a pod that has a `nodeSelector` to match that label.
5. Note that the autoscaler won't try to scale up the ASG, because it thinks the node won't have the label that the tag says it will have.
6. Check the tag new instances checkbox on the tag on the ASG.
7. Wait for the autoscaler to reread the ASGs
8. Observe the autoscaler trying to scale up the ASG to run the pod.

**Anything else we need to know?**:

I suspect taints and other stuff inferred from tags also work this way.

This might be a possible cause of people reporting they are affected by https://github.com/kubernetes/autoscaler/issues/4010 and https://github.com/kubernetes/autoscaler/issues/3802, even though the screenshots I've seen there indicate that the tag new instances flags are set by the main reporters.

**Comment by acalm** [comment]
I think this was "kind of" documented in an [example before](https://github.com/kubernetes/autoscaler/pull/2929/commits/f7f50d901aedcc5dd4ae07147d7dd047fa1633bc), it was later [replaced](https://github.com/kubernetes/autoscaler/commit/87dfbf8fc6239cbebc39d58be709337c7c7ed4cc) with some recommendations. Not sure if that means that the behavior was fixed between those commits or if it's just unfortunate that the example got removed.

**Comment by EHJ-52n** [comment]
@adamnovak Is this issue solved for you?

**Comment by adamnovak** [comment]
I've been employing the workaround of always setting the tags to propagate, and I'm not likely to find time to try and reproduce this again on our live system any time soon.

As for documenting that setting the tags to propagate is necessary, it looks like @acalm found where in the docs that would belong, so I think you could look there in the current mainline to see if it has been documented yet.
