### ISSUE TITLE
Cluster Autoscaler patch releases

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#4496]
Hi! I want to cut new Cluster Autoscaler patch releases for 1.20-22 next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

Tagging cloud provider owners for visibility:
@ringtail @Jeffwan @jaypipes @gjtempleton @feiskyer @nilo19 @marwanad @hello2mao @davidjumani @enxebre @elmiko @hardikdr @detiber @andrewsykim @MorrisLaw @kevin-wangzefeng @RainbowMango @avorima @ellistarn @tghartland @d-mo @detiber @deitch @displague @gianarb

**Comment by elmiko** [comment]
nothing from me, thanks @MaciekPytel

**Comment by MaciekPytel** [comment]
1.20.2, 1.21.2, 1.22.2 have been released.
