### ISSUE TITLE
Cascading expanders doesn't work

### ISSUE THREAD

**Issue by AndrewFarley** [kubernetes/autoscaler#4504]
Installed the latest release via Helm Chart, `k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.1`, would like to use cascading expander which it says in the [FAQ is possible](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders)...
```
Multiple expanders may be passed, i.e. .cluster-autoscaler --expander=priority,least-waste
```

The error I get is the following.  Did I format something incorrectly?  I directly copy/pasted from the FAQ.
```
F1207 04:37:45.236835       1 main.go:345] Failed to create autoscaler: Expander priority,least-waste not supported
goroutine 130 [running]:
k8s.io/klog/v2.stacks(0xc00013c001, 0xc000c387e0, 0x74, 0x102)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1021 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x629d5a0, 0xc000000003, 0x0, 0x0, 0xc0003dd0a0, 0x617f4a9, 0x7, 0x159, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:970 +0x1a3
k8s.io/klog/v2.(*loggingT).printf(0x629d5a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x3e3449b, 0x1f, 0xc000ed2370, 0x1, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:751 +0x18b
k8s.io/klog/v2.Fatalf(...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1509
main.run(0xc000822140)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:345 +0x125
main.main.func2(0x453c8a0, 0xc000682f00)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:447 +0x2a
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:207 +0x113
```

**Comment by AndrewFarley** [comment]
Related to: #4502

**Comment by AndrewFarley** [comment]
Related to: #4503 which seems that cascading expanders don't work currently?  Why are they in the FAQ then?

**Comment by ryanpeach** [comment]
Also getting this error

**Comment by andrew-unaffiliated** [comment]
Just tried to implement `--expander=priority,least-waste` in EKS using `k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.0` and got the same error.

**Comment by AndrewFarley** [comment]
Ping

**Comment by JHeilCoveo** [comment]
Hi,
I see that PR #4233 has been merged in version 1.23.0, you will need that version before you can configure multiple expanders.

**Comment by gjtempleton** [comment]
@AndrewFarley Have you tried this with version 1.23.0 of the cluster-autoscaler?

This is definitely a failure in the docs though, will raise a PR to make this clearer for others.

**Comment by AndrewFarley** [comment]
Yep, this works now on the latest, and the newest helm chart supports it also.  Cheers team!  Nice work
