### ISSUE TITLE
Implement ASG filtering based on tags

### ISSUE THREAD

**Issue by AustinSiu** [kubernetes/autoscaler#4505]
**Which component are you using?**:

Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Add support for Auto Scaling Group filtering based on tags to simplify the ASG discovery logic in CA.

**Describe the solution you'd like.**:

We can use EC2's recently-added support for [describing ASGs using tags.
](https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-auto-scaling-groups-using-tags/)

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by AustinSiu** [comment]
I've just learned of the existence of a feature request with a similar proposal: #3877. That issue has been closed, but I don't believe any solution has been merged yet. I had already submitted a PR #4506. However, @shahadc I saw that another user had submitted a PR on that thread, but I don't see any recent updates on it. How would you like to move forward with this, since the issue still remains in the code?

**Comment by shahadc** [comment]
Hi @AustinSiu 
It looks like both PRs will solve the excessive API call issue for large environments, so as long as one gets merged I'm happy, it looks like the other PR is blocked currently.  I don't have a lot of experience with public github projects, so let me know if I need to reopen the original issue or anything else

**Comment by AustinSiu** [comment]
@shahadc thanks for confirming. To consolidate the threads around this problem, I will close this issue in favor of #3877. Can you please reopen that thread in the meantime? Thank you!
