### ISSUE TITLE
VPA recommends higher memory requests than available on any node in the cluster

### ISSUE THREAD

**Issue by Tenzer** [kubernetes/autoscaler#4515]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 0.9.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

VPA should not set the requested memory to a value higher than what's available in the cluster.

**What happened instead?**:

VPA set the requested memory for a deployment above the 7.7 GB memory that is available on the nodes in the cluster, causing the pod to stop being scheduled on any node.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure how this could be easily reproduced. In our case we had a service that had a fairly steady memory usage which suddenly increased, causing the VPA to request more memory than what was available on any single node in the cluster:
<img width="835" alt="Screenshot 2021-12-11 at 07 38 10" src="https://user-images.githubusercontent.com/68696/145668712-a3735097-9ee4-4a22-9d92-095dc8755afd.png">

**Anything else we need to know?**:

While this can be worked around by setting a limit on how much memory each VPA object is allowed, it becomes tedious when you have many VPA configurations.

I would instead suggest the VPA either queried the nodes in the cluster to figure out what the maximum memory (and possibly CPU) available in the cluster is and use that as an upper boundary, or alternately add a flag to the recommender similar to `--pod-recommendation-min-memory-mb` but allowing to set an upper boundary in a central place.

**Comment by jbartosik** [comment]
Hi,
VPA might do that, as noted in the [Known Limitations section of README](https://github.com/kubernetes/autoscaler/tree/e14efa61989938f119b0b72f1d91a3b65294752a/vertical-pod-autoscaler#known-limitations):

> VPA recommendation might exceed available resources (e.g. Node size, available size, available quota) and cause pods to go pending. This can be partly addressed by using VPA together with Cluster Autoscaler.

I'd suggest following the README and enabling Cluster Autoscaler in the cluster and seeing if that helps.

Please reopen the issue if needed.

**Comment by Tenzer** [comment]
We are already using the Cluster Autoscaler, but it becomes a problem when the VPA sets the requested resources higher than what the node sizes in the cluster can handle. Cluster Autoscaler can only change the number of nodes in the cluster, not the size of them, as far as I know. This is also mentioned in the FAQ for it:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up
> CA doesn't add nodes to the cluster if it wouldn't make a pod schedulable. It will only consider adding nodes to node groups for which it was configured. So one of the reasons it doesn't scale up the cluster may be that the pod has too large (e.g. 100 CPUs) [...]

I'd imagine the size of the nodes in a cluster rarely changes, which is why I think a flag similar to `--pod-recommendation-min-memory-mb` and `--pod-recommendation-min-cpu-millicores`, but for setting maximum values, would be useful as it then could be configured to match what the nodes in the cluster can deliver.

**Comment by jbartosik** [comment]
Thank you for clarifying. I'll take another look. I think with CA in cluster VPA should be able to limit its recommendation to what's available in cluster.

**Comment by voelzmo** [comment]
@jbartosik 
> Thank you for clarifying. I'll take another look. I think with CA in cluster VPA should be able to limit its recommendation to what's available in cluster.

Did you end up looking into this at some point? We're also considering this scenario to be a problem that we'd like to avoid. If you have specific ideas/thoughts on this, it would be great to hear them! At least we should maybe /reopen this?

**Comment by jbartosik** [comment]
I didn't have bandwidth to look into the problem. Not sure when I'll be able to

**Comment by voelzmo** [comment]
/reopen

Still an issue we don't have any solution for.

**Comment by voelzmo** [comment]
I'd still be interested in solving this somehow.

@jbartosik do you think your initial idea points in the right direction?
> I think with CA in cluster VPA should be able to limit its recommendation to what's available in cluster

Are you suggesting that VPA could get information about the maximum allocatable resources from CA somehow? In the end, thats what we would need to do: limiting Pod resources to the allocatable, such that they don't become un-schedulable, right?
