### ISSUE TITLE
vertical-pod-autoscaler tags are not go modules friendly

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/autoscaler#4545]
**Which component are you using?**:

vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

From [Go modules wiki in golang/go](https://github.com/golang/go/wiki/Modules):
> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. **The leading v is required.**

Currently the tags of `k8s.io/autoscaler` are not prefixed with a leading `v` - https://github.com/kubernetes/autoscaler/tags.

When using the `k8s.io/autoscaler` in a Go modules project (for example to import the VPA types), it cannot be properly translated to concrete version:

```go
module github.com/foo/bar

go 1.16

require (
	// ...
	k8s.io/autoscaler v0.0.0-20190805135949-100e91ba756e
	// ...
)
```

Every time a developer has to check what is actually the version that corresponds to this commit sha.

**Describe the solution you'd like.**:

`k8s.io/autoscaler` or `k8s.io/autoscaler/vertical-pod-autoscaler` tags to be go modules friendly:

```go
require (
	// ...
	k8s.io/autoscaler v0.22.0 // or v1.22.0
	// ...
)
```

**Describe any alternative solutions you've considered.**:

N/A

**Additional context.**:

N/A

**Comment by voelzmo** [comment]
/remove lifecycle-stale

This is still a thing and causing pain on every update for us ;(

**Comment by ialidzhikov** [comment]
I think this was meanwhile somehow resolved. In our `go.mod` files we don't have anymore 

```
require (
	// ...
	k8s.io/autoscaler v0.0.0-20190805135949-100e91ba756e
	// ...
)
```

but
 
```
require (
	// ...
	k8s.io/autoscaler/vertical-pod-autoscaler v0.12.0
	// ...
)
```

Maybe we had some legacy transitive dependencies that were still pulling `k8s.io/autoscaler` and not `k8s.io/autoscaler/vertical-pod-autoscaler`.
