### ISSUE TITLE
Default VPA installation scripts/yamls using old CRD API

### ISSUE THREAD

**Issue by kgolab** [kubernetes/autoscaler#4562]
When I ran e2e tests from master:HEAD, I got the following warning:
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

I guess we should migrate to v1 CRD everywhere.

**Comment by adriananeci** [comment]
@kgolab Looking through the e2e scripts I only found `deploy/vpa-v1-crd-gen.yaml` referenced which have already `apiextensions.k8s.io/v1` configured for CRD specs.
Any extra details in your run logs regarding which CRD is about?

**Comment by kgolab** [comment]
I debugged the problem and it comes from `vpa-process-yamls.sh` being called to delete the resources prior to the test.

It contains the following code, pulling in the old CRD:
```
case ${ACTION} in
delete|diff|print) COMPONENTS+=" vpa-beta2-crd" ;;
esac
```
