### ISSUE TITLE
Discovering node's taints from ASG tags in Alicloud / Merging changes from and internal fork

### ISSUE THREAD

**Issue by teqwve** [kubernetes/autoscaler#4569]
**Which component are you using?**:

A cluster-autoscaler running on Alicloud

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Inheriting node's taints from tags of ASG. At the moment it's not possible to hint cluster-autoscaler about taints a node will have using tags of an ASG, it's only possible to hint about node's labels (you can see it [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/alicloud/alicloud_manager.go#L249)). It would be nice to have the same options as with AWS provider.

**Describe the solution you'd like.**:

The change is simple and I'd be very happy to provide the PR myself, but:

* Alibaba has an internal fork of cluster-autoscaler that has already implemented the feature I'd like to have (see notes in context)

* last time such PR was provided it was rejected and a codeowner of Alicloud provider synchronized changes from their internal fork instead (PRs: https://github.com/kubernetes/autoscaler/pull/1719 and https://github.com/kubernetes/autoscaler/pull/1723)

So instead I'd like to ask Alicloud provider codeowner (@ringtail from what I've found in `OWNERS` file) if it's possible to synchronize changes from the internal fork to this repository. If no, could I provide a PR that would add support for taints and hope it will be accepted?

**Describe any alternative solutions you've considered.**:

One solution is to use an internal version of autoscaler deployed by Alibaba cloud, but it's quite problematic:
* I can't use the same version of cluster-autoscaler as on other clouds
* it seems like this internal fork is based on an old version of cluster-autoscaler (internal tag is `v1.3.1-7369cf1`) and e.g. scaling events aren't visible in pending Pods' descriptions (there are errors like `E1229 11:03:27.374533       1 event.go:259] Could not construct reference to: '&v1.Pod(...)' due to: 'selfLink was empty, can't make reference'. Will not report event`), I can also imagine that there are bug fixes in this repository that haven't been backported to the internal fork

**Additional context.**:

The internal fork is deployed by  `alicloud_cs_kubernetes_autoscaler` terraform resource in Alicloud terraform provider maintained by Alibaba cloud If one looks at it's source code (available  [here](https://github.com/aliyun/terraform-provider-alicloud/blob/255dda4fbd411aaa4316d629beece1f8bb6b5968/alicloud/resource_alicloud_cs_kubernetes_autoscaler.go)) it becomes clear that internal fork has support for taints which haven't been merged to this repository.

I think that these constants ([here](https://github.com/aliyun/terraform-provider-alicloud/blob/255dda4fbd411aaa4316d629beece1f8bb6b5968/alicloud/resource_alicloud_cs_kubernetes_autoscaler.go#L32)) are self-descriptive:
```
const (
	(...)
	defaultAutoscalerImage     = "registry-vpc.%s.aliyuncs.com/acs/autoscaler:v1.3.1-7369cf1"
	LabelPattern               = "k8s.io/cluster-autoscaler/node-template/label/"
	TaintPattern               = "k8s.io/cluster-autoscaler/node-template/taint/"
)
```

I've configured cluster-autoscaler like this and I can confirm it's working as one would expect :)

**Comment by teqwve** [comment]
To be precise I'd like to add that there is also a 'managed' version of cluster-autoscaler (documented [here](https://www.alibabacloud.com/help/doc-detail/119099.htm#title-2gy-7ok-45m)) that deploys a different tag (last time I checked the `v1.3.1` part was the same, hash was different) than the terraform provider does. I ended up using this tag with ASG tag patterns the same as in the terraform provider. I can't remember the exact reasons now (the tag from terraform was incompatible with new kubernetes api, or something like this).

**Comment by ringtail** [comment]
@teqwve Sure. I'll check it.

**Comment by ringtail** [comment]
CC @IrisIris

**Comment by teqwve** [comment]
Hi, @ringtail, are there any chances of doing this?

If you don't have time, I will be very happy to provide a patch with taints support myself (but it would differ from internal fork in this case).

**Comment by ringtail** [comment]
@lrislris Pls follow it up.

**Comment by teqwve** [comment]
Hi! I see you might not have sufficient resources, I'll try to provide a PR for changing this myself. Is that ok?

**Comment by ringtail** [comment]
> Hi! I see you might not have sufficient resources, I'll try to provide a PR for changing this myself. Is that ok?

sure, thanks man.
