### ISSUE TITLE
How to make cluster autoscaler exclude node group by label 

### ISSUE THREAD

**Issue by tuatara73** [kubernetes/autoscaler#4573]
I'm trying to make cluster autoscaler scale up/down only 1 of 2 node groups that I have in AWS.
I googled it and read the FAQ and didn't find my answer.
Thanks on advance for your help.

**Comment by ian-llewellyn** [comment]
I'm searching for confirmation on exactly this topic too. I believe it should be possible to remove the autoscaling related tags (`k8s.io/cluster-autoscaler/enabled` and `k8s.io/cluster-autoscaler/<cluster-name>`) from the AWS ASG - see [Auto Discovery Setup](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup). I'm not sure if the cluster-autoscaler Pod needs to be restarted afterwards.

**Comment by spinus** [comment]
There is another use case. If cloud provider goes crazy and the resources are not available for user, but are available for API client (aka, deleted but kind of stuck), it blocks autoscaler from normal operations.
