### ISSUE TITLE
[VPA] Building binaries from source

### ISSUE THREAD

**Issue by gaganso** [kubernetes/autoscaler#4585]
Is there documentation that explains how to build recommender and other binaries of the vertical pod autoscaler project? I see that the manifest files contain images for these binaries but I couldn’t find any Makefile to build the binaries.
Goal: I want to modify the recommender algorithm and test it locally.

**Comment by gaganso** [comment]
\kind info

**Comment by Shubham82** [comment]
Hi @gaganso
The Makefile for recommender is under **`/vertical-pod-autoscaler/pkg/recommender`**. See this [link](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Makefile).  For Updater it is under **`/vertical-pod-autoscaler/pkg/updater`**. After creating your custom images then do changes in the deploy folder for recommender deployment (Image), then follow the [Installation](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#install-command) mentioned in the README.

**Comment by gaganso** [comment]
Hi @Shubham82, thanks a lot! I should have explored more.
