### ISSUE TITLE
VPA: Use Memory Limit as the memory usage in OOM event

### ISSUE THREAD

**Issue by robbiezhang** [kubernetes/autoscaler#4589]
In the VPA OOM observer, it reports the memory request in the memory info. I think we should use memory limit since OOM means the memory usage exceeded the memory limit. Code here:

https://github.com/kubernetes/autoscaler/blob/b3576e0cdcb32bf61986aa4db71b90a204f25d50/vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go#L158

Does anyone have any idea? Why we use memory request here?

**Comment by robbiezhang** [comment]
any ideas?

**Comment by jfoy** [comment]
A recorded OOM doesn't necessarily mean the usage exceeded the limit: it more commonly means that the machine was under memory pressure and chose to terminate the container's process. https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-out-of-memory-behavior
