### ISSUE TITLE
Azure unittest failing on master

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#4592]
This is also causing unittest runs to fail on PRs. Example: https://github.com/kubernetes/autoscaler/runs/4767923107?check_suite_focus=true

The issue can be reliably reproduced by running `make test-in-docker` locally.

@feiskyer @marwanad @nilo19

**Comment by nilo19** [comment]
fixed by: https://github.com/kubernetes/autoscaler/pull/4594

**Comment by MaciekPytel** [comment]
It seems the test got fixed for a second by #4594, but it's failing again now. Can we temporarily disable the test until it's fixed? 

https://github.com/kubernetes/autoscaler/pull/4600#issuecomment-1011438005 suggests there is some external endpoint the test depends on, can we consider some extra mocking to remove any external dependencies?

**Comment by MaciekPytel** [comment]
Seems #4620 has fixed the test again, but I think it's bad practice for a unittest to make calls to an external API. Can we consider adding additional mocking to avoid doing that? @nilo19

**Comment by marwanad** [comment]
/close

unit test removed/
