### ISSUE TITLE
Readme.md mentions slack - which doesn't allow registration?

### ISSUE THREAD

**Issue by applike-ss** [kubernetes/autoscaler#4593]
The readme.md mentions `Please join us on #sig-autoscaling at https://kubernetes.slack.com/` - however if you don't already own an account, then you can't get in. 
That is because you can only register with an `@get-an-invite-at.slack.kubernetes.io` address.
It would be great to be able to join the slack channel to ask questions if that is what the slack is used for.

**Comment by devarsh10** [comment]
Hey There,
You can get invite from this link: [https://communityinviter.com/apps/kubernetes/community](https://communityinviter.com/apps/kubernetes/community)
And then you can join the Slack Channel of Kubernetes.
Hope you get what you are looking for.

Regards,
Devarsh.

**Comment by devarsh10** [comment]
It is showing that couldn't sign in browser. But, it signs me in to the k8s Slack channel.


![image](https://user-images.githubusercontent.com/83413047/215727592-74ccd472-c7d4-4061-8f72-979649d57d21.png)
