### ISSUE TITLE
Failed to scale up: Could not compute total resources: No node info for: node pool id

### ISSUE THREAD

**Issue by varshavaradarajan** [kubernetes/autoscaler#4598]
**Which component are you using?**:

cluster-autoscaler 

**What version of the component are you using?**:

Component version: v1.21.0, but the problem exists on the latest 1.21 patch. 

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

DigitalOcean Managed Kubernetes

**What did you expect to happen?**:

For a node group X to scale up without issue to accommodate pending pods. 
**What happened instead?**:

CA did not trigger scale up, but logged the following error:

```
static_autoscaler.go:427] Failed to scale up: Could not compute total resources: No node info for: 48cc4907-5650-4d42-b385-293f5ada1d8d
```

**How to reproduce it (as minimally and precisely as possible)**:

1. Spin up a Kubernetes cluster on digitalocean with 2 node groups X and Y, both with autoscaling enabled. Let both node groups have 1 worker node each and autoscaler minNodes = 1 and maxNodes > 1
2. Mark worker node in group X as unschedulable
3. Add a deployment with enough replicas so that some pods are in `Pending` state triggering scale up in group Y.

**Anything else we need to know?**:

The readyNodes that is passed in https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.21.0/cluster-autoscaler/core/static_autoscaler.go#L268 does not contain the worker node from group X. So, nodeInfo is not retrieved for this. While computing resources in scaleUp, nodeInfosForGroup does not have an entry for X resulting in the above error.

**Comment by com6056** [comment]
Hitting this too, apparently the node groups aren't ever getting into the backoff state because of this which means it just keeps infinitely retrying

**Comment by leoryu** [comment]
@varshavaradarajan @com6056 How did you reslove this error?
