### ISSUE TITLE
`cluster_autoscaler_unremovable_nodes_count` undocumented metric

### ISSUE THREAD

**Issue by nniehoff** [kubernetes/autoscaler#4647]
**Which component are you using?**:  cluster-autoscaler
**What version of the component are you using?**:  1.21.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:  AWS EKS
**What did you expect to happen?**:

I was looking for the `cluster_autoscaler_unremovable_nodes_count` metric to be documented [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/metrics.md).

**What happened instead?**:

I can't find any documentation for the `cluster_autoscaler_unremovable_nodes_count` metric, specifically around the `reason` label.

**Comment by nniehoff** [comment]
I'm no go guru, but i think I found the mapping for the unremovable reasons [here](https://github.com/kubernetes/autoscaler/blob/91e8f8e40c7f933e99408d365fa03d72e5e5c14f/cluster-autoscaler/simulator/cluster.go#L69-L99)

**Comment by MikeTomlin19** [comment]
I am looking for the same info. Can this issue please be re-opened?

**Comment by DutchEllie** [comment]
Still completely undocumented. Can someone please re-open this issue and document it?

**Comment by dart-ops** [comment]
+1
