### ISSUE TITLE
CA incorrectly determines `emptyDir` as local storage and refuses to scale down

### ISSUE THREAD

**Issue by mbrancato** [kubernetes/autoscaler#4664]
**Which component are you using?**:

cluster-autoscaler (via GKE)

**What version of the component are you using?**:

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
</pre></details>

**What environment is this in?**:

GKE 

**What did you expect to happen?**:

Ephemeral storage would not block scale down.

**What happened instead?**:

Warning that *some* pods with `emptyDir` volumes are blocking scale down.

**How to reproduce it (as minimally and precisely as possible)**:

This requires getting a cluster into a state where it wants to scale down certain nodes, but those node have pods with `emptyDir` volumes.

**Anything else we need to know?**:

These are on nodes using a relatively new [ephemeral storage](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#local_ephemeral_storage) feature that allows local NVMe storage to back the overlay filesystems. I had not seen this issue before, so it may be caused by this recent ephemeral storage change.

**Comment by mbrancato** [comment]
As an update, I do see the `cluster-autoscaler` README shows:

```
If true cluster autoscaler will never delete nodes with pods with local storage, e.g. EmptyDir or HostPath
```

So this does confirm to me why CA is blocking the scale down. The problem I see is `emptyDir` is [defined](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) as temporary / ephemeral storage that is designed to be discarded when the pod is removed. So I do think this is a mischaracterization of the `emptyDir` volume type as being "local storage" when all pods using this are already subject to removal when the pod terminates. As I understand the goal here, it should only apply to `HostPath` and `LocalVolume` types.

**Comment by nsspradeep** [comment]
`emptyDir` volume type is treated as "local storage" because if pod is evicted then the data stored in `emptyDir` volume will be lost. So by evicting the pod using `emptyDir` from an under utilized node you can define annotation `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"`.

Also with GKE 1.22 cluster autoscaler will evict pods using `emptyDir` if the pod is running on an under utilized to scale down the node and only for pods where you do not want to have them evicted you need to define `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"`.

**Comment by philomory** [comment]
> Also with GKE 1.22 cluster autoscaler will evict pods using `emptyDir` if the pod is running on an under utilized to scale down the node and only for pods where you do not want to have them evicted you need to define `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"`.

Is this functionality specific to GKE, or is it true of CA on k8s 1.22+ in general?
