### ISSUE TITLE
VPA restarts my pods but does not modify CPU or memory settings

### ISSUE THREAD

**Issue by caddac** [kubernetes/autoscaler#4667]
As the title says, VPA restarts my pods but does not modify CPU or memory settings. I'v been through the faq, but still not sure what exactly is wrong or how to fix it.

**Which component are you using?**:
vertical-pod-autoscaler

**What version of the component are you using?**:
Using `vpa-release-0.8` to get by the `unknown option -addext` error

Component version:

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
running in a kind cluster, 1 worker, 1 control-plan node

**What did you expect to happen?**:
attempting to run basic hamster example, hamster pods get recreated with new resources values

**What happened instead?**:
hamster pods restart, but resource values never update. 
vpa-admission-controller logs show repeated errors:
`http: TLS handshake error from x.x.x.x:yyyyy: remote error: tls: bad certificate`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
All troubleshooting steps from the FAQ are successful except the very last step ("curl the vpa-webhook service"). 
```$curl vpa-webhook.kube-system``` hangs forever and `$curl https://vpa-webhook.kube-system` gives output:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by caddac** [comment]
quick update, `curl https://vpa-webhook.kube-system -k` returns a 200 and logs `E0206 04:03:16.937701       1 server.go:140] contentType=, expect application/json` in the admission-controller pod.

**Comment by StefanCenusa** [comment]
Hello @caddac,

I've also ran into this error on the vpa-admission-controller pod. I've installed VPA into the cluster using `hack/vpa-up.sh` on MacOS using the default openssl (which is libressl actually). 

When started, the vpa-admission pod logged:
```
❯ kl vpa-admission-controller-58cf99779c-l5n7h -f
I0316 10:43:11.001945       1 main.go:76] Vertical Pod Autoscaler 0.10.0 Admission Controller
I0316 10:43:11.067723       1 certs.go:40] Successfully read 1042 bytes from /etc/tls-certs/caCert.pem
I0316 10:43:11.070132       1 certs.go:40] Successfully read 1151 bytes from /etc/tls-certs/serverCert.pem
I0316 10:43:11.070310       1 certs.go:40] Successfully read 1679 bytes from /etc/tls-certs/serverKey.pem
```
then the errors:
```
2022/03/16 10:38:53 http: TLS handshake error from <master-ip>:4745: remote error: tls: bad certificate
2022/03/16 10:38:53 http: TLS handshake error from <master-ip>13151: remote error: tls: bad certificate
2022/03/16 10:38:53 http: TLS handshake error from <master-ip>:45571: remote error: tls: bad certificate
```
whereas, when I've installed VPA using the openssl (1.1.1m - not the default one):
```
❯ kl vpa-admission-controller-58cf99779c-4zdbf -f
I0316 11:42:42.951814       1 main.go:76] Vertical Pod Autoscaler 0.10.0 Admission Controller
I0316 11:42:42.952757       1 certs.go:40] Successfully read 1168 bytes from /etc/tls-certs/caCert.pem
I0316 11:42:42.957108       1 certs.go:40] Successfully read 1168 bytes from /etc/tls-certs/serverCert.pem
I0316 11:42:42.957357       1 certs.go:40] Successfully read 1675 bytes from /etc/tls-certs/serverKey.pem
```

Notice the difference of read bytes. Didn't do any further debugging on what was different between those two.

Don't know if you are having the same issue, but the same effects you were describing were gone after using openssl (not libressl).

Hope it helps!

**Comment by jabdoa2** [comment]
We have also seen this. When the certificate of the VPA webhook expired (or it becomes nonfunctional otherwise) VPA will start to evict pods constantly. No exponential backoff or anything else. This caused havoc in a few of our clusters. It started to evict cert-manager fast enough that it could not longer finish its leader election and became effectively disabled.

Just ratelimiting (#2326) is not enough unfortunately. We would need some backoff on retries to evict pods from the same deployment/daemonset.

/remove-lifecycle rotten

**Comment by jabdoa2** [comment]
Waiting did not fix it.

/remove-lifecycle stale

**Comment by jabdoa2** [comment]
@caddac can you reopen this? This is still an issue (at least for us).
