### ISSUE TITLE
Cluster Autoscaler for Hetzner - using Rancher Node Pools and/or Templates

### ISSUE THREAD

**Issue by kgeipel-retail7** [kubernetes/autoscaler#4680]
**Which component are you using?**:
Rancher 2.5.9
K8s 1.20.11
Hetzner Docker Machine Driver 3.5.0 for Rancher

**Is your feature request designed to solve a problem? If so, describe the problem this feature should solve.**:

We provide SaaS and run a set of Workloads for every of our customers. Because we are getting more customers, the cluster has to grow, and therefor we need the node autoscaling (no one wants to get an alert message if the cluster runs out of resources). Sadly, the current available Hetzner autoscaler seems to be designed to run in Kubernetes native clusters and is not able to use already existing Node Pools and/or Templates in Rancher.

This is a point what makes it very uninteresting for us, because we don't want to maintain node pools twice and also don't want to take care of setting up new nodes from scratch.

**Describe the solution you'd like.**:

- the autoscaler can be configured to use already existing node templates within Rancher by passing the node template name in the commands section or by injecting it via config map
- the autoscaler can operate already existing node pools in Rancher which get simply up and down scaled by need, which are also configured by passing them in the commands section or via config map

**Comment by henrikperssonvermiculus** [comment]
@kgeipel-retail7 - did you manage to setup Rancher at Hetzner with autoscaler?

Having the same questions.

**Comment by kgeipel-retail7** [comment]
Hey @henrikperssonvermiculus, no, but to be honest I didn't try it because of the limitations. We wrote now an own go based tool for managing node pools in Rancher. It's currently in a soaking phase and has some minor bugs regarding thresholds, if it's ready for production I'll maybe share it here.
