### ISSUE TITLE
cluster-autoscaler: A simple mechanism to grow node groups simultaneously

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/autoscaler#47]
a.k.a https://github.com/kubernetes/contrib/issues/2352
I'm recreating the issue here so that we can better track it from the corresponding and upcoming PR.

**Comment by mumoshu** [comment]
As @mwielgus kindly described [there](https://github.com/kubernetes/autoscaler/pull/49#issuecomment-300136877), we would need a more sophisticated solution in the future.
Anyway, the PR #49 implements a native/simple solution that work well for not all but specific use-cases.

**Comment by MaciekPytel** [comment]
This feature is implemented and merged and I'd like to close this issue. @mumoshu are you ok with that?

**Comment by mumoshu** [comment]
@MaciekPytel Your implementation looks super nice to me 👍 Thank you very much for the effort!
