### ISSUE TITLE
cluster_autoscaler_max_nodes_count metric has always value of 0

### ISSUE THREAD

**Issue by sesto** [kubernetes/autoscaler#4703]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Component version: 1.20.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version                                                                                                                                                                                 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
AWS EKS

**What did you expect to happen?**:
I would expect that the metric value will be equal to the maximum nodes count in all autoscaling groups

**What happened instead?**:
the value is 0

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The setup is using autodiscovery

**Comment by Rohlik** [comment]
We have exactly the same issue on AWS EKS. Any clues?
