### ISSUE TITLE
Failed to generate EC2 Instance Types: unable to load EC2 Instance Type list

### ISSUE THREAD

**Issue by guisesterheim** [kubernetes/autoscaler#4704]
**Which component are you using?**:
cluster-autoscaler, following procedure here (https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html)

**What version of the component are you using?**:
Component version: v1.21.0

**What k8s version are you using (`kubectl version`)?**:
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS EKS

**What did you expect to happen?**:
Autoscaler pod to stand without failing

**What happened instead?**:
Autoscaler pod fails in loop with error message.
Failed to generate EC2 Instance Types: unable to load EC2 Instance Type list.

It's unable to reach out to the internet because it's a private network only:
<img width="1791" alt="2" src="https://user-images.githubusercontent.com/7569966/155349336-6e6b9cc6-cfdd-4e46-9308-fdd3aa275def.png">

It's unable to reach out to the internet because it's a private network only. We have VCP endpoints in place and even after setting the env variable "AWS_STS_REGIONAL_ENDPOINTS=regional" same error is found:
<img width="908" alt="1" src="https://user-images.githubusercontent.com/7569966/155349367-2422d926-8539-4721-a547-97060e0da78b.png">

**How to reproduce it (as minimally and precisely as possible)**:
1 - Have an EKS cluster without internet access
2 - Deploy following pattern on AWS docs (https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html)

**Anything else we need to know?**:

**Comment by bwagner5** [comment]
Do you have vpc endpoints setup for the ec2 api?

**Comment by bwagner5** [comment]
There was recently a permission added for ec2:DescribeInstanceTypes

Is that in the role permissions? I wouldn't think that would crashloop since it should fallback to a static list though.

**Comment by guisesterheim** [comment]
Hello Brandon! yes, it's in the role. I just found that I was missing one parameter named "--aws-use-static-instance-list=true" to avoid getting the up to date instance list. After setting that I get the error of trying to dial to the autoscaling endpoint

**Comment by bwagner5** [comment]
Hmm it seems like the VPC endpoints are not working properly then. Can you confirm if you have an ec2 and autoscaling vpc endpoint with proper route table entries setup (and that the pod is being launched into a subnet where those routes apply)? There isn't a strange dns setup is there? You'll need to the VPC+2 resolver to resolve the vpc endpoints to local addresses.

**Comment by guisesterheim** [comment]
Hey Brandon,

Thank you very much for your help. Yes, we're missing the VPC endpoint for autoscaling for now.
I'll create it and continue with the deployment.

I'm closing the issue now so it's not open while I'm troubleshooting.

Thanks
