### ISSUE TITLE
Horizontal pod autoscaler is not able to downscale properly based on custom metrics.

### ISSUE THREAD

**Issue by sanjipta1995** [kubernetes/autoscaler#4707]
**Which component are you using?**:
Horizontal pod autoscaler

HPA

**What version of the component are you using?**:
autoscaling/v2beta2(k8s version 1.20)

prometheus adapter is used to send custom metrics(k8s.gcr.io/prometheus-adapter/prometheus-adapter) No issue with prometheus adapter, since custom metrics sent properly.

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
k8s version - 1.20
</pre></details>

**What environment is this in?**:

AWS EKS provider

**What did you expect to happen?**: While downscaling, HPA should terminate pods as and when load decreases.

**What happened instead?**: We are seeing downscaling only when custom metric touches zero and not when value decreases below threshold.

**How to reproduce it (as minimally and precisely as possible)**: Create http_request_per_second from total http requests and use it in HPA definition

**Anything else we need to know?**:

yaml file for HPA definition:

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: http-pod-hpa
  namespace: kaas-monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-example-app
  minReplicas: 1
  maxReplicas: 50
  metrics:
    # use a "Pods" metric, which takes the average of the
    # given metric across all pods controlled by the autoscaling target
    - type: Pods
      pods:
        metric:
          # use the metric that you used above: pods/http_requests
          name: http_requests_per_second
        target:
          # target 500 milli-requests per second,
          # which is 1 request every two seconds
          type: AverageValue
          averageValue: 100m
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 5
          periodSeconds: 60
      stabilizationWindowSeconds: 0
    scaleUp:
      policies:
        - type: Pods
          value: 10
          periodSeconds: 60
      selectPolicy: Max
      stabilizationWindowSeconds: 0

**Comment by jbartosik** [comment]
HPA code is in [kubernetes/kubernetes ](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/podautoscaler)

**Comment by jbartosik** [comment]
Please report this issue in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/podautoscaler).
