### ISSUE TITLE
Support for probe configuration in cluster-autoscaler's Helm chart

### ISSUE THREAD

**Issue by PrayagS** [kubernetes/autoscaler#4718]
**Which component are you using?**: cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We noticed that there is no configuration for liveness and readiness probes in the values file.

https://github.com/kubernetes/autoscaler/blob/76bd4cc17f21ec5f4901f30d94d895ee0a3d3c2f/charts/cluster-autoscaler/templates/deployment.yaml#L196-L199

The above given part is the only configuration that the deployment manifest includes. The chart values file also doesn't have any values regarding this or the readiness probe. We want to configure its attributes like initial delay seconds, success and failure thresholds, etc.

**Describe the solution you'd like.**:

Modify the deployment manifest template and the values file to allow users to configure probes.

**Additional context.**:

Is there any particular reason for the chart to not have this? If not, and If this feature request is approved, I'd like to make a PR. We already use modified templates and values file to make this work right now.

**Comment by rradecki-migo** [comment]
It would be great to have a related setting for the CA helm chart. Default settings are not enough in some scenarios.
