### ISSUE TITLE
Lower timeout seconds to 29

### ISSUE THREAD

**Issue by kyranb** [kubernetes/autoscaler#4729]
**Which component are you using?**: The reccomender

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Digital Ocean is unable to auto upgrade the cluster because `[Mutating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.](https://docs.digitalocean.com/products/kubernetes/resources/clusterlint-errors/#admission-controller-webhook-timeout)`

**Describe the solution you'd like.**:

To change the default from 30 seconds to 29

To change the default from 30 seconds to 29

**Comment by jbartosik** [comment]
VPA admission controller already has a flag for this: [`--webhook-timeout-seconds`](https://github.com/kubernetes/autoscaler/blob/a3267ca3b0525db9bba0ffb878b168d1d78f6c3a/vertical-pod-autoscaler/pkg/admission-controller/main.go#L67).

Please reopen if this doesn't work for you. If you do reopen please explain why setting the flag won't work but changing default would (changing default will affect everyone so I'd rather not do it (and changing defaults to work well for everyone might be impossible)).

**Comment by kyranb** [comment]
Thanks, I appreciate you leaving the flag here for others to see. The reason that a change to the defaults would benefit everyone is that:

> Admission control webhook timeouts can block upgrades, when the API call times out, due to an incorrectly configured TimeoutSeconds value. Since webhooks inherently add to API latency, we must stay within the recommended range in order for API requests to be successful. Specifically, this happens when an admission control webhook does not respond within 29 seconds.

This is taken from `Clusterlint` which Digital Ocean maintains as a set of best practises and is designed to work with all clusters, not just workloads running on Digital Ocean: https://docs.digitalocean.com/products/kubernetes/resources/clusterlint-errors/#admission-controller-webhook-timeout

**Comment by jbartosik** [comment]
I thought about this  a bit more.

I think I might be ok with changing the default value of the flag after all. From what I saw VPA admission controller is taking much less time than 30s so it could be safe.

I still want to check:

- If VPA admission controller is also much faster than 30s in other places too,
- What value would make sense,
- Are others ok with the flag default value change / do we have any recommendations for doing that
