### ISSUE TITLE
Does VPA support autoscaling its own components?

### ISSUE THREAD

**Issue by adriananeci** [kubernetes/autoscaler#4744]
Does VPA support autoscaling its own components like recommender and updater?

**Comment by jbartosik** [comment]
I don't recall anything about VPA scaling VPA either way.

So I think you could configure VPA to scale VPA if you want. But I'd be very careful about using anything other than `Off` mode - if VPA applying its recommendation to VPA breaks VPA then there will be no VPA to notice and improve the recommendation.

`Off` mode is probably fine.

Could you explain why you're thinking about this?

**Comment by voelzmo** [comment]
The simple solution we took was to install an additional VPA that scales the VPA. So in the end, its VPAs all the way down ;)
