### ISSUE TITLE
Use PreFilterResult in SchedulerBasedPredicateChecker

### ISSUE THREAD

**Issue by x13n** [kubernetes/autoscaler#4745]
**Which component are you using?**:

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Scheduler framework is slow when scheduling DaemonSet pods, since it unnecessarily iterates over all possible nodes to find a match. This was recently fixed, but resulted in API change in scheduler framework.

**Describe the solution you'd like.**:

Bump k8s deps to import the new interface ([update script](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/hack/update-vendor.sh)), then only consider nodes that are a part of PreFilterResult when simulating scheduler [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go).

**Describe any alternative solutions you've considered.**:

n/a

**Additional context.**:

Scheduler code change: https://github.com/kubernetes/kubernetes/pull/108648

/good-first-issue

**Comment by uroy-personal** [comment]
Good Morning @x13n,

I am interested to work on this issue. Please let me know if I can assign it to myself.

**Comment by x13n** [comment]
Thanks for expressing your interest in this!

Since the scheduler change went in just a few days ago, I think we have to wait for next 1.24 pre-release though. `v1.24.0-alpha.3` is over a month old now.

**Comment by uroy-personal** [comment]
> 

Yes Sure.

**Comment by BigDarkClown** [comment]
The Kubernetes v1.24.0-alpha.4 was just released, and it contains the change in question. I've already done a vendor upgrade as a part of https://github.com/kubernetes/autoscaler/pull/4761, after it is merged you should be able to work on it.

**Comment by x13n** [comment]
Hey @uroy-personal, are you planning to work on this?

**Comment by uroy-personal** [comment]
Hi @x13n ,

Yes I will look into the issue over the week-end. Hope to fix it early next week. In the meantime if I get any queries, I will get in touch with you.

**Comment by x13n** [comment]
Sounds good, thanks!

**Comment by uroy-personal** [comment]
Good Morning @x13n ,
I got few queries on the solution you are expecting. A short slack call would be good.  Please suggest the time.

**Comment by x13n** [comment]
I pinged you on Slack, let's discuss the details there.

**Comment by uroy-personal** [comment]
Hi @x13n ,
I am sorry to hold on to this issue for so long due to few personal issues. I got a big lot of backlogs to clear so I think unassigning it at the moment seems a logical step.
I will follow this wonderful project and hopefully contribute in the future.

**Comment by ahayschi** [comment]
I'd like to work on this, if that sounds good?

/assign

**Comment by x13n** [comment]
Yup, thanks!
