### ISSUE TITLE
VPA e2e uses old resource-consumer image not built for s390x

### ISSUE THREAD

**Issue by jeremyfreudberg** [kubernetes/autoscaler#4748]
**Which component are you using?**:
vertical-pod-autoscaler

**What version of the component are you using?**:

latest

**What environment is this in?**:

Red Hat OpenShift for IBM Z and IBM LinuxONE, but is applicable to all Kubernetes installations on s390x

**What did you expect to happen?**:

e2e tests pass

**What happened instead?**:

e2e tests fail

**How to reproduce it (as minimally and precisely as possible)**:

Run the e2e tests. They fail when pulling in the [resource-consumer image](https://github.com/kubernetes/autoscaler/blob/ecc0eed4fccdf9dd98aaf4757243bdbd5902dc47/vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go#L68) which is not built for s390x. [If we bumped the kubernetes version in VPA e2e it would pull in resource-consumer:1.9 which is built s390x.](https://github.com/openshift/kubernetes/commit/d56e21c57979cf94b1a019101f94121baef38624)

**Comment by jbartosik** [comment]
I think updating dependencies is a good idea, I'm happy to review PRs.

**Comment by voelzmo** [comment]
I assume this is fixed now since we're using `resource-consumer:1.10` in the meanwhile: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/e2e/vendor/k8s.io/kubernetes/test/utils/image/manifest.go#L268

/close
