### ISSUE TITLE
VPA e2e uses stress image which is amd64-only (and very old)

### ISSUE THREAD

**Issue by jeremyfreudberg** [kubernetes/autoscaler#4750]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

latest

**What environment is this in?**:

OpenShift, but applicable to all Kubernetes installations on non-amd64

**What did you expect to happen?**:

e2e tests pass

**What happened instead?**:

e2e tests fail

**How to reproduce it (as minimally and precisely as possible)**:

[e2e tests use stress image](https://github.com/kubernetes/autoscaler/blob/ecc0eed4fccdf9dd98aaf4757243bdbd5902dc47/vertical-pod-autoscaler/e2e/v1/autoscaling_utils.go#L64) which is amd64-only and very old. The same can be said of the no-longer-used `jbartosik-gke-dev` image. ppc64le/s390x/aarch64 support in the e2e tests is important, so the image should be rebuilt  for these architectures (noting that [the source](https://github.com/vishh/stress) is very old and obscure). I am open minded about how to accomplish this.

**Comment by yselkowitz** [comment]
#4546 which switched this test to the upstream image did not help, as it too is only available for x86_64.
/cc @jbartosik

**Comment by jbartosik** [comment]
Supporting more archs is good. Please let me know if you have any questions / need review

**Comment by yselkowitz** [comment]
Your initial approach to #4546 was to build the image and then promote it like other kubernetes test images, which if done properly should work for multi-arch support.  Any reason why that could not proceed?

**Comment by jbartosik** [comment]
> Your initial approach to #4546 was to build the image and then promote it like other kubernetes test images, which if done properly should work for multi-arch support. Any reason why that could not proceed?

I'd rather not maintain an extra image (there's much other work to do).

Also custom images were based on `gcr.io/google-containers/stress:v1` (see [here](https://github.com/kubernetes/autoscaler/pull/4556/files#diff-34dc5aa9e143440d33d4ee7696161dbb6241a52b3bbdbfdf064cb4ef0b43c02b)) so if that image works only for x86_64 then my custom image wouldn't work either.

**Comment by jbartosik** [comment]
I think I currently don't have capacity to look into this in more detail.

I'm happy to review if you know how to fix this issue

**Comment by zhengbingxian** [comment]
gcr.io/google-containers/stress:v1   also unsupport arm64 。 This is Kubernetes project,  It's so bad and pity that this project  don't do more test for other arch.

**Comment by voelzmo** [comment]
/reopen

After switching to an M2 MacBook recently, this became a visible pain for me as well: e2e couldn't run in a local KinD cluster anymore, because the stress image isn't available for arm64. I played around a bit and modified vishh/stress (assuming this is what the stress image is based on?) to have a multi-stage multi-platform build.

Here is my [Fork](https://github.com/voelzmo/stress) and all magic lives in the [Dockerfile](https://github.com/voelzmo/stress/blob/master/Dockerfile).

@jbartosik I'm not sure from where the stress image is currently published, but I could do a PR with similar changes. WDYT?

**Comment by jbartosik** [comment]
I'd rather not maintain an image. Let's check for images that already have what we need. If we can't find image with `stress` util maybe we should switch to resource consumer, like other tests do?
