### ISSUE TITLE
Custom Kubernetes without AKS Engine

### ISSUE THREAD

**Issue by ubikusss** [kubernetes/autoscaler#4755]
Hello, 

I am trying to use autoscaler with a custom deployment in Azure. Would that be possible?

Basically we are creating a kubernetes cluster over VMSS but not using [aks engine](https://github.com/Azure/aks-engine). We also want to use a MSI. I already did some tests with the `vmss` option but to no avail.

Best regards, 
Dini

**Comment by jbartosik** [comment]
Which autoscaler are you trying to set up ([here](https://github.com/kubernetes/autoscaler#whats-inside)'s a list)?

**Comment by ubikusss** [comment]
Yes, sorry, forgot to mention, cluster autoscaler.

**Comment by ubikusss** [comment]
It's good, it works fine :)
