### ISSUE TITLE
Ignore daemonset unschedulable pods for upscales?

### ISSUE THREAD

**Issue by bpineau** [kubernetes/autoscaler#4756]
The Kubernetes daemonset controller can create unschedulable pods in some situations, which can permanently slow down the cluster-autoscaler.

Here is an example situation we saw on live clusters:
1. A cluster with many nodes at maximum pods capacity (`allocatable.pods`): they can't take more pods
2. A new daemonset is deployed
3. The standard k8s daemonset controller will create pods targeting each node (eg. requiredDuringSchedulingIgnoredDuringExecution=thenode), regardless of their available resources (ability to accept more pods)
4. The daemonset pods with affinities to nodes that are already full (that can't accept more pods) will remain Pending
5. The cluster-autoscaler will pick those pending pods as normal "unschedulablePodsToHelp" and evaluate upscale options (but won't find any because those daemonset pods have strong affinities to already existing nodes)
6. At every subsequent RunOnce loop, the autoscaler will spend CPU time evaluating upscaling options, over and over
 
Yet I can't think of a good reason for the cluster-autoscaler to evaluate upscales opportunities for pending daemonset pods.

Did I miss any? Otherwise, would this be too much of a narrow/rare case for such a change, or is that acceptable (then I can make that a PR)?

```diff
--- cluster-autoscaler/core/static_autoscaler.go
+++ cluster-autoscaler/core/static_autoscaler.go
@@ -41,6 +41,7 @@ import (
        "k8s.io/autoscaler/cluster-autoscaler/utils/backoff"
        "k8s.io/autoscaler/cluster-autoscaler/utils/deletetaint"
        "k8s.io/autoscaler/cluster-autoscaler/utils/errors"
+       pod_util "k8s.io/autoscaler/cluster-autoscaler/utils/pod"
        scheduler_utils "k8s.io/autoscaler/cluster-autoscaler/utils/scheduler"
        "k8s.io/autoscaler/cluster-autoscaler/utils/taints"
        "k8s.io/autoscaler/cluster-autoscaler/utils/tpu"
@@ -425,6 +426,8 @@ func (a *StaticAutoscaler) RunOnce(currentTime time.Time) errors.AutoscalerError

        unschedulablePodsToHelp, _ := a.processors.PodListProcessor.Process(a.AutoscalingContext, unschedulablePods)

+       // ignore pods from daemonset, they shouldn't trigger upscales
+       unschedulablePodsToHelp = a.filterOutDaemonsetPods(unschedulablePodsToHelp)
        // finally, filter out pods that are too "young" to safely be considered for a scale-up (delay is configurable)
        unschedulablePodsToHelp = a.filterOutYoungPods(unschedulablePodsToHelp, currentTime)

@@ -710,6 +713,17 @@ func (a *StaticAutoscaler) nodeGroupsById() map[string]cloudprovider.NodeGroup {
        return nodeGroups
 }

+// don't consider pods owned by daemonsets as unschedulable
+func (a *StaticAutoscaler) filterOutDaemonsetPods(allUnschedulablePods []*apiv1.Pod) []*apiv1.Pod {
+       var retainedUnschedulablePods []*apiv1.Pod
+       for _, pod := range allUnschedulablePods {
+               if !pod_util.IsDaemonSetPod(pod) {
+                       retainedUnschedulablePods = append(retainedUnschedulablePods, pod)
+               }
+       }
+       return retainedUnschedulablePods
+}
```

**Comment by MaciekPytel** [comment]
I don't see any reason to consider DS pods in scale-up, since you can't possibly add a node that would be able to run them anyway. I think it's important to consider them in filterOutSchedulable step to account for the resources they will consume, but the change you're proposing is filtering the DS pods after filterOutSchedulable so it looks good to me. 

I'd be interested to learn if you observed an actual slow-down from this. My intuition would be that the impact of actually running predicates would be minimal (ds pod can't run even on template node, so it would be filtered out before actual binpacking; meaning each pending ds pod only adds a single predicate check / nodeGroup / loop). A more likely reason for slowdown would be DeepEqual comparisons in pod equivalence group logic which should be fixed by https://github.com/kubernetes/autoscaler/pull/4735.

**Comment by MaciekPytel** [comment]
Note that considering permanently unschedulable ds pods in filterOutSchedulable is potentially more costly than considering them in scale-up. I think https://github.com/kubernetes/autoscaler/pull/4735 should really help with that.
