### ISSUE TITLE
VPA Doesn't respect the Controlled Values set as RequestsOnly 

### ISSUE THREAD

**Issue by fsalazarh** [kubernetes/autoscaler#4759]
**Which component are you using?**: VPA

**What version of the component are you using?**: 

Component version: 0.10.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
EKS Cluster with t2.medium instances.

**What did you expect to happen?**:
VPA Respects the `ControlledValues` set as `RequestsOnly` and `minAllowed` - `maxAllowed` params.

**What happened instead?**:
VPA Overrides limits and requests resources from pods spec after recommendation. 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy VPA with following parameters:
```
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  '*'
      Controlled Resources:
        cpu
        memory
      Controlled Values:  RequestsOnly
      Max Allowed:
        Cpu:     1000m
        Memory:  1Gi
      Min Allowed:
        Cpu:     50m
        Memory:  64Mi
  Target Ref:
    API Version:  apps/v1
    Kind:         StatefulSet
    Name:         couchdb-couchdb
  Update Policy:
    Update Mode:  Auto

```
Stress Pods to trigger recommendation and describe VPA API Object. 

After Updater evicts pod and pods are recreated, describe pods to see his resource requests and limits.
```
Containers:
  couchdb:
    ...
    Limits:
      cpu:     2860m
      memory:  1414797856
    Requests:
      cpu:      143m
      memory:   88424866
```
So... VPA override Requests and Limits when the `controlledValues` are set to `RequestsOnly` in my case. 

**Anything else we need to know?**:

VPA is deploy with Terraform and Helm release from https://artifacthub.io/packages/helm/cowboysysop/vertical-pod-autoscaler v4.0.4 (latest).
 
The initial Resource definition from pods that are being manipulate by VPA (In Terraform syntax):

```
resources = {
      requests = {
        memory = "64Mi"
        cpu    = "50m"
      }
      limits = {
        memory = "1Gi"
        cpu    = "1000m"
      }
    }
```

The flags for Recommender components that I've used are (In order to trigger fast reactions by resource usage changes):
```
Args:
      --cpu-histogram-decay-half-life=0h5m0s
      --history-length=5m
      --history-resolution=1s
      --memory-aggregation-interval=0h5m0s
      --memory-aggregation-interval-count=8
      --memory-histogram-decay-half-life=0h5m0s
      --pod-recommendation-min-cpu-millicores=5
      --pod-recommendation-min-memory-mb=64
      --recommendation-margin-fraction=0.3
      --v=2
```

**Comment by jbartosik** [comment]
This sounds like a bug.

We have an e2e test for that. But all VPA e2e are failing right now (#4764). I'll come back to this issue when I know what's up with #4764

**Comment by jbartosik** [comment]
Is this in the same cluster as #4763? I suspect both problems might have the same cause.

If it's a different cluster than please check webhook in this cluster too.

**Comment by stoyanr** [comment]
I am not able to reproduce this issue in my test setup after #4733 is fixed. From my perspective `controlledValues: RequestsOnly` works as expected - on the next pod eviction and update by the webhook, the `limits` return to their original values set in the deployment instead of being scaled proportionally to requests.
