### ISSUE TITLE
pod didn't trigger scale-up when I add taint to the aws ASG

### ISSUE THREAD

**Issue by yourmoonlight** [kubernetes/autoscaler#4777]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:
Cluster Autoscaler 1.19.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-eks-9c63c4", GitCommit:"9c63c4037a56f9cad887ee76d55142abd4155179", GitTreeState:"clean", BuildDate:"2021-10-20T00:21:03Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS EKS

**Anything else we need to know?**:

when I manually scale one node to the node group，then everything will be fine，but when CA pod recreate，it can't scale-up

**Comment by lokeshgahlot** [comment]
@yourmoonlight 
Did you find any solution/workaround? I am facing similar issue.

**Comment by yourmoonlight** [comment]
> @yourmoonlight Did you find any solution/workaround? I am facing similar issue.
The workaround: you can monitor the CA pod's recreate, then run the scale cmd to trigger it .
