### ISSUE TITLE
VPA should validate that resources are specified with supported resolution

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#4790]
Follow up to #4774

VPA should validate that all fields that specify memory and CPU have supported resolution:

* CPU should be a whole number of milli CPUs ([documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu)),
* Memory should be a whole number of bytes ([documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory)).

Currently one can specify memory and CPU with higher resolution than K8s supports, with undesirable results (see #4774 for details).

VPA admission controller already does [validation](https://github.com/kubernetes/autoscaler/blame/1fa0716db97a0ce2b9785a954ffce5611c7a2d67/vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go#L109) of VPA objects.

In the validation we should add checks all fields which specify CPU or memory. Currently we have 2 such fields:

* [MinAllowed](https://github.com/kubernetes/autoscaler/blob/1fa0716db97a0ce2b9785a954ffce5611c7a2d67/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L170) and
* [MaxAllowed](https://github.com/kubernetes/autoscaler/blob/1fa0716db97a0ce2b9785a954ffce5611c7a2d67/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L174).

**Comment by mowangdk** [comment]
I'm newbie to this project, and I want to try it out. 

/assign

**Comment by jbartosik** [comment]
@mowangdk thank you. Please tag me on PR when you send it
