### ISSUE TITLE
Cluster Autoscaler: when the pool size has been scaled down to zero, it will never trigger new scale out.

### ISSUE THREAD

**Issue by delulu** [kubernetes/autoscaler#4805]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: Cluster Autoscaler 1.21.1

Component version: 

**What k8s version are you using (`kubectl version`)?**: 1.21.3

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: Azure VMSS

**What did you expect to happen?**: The cluster autoscale will make sure the node size will be no less than minimal node count setting.

**What happened instead?**: 

When the pool size has been scaled down to zero, it will never trigger new scale out. 
Cluster Autoscaler doesn’t work as expected to:
1.	bring the minimal nodes back
2.	trigger nodes scale out when there’re pending pods

**How to reproduce it (as minimally and precisely as possible)**:

Scale down the agent pool to zero node, the you can watch its behavior as shown above.

**Anything else we need to know?**:

**Comment by mmerrill3** [comment]
See this: https://github.com/kubernetes/autoscaler/issues/4739

**Comment by delulu** [comment]
So could someone confirm that this issue will be fixed in https://github.com/kubernetes/autoscaler/commit/8f11490c0c85fcab493af2538b4f51b0c6c72489 and resolved in cluster-autoscaler v1.22.0 onwards?
