### ISSUE TITLE
where can i get  recommend history value

### ISSUE THREAD

**Issue by aawuliliaa** [kubernetes/autoscaler#4817]
i want to get recommend history value,i didnot found any event in vpa

**Comment by ctml91** [comment]
You can use Prometheus to collect metrics from the VPA to see the recommendations over time.

**Comment by wu0407** [comment]
You can use kube-state-metrics crd metrics to expose vpa recommendation value,  and use Prometheus to collect metrics from kube-state-metrics
https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md
