### ISSUE TITLE
backport "daemonset-eviction-for-empty-nodes" and "daemonset-eviction-for-occupied-nodes" from 1.22 to 1.21

### ISSUE THREAD

**Issue by jmenan** [kubernetes/autoscaler#4830]
**Which component are you using?**:

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

With version 1.22 cluster-autoscaler introduces the possibility to manage the eviction of daemonsets differently :
- Add a flag to control DaemonSet eviction on non-empty nodes (https://github.com/kubernetes/autoscaler/pull/4162).
- Allow DaemonSet pods to opt in/out from eviction (https://github.com/kubernetes/autoscaler/pull/4172).

But in previous versions this is not possible and may cause bugs. 
One of these bugs is perfectly described in this issue: https://github.com/kubernetes/autoscaler/issues/4337

**Describe the solution you'd like.**:

backport the options `daemonset-eviction-for-empty-nodes` and `daemonset-eviction-for-occupied-nodes` to previous version of cluster-autoscaler ( ≤1.21)

**Describe any alternative solutions you've considered.**:

**Additional context.**:

In our case, this causes a bug during a downscale if there is a pod on the node that uses a PVC.
because we use an "aws-ebs-csi-driver" daemonset to manage our PVCs and in this case the "aws-ebs-csi-driver" pod is killed before our application pod and so it loses communication with its PVC

**Comment by Shubham82** [comment]
If it is valid to do then I would like to work on it.

Hi, @gjtempleton @MaciekPytel @jbartosik your thoughts on this.

**Comment by Shubham82** [comment]
Fixed it here: #4916

PTAL!

**Comment by Shubham82** [comment]
/close 
with reference to https://github.com/kubernetes/autoscaler/pull/4916
