### ISSUE TITLE
cluster-autoscaler: zone topology unschedulable pod fails scale-out topologySpread predicate check

### ISSUE THREAD

**Issue by muang0** [kubernetes/autoscaler#4848]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 1.21.2

**What k8s version are you using (`kubectl version`)?**: 1.21.5

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
v1.21.5-eks-bc4871b (shortened, can't paste from work machine)
</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: CA to scale out worker ASG nodeGroup from 2 to 3 instances.  I manually scaled out a deployment that had podTopologySpread which required a new node in the 3rd AZ. (DoNotSchedule, zone label, 1 maxSkew)

**What happened instead?**: CA failed topologySpreadConstraint predicate check (scheduler based, zone based podTopologySpread plugin)

**How to reproduce it (as minimally and precisely as possible)**: Run an eks cluster with at least two nodeGroups (asgs).  Have 2 running nodes in group1 (running in 2 out of 3 possible AZs- aws asg will automatically balance nodes between possible AZs).  Have at least one node in group2 running in the third AZ (the AZ where group1 doesn't have any nodes).  Run a deployment that is tainted so it can only be scheduled on group1.  Configure the deployment to have a zone topology constraint with DoNotSchedule and maxSkew of 1.  Then try to scale up the deployment.  My analysis behind why we are experiencing this issue is below- I am hoping someone familiar with the CA internals can comment. 

**Analysis**:

1. CA gets node infos for each group (the first matching node for each group is selected to populate that groups nodeInfo).  The labels from the node are populated in nodeInfo (with the exception of an updated hostName label) [core_utils.GetNodeInfosForGroups](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.21.2/cluster-autoscaler/core/static_autoscaler.go#L267)
2. When evaluating scale out options, CA loops through the groups and uses the corresponding nodeInfo to evaluate schedulability through predicate checks. [computeExpansionOption](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.21.2/cluster-autoscaler/core/scale_up.go#L437)
3. During the podtopologyspread predicate check, CA takes the possible set of label values from all nodes (including other nodeGroups).  This will populate the zone label for the 3rd AZ where only group2 is running (group2 from 'reproduce' section described above).  [calPreFilterState](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.21.2/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L198)
4. Because the nodeInfo object has the same zone label as one of the two nodes from group1, and the deployment doesn't have any pods associated with the zone key from group2- the skew validation will fail (our logs reflect this failure) [podtopologyspread plugin filter](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.21.2/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L325)

**Comment by krrrr38** [comment]
We have a same situation. If we restart cluster-autoscaler pod, it was resolved. w/version 1.21.2

> Pod ...web-api-544774954d-9gkt7 can't be scheduled on eks-web_api-2cbf69d8-005c-7943-6baa-dde5cdb15fbb, predicate checking error: node(s) didn't match pod topology spread constraints; predicateName=PodTopologySpread; reasons: node(s) didn't match pod topology spread constraints; debugInfo=

![Pasted_Image_2022_05_31_13_49](https://user-images.githubusercontent.com/915731/171095391-0515617d-1ec3-4347-a653-080361d8d4c3.png)

**Comment by David-Tamrazov** [comment]
Facing the same issue; a restart of the cluster autoscaler deployment fixed this problem for us as well. This is likely a problem with how we configured autoscaling groups within the cluster; we're using one group across 3 AZs right now but I wonder if we should be using 3 groups, 1 per AZ, with the `--balance-similar-nodegroups` feature. 

From the [Azure autoscaler docs](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/azure#explicit-setup) (different provider but still):

> To allow scaling similar node pools simultaneously, or when using separate node groups per zone and to keep nodes balanced across zones, use the --balance-similar-node-groups flag (default false).

There seem to be some gotchas with this from the [FAQs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-that-supported-by-cluster-autoscaler):

> - Currently the balancing is only done at scale-up. Cluster Autoscaler will still scale down underutilized nodes regardless of the relative sizes of underlying node groups. We plan to take balancing into account in scale-down in the future.
> - Cluster Autoscaler will only add as many nodes as required to run all existing pods. If the number of nodes is not divisible by the number of balanced node groups, some groups will get 1 more node than others.
> - Cluster Autoscaler will only balance between node groups that can support the same set of pending pods. If you run pods that can only go to a single node group (for example due to nodeSelector on zone label) CA will only add nodes to this particular node group.

Im now wondering if the "proper" solution for running cross-AZ autoscaling on AWS is to run 1 ASG per AZ with `--balance-similar-nodegroups` + deploy the [cluster descheduler](https://github.com/kubernetes-sigs/descheduler) to properly scale down Pods in a way that respects topology constraints?
