### ISSUE TITLE
[vertical-pod-autoscaler] log level are not applied => high volume of logs

### ISSUE THREAD

**Issue by aeimer** [kubernetes/autoscaler#4869]
**Which component are you using?**:
vertical-pod-autoscaler => recommender 

**What version of the component are you using?**:
k8s.gcr.io/autoscaling/vpa-recommender:0.10.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

I use the helm chart https://artifacthub.io/packages/helm/fairwinds-stable/vpa to deploy the VPA into our cluster.
The log level is set by default to `v=4`, so the verbosity should be pretty low.
I want see a documentation on how to set the log level.
Also the loglevels should be use adequatly. 

**What happened instead?**:
There are about two log lines per second which combines to gigabytes of nonsense log data.
The loglevel is 1 in the most cases, although 4 is set by default and I tried to overwrite it with 2.
No docuemtation on the logging levels available and how to set them could be found.
klog and in this repo no infos could be found.

It could also be a bug that somewhere a loglevel is not respected.

```
0509 11:43:41.408038       1 cluster_feeder.go:384] Using selector app.kubernetes.io/instance=asd-service,app.kubernetes.io/name=asd-service for VPA asd-service-main/asd-service
E0509 11:43:41.408054       1 cluster_feeder.go:552] Cannot get target selector from VPA's targetRef. Reason: Deployment asd-main/asd-app does not exist
I0509 11:43:41.408064       1 cluster_feeder.go:384] Using selector  for VPA asd-main/asd-app
I0509 11:43:41.408436       1 cluster_feeder.go:384] Using selector app.kubernetes.io/instance=asd-service,app.kubernetes.io/name=asd-service for VPA asd-service-main/asd-service
```

**How to reproduce it (as minimally and precisely as possible)**:

Deploy the helm chart in version 1.3.1.

**Anything else we need to know?**:

**Comment by voelzmo** [comment]
Hey @aeimer,

> The log level is set by default to v=4, so the verbosity should be pretty low.

The VPA uses `klog v2` for writing logs, where a higher number means a higher verbosity. Therefore, running it with `v=4` means all log statements with V-Level 4 and smaller will be written. This produces a huge amount of logs, as you already found out.

> I want see a documentation on how to set the log level.

You found the correct parameter `v=4`. The helm chart you linked seems to  provide this as `.Values.recommender.extraArgs`, so I guess this is where you'd want to set this to e.g. `v=1`. You shouldn't see any log statement with V-Level 2 or higher afterwards.

**Comment by aeimer** [comment]
Hi @voelzmo,
oh I see, I missed the order.
So when using `v=1` or `v=2`, the output is still very verbose:
![grafik](https://user-images.githubusercontent.com/25035182/171020383-fc59226f-7b75-440c-bed5-996f38b957bf.png)
I also wonder about these log outputs to be the lowest loglevel:
![grafik](https://user-images.githubusercontent.com/25035182/171020625-d63e9ccf-2b49-47a2-a0fc-0ffe08eeabb5.png)
May it still be a problem that there are some log prints a bit off?

BR
Alex

**Comment by voelzmo** [comment]
@aeimer: good catch! This statement seems to miss a level-guard:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L384

@jbartosik: what do you think we should guard this with? Seems like a pretty verbose piece of information, given that _every_ VPA object creates this every ~60 seconds. The recommender doesn't guard anything with a level <3 yet, so I guess we should at least put a `V(3)` in here – potentially even `V(4)`?

**Comment by jbartosik** [comment]
@voelzmo I'd say level 4 like other log statements in this file that log about frequent per-VPA-object events

**Comment by voelzmo** [comment]
@jbartosik Thanks for the suggestion, I have adapted the corresponding PR.
