### ISSUE TITLE
cloud-provider-azure 1.23.2 CA dependency is broken

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#4875]
CA has a dependency on cloud-provider-azure 1.23.2, which contains a file with [mismatched quotes](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/v1.23.2/pkg/provider/doc.go#L19) that [breaks CA tests](https://github.com/kubernetes/autoscaler/runs/6367971402?check_suite_focus=true).

Interestingly the file in CA vendor directory doesn't have the same bug. The problematic file was first introduced to CA vendor in https://github.com/kubernetes/autoscaler/pull/4689, without the bug. The only way I can think for how this would be possible is if the problem was manually fixed directly in the vendor directory (but the PR doesn't even mention anything like this). 

1. Can we update the cloud-provider-azure dependency to a version with the fix? Currently any attempt to update vendor fails, because of this bug being introduced by the update.
    * This is currently blocking 1.24 release. Is this version bump something we can safely perform last minute? The alternative is to carry the fix in the vendor (by manually removing the problematic file from vendor update commit), but this comes with its own problems. For example anyone importing CA 1.24.0 is likely to run into the very same issue (as they would get the transitive dependency, but not the modified version in CA vendor/).
3. If my guess above was correct, can we make sure not to fix any bugs or make any code changes directly in CA vendor directory going forward?

@gandhipr @marwanad @feiskyer

**Comment by x13n** [comment]
I think the long term solution (aka point 3) should be to just stop using vendor, just created https://github.com/kubernetes/autoscaler/issues/4878 for this.

**Comment by gandhipr** [comment]
I agree. Point 3 should be stopped. Apologies for #4689
<https://github.com/kubernetes/autoscaler/pull/4689>. I remember creating a
change in cloud-provider-azure.
In my opinion, we should update cloud-provider-azure dependency to a
version with a fix and verify that tests don't fail.

The alternative is to carry the fix in the vendor would be a quick fix but
will cause other issues as mentioned above.

**Comment by marwanad** [comment]
The cloudprovider version should be bumped to v1.23.11 which contains [this](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1158) fix.

**Comment by MaciekPytel** [comment]
Bumping cloudprovider to either 1.23.11 or 1.24 causes compilation error in CA azure cloudprovider. I'm guessing they shouldn't be very hard to fix, but I don't want to make last minute changes in cloudprovider I don't know and have no way of testing.

I'm leaning towards manually fixing this in vendor/, listing the import problem as a know issue and fixing it in a follow-up patch release. Unless you want to open a PR bumping the version of cloud-provider-azure and you have enough confidence that those changes are safe enough to include in 1.24.0?

**Comment by MaciekPytel** [comment]
I've updated https://github.com/kubernetes/autoscaler/pull/4871 to carry the fix in vendor. If there are no comments against this approach and / or alternative PRs with version update for Azure by tomorrow, I'd like to merge it tomorrow to unblock 1.24.0 release.

**Comment by gandhipr** [comment]
Okay, sounds good. I'll work on updating the vendor version in parallel.
Thank you.

**Comment by gandhipr** [comment]
I created this PR: https://github.com/kubernetes/autoscaler/pull/4883
fixing version issue in CA.

**Comment by gandhipr** [comment]
cherry-picking above PR to 1.22 and 1.23.
I'll push these changes onto 1.24 after release?

**Comment by feiskyer** [comment]
this should be fixed already
/close
