### ISSUE TITLE
cluster-autoscaler: Add option to disable scale down for unready nodes

### ISSUE THREAD

**Issue by gregth** [kubernetes/autoscaler#4876]
**Which component are you using?**:
Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
There are cases where a user may not want the unready nodes to be removed from a cluster. 

As an example, but not limited to, this might me useful in case a node is unreachable for a period of a time and local data live there, the node shall remain in the cluster, and possibly an admin may want to take any actions for recovering it.

**Describe the solution you'd like.**:
Provide the ability to disable scale-down for unready nodes. The Cluster Autoscaler ships with the `--scale-down-unready-time` flag, that configures "How long an unready node should be unneeded before it is eligible for scale down". Currently, if the flag is set to a negative or zero value, the unready nodes will be removed immediately. We could modify the logic of the code and if a negative value is provided, the cluster autoscaler shall disable scale down for unready nodes.

**Describe any alternative solutions you've considered.**:
Another alternative solution is to introduce a new flag for disabling scale down for unready nodes, but, we will end up with two flags that will be dependant.

**Additional context.**:

**Comment by gregth** [comment]
I have sent a PR to implement this feature, see https://github.com/kubernetes/autoscaler/pull/4877. Any feedback is more than welcome.

**Comment by drmorr0** [comment]
(imo) this is a breaking change that could cause somewhat surprising behaviour for cluster operators.  If someone sets `--scale-down-unready-time` to a negative number now, and then they upgrade CA, this could cause them to never scale down nodes again, which is not desirable.

**Comment by gregth** [comment]
> (imo) this is a breaking change that could cause somewhat surprising behaviour for cluster operators. If someone sets --scale-down-unready-time to a negative number now, and then they upgrade CA, this could cause them to never scale down nodes again, which is not desirable.

@drmorr0  As we have discussed in https://github.com/kubernetes/autoscaler/pull/4877#discussion_r890157350, we will add a separate flag for disabling the scale-down of unready nodes, instead of extending the functionality of the existing flag. 
We must -and will- keep this backwards compatible, the default behavior will be that the Cluster Autoscaler removes unready nodes, unless the user explicitly requests to not remove them via the new flag we'll introduce.
