### ISSUE TITLE
Upgrade the aws/examples/cluster-autoscaler-autodiscover.yaml to the latest release

### ISSUE THREAD

**Issue by joshross12** [kubernetes/autoscaler#4879]
**Which component are you using?**:

The cluster-autoscaler-autodiscover.yaml aws example file

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I would like to use the cluster-autoscaler-autodiscover.yaml aws example file but it is not up to date with the latest cluster autoscaler image as seen here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml#L147

**Describe the solution you'd like.**:

Update the cluster-autoscaler-autodiscover.yaml to be based off of the latest cluster autoscaler image

**Describe any alternative solutions you've considered.**:

More clear guidelines when upgrading the cluster autoscaler image tag as to what has changed over each release

**Additional context.**:

I am hoping to utilize the cluster autoscaler aws example yaml but want to get features from the latest release (v1.23.0)

**Comment by Shubham82** [comment]
Hi @joshross12 
[ClusterAutoscaler-1.24.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.24.0) is also released so can we change it to the latest one.  I think we have to change all the files under [Example](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws/examples) folder.

**Comment by Shubham82** [comment]
Hi @jbartosik @MaciekPytel @gjtempleton @mwielgus
What do you think about this?

**Comment by Shubham82** [comment]
Hi @joshross12
It is working with AWS EKS, [EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) currently has k8s version v1.22.6  as the latest version, so can we bump this to the latest minor version of CA of v1.22 which is [CA v1.22.2](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.2). k8s v1.23 for EKS will release in August 2022 as [per Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar).
Please correct me if I misunderstood anything.

Thanks

**Comment by Shubham82** [comment]
Fixed it here: #4905
