### ISSUE TITLE
Cluster autoscalar using ASG even after marking it unhealthy

### ISSUE THREAD

**Issue by tarun-asthana** [kubernetes/autoscaler#4900]
**Which component are you using?**:
Cluster autoscalar

**What version of the component are you using?**:

Component version:v1.18.2

**What k8s version are you using (`kubectl version`)?**:

$ kubectl version

v1.18.9

**What environment is this in?**:

AWS/kops

**What did you expect to happen?**:

Cluster autoscalar should not use the ASG which it has marked unhealthy

**What happened instead?**:

Cluster autoscalar maintained the desired count of the ASG 
![Screenshot 2022-05-19 at 6 34 24 PM](https://user-images.githubusercontent.com/60086012/169300212-317f8900-4964-4a2a-8138-6bc775cdc3dd.png)

**How to reproduce it (as minimally and precisely as possible)**:

The issue happened due to spot interruption hence you cannot reproduce it.

**Anything else we need to know?**:
Priority Expander: 
`priorities:
----
10:
  - ondemand-for-spot-a\.k8s2
  - ondemand-for-spot-b\.k8s2
  - ondemand-for-spot-c\.k8s2
  - spot-16-128-r5-4x-a\.k8s2
  - spot-16-128-r5-4x-b\.k8s2
  - spot-16-128-r5-4x-c\.k8s2
  - spot-8-16-c5-2x-a\.k8s2
  - spot-8-16-c5-2x-b\.k8s2
  - spot-8-16-c5-2x-c\.k8s2
  - ondemand-16-32-c5-4x-a\.k8s2
  - ondemand-16-32-c5-4x-b\.k8s2
  - ondemand-16-32-c5-4x-c\.k8s2
15:
  - spot-32-128-m5-8x-c-new\.k8s2
  - spot-32-128-m5-8x-b-new\.k8s2
  - ondemand-32-128-m5-8x-b-new\.k8s2
  - ondemand-32-128-m5-8x-c-new\.k8s2
50:
  - spot-32-128-m5-8x-a-new\.k8s2
  - ondemand-32-128-m5-8x-a-new\.k8s2`

Logs:
```
cluster-autoscaler-aws-cluster-autoscaler-chart-665597d969fwbkd aws-cluster-autoscaler-chart I0519 11:36:33.928882       1 auto_scaling_groups.go:409] Instance group spot-32-128-m5-8x-c-new.k8s2 has only 7 instances created while requested count is 42. Creating placeholder instance with ID i-placeholder-spot-32-128-m5-8x-c-new.k8s2-39.
cluster-autoscaler-aws-cluster-autoscaler-chart-665597d969fwbkd aws-cluster-autoscaler-chart I0519 11:36:33.928887       1 auto_scaling_groups.go:409] Instance group spot-32-128-m5-8x-c-new.k8s2 has only 7 instances created while requested count is 42. Creating placeholder instance with ID i-placeholder-spot-32-128-m5-8x-c-new.k8s2-40.
cluster-autoscaler-aws-cluster-autoscaler-chart-665597d969fwbkd aws-cluster-autoscaler-chart I0519 11:36:33.928893       1 auto_scaling_groups.go:409] Instance group spot-32-128-m5-8x-c-new.k8s2 has only 7 instances created while requested count is 42. Creating placeholder instance with ID i-placeholder-spot-32-128-m5-8x-c-new.k8s2-41.
cluster-autoscaler-aws-cluster-autoscaler-chart-665597d969fwbkd aws-cluster-autoscaler-chart W0519 11:36:39.232584       1 scale_up.go:380] Node group spot-32-128-m5-8x-c-new.k8s2 is not ready for scaleup - unhealthy
cluster-autoscaler-aws-cluster-autoscaler-chart-665597d969fwbkd aws-cluster-autoscaler-chart W0519 11:36:49.795781       1 scale_up.go:380] Node group spot-32-128-m5-8x-c-new.k8s2 is not ready for scaleup - unhealthy
cluster-autoscaler-aws-cluster-autoscaler-chart-665597d969fwbkd aws-cluster-autoscaler-chart W0519 11:37:00.593376       1 scale_up.go:380] Node group spot-32-128-m5-8x-c-new.k8s2 is not ready for scaleup - unhealthy
```

**Comment by drmorr0** [comment]
There is a feature in more recent Kubernetes that will "early-abort" for spot ASGs that are unavailable.  See https://github.com/kubernetes/autoscaler/pull/4489

This isn't available in 1.18 but there is a custom fork of Cluster Autoscaler that includes this feature: https://github.com/airbnb/autoscaler/tree/cluster-autoscaler-release-1.18-airbnb (this is not a supported fork though, so you're on your own if you decide to use it).
