### ISSUE TITLE
Typo in cluster-autoscaler/cloudprovider/aws/aws_wrapper.go

### ISSUE THREAD

**Issue by psimms-r7** [kubernetes/autoscaler#4903]
**Which component are you using?**:

Typo
"Failed to query launch tempate"

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_wrapper.go#L304

**What version of the component are you using?**:

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gjtempleton** [comment]
Hey, thanks for raising, if you want to raise a PR to fix this it would be more than welcome.

**Comment by Shubham82** [comment]
Hi @gjtempleton 
If no one is working on this, I'm up for it.

**Comment by Shubham82** [comment]
Fixed it here #4952
PTAL!
