### ISSUE TITLE
aws_manager.go:259] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials

### ISSUE THREAD

**Issue by varunpathy** [kubernetes/autoscaler#4922]
Hi Team,

I am facing issues with EKS ALB Cluster-Autoscaler. I have succefully deployed the ALB Cluster-Autoscaler for EKS , but its seems to be in un-stable mode right now. Its running few time’s & then goes to “CrashLoopBackOff “ state.

**Below are the error logs**:
E0527 08:22:15.158269       1 aws_manager.go:259] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp 54.239.29.25:443: i/o timeout

The EKS Cluster version I am using ---> v1.19
The EKS ALB Cluster-Autoscaler Docker Image version I am using ---> k8s.gcr.io/cluster-autoscaler:v1.14.7

I have pushed the above Docker Image version to our internal ECR repo ... to avoid throttling issues for future. Below is the attachment of mine cluster-autoscaler-autodiscover.yaml file & using kubectl to deploy the same.

[cluster-autoscaler-autodiscover.txt](https://github.com/kubernetes/autoscaler/files/8787396/cluster-autoscaler-autodiscover.txt)

Should I specify below details additonally in the yaml ?? Will that help ? 

          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional

I also saw one of the links for similar issues - https://github.com/kubernetes/autoscaler/issues/2829

Can you help me with the fix ? 

Regards,
Varun Pathy

**Comment by gjtempleton** [comment]
/area cloudprovider/aws
You're running a version of the CA significantly out of step with the EKS cluster version you're using. We [strongly recommend](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases) matching the minor version of the CA deployed to the cluster minor version.

Can you please try updating your image to the latest 1.19 CA patch release image ( `k8s.gcr.io/autoscaling/cluster-autoscaler:v1.19.2`) as a first step.

**Comment by varunpathy** [comment]
Hi Team,

After updating to CA Version to --> " k8s.gcr.io/autoscaling/cluster-autoscaler:v1.19.2 " .... I am still getting same issue's.

![image](https://user-images.githubusercontent.com/36322221/171115137-32f5e88d-6acd-4efe-a2ca-4a857970b1a5.png)

Any suggestion what to do to fix it ?? 

This link has one of the suggestions for applying the fix - https://github.com/kubernetes/autoscaler/issues/3216

Should I update the ALB Cluster Autoscaler Policy with below additional Permissions ? 

"autoscaling:DescribeInstances",
"ec2:DescribeInstanceTypes"

As these permisisons are currently not there in mine ALB Cluster Autoscaler Policy.


Regards,
Varun Pathy

**Comment by gjtempleton** [comment]
The expected IAM permissions for running the version of the CA you're using can be seen by navigating to the code at that point in time. You can see the expectations for 1.19.2 [here](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-1.19.2/cluster-autoscaler/cloudprovider/aws#iam-policy). Adding the above IAM permissions won't resolve the issue you're seeing.

There's one easy option as long as you're not using instance types not listed in [this file](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.19.2/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go), which is to use the static list shipped in the binary. You can do this by passing the command line argument `--aws-use-static-instance-list=true`.

Otherwise, you'll need to figure out why your CA is unable to reach that `index.json` file, as I can successfully reach it.

(As an aside, please copy and paste logs/console output in the future rather than screenshots of text, this makes it easier for us to help you.)

**Comment by varunpathy** [comment]
Hi @gjtempleton ,

Thanks for replying back & helping on the workaround's.

As per your suggestion I have tried updating  " **--aws-use-static-instance-list=true** " value in deployment.apps/cluster-autoscaler , using command " **kubectl -n kube-system logs -f deployment.apps/cluster-autoscaler** " . So its have additional below value's now under container spec
•	**--balance-similar-node-groups**
•	**--skip-nodes-with-system-pods=false**
•	**--aws-use-static-instance-list=true**

But still the ALB CA Pod is crashing.

Below are all the logs attached: 

sh aws_eks.sh kubectl logs cluster-autoscaler-7f5648ff68-twfgd -n kube-system >> Log1.txt
sh aws_eks.sh kubectl get event --namespace kube-system --field-selector involvedObject.name=cluster-autoscaler-7f5648ff68-twfgd >> Log2.txt
sh aws_eks.sh kubectl describe event cluster-autoscaler-7f5648ff68-twfgd --namespace kube-system >> Log3.txt
sh aws_eks.sh kubectl describe pod cluster-autoscaler-7f5648ff68-twfgd --namespace kube-system >> Log4.txt
sh aws_eks.sh kubectl -n kube-system logs -f deployment.apps/cluster-autoscaler >> Log5.txt

[Log1.txt](https://github.com/kubernetes/autoscaler/files/8804902/Log1.txt)
[Log2.txt](https://github.com/kubernetes/autoscaler/files/8804903/Log2.txt)
[Log3.txt](https://github.com/kubernetes/autoscaler/files/8804904/Log3.txt)
[Log4.txt](https://github.com/kubernetes/autoscaler/files/8804905/Log4.txt)
[Log5.txt](https://github.com/kubernetes/autoscaler/files/8804906/Log5.txt)

Below is the Cluster Autoscaler Policy & Trust
[alb-cluster-autoscaler-policy.txt](https://github.com/kubernetes/autoscaler/files/8804949/alb-cluster-autoscaler-policy.txt)
[alb-cluster-autoscaler-trust.txt](https://github.com/kubernetes/autoscaler/files/8804950/alb-cluster-autoscaler-trust.txt)

EKS Cluster Version - v1.19
"endpoint": "https://6BBEBE6F805273392D024BDEC81A0DF4.gr7.us-east-1.eks.amazonaws.com",
        "identity": {
            "oidc": {
                "issuer": "https://oidc.eks.us-east-1.amazonaws.com/id/6BBEBE6F805273392D024BDEC81A0DF4"
            }

Below are EKS Worker Node's
[root@GLUSVN-SD917527 Cluster-Autoscaler]# sh aws_eks.sh kubectl get nodes -o wide --namespace kube-system
Updated context arn:aws:eks:us-east-1:xxxxxxxxxxxxx:cluster/EKS-F1ANZO-APP01-USNV-DEV01-003 in /root/.kube/config
NAME                            STATUS   ROLES    AGE   VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                CONTAINER-RUNTIME
ip-10-181-48-66.ec2.internal    Ready    <none>   13d   v1.19.6-eks-49a6c0   10.181.48.66    <none>        Amazon Linux 2   5.4.144-69.257.amzn2.x86_64   docker://19.3.13
ip-10-181-56-171.ec2.internal   Ready    <none>   13d   v1.19.6-eks-49a6c0   10.181.56.171   <none>        Amazon Linux 2   5.4.144-69.257.amzn2.x86_64   docker://19.3.13
ip-10-181-56-253.ec2.internal   Ready    <none>   13d   v1.19.6-eks-49a6c0   10.181.56.253   <none>        Amazon Linux 2   5.4.144-69.257.amzn2.x86_64   docker://19.3.13
ip-10-181-56-254.ec2.internal   Ready    <none>   13d   v1.19.6-eks-49a6c0   10.181.56.254   <none>        Amazon Linux 2   5.4.144-69.257.amzn2.x86_64   docker://19.3.13

Also, attaching the ALB cluster-autoscaler-autodiscover.yaml file for your review.
[cluster-autoscaler-autodiscover.txt](https://github.com/kubernetes/autoscaler/files/8805047/cluster-autoscaler-autodiscover.txt)


Regards,
Varun Pathy

**Comment by varunpathy** [comment]
Below are the Errors I am getting after updating the " --aws-use-static-instance-list=true " value in the CA yaml

----------------------------------------------------------------------------------------------------------


Trace[638043721]: [599.976602ms] [599.976602ms] END
E0531 13:39:55.504052       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": dial tcp 209.54.180.124:443: i/o timeout
F0531 13:39:55.504069       1 aws_cloud_provider.go:382] Failed to create AWS Manager: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": dial tcp 209.54.180.124:443: i/o timeout
goroutine 131 [running]:

**Comment by varunpathy** [comment]
Any Workaround's that I can try ?? Should I get OIDC Connector , EKS Service Account Role checked ?? What with the Network Policies should I get checked ?? 

Any suggestions , blogs would really help. @gjtempleton ... Thanks !!!

Regards,
Varun Pathy

**Comment by foroozf001** [comment]
Is there any progress on this? I'm facing the same issue. I'm running EKS 1.22 in a private setup using VPC endpoints.

**Comment by bogdando** [comment]
I believe the solution is a) ensure a private VPC interface endpoint for STS (maybe also for autoscaler? See [private EKS blueprints](https://aws-ia.github.io/terraform-aws-eks-blueprints/advanced/private-clusters/)); b) follow https://github.com/kubernetes/autoscaler/issues/2829 and define AWS_STS_REGIONAL_ENDPOINTS, AWS_REGION; c) use cluster autoscaler >=1.17.3

I'm hitting the same issue in my private EKS playground, I will post back resultls as I have it.

**Comment by deniojunior** [comment]
I had the same error message:

```json
E0111 21:49:23.808922       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
    status code: 403, request id: 67d0fad1-77e3-425c-b87f-c3def839dbad
```

I found out later that the trust relationship of the cluster-autoscaler role was pointing to a different service account:

```json
"system:serviceaccount:sre:aws-load-balancer-controller"
```

Instead of 

```json
"system:serviceaccount:sre:cluster-autoscaler-aws-cluster-autoscaler"
```

In the end of the day it was a `ctrl+c / ctrl+v` issue 😆

**Comment by srinivasreddych** [comment]
Hello team. I have been noticing the same behavior w/ CA `1.25, .26, .27 images` on my `1.25 EKS cluster`. The CA pod restarts every few minutes. Fyi, I have extended my VPC CIDR, and launched CA and other app pods on my extended CIDR.
