### ISSUE TITLE
Cluster Autoscaler Patch Releases - June 2022

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#4924]
Hi all,

As discussed at today's SIG meeting, I'm planning on cutting patch releases for the Cluster Autoscaler this Friday (3rd June 2022).

If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

**Note:** I plan on cutting releases as far back as 1.19 up to 1.23 given there's at least [one known issue in the AWS cloud provider](https://github.com/kubernetes/autoscaler/issues/4732) which is patched in the 1.19 release branch, but hasn't made it to a release yet.

Tagging Cloud Provider implementation owners for visibility:
@ringtail @Jeffwan @jaypipes @feiskyer @nilo19 @marwanad @hello2mao @deitch @zalmarge @ArturasRa @Andrius521 @enxebre @elmiko @ hardikdr @detiber @andrewsykim @MorrisLaw @pierre-emmanuelJ @7fELF @PhilippeChepy @dbonfigli @kevin-wangzefeng @RainbowMango @avorima @schegi @piepmatz @tghartland @jlamillan @cprivitere @d-mo @deitch @displague @alphajc @ddymko

**Comment by himanshu-kun** [comment]
Hi @gjtempleton 
Just wanted to confirm timelines of the release ..

**Comment by ialidzhikov** [comment]
@gjtempleton, https://github.com/kubernetes/k8s.io/pull/3839 is merged. What is the next step? Cutting the github release?

**Comment by gjtempleton** [comment]
Hey @ialidzhikov, the merging of that PR's already published the images, so you can use them now, I just need to do the final docs pieces of pushing up tags and release notes which I'll get done today.

**Comment by himanshu-kun** [comment]
Yes having tags would be great.

**Comment by gjtempleton** [comment]
Tags and release notes now published, thanks for your patience everyone!

/close
