### ISSUE TITLE
Drop deprecated CAPI variables

### ISSUE THREAD

**Issue by enxebre** [kubernetes/autoscaler#4927]
**Which component are you using?**:
CAPI cluster autoscaler

Now CAPI has been v1beta1 for a while we should removed the old deprecated annotations for easier code base sustainability and communicate it appropriately to the community.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go#L29-L33

**Comment by enxebre** [comment]
This was closed [here](https://github.com/kubernetes/autoscaler/issues/4453) but there's still some work to do.
cc @elmiko

**Comment by elmiko** [comment]
@enxebre apologies, i thought that other PR had gotten all the references. thanks for the cleanup!
