### ISSUE TITLE
Mechanism for moving the pods to another node?

### ISSUE THREAD

**Issue by utsav2307** [kubernetes/autoscaler#494]
I understand that CA moves the pods to another nodes before deleting a node, but does it do a rolling deploy of pods ensuring no downtime when moving the pods or does it just delete the pod first and then wait for a new pod to come up on another node?

**Comment by MaciekPytel** [comment]
CA only evicts pods from node, it doesn't do a rolling deploy or anything of the sort. If you want to avoid disruptions to your service you should define a PodDisruptionBudget for your deployment. If you set minimum unavailable to 1 on your PDB, CA will respect that and only kill a pod if all the others are running.

Similarly if you set minimum unavailable to 0 CA will never touch your pods (which will likely block the scale-down).
