### ISSUE TITLE
Support whitelisting labels to ignore when balancing similar node groups

### ISSUE THREAD

**Issue by negz** [kubernetes/autoscaler#496]
Running the Cluster Autoscaler with `--balance-similar-node-groups` attempts to keep the size of identical node groups balanced when scaling up.

https://github.com/kubernetes/autoscaler/blob/d43029c/cluster-autoscaler/utils/nodegroupset/compare_nodegroups.go#L57

Per `IsNodeInfoSimilar` node groups are considered similar when a sample node from each node group has approximately the same resource capacity and labels. A fixed set of labels are ignored during this comparison - specifically hostname, failure domain, and region.

At Planet Labs we label nodes with their node group's unique identifier, which we call their pool. This label looks like `kubernetes.planet.com/pool_id=worker-7kd9`. Our node groups are typically identical and thus we would like to balance them, but they are considered dissimilar due to the existence of the `pool_id` label.

We'd like to be able to configure a set of labels for `IsNodeInfoSimilar` to ignore in addition to the hostname, failure domain, and region. This would involve passing the CA a flag like `--ignore-labels-when-comparing-node-groups=kubernetes.planet.com/pool_id,someotherlabel`. This flag would be used to set `IgnoreLabelsWhenComparingNodeGroups` in the autoscaling context, and that setting would be passed down to `IsNodeInfoSimilar` via `FindSimilarNodeGroups`.

Does this sound like a reasonable approach? If so we're happy to send a PR to implement it.

**Comment by MaciekPytel** [comment]
I'm curious what is your use-case for having those labels? I'm generally not opposed to adding something like that, just not sure how useful it would be. `--balance-similar-node-groups` only works if your nodes are similar and the same subset of pending pods can go to each "similar" node pool. So it won't necessarily work well if you'll try to use this custom label for things like nodeSelector or nodeAffinity.

**Comment by negz** [comment]
To be honest it's mostly historical and worth thinking through. We don't use the labels for node selection or affinity - I'm fairly sure they only exist so that humans can easily tie a node back to the pool it belongs to.

**Comment by negz** [comment]
Upon reflection we decided the use case for the label isn't worth adding this functionality to the CA - we'll just remove the label instead. Thanks for the perspective!
