### ISSUE TITLE
i am facing the same issue as https://github.com/kubernetes/autoscaler/issues/4775

### ISSUE THREAD

**Issue by amal786** [kubernetes/autoscaler#4968]
i am facing same issue as 
#4775
https://github.com/kubernetes/autoscaler/issues/3397
https://github.com/kubernetes/autoscaler/issues/2810

the problem is that the master branch does not create vpa-admission-controller pod and it fails on MountVolume.SetUp failed for volume "tls-certs" : secret "vpa-tls-certs" not found

and the branch vpa-release-0.8 does not create crd 
unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

for master i made changes to the gencerts.sh the changes were 

 44 openssl req -x509 -new -nodes -key ${TMP_DIR}/caKey.pem -days 100000 -out ${TMP_DIR}/caCert.pem -subj "/CN=vpa_webhook_ca"

after that also i am getting the same error 
unknown option -addext
req [options] <infile >outfile
the describe output from the pod is giving the same output 
  Warning  FailedMount  12s (x7 over 44s)  kubelet            MountVolume.SetUp failed for volume "tls-certs" : secret "vpa-tls-certs" not found
need help on this.

**Comment by jbartosik** [comment]
Hi,
I think VPA 0.9 and older won't work with K8s 1.22 and newer.

Support for CRD v1beta1 AP was removed in K8s 1.22 ([release note](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122)). [Yaml with definition of VPA CRD using v1 API](https://github.com/kubernetes/autoscaler/blob/6dc7f7a39da7ff3edd571a5d76b73c0337a3bcbf/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml#L1) was added in #3606, so it's not part of [vpa-release-0.8](https://github.com/kubernetes/autoscaler/tree/vpa-release-0.8/vertical-pod-autoscaler/deploy) branch. It's in [vpa-release-0.9](https://github.com/kubernetes/autoscaler/tree/vpa-release-0.9/vertical-pod-autoscaler/deploy) so I think [0.9.2](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.9.2)(or newer) should work.
