### ISSUE TITLE
Deprecate v1beta1 API

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#4969]
We should deprecate and remove v1beta1 API. Maintaining it is a burden, it's missing some features and we've had v1 for a long time.

I think [this](https://kubernetes.io/docs/reference/using-api/deprecation-policy/) is the relevant policy, I'll talk about it with SIG leads at SIG meeting.

**Comment by jbartosik** [comment]
I'd like to start deprecation with the next release.

**Comment by jbartosik** [comment]
From the doc I linked in the 1st comment:

> Rule #4a: minimum API lifetime is determined by the API stability level
> (...)
> Beta API versions must be supported for 9 months or 3 releases (whichever is longer) after deprecation

Since I'm trying to do releases together with K8s and K8s is doing 3 releases / year I guess this means that v1beta1 will stay around for 3 releases /  ~1 year after deprecation.

**Comment by Shubham82** [comment]
lifecycle/frozen
