### ISSUE TITLE
VPA Design Proposal give 404 error.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/autoscaler#4986]
**Which component are you using?**:

vertical-pod-autoscaler

**What did you expect to happen?**:

The hyperlink for the Design proposal of vertical-pod-autoscaler [here](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#related-links) should not give a 404 error. The correct link is:  `https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/vertical-pod-autoscaler.md`

**What happened instead?**:

The hyperlink for the Design proposal of vertical-pod-autoscaler gives a 404 error.

**Comment by voelzmo** [comment]
Seems like I missed a place in https://github.com/kubernetes/autoscaler/commit/80cdf9fd55e95bc9c24e5b5cb491929adbb583f1
Good catch, thanks!

**Comment by Shubham82** [comment]
> Seems like I missed a place in [80cdf9f](https://github.com/kubernetes/autoscaler/commit/80cdf9fd55e95bc9c24e5b5cb491929adbb583f1) Good catch, thanks!

thanks!
