### ISSUE TITLE
"cluster-autoscaler.kubernetes.io/safe-to-evict": "false" doesn't stop a node from being scaled down

### ISSUE THREAD

**Issue by steven-cherry** [kubernetes/autoscaler#4988]
Hi,

I have a hand full of pods that have the annotation cluster-autoscaler.kubernetes.io/safe-to-evict: 'false' set. However this doesn't prevent the autoscaler scaling down nodes where these pods are resident. I'm currently on version v1.22.3 running on AWS EKS 1.22 with managed node groups. The autocscaler flags I have set are

        - '--cloud-provider=aws'
        - '--namespace=kube-system'
        - >-
          --node-group-auto-discovery=asg:tag=kubernetes.io/cluster/<REDACTED>
        - '--ignore-daemonsets-utilization=true'
        - '--leader-elect=true'
        - '--leader-elect-resource-lock=endpoints'
        - '--logtostderr=true'
        - '--max-empty-bulk-delete=20'
        - '--max-graceful-termination-sec=300'
        - '--max-node-provision-time=3m'
        - '--scale-down-candidates-pool-ratio=1'
        - '--scale-down-delay-after-add=1m'
        - '--scale-down-delay-after-failure=1m'
        - '--scale-down-unneeded-time=1m'
        - '--scale-down-utilization-threshold=0.85'
        - '--skip-nodes-with-local-storage=false'
        - '--skip-nodes-with-system-pods=false'
        - '--stderrthreshold=info'
        - '--v=4'

Can anyone shed any light?

Thanks

**Comment by steven-cherry** [comment]
Discovered that this is probably being caused by 'AWS Availability Zone Rebalancing' for the AWS auto scaling group. See 'AZRebalance' in 
[](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html)

**Comment by pat-s** [comment]
This might also be the root of my current issue - I see evictions of pods which actually have `cluster-autoscaler.kubernetes.io/safe-to-evict: false` set.
