### ISSUE TITLE
Cluster Autoscaler multi cluster support

### ISSUE THREAD

**Issue by g-gaston** [kubernetes/autoscaler#5007]
**Which component are you using?**:

Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

When using a management + workload clusters topology ([capi reference](https://cluster-api.sigs.k8s.io/user/concepts.html#management-cluster)), I would like to run only one instance of the Cluster Autoscaler in the management cluster that watches all the workload clusters.

**Describe the solution you'd like.**:

I would like for the Cluster Autoscaler to be able to resize multiple clusters from one single instance.

**Describe any alternative solutions you've considered.**:

The current recommended solution is to run multiple instances of the Cluster Autoscaler in the management cluster, each configured to point to a different workload cluster.

**Additional context.**:

I would like to implement and contribute this feature, but looking for the community's interest and feedback before starting the work 🙂

**Comment by msyhu** [comment]
hi @g-gaston ! May I know where is the documentation that recommends deploying cluster autoscaler on the management cluster as many as the number of clusters? thanks.
