### ISSUE TITLE
[Azure] Cloud provider internal blocking vendor update to v.1.25.0-alpha.2 in cluster autoscaler

### ISSUE THREAD

**Issue by jayantjain93** [kubernetes/autoscaler#5009]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
master

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.25
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you expect to happen?**:
Completion in running update-vendor script : `./hack/update-vendor.sh v1.25.0-alpha.2`

**What happened instead?**:
`go mod tidy` fails with the following error:
```
...
go get: upgraded k8s.io/klog/v2 v2.60.1 => v2.70.0
go get: upgraded k8s.io/kubernetes v1.25.0-alpha.0 => v1.25.0-alpha.2
+ go mod tidy
go: finding module for package k8s.io/apimachinery/pkg/util/clock
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/azure imports
        sigs.k8s.io/cloud-provider-azure/pkg/provider imports
        sigs.k8s.io/cloud-provider-azure/pkg/nodemanager tested by
        sigs.k8s.io/cloud-provider-azure/pkg/nodemanager.test imports
        sigs.k8s.io/cloud-provider-azure/pkg/util/controller/testutil imports
        k8s.io/apimachinery/pkg/util/clock: module k8s.io/apimachinery@latest found (v0.24.2, replaced by k8s.io/apimachinery@v0.25.0-alpha.2), but does not contain package k8s.io/apimachinery/pkg/util/clock
```

**How to reproduce it (as minimally and precisely as possible)**:

Run the update vendor script on cluster-autoscaler master:
`./hack/update-vendor.sh v1.25.0-alpha.2`

**Anything else we need to know?**:

**Comment by jayantjain93** [comment]
@gandhipr Do you think you can look into this since you've recently updated the package where the issue is caused.

**Comment by jayantjain93** [comment]
You could also explore using an alternative like: `k8s.io/utils/clock`.

**Comment by gandhipr** [comment]
I am working on a fix.
Could you help me resolving following issue:

```
+ go mod tidy
+ go mod vendor
+ git rm -r --force --ignore-unmatch kubernetes
+ sed -i 's|\(const ClusterAutoscalerVersion = \)".*"|\1"1.25.0-alpha.2"|' version/version.go
sed: 1: "version/version.go": invalid command code v
```

I get this error on running  ./hack/update-vendor.sh v1.25.0-alpha.2
@jayantjain93

**Comment by jayantjain93** [comment]
If the script is running sed cmd, it means there weren't any issues with the actual vendor update.

The issue could be related to the shell that you're using. Are you using bash ?

**Comment by jayantjain93** [comment]
I think you can directly raise a PR.
