### ISSUE TITLE
`Cannot get cluster history...got result type model.Vector` with Promethus as storage

### ISSUE THREAD

**Issue by gsweene2** [kubernetes/autoscaler#5031]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

`v0.11.0` (note below I am not seeing this with `v0.10.0`)

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Minikube (also replicated on EKS)

**What did you expect to happen?**:

Expected to get the correct type back when Initializing VPA from history provider

**What happened instead?**:

Logged error
`Cannot get cluster history: cannot read last labels: expected query to return a matrix; got result type model.Vector`

**How to reproduce it (as minimally and precisely as possible)**:

Below is a bash script that will
* Restart minikube with necessary args
* Clone and install kube-prometheus
* Clone autscaler repo
* Checkout v0.11.0, patch to use prometheus as storage provider, hack-up, and save the logs to file (error seen)
* Checkout v0.10.0, patch to use prometheus as storage provider, hack-up, and save the logs to file (no error seen)

Expected `v0.10.0.logs` file
```
I0715 19:50:58.222415       1 cluster_feeder.go:229] Initializing VPA from history provider
```

Expected `v0.11.0.logs` file
```
I0715 19:50:13.957450       1 cluster_feeder.go:230] Initializing VPA from history provider
E0715 19:50:14.348896       1 cluster_feeder.go:233] Cannot get cluster history: cannot read last labels: expected query to return a matrix; got result type model.Vector
```

Script to report issue:
```bash
#!/bin/bash

set -e

# Once the scipt has been run once these can be set to false
CLONE_AND_INSTALL_KUBE_PROMETHEUS=false
RESTART_MINIKUBE=false
PATCH_RECOMMENDER_WITH_ARGS=true

SCRIPT_DIR=$(pwd)
DIRECTORY_FOR_ISSUE_DOWNLOADS=${SCRIPT_DIR}/"vpa-prometheus-storage-issue"
START="Start"
END="End"

STEP="Removing & Creating Directory for Issue Resources at ${DIRECTORY_FOR_ISSUE_DOWNLOADS}"
echo "${START}: ${STEP}"
rm -rf ${DIRECTORY_FOR_ISSUE_DOWNLOADS}
mkdir -p ${DIRECTORY_FOR_ISSUE_DOWNLOADS}
cd $DIRECTORY_FOR_ISSUE_DOWNLOADS
echo "${END}: ${STEP}"

if ${RESTART_MINIKUBE}
then
    STEP="Running Minikube to Support kube-prometheus Install"
    echo "${START}: ${STEP}"
    minikube delete && \
    minikube start \
        --kubernetes-version=v1.23.0 \
        --memory=6g \
        --bootstrapper=kubeadm \
        --extra-config=kubelet.authentication-token-webhook=true \
        --extra-config=kubelet.authorization-mode=Webhook \
        --extra-config=scheduler.bind-address=0.0.0.0 \
        --extra-config=controller-manager.bind-address=0.0.0.0 &&
    minikube addons disable metrics-server
    echo "${END}: ${STEP}"
fi

if ${CLONE_AND_INSTALL_KUBE_PROMETHEUS}
then
    STEP="Installing kube-prometheus"
    echo "${START}: ${STEP}"
    cd $DIRECTORY_FOR_ISSUE_DOWNLOADS
    git clone -b main git@github.com:gsweene2/kube-prometheus.git
    cd kube-prometheus
    git log --oneline -1
    kubectl apply --server-side -f manifests/setup
    # Having an issue with the next cmd so sleep as a quick hack
    sleep 15
    until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
    kubectl apply -f manifests/
    echo "${END}: ${STEP}"
fi

STEP="Optional: Open up and run query to verify metrics"
echo "${START}: ${STEP}"
echo "Run the following commands:"
echo "kubectl --namespace monitoring port-forward svc/prometheus-k8s 9090"
echo "container_memory_working_set_bytes{job=\"kubelet\", pod=~\".+\", name!=\"POD\", name!=\"\"}"
echo "${END}: ${STEP}"

STEP="Cloning autoscaler & cd to dir"
echo "${START}: ${STEP}"
echo $PWD
cd $DIRECTORY_FOR_ISSUE_DOWNLOADS
git clone git@github.com:kubernetes/autoscaler.git
cd autoscaler/vertical-pod-autoscaler
echo "${END}: ${STEP}"


STEP="Checkout out tag vertical-pod-autoscaler-0.11.0"
echo "${START}: ${STEP}"
git checkout vertical-pod-autoscaler-0.11.0
echo "${END}: ${STEP}"

STEP="Replace openssl with version installed with Homebrew"
echo "${START}: ${STEP}"
FILE="pkg/admission-controller/gencerts.sh"
sed -i '' 's/openssl/\/usr\/local\/Cellar\/openssl@3\/3.0.5\/bin\/openssl/g' ${FILE}
echo "${END}: ${STEP}"

STEP="Add args to recommender-deployment to use prometheus as store"
echo "Creating add.txt in dir ${PWD}"
echo "${START}: ${STEP}"
cat <<EOT > add.yaml
        args:
        - --v=4
        - --storage=prometheus
        - --prometheus-address=http://prometheus-k8s.monitoring.svc.cluster.local:9090
        - --prometheus-cadvisor-job-name=kubelet
        - --container-pod-name-label=pod
EOT
sed -i '' '/      - name: recommender/r add.yaml' deploy/recommender-deployment.yaml
echo "${END}: ${STEP}"

STEP="Run Hack Down Script (clean up before first install)"
echo "${START}: ${STEP}"
./hack/vpa-down.sh
echo "${END}: ${STEP}"

STEP="Run Hack Up Script"
echo "${START}: ${STEP}"
./hack/vpa-up.sh
echo "${END}: ${STEP}"

STEP="Wait for 60 seconds then save the logs"
echo "${START}: ${STEP}"
sleep 60
kubectl -n kube-system logs --selector app=vpa-recommender --tail=1000 | grep 'Initializing VPA from history provider\|Cannot get cluster history' > v0.11.0.logs
kubectl -n kube-system logs --selector app=vpa-recommender --tail=1000 > v0.11.0-all.logs
echo "${END}: ${STEP}"

STEP="Run Hack Down Script"
echo "${START}: ${STEP}"
./hack/vpa-down.sh
echo "${END}: ${STEP}"

STEP="Clean up deploy/recommender-deployment.yaml changes b4 checking out 0.10.0"
echo "${START}: ${STEP}"
git checkout vertical-pod-autoscaler-0.11.0 -- deploy/recommender-deployment.yaml
echo "${END}: ${STEP}"

STEP="Checkout out tag vertical-pod-autoscaler-0.10.0"
echo "${START}: ${STEP}"
git checkout vertical-pod-autoscaler-0.10.0
echo "${END}: ${STEP}"

STEP="Add args to recommender-deployment to use prometheus as store"
echo "Creating add.txt in dir ${PWD}"
echo "${START}: ${STEP}"
cat <<EOT > add.yaml
        args:
        - --v=4
        - --storage=prometheus
        - --prometheus-address=http://prometheus-k8s.monitoring.svc.cluster.local:9090
        - --prometheus-cadvisor-job-name=kubelet
        - --container-pod-name-label=pod
EOT
sed -i '' '/      - name: recommender/r add.yaml' deploy/recommender-deployment.yaml
echo "${END}: ${STEP}"

STEP="Run Hack Up Script"
echo "${START}: ${STEP}"
./hack/vpa-up.sh
echo "${END}: ${STEP}"

STEP="Wait for 60 seconds then save the logs"
echo "${START}: ${STEP}"
sleep 60
kubectl -n kube-system logs --selector app=vpa-recommender --tail=1000 | grep 'Initializing VPA from history provider\|Cannot get cluster history' > v0.10.0.logs
kubectl -n kube-system logs --selector app=vpa-recommender --tail=1000 > v0.10.0-all.logs
echo "${END}: ${STEP}"

STEP="Run Hack Down Script"
echo "${START}: ${STEP}"
./hack/vpa-down.sh
echo "${END}: ${STEP}"
```

**Anything else we need to know?**:

I checked my Prometheus dashboard and ran the queries without any issues, so I'm relatively confident they should be fine. Let me know if you see anything else to try in this setup!

Example log: `Historical memory usage query used: container_memory_working_set_bytes{job="kubernetes-cadvisor", pod_name=~".+", name!="POD", name!=""}` and query:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/14845943/179363569-997dab06-9a63-43c7-9e21-ff86c001644a.png">

**Comment by aslafy-z** [comment]
Can you try setting `metric-for-pod-labels` configuration value to `kube_pod_labels{job="kube-state-metrics"}[8d]`?

**Comment by neiser** [comment]
@aslafy-z Trying your suggestion to use `--metric-for-pod-labels=kube_pod_labels{job="kube-state-metrics"}[8d]` leads to the following (new) error:
```
E1205 06:36:53.126687       1 cluster_feeder.go:233] Cannot get cluster history: cannot read last labels: cannot get container ID from labels kube_pod_labels{container="kube-state-metrics", endpoint="http", instance="192.168.134.6:8080", job="kube-state-metrics", namespace="aad-pod-identity", pod="aad-pod-identity-mic-6f88994474-2hq8w", service="kube-prometheus-stack-kube-state-metrics", uid="1374d015-2b9c-46b1-a299-8dcd15917f54"}: no kubernetes_namespace label
```

This can finally fixed by adding the following additional options `--pod-namespace-label=namespace --pod-name-label=pod`. No errors are logged anymore on startup.

I still think this issue should be investigated, so I'm asking the bot to remove the stale label.

Additional context from my side: Running on Azure Kubernetes Service and using the [Fairwinds Helm chart](https://github.com/FairwindsOps/charts/tree/master/stable/vpa) to deploy the vpa-recommender.

/remove-lifecycle stale

**Comment by Viktor-Osika** [comment]
I had to change all those labels to make VPA recommender (0.13.0) to start w/o errors using VictoriaMetrics stack.

```
  prometheus-cadvisor-job-name: kubelet
  container-pod-name-label: pod
  container-name-label: container
  metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics"}[8d]
  pod-namespace-label: namespace
  pod-name-label: pod
```

**Comment by csepulveda** [comment]
Thank you @Viktor-Osika , that works perfectly.

**Comment by adinhodovic** [comment]
> I had to change all those labels to make VPA recommender (0.13.0) to start w/o errors using VictoriaMetrics stack.
> 
> ```
>   prometheus-cadvisor-job-name: kubelet
>   container-pod-name-label: pod
>   container-name-label: container
>   metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics"}[8d]
>   pod-namespace-label: namespace
>   pod-name-label: pod
> ```

Works to fetch the metrics, but does it work overall? Seems like every time the VPA is reset the upper boundary recommendation starts at 100GiB which I'd not expect if history works.
