### ISSUE TITLE
2 similar clusters, totally different sizing

### ISSUE THREAD

**Issue by headyj** [kubernetes/autoscaler#5032]
I have 2 similar clusters in term of pods and resources limits/requests:

eks-1
  - 263 pods
  - Memory
    - Request: 83GB
    - Limits: 174GB
  - CPU
    - Request: 26 cores
    - Limits: 78 cores

eks-2
  - 215 pods
  - Memory
    - Requests: 60GB
    - Limits: 154GB
  - CPU:
    - Requests: 26 cores
    - Limits: 78 cores

eks-1 load is a bit higher, but the difference in term of sizing done by the autoscaler is way different: 12 nodes on eks-1, 7 on eks-2

I don't really understand why, as nothing on the logs seems to show problems or misconfiguration. (neither min_size nor max_size are reached)

Both clusters are on latest available EKS version (v1.22), latest autoscaler helm chart and strictly identical configuration

I use m5a.xlarge instances. If we do the calculation, the sizing seems correct in term of memory for eks-1, but not for eks-2:

eks-1:
  - Memory: 12*16 = 184GB

eks-2:
  - Memory: 7*16 = 112GB

**Which component are you using?**:

cluster-autoscaler (helm-chart)

**What version of the component are you using?**:
helm-chart: v9.19.2
image: v1.22.1

**What k8s version are you using (`kubectl version`)?**:

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**What environment is this in?**:
AWS EKS (v1.22.9)

**What did you expect to happen?**:

both cluster should have quite similar sizing

**What happened instead?**:

both cluster have different sizing

**Comment by gjtempleton** [comment]
There's a number of different factors that could be involved here, including what scaling (both up and down) has happened before this point, and whether you're overriding the default `--scale-down-utilization-threshold` value from 0.5 for the CA to consider consolidation of nodes in the cluster.

For the second point the CA should be logging why it isn't considering nodes as candidates for scale-down, so I would look there first.

**Comment by headyj** [comment]
Yes indeed it's logging `Node ip-[....].compute.internal is not suitable for removal - cpu utilization too big (0.822704)` for all of the nodes, but I was wondering how it is possible to have such a difference between both identically configured clusters with similar usages. The first cluster has been running for much longer, so maybe it could be the reason?

I also have a descheduler on both cluster but it doesn't seems to be well integrated yet (according to descheduler roadmap: https://github.com/kubernetes-sigs/descheduler#roadmap)

In your opinion, Is there anything that could be done to "force" a recalculation or something? because the idea of the autoscaler is also to save costs, and apparently our cluster should be able to run with at least 3 to 4 less ec2 instances.

**Comment by headyj** [comment]
I don't know how CPU usage is calculated, but it seems to be way off the reality. According the AWS monitoring dashboard, CPU usage is under 10% for an hour, but still the autoscaler is not scaling down this specific node:
`Node ip-172-20-46-252.eu-west-2.compute.internal is not suitable for removal - cpu utilization too big (0.876276)`

**Comment by gjtempleton** [comment]
The Cluster Autoscaler operates only on the proportion of resources requested by the pods on the node, it doesn't scale based on the raw CPU usage.
