### ISSUE TITLE
i think larger lowerbound value is less secure than smaller lowerbound value

### ISSUE THREAD

**Issue by EchoUtopia** [kubernetes/autoscaler#5034]
https://github.com/kubernetes/autoscaler/blob/226784a223a2bc3a5c9edde714bbb6b6cc5094fb/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L115

i think for safety, we should make the range between lowerbound and upperbound broader, so we should make lowerbound smaller by passing `-*safetyMarginFraction`? am i right ?

**Comment by jbartosik** [comment]
Do we have examples of current lower bound calculation doing something undesirable?

Lowering the bound will slow down scaledowns

**Comment by jbartosik** [comment]
Yes, you're right
