### ISSUE TITLE
Version Skew Policy

### ISSUE THREAD

**Issue by riconnon** [kubernetes/autoscaler#5052]
During upgrades of kubernetes API server and/or cluster autoscaler upgrade it is inevitable that the autoscaler and other kubernetes components must have a variance in version for at least a period of time.
Looking at the various relevant docs the cluster autoscaler is not included in the overall Kubernetes Version Skew Policy here: https://kubernetes.io/releases/version-skew-policy/

Looking at the README on this repo I see
> Some user reports indicate successful use of a newer version of Cluster Autoscaler with older clusters, however, there is always a chance that it won't work as expected.

Is there a supported process to upgrade both the cluster and the autoscaler such that it is expected to continue to work throughout? It seems like the CA needs to have an official version skew policy supporting at least one minor version in one direction from the API server.

**Comment by kumarpmd** [comment]
On a similar topic, do we need to ensure cluster-autoscaler image tag values when installing cluster-autoscaler via helm charts in eks clusters?
cluster-autoscaler helm chat v9.19.2 default value for "image.tag" is "v1.23.0".  Can the chart be installed in eks 1.22 cluster?

**Comment by riconnon** [comment]
@Shubham82 I understand that recommendation but if, for example, I am going to upgrade my cluster from 1.20 to 1.21 I need to do one of two things:
1) I can ugprade my cluster (API server, kube controller manager, etc) to 1.21 first and have a window during which I have a 1.21 cluster and a 1.20 autoscaler
2) I can upgrade my autoscaler first and have a window during which I have a 1.21 autoscaler and a 1.20 cluster

In either case, as far as I can tell, the autoscaler project is saying it doesn't "support" this setup, so how can I ever upgrade from 1.20 to 1.21 since it's impossible to upgrade the two things at the exact same time.

**Comment by kumarpmd** [comment]
cluster autoscaler chart for eks 1.22 is covered in issue#[4580](https://github.com/kubernetes/autoscaler/issues/4850)..  I will repost in that issue.. thanks

**Comment by Shubham82** [comment]
> @Shubham82 I understand that recommendation but if, for example, I am going to upgrade my cluster from 1.20 to 1.21 I need to do one of two things:
> 
> 1. I can ugprade my cluster (API server, kube controller manager, etc) to 1.21 first and have a window during which I have a 1.21 cluster and a 1.20 autoscaler
> 2. I can upgrade my autoscaler first and have a window during which I have a 1.21 autoscaler and a 1.20 cluster
> 
> In either case, as far as I can tell, the autoscaler project is saying it doesn't "support" this setup, so how can I ever upgrade from 1.20 to 1.21 since it's impossible to upgrade the two things at the exact same time.

Hi @riconnon 
 In FAQ, I found this [How can I update CA dependencies (particularly k8s.io/kubernetes)?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-update-ca-dependencies-particularly-k8siokubernetes), See if it will answer your question.
There is no upgrade guide mentioned under Cluster Autoscaler.

**Comment by Shubham82** [comment]
Hi, @gjtempleton Could please take a look?

**Comment by gygitlab** [comment]
I'm also trying to reconcile this with the charts. It's not clear to me what approach is best to ensure compatibility. Best I can tell there's two potential approaches:

- Use the latest charts version to ensure we get any potential compatibility or security fixes and pin the specific Autoscaler version image to match the cluster as recommended.
- Find the last charts version that matches the autoscaler version needed and use that. Would result in potentially pretty old charts versions being installed though that could in turn have issues themselves.

Would be great to have official guidance on this.
