### ISSUE TITLE
Upgrade the openstackmagnum/cluster-autoscale image to the latest release under cloudprovider/magnum/examples

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/autoscaler#5066]
**Which component are you using?**:

Cluster Autoscaler/Openstack magnum

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I investigated the CA on magnum and found that the Cluster Autoscaler(openstackmagnum/cluster-autoscale) image used for [cluster-autoscaler-deployment-control-plane.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment-control-plane.yaml) and [cluster-autoscaler-deployment.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/magnum/examples/cluster-autoscaler-deployment.yaml) is not up to date with the latest Cluster Autoscaler image. It is a very old image of openstackmagnum/cluster-autoscale used here after that there are new images available see this: https://hub.docker.com/r/openstackmagnum/cluster-autoscaler/tags. So we will use the feature of new release.

**Describe the solution you'd like.**:

Update the openstackmagnum/cluster-autoscale image to be based on the latest Cluster Autoscaler image i.e. v1.23.0 
(openstackmagnum/cluster-autoscale:v1.23.0)

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by Shubham82** [comment]
Hi, @tghartland
What do you think about this?

**Comment by Shubham82** [comment]
If it seems good then I'm up for it. and will open a PR for it.

**Comment by tghartland** [comment]
It's worth bringing it up to date, I agree. There are two manifest examples and two values file examples that have old tags in.

If you can open a PR that would be great, thanks.

**Comment by Shubham82** [comment]
Thanks for taking look at this.

> If you can open a PR that would be great, thanks.


Yeah, I will open a PR soon.

**Comment by Shubham82** [comment]
Fixed it here: #5068
PTAL!

**Comment by tghartland** [comment]
Thanks, @Shubham82!

**Comment by Shubham82** [comment]
Welcome! @tghartland
