### ISSUE TITLE
cluster-autoscaler: Balancing scale up between different node groups does not account for node size difference

### ISSUE THREAD

**Issue by grosser** [kubernetes/autoscaler#5072]
for BalancingNodeGroupSetProcessor BalanceScaleUpBetweenGroups in cluster-autoscaler/processors/nodegroupset/balancing_processor.go

Given 3 azs with the nodes [[1x, 1x], [4x], [4x]] it will always chose the last 2 groups even though they have the highest capacity.
It should instead take the capacity into account.

I think a workable approach would be:
pass in nodeInfos, map nodes to asg via either instance ids or Comparator + templatenode (like FindSimilarNodeGroups does) and then convert to sum of capacity and use that for deciding where new nodes go

**Comment by jaypipes** [comment]
@grosser apologies for the long delay in response. Are you suggesting that the node group selection algorithm choose the node group with the *least* capacity (in aggregate across all nodes in the group)?

**Comment by grosser** [comment]
yes, it should balance by capacity
so for example `10,5,2 + 16 new nodes` -> 11,11,11
