### ISSUE TITLE
Does OCI provider support taints/tolerations?

### ISSUE THREAD

**Issue by Noksa** [kubernetes/autoscaler#5087]
I read this page https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/oci/README.md
But there is no information about taints/tolerations.

I tried to create an instance-pool with taints and when a pod is in 'Pending' state it looks like the autoscaler is not going to create an instance from a pool where we use kubelet flag `--registrer-with-taints`.

Is it possible to make autoscaler create nodes from pools with taints and toleration on a pod?

**Comment by Noksa** [comment]
Nvm, I found that code doesn't contain something like that.
I'll implement it myself

**Comment by jlamillan** [comment]
@Noksa we'd appreciate a pull request.
