### ISSUE TITLE
Release tags are wrong 1.21.3, 1.22.3, 1.23.1

### ISSUE THREAD

**Issue by FeLvi-zzz** [kubernetes/autoscaler#5089]
**Which component are you using?**:
cluster autoscaler

**What version of the component are you using?**:
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.21.3
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.3
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.23.1

**What k8s version are you using (`kubectl version`)?**:

**What environment is this in?**:

**What did you expect to happen?**:

I expected that release tags are cut to proper commits.
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.21.3 -> https://github.com/kubernetes/autoscaler/commit/c95c261d130c9c1c468da89536f6d2f5c21341fc
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.3 -> https://github.com/kubernetes/autoscaler/commit/a28edd0f3d24d224a3336d74b2051db0889a4f91
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.23.1 -> https://github.com/kubernetes/autoscaler/commit/df8acc3555f646bf8d377a8a9a4471c372c14333

**What happened instead?**:

Their tags are cut to the same commit https://github.com/kubernetes/autoscaler/commit/8037b0f9f5485e7b0d7c8b93cdabe3251aaf4fcb.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by piotrwielgolaski-tomtom** [comment]
it is really misleading, I spend few hours trying to use feature https://github.com/kubernetes/autoscaler/commit/b4cadfb4e25b6660c41dbe2b73e66e9a2f3a2cc9
that is not part of 1.23.1 but github shows it as included in tag because of tag misconfiguration.

**Comment by gregth** [comment]
This is indeed misleading and took me quite some time to understand what was going on. Are there any plans to fix the tags?

**Comment by x13n** [comment]
Looks like this is a problem with a known solution: https://stackoverflow.com/q/24849362

**Comment by x13n** [comment]
/assign @gjtempleton @MaciekPytel 

Can one of you fix this? Looks relatively simple, but I don't have the permissions.

**Comment by MaciekPytel** [comment]
I fixed this, the tags should point to the right commits now. Sorry for the confusion.
