### ISSUE TITLE
 nodegroup has no accessible CSIStorageCapacity with enough capacity for PVC

### ISSUE THREAD

**Issue by laxmanvallandas** [kubernetes/autoscaler#5093]
Which component are you using?:
CA (cluster-autoscaler)

What version of the component are you using?:
v1.22.11

k8s.gcr.io/autoscaling/cluster-autoscaler:v1.22.3

Component version:

What k8s version are you using (kubectl version)?:

v1.22.11

What environment is this in?:

AWS

What did you expect to happen?
Cluster autoscaler should scale the node from specified node group.

Ephemeral storage tag has been attached to the node group as suggested here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup

Can someone point what's missing in here?
```
I0816 06:00:54.705575       1 scheduler_binder.go:986] Node "template-node-for-1.generic-ephemeral-storage-scale-test.nodes.domain-name-9195797700036107435" has no accessible CSIStorageCapacity with enough capacity for PVC generic-ephemeral-storage-scale-test-testnamespace/generic-ephemeral-storage-scale-test-pod-scale-from-zero-0-generic-ephemeral-storage-scale-test-storage of size 1073741824 and storage class "topolvm-provisioner"
I0816 06:00:54.705592       1 scale_up.go:300] Pod generic-ephemeral-storage-scale-test-pod-scale-from-zero-0 can't be scheduled on 1.generic-ephemeral-storage-scale-test.nodes.domain-name, predicate checking error: node(s) did not have enough free storage; predicateName=VolumeBinding; reasons: node(s) did not have enough free storage; debugInfo=
I0816 06:00:54.705616       1 scale_up.go:449] No pod can fit to 1.generic-ephemeral-storage-scale-test.nodes.domain-name
```

**Comment by laxmanvallandas** [comment]
Seems like the issue is related to https://github.com/kubernetes/autoscaler/pull/3887. Wondering if there is any workaround for this until cluster autoscaler is stable to track and scale the nodes based on storage capacity on the nodes. Have verified this suggestion https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1472-storage-capacity-tracking/README.md#generic-autoscaler-support but itseems very flaky and also it doesnt seem to bring down the instances when the pods were deleted later. Any suggestions from the maintainers or may be someone able to get through the scaling of nodes based on storage capacity on the nodes?

We are using topolvm provisioner as storage class.

**Comment by Kavinraja-G** [comment]
@laxmanvallandas Did you had any progress on this issue later?
