### ISSUE TITLE
Add annotation to stop the autoscaler from moving a specific pod

### ISSUE THREAD

**Issue by vainu-arto** [kubernetes/autoscaler#510]
There is an annotation to stop specific nodes from being removed, but not one for marking pods as "do not touch". The "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" annotation only seems to work one way (you can use it to mark a pod as safe to move, not to mark a pod as unsafe to move).

**Comment by MaciekPytel** [comment]
You can achieve this with PodDisruptionBudget. Just set maxUnavailable to 0 and CA will never touch those pods.

**Comment by vainu-arto** [comment]
That works, but affects a lot of other things as well (such as draining nodes with this pod on them). I'd prefer having a specific method for affecting just the cluster autoscaler.

**Comment by DerrickMartinez** [comment]
+1 Having this would be awesome. Having an annotation not to touch it would be nice

**Comment by MaciekPytel** [comment]
I still think using PDB is the right way to do it, but I'm fine accepting a PR if someone feels like contributing one. Feel free to ping me on k8s slack if you need any help.

**Comment by vainu-arto** [comment]
How about for example long running Job pods that should not be interrupted? I can't seem to find documentation about how PDBs interact with jobs, do you have any hints?

**Comment by vainu-arto** [comment]
No, based on tests using a PDB to protect a Job does not appear to be supported at least on Kubernetes 1.9. The controllermanager logs "found no controllers for pod "test"" and "Failed to calculate the number of expected pods: found no controllers for pod "test"".

Having this annotation available to mark long running jobs as not interruptible by the autoscaler seems like the simple solution to this issue, but others exist as well. One option would be to make the cluster autoscaler use a NoExecute taint on the node instead of manually deleting each pod. In that case it would be possible to simply add a toleration to pods that should not be removed.

Yet another alternative would be to simply add the NoSchedule taint as is currently done and then wait for the currently running jobs to complete. Both of these seem rather inefficient, though.

**Comment by MaciekPytel** [comment]
PDB not working with Jobs is indeed a very good reason for this annotation. Thanks for your PR, merged.
