### ISSUE TITLE
Cluster autoscaler to support custom schedulers' Filter logic

### ISSUE THREAD

**Issue by jdheyburn** [kubernetes/autoscaler#5106]
**Which component are you using?**: 
Cluster autoscaler (CA)

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

When a Pod is being scheduled with a custom scheduler (i.e. non default-scheduler) that uses the Filter API, it can be marked as Unschedulable. When CA polls for unschedulable pods, it uses a different Filter API (I believe the non default-scheduler) to determine whether it can be scheduled on existing nodes ([from this block](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/filteroutschedulable/filter_out_schedulable.go#L49-L63)). This difference in logic can cause a pod to be stuck in Pending given that differing logic is used to determine its placement.  

**Describe the solution you'd like.**:

To allow CA to be extended to use the same Filter API as the scheduler used for the Pod that is currently in Unscheduled state, so that it can scale up the node that is required.

**Describe any alternative solutions you've considered.**:
N/A

**Additional context.**:

I am doing testing with the placement-policy scheduler plugin for this.

- https://github.com/Azure/placement-policy-scheduler-plugins/

I am also open to any other workaround to allow CA to play nicely with other schedulers, of which I am probably unaware of.

Thanks for taking the time to read this!

**Comment by vadasambar** [comment]
Looks like I can't re-open the issue. @jdheyburn you might have to re-open the issue.

**Comment by jdheyburn** [comment]
@vadasambar Thanks for picking this up, although I'm not in a position to test it out, I'll look to have a play around with it once it is released
