### ISSUE TITLE
Expanders don't seem to scale up a NodeGroup from 0

### ISSUE THREAD

**Issue by com6056** [kubernetes/autoscaler#5113]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

v1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS using the `cluster-api` provider

**What did you expect to happen?**:

`cluster-autoscaler` using expanders to select nodes that have a count of 0. ~It looks like expanders don't consider NodeGroups that don't have a count of at least 1.~ It looks like this might be an issue with the `cluster-api` provider not returning NodeGroups that are scaled to 0 actually. Right now we have a setup with multiple spot NodeGroups, many of which could be 0 due to lack of spot capacity, and whenever that happens they never get scaled back up from 0 when using an expander.

**What happened instead?**:

`cluster-autoscaler` using a priority expander only selected NodeGroups that have a count of at least 1.

**How to reproduce it (as minimally and precisely as possible)**:

Set up an expander with multiple NodeGroups, scale some of them to 0, the expander seems to never consider them again until they are scaled back up to at least 1.

**Anything else we need to know?**:

**Comment by com6056** [comment]
For anyone else running into this with cluster-api, just found this: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#scale-from-zero-support

**Comment by grzesuav** [comment]
@com6056 could you reopen this issue ? Not everyone are using CAPI along with CA

**Comment by com6056** [comment]
It wasn't actually an issue, just was a feature that wasn't actually implemented yet. I think scale from 0 support should be supported in other cases already, but happy to re-open if you still think it is needed.
