### ISSUE TITLE
cluster-autoscaler: empty node deletion is blocked by other, in-progress non-empty node deletion

### ISSUE THREAD

**Issue by alfredkrohmer** [kubernetes/autoscaler#5117]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.20.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-20T02:28:14Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-84b4fe6", GitCommit:"c813d094d1e9fa409079753049cfaa9a67524ed2", GitTreeState:"clean", BuildDate:"2022-06-09T18:20:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: AWS, EKS, self-managed node groups

**What did you expect to happen?**: 

Empty nodes should be deleted (according to the configured `--max-empty-bulk-delete` value) even when a non-empty node termination (due to binpacking) is already going on and taking a long time (due to high termination grace period of the pods).

**What happened instead?**:

Non-empty node termination (due to bin-packing) blocks termination of any other empty nodes:

(`--scale-down-unneeded-time` is at the default value of 10 minutes)

```
I0823 08:20:29.920865       1 cluster.go:187] Fast evaluation: node ip-172-20-88-250.us-west-2.compute.internal may be removed
I0823 08:20:29.920875       1 cluster.go:148] Fast evaluation: ip-172-20-91-81.us-west-2.compute.internal for removal
I0823 08:20:29.922039       1 cluster.go:332] Pod my-namespace/my-application-nginx-live-default-100-768798b5cf-9jlx9 can be moved to ip-172-20-90-16.us-west-2.compute.internal
I0823 08:20:29.922257       1 cluster.go:332] Pod my-namespace/my-application-nginx-live-default-25-5c85c9b6-hfbcx can be moved to ip-172-20-89-145.us-west-2.compute.internal
I0823 08:20:29.922567       1 cluster.go:332] Pod my-namespace/my-application-nginx-live-default-100-768798b5cf-x8dbr can be moved to ip-172-20-90-16.us-west-2.compute.internal
I0823 08:20:29.922604       1 cluster.go:187] Fast evaluation: node ip-172-20-91-81.us-west-2.compute.internal may be removed
I0823 08:20:29.922612       1 cluster.go:148] Fast evaluation: ip-172-20-91-107.us-west-2.compute.internal for removal
I0823 08:20:29.923057       1 cluster.go:332] Pod my-namespace/my-application-live-default-100-84dd6ccc94-lv8tj can be moved to ip-172-20-88-250.us-west-2.compute.internal
I0823 08:20:29.923089       1 cluster.go:187] Fast evaluation: node ip-172-20-91-107.us-west-2.compute.internal may be removed
I0823 08:20:29.923174       1 static_autoscaler.go:492] ip-172-20-91-107.us-west-2.compute.internal is unneeded since 2022-08-23 07:06:42.355339741 +0000 UTC m=+602844.173523810 duration 1h13m46.920269689s
I0823 08:20:29.923191       1 static_autoscaler.go:492] ip-172-20-80-160.us-west-2.compute.internal is unneeded since 2022-08-23 03:32:56.541968782 +0000 UTC m=+590018.360152861 duration 4h47m32.733640638s
I0823 08:20:29.923206       1 static_autoscaler.go:492] ip-172-20-82-10.us-west-2.compute.internal is unneeded since 2022-08-23 03:32:56.541968782 +0000 UTC m=+590018.360152861 duration 4h47m32.733640638s
I0823 08:20:29.923221       1 static_autoscaler.go:492] ip-172-20-82-230.us-west-2.compute.internal is unneeded since 2022-08-23 07:32:08.335720023 +0000 UTC m=+604370.153904093 duration 48m20.939889406s
I0823 08:20:29.923235       1 static_autoscaler.go:492] ip-172-20-90-16.us-west-2.compute.internal is unneeded since 2022-08-23 07:11:56.516596388 +0000 UTC m=+603158.334780454 duration 1h8m32.759013045s
I0823 08:20:29.923250       1 static_autoscaler.go:492] ip-172-20-121-78.us-west-2.compute.internal is unneeded since 2022-08-23 07:11:56.516596388 +0000 UTC m=+603158.334780454 duration 1h8m32.759013045s
I0823 08:20:29.923265       1 static_autoscaler.go:492] ip-172-20-82-209.us-west-2.compute.internal is unneeded since 2022-08-23 03:32:45.808167059 +0000 UTC m=+590007.626351124 duration 4h47m43.467442375s
I0823 08:20:29.923279       1 static_autoscaler.go:492] ip-172-20-81-197.us-west-2.compute.internal is unneeded since 2022-08-23 03:32:56.541968782 +0000 UTC m=+590018.360152861 duration 4h47m32.733640638s
I0823 08:20:29.923293       1 static_autoscaler.go:492] ip-172-20-88-68.us-west-2.compute.internal is unneeded since 2022-08-23 07:10:39.583032764 +0000 UTC m=+603081.401216842 duration 1h9m49.692576657s
I0823 08:20:29.923307       1 static_autoscaler.go:492] ip-172-20-83-112.us-west-2.compute.internal is unneeded since 2022-08-23 05:32:57.05337495 +0000 UTC m=+597218.871559021 duration 2h47m32.222234478s
I0823 08:20:29.923321       1 static_autoscaler.go:492] ip-172-20-120-229.us-west-2.compute.internal is unneeded since 2022-08-23 07:13:33.500100422 +0000 UTC m=+603255.318284494 duration 1h6m55.775509005s
I0823 08:20:29.923336       1 static_autoscaler.go:492] ip-172-20-88-250.us-west-2.compute.internal is unneeded since 2022-08-23 07:15:21.298699342 +0000 UTC m=+603363.116883416 duration 1h5m7.976910083s
I0823 08:20:29.923351       1 static_autoscaler.go:492] ip-172-20-91-81.us-west-2.compute.internal is unneeded since 2022-08-23 03:40:30.014931513 +0000 UTC m=+590471.833115589 duration 4h39m59.26067791s
I0823 08:20:29.923365       1 static_autoscaler.go:492] ip-172-20-90-79.us-west-2.compute.internal is unneeded since 2022-08-23 07:10:39.583032764 +0000 UTC m=+603081.401216842 duration 1h9m49.692576657s
I0823 08:20:29.923380       1 static_autoscaler.go:503] Scale down status: unneededOnly=true lastScaleUpTime=2022-08-23 07:09:13.657405344 +0000 UTC m=+602995.475589411 lastScaleDownDeleteTime=2022-08-23 03:40:19.264227071 +0000 UTC m=+590461.082411138 lastScaleDownFailTime=2022-08-16 07:39:45.025049 +0000 UTC m=+26.843233056 scaleDownForbidden=false isDeleteInProgress=true scaleDownInCooldown=false
E0823 08:20:33.763015       1 scale_down.go:1255] Not deleted yet my-namespace/my-application-live-default-100-84dd6ccc94-lv8tj
```

As you can see, `my-namespace/my-application-live-default-100-84dd6ccc94-lv8tj` has been evicted in order to be moved to a different node but this eviction takes some time since this pod has a high termination grace period. This in-progress pod termination prevents deletion of other empty nodes in the cluster (that are even in a different node group with different taints and tolerations).

**How to reproduce it (as minimally and precisely as possible)**:

* Trigger non-empty node deletion (due to binpacking), e.g. by removing some pods so that the resource utilization of some node goes below the configured threshold.
* Make sure that some of the remaining pods on the node have a high termination grace period.
* Wait for cluster-autoscaler to terminate the remaining pods on the node (in order to move them to another node).
* Manually empty another node so that it's unneeded.
* Observe that cluster-autoscaler doesn't delete the empty, unneeded node until the in-progress termination is finished.

**Anything else we need to know?**:

**Comment by x13n** [comment]
This is a limitation of current scale down implementation. However, it is currently undergoing major changes to allow parallel drain. This is tracked in https://github.com/kubernetes/autoscaler/issues/5079. Once the changes are implemented, this will no longer be happening.

**Comment by rcjsuen** [comment]
@x13n Hello, there are no known workarounds/configuration changes we can do for this at the moment, correct? We will just have to wait patiently for the parallel drain to be implemented I presume?

Thanks for the info!

**Comment by x13n** [comment]
Yes, unfortunately. Current scale down implementation simply aborts when there is any ongoing drain:

https://github.com/kubernetes/autoscaler/blob/d7caed33d4960da7afb2be27e3eaf78a88752889/cluster-autoscaler/core/scaledown/legacy/legacy.go#L258-L261
