### ISSUE TITLE
Cannot filter ASGs by tag value

### ISSUE THREAD

**Issue by evandam** [kubernetes/autoscaler#5121]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Docker image v1.23.0

Helm version 9.19.4

Component version:

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS with EKS managed node groups

**What did you expect to happen?**: 

ASGs with `k8s.io/cluster-autoscaler/enabled: "false"` are excluded  by the cluster-autoscaler based  on the `--node-group-auto-discovery` flag as explained in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup.

**What happened instead?**:

All ASGs with the `k8s.io/cluster-autoscaler/enabled` tag present are picked up by the cluster-autoscaler using default configuration, even if the tag value is `"false"`.

If the `--node-group-auto-discovery` has a `key=value` filter, no ASGs are found.

**How to reproduce it (as minimally and precisely as possible)**:

Run cluster autoscaler with `--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled=true,k8s.io/cluster-autoscaler/<my-cluster>`

Use two EKS node groups. One ASG tagged `k8s.io/cluster-autoscaler/enabled: "false"` and the other `k8s.io/cluster-autoscaler/enabled: "false"`

**Anything else we need to know?**:

It looks like there are some related PRs merged like https://github.com/kubernetes/autoscaler/pull/4424  and https://github.com/kubernetes/autoscaler/issues/3877, but I'm not sure if there is a release available or this solves the issue.

Even better, I think a reasonable default would be for cluster-autoscaler to check `k8s.io/cluster-autoscaler/enabled=true` rather than the tag being present, so we can easily enable/disable autoscaling for a given ASG. It's intuitive that you can set it to `false` and it will still use that ASG.

**Comment by scalp42** [comment]
I looked at `v1.22`/`v1.23`/`v1.24`, none of those versions have the commit in so it seems that values are disregarded 🤔

**Comment by rozcietrzewiacz** [comment]
+1
I just lost over a day of work due to this bug 😞
