### ISSUE TITLE
Cannot deploy cluster-autoscaler with Rancher RKE2

### ISSUE THREAD

**Issue by bennysp** [kubernetes/autoscaler#5140]
**Which component are you using?**:
cluster-autoscaler / cluster-autoscaler-chart

**What version of the component are you using?**:

Component version:
[cluster-autoscaler1.23.1](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.23.1) / [cluster-autoscaler-chart-9.20.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.20.0)

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+rke2r2", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-28T19:13:01Z", GoVersion:"go1.17.9b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
</pre></details>

**What environment is this in?**:
Dev

**What did you expect to happen?**:
Cluster Autoscaler to deploy with Helm chart to my Rancher RKE2 cluster after the changes from [PR 4975](https://github.com/kubernetes/autoscaler/pull/4975).

**What happened instead?**:
This error in the cluster autoscaler pod logs:
```shell
F0829 00:36:25.149073 1 main.go:430] Failed to get nodes from apiserver: nodes is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "nodes" in API group "" at the cluster scope
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Rancher API key (in my case, not restrictions)
2. Create Opaque Secret with you Rancher cloud-config:
<details><pre>
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |
    # rancher server credentials
    url: https://rancher.domain.com
    token: [Redacted: token-*:*]
    # name and namespace of the clusters.provisioning.cattle.io resource on the
    # rancher server
    clusterName: my-cluster
    clusterNamespace: fleet-default
    # optional, will be auto-discovered if not specified
    #clusterAPIVersion: v1alpha4
</pre></details>
3. Use the below helm values:
<details><pre>
autoDiscovery:
  clusterName: my-cluster
  labels: []
  roles:
    - worker
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}
cloudProvider: rancher
extraVolumeSecrets:
  cluster-autoscaler-cloud-config:
    mountPath: /config
    name: cluster-autoscaler-cloud-config
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  cloud-config: /config/cloud-config
  cluster-name: my-cluster
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  tag: v1.23.1
</pre></details>

**Anything else we need to know?**:
On Rancher 2.6.7 with RKE2 1.23.x.
Tried to deploy to downstream and management clusters (both on RKE2 1.23.x)

I am wondering if something is wrong in reading my deployed cloud-config?

**Comment by bennysp** [comment]
@ctrox Do you have any ideas from the above?

**Comment by ctrox** [comment]
From your message in the logs the autoscaler does not have permissions to get nodes, so I'm assuming it is missing some permissions (on the downstream cluster). If the autoscaler is running on the downstream cluster, you need to make sure the service account you set in the deployment has [these permissions](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/clusterrole.yaml) but that should happen automatically with the helm chart default values.

Also please note that cluster-autoscaler 1.23.1 that you linked does not contain the rancher provider, I'm assuming it will be in the next minor release (1.25.0).

**Comment by bennysp** [comment]
Thanks @ctrox . I was wondering about that 1.23.1. I will double check the service account.

**Comment by nugzarg** [comment]
The same issue here. cluster-autoscaler version 1.25.0, installed via helm. rancher version 2.6.9, rke2 version 1.24.4+rke2r1. Cluster type Amazon EC2. 
Autoscaler cmd:
./cluster-autoscaler --cloud-provider=rancher --namespace=kube-system --nodes=3:5:cpu-worker --cloud-config=/config/cloud-config --logtostderr=true --stderrthreshold=info --v=4

Please see cluster-autoscaler log in attached file.

[cluster-autoscaler-rancher.log](https://github.com/kubernetes/autoscaler/files/9948993/cluster-autoscaler-rancher.log)

**Comment by ctrox** [comment]
Can you try without the `--nodes` flag? The node groups are discovered dynamically (using the [annotations](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/rancher#enabling-autoscaling) on the `machinePool`) so this flag should not be needed.

Also can you tell me the `ProviderID` of one of the nodes in the pool `cpu-worker`?

```
$ kubectl describe node <node> | grep ProviderID
```

I just verified here that cluster-autoscaler v1.25.0 runs fine with an RKE2 cluster, even a way older version of `v1.21.14+rke2r1`. I'm also on Rancher 2.6.9.

**Comment by nugzarg** [comment]
Hello @ctrox ,

Without --nodes flag the result is the same. Here the snipper ftom cluster-autoscaler log:

I1107 17:39:19.455773      37 klogx.go:86] Pod ci-test/node-example-main-657d4bb7f4-fqwvn is unschedulable
I1107 17:39:19.455810      37 scale_up.go:375] Upcoming 3 nodes
W1107 17:39:19.455830      37 clusterstate.go:376] Failed to find readiness information for cpu-worker
W1107 17:39:19.455844      37 clusterstate.go:376] Failed to find readiness information for cpu-worker
W1107 17:39:19.455870      37 scale_up.go:395] Node group cpu-worker is not ready for scaleup - unhealthy
I1107 17:39:19.455889      37 scale_up.go:462] No expansion option

And the output of command kubectl describe node i-0d33022be1ed6ac78.eu-central-1.compute.internal  |grep ProviderID:

ProviderID:                   aws:///eu-central-1a/i-0d33022be1ed6ac78

**Comment by ctrox** [comment]
> ProviderID: aws:///eu-central-1a/i-0d33022be1ed6ac78

Aha, it makes sense now why it does not work with your EC2 backed cluster. This is a bit weird, looks like I (wrongly) assumed rancher would always set the `ProviderID` in a consistent way, no matter which backend node driver is used.

Just to be sure, you created your cluster with EC2 using RKE2 like so?

![image](https://user-images.githubusercontent.com/2719925/200614211-b32ed77d-f5dc-4636-b450-a0274f586b4d.png)

Would you mind sharing a full node object with `kubectl get node <node> -o yaml`? For a potential fix, I need to see if there's a way to figure out the node pool name from the node object.

**Comment by nugzarg** [comment]
Hello @ctrox ,

Yes cluster type is definitively RKE2 on EC2. Please see screenshot. 
![Screenshot_20221109_093347](https://user-images.githubusercontent.com/21188822/200748815-e9a60860-b950-44f6-9a82-ec5471206ac6.png)

Also please see node manifest yaml file in attached file. The file has txt extension, because attaching of yaml is not supported. Simple shange txt extension to yml if you want
[node.txt](https://github.com/kubernetes/autoscaler/files/9967779/node.txt)
.

**Comment by ctrox** [comment]
> Q: Rancher cloud-provider is not yet supported in the [Helm chart](https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler) right?

I have not tested it but I think it should work with the helm chart. You just need to a few values like `cloudProvider: rancher` and `cloudConfigPath` respectively.

Thanks @nugzarg, I can think of a possible fix but I'm not yet sure when I will have time for that. I will look into it more on friday.

**Comment by nugzarg** [comment]
Thanks @ctrox .
Maybe this information is also relevant. If let rancher to show the node in API (In older 2.5 version of rancher UI, which is hidden but still present),   nodePoolId key is empty and there is no nodePoolname key.
![Screenshot_20221109_175454](https://user-images.githubusercontent.com/21188822/200849270-176ea102-eb57-43e0-b9f2-34aa72acf754.png)

**Comment by ctrox** [comment]
I'm using a custom node driver which is not built-in. My guess is that just the ones that don't have a `Cloud Provider` in Rancher get a `ProviderID` `rke2://`. Anyways, it's clear to me that the autoscaler should not rely on the `ProviderID` anymore. I'm close to finishing up a PR, it will probably be done sometime next week.
