### ISSUE TITLE
helm chart installation adds --cloud-config=/etc/gce.conf automatically, which fails.

### ISSUE THREAD

**Issue by hernandev** [kubernetes/autoscaler#5143]
**Which component are you using?**:
Helm Chart.

**What version of the component are you using?**:
9.20.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:19:07Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS (EKS)

**What did you expect to happen?**:

Pod crash-looping

**What happened instead?**:
Flag/value `--cloud-config=/etc/gce.conf` is being set automatically, even with cloudProvider option of the chart being `aws` 

Config flag not being set as it is not needed on most setups.

**How to reproduce it (as minimally and precisely as possible)**:
Just deploy the helm chart without specifying `cloudConfigPath`.

**Anything else we need to know?**:

To overcome the crash-loop without downgrade, using `cloudConfigPath: ''` empty string, looks like working.

**Comment by maxres-ch** [comment]
We are also having this issue too.

**Comment by hernandev** [comment]
> We are also having this issue too.

for the moment, making the value into an empty string: 

```
cloudConfigPath: ''
```

allows moving on

**Comment by hernandev** [comment]
> We upgraded to [9.20.1](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-9.20.1) and it's fixed there. @hernandev

Thank you very mich @maxres-ch
