### ISSUE TITLE
Ways for VPA recommender to support other sources of data.

### ISSUE THREAD

**Issue by lallydd** [kubernetes/autoscaler#5153]
**Which component are you using?**:
`vertical-pod-autoscaler/pkg/recommender`

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
We collect our own metrics separately.  `metrics-server` is redundant.

**Describe the solution you'd like.**:
Enable some way:
* via RPC to another metrics client system
* some plugin mechanism
* (or something else)

To have the recommender use a separate metrics source than `metrics-server`.

**Describe any alternative solutions you've considered.**:
Nothing good comes to mind.  We have a custom fork that's almost all redundant code with the stock `recommender`.

**Additional context.**:
In our case, Datadog already collects metrics for all of our Kubernetes clusters, and has a simple API to get the metric values.  Feeding metrics from the API to the `recommender` is substantially easier than maintaining a deployment to `metrics-server`.

**Comment by jbartosik** [comment]
Can you come to SIG meeting to talk about this?

- I think it makes sense to allow getting data from different sources.
- I won't have capacity to design or implement this but I can help (discuss, review, make suggestions).
- I'm worried about testing and maintenance:
  - Can we have automated e2e tests to make sure this keeps working?
  - I don't have any experience with Datadog so what happens if it turns out it needs some work (likely I won't be able to help)?
    - This reminds me of discussions Cluster Autoscaler recently were having about their support for cloud providers, maybe we can ask them what they worked out and see if something similar would work here?

**Comment by lallydd** [comment]
Hi! Form the SIG meeting, this is my recollection (please correct me when I've remembered incorrectly) of the discussion:

- The VPA recommender can follow the cluster-autoscaler model, where different metrics sources provide different implementations of an interface
- 3rd parties (like us at Datadog) may provide alternative implementations of the interface
- The implementations must (a) compile and (b) not have too many dependencies and (c) not have conflicting dependencies with what's already in the recommender
- The 3rd parties are responsible for the interface implementations.
- Interface discussion is ongoing, but can start with a proposal in this Issue.

I propose using the [`metrics.v1beta1.PodMetricsGetter` and its included `PodMetricsInterface` as the interface](https://github.com/lallydd/autoscaler/blob/lally%2Fdd-vpa/vertical-pod-autoscaler/vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/podmetrics.go#L32-L44):
```golang

// PodMetricsesGetter has a method to return a PodMetricsInterface.
// A group's client should implement this interface.
type PodMetricsesGetter interface {
	PodMetricses(namespace string) PodMetricsInterface
}

// PodMetricsInterface has methods to work with PodMetrics resources.
type PodMetricsInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.PodMetrics, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.PodMetricsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	PodMetricsExpansion
}
```

**Comment by lallydd** [comment]
RE: the automated tests, I've used a recorded result from the Datadog API as an offline test.

**Comment by jbartosik** [comment]
Hi,
I took a look. I think I need to look some more. I'm still thinking / asking around. I'm not very confident in what I think but I thought I should let you know:

1. I'm not sure about using `PodMetricsesGetter`:
  a. We don't control the interface. If we need to update the dependency and the interface changes we'll need to update all metric providers
  b. It might be bigger than we need, [MetricsClient](https://github.com/kubernetes/autoscaler/blob/832154bd2c1d252ed6a10abad459c25fb74714b4/vertical-pod-autoscaler/pkg/recommender/input/metrics/metrics_client.go#L45) might be all we need (I still need to check if it's all we need),
 2. I think we also need to tell VPA which metrics provider it should use. How do we do that? My first thought is have a function which returns implementation chosen by a flag. I want to check how CA(Cluster Autoscaler) does this with cloud providers.
 3. I want to check how CA allows excluding cloud providers from some of its builds (IIRC someone said during SIG meeting that they do)
 4. I want to check what images CA releases with regards to built in cloud providers (and follow their example, to check if we'll need to provide more images in release)

**Comment by lallydd** [comment]
So, roughly, does this mean using this interface https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/interfaces.go#L40-L57 inside the `recommender`?  

I see the appeal, and it seeems reasonable.    My only concern is the user configuration for the metric.  Generally we only want the measurement of each resource that corresponds to its recommendation (e.g., RSS for RAM, `top(1)` CPU usage for CPU).  Is there some way to avoid or strongly discourage misconfiguration?

**Comment by jbartosik** [comment]
Yes, VPA recommender would use `MetricsClient` interface to get metrics.

I'm not sure I understand your question about misconfiguration.

Are you considering which of two approaches:

1. Allow users to configure which metrics to use on per-VPA-object level
2. Allow configuring VPA recommender which metrics to use (for all VPA objects it generates recommendations for)

?

**Comment by lallydd** [comment]
For configuration, different measurement systems (e.g., `metrics-server`, Datadog, others) will likely have different names for container CPU / Memory usage.  So we'll have to configure that somehow.

As for the two approaches, I think (2) is likely necessary - we shouldn't require each `VerticalPodAutoscaler` to have more configuration when it's all the same for every instance in a cluster.  As for (1), I think that's a separate and longer discussion.

**Comment by lallydd** [comment]
Clarifying: when calling
```golang
 GetExternalMetric(metricName string, namespace string, selector labels.Selector)
```

The `metricName` arg needs a value, and we have to call it twice, once for CPU metrics, once for RAM.

So, if the `recommender` took three more command-line args:
```
  --use-external-metrics
  --external-metrics-cpu-metric=kubernetes.cpu.usage.total
  --external-metrics-memory-metric=kubernetes.memory.usage
```

This could configure the `recommender` to both call the external metrics provider and use the right values for the `metricName` parameter of `GetExternalMetric`.  I used the appropriate Datadog metric names here as an example.

**Comment by jbartosik** [comment]
Sounds good to me. We could look at HPAs e2e tests [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go) ([dashboard](https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gci-gce-autoscaling-hpa-cm)) and have similar tests to ensure we notice if the feature breaks.
