### ISSUE TITLE
[VPA] Limit Pod eviction across Availability Zones

### ISSUE THREAD

**Issue by fsalazarh** [kubernetes/autoscaler#5169]
Is there a way that I can limit the eviction of Pods across Availability Zones? 

In my case, I have a database deployed as a StatefulSet, where using `topologySpreadConstraints` we have the pods evenly distributed among the different availability zones. However, when VPA decides to evict Pods, it is zone agnostic and that doesn't allow me to control high availability well. I understand that I can control the ratio of pods to delete, but it would be nice to be able to control that ratio across Availability Zones.

**Comment by jbartosik** [comment]
I don't recall anything that would have that effect and didn't find anything when I looked for it.

It sounds like an useful feature. Currently I don't have capacity to work on this. Please let me know if you're interested in contributing
