### ISSUE TITLE
[cluster-autoscaler v.1.23.0] calls /apis/storage.k8s.io/v1beta1/csistoragecapacities

### ISSUE THREAD

**Issue by tomsucho** [kubernetes/autoscaler#5171]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
v1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:
EKS 1.21 and doing readiness checks for 1.22 upgrade

**What did you expect to happen?**:
The controller should not call deprecated APIs which are removed in 1.22

**What happened instead?**:
I can see in EKS audit logs controller makes API requests like follows:
<html>
<body>

 col1 | col2
-- | --
kind | Event
level | Request
objectRef.apiGroup | storage.k8s.io
objectRef.apiVersion | v1beta1
objectRef.resource | csistoragecapacities
requestReceivedTimestamp | 2022-09-06T15:19:58.475565Z
requestURI | /apis/storage.k8s.io/v1beta1/csistoragecapacities?allowWatchBookmarks=true&resourceVersion=608280711&timeout=7m36s&timeoutSeconds=456&watch=true
responseStatus.code | 200
responseStatus.message | Connection closed early
responseStatus.status | Success
sourceIPs.0 | 10.0.67.160
stage | ResponseStarted
stageTimestamp | 2022-09-06T15:27:34.476026Z
user.extra.authentication.kubernetes.io/pod-name.0 | aws-cluster-autoscaler-84f59d8855-qtxgn
user.username | system:serviceaccount:kube-system:aws-cluster-autoscaler
userAgent | Go-http-client/2.0
verb | watch

</body>
</html>

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by TekTimmy** [comment]
We are on EKS v1.23.x and use the according autoscaler 1.23.1 and have no problems. Did you check if autoscaler version 1.23.1 fixes the problem ?

**Comment by tomsucho** [comment]
@TekTimmy I guess it is no issue then, if it works fine on 1.23.x then definitely this API call is not necessary and if it fails the auto-scaler controller must be running okay still. Thanks for confirmation this can be closed I guess as it doesn't cause any harm, tho calling obsolete APIs is still not perfect and will produce API server errors I guess.
