### ISSUE TITLE
Tags Point To Same Commit

### ISSUE THREAD

**Issue by jonathanmeier5** [kubernetes/autoscaler#5179]
Hey all, thanks for the work you do. The community really appreciates it!

I was poking around today and noticed that three release tags all point to the same commit:
```
$ git tag --points-at 8037b0f
cluster-autoscaler-1.21.3
cluster-autoscaler-1.22.3
cluster-autoscaler-1.23.1
```

Is this intentional? It felt a little funky, so I wanted to flag.

**Comment by FeLvi-zzz** [comment]
It's duplicate
https://github.com/kubernetes/autoscaler/issues/5089
