### ISSUE TITLE
Error string for making a POD unschedulable is not printed

### ISSUE THREAD

**Issue by abhijit-dev82** [kubernetes/autoscaler#5186]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:
1.23

What version of the relevant component are you using? Either the image tag or helm chart version.
"k8s.gcr.io/autoscaling/cluster-autoscaler-amd64:v1.23.1"

Component version:

**What k8s version are you using (`kubectl version`)?**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+vmware.wcp.2", GitCommit:"0f23d9e39892fef2a7e9da16d6b517d579a3164d", GitTreeState:"clean", BuildDate:"2022-05-26T18:56:08Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

**What environment is this in?**:

vSphere

**What did you expect to happen?**:
In the routine filterOutSchedulableByPacking(), if POD is marked  as unschedulable on a NODE , the error string is not printed.

"nodeName, err := predicateChecker.FitsAnyNode(clusterSnapshot, pod)"
Thus making it difficult to decode why a node is unscheduable.

What behaviour did you expect to see?
Error string  returned from "predicateChecker.FitsAnyNode()" for marking a POD unscheduable should be printed in logs.

**What happened instead?**:
No error string for POD  which is marked as "unscheduable"

What behaviour did see instead?
No error string was printed.

**How to reproduce it (as minimally and precisely as possible)**:
Trigger Cluster autoscaling using CAPI as provider.

**Anything else we need to know?**:

None

**Comment by abhijit-dev82** [comment]
Stale issue

**Comment by shazib-summar** [comment]
what happened here? is this fixed?
