### ISSUE TITLE
When will the vpa recommender set the recommended value for the vpa's status？

### ISSUE THREAD

**Issue by AllenZMC** [kubernetes/autoscaler#5219]
**Which component are you using?**:
vertical-pod-autoscaler

**What version of the component are you using?**:
0.9.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by jbartosik** [comment]
VPA will set recommendation after it calculates it. If everything is configured correctly (VPA is pointing to an existing controller, there are pods running in the controller, pods are reporting metrics, VPA can get metrics) first recommendation should appear after a few minutes (~1 minute for sample to appear, some time for VPA to get the metric, calculate recommendation and write it).

If this doesn't answer your question then please provide some more context (why are you asking? do you have a VPA object when recommendation doesn't appear as quickly as you'd expect? how long does it take for the recommendation to appear?)

**Comment by AllenZMC** [comment]
@jbartosik   `Cannot get ContainerMetricsSnapshot from MetricsClient. Reason: Get "https://172.30.0.1:443/apis/metrics.k8s.io/v1beta1/pods": stream error: stream ID 97; INTERNAL_ERROR`

**Comment by jbartosik** [comment]
Looks like a log indicating some problem with getting metrics

I can't say anything more just from that, pleas provide some more details.
