### ISSUE TITLE
CA Should cross-reference availability zone with instance type before attempting scale up

### ISSUE THREAD

**Issue by dan-tw** [kubernetes/autoscaler#5224]
**Which component are you using?**: 

Cluster Autoscaler on AWS

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: 

Currently the CA will attempt to scale up an instance in an availability zone it is not available in without first checking.

 For example, if I create:

A managed node group with:
Instance type: `g5.xlarge`
Region: `eu-west-2`
Availability Zones: `eu-west-2a`,  `eu-west-2b`, `eu-west-2c`

And I attempt a scale up, when it gets attempts AZ `eu-west-2c`, I get the following:

_Launching a new EC2 instance. Status Reason: Your requested instance type (g5.xlarge) is not supported in your requested Availability Zone (eu-west-2c). Please retry your request by not specifying an Availability Zone or choosing eu-west-2a, eu-west-2b. Launching EC2 instance failed._

**Describe the solution you'd like.**: 

The CA should check that an instance type is available in the AZ it is about to request, before attempting to scale out the ASG instances in that AZ.

**Describe any alternative solutions you've considered.**:

**Additional context.**:

CA version: `cluster-autoscaler:1.25.0-alpha.2`
Kubernetes Version: v1.22

**Comment by drmorr0** [comment]
AFAICT this information is not currently exposed by AWS; the availability is only specified at a per-region level, not a per-AZ level.

As an aside, cluster autoscaler expects that every instance in a node group is identical, _including_ the AZ.  In your example, if you have three AZs specified in your node group, and AWS is unable to fulfill capacity in a single AZ, cluster autoscaler will mark the entire node group as "unavailable" and will refuse to attempt to scale it again until the backoff limit is reached.  I recommend splitting your node groups into 3 so that you are still able to provision nodes in a different AZ even if one is unavailable.

**Comment by TekTimmy** [comment]
You can have many ASGs, so you can create a single node group for the according AZ with the desired instance type.

**Comment by dan-tw** [comment]
> AFAICT this information is not currently exposed by AWS; the availability is only specified at a per-region level, not a per-AZ level.

It is definitely available

**AWS CLI Tool**

`aws ec2 describe-instance-type-offerings --filters "Name=location,Values=eu-west-2a" --location-type availability-zone --region eu-west-2`

**GO AWS SDK**

```go
mySession := session.Must(session.NewSession())
ec2Client := ec2.New(mySession, aws.NewConfig().WithRegion("eu-west-2"))
offerings, err := ec2Client.DescribeInstanceTypeOfferings(&ec2.DescribeInstanceTypeOfferingsInput{
	Filters: []*ec2.Filter{
		{
			Name:   aws.String("location"),
			Values: aws.StringSlice([]string{"eu-west-2a"}),
		}},
	LocationType: aws.String("availability-zone"),
})
if err != nil {
	log.Fatalln(err)
}

fmt.Println(offerings.InstanceTypeOfferings)
```

> As an aside, cluster autoscaler expects that every instance in a node group is identical, _including_ the AZ. In your example, if you have three AZs specified in your node group, and AWS is unable to fulfill capacity in a single AZ, cluster autoscaler will mark the entire node group as "unavailable" and will refuse to attempt to scale it again until the backoff limit is reached. I recommend splitting your node groups into 3 so that you are still able to provision nodes in a different AZ even if one is unavailable.

Seems to me like a lot of unnecessary work for something that the CA can handle on it's own

**Comment by dan-tw** [comment]
If I were to split my ASG into one for each AZ, how do I prevent extra scaling?

Right now, for example, I have 1 ASG with 3 AZ's and if I have the maximum limit of instances set to 5 for example, that one ASG will scale up to 5. If I have 3 ASG's, one for each AZ,  all set to maximum 5 instances .. that is a potential 15 maximum nodes that we can scale out to (more than the 5 that was desired).

Is there any way around this?
