### ISSUE TITLE
Behavior change in daemonset pod eviction

### ISSUE THREAD

**Issue by jdn5126** [kubernetes/autoscaler#5240]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
v1.21.3

Component version: v1.21.3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:22:16Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS EKS

**What did you expect to happen?**:
Daemonset pods, especially those marked `system-node-critical`, to either not be evicted by default or to be evicted only after all other pods are evicted.

**What happened instead?**:
Daemonset pods were evicted before other non-critical and non-daemonset pods.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy daemonset pod without the `cluster-autoscaler.kubernetes.io/enable-ds-eviction` annotation and without `--daemonset-eviction-for-occupied-nodes=false`.
2. Deploy other pods on node with high termination grace period
4. Schedule node eviction
5. See that daemonset pod is evicted before other pods

**Anything else we need to know?**:
I understand that `cluster-autoscaler.kubernetes.io/enable-ds-eviction` and `--daemonset-eviction-for-occupied-nodes` were added to control daemonset pod eviction, but the default behavior on occupied nodes changed from "do not evict daemonset pods" to "evict daemonset pods unless annotation is present". This behavior change can lead to regressions and unexpected changes.

If the default behavior cannot be changed back, it seems like daemonset pods, or even more specifically `system-node-critical` pods, should not be evicted until all other pods are evicted. Adding issue #4337 for referencing similar discussion

**Comment by jdn5126** [comment]
Any thoughts on this?

**Comment by Kuzbekov** [comment]
We faced the same situation in GKE (1.24.6-gke.1500) with managed local dns service. Our services have slight delay while stopping, but local dns usually stops faster than some workloads and that leads to failed requests. 
The problem is that we can't change needed settings of autoscaler, and can't change annotations of daemonset because it could be overwritten by cloud.

**Comment by dims** [comment]
xref: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/253
