### ISSUE TITLE
Documentation for ignore-taint

### ISSUE THREAD

**Issue by hterik** [kubernetes/autoscaler#5251]
**Which component are you using?**: 
Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
I would like to understand how to best use ignore-taint.
Both the command-line argument `--ignore-taint`, and the annotation prefix `ignore-taint.cluster-autoscaler.kubernetes.io/`.
See below for exact use case.

**Describe the solution you'd like.**:
Behaviour, use cases and examples for ignore-taint explained in **_cluster-autoscaler/FAQ.md_**

**Describe any alternative solutions you've considered.**:
`go run main.go --help`, very brief explanation.

Reading the source code. It get quite hairy for an outsider when starting with the ClusterSnapshot stuff.

Digging through issues,

- Here is where i found the best explanation so far: https://github.com/kubernetes/autoscaler/issues/3985#issuecomment-812417839
  > The _only_ use-case supported by ignore-taint is one where a node requires additional custom initialization (ex. installing drivers, starting some DS) before it can accept pods. In this case node can be started with ignore-taint and the taint can be removed once the initialization is done.
  >
  > As long as the node has an ignore-taint CA will treat it as still booting up / unready. This is needed to avoid infinite scale-up (node is created with ignore-taint, pods remain pending, CA immediately triggers scale-up again, this cycle repeats until the taint is removed from some nodes). Since a node with ignore-taint is unready as far as CA is concerned, once there are enough such nodes in the NodeGroup CA will start treating the NG as unhealthy (thresholds are controlled by --max-total-unready-percentage, --ok-total-unready-count).
 
- PR describing use case waiting for DaemonSets to init: https://github.com/kubernetes/autoscaler/pull/2758
- PR adding annotation-prefix: https://github.com/kubernetes/autoscaler/pull/2733
- PR adding --ignore-taints flag: https://github.com/kubernetes/autoscaler/pull/2493 
   > for example if they have their own readiness labels or other markings that should not affect balancing behaviour.

---------------------------

**Additional context.**:

To explain the situation i'm trying to solve.
We have batch oriented pods that need to run on nodes with a pre-warmed cache in a shared hostPath. Network PVs don't work for this. Each batch takes around 10 minutes to process, pre-baking the cache takes 30 minutes. Each warm node can handle 3 such pods at a time.
Image you have one node N1, already serving 3 pods, P1,P2,P3. Now fourth pod, P4, is added to the scheduler-queue. Autoscaler sees that one pod is unschedulable and starts a new node N2. 
Now N2 will not be able to serve the fourth pod until it has prepared the cache, which will take 30 minutes, but we also know that any of P1,P2,P3 will finish in only 10, so when that happens it's better to put P4 onto N1, while N2 is still warming up. (The load pattern is such that even after this, N2 will not be redundant because the queue is having consistent pressure with additional P5,6,7...)

To do this, i was imagining one could add a taint to the NodePool, `CachePrepared=false:NoSchedule`, a DaemonSet tolerating this taint will start on the Node, prepare the cache and remove the taint. All other pods get blocked from scheduling on the node until the taint is removed.

From my understanding, `--ignore-taint CachePrepared` would solve the situation of creating N2 even though it can not schedule P4 according to its template. What i'm unsure about is what happens after that, will the autoscaler understand that N2 is upcoming or will it still consider P4 as unschedulable and allocate a new N3?

If it makes any difference, using AKS with the built in autoscaler.

**Comment by Rangudu** [comment]
Which component are you using?:
Cluster Autoscaler

Is your feature request designed to solve a problem? If so describe the problem this feature should solve.:
I would like to understand why --ignore-taint was reused to perform the extension 
https://github.com/kubernetes/autoscaler/pull/2758
This extension is marking all the existing nodes as NotReady and eventually marking the cluster as unhealthy stalling scaling on our cluster.

Describe the solution you'd like.:
Behavior, of the ignore-taint is supposed to be used to help with CA not stopping scaling up even when its local node templates have some taints which should ignored for scaleup.

Describe any alternative solutions you've considered.:

We dont have an alternate solution here.

Additional context.:

We are using EKS and we do want to differentiate between different workloads from different accounts so that pods from two different accounts wont land-up on the same node. for this we are using taints. but due to that CA was not able scale-up the cluster as it is seeing taints on the existing nodes while build node templates hence we have added this --ignore-taint flag https://github.com/kubernetes/autoscaler/commit/92ea680f1a1ab726ff4d2e85969bf2137ef4a967 as a solution for that. but the problem with the recent changes on this flag is that these nodes are considered as notready and eventually stalling the CA as all the node groups ending up in un healthy state.

**Comment by azylinski** [comment]
Hi @hterik, @Rangudu - I was recently working on this functionality and I totally agree - it is confusing and it should be documented.

If I may add one more caveat:
> Now N2 will not be able to serve the fourth pod until it has prepared the cache, which will take 30 minutes

The CA clusterstate would consider node with an `ignore-taint` `NotStarted` for 15 minutes, which is a hardcoded value (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/clusterstate/clusterstate.go#L552). After that time, if the taint would not disappear, that node is marked as `Unready` (unjustified) and it might treat the whole NodeGroup as unhealthy (see the MaxTotalUnreadyPercentage param).

This brings even more need to document it well and possibly refactor :) 

I've prepared a PR: #5590 to improve naming, so it better represents it's current functionality. If you can have a look there, it would be great.

**Comment by singhprincejeet** [comment]
> Hi @hterik, @Rangudu - I was recently working on this functionality and I totally agree - it is confusing and it should be documented.
> 
> If I may add one more caveat:
> 
> > Now N2 will not be able to serve the fourth pod until it has prepared the cache, which will take 30 minutes
> 
> The CA clusterstate would consider node with an `ignore-taint` `NotStarted` for 15 minutes, which is a hardcoded value ([`master`/cluster-autoscaler/clusterstate/clusterstate.go#L552](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/clusterstate/clusterstate.go?rgh-link-date=2023-03-13T09%3A53%3A31Z#L552)). After that time, if the taint would not disappear, that node is marked as `Unready` (unjustified) and it might treat the whole NodeGroup as unhealthy (see the MaxTotalUnreadyPercentage param).
> 
> This brings even more need to document it well and possibly refactor :)
> 
> I've prepared a PR: #5590 to improve naming, so it better represents it's current functionality. If you can have a look there, it would be great.

The link in the comment refers to this [line](https://github.com/kubernetes/autoscaler/blob/acdeb92a15bc9ba01c188e8e6c0673f681c87251/cluster-autoscaler/clusterstate/clusterstate.go#L552) I suppose. Master is not the same since the day the comment was made.

**Comment by hterik** [comment]
This has been mostly solved in https://github.com/kubernetes/autoscaler/pull/6218  Thanks @piotrwrotniak :+1: 
Some more examples and description around the connection to Unready timeouts would be nice, but I'm equally happy to close this in current state also.
