### ISSUE TITLE
How often are Cluster Autoscaler Patch Releases cut?

### ISSUE THREAD

**Issue by FeLvi-zzz** [kubernetes/autoscaler#5253]
**Which component are you using?**:

Cluster Autoscaler

I merged cherry-pick PRs into the v1.21 ~ v1.23 release branches 2 months ago, but patch releases haven't been cut yet.

I'd like someone to release patches, however I have no idea how often are they cut and who should I ask.

FYI
previous release was in June.
https://github.com/kubernetes/autoscaler/issues/5253

**Comment by voelzmo** [comment]
/remove-lifecycle stale

This seems like a relevant question: Do we have an official guideline/policy of what people can expect in release frequency? Documenting this might help for the future.

**Comment by voelzmo** [comment]
I think this is clarified by https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#patch-releases in the meanwhile?
/close
