### ISSUE TITLE
Autoscaler version

### ISSUE THREAD

**Issue by h326370** [kubernetes/autoscaler#5258]
Hi 
It is mandatory for Cluster Autoscaler version to matches the Kubernetes major and minor version of eks cluster . Or we can also run Autoscaler with higher version .

Thanks
Himanshu

**Comment by Shubham82** [comment]
yes, It is strongly recommended to use Cluster Autoscaler minor release branch that matches the k8s minor version. 
for example Use CA v1.23.x with k8s 1.23.x

**Comment by Shubham82** [comment]
Hi @h326370,
Closing this issue, as your query is answered. Please open it again if you will have any doubts.

/close
