### ISSUE TITLE
Is VPA `UpdateModeAuto` still an experimental feature

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/autoscaler#5262]
/kind documentation

The default value of PodUpdatePolicy.UpdateMode is “Auto”.
https://github.com/kubernetes/autoscaler/blob/0a46483c07b9422db58168893bc3a6dfb634cd44/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L111

It's a bit confusing because the [README](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#quick-start) says “NOTE: This feature of VPA is experimental and may cause downtime for your applications.“.

Should we avoid using Auto in production? Or, README is just too old and “Auto” is ready to be used in production, no longer an experimental feature now?

**Comment by Shubham82** [comment]
Duplicate of #5245
There is already a discussion going on this issue, PTAL!

**Comment by sanposhiho** [comment]
Thanks for letting me know.
/close
