### ISSUE TITLE
Hetzner Autoscaler does not allow subnets for HCLOUD_NETWORK

### ISSUE THREAD

**Issue by ifeulner** [kubernetes/autoscaler#5263]
**Which component are you using?**:
Horizontal autoscaler

The hetzner implementation , see https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/hetzner

**What version of the component are you using?**:
1.25.0

Component version: 1.25.0
**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:
If a subnet_id will be provided, the right subnet network will be used for assigning an ip when creating the autoscaler node

Autoscaler nodes get an ip out of the range specified in the subnet network
**What happened instead?**:

Node creation fails

**How to reproduce it (as minimally and precisely as possible)**:
Specificy an subnet id in `HCLOUD_NETWORK' instead of a network id

**Anything else we need to know?**:

**Comment by apricote** [comment]
Unfortunately this is not easily possible through the Hetzner Cloud API right now. Subnets do not have any IDs. You can only assign a Server to a Network, and the last created Subnet will be used, alternatively you can specify the IP yourself (in the API).

I have added 5 Votes (OP + 4 Upvotes) to the matching issue in our internal feedback tracker.

/area provider/hetzner

**Comment by dominic-p** [comment]
This would still be nice to have for my use case. Are there any updates on providing a subnet ID?

**Comment by apricote** [comment]
No updates from the API side. There is also no one working on the cluster-autoscaler side of things. We have the same feature request in the terraform provider, so perhaps its something that could be done in `hcloud-go` and shared between the integrations. Open for any contributions, here or in `hcloud-go` :)
