### ISSUE TITLE
2 Pods with graceful Termination over 2 mins and PDB prevent scale-down of underutilized node

### ISSUE THREAD

**Issue by tiwisag** [kubernetes/autoscaler#5273]
**Which component are you using?**:
Cluster-Autoscaler

**What version of the component are you using?**:
v1.22.1

**What k8s version are you using (`kubectl version`)?**:
1.23

**What environment is this in?**:
AWS

**What did you expect to happen?**:
I have two Pods from a single StatefulSet with a graceful Termination of over 2 mins(10 min in my case) on an underutilized node (~5%).  There is an PodDisruptionBudget which allows only to have 1 maxUnavailable Pod at a time.

**What behaviour did you expect to see?**:
The node can be scaled-down by terminating one Pod at a time to respect the PDB by scheduling it to other nodes.

**What happened instead?**:
The drain of the node failed after 2 mins because the second Pod could not be evicted (PDB, other Pod still terminating)
I guess the two minutes mentioned here(https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#does-ca-work-with-poddisruptionbudget-in-scale-down). Can i change this parameter?

**How to reproduce it (as minimally and precisely as possible)**:
2 Pods on an underutilized node with a preStop hook that takes 10 min and a PDB with these two Pods with maxUnavailable set to 1.
[grace-sleep-sts.txt](https://github.com/kubernetes/autoscaler/files/9867991/grace-sleep-sts.txt)
[autoscaler-logs.txt](https://github.com/kubernetes/autoscaler/files/9868000/autoscaler-logs.txt)

**Comment by qianlei90** [comment]
When calculating which pods can be moved to other nodes, the pdb check is static. If two pods are on the some node and the node is under utilization, we will not block this node because the checkPdbs is always passed.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/drain.go#L83

**Comment by tiwisag** [comment]
Hi @qianlei90 thanks for your answer!
Those 2 Pods are from my/our application and are expected to have the termination time of 10 mins.
Pod 1 could be started on other node after the termination is finished, and then the other pod could be terminated, so over 20 mins both pods could be transfered to another node graceful.

**Comment by qianlei90** [comment]
`--max-pod-eviction-time` is added in version `1.25.0`, maybe this parameter can solve your problem：https://github.com/kubernetes/autoscaler/pull/4842

Another relevant issue：https://github.com/kubernetes/autoscaler/issues/2045
