### ISSUE TITLE
vpa-recommender v0.11 - error adding metric sample for container

### ISSUE THREAD

**Issue by chacond** [kubernetes/autoscaler#5288]
We are using vertical-pod-autoscaler v0.11. We use prometheus as history data provider. We are receiving spam of following" "Error adding metric sample for container" 

This is very similar to the following issues:
https://github.com/kubernetes/autoscaler/issues/2010
https://github.com/kubernetes/autoscaler/issues/2512

A fix was implemented with this PR:
https://github.com/kubernetes/autoscaler/pull/4102

but we are still seeing the issue even though we are on vpa v0.11

**Comment by superset1** [comment]
I am still getting "Error adding metric sample for container" in our logs.

**Comment by shixinlishixinli** [comment]
i meet the same problem

**Comment by kennangaibel** [comment]
Try setting "--memory-saver=true" in the args of your vpa recommender yaml file.
