### ISSUE TITLE
error whe using VPA 0.12.0

### ISSUE THREAD

**Issue by mohang6770** [kubernetes/autoscaler#5296]
**Which component are you using?**:
Vertical pod autoscale 0.12.0 for k8s 1.25.3

vertical pod autoscaler
**What version of the component are you using?**:
0.12.0

Component version:

**What k8s version are you using (`kubectl version`)?**:
1.25.3
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.25.3
</pre></details>

**What environment is this in?**:
k8s

**What did you expect to happen?**:

**What happened instead?**:

**Comment by mohang6770** [comment]
Status:
  Conditions:
    Last Transition Time:  2022-11-06T22:30:41Z
    Message:               Cannot read targetRef. Reason: Deployment kube-system/my-app does not exist
    Status:                True
    Type:                  ConfigUnsupported
    Last Transition Time:  2022-11-06T22:30:41Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                True
    Type:                  NoPodsMatched
    Last Transition Time:  2022-11-06T22:30:41Z
    Message:               No pods match this VPA object
    Reason:                NoPodsMatched
    Status:                False
    Type:                  RecommendationProvided
  Recommendation:
Events:  <none>

**Comment by voelzmo** [comment]
The message means that the Deployment referenced by the VPA resource doesn't exist. Is there a `Deployment` called `my-app` in the namespace `kube-system`? Does it have available Pods?

**Comment by mohang6770** [comment]
yes the deployment exists but pod does not..

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app
 namespace: kube-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       my-app
  updatePolicy:
    updateMode: "Auto"

**Comment by mohang6770** [comment]
if you have sometime i can share my screen and show you exactly the issue

**Comment by mohang6770** [comment]
fixed...
