### ISSUE TITLE
VPA e2e tests are failing

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#5298]
https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-updater

All tests started failing on 2022-11-02. I think cause is changes in K8s 1.26

**Comment by jbartosik** [comment]
I think this is caused by #5268. With that change service accounts are now created in namespace `openshift-vertical-pod-autoscaler` instead of `kube-system`

As a result script setting up VPA components fails. Example logs from [this run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-updater/1589555369170964480):

```
W1107 09:57:05.829] Error from server (NotFound): error when creating "../vertical-pod-autoscaler/hack/../hack/../deploy/vpa-rbac.yaml": namespaces "openshift-vertical-pod-autoscaler" not found
W1107 09:57:05.830] Error from server (NotFound): error when creating "../vertical-pod-autoscaler/hack/../hack/../deploy/vpa-rbac.yaml": namespaces "openshift-vertical-pod-autoscaler" not found
```

**Comment by jbartosik** [comment]
@joelsmith FYI

**Comment by joelsmith** [comment]
Sorry about that! It crept in via my copy/paste from a downstream fork. Thanks for fixing it.
