### ISSUE TITLE
Failed to scale up node pool from 0

### ISSUE THREAD

**Issue by Stono** [kubernetes/autoscaler#530]
Hi, 
I've just observed some strange behaviour.  I have a cluster with three node pools, tagged with a `purpose` label, in the following ways

- default
- hot
- warm

Default was running 2 nodes, whilst hot and warm were at 0 (as nothing was deployed).

I then deployed a pod which had a nodeSelector of `purpose=hot`, but observed the following:

```
Events:
  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Warning  FailedScheduling   1m (x22 over 6m)   default-scheduler   No nodes are available that match all of the predicates: Insufficient cpu (1), MatchNodeSelector (1).
  Normal   NotTriggerScaleUp  51s (x23 over 6m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

I had to go and manually increase the pool size to 1 to get this pod to deploy.
When i then deployed more instances of the application, the pool continued to scale up as expected.

**Comment by MaciekPytel** [comment]
Hi @Stono,
What cloudprovider are you using (GCE, GKE, AWS, Azure)? Code from scale-from-0 is largely platform specific, so this is a critical piece of information for this issue.

**Comment by Stono** [comment]
Apologies @MaciekPytel - I am on Google Container Engine (GKE)

**Comment by MaciekPytel** [comment]
How do you set up `purpose` label on your nodes? Is it set on node-pool using `--node-labels` gcloud flag? If you set it up any other way CA will not be able to predict that a new node in node-pool scaled to 0 will have a given label, so it will assume the node with nodeSelector won't be able to schedule there.

If it's set with `--node-labels`, than any other data you can provide will help figure out the issue. In particular the type of instances you use and your pod definitions could be very helpful.

**Comment by bhack** [comment]
I'am also interested in this with AWS and ASG tag cause [this section](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0) of Docs is not very clear. Do you need to use `k8s.io/cluster-autoscaler/node-template/label/` in the nodeselector?

**Comment by bhack** [comment]
For aws I've solved replicating nodelabel and cloudlabel key/value. Probably it could be better document  in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0

**Comment by aleksandra-malinowska** [comment]
@Stono have you been able to resolve it?

**Comment by derekrgoss** [comment]
@Stono I am also encountering a similar issue on GKE. I have not set any labels at all- does the default scaling functionality require labels?

**Comment by aleksandra-malinowska** [comment]
@derekrgoss No, there's no need for labels unless you want to use node selectors. Can you share a bit more about your setup (pod request and any node selector, node group spec)?
