### ISSUE TITLE
Namespaces in vpa-rbac.yaml seem to be incorrect

### ISSUE THREAD

**Issue by jppitout** [kubernetes/autoscaler#5300]
Service accounts are being created in the `openshift-vertical-pod-autoscaler` namespace which won't exist on vanilla Kubernetes

See commit for reference: https://github.com/kubernetes/autoscaler/commit/bc586f87f8fe5d74bd95802344e3b5675bb5957f

**Comment by jbartosik** [comment]
Yes. The fix #5299 already merged
