### ISSUE TITLE
when using 0.8.0

### ISSUE THREAD

**Issue by mohang6770** [kubernetes/autoscaler#5302]
resource mapping not found for name: "verticalpodautoscalers.autoscaling.k8s.io" namespace: "" from "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "verticalpodautoscalercheckpoints.autoscaling.k8s.io" namespace: "" from "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first

**Comment by jbartosik** [comment]
On what K8s version this is?

`apiextensions.k8s.io/v1beta1` was removed in 1.22 (see [API removals for Kubernetes v1.22](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes)).

**Comment by mohang6770** [comment]
Thanks..
