### ISSUE TITLE
what is causing this?

### ISSUE THREAD

**Issue by mohang6770** [kubernetes/autoscaler#5304]
this is the log of vpa-recommender...could you please help..

│ E1108 17:50:42.438615       1 reflector.go:126] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:109: Failed to list *v1.StatefulSet: Get https://xx.xx.x.x:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp xx.xx.x.x:443: i/o timeout                                 │
│ I1108 17:50:43.438502       1 reflector.go:161] Listing and watching *v1.Pod from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go:183                                                                                                                                                                            │
│ I1108 17:50:43.439554       1 reflector.go:161] Listing and watching *v1.StatefulSet from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:109                                                                                                                                             │
│ E1108 17:50:51.431337       1 cluster_feeder.go:145] Cannot initialize watching events. Reason Get https://xx.xx.x.x:443/api/v1/events?fieldSelector=reason%3DEvicted&watch=true: dial tcp xx.xx.x.x:443: i/o timeout

**Comment by nandorKollar** [comment]
The communication between the pod and Kubernetes API server looks broken, either because of some network issue, or API server request throttling. Maybe API server logs can tell more if this is a throttling problem, and look for errors in CNI logs for network problems.
