### ISSUE TITLE
AWS me-central-1 region not supported in cluster-autoscaler-1.25.0

### ISSUE THREAD

**Issue by gaurav34065** [kubernetes/autoscaler#5311]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 1.22.2

Component version: 1.22.2

**What k8s version are you using (`kubectl version`)?**: 1.22

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:18:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: AWS

**What did you expect to happen?**: cluster-autoscaler pod should work without any errors

**What happened instead?**: Getting below error
```
I1112 08:12:03.960740       1 cloud_provider_builder.go:29] Building aws cloud provider.
F1112 08:12:03.960789       1 aws_cloud_provider.go:365] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list
goroutine 89 [running]:
k8s.io/klog/v2.stacks(0xc00013c001, 0xc0002d4000, 0x8a, 0xf3)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x61371c0, 0xc000000003, 0x0, 0x0, 0xc00077e2a0, 0x0, 0x50b6724, 0x15, 0x16d, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printf(0x61371c0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x41588bb, 0x2d, 0xc000a21a60, 0x1, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
k8s.io/klog/v2.Fatalf(...)
```

**How to reproduce it (as minimally and precisely as possible)**:
Launch EKS cluster in AWS `me-central-1` region and install `cluster-autoscaler-1.22.2` deployment in it.

**Anything else we need to know?**: Currently i tried with 1.22.2 version but `me-central-1` is not present in any of it's source code references. I checked in 1.25.0 version source also, same issue.
Also, I have verified that the serviceAccount associated with the autoscaler pod has necessary IAM permissions for EC2.

**Comment by nandorKollar** [comment]
It appears that this region is missing from [Go SDK for AWS v1.38.49](https://github.com/aws/aws-sdk-go/blob/v1.38.49/aws/endpoints/defaults.go). Master also is on this version, might be good to update to a [more recent](https://github.com/aws/aws-sdk-go/blob/v1.44.136/aws/endpoints/defaults.go) SDK version.
