### ISSUE TITLE
The quickstart instructions are incorrect

### ISSUE THREAD

**Issue by 2fst4u** [kubernetes/autoscaler#5312]
**Which component are you using?**:

 vertical-pod-autoscaler

**What version of the component are you using?**:

Trying to install 0.12

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version 1.25

</pre></details>

**What environment is this in?**:

on prem k3s

**What did you expect to happen?**:

commands in quick start work

**What happened instead?**:

The commands refer to scripts that don't exist.

**How to reproduce it (as minimally and precisely as possible)**:

Follow quick start

**Anything else we need to know?**:

It says to run `./hack/vpa-up.sh` but this no longer exists. Which script should I run?

**Comment by Shubham82** [comment]
Hi @2fst4u
It is present under the hack directory. Below is the link for it.
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/hack/vpa-up.sh

**Comment by 2fst4u** [comment]
The command `git clone https://github.com/kubernetes/autoscaler.git` doesn't clone this script. The directory is differently named tot he instructions too.

**Comment by Shubham82** [comment]
you are looking at the wrong directory, For VPA it should be` autoscaler/vertical-pod-autoscaler/hack/` instead of ` autoscaler/hack/`.

**Comment by 2fst4u** [comment]
Thank you that makes sense. That was confusing.
