### ISSUE TITLE
TLS cert issues?

### ISSUE THREAD

**Issue by zestysoft** [kubernetes/autoscaler#5331]
**Which component are you using?**:
vertical-pod-autoscalar

**What version of the component are you using?**:
master branch
k8s.gcr.io/autoscaling/vpa-admission-controller:0.12.0
k8s.gcr.io/autoscaling/vpa-recommender:0.12.0
k8s.gcr.io/autoscaling/vpa-updater:0.12.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5", GitCommit:"e979822c185a14537054f15808a118d7fcce1d6e", GitTreeState:"clean", BuildDate:"2022-09-14T16:35:41Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/arm64"}
</pre></details>

**What environment is this in?**:
self-hosted -- kubeadm

**What did you expect to happen?**:
Generated certificates would function as author expected

Given that the CA and certs were generated through executing the hack/vpa-up.sh script, I thought the code would understand and be able to work around any foreseen trust issues.
**What happened instead?**:
```
[vpa-admission-controller-5bffc4b7b7-qh9t7] 2022/11/26 04:46:47 http: TLS handshake error from 192.168.100.91:37520: remote error: tls: bad certificate
[kube-apiserver-k8s-master-5] W1126 04:46:47.589508       1 dispatcher.go:180] Failed calling webhook, failing open vpa.k8s.io: failed calling webhook "vpa.k8s.io": failed to call webhook: Post "https://vpa-webhook.kube-system.svc:443/?timeout=30s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "vpa_webhook_ca")
[kube-apiserver-k8s-master-5] E1126 04:46:47.589578       1 dispatcher.go:184] failed calling webhook "vpa.k8s.io": failed to call webhook: Post "https://vpa-webhook.kube-system.svc:443/?timeout=30s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "vpa_webhook_ca")
```

hamster example pod regularly terminates and restarts -- I believe whatever settings are supposed to get applied aren't -- at least when I describe the pods I see what was originally set in the deployment yaml file and not what the vsa recommends.

**How to reproduce it (as minimally and precisely as possible)**:
git clone https://github.com/kubernetes/autoscaler.git
cd autoscaler/vertical-pod-autoscaler
./hack/vpa-up.sh

**Anything else we need to know?**:
I had previously followed some of the guidance from here: https://github.com/aquasecurity/kube-bench so it's possible I've locked down something a default system may not have set.
I do have the ability to generate lets encrypt certs for things like my ingresses -- perhaps I can use that to generate trusted certs instead?

**Comment by voelzmo** [comment]
> perhaps I can use that to generate trusted certs instead?

You should be able to generate certs with different means and put them into the secret `vpa-tls-certs`, for example with cert-manager
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signer
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-cert-by-certmanager
  namespace: kube-system
spec:
  secretName: vpa-tls-certs
  dnsNames:
    - vpa-webhook.kube-system.svc
  issuerRef:
    name: self-signer
```

Just make sure the adjust the startup args of the admission-controller to fit the certificate names in the mounted secret, like described here: https://github.com/kubernetes/autoscaler/issues/5318#issuecomment-1329445376

**Comment by mohang6770** [comment]
could someone please help me with the files to be installed for vertical pod autoscalers
resources:
  - vpa-crd.yaml
  - vpa-beta-crd.yaml
  - vpa-rbac.yaml
  - vpa-v1-crd-gen.yaml
  - certificate.yaml
  - admission-controller-deployment.yaml
  - recommender-deployment.yaml
  - updater-deployment.yaml
  - vpa-beta2-crd.yaml

**Comment by preflightsiren** [comment]
@voelzmo one thing to be aware of is the VPA expects certificates to be in pem format, so unless you're running cert-manager 1.7 or newer, you won't be able to generate them.

**Comment by voelzmo** [comment]
Ah, thats a good hint, thanks @preflightsiren. I wasn't sure how old cert-manager 1.7 was, so I had a look at [their docs](https://cert-manager.io/docs/installation/supported-releases/): seems like it was released more than 2 years ago and is already EOL – so I hope not many people would use a version smaller than 1.7? It is definitely good to keep this in mind, in case you're trying to use cert-manager and keep getting weird errors, though!

**Comment by mohang6770** [comment]
Hi

Sorted it by creating a sidecar nginx and offloading the certificates

**Comment by voelzmo** [comment]
/remove-kind bug
/kind support
/close

I'm closing this assuming that everything has been clarified. Please re-open if you feel the need to.
