### ISSUE TITLE
Link for cloud-controller-manager is not working.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/autoscaler#5332]
**Problem:**

The Link for `cloud-controller-manager` under [FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-remove-nodes) is not working. It redirects to k8s v1.19 docs, which are not supported now by k8s. and this cloud-controller-manager reference page is removed in k8s v1.20. There is no reference page for it in k8s docs.
There is only the [Cloud Controller Manager](https://kubernetes.io/docs/concepts/architecture/cloud-controller/) doc mentioned under k8s docs.

**Proposed Solution:**
Either we will remove Cloud-Controller-Manager or Update the link to `https://kubernetes.io/docs/concepts/architecture/cloud-controller/ `. 

**Page to Update:**
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

**Comment by Shubham82** [comment]
Hi @gjtempleton @mwielgus
PTAL!

**Comment by McGon-Fid** [comment]
I will work on this and open a PR shortly. Thanks

**Comment by Shubham82** [comment]
Hi @McGon-Fid
It is better if maintainers will give their views on this, so let's wait for @gjtempleton @mwielgus response. After confirmation, you can raise the PR.

**Comment by Shubham82** [comment]
closing the issue as it was fixed in #5346 
/close
