### ISSUE TITLE
Support running a cluster-autoscaler in a multi-cloud Kubernetes Cluster

### ISSUE THREAD

**Issue by jaredallard** [kubernetes/autoscaler#5347]
**Which component are you using?**: `cluster-autoscaler`

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

When running a cluster with multiple clouds, e.g. `gcp` and self-hosted, you cannot run `cluster-autoscaler` because it gets stuck on `providerID` being not set (or not a GCE value) (https://github.com/kubernetes/autoscaler/issues/4242)

**Describe the solution you'd like.**: A flag / or some other mechanism for picking a single cloud for a cluster-autoscaler instance to "look" for. This seems like the easiest way to support this since one could run a cluster-autoscaler per cloud.

I'd imagine that there'd also need to be support for ignoring certain workloads/limiting them to each cloud if that were the case.

**Describe any alternative solutions you've considered.**: I'm not aware of any other solutions.

**Additional context.**: n/a

**Comment by james-callahan** [comment]
> e.g. `gcp` and self-hosted, you cannot run `cluster-autoscaler` because it gets stuck on `providerID` being not set

Why is providerID not set?
Can't you just set it? What is initializing your nodes?
You may want to look into projects such as the talos cloud controller: https://github.com/siderolabs/talos-cloud-controller-manager/
