### ISSUE TITLE
Release VPA 0.13.0

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#5355]
K8s 1.26 will be released on 2022-12-08, release VPA

**Comment by jbartosik** [comment]
#5313 didn't have approval only lgtm so it didn't merge until today.

I want to wait for e2e to pick it up and plan to cut release tomorrow

**Comment by Shubham82** [comment]
Hi, @jbartosik when will we have VPA 0.13.0?

are we waiting for this PR #5275 to be merged?

**Comment by jbartosik** [comment]
@Shubham82 yes I want to merge #5275. I was also busy with some other things. This week I expect to have time for the release so I expect to finish it (unless something unexpected happens).

**Comment by Shubham82** [comment]
> @Shubham82 yes I want to merge #5275. I was also busy with some other things. This week I expect to have time for the release so I expect to finish it (unless something unexpected happens).

Thanks, @jbartosik for the information.

**Comment by jbartosik** [comment]
I created [vpa-release-0.13](https://github.com/kubernetes/autoscaler/tree/vpa-release-0.13) branch

**Comment by jbartosik** [comment]
I've built and tested images

**Comment by jbartosik** [comment]
Release is available: https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.13.0
