### ISSUE TITLE
VPA Compatibility

### ISSUE THREAD

**Issue by stevehipwell** [kubernetes/autoscaler#5360]
I'm looking at the VPA compatibility matrix and I'd like to confirm that it's showing the actual compatibility and not just a recommendation, e.g. I can't use `v0.12.0` on a pre K8s `v1.25` cluster?

Also it'd be nice if all of the versions had upper limits added like for `v0.11.0`.

**Comment by stevehipwell** [comment]
@jbartosik thanks for the info.

**Comment by voelzmo** [comment]
@stevehipwell if it helps: We're using VPA 0.12 successfully with k8s versions between 1.21 and 1.25 and haven't experienced any issues so far.

**Comment by stevehipwell** [comment]
Thanks @voelzmo, it does help to know what others have had success with. I think we'll use `v0.11.0` for our clusters lower than K8s v1.25 (v1.21+) unless we have issues which can only be resolved by `v0.12.0`; at that point it's really useful to know people have had success with `v0.12.0` on clusters lower than v1.25.
