### ISSUE TITLE
Unable to "kubectl exec" into cluster autoscaler container

### ISSUE THREAD

**Issue by hfarooqui** [kubernetes/autoscaler#5365]
**Component version**
 Cluster autoscaler  v9.21.1
https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6"}

**Environment**
EKS

**Issue**
```
kubectl exec -it autoscaler-aws-cluster-autoscaler-xyz -n kube-system -- /bin/sh

OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
command terminated with exit code 126
```

Tried with `/bin/bash/` but it does not work. Is there a way to get inside the container?
```
docker run -it --entrypoint /bin/bash k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.0
Unable to find image 'k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.0' locally
v1.23.0: Pulling from autoscaling/cluster-autoscaler
dbcab61d5a5a: Pull complete
cc90f681e25e: Pull complete
Digest: sha256:f46687231c2c1bfa139f2b18275b123222c8cf6a288bb9c8145932bd14ac3deb
Status: Downloaded newer image for k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.0
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
ERRO[0002] error waiting for container: context canceled
```

**Comment by khizunov** [comment]
@hfarooqui Cluster autoscaler image is based on [distroless](https://github.com/GoogleContainerTools/distroless) and doesn't have shell by design. 
You can try [debug Kubernetes pods without shells]( https://prefetch.net/blog/2022/04/08/ways-to-debug-kubernetes-pods-without-shells/) in 1.23 it should be enabled by default.
