### ISSUE TITLE
Cluster Autoscaler: pick up the fix for k/k#114509

### ISSUE THREAD

**Issue by towca** [kubernetes/autoscaler#5372]
https://github.com/kubernetes/kubernetes/issues/114509 is a bug in scheduler which affects Cluster Autoscaler at scale, introduced in k8s 1.24. It was already fixed on k/k master (https://github.com/kubernetes/kubernetes/pull/114518), and the fix will be cherry-picked to 1.24 and 1.25. After that happens, and new k8s patch releases are tagged, we need to update the vendor in 1.24 and 1.25 to pick up the fix, and cut new CA patch versions.

**Comment by Bryce-Soghigian** [comment]
Looks like it was cherry-picked here
 https://github.com/kubernetes/kubernetes/pull/114524
 https://github.com/kubernetes/kubernetes/pull/114525
 
 So we are just waiting on the patch release.https://kubernetes.io/releases/patch-releases/#1-25

**Comment by jayantjain93** [comment]
PRs are open for all affected versions.
