### ISSUE TITLE
Is it issue with Kubernetes 1.9?

### ISSUE THREAD

**Issue by vovkanaz** [kubernetes/autoscaler#539]
Our Cluster based on Kubernetes 1.9, seted up via kubeadmin
We are also create a role, gave it needed permissions, and attach it with  a working nodes(in AWS console).
When we try to run our pod, we've see always something like that!
`
 kubectl logs cluster-autoscaler-55797ff9db-r8qps
I0112 12:08:07.299859       1 main.go:225] Cluster Autoscaler 0.6.0
F0112 12:08:07.402421       1 main.go:257] Failed to get nodes from apiserver: nodes is forbidden: User "system:serviceaccount:default:default" cannot list nodes at the cluster scope
goroutine 1 [running]:`
Our Cloud Provider AWS. Thanks a lot, if you'll advice a little bit how to resolve this trouble

**Comment by aleksandra-malinowska** [comment]
cc @mumoshu

**Comment by mumoshu** [comment]
Hi @vovkanaz! I guess you would need to assign a more permissive serviceaccount which allows listing nodes against k8s apiserve(and more).
Just for clarification, the error itself doesn't seem to relate aws cloudprovider to me.

**Comment by vovkanaz** [comment]
Yes! Thanks a lot!
