### ISSUE TITLE
cluster-autoscaler on RKE2 crashes

### ISSUE THREAD

**Issue by BitTheByte** [kubernetes/autoscaler#5393]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Cluster autoscaler with rancher (v2.7.0) on Digitalocrean (RKE2)

Component version: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.26.0 with helm chart 9.21.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+rke2r1", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-10T17:56:22Z", GoVersion:"go1.18.8b7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+rke2r1", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-10T17:56:22Z", GoVersion:"go1.18.8b7", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

[error.txt](https://github.com/kubernetes/autoscaler/files/10329077/error.txt)

**Comment by DavidSpek** [comment]
Can confirm I am also running into this.

**Comment by towca** [comment]
This issue was already reported in #5378. The fix is cherry-picked to 1.26, I'll cut a patch version shortly.

**Comment by towca** [comment]
FYI this is now fixed in Cluster Autoscaler 1.26.1: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.26.1. I tested a basic scale-up/down scenario on GCE and everything looked ok.
