### ISSUE TITLE
Use ClusterAutoscaler CR's .status field instead of ConfigMap to report status

### ISSUE THREAD

**Issue by the-it-jaeger** [kubernetes/autoscaler#5400]
**Which component are you using?**:

ClusterAutoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Not really a problem, just trying to better follow conventions for reporting status of ClusterAutoscaler

**Describe the solution you'd like.**:

Use ClusterAutoscaler CR's .status field instead of ConfigMap to report status

**Describe any alternative solutions you've considered.**:

N/A

**Additional context.**:

N/A

**Comment by Bryce-Soghigian** [comment]
i wonder if people have built monitoring or logic based on the status inside the configmap. Maybe we should not delete the configmap logic but also add status into the cr
