### ISSUE TITLE
how to contact owners 

### ISSUE THREAD

**Issue by olsenme** [kubernetes/autoscaler#5405]
Hello. I am looking to get in contact with owners of this repo. Is there a way to reach out directly?

**Comment by Shubham82** [comment]
Hi @olsenme 
The best way to contact the Chairs of Sig-Autoscaling is at the SIG-Autoscaling Meeting which is held every [Monday at 16:00 Poland](https://zoom.us/j/944410904).
For Information on Sig-autoscaling meetings please take a look at the following link: https://github.com/kubernetes/community/tree/master/sig-autoscaling#meetings

**Comment by jbartosik** [comment]
The doc @Shubham82 linked also gives other ways to contact. I think this will answer your question. If it doesn't feel free to reopen
