### ISSUE TITLE
clusterapi: Cluster Autoscaler fails to backoff exhausted nodegroups

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes/autoscaler#5417]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:

Component version:
cluster-autoscaler 1.26

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.3.428+425ff1c8e2d298-dirty", GitCommit:"425ff1c8e2d29874926abb7da37641cf785c4ff3", GitTreeState:"dirty", BuildDate:"2022-03-10T21:18:29Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS, clusterAPI provider

**What did you expect to happen?**:
When the cluster autoscaler is configured with a priority expander for the clusterapi provider, and multiple MachineDeployments of differing priorities is provided, the cluster autoscaler can become stuck attempting to provision nodes in a higher priority nodegroup whose backing instance type is exhausted in the cloud provider. 

**What happened instead?**:
We have CAPI/CAPA configured in a self-managed cluster with the cluster autoscaler, and the highest priority MachineDeployment instance type became unavailable from AWS. 

The exact behavior we saw was that a new pod was created in the cluster which could not fit on any node, so the cluster autoscaler scaled up the highest priority MachineDeployment. CAPI created a new Machine for the upcoming node, and CAPA created an AWSMachine to fulfill the request. However, AWS was out of capacity of the instance type (m6a.32xlarge) in the AZ and the CAPA controller logged a warning. Because the node does not yet exist in AWS, it lacks a provider ID (the aws ID), and because this is not a failure (in theory the instance type might become available at any time), there is no failure message in the Machine or AWSMachine status fields. 

So the cluster autoscaler believes the upcoming node is available to schedule pods onto, so does not scale up any more nodegroups, but can not track the node as being "unregistered" or "long unregistered" in the cluster state registry, as it lacks a provider id, and nodes without an id can not be mapped back to a node group correctly either. As a result, the cluster autoscaler never backs off the unhealthy MachineDeployment picks another MachineDeployment to attempt to scale up, even when lower priority MachineDeployments exist.

The detail that led me to this finding was noticing this message in the cluster autoscaler logs frequently when this occurred:
```
W0111 18:40:44.125721       1 clusterapi_controller.go:476] Machine "audit-compliant-rad-worker-private-m6a-az3-5f7c8d44c6-j854x" has no providerID
```
When pending nodes with no ID exist, that is logged by the cluster api provider when the cluster state registry tries to understand the node and fails. The pending nodes seem to need a temporary "fake" pending ID to allow the cluster state registry to track the node and then utilize it's existing logic to move the node to a "long unregistered" state if the node fails to provision in time. In fact, there is already a mechanism to create a fake ID for failed Machines, but not pending unprovisioned Machines in the cluster api provider.

**How to reproduce it (as minimally and precisely as possible)**:
Configure the cluster autoscaler with a priority expander and multiple MachineDeployments with different priorities. Create some pods that will deploy onto these nodegroups. When the highest priority MachineDeployment's instance type can not be satisfied, the cluster autoscaler will not advance to the lower priority MachineDeployments for scale up. 

**Anything else we need to know?**:
The bug is also visible in the configmap cluster-autoscaler-status which has the nodegroup health and state information. Node groups backed by MachineDeployments will _not_ having pending or provisioning Machines counted in the nodegroups count of nodes, not even as unready or notStarted, instead they only count towards the cloudProviderTarget until the AWSMachine has an AWS ID assigned.

**Comment by elmiko** [comment]
thanks for the detailed write up, very nice !
