### ISSUE TITLE
Vertical Pod Autoscaler in `Recommendation` mode (no Updater) - how to automate?

### ISSUE THREAD

**Issue by gczarnocki** [kubernetes/autoscaler#5426]
Good morning all. I am working with Vertical Pod Autoscaler (VPA) to optimise resource consumption (CPU only) on the cluster. There's around 50+ microservices deployed, multiple namespaces. I can easily, in a shell script, automate creation of the VPA objects and I get recommendations. I cannot use the _Admission Controller_ on a cluster - this is not deployed. **The only part of VPA I have deployed is _Recommender_.**

I am also using Prometheus as a history provider with the following options:

```
        - --history-length=7d
        - --prometheus-address=<url>:9090
        - --recommender-interval=1m0s
        - --storage=prometheus
```
 
When I deploy the VPA across all deployments in a namespace, for great majority of deployments, my `target` is set to `minAllowed` (`50m`). Indeed, there's not much traffic on a namespace of choice, for some more loaded applications, I get targets closer to `200/300m`.

How should I proceed with that? As there's no constant load on the namespaces (used during business hours, not used on the weekend), how and when to deploy VPA to get reliable results?

Right now, I have a loop that traverses the namespaces, deploys VPA, gets its recommendations and output of `kubectl top pod -n <namespace>` and deletes VPA. That was the idea to get the recommendations `mode = Initial` over time. I don't know when the users of the namespaces will be generating more load on the namespace, so the idea is to make VPA recommend values every e.g. 15/30mins and process the results later.

```
while true; do
  for env in $envs; do
    1 Deploy VPA for all deployments in $env
    2 Wait for all VPA objects to provide recommendation
    3 Get output of 'kubectl top pod -n $env', save to file
    4 Save output of `kubectl get vpa -n $env -o=(...)` to file
    5 Remove all VPAs
  done
done

6 Determine the average / maximum of the VPA recommendations over time. Process data in e.g. Excel.
```

I am missing context about how relevant the Prometheus metrics are in getting recommendation, this issue: https://github.com/kubernetes/autoscaler/issues/4476 sheds some light on a decaying histogram algorithm. It seems to me that the actual consumption taken from metrics-server from the time when VPA object was created plays a greater role in determining recommendation that the Prometheus history. Or maybe this is biased because applications in fact are idle and peak from to time.

What I am describing can be probably summarized by: 

1) I want VPA in Recommendation mode, cannot use Admission Controller. How do I use it in an automated way? 
And: 2) How to use VPA in deployments with non-homogeneous CPU usage?

Thank you all for all the input.

**Comment by jbartosik** [comment]
I don't understand, it sounds like you're trying to re-implement admission controller. I think it would be easier to deploy the admission controller that we already have.
