### ISSUE TITLE
Cluster Autoscaler: Avoid Updating the Spec on Scaling Operations

### ISSUE THREAD

**Issue by spjmurray** [kubernetes/autoscaler#5436]
**Which component are you using?**:

cluster-autoscaler (cluster-api provider)

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We're using cluster-autoscaler/CAPI with ArgoCD as a deployment/update mechanism.  I can see commit 8b21473fc709e987f0a82c6185fc702d93abb7f4 caused a bit of a split brain issue where Argo/Helm thinks it's in control of `.spec.replicas` of the `MachineDeployment` and reverts any changes that cluster autoscaler makes to the same field.

Now there is a way out of it/hack, in that you can select MDs that have autoscaling enabled (jq query for an autoscaler annotation), then select the replicas spec field and have that ignored by CD.  It's just not very pretty 😸 

**Describe the solution you'd like.**:

I can see from the cited commit that it's a performance/stability issue, so I guess the clients should be aware of, watch and cache the scaling subresource, at which point updates to the spec become irrelevant.

**Describe any alternative solutions you've considered.**:

None, it's using the scale subresource as I'd expect, it's just spec updates are not what I'd expect a controller to do, my personal rule of thumb is that the spec shows user intent, not what the controller is forcing you into doing, which feels wrong somehow.

**Additional context.**:

**Comment by MaciekPytel** [comment]
I think controllers modifying spec (and particularly replicas) is a common pattern in Kubernetes. For example HPA modifies spec.replicas of deployment, deployment manages ReplicaSets and those manage Pods. Each case involves controller managing spec (and the HPA case is particularly relevant, since I believe MachineDeployment was modeled based on the Deployment).

**Comment by spjmurray** [comment]
Ah my bad, I read the change request wrong, it's doing some caching optimisation. Yeah the scale api design is prone to split brain by design. I will consult the oracle and see what helm users do about it usually..
