### ISSUE TITLE
Why not just assume `safe-to-evict` true?

### ISSUE THREAD

**Issue by thelabdude** [kubernetes/autoscaler#5456]
**Which component are you using?**:

cluster-autoscaler on EKS

**What version of the component are you using?**:

Component version: latest ~ 1.26.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.23
</pre></details>

**What environment is this in?**:

EKS

**What did you expect to happen?**:

It makes sense to require pods that should not be evicted use the `cluster-autoscaler.kubernetes.io/safe-to-evict=false` but why not just assume `true` if the annotation is not present on a non-replicated pod vs. requiring the explicit `cluster-autoscaler.kubernetes.io/safe-to-evict=true` annotation to be present (see: 
 https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go#L284).

At the very least, this seems to violate the principle of least surprise. In practice, our clusters don't down-scale aggressively enough because the auto-scaler is requiring an explicit `safe-to-evict=true` or it won't evict pods that are not replicated:
```
I0120 00:27:58.701038       1 cluster.go:169] Fast evaluation: node ??? cannot be removed: spark-1674173904922-???-exec-11 is not replicated
```
 (we run a lot of Apache Spark and it's generally safe to evict Spark executors and driver pods should use `safe-to-evict=false`.

Isn't the first rule of designing applications Kubernetes is that pods can be evicted at anytime? Thus, it seems reasonable to require `safe-to-evict=false` but then assume `safe-to-evict=true` if the annotation is not present.

**What happened instead?**:

Cluster auto-scaler fails to drain under-utilized nodes because they have pods without the `cluster-autoscaler.kubernetes.io/safe-to-evict=true` annotation.

**How to reproduce it (as minimally and precisely as possible)**:

Run any pods that are not managed by a ReplicaSet and the cluster auto-scaler will not drain the hosting node.

**Anything else we need to know?**:

see: 
 https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go#L284

Maybe the easiest solution here (so as to not break existing installs relying on the current behavior) would be to add another configuration option to opt-in, something like: `--assume-safe-to-evict-true`

**Comment by joebowbeer** [comment]
@thelabdude writes:

> Isn't the first rule of designing applications Kubernetes is that pods can be evicted at anytime?

I think the rule is more nuanced. Disruptions come in two flavors: voluntary and involuntary.

From https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

> Pods do not disappear until someone (a person or a controller) destroys them, or there is an unavoidable hardware or system software error. We call these unavoidable cases _involuntary disruptions_ to an application.

Your suggested change would make all autoscaling disruptions involuntary, unless otherwise specified.
