### ISSUE TITLE
Removed API v1beta1.CronJob in Kubernetes 1.26+

### ISSUE THREAD

**Issue by whitelancer** [kubernetes/autoscaler#5457]
Within Vertical Pod Autoscaler:

1. helm chart version 1.6.0 / https://artifacthub.io/packages/helm/fairwinds-stable/vpa
2. direct install as of Jan 31, 2023 

Component version:

**What k8s version are you using (`kubectl version`)?**: 1.26

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

At the moment, minikube & microk8s.

**What did you expect to happen?**:

VPA should correctly install and run without errors.

**What happened instead?**:

Due to the removal of the v1beta1.CronJob api in 1.26, I'm now seeing this in the container logs:

```
1 reflector.go:178] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/target/fetcher.go:95: Failed to list *v1beta1.CronJob: the server could not find the requested resource
```
 
**How to reproduce it (as minimally and precisely as possible)**:

I believe any K8S install of 1.26 or higher will exhibit this issue.  

**Anything else we need to know?**:

Here is a relevant document (one of many, I'm sure) describing how this API was removed and no longer compatible.  

https://github.com/kubernetes-sigs/kubebuilder/discussions/2841

I believe simply updating the API to use the correct nomenclature should solve the issue with minimal time committment.

APIs removed from k8s 1.25:
Group	Version	Resource	How to upgrade
batch	v1beta1	cronjobs	use v1 instead of v1beta1. v1 has been available since k8s v1.21. No notable changes
discovery.k8s.io	v1beta1	endpointslices	use v1 instead of v1beta1. v1 has been available since k8s v1.21. (See the guide to check the notable changes)
events.k8s.io	v1beta1	events	use v1 instead of v1beta1. v1 has been available since k8s v1.19. (See the guide to check the notable changes)
autoscaling	v2beta1	horizontalpodautoscalers	use v2 instead of v2beta1. v2 has been available since k8s v1.23. (No notable changes)
policy	v1beta1	poddisruptionbudgets	use v1 instead of v1beta1. v1 has been available since k8s v1.21. (See the guide to check the notable changes.)
policy	v1beta1	podsecuritypolicies	Migrated to 3rd-party admission webhooks.
node.k8s.io	v1beta1	runtimeclasses	use v1 instead of v1beta1. v1 has been available since k8s v1.20. (No notable changes)

APIs removed from k8s 1.26:
Group	Version	Resource	How to upgrade
autoscaling	v2beta2	horizontalpodautoscalers	use v2 instead of v2beta2. v2 has been available since k8s v1.23(No notable changes)
flowcontrol.apiserver.k8s.io	v1beta1	flowschemas	use v1beta2 instead of v1beta1. v1beta2 has been available since k8s v1.23(No notable changes)
flowcontrol.apiserver.k8s.io	v1beta1	prioritylevelconfigurations	use v1beta2 instead of v1beta1. v1beta2 has been available since  k8s v1.23(No notable changes)

**Comment by jbartosik** [comment]
Hi, as noted in VPAs README [Compatiblity](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#compatibility) section for K8s 1.25+ you will need VPA 0.12 (I think 0.13, which will come out soon, will work too).

I guess you should try reporting this to maintainers of the Helm chart.

I think this is all about this issue but please reopen if you want to talk about this more
