### ISSUE TITLE
Add extra eventing/doc for long unregistered nodes causing cluster autoscaler to consider cluster as broken

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#546]

**Comment by bskiba** [comment]
We should include manual steps that can be performed to fix the situation.

**Comment by aleksandra-malinowska** [comment]
Fixed in #551. Opened #555 to track further improvement.

**Comment by bskiba** [comment]
This can be closed then?

**Comment by aleksandra-malinowska** [comment]
Right, it was left open by mistake.
