### ISSUE TITLE
Update cloud-provider-azure version for Azure Cluster Autoscaler

### ISSUE THREAD

**Issue by manishsat** [kubernetes/autoscaler#5466]
**Which component are you using?**:

Azure Cluster autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

This is to update cloud-provider-azure dependency to 1.26.2
**Describe the solution you'd like.**:

Updating reference in the go.mod and updating the imports as necessary to include new compute model structs
**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by Shubham82** [comment]
Closing this issue, as resolved by PR #5473 
/close
