### ISSUE TITLE
Bump the VPA version and Update the VPA compatibility (vpa-release-0.13 branch)

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/autoscaler#5468]
The VPA image version use by [deploy/recommender-deployment-high.yaml](https://github.com/kubernetes/autoscaler/blob/vpa-release-0.13/vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml) and [deploy/recommender-deployment-low.yaml](https://github.com/kubernetes/autoscaler/blob/vpa-release-0.13/vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml) files is `0.12.0` under the `vpa-release-0.13` branch. Instead of 0.12.0 it should be **0.13.0**
And also update the compatibility for vpa 0.13.0 release under the [README.md](https://github.com/kubernetes/autoscaler/blob/vpa-release-0.13/vertical-pod-autoscaler/README.md)

part of #5355

**Comment by Shubham82** [comment]
Fixed it here: #5469

**Comment by jbartosik** [comment]
Fixed by #5475
