### ISSUE TITLE
Cluster Autoscaler evaluating a node memory utilization 0.000000

### ISSUE THREAD

**Issue by yhrunyk** [kubernetes/autoscaler#5471]
**Which component are you using?**: 
cluster-autoscaler

**What version of the component are you using?**:
cluster-autoscaler v1.23.1

Component version:

**What k8s version are you using (`kubectl version`)?**:
v1.23.14

$ kubectl version

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:32:47Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/arm64"}

**What environment is this in?**:
AWS

**What did you expect to happen?**:

CA properly evaluates memory requests on nodes.

**What happened instead?**:

I constantly see such logs `scale_down.go:448] Node ***.ec2.internal - memory utilization 0.000000` on some of the nodes(not all). The interesting thing is that after CA shows such a log it stops evaluating the node memory, though it still continues to evaluate CPU e.g `cpu utilization 0.545455` and the node can lives for hours.

The main issue here is that CA doesn't try to evaluate memory usage anymore after it got `memory utilization 0.000000`. This usually happens when a new node comes up. For example:

1. `***.eu-west-1.compute.internal - **start time** - 2023-02-01 15:54:57`

   `MESSAGE: ++ aws ec2 create-tags --resources i-***** --tags Key=BootstrapStatus,Value=Complete`

2. `log: I0201 15:54:24.219137       1 scale_down.go:448] Node ****.compute.internal - memory utilization 0.000000` - the intersting thing is that the first evaluation happens before **BootstrapStatus** is **Complete** that means the node doesn't run any workload yet.

3. `16:09:17.659997       1 scale_down.go:448] Node ****.eu-west-1.compute.internal - cpu utilization 0.058442` - there were 29 such events for **CPU** after the **memory utilization 0.000000**, but none for **memory utilization** and the node lived around 1 hour.

However, the are cases when CA continues evaluating the memory metrics even after `memory utilization 0.000000`, so I can't understand what is the pattern here, maybe CA has some logic that controls this behavior?

**Anything else we need to know?**:

I have quite aggressive CA parameters:
**--scale-down-utilization-threshold=0.9**
**--scale-down-unneeded-time=10s**
This is why it is important for me to properly evaluate the real CPU/Memory requests, as nodes can be scaled down quickly.

**Comment by gregth** [comment]
@yhrunyk :
1. First let's note that when it comes to utilization, the autoscaler will:
    1. Calculate & log, only the GPU utilization, if the node has GPU
    2. Otherwise, the max between CPU and Memory
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/simulator/cluster.go#L220-L250
That is the reason you may see alternating CPU and Memory logs (?), unless they refer to different nodes.
2. The main loop of the autoscaler repeatedly evaluates the utilization of the various nodes of the cluster, and logs it: https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/core/scale_down.go#L448. So, the logs you see should be normal.
3. The utilization is based on the `requests` of the containers, as you rightly stated.
4. If the `--ignore-daemonsets-utilization` is set to `false` (default value), then the CA removes the DaemonSet Pods requests from the node's allocatable:
https://github.com/kubernetes/autoscaler/blob/1f9b4e0e4648f358b631a9fc2dfadf4c5bbe63fc/cluster-autoscaler/simulator/cluster.go#L298
 That may be a bit tricky, but ultimately the utilization is:
a) **Case A - Do not ignore DS**: All_pod_requests / NodeAllocatable
b) **Case B - Ignore DS**: NonDaemonSetPodRequests / (NodeAllocatable - DaemonSetPodRequest)
5. Do your DaemonSet containers request any resources? If they do not, your utilization will be 0.

**Comment by gregth** [comment]
Note that based on my previous comment:
1. If its a non-GPU node, and **both CPU and Memory utilization are 0**, then the autoscaler will show preference for the **Memory** resource. See the quotes code snippet.   
2. Based on that I would assumpt that:
    a) You had some Pods that requested CPU running, so the autoscaler logged a non-zero CPU utilization 
    b) Then, these workload Pods stopped existing on the node
    c) Both CPU and Memory utilization dropped to 0, so the logs show only "Memory utilization" being zero.

**Comment by gregth** [comment]
Note that based on my previous comment:
1. If its a non-GPU node, and **both CPU and Memory utilization are 0**, then the autoscaler will show preference for the **Memory** resource. Please take a look at the quoted code snippet.   
2. Based on that I would assume that:
    a) No Pods requested any resources, so both the Memory and CPU utilization where zer
    b) Since both of them were zero, the autoscaler logged "memory utilization 0.00"
    c) After that, some workload appeared, and the CPU utilization was always higher than the Memory utilization, so that's why you see "CPU utilization" and no memory utilization log messages.

**Comment by gregth** [comment]
\sigautoscaling

**Comment by yhrunyk** [comment]
@gregth Thank you a lot for this detailed explanation! Just want to clarify one moment. You said " If the --ignore-daemonsets-utilization is set to false (default value), then the CA removes the DaemonSet Pods requests from the node's allocatable:", is it correct or the CA **doesn't** remove the DaemonSet Pods requests?

**Comment by gregth** [comment]
@yhrunyk the final formula for the utilization is:
 That may be a bit tricky, but ultimately the utilization is:
a) **Case A - Do not ignore DS**: All_pod_requests / NodeAllocatable
b) **Case B - Ignore DS**: NonDaemonSetPodRequests / (NodeAllocatable - DaemonSetPodRequest)
( "/" indicates division)

**Comment by yhrunyk** [comment]
@gregth Thank you once again. I think this ticket can be closed.
