### ISSUE TITLE
Some questions about VPA

### ISSUE THREAD

**Issue by xiazhan** [kubernetes/autoscaler#5481]
Hi @jbartosik or someone else working on VPA

This is Allan from Microsoft who attended your weekly meeting last week. Thanks a lot for answering our questions on the meeting.
Now I have some extra questions:

- VPA have 3 parts: Recommender, Updater and Admission Controller. Do we have plan to support HA such that we can have multiple replicas for Recommender, Updater and Admission Controllers? Or we already support HA.
- For security patch, would we able to get it before announcement?  If so, is it okay for us to release in public via our image repo once we get it?

**Comment by jbartosik** [comment]
Hi,
currently all components of VPA (Recommender, Updater, and Admission Controller) assume there is only 1 instance of each running[1]. I currently don't have capacity to implement HA. I'm happy to discuss design, review PRs and accept contributions implementing it.

For security patch do you mean fix for #5455? We're doing our best to release it quickly but I don't know when exactly we will release it.

[1] You can run multiple instances of for example recommender and tell them to watch pods in different namespaces (using [this flag](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/recommender/main.go#L55)) or run multiple recommenders with different names (alternative recommenders) but those allow you to reduce load on a single instance / run different configurations and are not suitable to keep extra instances around to improve availability.

**Comment by voelzmo** [comment]
@gouglhupf You can run multiple instances of the admission-controller, we also do this in our platform. There's no local state and this works just fine.

@gozer was this also the answer you were looking for, or is there anything else left in this issue that you were wondering about?

**Comment by gozer** [comment]
I was hoping for at least leader elections for vpa-updater and CPA-recommender

**Comment by voelzmo** [comment]
As stated above: this is currently not supported. My understanding is that you're trying to raise a feature request, in that case I'd ask you to open a separate issue, so we can split out a dedicated discussion about that and close this issue, which was more about a few generic questions. Thanks!

**Comment by Shubham82** [comment]
> As stated above: this is currently not supported. My understanding is that you're trying to raise a feature request, in that case I'd ask you to open a separate issue, so we can split out a dedicated discussion about that and close this issue, which was more about a few generic questions. Thanks!

Closing this issue as per the above comment.
