### ISSUE TITLE
Publish to registry.k8s.io instead of k8s.gcr.io

### ISSUE THREAD

**Issue by neiser** [kubernetes/autoscaler#5486]
The docker images published by this repository are still pushed to `k8s.gcr.io`, which is sunsetting in April 2023 [according to this blog post](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/). Searching the repo for `k8s.gcr.io` yields [quite a few results](https://github.com/search?q=k8s.gcr.io+repo%3Akubernetes%2Fautoscaler&type=Code&ref=advsearch&l=&l=). Are there any plans to move to the new `registry.k8s.io` soonish? I did not find any related issue.

I also couldn't figure out how exactly images are pushed (at least no Github action seems to do it, only Helm charts are published there). So maybe if you can give me a hint how that's supposed to work, I could prepare a PR resolves this issue. Currently, I suspect images are manually pushed using various [Makefile](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/Makefile)s. Is that true?

**Comment by jbartosik** [comment]
For VPA we build &  push images to `gcr.io/k8s-staging-autoscaling`(see [RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#build-and-stage-images)), then automation pushes those images to `k8s.gcr.io/autoscaling` after we apply changes to [`images.yaml`](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-autoscaling/images.yaml) (see [RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#promote-image)).

Addon resizer has similar release process (not documented in the repo). Looking at the images.yaml I think Cluster Autoscaler has similar release process too.

**Comment by jbartosik** [comment]
Closing, let's track this in #5491. Having 1 issue will help avoid confusion

**Comment by neiser** [comment]
@jbartosik Thanks for picking this up and the kind explanation.
