### ISSUE TITLE
rate vs irate for container_cpu_usage_seconds_total

### ISSUE THREAD

**Issue by jisnardo** [kubernetes/autoscaler#5490]
**Which component are you using?**

- recommender

**Question**

At this point https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go#L274

Why **rate** is used instead of **irate**?

```
historicalCpuQuery := fmt.Sprintf("rate(container_cpu_usage_seconds_total{%s}[%s])", podSelector, p.config.HistoryResolution)
```

https://prometheus.io/docs/prometheus/latest/querying/functions/#rate

https://prometheus.io/docs/prometheus/latest/querying/functions/#irate

`irate should only be used when graphing volatile, fast-moving counters. Use rate for alerts and slow-moving counters, as brief changes in the rate can reset the FOR clause and graphs consisting entirely of rare spikes are hard to read.`

Maybe **irate** provides more accurate results or is a better approach to CPU metrics?

At grafana kuberntes dashboards appears **sum_irate**

https://github.com/grafana/kubernetes-mixin/blob/master/dashboards/resources/pod.libsonnet#L113

```
'sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="$namespace", pod="$pod", %(clusterLabel)s="$cluster"}) by (container)' % $._config,
```

Thanks in advance.

**Comment by jbartosik** [comment]
I found that https://github.com/kubernetes/autoscaler/pull/1824 switched VPA to use rate, as a fix for https://github.com/kubernetes/autoscaler/issues/1501

I didn't find any discussion on why use `rate` and not `irate`.

If you think `irate` is better I'd like to get input from people who know more about this issue than I do (I don't use Prometheus much) - documentation makes it sound like using `rate` is a safe choice

**Comment by jisnardo** [comment]
Ok, we wait for the experts.

**Comment by kong62** [comment]
limits.cpu = 4
irate more than limits

irate
![image](https://user-images.githubusercontent.com/10241723/232376905-79967d9c-9058-48fe-a8ca-472e0078ffe8.png)

rate
![image](https://user-images.githubusercontent.com/10241723/232376975-42a21f18-e99d-406e-a25a-f5f429fcba8c.png)
