### ISSUE TITLE
[Action Required] Update references from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/autoscaler#5491]
With the [change to defaulting](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) to registry.k8s.io as our image registry and the [planned freeze in April](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), projects within the Kubernetes orgs should update their image references to point to the new address.

**NOTE:** We can ignore references to staging-k8s.gcr.io, but any other references to k8s.gcr.io should be updated to registry.k8s.io

[k8s.gcr.io search results](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes/autoscaler) 

ref: [[Umbrella Issue] Migrate K8s projects from k8s.gcr.io -> registry.k8s.io](https://github.com/kubernetes/k8s.io/issues/4738)

(similar issue: https://github.com/kubernetes/autoscaler/issues/5486)

/kind cleanup
/sig autoscaling
/priority important-soon

**Comment by jbartosik** [comment]
For VPA we build &  push images to `gcr.io/k8s-staging-autoscaling`(see [RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#build-and-stage-images)), then automation pushes those images to `k8s.gcr.io/autoscaling` after we apply changes to [`images.yaml`](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-autoscaling/images.yaml) (see [RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#promote-image)).

Addon resizer has similar release process (not documented in the repo). Looking at the images.yaml I think Cluster Autoscaler has similar release process too.
