### ISSUE TITLE
What would we like from a VPA Benchmark?

### ISSUE THREAD

**Issue by lallydd** [kubernetes/autoscaler#5493]
To understand the capacity of a VPA deployment, in particular the `recommender`, what kind of performance measurements would we like from a benchmark?

**Which component are you using?**:
This will likely end up as an end-to-end test running off of kind on a single box.

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

- Reduce worry about the VPA's capacity and performance for stakeholders and users
- Provide a baseline for performance engineering.

**Comment by lallydd** [comment]
First thoughts: 
- A full-throughput case for determining how many `VerticalPodAutoscaler` objects a single `recommender` can handle in a cluster.
  - Especially in the External Metrics case, where it has to be queried repeatedly.
- Similar for latency for adding a new pod in the `admission-controller`.

**Comment by jbartosik** [comment]
Sounds good to me.

I think that first thing likely to slow down is processing VPA objects in recommender.

As we get more and more costly to process VPA objects in a cluster (see VPA recommenders [`RunOnce`](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L160)):
* [`UpdateVPAs`](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L93) and [`MaintainCheckpoints`](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L147) will take more time,
* Eventually the function will hit [the timeout](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L165) (default 1 minute),
* Then we will start limiting how many VPA objects we checkpoint in each Run.
  * This will be visible in the recommenders [`execution_latency_seconds`](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go#L65) metric (time spent on checkpoints will start going down) and in age of checkpoints (they will be getting older)
  * I expect age of checkpoints will grow faster than linearly with number of VPAs (number of VPAs to checkpoint is growing and time for doing that shrinks) here
* Eventually we hit `minCheckpointsPerRun` ([default 10](https://github.com/kubernetes/autoscaler/blob/9f04d4fb87c34a6ce15163faec99f67b3db557ee/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L50)) and time we spend per loop starts increasing (visible in `execution_latency_seconds` metric), checkpoint age will keep increasing (I'd guess age slows down growth to linear here).

For latency of admission controller I'm less worried but it'd be good to check it too.

**Comment by voelzmo** [comment]
There's also [`recommendation_latency_seconds`](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/metrics/recommender/recommender.go#L59) which is important to understand how well the `recommender` can deal with many objects being created at the same time.

@lallydd is this also about adjusting the history storage of the `recommender` to something external? Or do your external metric sources currently only provide real-time data? If we're also taking history storage into account, it would be interesting [how long it takes to backfill the historic data](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/main.go#L109-L132), but AFAIK we don't have a metric for this yet.

**Comment by lallydd** [comment]
@voelzmo The external metric sources only provide real-time data.  The one we intend to use for our use case will need some work to handle high query rates without overwhelming any upstream services.  Another team member here is working on a different recommender that can take percentiles directly from an external data source.  

The local-testing configuration I've put together for #5153 can let us run the benchmark to exhaust the `recommender` safely.
