### ISSUE TITLE
Make enum fields on the VPA API not pointers

### ISSUE THREAD

**Issue by EraYaN** [kubernetes/autoscaler#5503]
**Which component are you using?**: Vertical Pod Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
I'm trying to create a operator that creates VPA resources. And this does not work:
```go
op, err := ctrl.CreateOrUpdate(ctx, r.Client, vpa, func() error {
	vpa.Spec.UpdatePolicy.UpdateMode = autoscalingv1.UpdateModeOff // this breaks since it needs a pointer.

	return ctrl.SetControllerReference(instance, cert, r.Scheme)
})
```
Go won't let you make a pointer to a const.
`autoscalingv1` is `"k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1"`

**Describe the solution you'd like.**:
When looking at many other k8s apis these kinds of fields are often not pointers and thus letting you assign the enum values that are in the module to the actual field directly.

For example from the core API
```go
cont = corev1.Container{
    ImagePullPolicy: corev1.PullAlways,
}
```
`ImagePullPolicy` is of type `corev1.PullPolicy` and not `*corev1.PullPolicy`

**Describe any alternative solutions you've considered.**:
I have to do the following:
```go
mode := autoscalingv1.UpdateModeOff
vpa.Spec.UpdatePolicy.UpdateMode = &mode
```
Which feels like it's not really necessary.

An other option is of course generating ApplyConfiguration objects so I don't need to ever touch the actual k8s object.

**Additional context.**:

I'm using the Operator SDK, but that doesn't really have an impact I feel like.
Go 1.20 and mod `k8s.io/autoscaler/vertical-pod-autoscaler v0.13.0`

**Comment by EraYaN** [comment]
/remove-lifecycle stale

This is still a request that is useful.

**Comment by kwiesmueller** [comment]
These fields are pointers because they are optional. It's common practice with Kubernetes clients.

Generating ApplyConfigurations would be useful either way.
