### ISSUE TITLE
Exclude node in Cluster Autoscaler

### ISSUE THREAD

**Issue by gawsoftpl** [kubernetes/autoscaler#5504]
**Which component are you using?**:
Cluster autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Add annotation to node for exclude node from autoscaler

I have self-manage k8s cluster in the cloud and I added a dedicated node to this cluster.
Cluster-Autoscaler pod during download instances info raise an error because it tries to download info about the dedicated instance:
```
static_autoscaler.go:337] Failed to get node infos for groups: failed to check if server  exist │
│ s error: failed to get servers for node devops error: server not found
```

How to mark my dedicated instance for exclude from Cluster Autoscaler?

**Comment by cristianrat** [comment]
@gawsoftpl did you ever find a way to do this?
this is my exact issue :)

**Comment by gawsoftpl** [comment]
> @gawsoftpl did you ever find a way to do this? this is my exact issue :)

I dont remember. Maybe you do not install cloud controller. Do you install autoscaler on prem ?

**Comment by cristianrat** [comment]
I am not running k8s on prem
I have a combination of cloud and dedicated boxes
cloud gives me autoscaling while the dedicated are really cost effective

**Comment by gawsoftpl** [comment]
> I am not running k8s on prem I have a combination of cloud and dedicated boxes cloud gives me autoscaling while the dedicated are really cost effective

Maybe try install k3s with listen on public ip and default cloud controller. If you install cloud controller manager for your specific cloud, it will no get info about dedicated host and maybe this is a issue.

**Comment by cristianrat** [comment]
k3s doesn't work for me
it wouldn't change the situation anyway, i'd still have the same issue with cluster autoscaler :)
