### ISSUE TITLE
For CAPI cluster roles from chart and example do not mention cloud specific resources

### ISSUE THREAD

**Issue by jonathanbeber** [kubernetes/autoscaler#5509]
**Which component are you using?**:
cluster-autoscaler and its helm chart

**What version of the component are you using?**:

Component version: `v1.26.1`

**What k8s version are you using (`kubectl version`)?**: 1.26

**What environment is this in?**:

CAPI mainly with CAPA.

**What did you expect to happen?**:

The cluster-autoscaler to be able to read all resources it needs/wants with the documented RBAC permissions.

**What happened instead?**:

It fails to read and watch CAPA specific resources:

```logs
I0214 17:32:23.765518       1 reflector.go:257] Listing and watching *unstructured.Unstructured from k8s.io/client-go/dynamic/dynamicinformer/informer.go:91
W0214 17:32:23.766761       1 reflector.go:424] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: failed to list *unstructured.Unstructured: awsmachinetemplates.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "awsmachinetemplates" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
E0214 17:32:23.766790       1 reflector.go:140] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: awsmachinetemplates.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "awsmachinetemplates" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
```

**How to reproduce it (as minimally and precisely as possible)**:

Create a CAPA cluster, annotate the `MachineDeployments` with `cluster.x-k8s.io/cluster-api-autoscaler-node-group-[min|max]-size` and deploy cluster-autoscaler with `--cloud-provider=clusterapi`.

**Anything else we need to know?**:

It doesn't happen in `v1.23.1`. 

I believe we are missing it in places like

https://github.com/kubernetes/autoscaler/blob/04e5bfc88363b4af9fdeb9dfd06c362ec5831f51/charts/cluster-autoscaler/templates/clusterrole.yaml#L150-L161

although, I'm not sure how we want to proceed here. Should we document that for all cloud providers supported by CAPI? Why does it want to read CAPA specific resources instead of relying on CAPI respective ones?

**Comment by yankcrime** [comment]
I think a solution to this is also needed to support scale-from-zero, given that it requires CAPI provider specific resources adding here (see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#rbac-changes-for-scaling-from-zero)

**Comment by mstarostik** [comment]
As a quick fix, https://github.com/mstarostik/autoscaler/commit/5a881d99eab98aa3ced962fe4d32b7eb8fbc2020 at least opens the CR to values.yaml by enabling e.g.:
```
rbac:
  extraRules:
    - apiGroups:
        - infrastructure.cluster.x-k8s.io
        resources:
        - hcloudmachinetemplates
        verbs:
        - get
        - list
```
But maybe there is a better solution ahead?

**Comment by Preisschild** [comment]
Namespace scoped [`Roles`](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/role.yaml#L50) would need this too, in case `rbac.clusterScoped` is set to `false`

**Comment by eperdeme** [comment]
I'm also hitting this problem for Vmware absed CAPI.

```
3
I0621 10:32:56.666295       1 reflector.go:257] Listing and watching *unstructured.Unstructured from k8s.io/client-go/dynamic/dynamicinformer/informer.go:91
2
W0621 10:32:56.667774       1 reflector.go:424] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: failed to list *unstructured.Unstructured: vspheremachinetemplates.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "vspheremachinetemplates" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
1
E0621 10:32:56.667802       1 reflector.go:140] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: vspheremachinetemplates.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "vspheremachinetemplates" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
```

**Comment by cwrau** [comment]
This is still kinda required, othweise the autoscaler crashes since at least 9.57.0; should I open a new issue for this?
