### ISSUE TITLE
VPA: Allow for the removal of CPU limits in containerPolicy while keeping CPU requests and memory requests/limits

### ISSUE THREAD

**Issue by trevorvoncannon** [kubernetes/autoscaler#5513]
**Which component are you using?**: Vertical Pod Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: 
We are trying to apply VPA Auto recommendations to our lower environments without throttling applications with low CPU limits. Ideally we would like to remove CPU limits and have VPA update CPU requests and Memory requests/limits. Like so:
```
Spec:
  Resource Policy:
    Container Policies:
      Container Name:  argocd-repo-server
      Controlled Resources:
        cpu
      Controlled Values:  RequestsOnly
      Mode:               Auto
      Container Name:     argocd-repo-server
      Controlled Resources:
        memory
      Controlled Values:  RequestsAndLimits
      Mode:               Auto
  Target Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         argocd-repo-server
  Update Policy:
    Update Mode:  Auto
Status:
  Conditions:
    Last Transition Time:  2023-02-16T03:20:05Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  argocd-repo-server
      Lower Bound:
        Cpu:  12m
      Target:
        Cpu:  23m
      Uncapped Target:
        Cpu:  23m
      Upper Bound:
        Cpu:           37m
      Container Name:  cmp
      Lower Bound:
        Cpu:     12m
        Memory:  131072k
      Target:
        Cpu:     12m
        Memory:  131072k
      Uncapped Target:
        Cpu:     12m
        Memory:  131072k
      Upper Bound:
        Cpu:     12m
        Memory:  131072k
```
In VPA's current state, if you configure two containerPolicies for the same container, only one will be applied.

**Describe the solution you'd like.**: 

I think it would make more sense to have more granular control over container policies. Instead of [cpu|memory] [RequestsOnly|RequestsAndLimits], spreading it out to [cpuRequests|cpuLimits|memoryRequests|memoryLimits] that can be applied to a single container or all containers in the pod

**Alternative solution**
Alternatively, providing a flag `noCpuLimits: true` so that VPA would update requests and limits, but ingest this flag and recommend wiping the CPU limits altogether.

**Comment by voelzmo** [comment]
Hey @trevorvoncannon, thanks for the issue! For the record: I feel this is related to the recently closed #4861.

In the specific case you're describing, I'm wondering if the deployments you're using are specifying a CPU limit at all? The easiest way to have VPA not care about limits is to not set them during deployment. The property `Controlled Values:  RequestsOnly` refers to the case in which limits _are set_ but _should not be adjusted_ by VPA during scaling. VPA does not introduce CPU limits if they are not present in the original deployment.
My assumption is that if your goal is to remove CPU limits from the Deployments you're using, this should "just work" when you're keeping `Controlled Values:  RequestsOnly`. If you don't control the Deployments, a webhook might be the best approach here?

Some additional context: I think scaling requests only was the behavior with which VPA v2 was originally implemented. When the default was changed to also scale limits whenever it scaled the requests, a setting was created to bring back/preserve the original behavior for special cases or compatibility reasons. Take this with a grain of salt, though, I wasn't there while these decisions were made – this is just how I pieced the things together ;)

**Comment by trevorvoncannon** [comment]
Awesome thanks! I just tested a deployment without limits and it worked just as you said. I'll have to start digging into a webhook method to address the other deployments and remove some of our limitRanges to get this applied at scale.

**Comment by jbartosik** [comment]
Looks like the issue is addressed. Please reopen if there is anything more to do
