### ISSUE TITLE
Cluste Austoscaler IAM role issues 

### ISSUE THREAD

**Issue by rjtshrm** [kubernetes/autoscaler#5515]
**Which component are you using?**: cluster autoscaler

**What version of the component are you using?**: v1.22.2

**What k8s version are you using (`kubectl version`)?**:

**What did you expect to happen?**:
Autoscaler should be deploy successfully in kube-system on EKS fargate

**What happened instead?**:
I am trying to install CA on eks Fargate cluster which have **kube-system** namespace associated with Fargate profile.I followed the steps from [official aws docs](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#cluster-autoscaler). It seems that the IAM role (annotated to the service account **cluster-autoscaler** and associated with the cluster autoscaler deployment) is not being used.

```
E0216 19:02:15.487721       1 aws_manager.go:264] Failed to regenerate ASG cache: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F0216 19:02:15.487751       1 aws_cloud_provider.go:389] Failed to create AWS Manager: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Below is the IAM policy & trust relation ship that is used following the docs.

**IAM policy**
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeScalingActivities",
                "autoscaling:DescribeTags",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeLaunchTemplateVersions"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "ec2:DescribeImages",
                "ec2:GetInstanceTypesFromInstanceRequirements",
                "eks:DescribeNodegroup"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
**Trust relation ship**
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<ACCOUNT_ID>:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/<CLUSTER_ID>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-central-1.amazonaws.com/id/<CLUSTER_ID>:sub": "system:serviceaccount:kube-system:cluster-autoscaler",
                    "oidc.eks.eu-central-1.amazonaws.com/id/<CLUSTER_ID>:sub": "system:serviceaccount:cluster-autoscaler:cluster-autoscaler"
                }
            }
        }
    ]
}
```
I also tried to deploy CA in the managed node group (namespace: **cluster-autoscaler**), the error I get that the node in this group does not have permissions to describe autoscalergroup because the node use the IAM role that is associated with the managed node group. Even though I specified the service account to the CA deployment that is annotated with the above IAM role. So just to test I added the IAM policy to the IAM role that is used by managed node group and after that, CA was deployed successfully with new error but it seems that the CA is deployed succesfull.

`Failed to retrieve status configmap for update: configmaps "cluster-autoscaler-status" is forbidden: User "system:serviceaccount:cluster-autoscaler:cluster-autoscaler" cannot get resource "configmaps" in API group "" in the namespace "kube-system" `

**Comment by nan008** [comment]
you need to add the configmaps permission to the role in K8S not the IAM, we had the same issue just different permissions were missing when migrating to 1.22.2
add to your rbac

```
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-autoscaler-status"]
    verbs: ["delete", "get", "update", "watch"]
```
