### ISSUE TITLE
Reversing the order of pod re-creation in VPA

### ISSUE THREAD

**Issue by saeid93** [kubernetes/autoscaler#5520]
I am trying to use VPA for autoscaling my deployed services. Due to limitation in resources in my cluster I set the min_replica option to 1. The workflow of VPA that have seen so far is that it first deletes the existing pod and then re-create the pod. This approach will cause a downtime to my services. What I want is that the VPA first create the new pod and then deletes the old pod, completely similar to the rolling updates for deployments. Is there an option or hack to reverse the flow to the desired order in my case?

**Comment by voelzmo** [comment]
Hey @saeid93,
as mentioned in [the slack thread](https://kubernetes.slack.com/archives/C09R1LV8S/p1676745983324079), I don't think it is possible to achieve this with VPA.  VPA uses the eviction API to evict Pods from Nodes directly. It doesn't touch the Deployment, so usual options like the rollout strategy shouldn't change anything here.
You could prevent VPA from updating Pods with fewer than 2 replicas, but I'm not sure if that's what you want. For all your singletons this would mean they don't ever get updated resource requests.

**Comment by saeid93** [comment]
Hey @voelzmo ,
Thank you, it was very helpful!
