### ISSUE TITLE
Missing support for AWS inf2 instance types

### ISSUE THREAD

**Issue by mmcclean-aws** [kubernetes/autoscaler#5528]
**Which component are you using?**:

AWS autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Require support for upcoming inf2 instance types.

**Describe the solution you'd like.**:

Add inf2 instance type definitions to AWS ec2 config.

**Describe any alternative solutions you've considered.**:

None

**Additional context.**:

None

**Comment by sftim** [comment]
BTW, did you consider [Karpenter](https://github.com/aws/karpenter/) (not part of Kubernetes)?
