### ISSUE TITLE
Could not get a CSINode object for the node Error

### ISSUE THREAD

**Issue by sudhakar6343** [kubernetes/autoscaler#5533]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: cluster-autoscaler-9.20.1 helm chart

Component version: 1.23.0

**What k8s version are you using (`kubectl version`)?**: v1.24.7-eks

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:19:24Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: EKS

**What did you expect to happen?**: cluster autoscale to scale the cluster without any errors.

**What happened instead?**: 
Cluster autoscaling is happening , but seeing the below errors very frequently in the autoscaler pod logs.

"Could not get a CSINode object for the node" node="template-node-for-Workers-for-cluster-reddsudh2-reddsudh-EC2NodeGroupAZ2-MAIOYX30Q6K2-1205043859388862788-upcoming-0" err="csinode.storage.k8s.io \"template-node-for-Workers-for-cluster-reddsudh2-reddsudh-EC2NodeGroupAZ2-MAIOYX30Q6K2-1205043859388862788-upcoming-0\" not found"

**How to reproduce it (as minimally and precisely as possible)**:
Creating an EKS cluster and deploy statefulsets using PV's of EBS volumes.

**Anything else we need to know?**:

**Comment by gregth** [comment]
```
"Could not get a CSINode object for the node" node="template-node-for-Workers-for-cluster-reddsudh2-reddsudh-EC2NodeGroupAZ2-MAIOYX30Q6K2-1205043859388862788-upcoming-0" err="csinode.storage.k8s.io "template-node-for-Workers-for-cluster-reddsudh2-reddsudh-EC2NodeGroupAZ2-MAIOYX30Q6K2-1205043859388862788-upcoming-0" not found"
```

The cluster autoscaler determines how a scale-up would help the Pods by creating in-memory node templates (resembling new nodes of a node group) and simulating scheduling decisions. 

This error indicates that the cluster autoscaler could not find any CSINode object for the template node, which is absolutely normal, and expected: there are no CSINode template objects for each template node. **This error is not fatal**, you can confirm it in the code:

```golang
	// If CSINode doesn't exist, the predicate may read the limits from Node object
	csiNode, err := pl.csiNodeLister.Get(node.Name)
	if err != nil {
		// TODO: return the error once CSINode is created by default (2 releases)
		klog.V(5).InfoS("Could not get a CSINode object for the node", "node", klog.KObj(node), "err", err)
	}
```

**Comment by seh** [comment]
As far as I can tell from reading the scheduler code today, the only thing that a present _CSINode_ helps the scheduler to decide is [whether to translate a _PersistentVolume_ using an in-tree source to an out-of-tree CSI source](https://sourcegraph.com/github.com/kubernetes/autoscaler@ad86bdd64190baa3a685ec4816a09372453b67b3/-/blob/vertical-pod-autoscaler/e2e/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/binder.go?L1061-L1068).

For AWS EC2 EBS, you can find [the translation procedure in file _aws_ebs.go_](https://sourcegraph.com/github.com/kubernetes/autoscaler@ad86bdd64190baa3a685ec4816a09372453b67b3/-/blob/vertical-pod-autoscaler/e2e/vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go?L136-L167).

**Comment by zentavr** [comment]
Hi,
How to overcome this error? Seems like the EBS CSI driver creates the volume in one AZ, but autoscaler does not bring up the node in that AZ.

**Comment by zentavr** [comment]
In the similar issue there was a proposal [how to fix that](https://github.com/kubernetes/autoscaler/issues/4811#issuecomment-1170065024).
