### ISSUE TITLE
VPA: add a way to pass prometheus endpoint credentials

### ISSUE THREAD

**Issue by owlzq1** [kubernetes/autoscaler#5534]
**Which component are you using?**:
VPA recommender

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I want to use Prometheus as a history provider for the VPA recommender, but the Prometheus endpoints are under password protection in my company. Currently there is no way to pass basic auth credentials.

**Describe the solution you'd like.**:
Add a way to pass credentials either trough cli arguments, config file, or url parsing for basic auth.

**Describe any alternative solutions you've considered.**:
I can put some proxy between VPA and Prometheus, but i don't think that is the best solution.

**Comment by jbartosik** [comment]
I don't have capacity to work on this myself (also I'm not that familiar with Prometheus). But I'm happy to help with design & review
