### ISSUE TITLE
Allow Addon Resizer to scale based on container count

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#5546]
How much load some workload see depends on number of containers, not on the number of nodes. Number of nodes is not good enough predictor of how many containers are in the cluster and so we should allow scaling directly based on the number of containers.

I want to implement this on 1.8 branch.

**Comment by AhmedGrati** [comment]
@jbartosik To integrate `metrics-server` with this feature, I didn't find a stable metric that can return the number of containers in the cluster in this [list](https://kubernetes.io/docs/reference/instrumentation/metrics/#list-of-stable-kubernetes-metrics). Do you have another way around?

**Comment by kwiesmueller** [comment]
The metrics it's using right now are here: https://github.com/kubernetes/autoscaler/blob/addon-resizer-release-1.8/addon-resizer/nanny/kubernetes_client.go#L37
I think the same metric should also contain the number of pods, not sure about containers.
If we can't get a container metric pods would do as a first step too, I think.

**Comment by AhmedGrati** [comment]
@kwiesmueller Yes it contains the number of pods, but not containers. Starting with the number of pods should be a good first step I think.
