### ISSUE TITLE
VPA Support In-place Pod Vertical Scaling

### ISSUE THREAD

**Issue by tossmilestone** [kubernetes/autoscaler#5555]
**Which component are you using?**:

VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Since the In-place Pod Vertical Scaling has been merged (https://github.com/kubernetes/kubernetes/pull/102884), and will be released in k8s 1.27, the vpa should support the in-place resource updates then.

**Describe the solution you'd like.**:

Utilize the In-place Pod Vertical Scaling feature of k8s, add a new update policy.

**Describe any alternative solutions you've considered.**:

None

**Additional context.**:

None

**Comment by voelzmo** [comment]
Hey @tossmilestone, thanks for pinging about the in-place scaling feature! There is already an issue tracking this topic – it seems it could use a better name such that you can find it more easily, though. I'm closing this in favor of the already existing issue.

/duplicates #4016
/close
