### ISSUE TITLE
Deprecation of legacy k8s.gcr.io container image registry

### ISSUE THREAD

**Issue by identtogrodniczek** [kubernetes/autoscaler#5563]
As the current registry that is serving the image is going to freeze:
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
We have to migrate images to registry.k8s.io

Thanks.

**Comment by gjtempleton** [comment]
Hi @identtogrodniczek, all of the historic images owned by the SIG have already been mirrored to the new `registry.k8s.io` registry, we've updated the defaults and example references as per #5491 / #5494 and new images will be published to the new registry going forward. 

Is there anything else you think we need to do here?

**Comment by identtogrodniczek** [comment]
>Is there anything else you think we need to do here?

@gjtempleton Great to hear, thanks for the work!
