### ISSUE TITLE
Cluster Autoscaler events

### ISSUE THREAD

**Issue by danieltaub96** [kubernetes/autoscaler#5564]
**Which component are you using?**: Kubernetes Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I'm having trouble finding documentation on the events that can be accessed through the Cluster Autoscaler. I want to be able to audit the events for my cluster and use them for analysis, but I can't find a comprehensive list or guide anywhere. This feature request is designed to solve this problem by adding more documentation on the events that can be accessed through the Cluster Autoscaler.

**Describe the solution you'd like.**:

I would like to see more comprehensive documentation on the events that can be accessed through the Cluster Autoscaler. This could include a list of the events and what they signify, as well as guidance on how to access and use them for analysis.

**Describe any alternative solutions you've considered.**:

I've searched through the documentation, wiki, and code for the Cluster Autoscaler, but haven't been able to find the information I need on the events. One alternative solution would be to spend more time digging through the code to try and find the events, but I believe that better documentation would be a more efficient solution.

**Additional context.**:

I think that having better documentation on the events would be very helpful for anyone using the Cluster Autoscaler. This information could be used to monitor and analyze the performance of the autoscaler, as well as to troubleshoot issues and optimize performance. Thank you for your consideration of this feature request.

**Comment by gregth** [comment]
Documentation would indeed help. A workaround, however, is to `grep` the source code for `Recorder.Event`:
```
git grep Recorder.Event
```
