### ISSUE TITLE
Add info about `mirror pods` in FAQ

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/autoscaler#5566]
We use the wording `mirror pods` in our flags but don't really talk about what they mean anywhere.  e.g.,
![image](https://user-images.githubusercontent.com/34534103/223026939-a91f99cd-4027-4bc5-bf91-d4d84e8dc41a.png)
More can be found in the FAQ [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca)
This can be confusing for end users.

**Comment by vadasambar** [comment]
`kind/bug` is not correct here but I am not sure how to remove it.

**Comment by gregth** [comment]
Maybe a reference to the Kubernetes documentation would help: https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

**Comment by Shubham82** [comment]
> Maybe a reference to the Kubernetes documentation would help: https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

It seems good!
I'm up for it.

**Comment by Shubham82** [comment]
Fixed it here: #5609

**Comment by vadasambar** [comment]
@Shubham82 thanks for picking this up. Note that we have some additional TODOs:

From the comment [here](https://github.com/kubernetes/autoscaler/pull/5565#discussion_r1133471912)
> 1. add link to official definition of mirror pod OR static pod docs in FAQ wherever mirror pod is mentioned
> 2. add link to static pod docs wherever mirror pod is mentioned in the code
> 3. add a section around how CA treats mirror/static pods when draining a node

**Comment by Shubham82** [comment]
Hi @vadasambar, i didn't that about your PR.
Thanks for mentioning it here.

> add a section around how CA treats mirror/static pods when draining a node
In FAQ, there is mention about Mirror podes while scaling down the node, and its respective flags i.e. `skip-nodes-with-system-pods` and `ignore-mirror-pods-utilization`. i guess these flags explain what to do with mirror pods while draining a node.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work

> add link to official definition of mirror pod OR static pod docs in FAQ wherever mirror pod is mentioned

I will do that.

> add link to static pod docs wherever mirror pod is mentioned in the code

I think not everywhere, which you mentioned in the comment [here](https://github.com/kubernetes/autoscaler/pull/5565#discussion_r1133471107), I suggest mentioning it in the following place:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/pod/pod.go#L45

**Comment by vadasambar** [comment]
> In FAQ, there is mention about Mirror podes while scaling down the node

I guess you are talking about
> The sum of cpu and memory requests of all pods running on this node (DaemonSet pods and Mirror pods are included by default but this is configurable with --ignore-daemonsets-utilization and --ignore-mirror-pods-utilization flags)

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work

As a user of CA(cluster-autoscaler), it is hard to understand how CA is going to treat mirror pods during (say) scale-down. 

> I think not everywhttps://github.com/kubernetes/autoscaler/pull/5565#discussion_r1133471107, which you mentioned in the comment here, I suggest mentioning it in the following place:

I think having it in all those places might be valuable because many of the places I mentioned don't refer to `IsMirrorPod` function directly. Open to other opinions here.

**Comment by Shubham82** [comment]
@vadasambar, If someone knows about Mirror Pods, before understanding the code. Mention everywhere I don't think it makes sense. but let's wait for other opinions.

**Comment by Shubham82** [comment]
cc @MaciekPytel
