### ISSUE TITLE
VPA: Automate the process of generate certificates in VPA via initContainer

### ISSUE THREAD

**Issue by gusampaio** [kubernetes/autoscaler#5615]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Yes. Currently, there is no "native" way to fully automate the deployment of VPA in the cluster, as currently it is required to run the [vpa-up.sh](https://github.com/kubernetes/autoscaler/blob/dcf8f822f53f2c2933d1d75a9ef81e35858c710d/vertical-pod-autoscaler/hack/vpa-up.sh) script. This manual process can be a bit cumbersome if you are running in a gitops environment, in which you don't want to manually intervene. 

I can see that the most important thing that the script does is generate OpenSSL certificates to be used by the admission webhook deployment.

**Describe the solution you'd like.**:
The solution proposed is making use of an init container in the vpa-admission-controller deployment, so it can generate the certificates and share via mounted volume with the main container, without requiring to run any script whatsoever

```yaml
initContainers:
- name: cert-generator
  image: alpine:latest
  command: [ "/bin/sh", "-c" ]
  args:
    - |
      set -o errexit
      set -o nounset
      
      CN_BASE="vpa_webhook"
      TMP_DIR="/tmp/vpa-certs"
                
      echo "Installing openssl"
      apk upgrade --update-cache --available && \
      apk add openssl && \
      rm -rf /var/cache/apk/*
      
      echo "Generating certs for the VPA Admission Controller in ${TMP_DIR}."
      mkdir -p ${TMP_DIR}
      cat > ${TMP_DIR}/server.conf << EOF
      [req]
      req_extensions = v3_req
      distinguished_name = req_distinguished_name
      [req_distinguished_name]
      [ v3_req ]
      basicConstraints = CA:FALSE
      keyUsage = nonRepudiation, digitalSignature, keyEncipherment
      extendedKeyUsage = clientAuth, serverAuth
      subjectAltName = DNS:vpa-webhook.kube-system.svc
      EOF
      
      # Create a certificate authority
      openssl genrsa -out ${TMP_DIR}/caKey.pem 2048
      set +o errexit
      openssl req -x509 -new -nodes -key ${TMP_DIR}/caKey.pem -days 100000 -out ${TMP_DIR}/caCert.pem -subj "/CN=${CN_BASE}_ca" -addext "subjectAltName = DNS:${CN_BASE}_ca"
      if [[ $? -ne 0 ]]; then
        echo "ERROR: Failed to create CA certificate for self-signing. If the error is \"unknown option -addext\", update your openssl version or deploy VPA from the vpa-release-0.8 branch."
        exit 1
      fi
      set -o errexit
      
      # Create a server certiticate
      openssl genrsa -out ${TMP_DIR}/serverKey.pem 2048
      # Note the CN is the DNS name of the service of the webhook.
      openssl req -new -key ${TMP_DIR}/serverKey.pem -out ${TMP_DIR}/server.csr -subj "/CN=vpa-webhook.kube-system.svc" -config ${TMP_DIR}/server.conf -addext "subjectAltName = DNS:vpa-webhook.kube-system.svc"
      openssl x509 -req -in ${TMP_DIR}/server.csr -CA ${TMP_DIR}/caCert.pem -CAkey ${TMP_DIR}/caKey.pem -CAcreateserial -out ${TMP_DIR}/serverCert.pem -days 100000 -extensions SAN -extensions v3_req -extfile ${TMP_DIR}/server.conf
      
      chown -R 65534:0 ${TMP_DIR}
```

Obs: In order to make this solution work I had to set the security context flag `runAsNonRoot` to `false` and also set a special security context for this init container:

```yaml
  securityContext:
    privileged: true
    runAsUser: 0
```

This was only necessary in order to install openssl in the alpine image, if we have a pre-baked image with openssl installed, this is not needed

**Describe any alternative solutions you've considered.**:
Another approach that I took in order to automate this task was using external secrets with aws secret manager, but the manual steps to generate the keys were still required.

**Additional context.**:
The best approach that I could reach in order to use argocd to install vpa with kustomize was through the usage of the init container, so it was not needed any manual change during the process

**Comment by jbartosik** [comment]
Sounds like a good improvement: We probably should use an image that already has openssl so that it doesn't have to run as root (and also so that it doesn't need to install anything while it's running). I don't know when I'll have capacity to work on this myself
