### ISSUE TITLE
Move Registry from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by gallowaystorm** [kubernetes/autoscaler#5616]
**Which component are you using?**:
Autoscaler Helm chart

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Yes this is intended to solve the problem of Kubernetes removing k8s.gcr.io regsitry and moving to registry.k8s.io
**Describe the solution you'd like.**:
All images should be pulling from registry.k8s.io instead of k8s.gcr.io

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by gallowaystorm** [comment]
@roee-landesman  what version of the helm chart do I need to use in order for this to take a affect?  I dont see any release notes

**Comment by gallowaystorm** [comment]
@roee-landesman  following back up on this

**Comment by z0rc** [comment]
Release notes, for example https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.26.2, still reference k8s.gcr.io.

**Comment by obounaim** [comment]
@gallowaystorm, I have deployed the last chart version 9.27.0. The image is being correctly pulled from New Registry URL for Kubernetes (registry.k8s.io).

Please check your local values.yaml or the the values you set using the "--set" helm falg, maybe the old URL endpoint is hard-coded there.

Regards,

**Comment by obounaim** [comment]
I did not find any changelog of the Helm chart. However you can see the change in this commit :

https://github.com/kubernetes/autoscaler/commit/66e1eeb7c61f6e22fa7f262abe7efa39a48ba069

**Comment by gjtempleton** [comment]
Any version of the chart [post 9.24.0](https://github.com/kubernetes/autoscaler/pull/5494) will by default use `registry.k8s.io` as the registry, though any version before that can override the `image.repository` setting to use the new registry. 

I've also just updated the release notes of the latest round of patch releases to refer to the new registry.

Any objection to closing this issue?

**Comment by Shubham82** [comment]
@gallowaystorm if you have no further concerns so can we close this issue?

**Comment by Shubham82** [comment]
Closing this issue, as query resolved by the above comment done by @gjtempleton.
so @gallowaystorm if you have any further queries please reopen the issue.

**Comment by z0rc** [comment]
@gjtempleton release notes https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.28.0 again use `k8s.gcr.io`.

**Comment by gjtempleton** [comment]
Thanks for highlighting, my fault, now updated.
