### ISSUE TITLE
VPA stops giving recommendations after the first recommendation is given

### ISSUE THREAD

**Issue by marc19997** [kubernetes/autoscaler#5620]
**Which component are you using?**:
Vertical Pod Autoscaler

Vertical Pod Autoscaler

**What version of the component are you using?**:
0.11

Component version:

**What k8s version are you using (`kubectl version`)?**:
Kubectl Version

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0",GoVersion:"go1.18.1"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GoVersion:"go1.18.6"}

**What environment is this in?**:
Using it in AKS

**What did you expect to happen?**:
I would expect to see the VPA continuously give recommendations of the affected replicaset.

**What happened instead?**:
After the first recommendation, the VPA stops giving recommendations even though the pod is continuously running

<img width="373" alt="image" src="https://user-images.githubusercontent.com/68565611/227801046-6f959d47-ee70-49e0-b48d-02f421e51467.png">

When I run kubectl get vpa:
`
NAME               MODE   CPU   MEM   PROVIDED   AGE

test2-1-index-vpa   Off    1           True       43h`

As you can see here, the VPA provides a recommendation after the first minute, but stops giving recommendations after the first recommendation even though the VPA and the Pod dates from 47h. Looking at the logs of the Recommender, I don't see anything that suggests any errors with the Replicaset of the recommender.

Even looking at the VPA checkpoints, I see that the samples are quite recent to the recommendations provided timestamp:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/68565611/227800965-3fad5253-26d5-45ac-a2b9-1ae7643980b8.png">

**Comment by voelzmo** [comment]
Hey @marc19997 thanks for the issue!

> but stops giving recommendations after the first recommendation even though the VPA and the Pod dates from 47h
Could you elaborate a bit on how you reached this conclusion? Are you watching the VPA object and expecting changes to the `.status.recommendations` section? Are you looking at the timestamps and looking for a change there?

It could be that what you're seeing is normal behavior, depending on how your test workload consumes resources. Thanks for providing both, the VPA and the VPACheckpoint object! From these two objects, it seems

* that your workload doesn't consume much CPU at all. In the VPACheckpoint you can see in the `cpuHistogram` that the bucket with the index `0` has the highest weight (by far). This bucket gets more weight (maxed out at 10000) whenever a CPU sample is seen with 0-1 millicores (sometimes `mCores`, most of the time in code and yaml files `m`) – so my guess is that this is not doing any work and more or less a pause container.
* that you set `minAllowed.cpu` to _1 full core_, indicated by `1`. If you were to say 1 millicore, that should have been `1m`
* that the VPA recommender is giving a much smaller recommendation than what you configured to be the minimum allowed value (compare `uncappedTarget: 25m` and `target: 1`)

You can read more about resources and their units in the [official docs about Pod and Container resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes).

Let me know if that helps or if you think something else is going on!

**Comment by voelzmo** [comment]
Hey @marc19997,

The property you were looking at is a _Condition_ (it is located at `.status.conditions`), indicating the point in time when the VPA object transitioned from _not_ having a recommendation to _having_ a recommendation provided: At `2023-03-25T00:45:33Z` this VPA _transitioned_ from `RecommendationProvided: false` to `RecommendationProvided: true`. That's the only information you can derive from this field. The timestamp will only change if that Condition will evaluate to `false` and then back to `true` afterwards.

I don't think that it is possible to see what you're looking for. Once the first recommendation came in, the VPA will be updated every 60s (that's the recommender's loop interval) with a new recommendation. The above mentioned Condition only transitions back if there are no Pods matching the VPA anymore. In all other cases, it will get a new recommendation.

**Comment by marc19997** [comment]
Hey @voelzmo,

So what i've noticed is that sometimes the VPA recommendations are just not being updated then possibly? Even though the pod's usage is minimal as it is not getting any traffic for some time, the VPA keeps giving relatively high recommendations or just very out of date ones. I was hoping I would be able to identify that using the timestamps of the recommendations but from what you're saying that is not feasible.

**Comment by voelzmo** [comment]
/kind support
/remove-kind bug
/close

I'm closing this assuming we've clarified what's happening. Please re-open if you feel there's still undesired behavior from VPA side.
