### ISSUE TITLE
`make container` target in addon-resizer makefile  is running into an error

### ISSUE THREAD

**Issue by ShaunakJoshi1407** [kubernetes/autoscaler#5622]
**Which component are you using?**: addon-resizer

**What version of the component are you using?**:  https://github.com/kubernetes/autoscaler/tree/addon-resizer-1.8.16

**What did you expect to happen?**: The `make container` should run smoothly without running into any errors.

**What happened instead?**:  I ran into this error: 
```
docker buildx inspect img-builder > /dev/null || docker buildx create --name img-builder --use
cp -r * /var/folders/d7/pr1y9kqn4z57m0j2_1xllj000000gn/T/tmp.YylFOq9v
cd /var/folders/d7/pr1y9kqn4z57m0j2_1xllj000000gn/T/tmp.YylFOq9v && sed -i 's|BASEIMAGE|gcr.io/distroless/static:latest|g' Dockerfile
sed: 1: "Dockerfile": extra characters at the end of D command
make: *** [.container-amd64] Error 1
```

**How to reproduce it (as minimally and precisely as possible)**: Running `make container` from this branch: https://github.com/kubernetes/autoscaler/tree/addon-resizer-1.8.16 should suffice.

**Anything else we need to know?**: For now, I have made a minor change in this target to make this run. 
`cd $(TEMP_DIR) && sed -i 's|BASEIMAGE|$(BASEIMAGE)|g' Dockerfile` --> `cd $(TEMP_DIR) && sed -i- 's|BASEIMAGE|$(BASEIMAGE)|g' Dockerfile` to make it run. If this is an acceptable solution, I can make the change here.

**Comment by kwiesmueller** [comment]
I just tested this, on my local machine (debian) using `zsh` the `make container` command finishes as expected.
Do you have more details on what's different in your proposed fix and why you think it works?
