### ISSUE TITLE
Cluster autoscaler scale to min may breach cluster wide limits

### ISSUE THREAD

**Issue by kisieland** [kubernetes/autoscaler#5624]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Most recent from the HEAD.

**What k8s version are you using (`kubectl version`)?**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1-gke.1500", GitCommit:"633b8d38c09de2c1acd636c37f1f555bef6f905f", GitTreeState:"clean", BuildDate:"2023-02-07T09:38:46Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</pre></details>

**What environment is this in?**:

GCE running a custom Cluster autoscaler with `enforce-node-group-min-size` enabled maximal number of cores set to 5. 
There were 6 node groups present in the cluster, each running node with 1 core. 
In one there were 2 VMs, in another 1 and all others were empty.
When the 3 of empty nodegroups got updated to set min-nodes to 1, CA created 1 VM in each of them, resulting in 6 cores used.

**What did you expect to happen?**:

I would expect CA to respect the total resource limits and only create 2 new nodes.

**What happened instead?**:

CA created 3 nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Have a cluster close to core/node limit and atomically increase the min-size of two or more node groups.

**Anything else we need to know?**:

The code is in [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go#L398-L418), I've noticed the bug during refactor of the scale-up logic.

CC: @liuxintong as author of #5195

**Comment by kisieland** [comment]
Hi @xint6 I don't think this affects regular `ScaleUp` function, as it only picks one node group to scale-up and then balances the scale-up between similar node groups. \
Here we pick all nodegroups that we need to move to min size and scale them up together (I guess one solution would be to limit it to one nodegroup per loop).

As for the implementation, I finished my refactor and now the code lives in [orchestrator](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go#L348).
I don't think I will have the capacity to fix this anytime soon (hence the issue rather than PR).

**Comment by xint6** [comment]
@kisieland - Yeah, that makes sense. A better solution is to update the resource left in place so that multiple node groups can be scaled up in one loop. The fix PR is linked above, please help take a look, thanks.

**Comment by liuxintong** [comment]
I'm currently working on it.
/remove-lifecycle rotten

**Comment by liuxintong** [comment]
Reopening as I'm currently working on it.
/reopen
