### ISSUE TITLE
Cluster Autoscaler 1.27 blocked on missing AWS cloud provider dependencies

### ISSUE THREAD

**Issue by BigDarkClown** [kubernetes/autoscaler#5625]
**Which component are you using?**:

Cluster Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

AWS Cloud provider is using `k8s.io/legacy-cloud-providers/aws` package as a dependancy. This package was removed in Kubernetes release `v1.27.0-beta.0`, so migrating from it is a blocker for Cluster Autoscaler release 1.27.

**Describe the solution you'd like.**:

We should migrate from `k8s.io/legacy-cloud-providers/aws`.

**Reproduction steps.**:
1. Change the go version in `cluster-autoscaler/go.mod` from `go 1.19` to `go 1.20`.
2. Run update vendor script `bash hack/update-vendor.sh v1.27.0-beta.0`.

**Comment by BigDarkClown** [comment]
PTAL @jaypipes @gjtempleton @drmorr0

**Comment by gjtempleton** [comment]
Related: #5138

**Comment by gjtempleton** [comment]
What's the timeline like here @BigDarkClown?

Have you got repro steps for us to work on addressing?

**Comment by BigDarkClown** [comment]
I've added reproduction steps to the Issue description.

According to https://github.com/kubernetes/sig-release/tree/master/releases/release-1.27, the Kubernetes v1.27.0 will be released on April 11th, so ideally we should fix this before that.

**Comment by gjtempleton** [comment]
@drmorr0 @jaypipes do either of you have the bandwidth to look at this?

**Comment by olemarkus** [comment]
#5138 has been updated to address this.
