### ISSUE TITLE
Cluster Autoscaler 1.24 branch Missing support for AWS inf2 instance type

### ISSUE THREAD

**Issue by ferboz** [kubernetes/autoscaler#5626]
**Which component are you using?**:

AWS autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

**Describe the solution you'd like.**:

Back port support for inf2 instance types which is supported in `master` branch.
Master branch already has that from [here](https://github.com/kubernetes/autoscaler/pull/5529)

**Describe any alternative solutions you've considered.**:

Not specify

**Additional context.**:

Not specify

**Comment by mbdebian** [comment]
@gjtempleton I hope this helps. When will be next patch releases happening? Thanks

**Comment by gjtempleton** [comment]
@mbdebian / @ff-apple I'm [scheduled](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#patch-releases) to be cutting the next batch of patch releases in a couple of weeks. Are you planning to raise a cherry-pick to the 1.26 release branch as well?

**Comment by ff-apple** [comment]
> @mbdebian / @ff-apple I'm [scheduled](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#patch-releases) to be cutting the next batch of patch releases in a couple of weeks. Are you planning to raise a cherry-pick to the 1.26 release branch as well?

Thanks for the reference. Yes, definitely will do.
