### ISSUE TITLE
AWS EKS `Failed to regenerate ASG cache: NoCredentialProviders: no valid providers in chain. Deprecated`

### ISSUE THREAD

**Issue by khteh** [kubernetes/autoscaler#5642]
```
E0331 06:35:18.484130       1 aws_manager.go:262] Failed to regenerate ASG cache: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F0331 06:35:18.484154       1 aws_cloud_provider.go:414] Failed to create AWS Manager: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
**Which component are you using?**:
https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html
https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.25.1

cluster-autoscaler
**What version of the component are you using?**:
1.25.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-25T14:27:37Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:
No error

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by mehmetyazicioglu** [comment]
the issue was related to KIAM, i fixed that part for regex expression of IAM Roles for the namespace, it started to work again.
