### ISSUE TITLE
Adding New EC2 Instance Types

### ISSUE THREAD

**Issue by apatil4** [kubernetes/autoscaler#5661]
I saw that the [Ec2_Instance_types](https://github.com/kubernetes/autoscaler/blob/d9a86611a5305c2f73096f74735e0c77d2b3fae9/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go) file does not have many of the instance types that are available in AWS. Ofcourse, it will be behind as AWS releases new instance types but is the process to add new instance types to cluster autoscaler as easy as updating that file.

If so, can I add some new instance types that I want the cluster autoscaler to support?

**Comment by gjtempleton** [comment]
Closing due to no response, please re-open if you think this is still an issue.

/close
