### ISSUE TITLE
VPA API Spec

### ISSUE THREAD

**Issue by thepaulmacca** [kubernetes/autoscaler#5664]
More of a question than an issue...

I could just be looking in the wrong places, but is there anywhere that I can view a rendered copy of the `VerticalPodAutoscaler` API Spec, so I can see what options are available?

Thanks

**Comment by wu0407** [comment]
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go

**Comment by thepaulmacca** [comment]
It's ok, I'll close this now. I can live with it
