### ISSUE TITLE
Inconsistency about CPU architecture of VPA images between manifest and image attribute

### ISSUE THREAD

**Issue by hayashier** [kubernetes/autoscaler#5667]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 0.12.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af", GitCommit:"9f22d4ae876173884749c0701f01340879ab3f95", GitTreeState:"clean", BuildDate:"2023-01-24T19:19:02Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.25) exceeds the supported minor version skew of +/-1

</pre></details>

**What environment is this in?**:

[Amazon EKS](https://aws.amazon.com/jp/eks/)

**What did you expect to happen?**:

Consistency about CPU architecture of VPA images between manifest and image attribute

**What happened instead?**:

In the following repositories, I confirmed there is inconsistency about CPU architecture of VPA images between manifest and image attribute.

* registry.k8s.io/autoscaling/vpa-admission-controller:0.12.0
* registry.k8s.io/autoscaling/vpa-recommender:0.12.0
* registry.k8s.io/autoscaling/vpa-updater:0.12.0

**How to reproduce it (as minimally and precisely as possible)**:

For example, we can see manifest like this.

```
$ docker manifest inspect registry.k8s.io/autoscaling/vpa-admission-controller:0.12.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:bc6652d68d1cc90184e3b775baaaba5ed809c98c6c15a660c9333cf005b5e6bd",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      :
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:55d848ef05ac8a7f40f9f98710368a90d20717aabf0d895db3fdb15809485451",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      :
}
```

I pull Docker images like this on ARM machine.

```
$ docker pull registry.k8s.io/autoscaling/vpa-admission-controller:0.12.0@sha256:55d848ef05ac8a7f40f9f98710368a90d20717aabf0d895db3fdb15809485451 --platform arm64  
```

However, the arch attribute of this image is registered as x86 64.

```
$ docker image inspect registry.k8s.io/autoscaling/vpa-admission-controller:0.12.0@sha256:55d848ef05ac8a7f40f9f98710368a90d20717aabf0d895db3fdb15809485451    
[
    {
        "Id": "sha256:0b46c6a38ff2d4f8d1f3962ec1071a3696edff9c0973e7e67f7f7d1c406553a8",
        "RepoTags": [],
        "RepoDigests": [
            "registry.k8s.io/autoscaling/vpa-admission-controller@sha256:55d848ef05ac8a7f40f9f98710368a90d20717aabf0d895db3fdb15809485451"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2022-09-07T09:12:59.015782266Z",
        "Container": "4fea3f6e9158e82515150da2c4dced411d1829a25e266c88e893e2b51e488bd2",
        "ContainerConfig": {
            "Hostname": "4fea3f6e9158",
            :
        "Architecture": "amd64",
        "Os": "linux",
        :
    }
]
```

**Anything else we need to know?**:

As a situation that this causes issue, when we pull images for x86 64 and arm64 and create multi-arch images, both of images are recognized as x86 64, so we cannot pull those images correctly based on CPU arch unless we annotate CPU arch explicitly to the manifest. But even when we annotate CPU arch explicitly, CPU info showed by `docker image inspect` is wrong. For example, when we run `docker image inspect` for arm image, the output shows that is x86 64 image although actually that image is for arm64.

I filed this issue(https://github.com/kubernetes/registry.k8s.io/issues/222) to `kubernetes/registry.k8s.io` at first.
@BenTheElder guided me to file an issue with the VPA project.

**Comment by BenTheElder** [comment]
See previously: https://github.com/kubernetes/kubernetes/issues/87325, https://github.com/kubernetes/kubernetes/pull/87954
