### ISSUE TITLE
cluster-autoscaler.kubernetes.io/safe-to-evict: false annotation not disabling eviction

### ISSUE THREAD

**Issue by fkennedy1** [kubernetes/autoscaler#5668]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: v1.23.0/ helm chart - v9.15.0

Component version: v1.23.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.17-eks-48e63af", GitCommit:"47b89ea2caa1f7958bc6539d6865820c86b4bf60", GitTreeState:"clean", BuildDate:"2023-01-24T09:34:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: production

**What did you expect to happen?**: Using EKS. The pod would not be evicted due to this annotation being present in the spec.template portion of the k8s deployment. I checked the all the relevant pods and they have the annotation.

**What happened instead?**: The pod and node were evicted even with the cluster-autoscaler.kubernetes.io/safe-to-evict: "false" annotation

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I checked the logs and did not see this message at all: ```Fast evaluation: node xxxx.ec2.internal cannot be removed: pod annotated as not safe to evict present: xxxx.```

I even increased the scale down threshold temporarily to try and see if above logs were present to no success

We also have 1 AZ per ASG (not managed node groups) so not sure if suspending AZRebalance would have an effect. 

Relevant component configuration:
 ```Command:
      ./cluster-autoscaler
      --cloud-provider=aws
      --namespace=kube-system
      --node-group-auto-discovery=xxxx
      --balance-similar-node-groups=true
      --expander=least-waste
      --logtostderr=true
      --scale-down-enabled=true
      --scale-down-utilization-threshold=0.5
      --stderrthreshold=info
      --v=4

**Comment by fkennedy1** [comment]
Seems as though the pod having local storage notification takes precedence over the safe-to-evict annotation log message

**Comment by vadasambar** [comment]
Yes. CA checks for blocking local storage before `safe-to-evict`: `false` annotation
https://github.com/kubernetes/autoscaler/blob/5af3685e86ab8ac5fdb848699e948cbd6d1c3d43/cluster-autoscaler/utils/drain/drain.go#L222-L226

**Comment by vadasambar** [comment]
I think it will be a little hard to say why the node is getting removed without the logs.

**Comment by comeonyo** [comment]
Can you show us the YAML of pod & deployment without sensitive information?

**Comment by fkennedy1** [comment]
I solved the problem by lowering the scale down threshold and by adding  _skip-nodes-with-local-storage: false_ which now shows the correct log message and functioning as expected

**Comment by comeonyo** [comment]
If you set skip-nodes-with-local-storage as false, then the pod will be moved to another node by CA.
But, you wanted the pod to be protected.

**Comment by msardana94** [comment]
> I solved the problem by lowering the scale down threshold and by adding _skip-nodes-with-local-storage: false_ which now shows the correct log message and functioning as expected

@fkennedy1 did this work for you?

> If you set skip-nodes-with-local-storage as false, then the pod will be moved to another node by CA. But, you wanted the pod to be protected.

I am facing exactly this issue after changing the config. This seems like a bug to me?

**Comment by fkennedy1** [comment]
@msardana94 This did work for me. I however also updated the threshold for scaling down. For me all the workloads with storage are using the annotation
