### ISSUE TITLE
Cluster Autoscaler 1.25 branch Missing support for AWS inf2 instance type

### ISSUE THREAD

**Issue by ff-apple** [kubernetes/autoscaler#5684]
Which component are you using?:

AWS autoscaler

Is your feature request designed to solve a problem? If so describe the problem this feature should solve.:

Describe the solution you'd like.:

Back port support for inf2 instance types which is supported in `master` branch.
Master branch already has that from [here](https://github.com/kubernetes/autoscaler/pull/5529)

Describe any alternative solutions you've considered.:

Not specify

Additional context.:

Not specify

**Comment by Shubham82** [comment]
I would like to work on it and will add this to CA-1.26

**Comment by ff-apple** [comment]
marking this issue as closed.

**Comment by Shubham82** [comment]
thanks @ff-apple, I missed this PR: #5721
