### ISSUE TITLE
VPA in EKS Cluster only evicted by VPA Updater but don't update request resouce in pod

### ISSUE THREAD

**Issue by TVN-Quang** [kubernetes/autoscaler#5686]
### **I configure 1 VPA (vertical pod autoscaler) on EKS Cluster to automatically update pod resources, currently I use the configuration in examples/hamster in https://github.com/kubernetes/autoscaler/tree/master /vertical-pod-autoscaler. I installed VPA according to the instructions [text](https://docs.aws.amazon.com/eks/latest/userguide/vertical-pod-autoscaler.html). I tried to check the log and pods and see that the pods are just recreated but not updated based on the recommendation, also I don't see any event or log about updating request resource spec in events nor vpa-admission-controller **
![image](https://user-images.githubusercontent.com/50582605/232013937-dc47865c-69e8-470e-be99-50fde79d3f0c.png)

1. kubectl get events
![image](https://user-images.githubusercontent.com/50582605/232014269-751dc2af-1ce4-4dbc-bf25-ef9ad481aaef.png)

2. logs of vpa-admission-controller pod
![image](https://user-images.githubusercontent.com/50582605/232014316-5f3be35e-c6f6-4659-a1a5-fca34cf3f658.png)

3. logs of vpa-updater pod
![image](https://user-images.githubusercontent.com/50582605/232014371-8e370600-d23d-48d5-9d36-3d98b24134b8.png)

4. kubectl get po
![image](https://user-images.githubusercontent.com/50582605/232014458-fa7ffa44-b818-40c8-b329-7c4747b9a742.png)
![image](https://user-images.githubusercontent.com/50582605/232014479-42171979-ff51-4cb8-9b81-c38b59a6f791.png)
![image](https://user-images.githubusercontent.com/50582605/232014496-a288217f-0d0b-45ba-8912-4a31391cf47d.png)

5. kubectl get verticalpodautoscalers
![image](https://user-images.githubusercontent.com/50582605/232014525-89a0dbb4-96f5-468d-8532-a726f53955d9.png)

**Comment by starlightromero** [comment]
@TVN-Quang  What ended up being the resolution?
