### ISSUE TITLE
Pod didn't trigger scale-up because "max node group size reached"

### ISSUE THREAD

**Issue by esaeki417** [kubernetes/autoscaler#5692]
I use GKE in Google Cloud Platform, and encountered the following error message.

"pod didn't trigger scale-up: 12 node(s) didn't match Pod's node affinity/selector, 3 max node group size reached."

Does anyone know the cause of this issue? Also, I would appreciate if you tell me about the solution for this error.

**Comment by skorati** [comment]
@esaeki417 As per the  pod-event it seems the node-group has reached max configured size.

To resolve this issue you can increase the maxSize, I am not much aware of GCE but below docs has more information.
https://cloud.google.com/compute/docs/nodes/autoscaling-node-groups#updating
https://cloud.google.com/compute/docs/nodes/autoscaling-node-groups#size_range_of_a_node_group

**Comment by esaeki417** [comment]
@skorati Thank you for your advice. I will increase the resource of GKE.
