### ISSUE TITLE
Automatically reload nanny configuration when updated

### ISSUE THREAD

**Issue by rtheis** [kubernetes/autoscaler#5700]
**Which component are you using?**:

Using addon-resizer in conjunction with the metrics server 

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Feature request is designed to improve user experience for applying nanny configuration changes.

**Describe the solution you'd like.**:

Update the addon resizer so that it will automatically reload the nanny configuration when the configuration changes.  This avoids alternative solutions noted below.

**Describe any alternative solutions you've considered.**:

We've implemented a sidecar container to monitor for nanny configuration updates.  If there is an update, the addon resizer container/nanny is restarted.  This is not ideal since the restart is not highly available.  

We've also relied on process documentation detailing that the metrics server pods must be restarted to pick up nanny configuration changes. 

**Additional context.**:

None.

**Comment by jbartosik** [comment]
Thanks.  Unfortunately we currently don't have much capacity to work on Addon Resizer
