### ISSUE TITLE
VPA e2e actuation, admission-controller, and updater test suites are failing

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#5727]
It seems to me that #5680 that broke VPA e2e tests. @wu0407 can you take a look?

* [vpa-actuation](https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-actuation) tests are consistently failing. [First failing run started on 2023-05-02 14:30 CEST](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1653376481008553984), [last passing run started on 2023-05-02 12:23 CEST](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1653344519522881536).
* [vpa-admission-controller](https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-admission-controller) tests are consistently failing. [First failing run started on 2023-05-02 13:35 CEST](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-admission-controller/1653362639243317248), [last passing run started on 2023-05-02 11:35 CEST](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-admission-controller/1653332439788949504).
* [vpa-updater](https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#autoscaling-vpa-updater) tests are consistently failing. [First failing run started on 2023-05-02 14:01 CEST](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-updater/1653369182730850304), [last passing run started on 2023-05-02 12:01 CEST](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-updater/1653338983192596480).

[Two PRs labeled VPA merged on that day](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+is%3Aclosed+label%3Avertical-pod-autoscaler+merged%3A2023-05-02):
* #5680 at 12:58 UTC+2 (so CEST) (matches when tests started to fail) and
* #5676 at 15:46 UTC+2 (CEST) (failing tests already started by that time).

**Comment by jbartosik** [comment]
I think the problem is that tests are not creating VPA objects correctly now.

For example while `raises request according to container min limit set in LimitRange` test case was running I printed VPA it created and it has empty status[1]. But the test is supposed to set a recommendation ([here](https://github.com/kubernetes/autoscaler/blob/47117ad68c6dfa512e8fd8ea271be30054717da1/vertical-pod-autoscaler/e2e/v1/admission_controller.go#L506)).

It looks like after #5680 we can't set status like we used to.  I think we should fix our e2e and mention that the change is breaking this way too but we might have to revert it.

@wu0407 can you fix those tests?

@mwielgus @kgolab what do you think?

[1]

```bash
$ kubectl get vpa --all-namespaces
NAMESPACE                       NAME          MODE   CPU   MEM   PROVIDED   AGE
vertical-pod-autoscaling-9363   hamster-vpa   Auto                          119s
jbartosik-macbookpro:~ jbartosik$ kubectl get vpa --all-namespaces -oyaml
apiVersion: v1
items:
- apiVersion: autoscaling.k8s.io/v1
  kind: VerticalPodAutoscaler
  metadata:
    creationTimestamp: "2023-05-08T12:31:57Z"
    generation: 1
    name: hamster-vpa
    namespace: vertical-pod-autoscaling-9363
    resourceVersion: "17919"
    uid: 3387c7dd-81e4-4909-9217-c367ada9b04d
  spec:
    resourcePolicy: {}
    targetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: hamster-deployment
    updatePolicy:
      updateMode: Auto
kind: List
metadata:
  resourceVersion: ""

```

**Comment by voelzmo** [comment]
Wait, isn't `raises request according to container min limit set in LimitRange` only deploying an admission-controller and no recommender at all? How could the VPAs `status` be updated in a test like this?

**Comment by jbartosik** [comment]
@voelzmo **the test** is setting recommendation ([here](https://github.com/kubernetes/autoscaler/blob/47117ad68c6dfa512e8fd8ea271be30054717da1/vertical-pod-autoscaler/e2e/v1/admission_controller.go#L501)). That's why we don't want recommender running in those tests. We don't want recommendations written by the recommender, we want recommendations written by the test scenario.

**Comment by jbartosik** [comment]
vpa-actuation, vpa-admission-controller, and vpa-updater tests passed after the revert PR merged.

**Comment by wu0407** [comment]
I will fix that

**Comment by voelzmo** [comment]
Ah, I see, that makes sense! When reviewing the PR, I didn't run the e2e tests (which in hindsight I probably should have), but checked that VPA works for a deployed example workload  – and that succeeded.
So this is about also allowing the test setup to set the VPA's `status` correctly, the VPA was working correctly (mostly?).

I think there's a few places where updating the `status` is currently ignored, like patching recommendations in [v1beta2](https://github.com/kubernetes/autoscaler/blob/d3ec0c4d049084bc5bb266a19448df0e82e3056a/vertical-pod-autoscaler/e2e/v1beta2/common.go#L387) and in [v1](https://github.com/kubernetes/autoscaler/blob/d3ec0c4d049084bc5bb266a19448df0e82e3056a/vertical-pod-autoscaler/e2e/v1/common.go#L399) and in places where we upload an entire VPA with `spec` and `status` together, [like the one you linked ](https://github.com/kubernetes/autoscaler/blob/47117ad68c6dfa512e8fd8ea271be30054717da1/vertical-pod-autoscaler/e2e/v1/admission_controller.go#L507)

I can take a look at this and take the commits from the original PR and add the necessary test modifications – or is something that you want to take a shot at today, @jbartosik?
