### ISSUE TITLE
VPA in-place vertical scaling 

### ISSUE THREAD

**Issue by THMAIL** [kubernetes/autoscaler#5744]
**Which component are you using?:**
VerticalPodAutoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.:**
While reading the [doc](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#quick-start) of VPA, I found that "Once restart free ("in-place") update of pod requests is available, it may be used as the preferred update mechanism by the "Auto" mode.". 

But when I have a try,it doesn't work at all ！my k8s version is 1.27.1 who has support [in-place feature](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#kubelet-restart-tolerance). Then I read the code of VPA, I found that the code of Updater Controller still evict pod !

Kubernetes (>= 1.27 version) has supported updating pods in-place, but VPA currently uses eviction and reconstruction to modify existing pods. This greatly disrupts the stability of the business.And this does not align with the description of Auto mode in your documentation, which states that Auto mode supports in-place updates.

**Describe the solution you'd like.:**
[k8s in-place](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#kubelet-restart-tolerance)
We can modify the current code of the Updater module to change the pod updating logic from eviction to both eviction and in-place updates. When the VPA runs in auto mode, it will try to update in-place first, and if it fails, it will evict and then update in-place.

Describe any alternative solutions you've considered.:

I can rely on the existing behavior that replaces Pods with new Pods. This will trigger longer outages than an in-place resize, and even if my legacy app is able to tolerate the replacements that happen, there is a bigger risk of a disruption to the end user experience.

Additional context.:
[k8s-inplace](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#kubelet-restart-tolerance)
https://github.com/kubernetes/enhancements/issues/1287

**Comment by voelzmo** [comment]
Hey @THMAIL, thanks for asking about this feature! There's already an issue tracking this, so I'll go ahead and close this one.

/duplicates https://github.com/kubernetes/autoscaler/issues/4016
/close

**Comment by abasha1** [comment]
hello guys, @voelzmo  @THMAIL this problem is solved?
