### ISSUE TITLE
Cluster Autoscaler app version 1.25.x Helm chart missing from repo

### ISSUE THREAD

**Issue by mw-tlhakhan** [kubernetes/autoscaler#5761]
**Which component are you using?**:  cluster autoscaler
**What version of the component are you using?**: 1.25
**What environment is this in?**: Helm charts
**What did you expect to happen?**:  CA Helm chart for app version 1.25.x is available for use.
**What happened instead?**:  Missing Helm chart for CA with app version 1.25.x.

**How to reproduce it (as minimally and precisely as possible)**:
```
% helm repo add autoscaler https://kubernetes.github.io/autoscaler
"autoscaler" has been added to your repositories

% helm search repo autoscaler --versions | head
NAME                               	CHART VERSION	APP VERSION	DESCRIPTION
autoscaler/cluster-autoscaler      	9.28.0       	1.26.2     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.27.0       	1.24.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.26.0       	1.24.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.25.0       	1.24.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.24.0       	1.23.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.23.2       	1.23.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.23.1       	1.23.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.23.0       	1.23.0     	Scales Kubernetes worker nodes within autoscali...
autoscaler/cluster-autoscaler      	9.22.0       	1.23.0     	Scales Kubernetes worker nodes within autoscali...
```

Release for cluster autoscaler 1.25.1: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.25.1
Kubernetes to cluster autoscaler version guideline:  https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases

**Comment by gjtempleton** [comment]
Hey, we don't believe this is a bug, we don't cut a release of the helm chart for each version of the CA currently, instead providing the ability for users to override the CA image tag as appropriate.

**Comment by saiharshitachava** [comment]
@gjtempleton,  Could you confirm if that's the case?

Can we use helm chart of latest and just replace the image?

**Comment by qoehliang** [comment]
I am also curious to know if we should use the latest helm chart available or the latest helm chart available for the specific Kubernetes version. E.G. I am on Kubernetes v1.24. Should I use the latest helm chart that has an app version of 1.24.X or can I use the latest helm chart which as of today has an app version of 1.27.2.

**Comment by ldemailly** [comment]
it's a bit risky to not release the chart in sync with the image, what if you change or add flags that older/newer images don't understand (thus creating a crashing or misfunctioning pod)

at least document which range of image is applicable for which chart version maybe? (though having parity would be clearer)

**Comment by Shubham82** [comment]
@mw-tlhakhan, if your issue is resolved, can we close this issue?

**Comment by Shubham82** [comment]
> @Shubham82, yes, my issue is resolved. I did not encounter any problems with using the latest Helm chart and overriding the CA `image.tag` to the one compatible with my Kubernetes version.

Thanks @mw-tlhakhan for the confirmation.

**Comment by Shubham82** [comment]
I'm closing this as it is resolved.
