### ISSUE TITLE
Disable InterPodAffinity predicate if only soft affinity is used by pods

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#577]
As described in #281 we disable affinity predicate (for efficiency) if no pod in the cluster is using affinity. Looking at the code it looks like we don't distinguish between soft (preferedDuringScheduling) and hard (requiredDuringScheduling) affinity. CA completely ignores soft affinity anyway, so we should only enable the predicate if at least a single pod uses hard affinity.

cc: @mwielgus @aleksandra-malinowska @bskiba

**Comment by aleksandra-malinowska** [comment]
Fixed by #640
