### ISSUE TITLE
Cluster Autoscaler patch releases May 2023

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#5774]
I'm planning to cut the latest round of CA patch releases as per [the schedule](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#patch-releases), on Monday the 22nd of May.

I will be cutting releases for 1.24, 1.25, 1.26, and 1.27 release branches. If you have any bug fixes for the versions listed that haven't yet been cherry-picked, please raise them and reference this issue.

**Comment by maximrub** [comment]
It will be great if you can include
https://github.com/kubernetes/autoscaler/pull/5340

**Comment by gjtempleton** [comment]
@maximrub , if you're able to raise the cherry-picks, I'm more than happy to review them either late tomorrow or on Monday before I cut the releases.

**Comment by maximrub** [comment]
Hi @gjtempleton

**Comment by vadasambar** [comment]
1.24:
- https://github.com/kubernetes/autoscaler/pull/5785
- https://github.com/kubernetes/autoscaler/pull/5784

**Comment by gjtempleton** [comment]
It won't be until this evening UK time, I'm doing this outside of my day to day work commitments.

**Comment by gjtempleton** [comment]
Raised #5794, #5795, #5796, and #5797 to update the vendoring of k/k for each.

**Comment by gjtempleton** [comment]
Promotion to registry.k8s.io PR, images will be available shortly after this is merged: https://github.com/kubernetes/k8s.io/pull/5317

**Comment by qianlei90** [comment]
after this 1.24 will enter maintenance mode, is there any chance to merge PRs like these?

- https://github.com/kubernetes/autoscaler/pull/5804
- https://github.com/kubernetes/autoscaler/pull/5521 (have not create a cherry pick PR yet)

**Comment by gjtempleton** [comment]
Releases have been cut. One issue with the 1.24 release notes as I didn't finish the tagging and release notes until after the merging of #5804, however this hasn't, and won't, make it into a 1.24 release. Working on updating this now.

**Comment by gjtempleton** [comment]
1.24 now pointing to the correct commit.

/close

**Comment by zchenyu** [comment]
Just to confirm, is https://github.com/kubernetes/autoscaler/pull/5804 in CA 1.24.2 ? and if not, will it be in a later release?

**Comment by qianlei90** [comment]
> Just to confirm, is #5804 in CA 1.24.2 ? and if not, will it be in a later release?

@zchenyu unfortunately this PR is not in v1.24.2, and it may still have a release later as v1.24 has enter maintenance mode:

<img width="929" alt="image" src="https://github.com/kubernetes/autoscaler/assets/5654791/ca4c6c6a-deb3-45f3-ba2e-a266c8305da2">

cc @gjtempleton
