### ISSUE TITLE
Support RRSA auth in AliCloud

### ISSUE THREAD

**Issue by maximrub** [kubernetes/autoscaler#5779]
I wanted to know when the RRSA auth support will be added, what version?
My PR to add the support was merged last month
https://github.com/kubernetes/autoscaler/pull/5340

**Comment by Shubham82** [comment]
Hi, @maximrub I have checked it, your PR merged in the upstream after the cluster-autoscaler-release-1.27 branch had been cut. that's why it is not reflected in the CA v1.27. It will be there in the next version of Cluster Autoscaler i.e. CA v1.28.

**Comment by maximrub** [comment]
yes, waiting for their approval

**Comment by Shubham82** [comment]
So we can close this issue if your concern is resolved.
WDYT?

**Comment by maximrub** [comment]
yes, closing

**Comment by Shubham82** [comment]
Thanks @maximrub
