### ISSUE TITLE
Tuning "scale-down-utilization-threshold"

### ISSUE THREAD

**Issue by youwalther65** [kubernetes/autoscaler#5793]
Great KubeCon session "[Deep Dive into Autoscaling - Marcin Wielgus, Google & Vivek Bagade, Google](https://www.youtube.com/watch?v=3RwgRWIs9Q4&t=972s)" from KubeCon NA 2019 describes at recording time 17:09, that "scale-down-utilization-threshold" needs to be lowered compared to default of 0.5 to have tighter binpacking of nodes.
For me it is a bit counterintuitive. With larger values, for example 0.7, more nodes could be a potential scale-down candidate if pods fit into other nodes and nodes with lower actual request utilization values like 0.3 are included anyway. And I have seen some customers using values > 0.5
There is no explanation regarding tuning of this parameter beside the KubeCion talk. It would be great to get some better explanation in FAQ.
I considered doing some tests with different values above and below the default 0.5 and observe the "scaled_down_nodes_total" metric but wanted to have a discussion here first.
Thank you!

**Comment by vadasambar** [comment]
Doesn't make a lot of sense to me either. My understanding is, increasing the threshold allows for tighter bin-packing and higher utilisation while decreasing the threshold allows for overprovisioning and looser packing of nodes. 

I wonder if the descriptions for higher and lower thresholds were flipped.

**Comment by youwalther65** [comment]
Maybe the former Kubecon presenters @mwielgus or @vivekbagade can comment on this!
