### ISSUE TITLE
Aggressive scale down followed by scale up

### ISSUE THREAD

**Issue by DaveTaddei-CR** [kubernetes/autoscaler#581]
Since upgrading to kubernetes 1.8 we also upgraded the autoscaler to 1.1.0.  We have noticed an odd behaviour where the autoscaler appears to try and scale to the minimum number of nodes and then immediately scale up again.

To reproduce:
* start with a single node and increase the number of replicas of a pod one at a time, continue until there are three nodes
* decrease the number of replicas gradually allowing the autoscaler time to adjust

The autoscaler appears to mark multiple nodes for removal without considering the accumulated resources required.  The scheduler is then unable to accommodate the required pods on the remaining nodes which triggers a scale up.  When dealing with a minimum of 1 node its not uncommon to observe a flip-flop behaviour.

**Comment by DaveTaddei-CR** [comment]
The scale down and scale up has been observed.  The logs do not completely reflect this however.  They identify a node could be scaled down using the fast-evaluation.  Lack of space to re-schedule a pod causes the scale down to abort.  In practice the scale down is occurring anyway.  A short time later a scale up is observed.

A summarised sequence of events is as follows:
08:31:26.335664 - unschedulable pod, adding another node
08:33:39 - pod running on new new, utilisation 31%
08:38:34.037346 - pod on 31% node could not be removed as a place could not located for it
08:39:16 - added another pod  (2->3 replicas)
08:42:51 -removed pod (3->2 replicas), 1 pod per node currently
08:43:39.404887 - node at 31% identified for removal
08:43:39.404974 - pod identified node as unsuitable for removal
08:45-52 - scale up but no indication a scale down has occurred

[autoscaler-log.txt](https://github.com/kubernetes/autoscaler/files/1672850/autoscaler-log.txt)

**Comment by MaciekPytel** [comment]
There was no scale-down performed by CA during the time covered by your log. 'Fast evaluation' only means that the second condition (possibility to move pods) will be checked at all. A node will actually be deleted only if it can be removed for 10 consecutive minutes. If there was a scale-down there would be logs signifying it coming from a lot of different places (simulator saying the node could be deleted, creating events, draining, actual node deletion).

If you observed nodes disappearing during that period they were not deleted by CA. Are you sure you don't have any other autoscalers enabled (like AWS autoscaler or a second instance of CA(unlikely))?

**Comment by aleksandra-malinowska** [comment]
@DaveTaddei-CR any update on this? If this has been resolved, can you please close the issue?

**Comment by DaveTaddei-CR** [comment]
The result of this was an incompatible cluster-autoscaler version used with the kubernetes cluster.  There are now compatibility matrices available.
