### ISSUE TITLE
Provide metrics endpoints for VPA components

### ISSUE THREAD

**Issue by Alvaro-Campesino** [kubernetes/autoscaler#5817]
**Which component are you using?**:
Updater, recommender and admission

**Which component hosted in this repository is this a feature for?**

Recommender and updater
**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
No

**Describe the solution you'd like.**:

I would like for the recommender and the updater to have a `/metrics` endpoint where events such as:
* restarted pods
* scaled pods
* errors in scaling
* Status of the conection with the metrics storage
* other usuful events could be published.

**Describe any alternative solutions you've considered.**:

**Additional context.**:

This information will be useful for creating dashboads or alerts related to this metrics

**Comment by R-Studio** [comment]
@Alvaro-Campesino do you created a Grafana dashboard with the VPA metrics or how do you use it?
