### ISSUE TITLE
OCI autoscaler throwing 'Retrying: Service error:NotAuthorizedOrNotFound' error with InstancePrincipal

### ISSUE THREAD

**Issue by bettaps** [kubernetes/autoscaler#5821]
**Which component are you using?**:
Cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.27

**What k8s version are you using (`kubectl version`)?**: 1.26

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: OCI

**What did you expect to happen?**: Cluster-Autoscaler pods should initialise successfully

**What happened instead?**: Cluster-autoscaler pods are running but logs have the error: oci_manager.go:164] unable to fill cache on startup. Retrying: Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found..

**How to reproduce it (as minimally and precisely as possible)**: Install cluster-autoscaler 1.27 helm chart on OKE cluster with Instance Principal enabled. cluster-autoscaler pods have the above error.

**Anything else we need to know?**: Instance Principal has been enabled with the required policies in root tenancy.

**Comment by bettaps** [comment]
This was a problem with dynamic group policy. Closing ticket.

**Comment by sourabhgupta385** [comment]
@bettaps May I know what policy did you used to fix it? I am also having same issue. Thanks

**Comment by ivanamato** [comment]
> 

Same here. Any news?

**Comment by jlamillan** [comment]
@ivanamato, example policies can be found in the project [README](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/oci#iam-policy-if-using-instance-principals). If you are still having issues, please file an issue and tag me.
