### ISSUE TITLE
VPA Events Property Should Capture Information on Pod Resizing

### ISSUE THREAD

**Issue by kewynakshlley** [kubernetes/autoscaler#5831]
I am conducting a benchmark between VPA (Vertical Pod Autoscaler) and HPA (Horizontal Pod Autoscaler) using Kubernetes with the autoscaler version 1.27.2. My analysis involves metrics such as event time, application performance, and resource usage on the node. One of my objectives is to track instances where a pod is resized with increased resources when utilizing VPA. I expected this information to be stored in the events property when describing my VPA object. However, the events property remains empty even when my pod undergoes multiple recreations.

https://github.com/kubernetes/autoscaler/blob/ac3946664db3cb9a15a5a6e43730a7ea0fe2a193/vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go#L142

In the context of VPA, the Pod itself can be destroyed/replaced and the information about events can be lost/hard to track. Pods resized vertically don't save information about events of previous pods.

I would appreciate any insights or suggestions regarding this matter. Is it possible that this feature is not functioning as intended, or could there be a missing configuration in my deployments?

**Comment by voelzmo** [comment]
Hey @kewynakshlley,

You identified the right line that produces an Event whenever a Pod is evicted by the Updater! When you look at [the API docs for the method](https://pkg.go.dev/k8s.io/client-go/tools/record@v0.26.1#EventRecorder.Event) that is used here (`eventRecorder.Event`), you can see that the first argument is the Object that the Event is recorded for – in this case that's the Pod that is evicted.

You can look at the Pod eviction Events with `kubectl get events -A --field-selector=reason=EvictedByVPA`. As the Events are recorded for the Pod, not for the VPA, you don't see them when inspecting the VPA object.

Hope that helps!

/remove-kind bug
/kind consulting

**Comment by voelzmo** [comment]
¯\_(ツ)_/¯

/kind support

**Comment by kewynakshlley** [comment]
@voelzmo thanks for explaining, that makes sense. I will be closing this issue.
