### ISSUE TITLE
Showing scaling up in MIG but not scaling in GCE - Even when creation it not launching more than 3 nodes across zones

### ISSUE THREAD

**Issue by dineshsckloud9** [kubernetes/autoscaler#584]
Multizone scaling with MIG per zone seems working but could not launch more than 3 instances.. MIG showing 1 -> 2 but its not launching in gce... What could be the problem?

I0127 04:52:37.565409 5 scale_up.go:110] Skipping node group https://content.googleapis.com/compute/v1/projects/global-snow-193212/zones/europe-west1-b/instanceGroups/kubernetes-minion-group - max size reached
W0127 04:52:37.566044 5 scale_up.go:99] Node group https://content.googleapis.com/compute/v1/projects/global-snow-193212/zones/europe-west1-d/instanceGroups/kubernetes-minion-group is not ready for scaleup
W0127 04:52:37.566348 5 scale_up.go:99] Node group https://content.googleapis.com/compute/v1/projects/global-snow-193212/zones/europe-west1-c/instanceGroups/kubernetes-minion-group is not ready for scaleup

Why it is not ready?

Kubernetes - v1.9.2
Cluster-Autoscaler - v1.1.0

/sig scalability

**Comment by bskiba** [comment]
My first guess would be that you hit some quota. But  AFAIK this should be visible as errors in the UI.

Can you also check cluster autoscaler configmap?
kubectl get -o yaml configmap cluster-autoscaler-status -n kube-system

**Comment by MaciekPytel** [comment]
If it's a quota issue (I agree with @bskiba that's most likely) you can diagnose it easily in UI by going "Compute Engine" -> "Instance Groups" -> click on your MIG. You will see all instances, if you hit a quota some of them will not exist and have a warning saying which quota you hit.

**Comment by dineshsckloud9** [comment]
Yes! It was a quota issue.. Thanks guys
