### ISSUE TITLE
GKE Add support for L4 GPUs in Node Autoprovisioning

### ISSUE THREAD

**Issue by samos123** [kubernetes/autoscaler#5847]
I tried using auto provision to create nodes with L4 GPUs on GKE 1.26 and 1.27 and L4 GPUs don't seem to be supported. Unsure if I simply need to use a newer version or if this feature hasn't landed yet, so filing this FR.

These are the node selectors I used:
```
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-l4
    cloud.google.com/gke-spot: "true"
```

Log message seen from cluster autoscaler:
```
messageId: "no.scale.up.nap.pod.gpu.type.not.supported"
parameters: [
0: "nvidia-l4"
]
```

**Comment by bhack** [comment]
I think it is the same problem with  `nvidia-a100-80gb` right?

**Comment by samos123** [comment]
I was hoping it would at least have nvidia-tesla-a100 but seems it doesn't have it. I guess I'm back to creating 0 node nodepools for each possible machine type of A100.

**Comment by rjanovski** [comment]
FYI - `nvidia-l4` works as autoprovisioning resource on GKE 1.28.3-gke.1286000 (regular channel).

<img width="525" alt="image" src="https://github.com/kubernetes/autoscaler/assets/12986880/1cef40ad-7e40-4d4c-935b-8eff1a7a2c8e">

<img width="610" alt="image" src="https://github.com/kubernetes/autoscaler/assets/12986880/50799888-e06a-4f81-818d-809debc43984">
