### ISSUE TITLE
Add support for Metros in Equinix Metal

### ISSUE THREAD

**Issue by enkelprifti98** [kubernetes/autoscaler#5855]
**Which component are you using?**:

Cluster Autoscaler for Equinix Metal

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Equinix Metal will be deprecating `facilities` for `metro` soon so metro deployments should be supported.

**Describe the solution you'd like.**:

Instead of defining `facility` for the autoscaling pool, the user should be able to define `metro`.

**Describe any alternative solutions you've considered.**:

None are possible.

**Comment by displague** [comment]
This is a dupe of https://github.com/kubernetes/autoscaler/issues/4287 (which was robo closed)

**Comment by displague** [comment]
/close

Fixed by #6078
