### ISSUE TITLE
Allow nodes that are not managed by the CPEM / CCM to work with the autoscaler node pools in Equinix Metal

### ISSUE THREAD

**Issue by enkelprifti98** [kubernetes/autoscaler#5859]
**Which component are you using?**:
Cluster Autoscaler for Equinix Metal.

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently it's not possible to have Equinix Metal nodes NOT managed by the CCM / CPEM be able to work with the cluster autoscaler or be part of a pool.

**Describe the solution you'd like.**:
Allow nodes that are not managed by the CCM / CPEM to work with the autoscaler node pools. From my testing the autoscaler looks for the node `spec.ProviderID` string which is added by CCM / CPEM and if it is missing for any single node, the autoscaler throws errors and cannot proceed with its logic for other nodes that are managed by the CCM / CPEM. This should be more graceful in my opinion and allow the autoscaler to work even if there are nodes that may not qualify.

**Describe any alternative solutions you've considered.**:
I have discovered that manually adding the node `spec.ProviderID` string to nodes that are NOT managed by the CCM / CPEM makes them work with the autoscaler.

**Comment by displague** [comment]
@enkelprifti98 As far as I can tell, after reviewing other Cloud Provider implementations, spec.ProviderID is a requirement for the node to be used by Autoscaler. The Cloud Provider is expected to provide this value and the formatting is defined by that cloud provider.

Here's an example from the EC2 provider:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L112-L153

(I also check DO, Linode, and Heztner's).
