### ISSUE TITLE
cluster-autoscaler release for kubernetes 1.9.x missing

### ISSUE THREAD

**Issue by alexanderkjeldaas** [kubernetes/autoscaler#586]
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases does not list a kubernetes 1.9.x release.

**Comment by alexanderkjeldaas** [comment]
Or 1.10.x which is incoming.

**Comment by bskiba** [comment]
Seems like we need release notes for 1.1.x
