### ISSUE TITLE
Add label app.kubernetes.io/version - helm chart

### ISSUE THREAD

**Issue by psimms-r7** [kubernetes/autoscaler#5871]
**Which component are you using?**:

cluster-autoscaler helm chart

helm chart

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Can we add the label app.kubernetes.io/version for the cluster-autoscaler helm chart please this would help with tracking versions

**Describe the solution you'd like.**:

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by psimms-r7** [comment]
https://github.com/kubernetes/autoscaler/pull/5874

**Comment by Shubham82** [comment]
Closing this issue, as it is resolved by PR #6012
