### ISSUE TITLE
Support GitHub/Prow labeling for issue/PR triage

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/autoscaler#5872]
We're onboarding new contributors who are looking for issues and PRs to work on.
To make it easier for new folks to onboard to a certain area I'd like to suggest that we open up the selection of area labels so issues and PRs can be tagged as `cluster-autoscaler`, `vertical-pod-autoscaler`, `addon-resizer` by people more easily.

I'd recommend using the [`/area`](https://prow.k8s.io/command-help#kind) command.

To do this it should be enough that we rename the existing labels to have the `area/` prefix.
More testing is needed, but we'll need help from an existing maintainer.

/kind cleanup
/cc @mwielgus

**Comment by jbartosik** [comment]
I like the idea of allowing people to tag issues.

**Comment by Shubham82** [comment]
@kwiesmueller is there any update on this issue?

**Comment by kwiesmueller** [comment]
I didn't get a chance to work on this. Feel free to pick it up if interested.

**Comment by Shubham82** [comment]
I think maintainers(owners of the autoscaling repo) have the right to add labels.

**Comment by Shubham82** [comment]
cc @mwielgus @gjtempleton @MaciekPytel
could you please take a look?

**Comment by gjtempleton** [comment]
Yeah, it'll require some work from a repo admin.

Bits that I think will need to be done and who can do them:

- [ ] Create new versions of existing labels with `area/` prefix (Needs to be done by a repo admin)
- [ ] Update auto-labelling of PRs/issues to use the new labels - probably want to cherry-pick this back to all currently supported release branches to ensure consistency going forward (PRs from anyone can cover this.)
- [ ] (Not sure if worth doing this/can we do it programmatically?) Update past issues/PRs to migrate labels to ensure consistency across PRs/issues. (Addition of new labels should be doable by anyone, I think removal of old ones would have to be a repo admin?)

Anything people think is missing here and any thoughts on whether point 3 is worth doing?

**Comment by Shubham82** [comment]
> Yeah, it'll require some work from a repo admin.
> 
> Bits that I think will need to be done and who can do them:
> 
> * [ ]  Create new versions of existing labels with `area/` prefix (Needs to be done by a repo admin)
> * [ ]  Update auto-labelling of PRs/issues to use the new labels - probably want to cherry-pick this back to all currently supported release branches to ensure consistency going forward (PRs from anyone can cover this.)
> * [ ]  (Not sure if worth doing this/can we do it programmatically?) Update past issues/PRs to migrate labels to ensure consistency across PRs/issues. (Addition of new labels should be doable by anyone, I think removal of old ones would have to be a repo admin?)
> 
> Anything people think is missing here and any thoughts on whether point 3 is worth doing?

Thanks @gjtempleton,
It sounds good to me.

**Comment by voelzmo** [comment]
Overall this would be great to have!

> Anything people think is missing here and any thoughts on whether point 3 is worth doing?

I'm wondering if we would get this for free if instead of creating new labels  we would rename the existing ones?

**Comment by gjtempleton** [comment]
> I'm wondering if we would get this for free if instead of creating new labels we would rename the existing ones?

Looks like the answer is yes. I've just experimented with the helm-charts label renaming it to `area/helm-charts` and carries over.

Next question I guess is which labels we want to make this change to, just the relevant sub-projects contained within the repo?

**Comment by voelzmo** [comment]
sounds good to me. We don't have to get everything on the first shot, so this seems like a good start!
Thanks, @Shubham82!

**Comment by Shubham82** [comment]
Thanks @voelzmo for taking a look at this.

**Comment by gjtempleton** [comment]
OK, I've updated the labels suggested by you @Shubham82 and created #6506 to update the auto-labels applied on the creation of PRs.

**Comment by Shubham82** [comment]
> OK, I've updated the labels suggested by you @Shubham82 and created #6506 to update the auto-labels applied on the creation of PRs.

Thanks, @gjtempleton for the above PR.
