### ISSUE TITLE
Clarification on restart-free updates with VPA

### ISSUE THREAD

**Issue by abasha1** [kubernetes/autoscaler#5885]
Hello,

I'm currently reviewing the KEDA and VPA projects for possible implementation and had a question about a specific feature mentioned in the documentation.

The documentation for VPA mentions an "Auto" mode that may take advantage of restart-free updates once they become available. From my understanding, the current approach of VPA requires pods to be restarted when their resource allocations are adjusted. However, the mention of "restart-free updates" suggests a future feature where VPA can adjust the resources of a running pod without needing to restart it.
![image](https://github.com/kubernetes/autoscaler/assets/51801315/3a76f930-a808-402c-8349-5ee6c4a9e970)

Can you provide more information on this feature? Specifically, I'd like to understand:

1.Does "restart-free" mean that the pod can be scaled without being recreated?(or you mean rolling update? ) 
2. If it is a planned feature, is there an expected timeline for its implementation? ( as i read in kubernetes 1.27.1 version its already possible) 
I'm particularly interested in understanding if and how we could use VPA to dynamically scale pods without causing disruption by recreating them.

Thank you for your assistance.

**Comment by Shubham82** [comment]
cc @jbartosik @voelzmo

**Comment by jbartosik** [comment]
This is a planned feature. There are more details in [enhancement proposal](https://github.com/kubernetes/autoscaler/blob/d17b1aaaec7fdb2c2afad18ce8c076f01e0f6f4b/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md) and on #4016. I also want to do some related changes to allow control in direction of scaling in place #5754.

This is not exactly "restart-free". The alpha feature available in 1.27 allows containers to be resized in place, but container might specify that it wants to be restarted when its memory or CPU are change.

I think this is a really great improvement to how VPA works so I'd like to see support for in-place updates in VPA soon. But I can't commit to any specific timeline.

Please let me know if you have any questions / suggestions

**Comment by Shubham82** [comment]
Thanks, @jbartosik for the above information, it's really useful.

**Comment by Shubham82** [comment]
> This is a planned feature. There are more details in [enhancement proposal](https://github.com/kubernetes/autoscaler/blob/d17b1aaaec7fdb2c2afad18ce8c076f01e0f6f4b/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md) and on #4016. I also want to do some related changes to allow control in direction of scaling in place #5754.
> 
> This is not exactly "restart-free". The alpha feature available in 1.27 allows containers to be resized in place, but container might specify that it wants to be restarted when its memory or CPU are change.
> 
> I think this is a really great improvement to how VPA works so I'd like to see support for in-place updates in VPA soon. But I can't commit to any specific timeline.
> 
> Please let me know if you have any questions / suggestions

I'm closing this issue according to the above explanation given by @jbartosik.
@abasha1 Please reopen it if you have any concerns.
