### ISSUE TITLE
[Magnum][ClusterAutoscaler] Backport control-plane label

### ISSUE THREAD

**Issue by modzilla99** [kubernetes/autoscaler#5888]
I fixed #5751 with #5776, but since we already deploy v1.26 and v1.27 with that node role, those versions are also effected. Can this change be cherry-picked for those releases as well, or do we have to build custom images for our customers?

**Comment by Shubham82** [comment]
We can do it in the following release of CA:  1.26, 1.25, 1.24
if it seems good then I'm up for it.

**Comment by tghartland** [comment]
No reason it can't be backported.
The openstack code still deploys the "master" label which is still caught by the existing condition, and the new check will just be for the "control-plane" label if manually added. Otherwise the new check does nothing.

**Comment by Shubham82** [comment]
Thanks @tghartland for the above info.

**Comment by modzilla99** [comment]
> We can do it in the following release of CA: 1.26, 1.25, 1.24 if it seems good then I'm up for it.

That would be amazing! ^^

**Comment by Shubham82** [comment]
@modzilla99 as per @tghartland above comment, it can't backport.
Am I understanding right?

**Comment by tghartland** [comment]
It can be backported. Sorry if I worded it confusingly!

**Comment by Shubham82** [comment]
@tghartland Please don't be sorry and thanks for confirmation.
I will open a PR for cherry-picked it to the previous releases.

**Comment by Shubham82** [comment]
I checked it, we have to do it for CA v1.27 also because it is not there: https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.27/cluster-autoscaler/cloudprovider/magnum/magnum_cloud_provider.go

These changes will reflect in the CA v1.28, so i will backport it in the v1.27 also.

**Comment by Shubham82** [comment]
Raised the following PR to fix this issue:
For CA 1.27 https://github.com/kubernetes/autoscaler/pull/5910
For CA 1.26 https://github.com/kubernetes/autoscaler/pull/5909
For CA 1.25 https://github.com/kubernetes/autoscaler/pull/5908
For CA 1.24 https://github.com/kubernetes/autoscaler/pull/5907

**Comment by Shubham82** [comment]
PTAL!

**Comment by modzilla99** [comment]
lgtm

**Comment by tghartland** [comment]
All good.

**Comment by Shubham82** [comment]
Thanks @tghartland and @modzilla99 for taking a look at PRs.

**Comment by Shubham82** [comment]
Closing this issue as all the related PRs are merged now.
For CA 1.27 https://github.com/kubernetes/autoscaler/pull/5910
For CA 1.26 https://github.com/kubernetes/autoscaler/pull/5909
For CA 1.25 https://github.com/kubernetes/autoscaler/pull/5908
For CA 1.24 https://github.com/kubernetes/autoscaler/pull/5907

**Comment by modzilla99** [comment]
Thank you @Shubham82 !
