### ISSUE TITLE
Clarification on restart-free updates with VPA

### ISSUE THREAD

**Issue by abasha1** [kubernetes/autoscaler#5889]
Hello,

I'm currently reviewing the KEDA and VPA projects for possible implementation and had a question about a specific feature mentioned in the documentation.

The documentation for VPA mentions an "Auto" mode that may take advantage of restart-free updates once they become available. From my understanding, the current approach of VPA requires pods to be restarted when their resource allocations are adjusted. However, the mention of "restart-free updates" suggests a future feature where VPA can adjust the resources of a running pod without needing to restart it.
![image](https://github.com/kubernetes/autoscaler/assets/51801315/aedc050c-a093-4bb6-ae2c-75bb7e8c3b02)

Can you provide more information on this feature? Specifically, I'd like to understand:

1.Does "restart-free" mean that the pod can be scaled without being recreated?(or you mean rolling update? )
2. If it is a planned feature, is there an expected timeline for its implementation? ( as i read in kubernetes 1.27.1 version its already possible)
I'm particularly interested in understanding if and how we could use VPA to dynamically scale pods without causing disruption by recreating them.

Thank you for your assistance.
```[tasklist]
### Tasks
```

**Comment by Shubham82** [comment]
Looks like a duplicate of #5885

you already opened it before.

/triage duplicate

**Comment by Shubham82** [comment]
closing in favor of #5885
