### ISSUE TITLE
Log format Json or LogFMT

### ISSUE THREAD

**Issue by DanielCastronovo** [kubernetes/autoscaler#5898]
**Which component are you using?**:
cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

**Describe the solution you'd like.**:

Support logformat JSON or logfmt

**Additional context.**:

Loki support only JSON & Logfmt

**Comment by NabilHouidi** [comment]
Hi,
I would like to work on this issue. 
I have one question for a start, is this a matter of adding support for the `--logging-format=json` flag? (similar to [this PR](https://github.com/kubernetes/kubernetes/pull/91532/files))

**Comment by Bryce-Soghigian** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1602-structured-logging/README.md 

Are we trying to have a structured logging mode?

**Comment by NabilHouidi** [comment]
I believe this is what is this issue is asking for.
I am new here, is this something aligned with the vision of the project? Can I work on it?
