### ISSUE TITLE
can not get the target cpu and memory

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/autoscaler#5914]
**Which component are you using?**: i use vpa

**What version of the component are you using?**:vpa

Component version:

**What k8s version are you using (`kubectl version`)?**:

$ kubectl version v1.26.3

i try to follow the Installation(https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler)
i try to run the examples/hamster.yaml , but the pod can not be reset . 
<img width="472" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/3aeaa8a0-c7fd-45fe-8559-31bb7c55d59c">

<img width="412" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/ab0d1171-4403-446e-9f60-a3ae6e17c561">
i can not get the target cpu and memory .
Troubleshooting is not useful for me 
how can i fix this bug?
looking for you help.

**Comment by Shubham82** [comment]
Hi @shixinlishixinli, have you enabled the metrics server on your cluster? IMO it is due to the metrics server. I tried it and after enabling it, the issue is resolved.

**Comment by Shubham82** [comment]
Please follow the prerequisites for vpa:
https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#prerequisites

**Comment by shixinlishixinli** [comment]
i have already install metrics server.
<img width="518" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/6cfe03a3-2d3d-4eb7-9ad8-b1e85a2095f5">
<img width="394" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/9ffaa626-1ebc-4e4b-8201-85b01fe71e5e">

**Comment by jbartosik** [comment]
In notice that in screenshots you attached VPA appears to have empty mode. In the [example yaml](https://github.com/kubernetes/autoscaler/blob/c887626bec01500ad3f895d7a4aa33cfe4efb171/vertical-pod-autoscaler/examples/hamster.yaml#L12) we don't set the mode but it should be changed to auto by [VPA admission webhook](https://github.com/kubernetes/autoscaler/blob/c887626bec01500ad3f895d7a4aa33cfe4efb171/vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler.go#L93C14-L93C26).

Please verify that VPA pods are runing (`kubectl get pod -n kube-system | grep vpa`).

If they are then I'd try deleting and recreating `hamster-vpa` object - maybe it was created before vpa-admission-controller started?

**Comment by shixinlishixinli** [comment]
hamster-vpa has empty mode.  vpa-nginx-test is a vpa set by myself  not by example code .  deleting and recreating is not useful for me

<img width="485" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/29594c96-386f-422f-af4f-f281fd95a713">

**Comment by shixinlishixinli** [comment]
i can not get any Recommender.

**Comment by jbartosik** [comment]
> i can not get any Recommender.

I don't understand. Please post commands and their output. From screenshot in https://github.com/kubernetes/autoscaler/issues/5914#issuecomment-1614572829 it looks like VPA is running.

> hamster-vpa has empty mode. vpa-nginx-test is a vpa set by myself not by example code . deleting and recreating is not useful for me

What do you mean it's not useful? Please paste commands you executed.

- Did you try `kubectl delete vpa hamster-vpa` to delete the VPA?
- Did it work?
- Did you run `kubectl apply -f hamster.yaml` after that?
- Did it create VPA with no mode?

What VPA version are you running? Please replace `{please-replace}` with end of the name of admission-controller pod and run `kubectl get pod -n kube-system vpa-admission-controller-{please-replace}  -ojsonpath='{.spec.containers[].image}{"\n"}'` then post output here to check the version

**Comment by shixinlishixinli** [comment]
i deploy vpa on a new computer , it works on the new computer,   it does not work on the old computer.  i do not know the reason,  but it works on the new computer
