### ISSUE TITLE
Add instructions for updating VPA CRD for next release

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/autoscaler#5921]
#5911 (see also #5675) changes definition of VPA CRD by adding subresource.

I think this means update to the next VPA minor release will be more involved than usually.

I think usually it's ok to just change VPA deployments to use new images. This time we also need to change resource definition. We need to update resource definition in a way that doesn't break any existing VPAs (we don't want to delete existing VPA objects, users hopefully have important data there!).

I think we need clear instructions for updating CRD. Would be great to have instructions to roll back the change in case some need to go back to an older VPA versions. If those instructions are more than 1 command it would be nice to script them.

@wu0407 @kwiesmueller can you take a look?

**Comment by wu0407** [comment]
I will do this recently

**Comment by jbartosik** [comment]
Thanks @wu0407 , K8s 1.28 has been released so we plan to do a VPA release soon and we'll need those instructions.
