### ISSUE TITLE
Events are missing from cluster-autoscaler

### ISSUE THREAD

**Issue by skorati** [kubernetes/autoscaler#5938]
**Which component are you using?**:
cluster-autoscaler 1.24.0

**What version of the component are you using?**:
1.24.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12+ceaf338", GitCommit:"1a1542f8fd7e4eac5c94d9111141be3c3829fe71", GitTreeState:"clean", BuildDate:"2023-04-08T20:36:14Z", GoVersion:"go1.18.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:
If cluster-autoscaler has scaled-up clusters based on the list of pending pods, then if would be helpful to see `TriggeredScaleUp` event on all such pods which were considered during scale-up

```
 Normal  TriggeredScaleUp    18m        cluster-autoscaler pod triggered scale-up: [{ibm://acc///cluster1/nodegroup1 1->2 (max: 8)}]
 Warning FailedScheduling    14m (x2 over 19m) default-scheduler  0/6 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 4 Insufficient cpu. preemption: 0/6 nodes are available: 2 Preemption is not helpful for scheduling, 4 No preemption victims found for incoming pod.
 Normal  TriggeredScaleUp    12m        cluster-autoscaler pod triggered scale-up: [{ibm://acc///cluster1/nodegroup 1->2 (max: 8)}]
 Normal  Scheduled        10m        default-scheduler  Successfully assigned default/pod1 to 10.x.x.x
```

**What happened instead?**:

Not all pods have this event, some pods only show `FailedScheduling` and then go to running state. 
Also some times, Cluster-autoscaler logs also does not have details about all pods.
```
I0614 13:11:26.688598    1 filter_out_schedulable.go:162] Pod default.pod1 marked as unschedulable can be scheduled on node template-node-for-ibm://acc///cluster1/nodegroup-upcoming-0. Ignoring in scale up.
I0614 13:12:39.358761    1 filter_out_schedulable.go:162] Pod default.pod2 marked as unschedulable can be scheduled on node template-node-for-ibm://acc///cluster1/nodegroup2-upcoming-0. Ignoring in scale up.
I0614 13:13:44.714497    1 filter_out_schedulable.go:162] Pod default.pod1 marked as unschedulable can be scheduled on node template-node-for-ibm://acc///cluster1/nodegroup2-upcoming-0. Ignoring in scale up.
```
My understanding is logging of pod/node details for some operations has a quota(loggingQuota), due to which logs might not have all details (this quota is now increased from 1.27(https://github.com/kubernetes/autoscaler/pull/5380)), so having scaleup events logged in pod would be helpful for debugging when something goes wrong in the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster 1.24
- Deploy cluster-autoscaler 1.24 and enable auto-scaling
- Deploy workload to scale-up and observe the events of pods stuck in pending state.

**Anything else we need to know?**:

**Comment by Horiodino** [comment]
Hii @jbartosik  @skorati  if anyone not working on it can i work ? i haven't any experience but i think i can learn something more about autoscaler stuff.
