### ISSUE TITLE
how to build vpa-recommender image

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/autoscaler#5946]
i can successfully run hamster.yaml . and  i found that the image i use is 'registry.k8s.io/autoscaling/vpa-recommender:0.14.0' . the image is download form registry.k8s.io  not  form source code.  i want to use the image build form the source code.   How to use this compiled image?

best
Lisa Shi

**Comment by Shubham82** [comment]
Hi @shixinlishixinli
You can create a Recommender and Updater with the help of Makefile present in their respective directories.
The [Makefile](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Makefile) for the recommender is under **`/vertical-pod-autoscaler/pkg/recommender`**.  For Updater [Makefile](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/pkg/updater) is under **`/vertical-pod-autoscaler/pkg/updater`**. After creating your custom images then do modify the deployments present under the [deploy](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/deploy) folder, for Recommender and Updater, then follow the [Installation](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#install-command) mentioned in the README.

**Comment by shixinlishixinli** [comment]
hi 

> m82

thanks for your help.

i have create a recommender and updater by Makefile.  i do not know how to create my custom image. i am sorry , i am a newer at k8s


best
Lisa Shi

**Comment by shixinlishixinli** [comment]
i use ' make release' to build recommender images .  i have a lot of images . what is the image which can be written in the recommender-deployment.yaml
<img width="747" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/024838e1-638a-4a2e-9f61-f23a62b3331d">

the docker push is not successful, because i do not have gcloud account .  
Can I use this image to run vpa successfully on the host without using 'Docker Push'?

**Comment by Shubham82** [comment]
Hi @shixinlishixinli 
make release command created images for multiple architectures. you can use  the following command to create specific architecture:  
`ALL_ARCHITECTURES=<architecture name> REGISTRY=<your registry username> TAG=<tag name> make release`

Example:

` ALL_ARCHITECTURES="amd64" REGISTRY=abc TAG=testing make release`

**Comment by Shubham82** [comment]
IMO, After creating the images you can directly use them in the configuration(YAML), or you can normally push in into your repository(docker hub) and then mention it in the configuration(with the repo URL), it will pull the images from there.

**Comment by shixinlishixinli** [comment]
thank you so much for your help. now i can successfully run the modified recommender code
