### ISSUE TITLE
Scaling does not take nodeAffinity into account

### ISSUE THREAD

**Issue by ericln** [kubernetes/autoscaler#595]
We have a few node groups running in our cluster and based on `taints` and `nodeAffinity` to ensure pods can only be scheduled onto certain group of the node. In the configuration of the cluster autoscaler deployment we specified all the AWS ASGs we have in the cluster, however as the pods scale, the one that has `tolerations` and `nodeAffinity` assgined, they do not seem to trigger the ASG to scale up.

**Comment by aleksandra-malinowska** [comment]
Check events for the pod - if it's unschedulable, there should be either a TriggeredScaleUp or NotTriggeredScaleUp event. You can also search Cluster Autoscaler logs for any mention of the pod. This and other suggestions for debugging [can be found in Cluster Autoscaler FAQ](https://github.com/kubernetes/autoscaler/blob/acd172bbe6b3dc7d9c62efebc9ae69f2bf8e90fb/cluster-autoscaler/FAQ.md#how-can-i-check-what-is-going-on-in-ca-). There are many possible reasons for not scaling up, so it's hard to guess what happened without more information.

In general, Cluster Autoscaler should be able to handle taints and nodeAffinity, so if you observe it doesn't, please provide reproduction steps including your pod's and node's configurations (you can get this by running `kubectl describe node <node>`).

**Comment by bhack** [comment]
@aleksandra-malinowska It is working for me, I have a problem only when the ASG is at 0. See also https://github.com/kubernetes/autoscaler/issues/530
