### ISSUE TITLE
vertical-pod-autoscaler-0.14.0 wrong images tags?

### ISSUE THREAD

**Issue by dyferx** [kubernetes/autoscaler#5950]
Hello,

It seems there are wrong images tags (0.13.0 instead of 0.14.0) in VPA deployment yaml files for vertical-pod-autoscaler-0.14.0 release:

Example:
https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.14.0/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml#L23

**Comment by jbartosik** [comment]
[Release instructions](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.14.0/vertical-pod-autoscaler/RELEASE.md#finalize-release) tell us to update the default version before pushing a tag. I don't know why this didn't work as expected.

**Comment by Shubham82** [comment]
This issue resolved by PR #5881

Closing this issue.
