### ISSUE TITLE
Support OCI OKE multiple nodepool configuration

### ISSUE THREAD

**Issue by rmalakar8x8** [kubernetes/autoscaler#5960]
We are trying to deploy autoscale on OCI OKE but as per existing logic, it does not support oci oke node pool configuration at command. 

reference: https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingclusterautoscaler.htm

command section should support the configuration of node pool mentioned below.

            - --nodes=1:5:{{ node pool ocid 1 }}
            - --nodes=1:5:{{ node pool ocid 2 }}

**Which component are you using?**:
Cloud provider : **OCI-OKE**

Which component hosted in this repository is this a feature for?

/charts/cluster-autoscaler/templates/deployment.yaml

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We are trying to deploy autoscale on OCI OKE but as per existing logic, it does not support oci oke node pool configuration at command section of /charts/cluster-autoscaler/templates/deployment.yaml

**Describe the solution you'd like.**:

1. Set a new parameter at values.yaml 
    ociOkeNodePools: []
    
2. Updated the logic for setting nodepools for oci-oke below 83 line
https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-chart-9.29.0/charts/cluster-autoscaler/templates/deployment.yaml#L83

`          {{- if eq .Values.cloudProvider "oci-oke" }}
            {{- if .Values.ociOkeNodePools }}
            {{- range .Values.ociOkeNodePools }}
            - --nodes={{ .minSize }}:{{ .maxSize }}:{{ .name }}
            {{- end }}
            - --balance-similar-node-groups
            {{- end }}
`

**Describe any alternative solutions you've considered.**:

The alternative solution is to support the same configuration of node pool from **extraArgs** which should support the value

nodes: "1:5:{{ node pool ocid 1 }}"
nodes: "1:6:{{ node pool ocid 1 }}"

As of now if we pass a value like this in extraArgs it supplies only last nodepool configuration due to existing logic of separating key and value (reason is ":") 

**Additional context.**:
Let me know how i can raise a PR for the same i am not allowed to do this

**Comment by jlamillan** [comment]
@trungng92

**Comment by Tarasovych** [comment]
Any updates of this? Now it's impossible to add two nodepools because of `extraArgs` is a map

**Comment by trungng92** [comment]
I agree that option #2 is the right solution. We should loop through to allow users to specify multiple lines.
