### ISSUE TITLE
Cluster Autoscaler Patch Releases: July 2023

### ISSUE THREAD

**Issue by BigDarkClown** [kubernetes/autoscaler#5962]
I'm planning to cut the latest round of CA patch releases as per [the schedule](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#patch-releases), on Monday the 24th of July.

I will be cutting releases for 1.24, 1.25, 1.26, and 1.27 release branches. If you have any bug fixes for the versions listed that haven't yet been cherry-picked, please raise them and reference this issue.

Tagging cloud provider owners for visibility:
@andrewsykim
@apricote
@arunmk
@avorima
@BigDarkClown
@cprivitere
@davidjumani
@deitch
@detiber
@displague
@d-mo
@drmorr0
@ellistarn
@elmiko
@enxebre
@feiskyer
@gandhipr
@gjtempleton
@hardikdr
@hello2mao
@jackfrancis
@jayantjain93
@jaypipes
@Jeffwan
@jlamillan
@kevin-wangzefeng
@maciekpytel
@marwanad
@MorrisLaw
@mrajashree
@nilo19
@piepmatz
@RainbowMango
@remyleone
@ringtail
@schegi
@Sh4d1
@shysank
@tallaxes
@tghartland
@towca
@vishalanarase
@v-pap
@x13n
@yaroslava-serdiuk

**Comment by Bryce-Soghigian** [comment]
I have cherry picks for the max-empty-bulk-delete fix I wrote
https://github.com/kubernetes/autoscaler/pull/5965
https://github.com/kubernetes/autoscaler/pull/5966
https://github.com/kubernetes/autoscaler/pull/5967

CC: @x13n, @gandhipr

**Comment by Shubham82** [comment]
Closing this issue as corresponding Patch releases for July are released.

https://github.com/kubernetes/autoscaler/releases?page=2
