### ISSUE TITLE
Prevent scale up to specifix node pools on aks and gke

### ISSUE THREAD

**Issue by eyltl** [kubernetes/autoscaler#5963]
Hey
Using cluster autoscaler
There is any way to suspend scale up operation on a specific node pool?
For example i have a use case , i have 2 node pools
I want to prevent one node pool from scale up
But to continue to scale down as needed

it possible?

**Comment by Bryce-Soghigian** [comment]
Are you using the managed AKS Autoscaler? or are you deploying your own Cluster Autoscaler on AKS? What sort of GKE configuration do you have?

**Comment by Bryce-Soghigian** [comment]
Sorry for the late reply. FOr cluster autoscaler there are a couple of ways to get around scaling up further.

THe first reccomended way I would use to prevent scale up beyond a threshold is to set a --max-count parameter on the aks nodepool api to control the number of nodes we scale up to. Also you can configure certain node pools to not be autoscaling nodepools. So if you just want autoscaler to scale up for one pool, just enable one nodepool. 

What is your usecase? Autoscaler only creates new nodes based on pending pods. Why do you want to suspend scaling operations?

**Comment by eyltl** [comment]
Thanks for your reply 
So the idea is to be able to do a blue green migration for node pools
So for example i have node pool A and node pool B
and i want to move all my workloads from A to B
i can taint all the nodes on A with some taint
And than to rollout restart my apps. Due to the taints on node pool A , apps will be scheduled on node pool B, however autoscaler can still scale up node on node pool A, if the node pools is still manage by autoscaler,
The idea to keep it manage by autoscaler is for the scale down operations but to block it from scale up so pods will move to the new node pool, in eks it possible by suspending process on the autoscaler group configuration,
If i will modify the max node group size to 1 (vmss tags/deployment for gcp) it will do the trick ?( GCP and Azure)
On azure there is possible to add taint via VMSS tags, it possible also for gke?

thanks

**Comment by eyltl** [comment]
Any update on this?
