### ISSUE TITLE
 Failed to list *v1beta1.CronJob: the server could not find the requested resource

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/autoscaler#5972]
k8s version is 1.26.3

metrics server version is 0.6.3

this is the bug of recommender , do you have some suggesstion about how to solve it 

this is the log of recommender 
I0718 12:47:32.582147       1 reflector.go:175] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go:203
I0718 12:47:32.582161       1 reflector.go:211] Listing and watching *v1.Pod from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go:203
I0718 12:47:32.582619       1 reflector.go:175] Starting reflector *v1.Job (10m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137
I0718 12:47:32.582635       1 reflector.go:211] Listing and watching *v1.Job from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137
I0718 12:47:32.682994       1 shared_informer.go:253] caches populated
I0718 12:47:32.683005       1 controller_fetcher.go:142] Initial sync of Job completed
I0718 12:47:32.683166       1 reflector.go:175] Starting reflector *v1beta1.CronJob (10m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137
I0718 12:47:32.683176       1 reflector.go:211] Listing and watching *v1beta1.CronJob from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137
E0718 12:47:32.684199       1 reflector.go:178] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137: Failed to list *v1beta1.CronJob: the server could not find the requested resource
I0718 12:47:34.015940       1 reflector.go:211] Listing and watching *v1beta1.CronJob from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137
E0718 12:47:34.016643       1 reflector.go:178] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137: Failed to list *v1beta1.CronJob: the server could not find the requested resource

**Comment by mastersingh24** [comment]
Looks like you'll need to upgrade the CA to version v0.14.0 or later.

**Comment by jbartosik** [comment]
Cron job v1beta was removed in K8s 1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
Sound's like you'll need to use a newer VPA version: https://github.com/kubernetes/autoscaler/blob/fb1a4c28a3ab95f14ae064039733ae4a933030e1/vertical-pod-autoscaler/README.md#compatibility

**Comment by jbartosik** [comment]
Please reopen if you think this doesn't resolve your issue
