### ISSUE TITLE
i can not change base image in dockerfile

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/autoscaler#5992]
hi 

i want to change the base image of dockerfile(https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Dockerfile).  the gcr.io/distroless/python can be download , while the ubuntu image can not be download . i can use docker pull to download 'gcr.io/distroless/python' and 'ubuntu 20.04' in the host 

FROM gcr.io/distroless/python   is ok
FROM ubuntu:20.04                    is not ok

actually, i want to use 'pip3 install' in dockerfile . do you have any suggestion about how to use 'pip3 install ' in dockerfile of recommender ?

i use proxy in my environment.  docker buildx build is added proxy.(docker buildx build --pull --load --platform linux/amd64 -t shixinlishixinli/vpa-recommender-amd64:testing1 --build-arg http_proxy='http://child-prc.intel.com:913' --build-arg https_proxy='http://child-prc.intel.com:913' --build-arg ARCH=amd64  .)

the is the log report:

lisa@nvbox:~/program/k8s/autoscaler/vertical-pod-autoscaler/pkg/recommender$ sudo  ALL_ARCHITECTURES="amd64" REGISTRY=shixinlishixinli TAG=testing1 make docker-build
[sudo] password for lisa:
docker buildx build --pull --load --platform linux/amd64 -t shixinlishixinli/vpa-recommender-amd64:testing1 --build-arg http_proxy='http://child-prc.intel.com:913' --build-arg https_proxy='http://child-prc.intel.com:913' --build-arg ARCH=amd64  .
[+] Building 119.4s (5/16)
 => [internal] load build definition from Dockerfile                 0.0s
 => => transferring dockerfile: 1.23kB                               0.0s
 => [internal] load .dockerignore                                    0.0s
 => => transferring context: 2B                                      0.0s
 => ERROR [internal] load metadata for docker.io/library/ubuntu:la  59.3s
 => ERROR [1/12] FROM docker.io/library/ubuntu:latest               60.1s
 => => resolve docker.io/library/ubuntu:latest                      60.1s
 => [internal] load build context                                    0.0s
 => => transferring context: 951B                                    0.0s
------
 > [internal] load metadata for docker.io/library/ubuntu:latest:
------
------
 > [1/12] FROM docker.io/library/ubuntu:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://registry.docker-cn.com/v2/library/ubuntu/manifests/latest: Service Unavailable
Makefile:45: recipe for target 'docker-build-amd64' failed
make: *** [docker-build-amd64] Error 1

best
lisa shi

**Comment by Shubham82** [comment]
@shixinlishixinli, if your concern is resolved, can we close this issue?

**Comment by Shubham82** [comment]
Closing this as no response is provided. Please reopen this issue if there is any concern.
