### ISSUE TITLE
Increase unit test coverage for cluster-autoscaler/simulator

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#6]
Current test level is 69. Our target should be above 80% as the code is quite testable.

**Comment by mwielgus** [comment]
Ref: kubernetes/contrib#2191

**Comment by MaciekPytel** [comment]
I'm trying to learn about how simulator works anyway, so I may as well add some tests.

**Comment by MaciekPytel** [comment]
Closing after merging #12. The current coverage is 79.4%, which I think is reasonably close to 80% and there aren't any testable, uncovered functions left in simulator.
