### ISSUE TITLE
Update scale to 0 proposal with allocatable estimation

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#60]
Follow up on: https://github.com/kubernetes/autoscaler/pull/57.

cc: @MaciekPytel @fgrzadkowski

**Comment by bhack** [comment]
For aws is documented as 0.6.1 but it will never be a 0.6.1 release?

**Comment by mwielgus** [comment]
Allocatable estimation added to scale-from-0 in GKE code.
