### ISSUE TITLE
Automated pod resource optimisation

### ISSUE THREAD

**Issue by vivuu1989** [kubernetes/autoscaler#6007]
### What would you like to be added?

Our Developers are developing springboot java application and which are deploying to AKS cluster. We have Helm and Azure pipelines to deploy these apps to the AKS cluster dynamically and the values for the Pod resource speicification are defined in Variablegroups of the ADO pipelines and.

 But we are facing some difficlties to estimate the required resource specification for their each apps,because each apps has different JVM settings and startup behaviour. Since we dont have a proper mechanisam inplace to define the Resource Request and Limit (Cpu and Mem respectively), our clutsers are over committed by the mis usage of these values in ADO pipelines.

So we are trying to introduce some automated mechanism, where a developer can estimate their required memory& cpu request and limit values by passing their JVM arguments or some specific things to be considered for springboot application, then these estimated values can be used in the corresponding Variables groups. below are the some components which are used in jvmSetings. 

So is this possible to achieve in an automated way ? 

Below are the some of the jvmSettings parameters used by the developers

```
-Xmx650m 
-XX:MaxGCPauseMillis=100
-XX:MetaspaceSize=150m
-XX:MaxMetaspaceSize=150m 
-XX:MaxMetaspaceFreeRatio=100
-XX:CompressedClassSpaceSize=25m
-XX:InitialCodeCacheSize=100m
-XX:ReservedCodeCacheSize=100m
-XX:MaxDirectMemorySize=100m
-XX:+DisableExplicitGC
```

### Why is this needed?

This is needed to define the actual resource specifications than over committing any unused resource

**Comment by vivuu1989** [comment]
> This is something I'm interested in. However, JVM recommendations aren't currently possible via the Recommender, at least for memory, because the JVM reserves memory on startup and allocates its heaps/pools internally, meaning metrics from the container itself are useless.
> 
> What we need is the ability to define a custom Prometheus query for memory usage, for example `jvm_memory_used_bytes` assuming you're exporting JVM metrics to Prom' using micrometer or something.
> 
> In addition (but out of the scope of this project) the following JVM parameters are usually recommended for containerized Java, though may differ slightly based on the size of your application: `-XX:+UseParallelGC -XX:MaxRAMPercentage=75 -XX:ActiveProcessorCount=2`

Not clear about how can we estimate the pod resources properties by this

**Comment by jbartosik** [comment]
If I understand correctly this is a feature request for VPA to support memory recommendations for Java. Like @vivuu1989 wrote this isn't an easy task. We currently lack capacity to implement the support.

**Comment by voelzmo** [comment]
Thanks @des1redState for getting back to this! Out of curiosity: you ended up scaling based on an export of `jvm_memory_used_bytes` and that is working fine for you? How did you compute the necessary container resources based on this value? Thanks!
