### ISSUE TITLE
Failed to scale up: failed to build node infos for node groups: Wrong id: expected format aws:///&lt;zone&gt;/&lt;name&gt;, got 

### ISSUE THREAD

**Issue by rongshen** [kubernetes/autoscaler#604]
Hello,

I'm looking for some help for CA. Forgive me if I did not post it at the right place.
My set up is the following:
1. Existing k8s clusters are all running on bare metal
2. Cluster is managed by kubeadm
3. kubeadm/kubectl/kubelet version: 1.9

What I want to achieve is an elastic k8s cluster with auto scale up and down on AWS ec2 instances.
I have done the following:
1. created an AMI with all required k8s node configs
2. created IAM role with all auto scaling permissions
3. created an AWS ec2 instance with the IAM role attached, and added it to existing cluster with kubeadm
4. Deployed CA on that ec2 node

My CA yaml file is like this:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - image: k8s.gcr.io/cluster-autoscaler:v1.1.0
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --node=1:5:k8s-asg
          env:
            - name: AWS_REGION
              value: us-west-1
          imagePullPolicy: "Always"
      nodeSelector:
          dedicated: test
```
I did not mount on ca-certificate.crt because my ec2 instances does not have it. It is a Centos based instance.

Now I'm seeing this error in log:
```
 W0202 01:21:48.983111       1 clusterstate.go:514] Failed to get nodegroup for a.k8s: Wrong id: expected format aws:///&lt;zone&gt;/&lt;name&gt;, got 
W0202 01:21:48.983116       1 clusterstate.go:514] Failed to get nodegroup for b.k8s: Wrong id: expected format aws:///&lt;zone&gt;/&lt;name&gt;, got 
I0202 01:21:48.983183       1 static_autoscaler.go:230] Filtering out schedulables
I0202 01:21:48.983848       1 static_autoscaler.go:240] No schedulable pods
I0202 01:21:48.983861       1 scale_up.go:54] Pod default/rong-test-j7p4q is unschedulable
I0202 01:21:48.983865       1 scale_up.go:54] Pod default/rong-test-hvrl5 is unschedulable
I0202 01:21:48.983868       1 scale_up.go:54] Pod default/rong-test-gjmr6 is unschedulable
E0202 01:21:48.983881       1 static_autoscaler.go:262] Failed to scale up: failed to build node infos for node groups: Wrong id: expected format aws:///&lt;zone&gt;/&lt;name&gt;, got 
```

Can anyone give me some tips on how I can make it work?

Thanks a lot

**Comment by aleksandra-malinowska** [comment]
cc @mumoshu

**Comment by aleksandra-malinowska** [comment]
Can you check node spec of your nodes for ProviderId? You can get it by running `kubectl describe node <node>`. These errors look as if this field is missing. I think kubelet is supposed to set it, so if it's missing, I'd look at kubelet logs of affected nodes.

**Comment by rongshen** [comment]
@aleksandra-malinowska There is no ProviderId in my k8s nodes. I'm wondering if it is because my existing cluster is made of bare metal. Could you tell me more on how to examine kubelet logs? Thank you!
