### ISSUE TITLE
VPA recommender is restarting continuously

### ISSUE THREAD

**Issue by yaakov-berkovitch** [kubernetes/autoscaler#6049]
**Which component are you using?**:
vertical-pod-autoscaler,

**What version of the component are you using?**:
registry.k8s.io/autoscaling/vpa-recommender:0.13.0
helm chart: https://artifacthub.io/packages/helm/fairwinds-stable/vpa v2.2.1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
AWS EKS

**What did you expect to happen?**:

vpa-recommender to be stable without restarts
**What happened instead?**:

For a period of about 10 days we see more than 2500 POD restarts

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Not sure but reason could be that the VPA version we are using doesn't support 1.27 ?!
I have also another question: Kubernetes 1.27 introduced in place memory and CPU update (https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) - Do the VPA already supports this new feature ?

**Comment by jbartosik** [comment]
I don't know why VPA is restarting. I'd start by checking it's logs.

We have an open issue #4016 to support in place updates, there's [enhancement proposal](https://github.com/kubernetes/autoscaler/blob/57f2814267399e0900a70d567a7813089a3cfa5b/vertical-pod-autoscaler/enhancements/4016-in-place-updates-support/README.md?plain=1#L1).

**Comment by yaakov-berkovitch** [comment]
Not so much in the logs - But the readiness and liveness failed with error: 
`Readiness probe failed: HTTP probe failed with statuscode: 500
`

**Comment by Staggerlee011** [comment]
Hi, we have the same issue, tried upping resource limit / requests to 

```
recommender:
  resources:
    limits:
      cpu: 300m # 200m default
      memory: 2000Mi # 1000Mi default
    requests:
      cpu: 100m # 50m default
      memory: 1000Mi # 500Mi default
```
but soon as it re-deployed it started to restart 

event logs: 

```
LAST SEEN   TYPE      REASON                   OBJECT                                 MESSAGE
38m         Warning   Unhealthy                pod/vpa-recommender-6fd945b759-rtn9c   Liveness probe failed: HTTP probe failed with statuscode: 500
44m         Warning   Unhealthy                pod/vpa-recommender-6fd945b759-rtn9c   Readiness probe failed: HTTP probe failed with statuscode: 500
95s         Warning   Unhealthy                pod/vpa-recommender-9486d5997-cc5gq    Liveness probe failed: HTTP probe failed with statuscode: 500
7m5s        Warning   Unhealthy                pod/vpa-recommender-9486d5997-cc5gq    Readiness probe failed: HTTP probe failed with statuscode: 500
```

**Comment by juwatanabe** [comment]
Also seeing the same issue:

Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7-eks-4f4795d

**Comment by liorco300** [comment]
same here:

Client Version: v1.25.10
Kustomize Version: v4.5.7
Server Version: v1.25.10-gke.2700

**Comment by omri-shilton** [comment]
same here:

vpa chart version: 1.7.5
app version: 0.13.0
server version: eks v1.27
