### ISSUE TITLE
unschedulablePodWithGpuTimeBuffer configuration

### ISSUE THREAD

**Issue by maxpain** [kubernetes/autoscaler#6087]
Hello. How do you configure this variable?

https://github.com/kubernetes/autoscaler/blob/57f2814267399e0900a70d567a7813089a3cfa5b/cluster-autoscaler/core/static_autoscaler.go#L69

NVIDIA L4 spot GPUs in GCE are cheap for our use case, so we need to scale up immediately.

**Comment by vadasambar** [comment]
@maxpain I don't think the variable is configurable right now. We might need to expose it via flag if you want to configure it.

**Comment by aiden-von** [comment]
May I handle this issue? please assign to me. I'll create PR.

**Comment by vadasambar** [comment]
@aiden-von I don't think anyone else is working on this. You can assign the issue to yourself with `/assign @aiden-von`

**Comment by Shubham82** [comment]
@maxpain can you confirm if this issue is resolved by PR #6235?
If yes, so we can close this issue.

**Comment by maxpain** [comment]
@Shubham82 Yes! Thanks you.

**Comment by Shubham82** [comment]
@maxpain Thanks for the confirmation.

**Comment by Shubham82** [comment]
closing this issue, as it is resolved by PR #6235
