### ISSUE TITLE
VPA supported versions

### ISSUE THREAD

**Issue by shazib-summar** [kubernetes/autoscaler#6097]
Just a general question. What are the supported versions for Vertical Pod Autoscaler in production envs? 

Also what is the support policy like?

Thanks ❤️

**Comment by shazib-summar** [comment]
Bump please

**Comment by Shubham82** [comment]
Here is the table of compatibility of the VPA version with the k8s version:
https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#compatibility

**Comment by Shubham82** [comment]
cc @jbartosik @voelzmo

**Comment by shazib-summar** [comment]
Thanks for replying @Shubham82 

> Here is the table of compatibility of the VPA version with the k8s version:

I'm not looking for the compatibility information but the support policy. What I mean is what/how-many versions of VPA are supported at any time. By supported I mean if a bug is found in the latest version A.B, how far behind will it be backported. Would it be A.B-1 or A.B-2 or something else entirely?

For example Argo Events has a N-1 support policy. ref: https://argoproj.github.io/argo-events/releases/

> We maintain release branches for the most recent two minor releases.

**Comment by Shubham82** [comment]
@shazib-summar IIRC, For this there is already a discussion going on, Here is the issue: #5759

**Comment by Shubham82** [comment]
closing this issue, as the same issue #5759 is opened.
/close
