### ISSUE TITLE
Error: Failed to get servers for hcloud - Cluster Autoscaler with Hetzner

### ISSUE THREAD

**Issue by dominic-p** [kubernetes/autoscaler#6099]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 1.28.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.1", GitCommit:"8dc49c4b984b897d423aab4971090e1879eb4f23", GitTreeState:"clean", BuildDate:"2023-08-24T11:16:30Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: Heztner Cloud

**What did you expect to happen?**:

Cluster autoscaler should be able to get the list of servers from the hcloud API.

**What happened instead?**:

This error shows up on a regular basis in the logs.

```
E0910 23:27:16.397736       1 hetzner_node_group.go:512] failed to set node pool draining-node-pool size, using delta 0 error: failed to get servers for hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": unexpected EOF
```

**How to reproduce it (as minimally and precisely as possible)**:

I'm not 100% sure what a minimal reproduction would look like. My setup is basically:

1. Install cluster with kubeadm on single control plane node
2. Install cluster-autoscaler using a yaml manifest like [the example](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.28.0/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml)
3. Watch the logs for the cluster-autoscaler pod

**Anything else we need to know?**:

I have confirmed that I can communicate with the hcloud API from an [ephemeral container](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container) attached to the cluster-autoscaler pod. I can curl the same URL mentioned in the logs from that container and I get back a nicely formatted JSON document with no errors being reported by curl.

```
curl -H "Authorization: Bearer API-KEY-HERE" "https://api.hetzner.cloud/v1/servers?page=1&per_page=50"
{
  "servers": [
    {
      "id": server-id,
      "name": "server-name"
...
```

I'm using CRI-O as my CRI which shouldn't be relevant, but you never know. I'm also seeing an issue where the autoscaler adds a second worker node unnecessarily, but I think that's more to do with my CNI config. The unexpected EOF error is the same on all of my test clusters.

Lastly, I'll say that the errors doesn't seem to significantly impact the performance of the autoscaler (other than maybe the excessive scale up issue I just mentioned). Despite the error, new nodes are added and empty nodes are removed.

**Comment by apricote** [comment]
This seems to be an intermittent network failure, perhaps the API was down for some time. Is still still regularly happening for you?

/area provider/hetzner

**Comment by dominic-p** [comment]
I still need to reproduce this to confirm if it was an intermittent issue or not. I've been occupied with other projects, but I'm hoping to have some time to work on this in the next few weeks. I'll post back what I find.

**Comment by ByteAlex** [comment]
Adding that I have a similar issue. Just set up a cluster-autoscaler on a fresh setup with calico, hetzner ccm, hetzner csi and prometheus, nothing else is there and I'm running kubernetes v1.29.1, with the autoscaler on v1.29.0.

`E0207 21:47:02.805620       1 hetzner_node_group.go:556] failed to set node pool draining-node-pool size, using delta 0 error: failed to get servers for hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": unexpected EOF
W0207 21:47:02.805704       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API
I0207 21:47:03.958794       1 hetzner_node_group.go:559] Set node group worker size from 0 to 0, expected delta 0
I0207 21:47:33.968948       1 hetzner_node_group.go:559] Set node group draining-node-pool size from 0 to 0, expected delta 0
I0207 21:47:33.968977       1 hetzner_node_group.go:559] Set node group worker size from 0 to 0, expected delta 0
W0207 21:48:03.979541       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API
E0207 21:48:04.054193       1 hetzner_node_group.go:556] failed to set node pool draining-node-pool size, using delta 0 error: failed to get servers for hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": unexpected EOF
W0207 21:48:04.054286       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API
I0207 21:48:05.114700       1 hetzner_node_group.go:559] Set node group worker size from 0 to 0, expected delta 0
I0207 21:48:35.125604       1 hetzner_node_group.go:559] Set node group draining-node-pool size from 0 to 0, expected delta 0
I0207 21:48:35.125639       1 hetzner_node_group.go:559] Set node group worker size from 0 to 0, expected delta 0
I0207 21:48:55.755516       1 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0207 21:48:55.755569       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 21.551µs
W0207 21:49:05.135992       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API
E0207 21:49:05.209691       1 hetzner_node_group.go:556] failed to set node pool draining-node-pool size, using delta 0 error: failed to get servers for hcloud: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": unexpected EOF
`

**Comment by apricote** [comment]
For the record, I am able to reproduce with this code, on the third iteration (so connection is open for 2 minutes and idle for 1):

```
package main

import (
	"context"
	"os"
	"time"

	"github.com/hetznercloud/hcloud-go/v2/hcloud"
)

func main() {
	client := hcloud.NewClient(
		hcloud.WithToken(os.Getenv("HCLOUD_TOKEN")),
		hcloud.WithDebugWriter(os.Stdout),
	)

	for {
		_, err := client.Server.All(context.Background())
		if err != nil {
			panic(err)
		}

		time.Sleep(1 * time.Minute)
	}
}
```

This is therefore unrelated to `cluster-autoscaler` and the CNI used. Will investigate further.

**Comment by apricote** [comment]
We have updated the configuration of `api.hetzner.cloud` and the problem should not show up anymore.

Feel free to comment here if you still see this issue and I will reopen the issue/investigate some more. Right now I am unable to reproduce it anymore.

/close

## Details

The proxy behind `api.hetzner.cloud` was closing TCP connections after 60 seconds. If the client sent a request right before receiving the connection close packet it failed with `unexpected EOF`. The Go http(2) client does not handle this gracefully for http2 connections.

We have now updated the configuration to send a http2 `GOAWAY` frame before closing the TCP connection. This is handled correctly by the Go http client. It will make a new connection and resend the request.
