### ISSUE TITLE
CA: Hetzner cloud-init example may need to be updated for new community packages

### ISSUE THREAD

**Issue by dominic-p** [kubernetes/autoscaler#6106]
**Which component are you using?**: Cluster Autoscaler with Hetzner

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Ever since updating to the [new community hosted APT repo](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/), I've been experience network issues with my clusters. It appears that the issue has do with the `KUBELET_EXTRA_ARGS` env variable (see [this comment](https://github.com/kubernetes/release/issues/3219#issuecomment-1717015276)). I was previously configuring this variable as shown in the example [cloud-init script here](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.28.0/cluster-autoscaler/cloudprovider/hetzner/examples/cloud-init.txt#L19-L21).

**Describe the solution you'd like.**:

I'm not exactly sure why the CA needs this env variable set for Hetzner. In my testing, it didn't seem to be affected like the CCM was. But, I thought I would bring up the potential issue anyway.

I'm currently working around the problem by overwriting the new file that the deb package introduces, but that's not exactly the most elegant solution.

**Comment by apricote** [comment]
> I'm not exactly sure why the CA needs this env variable set for Hetzner. In my testing, it didn't seem to be affected like the CCM was. But, I thought I would bring up the potential issue anyway.

I dont think this variable is specifically required for cluster-autoscaler, more that it makes sense to always deploy hcloud-cloud-controller-manager in tandem with CA.

The cloud-init example is really outdated, if anyone wants to update it I am more than happy to review/help.

**Comment by dominic-p** [comment]
I don't think this one is stale. I haven't had a chance to look into updating the example cloud-init myself, but it would be helpful for future users.

**Comment by apricote** [comment]
/remove-lifecycle stale

If anyone wants to work on this, we made these changes to the hcloud-cloud-controller-manager documentation regarding `KUBELET_EXTRA_ARGS`: https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/607/files

**Comment by dominic-p** [comment]
I still think a doc update might be appropriate here, but I haven't had a chance to tackle it myself.
