### ISSUE TITLE
CA: Allow users to define their custom taints

### ISSUE THREAD

**Issue by LambdaHJ** [kubernetes/autoscaler#6112]
**Which component are you using?**:
CA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Kubernetes has its own resource pressure-related taints that prevent pod scheduling on nodes, but they do not affect the functioning of the CA.

We should provide a mechanism to allow users to use custom taints to manage other resource pressures on the node, such as CPU, bandwidth, etc.

**Describe the solution you'd like.**:

I would like to define some taints, these taints will not be used as templates for creating new nodes，at the same time, these taints will not cause the CA to judge the node as not ready.

**Describe any alternative solutions you've considered.**:

**Additional context.**:

The **--ignore-taints** flag will be considered "not ready" by the CA, just like it is implemented in the **FilterOutNodesWithIgnoredTaints** function.

**Comment by guopeng0** [comment]
@LambdaHJ L
