### ISSUE TITLE
README for AWS still mentions autoscaling:DescribeTags

### ISSUE THREAD

**Issue by rittneje** [kubernetes/autoscaler#6129]
In the release notes for v1.25.0, it says "DescribeAutoScalingGroups [now supports](https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-auto-scaling-groups-using-tags/) directly including tag filers, which results in less API calls to AWS. Users of the AWS Cloudprovider may want to update their IAM roles to remove the DescribeTags action as this is no longer used".

However, the [README](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#full-cluster-autoscaler-features-policy-recommended) still includes `autoscaling:DescribeTags`.

Is this an oversight? Or is DescribeTags still needed?

**Comment by gjtempleton** [comment]
You're correct, just an oversight from #4424's cleanup
