### ISSUE TITLE
README for AWS is inconsistent about autoscaling:DescribeScalingActivities

### ISSUE THREAD

**Issue by rittneje** [kubernetes/autoscaler#6138]
In the [README](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.25/cluster-autoscaler/cloudprovider/aws/README.md) for v1.25, it mentions `autoscaling:DescribeScalingActivities` under "Minimal IAM Permissions Policy" but not under "Full Cluster Autoscaler Features Policy (Recommended)". This does not make sense.

If this action is actually needed, it should be included in the full policy. If it isn't, it should be removed from the minimal policy.

**Comment by Shubham82** [comment]
@rittneje `autoscaling:DescribeScalingActivities` was added under Full Cluster Autoscaler Features Policy (Recommended) in CA1.26 by PR #5373.

So IMO if we backport this, it can only be done in CA1.24 and CA1.25

**Comment by Shubham82** [comment]
CC @drmorr0 your thoughts on this?

**Comment by drmorr0** [comment]
Seems fine to backport to me.

**Comment by Shubham82** [comment]
> Seems fine to backport to me.

Thanks @drmorr0 
I will raise PR for it.

**Comment by Shubham82** [comment]
Raised the following PR to fix this issue:
For CA 1.25 #6182
For CA 1.24 #6181

**Comment by Shubham82** [comment]
closing this issue as above both PRs are merged.
