### ISSUE TITLE
[VPA] sharedIndexInformer started twice

### ISSUE THREAD

**Issue by mikutas** [kubernetes/autoscaler#6156]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 0.14.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

AWS EKS / k3d local cluster

**What did you expect to happen?**:

sharedIndexInformer not started more than once

**What happened instead?**:

[Seven sharedIndexInformer](https://github.com/kubernetes/autoscaler/blob/cc3283c917c58666c4747f096e43cd23874730ea/vertical-pod-autoscaler/pkg/target/fetcher.go#L83-L89) are started twice and following log are output seven times.

`The sharedIndexInformer has started, run more than once is not allowed`

**How to reproduce it (as minimally and precisely as possible)**:

just start vpa-admission-controller

**Anything else we need to know?**:

It is similar to: https://github.com/kubernetes-sigs/metrics-server/issues/1002

**Comment by jbartosik** [comment]
@laoj2 please take a look
