### ISSUE TITLE
Priority expander for OCI Cluster autoscaler does not scale secondary nodepool when there are capacity issues

### ISSUE THREAD

**Issue by bettaps** [kubernetes/autoscaler#6168]
**Which component are you using?**: Cluster autoscaler: 1.28.0

**What version of the component are you using?**: 1.28.0

Component version: 1.28.0

**What k8s version are you using (`kubectl version`)?**: 1.27.2

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: Oracle Cloud (OCI)

**What did you expect to happen?**: When using priority expander with two different nodepools , the one with lesser priority has to scale up when the higher priority nodepool has 'Out of Host Capacity' errors(Cloud side server capacity issues) .

**What happened instead?**: Lower priority nodepool does not scale up.

**How to reproduce it (as minimally and precisely as possible)**: Create two nodepools with different instance types in OKE cluster in me-jeddah-1 cluster. Configure cluster-autoscaler with the two nodepools and also with priority expander where one nodepool has higher priority than the other. Stress test by deploying an application with a huge number of replicase to scale up the nodepools. When there are capacity based issues on the Cloud whoch causes higher priority nodepool to not scale anymore, second nodepool should start scaling up.

**Anything else we need to know?**: No

**Comment by bettaps** [comment]
Another observation i could add here is, i can see the following in the logs:
I1003 12:11:06.590688       1 klogx.go:87] Pod default/awscli-trigger-autoscaling-f6d7b9f79-8hk66 can be moved to template-node-for-ocid1.nodepool.oc1.me-jeddah-1.abc..-7014040076515837416-upcoming-12
I1003 12:11:06.590759       1 klogx.go:87] Pod default/awscli-trigger-autoscaling-f6d7b9f79-8z7jd can be moved to template-node-for-ocid1.nodepool.oc1.me-jeddah-1.pqr..-7014040076515837416-upcoming-1
I1003 12:11:06.590833       1 klogx.go:87] Pod default/busybox-trigger-autoscaling-d674667cd-8lfwk can be moved to template-node-for-ocid1.nodepool.oc1.me-jeddah-1.cde..-7014040076515837416-upcoming-1

Which means the stuck nodes (ones with the Out of host capacity) errors are tagged as upcoming. Is there anyway to decrease the timeout for the upcoming nodes ? Meaning if they havent come up in 5 mins, trigger another node from a different node pool to scale up. Is there such a feature ?

**Comment by jasseeeem** [comment]
Hey
Did you find any way to fix this?

**Comment by bettaps** [comment]
No not yet @jasseeeem

**Comment by jasseeeem** [comment]
Did you try changing `--max-node-provision-time` under cluster autoscaler?

**Comment by bettaps** [comment]
This issue got resolved after setting environment variable DECREASE_TARGET_CHECK_VIA_COMPUTE=true. This isnt mentioned anywhere in the documentation, would help if it is. 
--max-node-provision-time doesn't help the original issue but we did tweak it in order to reduce scale up time. Thanks @jasseeeem

**Comment by jasseeeem** [comment]
Hey @bettaps. Thanks for the reply.
How did you arrive at this solution? I wanted to confirm what this flag actually does.

**Comment by robo-cap** [comment]
@bettaps, can you confirm what were the parameters you used for the cluster-autoscaler?

In my case I have the nodepool failing to scale up because of OutOfHostCapacity issues in BackOff, and the cluster autoscaler not using the secondary nodepool.

I've configured `--max-node-provision-time=7m` but without success.

**Comment by atiasadir** [comment]
> This issue got resolved after setting environment variable DECREASE_TARGET_CHECK_VIA_COMPUTE=true. This isnt mentioned anywhere in the documentation, would help if it is. --max-node-provision-time doesn't help the original issue but we did tweak it in order to reduce scale up time. Thanks @jasseeeem

Can you elaborate more about this flag ?
"DECREASE_TARGET_CHECK_VIA_COMPUTE"
