### ISSUE TITLE
Release Cluster Autoscaler 1.2 rc

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes/autoscaler#618]
Looks like there have been big changes to the AWS provider (e.g. https://github.com/kubernetes/autoscaler/pull/462) and I would like to check whether the new code resolves https://github.com/kubernetes/autoscaler/issues/252#issuecomment-345611287

Would there be a chance to release a 1.2 RC including those changes?

//cc @mwielgus

**Comment by aleksandra-malinowska** [comment]
Looks like the situation is similar with Azure changes #644

**Comment by feiskyer** [comment]
> Looks like the situation is similar with Azure changes #644

+1 for a new rc release.

**Comment by negz** [comment]
Agreed - we've been running a build of 1.1.0 that includes https://github.com/kubernetes/autoscaler/pull/462 for months in production. I'd love to be running something more like an official release.

**Comment by dbluxo** [comment]
+1 for a new rc release.

**Comment by johanneswuerbach** [comment]
Closing as there is a 1.2 beta now https://github.com/kubernetes/kubernetes/pull/61359
