### ISSUE TITLE
Azure: "AKS" vmType no longer works

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes/autoscaler#6190]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.27.2

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"8b6cfe2c7c54ae110e0c2dbcc52b468bc08bf5f6", GitTreeState:"clean", BuildDate:"2023-07-28T22:18:46Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Azure AKS

**What did you expect to happen?**:

I expect to be able to install the cluster-autoscaler runtime w/ a vmType configuration of "AKS" on an AKS cluster

**What happened instead?**:

Configured node pools are not identified for proper scaling

**How to reproduce it (as minimally and precisely as possible)**:

```
$ helm install cluster-autoscaler cluster-autoscaler --repo https://kubernetes.github.io/autoscaler --set cloudProvider=azure --set autoscalingGroups[0].name=<name of pool>,autoscalingGroups[0].maxSize=100,autoscalingGroups[0].minSize=1 --set azureClientID=$TEST_AZURE_SP_ID --set azureClientSecret=$TEST_AZURE_SP_PW --set azureSubscriptionID=$TEST_AZURE_SUB_ID --set azureTenantID=$TEST_AZURE_TENANT_ID --set azureResourceGroup=<name of resource group> --set azureNodeResourceGroup=<name of node resource group> --set azureVMType=AKS --set azureClusterName=<name of AKS cluster>
```

**Anything else we need to know?**:

**Comment by jackfrancis** [comment]
Here are the relevant log messages that indicate that the cluster-autoscaler runtime is not able to properly bootstrap itself for node pools w/ the "AKS" vmType:

```
I1011 23:50:44.395284       1 azure_cache.go:329] FindForInstance: starts, ref: azure:///subscriptions/<redacted>/resourceGroups/mc_francis-aks-test_francis-aks-test_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool2-26139306-vmss/virtualMachines/191
...
I1011 23:50:44.395344       1 azure_cache.go:369] FindForInstance: Couldn't find node group of instance {"azure:///subscriptions/<redacted>/resourceGroups/mc_francis-aks-test_francis-aks-test_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool2-26139306-vmss/virtualMachines/191"}
...
W1011 23:50:44.904213       1 clusterstate.go:647] Readiness for node group nodepool2 not found
W1011 23:50:44.904297       1 static_autoscaler.go:921] Couldn't find template for node group nodepool2
...
W1011 23:50:44.905331       1 clusterstate.go:397] Failed to find readiness information for nodepool2
W1011 23:50:44.905359       1 clusterstate.go:459] Failed to find readiness information for nodepool2
W1011 23:50:44.905363       1 clusterstate.go:397] Failed to find readiness information for nodepool2
```

**Comment by jackfrancis** [comment]
@gandhipr let me know if there's anything else we can document as part of proving that this doesn't work

Also let me know if my testing is incorrect.

Thanks!

**Comment by gandhipr** [comment]
This look good to me.
This type is historic and hence no longer works. We can go ahead and remove it. However, I am unaware if someone is using this. As it is not working, I don't expect anyone using this.

**Comment by jackfrancis** [comment]
/hold

while I work on a possible fix as an alternative
