### ISSUE TITLE
Cluster autoscaling with kubeadm

### ISSUE THREAD

**Issue by KetulRadadiya** [kubernetes/autoscaler#6203]
**Which component are you using?**:

Cluster autoscaler is deployed using helm chart:
Chart version : [9.29.3](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-chart-9.29.3/charts/cluster-autoscaler)

**What version of the component are you using?**:

CA image details:
```
image:
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  tag: v1.23.0
```

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Deployed K8S cluster on AWS EC2 instance using Kubeadm.

**What did you expect to happen?**:

Expected behavior is, scale down worker node only when the Job (pod) deployed on that node gets status Completed. Job may take time 2-60 minutes to complete.

**What happened instead?**:

The problem is after 10-15 minutes of the worker node joining event, Cluster autoscaler somehow triggers the scale down event every time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create k8s cluster with the help of kubeadm v1.27.6.
2. Deploy cluster-autoscaler using helm chart cluster-autoscaler-9.29.3 and custom values like below.
```
autoDiscovery:
  clusterName: kubernetes-admin@kubernetes

  # autoDiscovery.tags -- ASG tags to match, run through `tpl`.
  tags:
  - k8s.io/cluster-autoscaler/enabled
  - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}

awsRegion: ap-south-1

cloudProvider: aws

deployment:
  # deployment.annotations -- Annotations to add to the Deployment object.
  annotations: 
    cluster-autoscaler.kubernetes.io/enable-ds-eviction: "false"

extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  scale-down-unneeded-time: 60m
  scale-down-utilization-threshold: "0"
  cores-total: "0:40" 
  memory-total: "0:160" 
  skip-nodes-with-local-storage: false
  cordon-node-before-terminating: true


# fullnameOverride -- String to fully override `cluster-autoscaler.fullname` template.
fullnameOverride: "cluster-autoscaler"

image:
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  tag: v1.23.0
  pullPolicy: IfNotPresent


rbac:
  # rbac.create -- If `true`, create and use RBAC resources.
  create: true
  pspEnabled: false
  clusterScoped: true
  serviceAccount:
    # rbac.serviceAccount.annotations -- Additional Service Account annotations.
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::5024xxx82893:role/K8SAccessRole
    # rbac.serviceAccount.create -- If `true` and `rbac.create` is also true, a Service Account will be created.
    create: true
    # rbac.serviceAccount.name -- The name of the ServiceAccount to use. If not set and create is `true`, a name is generated using the fullname template.
    name: ""
    # rbac.serviceAccount.automountServiceAccountToken -- Automount API credentials for a Service Account.
    automountServiceAccountToken: true

# replicaCount -- Desired number of pods
replicaCount: 1
```
3. Create a job that required high resources to utilize (EC2) and eventually CA spin up new worker node to schedule that job pod.
```
resources:
  limits:
    cpu: 3500m,
    memory: 14500Mi
  requests:
    cpu: "2",
    memory: 13000Mi
```
4. New Worker node will be created and join the k8s cluster using [User data script](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html). 

**Anything else we need to know?**:

CA Scales up node just works fine as expected. But it also scales down in-use worker node even there is pod deployed on it still in running phase and utilizing the resource.
Logs of cluster autoscaler pod during scale down trigger events.
```
I1018 10:38:23.032232       1 static_autoscaler.go:230] Starting main loop
W1018 10:38:23.032452       1 aws_cloud_provider.go:103] Node ip-172-20-3-75 has no providerId
W1018 10:38:23.032465       1 aws_cloud_provider.go:103] Node ip-172-20-35-108 has no providerId
W1018 10:38:23.032477       1 aws_cloud_provider.go:103] Node ip-172-20-43-69 has no providerId
I1018 10:38:23.032483       1 aws_manager.go:313] Found multiple availability zones for ASG "k8s-autoscaling-group"; using ap-south-1c for failure-domain.beta.kubernetes.io/zone label
W1018 10:38:23.032750       1 aws_cloud_provider.go:103] Node ip-172-20-3-75 has no providerId
W1018 10:38:23.032761       1 aws_cloud_provider.go:103] Node ip-172-20-35-108 has no providerId
W1018 10:38:23.032767       1 aws_cloud_provider.go:103] Node ip-172-20-43-69 has no providerId
I1018 10:38:23.032791       1 clusterstate.go:602] Found longUnregistered Nodes [aws:///ap-south-1c/i-0c6cd7475aecf5xyz aws:///ap-south-1a/i-01ac1861a98b46abc]
I1018 10:38:23.032826       1 static_autoscaler.go:334] 2 unregistered nodes present
I1018 10:38:23.032832       1 static_autoscaler.go:610] Removing unregistered node aws:///ap-south-1a/i-01ac1861a98b46abc
I1018 10:38:23.282289       1 auto_scaling_groups.go:304] Terminating EC2 instance: i-01ac1861a98b46abc
I1018 10:38:23.282306       1 aws_manager.go:294] DeleteInstances was called: scheduling an ASG list refresh for next main loop evaluation
I1018 10:38:23.282440       1 static_autoscaler.go:610] Removing unregistered node aws:///ap-south-1c/i-0c6cd7475aecf5xyz
I1018 10:38:23.282504       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"e81a344d-c589-4f6e-a10e-0cdfe4d6b994", APIVersion:"v1", ResourceVersion:"2082846", FieldPath:""}): type: 'Normal' reason: 'DeleteUnregistered' Removed unregistered node aws:///ap-south-1a/i-01ac1861a98b46abc
I1018 10:38:23.441849       1 auto_scaling_groups.go:304] Terminating EC2 instance: i-0c6cd7475aecf5xyz
I1018 10:38:23.441866       1 aws_manager.go:294] DeleteInstances was called: scheduling an ASG list refresh for next main loop evaluation
I1018 10:38:23.441898       1 static_autoscaler.go:342] Some unregistered nodes were removed, skipping iteration
I1018 10:38:23.442013       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"e81a344d-c589-4f6e-a10e-0cdfe4d6b994", APIVersion:"v1", ResourceVersion:"2082846", FieldPath:""}): type: 'Normal' reason: 'DeleteUnregistered' Removed unregistered node aws:///ap-south-1c/i-0c6cd7475aecf5xyz
```

Event detail in "AWS ASG > Activity > Activity history" we can see in image below.
![image](https://github.com/kubernetes/autoscaler/assets/46047598/1efe82b4-035f-44b4-9e30-2cd2c13eeb67)

**Comment by 793653518** [comment]
I would like to ask how it was resolved, and I have encountered the same situation. Thank you

**Comment by KetulRadadiya** [comment]
@793653518 When a new worker node joins the k8s cluster it comes without a provider ID. As we can see in the logs CA counts it as the **longUnregistered Nodes**. And it takes around 10 min to scale down. So I just added an initContainer with k8s-awsCli image definition (to get details of the worker node from aws and manage the k8s node) in the job pod to patch the node and add providerID.
