### ISSUE TITLE
CAS FAQ - What types of pods can prevent CA from removing a node? - pods with a hostPort configuration

### ISSUE THREAD

**Issue by axelgMS** [kubernetes/autoscaler#6209]
Suggestion for the Cluster Autoscaler FAQ document - in the section "[What types of pods can prevent CA from removing a node?]"

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

Looks like there's also this scenario that can prevent CAS from scaling down. It's been especially observed with Calico-typha.

    1- Calico-typha will use a hostPort configuration to listen a port on host by design. This means only max 1 pod of calico-typha can exist on the same node.
    2- Calico-typha is a deployment, which has a “auto-scale” configuration from the tigera operator to set its replica count according to node count.
    3- When scaling down, cluster-autoscaler will try to find another node that can schedule the pod, however it will be blocked due to (1), as every other node also have typha scheduled.

So I'd suggest adding this in the section:

* Pods with a hostPort configuration - causing the scheduler to fit only one of those pods per node. Scale-down might not work as the existing nodes will already have a pod on them and can't schedule the new one.

**Comment by lualvare** [comment]
I have been facing the same issue with the exact configuration where CAS is not working properly since calico-typha deployment is using hosPort configuration, this prevents the POD to be scheduled into another node since the PORT is already used.

<img width="274" alt="image" src="https://github.com/kubernetes/autoscaler/assets/25044818/451d42be-b88f-41ce-8e42-c3237f1cf2bb">


Please update the FAQ as required.

Thanks.

**Comment by Shubham82** [comment]
@lualvare the PR is closed due to a CLA issue, which was not signed.
If you are interested, you can open a PR for this (what you want to update in the FAQ).

Thanks!

**Comment by Shubham82** [comment]
The PR to fix this issue: #6567

**Comment by Shubham82** [comment]
closing this issue as it is resolved by PR #6567
