### ISSUE TITLE
in vpa recommender , 0 podMetrics retrieved for all namespaces

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/autoscaler#6221]
use prometheus as input metrics. but 0 pod metrics retrieved
        
        - --v=4
        - --storage=prometheus
        - --prometheus-address=http://10.238.158.59:32106
        - --prometheus-cadvisor-job-name=kubelet
        - --container-pod-name-label=pod
        - --container-name-label=container
        - --metric-for-pod-labels=kube_pod_labels{job="kube\
-state-metrics"}[8d]
        - --pod-name-label=pod
        - --recommender-name=default
        - --target-cpu-percentile=0.99
        - --memory-saver=true
        - --pod-label-prefix=label_
        - --recommender-interval=1s
        - --cpu-histogram-decay-half-life=1s

this is the log of cluster_feeder.go
I1024 15:49:09.603543       1 metrics_client.go:70] podMetricsList:&PodMetricsList{ListMeta:{   <ni\
l>},Items:[]PodMetrics{},} namespace: metav1:{{ }   false false   <nil> 0 } context:context.TODO
I1024 15:49:09.603568       1 metrics_client.go:71] c:&{{0xc0000ae400}  default-metrics-client}
I1024 15:49:09.603576       1 metrics_client.go:76] 0 podMetrics retrieved for all namespaces

i can get nginx cpu and memory in prometheus 
but the vpa can not get pod metrics
do you have any suggestions about how to solve it 

best
Lisa Shi

**Comment by wu0407** [comment]
You can refer to this configuration
```
- --recommender-name=level-s1
    - --kube-api-burst=20
    - --kube-api-qps=10
    - --recommendation-margin-fraction=0.00
    - --target-cpu-percentile=0.50
    - --container-name-label=container
    - --container-namespace-label=namespace
    - --container-pod-name-label=pod
    - --storage=prometheus
    - --memory-saver=true
    - --pod-label-prefix=label_
    - --metric-for-pod-labels=kube_pod_labels{job="kube-state-metrics"}[8d]
    - --pod-name-label=pod
    - --pod-namespace-label=namespace
    - --prometheus-address=http://vmselect-victoria-metrics-k8s-stack.victoria.svc:8481/select/0/prometheus
    - --prometheus-cadvisor-job-name=kubelet
```
