### ISSUE TITLE
Cluster Auto Scaler Not Scaling on Node CPU/Memory Utilization

### ISSUE THREAD

**Issue by srreddy2020** [kubernetes/autoscaler#6230]
Hello Team,
Kubernetes Version:  1.27.4
Cluster Autoscaler: v1.27.3

I am facing an issue related to Cluster Autoscaler,

We are running AWS EKS.

Issue is we have Node groups configured in EKS, The concern  is Nodes Cpu and Memory actual  Utilization is less than 50%.
Nodes CPU and Memory requests are around 99%, Cluster autoscaler is spinning up the new node when its having pending pods.
that time we are getting application down for couple of minutes for spinning up the node and place the pods.

But my requirement is how we can spin up the new node based on Node Utilization, means when CPU and Memory reaches 70% i want to have new node spine Up.

Please help me this.
Thanks & Regards

**Comment by srreddy2020** [comment]
Hello Team,

Can someone have a look on this please..

**Comment by sherifabdlnaby** [comment]
> But my requirement is how we can spin up the new node based on Node Utilization, means when CPU and Memory reaches 70% i want to have new node spine Up.

This is not in the scope of cluster auto-scaler. Cluster Autoscaler scale nodes up & down based on CPU/Memory Requests and not the actual utlization. 

To achieve what you're looking for you need to size workloads requests/memory correctly. There are other bin-packing techniques you can use to achieve better overall utilization, but not something the CAS will solely handle.

Also, please use a more descriptive issue titles

**Comment by gjtempleton** [comment]
As @sherifabdlnaby says, this is by design and to improve your node's utilisation of resources you need to improve the sizing of your workloads' resource requests. 

The Vertical Pod Autoscaler can help you with this.

/close
