### ISSUE TITLE
Exclude some namespaces from VPA webhook

### ISSUE THREAD

**Issue by adrianmoisey** [kubernetes/autoscaler#6232]
**Which component are you using?**:

vertical-pod-autoscaler - admission-controller

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
The source of this feature request is https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks#unsafe-webhooks

GKE displays a warning for webhooks that intercept resources in the kube-system namespace. 

This warning seems sane to me.

**Describe the solution you'd like.**:

Ability to ignore some namespaces for the vertical-pod-autoscaler admission-controller webhook.

**Describe any alternative solutions you've considered.**:

N/A

**Additional context.**:

N/A

**Comment by voelzmo** [comment]
will be fixed by: #6428
