### ISSUE TITLE
Verify vendor code in presubmit

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes/autoscaler#6267]
**Which component are you using?**: VPA

**Which component hosted in this repository is this a feature for?**: All components

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: 
Currently there is no good way to verify the integrity of modules under `vendor` directory. For example, someone could upgrade go version or go module version; update dependencies; perform `go mod vendor`; hand edit a go file under `vendor` and add a new function. The tempered vendor file will be buried in all the vendor changes.

You could look at all the vendor file change and verify individually but it is pretty time consuming and unrealistic.

**Describe the solution you'd like.**: Add a verification under `hack/` directory to verify vendor code integrity. Similar to https://github.com/kubernetes/kubernetes/blob/master/hack/verify-vendor.sh

**Describe any alternative solutions you've considered.**: Ideally `go mod verify` should do this but it is not happening: https://github.com/golang/go/issues/27348

**Additional context.**:

**Comment by Shubham82** [comment]
Hi @sophieliu15, JFI we removed the Cluster Autoscaler vendor directory in favor of Go modules,
Here is the PR for it: #6572
