### ISSUE TITLE
VPA admission controller certificate is not reloaded 

### ISSUE THREAD

**Issue by bmendoza820** [kubernetes/autoscaler#6272]
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: 0.13.0

Component version: 0.13.0

**What k8s version are you using (`kubectl version`)?**: 1.24

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: When using cert-manager to generate the secret containing TLS certs for the VPA admission controller, updates to the secret should trigger a reload so that the VPA admission controller is still available.

**What happened instead?**: When using cert-manager to generate the secret containing TLS certs for the VPA admission controller, updates to the secret result in the VPA admission controller reporting a bad certificate.

**How to reproduce it (as minimally and precisely as possible)**: See above

**Anything else we need to know?**:

Re-filing this as a +1 to https://github.com/kubernetes/autoscaler/issues/3458.
I see that https://github.com/kubernetes/autoscaler/pull/3462 was opened but eventually closed.

**Comment by voelzmo** [comment]
Will be fixed by #6665
