### ISSUE TITLE
Cluster Autoscaler patch releases Nov 2023

### ISSUE THREAD

**Issue by x13n** [kubernetes/autoscaler#6293]
I'm planning to cut new Cluster Autoscaler patch releases for 1.26-28 next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

Tagging cloud provider owners for visibility:
@4ND3R50N
@7fELF
@alphajc
@andrewsykim
@Andrius521
@apricote
@ArturasRa
@arunmk
@avorima
@BigDarkClown
@cprivitere
@ctrox
@davidjumani
@dbonfigli
@deitch
@detiber
@displague
@d-mo
@dougsong
@drmorr0
@ellistarn
@elmiko
@enxebre
@ericrrath
@feiskyer
@gajicdev
@gandhipr
@gjtempleton
@happytreees
@hardikdr
@hello2mao
@jackfrancis
@jayantjain93
@jaypipes
@Jeffwan
@jlamillan
@johnl
@jtherin
@kevin-wangzefeng
@LKaemmerling
@louisportay
@maciekpytel
@marwanad
@MorrisLaw
@mrajashree
@NeilW
@nilo19
@optik-aper
@OriHoch
@pawelkuc

**Comment by x13n** [comment]
@PhilippeChepy
@piepmatz
@pierre-emmanuelJ
@RainbowMango
@remyleone
@ringtail
@schegi
@Sh4d1
@shysank
@sohan-oracle
@tallaxes
@tghartland
@thirdeyenick
@towca
@trungng92
@vishalanarase
@v-pap
@zalmarge

**Comment by RainbowMango** [comment]
LGTM thank you for the notice

**Comment by ricardov1** [comment]
@x13n these have been merged but just want to make sure they're included in the releases:
1.26: https://github.com/kubernetes/autoscaler/pull/6287
1.27: https://github.com/kubernetes/autoscaler/pull/6285
1.28: https://github.com/kubernetes/autoscaler/pull/6283

**Comment by x13n** [comment]
@ricardov1 @ctrox Thanks, all the PRs you listed will be included.

**Comment by x13n** [comment]
Unfortunately, 1.25 reached end of life a month ago, I'm only patching the k/k versions that are still supported: https://kubernetes.io/releases/

**Comment by ricardov1** [comment]
hey @x13n, there was a bug introduced by this PR (https://github.com/kubernetes/autoscaler/pull/6072) that causes the cluster autoscaler pod to crash when using the `leader-elect` flag. This PR (https://github.com/kubernetes/autoscaler/pull/6115) fixes it but it wasn't included in the patch. is it posible to create an adhoc patch with this bug fix? and if so, what would that timeline look like?

**Comment by allenmunC1** [comment]
@x13n 

here are the backport PRs of #6115 to 1.26/1.27/1.28 release branches

1.26 - https://github.com/kubernetes/autoscaler/pull/6332
1.27 - https://github.com/kubernetes/autoscaler/pull/6331
1.28 - https://github.com/kubernetes/autoscaler/pull/6330

**Comment by x13n** [comment]
Thanks! Approved all 3, will cut new images next week.

**Comment by vishalanarase** [comment]
@x13n is it possible to include?

1.28 - https://github.com/kubernetes/autoscaler/pull/6322
128 - https://github.com/kubernetes/autoscaler/pull/6324

**Comment by x13n** [comment]
I'd like to limit the changes just to fix the bug introduced with the November patches. For all other changes we'll follow [the regular schedule](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#patch-releases). Please prepare cherrypick PRs to make sure the changes are included in the next patch release.

**Comment by x13n** [comment]
A new set of patches has been released, fixing the `--leader-elect` flag problem. Thanks @ricardov1 for raising this!
