### ISSUE TITLE
Cluster Autoscaler - Add docs for debugging snapshotter

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#6309]
**Which component are you using?**:

Cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We implemented the [debugging snapshotter](https://github.com/kubernetes/autoscaler/pull/4552) feature for the cluster autoscaler to provide significant help to users when trying to understand the CA's behaviour. 

We've previously demoed this at [Kubecon EU 2023](https://youtu.be/VgTWf4mjyG8?si=iHkcv5FT2yO3q5x0&t=596), however currently we don't have any docs for this feature in the repo to help users discover and use it.

**Describe the solution you'd like.**:

Docs added to explain the use of the debugging snapshotter.

**Describe any alternative solutions you've considered.**:

N/A

**Additional context.**:

**Comment by Dharma-09** [comment]
Hey @gjtempleton Can I work on this issue?

**Comment by Shubham82** [comment]
@Dharma-09 you can work on this issue by assigning it to yourself.

@professorabhay are you working on this issue? (just want to confirm)
