### ISSUE TITLE
how to use external metrics in vpa

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/autoscaler#6314]
i can get the value data in kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta2/namespaces/default/pods/*/container_cpu_usage_seconds_total"

i use prometheus adapter to make apiservice custom.metrics.k8s.io/v1beta2.
how to use this metrics in vpa?
where to change the metrics form metrics server to custom.metrics.k8s.io/v1beta2?
do the data in custom metrics has some request?

this is the data in custom metrics

{"describedObject":{"kind":"Pod","namespace":"default","name":"nginx-579576b854-b989n","apiVersion":"/v1"},\
"metric":{"name":"container_cpu_usage_seconds_total","selector":null},"timestamp":"2023-11-23T14:04:34Z","value":"200m"}

this is APIservice

<img width="252" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/8e8a8b86-2953-4148-bab0-bfb072e7da07">

this is prometheus adapter config
<img width="434" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/513911e3-64c8-4841-920b-bcf4d28a0b76">

looking forward to your reply
Best
Lisa Shi

**Comment by shixinlishixinli** [comment]
i have try /autoscaler/vertical-pod-autoscaler/hack/e2e/prometheus-adapter.yaml and autoscaler/vertical-pod-autoscaler/hack/e2e/prometheus.yaml

but the resource is empty

<img width="447" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/fa08049b-dc46-4325-8a30-778d4d78d3fd">

how to put my data into this external metrics

best
lisa shi

**Comment by shixinlishixinli** [comment]
i can get the cpu usage from "kubectl  get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/cpu"| jq"
<img width="314" alt="image" src="https://github.com/kubernetes/autoscaler/assets/20768380/2570a893-b2e4-4026-b160-166a65d47ec9">

 --use-external-metrics=true
 --external-metrics-cpu-metric=cpu

in recommender-deployment.yaml


the err is  err: cpu.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:vpa-recommender"
 cannot list resource "cpu" in API group "external.metrics.k8s.io" in the namespace "default"


do you know how to solve this bug ?
looking forward to your reply
best
lisa shi

**Comment by shixinlishixinli** [comment]
> i can get the cpu usage from "kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/cpu"| jq" <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/20768380/286636236-2570a893-b2e4-4026-b160-166a65d47ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTcyOTIsIm5iZiI6MTcwMTQxNjk5MiwicGF0aCI6Ii8yMDc2ODM4MC8yODY2MzYyMzYtMjU3MGE4OTMtYjJlNC00MDI2LWIxNjAtMTY2YTY1ZDQ3ZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA3NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3Zjk3YTMyYjE4Mzk0YjhkODJiYzlmNjI2NzJkNTdhZjNlOTkwZDg5M2EzM2VkZTU1ZmRlNTVkOGI2ZTJkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4oogQLo8h6d70gRSXgQWapa4edS2C4SO0Q4IPuYr7Nc">
> 
> --use-external-metrics=true --external-metrics-cpu-metric=cpu
> 
> in recommender-deployment.yaml
> 
> the err is err: cpu.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:vpa-recommender" cannot list resource "cpu" in API group "external.metrics.k8s.io" in the namespace "default"
> 
> do you know how to solve this bug ? looking forward to your reply best lisa shi

the reason is not run rbac.yaml

**Comment by Shubham82** [comment]
Hi @shixinlishixinli 
if your issue is resolved, so can we close this issue?

**Comment by Shubham82** [comment]
Closing this issue, Please reopen it if you still have any concerns.
