### ISSUE TITLE
Please update the chart's image (or is there a reason cluster-autoscaler-chart-9.32.1 pins image v1.27.2 instead of a newer build)

### ISSUE THREAD

**Issue by kevincantu** [kubernetes/autoscaler#6334]
I'm surprised to see that this week's `cluster-autoscaler-chart-9.32.1` release in November still defaults to `image.tag: v1.27.2` ([here](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-chart-9.32.1/charts/cluster-autoscaler/values.yaml#L233)) which is a version of cluster-autoscaler from May!

Is there a reason that isn't referencing the newest cluster-autoscaler image, `cluster-autoscaler-1.28.1`?

Can you do a chart release with the update?

**Comment by gjtempleton** [comment]
Resolved by #6340 
/close

**Comment by kevincantu** [comment]
Thanks @gjtempleton!!
