### ISSUE TITLE
Improve kwok provider installation docs

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/autoscaler#6339]
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/kwok#how-to-use-kwok-provider talks about installing cluster-autoscaler in your local kind cluster but it doesn't clarify where to install the chart from:
![image](https://github.com/kubernetes/autoscaler/assets/34534103/21b892ba-287f-4495-a37c-6d94c047d75d)

Right now, it is implicitly assumed that the user is in the parent [`autoscaler` directory](https://github.com/kubernetes/autoscaler). Many users will not have the repo cloned on their computer. The docs should be updated to use helm repo chart for installation. 

/label area/provider/kwok
/label cluster-autoscaler
/label good-first-issue

**Comment by vadasambar** [comment]
Note that to use cluster-autoscaler with kwok provider needs a new cluster-autoscaler release (aka new official image).

**Comment by Shubham82** [comment]
@vadasambar, is there any update on this issue? I think we can update the Kwok README.md

**Comment by Shubham82** [comment]
Closing this issue as it is resolved by PR #7069
/close
