### ISSUE TITLE
Steady memory leak in VPA recommender

### ISSUE THREAD

**Issue by DLakin01** [kubernetes/autoscaler#6368]
**Which component are you using?**: 

vertical-pod-autoscaler, recommender only

**What version of the component are you using?**

0.14.0

**What k8s version are you using (`kubectl version`)?**:

1.26

**What environment is this in?**:

AWS EKS, multiple clusters and accounts, multiple types of applications running on the cluster

**What did you expect to happen?**:

VPA recommender should run at more or less at the same memory level throughout the lifetime of a particular pod

**What happened instead?**:

There is a steady memory leak that is especially visible over a period of days, as seen here in a screen capture of our DataDog:
![image](https://github.com/kubernetes/autoscaler/assets/28016495/d9e920f3-c2ed-42e1-bcec-3b98e764ee77)

The upper lines with the steeper slope are from our large multi-tenant clusters, but the smaller clusters also experience the leak, albeit more slowly. If left alone, the memory will reach 200% of requests before the pod gets kicked. The recommender in the largest cluster is tracking 3161 `PodStates` at the time of creating this issue

**How to reproduce it (as minimally and precisely as possible)**:

Not sure how reproducible the issue is outside of running VPA in a large cluster with > 3000 pods and waiting several days to see if the memory creeps up. 

**Anything else we need to know?**:

We haven't yet created any VPA CRDs to generate recommendations, waiting until a future sprint to begin rolling those out.

**Comment by vkhacharia** [comment]
We also face the same issue. Our version is `0.11` with k8s version `1.24`. Below is grafana snippet from the last restart.
<img width="1704" alt="image" src="https://github.com/kubernetes/autoscaler/assets/32457297/2b11a347-5dca-4b07-ad12-9853d7319ea1">

**Comment by voelzmo** [comment]
Hey @vkhacharia @DLakin01 thanks for bringing this up!

To some extend, this behavior is expected and given only these graphs it is hard to tell, if the behavior is normal or not. 
The recommender keeps metrics for each container, regardless if that container is under VPA control or not. I guess the reasoning is that you get accurate recommendations immediately if you would decide to enable VPA for this container at a later point in time. You can switch off this default behavior by [enabling memory saver mode](https://github.com/kubernetes/autoscaler/blob/0c62f543f1a1a8922f1579ffe2a238bb2e269325/vertical-pod-autoscaler/pkg/recommender/main.go#L75).

Even with memory saver mode enabled, there's some grow in memory expected:
* `AggregateContainerState` is garbage collected, whenever a sample is found to be [no longer contributing to a recommendation](https://github.com/kubernetes/autoscaler/blob/0c62f543f1a1a8922f1579ffe2a238bb2e269325/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L354-L362). This check is run [once per hour](https://github.com/kubernetes/autoscaler/blob/0c62f543f1a1a8922f1579ffe2a238bb2e269325/vertical-pod-autoscaler/pkg/recommender/main.go#L99-L100).
* `AggregateContainerStates` are [indexed by their `name`, `namespace`, and `labelSet`](https://github.com/kubernetes/autoscaler/blob/0c62f543f1a1a8922f1579ffe2a238bb2e269325/vertical-pod-autoscaler/pkg/recommender/model/cluster.go#L69-L75), so e.g. every rollout of a new `Deployment` version will create new `AggregateContainerState`s. The old `AggregateContainerStates` are kept for 8 days (removed only when they are found to be no longer possibly contributing, see above).

So if you're rolling approximately the same number of times per week, your memory is expected to grow for ~2 weeks. If you're adding Containers and don't have memory saver mode enabled, memory will grow with every Container.

If all of those parameters are controlled and you still see memory growth, I guess this really is a memory leak that shouldn't happen.

**Comment by vkhacharia** [comment]
@voelzmo  Thanks for the quick response, I wanted to try it  now but noticed that I am on k8s version 1.24 which has compabitility with 0.11 of vpa recommender. I dont see the parameter `memory-saver` in code in branch for version 0.11.

**Comment by voelzmo** [comment]
Hey @vkhacharia, thanks for your efforts! VPA 0.11.0 also has `memory-saver` mode, but the parameter is in [a different place](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-0.11.0/vertical-pod-autoscaler/pkg/recommender/routines/recommender.go#L52) and was moved to the above section in the code with a refactoring that happened later.

So you can still turn on `--memory-saver=true` and see what this does for you. Hope that helps!
