### ISSUE TITLE
Will cluster-autoscaler work for openshift cluster created in GCE

### ISSUE THREAD

**Issue by dineshsckloud9** [kubernetes/autoscaler#638]
We have a openshift cluster setup with instance group in GCE. We could not achieve node autoscaling for openshift nodes. 

Can we run this cluster-autoscaler as a pod in openshift master instance to make autoscaling work?

Will it work? Suggest me any other way if cluster-autoscaler does not work.

Note: We have taken cluster-autoscaler v0.6.1 pod config from kubernetes and have modified the yaml for openshift.

/sig scalability
/sig autoscaling
/sig openshift

**Comment by aleksandra-malinowska** [comment]
cc @DirectXMan12

**Comment by pradeeppandeyy** [comment]
kubernetes cluster autoscaler will work with openshift  @dineshsckloud9  . We already tried this and It is working fine for us in gcp.

**Comment by aleksandra-malinowska** [comment]
@DirectXMan12 should we keep it open?

**Comment by dineshsckloud9** [comment]
It works fine.. Closing this ticket
