### ISSUE TITLE
Bump VPA version to 1.1.0 in preparation for 1.29 k8s release

### ISSUE THREAD

**Issue by laoj2** [kubernetes/autoscaler#6388]
Please follow instructions in
[RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md) and note each
completed step on this issue.

Please provide any information that is related to the release:

- When we plan to do the release?
     - ~now 
- Are there any issues / PRs blocking the release?
    - VPA tests are mostly red: https://testgrid.k8s.io/sig-autoscaling-vpa, we'll need to fix those before the release.

**Comment by laoj2** [comment]
Created #6389 to track the E2E test failures

**Comment by voelzmo** [comment]
Still some e2e errors, created #6510 to track

**Comment by voelzmo** [comment]
e2e tests are green again 🎉

**Comment by laoj2** [comment]
Thanks for the fixes @voelzmo! Tests have been green for a while, sent #6610 for review.

**Comment by laoj2** [comment]
Thanks for approving @kwiesmueller, are you able to create a new `vpa-release-1.1` branch in https://github.com/kubernetes/autoscaler/branches from the merged PR? I don't have permission.

**Comment by laoj2** [comment]
@kwiesmueller we can use these release notes:

```
Confirms VPA/Pod association by checking OwnerRef against TargetRef, instead of relying on labelSelector (see #6460)

Removes vpa builder Dockerfile and switch dependabot to component Dockerfiles (see #6370)

Switches to multistage build Dockerfiles for VPA (see #6338)

Fixes '.spec.updatePolicy.evictionRequirements.resources' to be plural in yaml (see #6251)

Implements KEP-4831: Control VPA eviction behavior based on scaling direction and resource (see #5599)

Fixes multiple run of informers created in fetcher.go (see #6157)

```

I'm purposely omitting the go and dependency version bumps from the list because there were way too many in the past months.

**Comment by voelzmo** [comment]
> I'm purposely omitting the go and dependency version bumps from the list because there were way too many in the past months.

Maybe we can just include a hint to the go version that this release was built with? No need to include the intermediate bumps, I guess. WDYT?

I would also leave these notes out, as they don't have relevance
> Fixes '.spec.updatePolicy.evictionRequirements.resources' to be plural in yaml (see #6251)

**Comment by laoj2** [comment]
Yes, sounds good @voelzmo. @kwiesmueller can you take another look? I amended the comment with the updated release notes. Thanks

**Comment by laoj2** [comment]
Ran the `full-vpa` test suite with the [1.1.0](gcr.io/k8s-staging-autoscaling/vpa-admission-controller:1.1.0) staging images and the tests are passing. Will send a PR to promote the images.

**Comment by laoj2** [comment]
Released 🎉 : https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-1.1.0
