### ISSUE TITLE
VPA E2E tests are broken

### ISSUE THREAD

**Issue by laoj2** [kubernetes/autoscaler#6389]
This is blocking the VPA 1.1.0 release

**Which component are you using?**:

vertical-pod-autoscaler 

**What version of the component are you using?**:

gcr.io/k8s-infra-e2e-boskos-079/vpa-updater-amd64:latest

gcr.io/k8s-infra-e2e-boskos-079/vpa-admission-controller-amd64:latest

Testgrid: https://testgrid.k8s.io/sig-autoscaling-vpa#Summary

Logs of the latest failed run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1737090055995920384

**Comment by voelzmo** [comment]
This might have happened in the refactorings of https://github.com/kubernetes/autoscaler/pull/5599
I'll take a look today and see if I can find out what happened.
