### ISSUE TITLE
scaling-down nodes that are running only system pods

### ISSUE THREAD

**Issue by adamrp** [kubernetes/autoscaler#64]
I'm using:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

What I did:
- I created a one-node GKE cluster, cluster autoscaling disabled
- At the time of creation, all kube-system pods were running on the one node
- I subsequently enabled cluster autoscaling with a minimum cluster size of 1 and a maximum of 5
- All kube-system pods continued to run on the one original node
- I ran a Job that taxed the system to the extent that CA added a new node
- After the job was finished, all pods were removed, leaving only kube-system pods running

What I expected:
- CA would scale down the cluster to its initial (minimum) size (one node) shortly after the taxing job was complete

What happened:
- The cluster stayed at two nodes
- When CA added a new node, the kube-system pods had been redistributed to run across *both* nodes
- According to [the FAQ here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#i-have-a-couple-of-nodes-with-low-utilization-but-they-are-not-scaled-down-why), this happened because CA will not remove nodes running system pods

Suggestion:
- If a cluster is above its configured minimum size *only* because kube-system pods are preventing it from shrinking, the superfluous node(s) should be automatically drained, the kube-system pods should be consolidated onto a single node (or rather, onto a number of nodes equal to the cluster's configured minimum), and the superfluous nodes should be removed from the cluster

**Comment by mwielgus** [comment]
Thank you for the report. We are aware of this and we thinking about the best approach to solve it.

cc: @MaciekPytel @fgrzadkowski

**Comment by mwielgus** [comment]
@adamrp It will be possible in the new version. However you will have to create a PodDisruptionBudget for all of your system pods like dns, dashboard, heapster (evertyhin other than daemonset/kube-proxy/etc).

**Comment by axot** [comment]
Any best practices PodDisruptionBudget for kube-system? Thanks.

**Comment by aleksandra-malinowska** [comment]
> Any best practices PodDisruptionBudget for kube-system?

Only add them if you're sure those pods can be safely evicted :) E.g. creating a PDB for kube-dns with minAvailable > 50% should be OK in most cases. However, evicting all kube-dns pods at the time can cause networking problems. In case of metrics-server or heapster, there's only one replica, so a PDB for it will always cause the risk of downtime (loss of metrics) for a couple of minutes. It really depends on your setup whether it's acceptable or not.

**Comment by MaciekPytel** [comment]
In this particular case your node is running metrics-server. Restarting it would prevent all HPAs in your cluster from autoscaling (and make them set error status, emit error events, etc) for a few minutes. As @aleksandra-malinowska wrote it's really your decision if it's acceptable or not.

In general kube-dns is the only system pod that comes to my mind that has multiple replicas. Every other system pod is a singleton and restarting it will likely cause some kind of temporary disruption in cluster. If it's a test cluster it may be ok to just create a PDB for every kube-system pod. If it's production you probably need to make case-by-case decision based on which services are critical for your workloads.

**Comment by axot** [comment]
@aleksandra-malinowska  @MaciekPytel Thank you for so detailed explanation. Maybe the best way is set non-PDB for kube-system in my case.

Could I ask one more question? I noticed in FAQ `What types of pods can prevent CA from removing a node?`

```
Pods with restrictive PodDisruptionBudget.
Kube-system pods that:
    are not run on the node by default, *
    don't have PDB or their PDB is too restrictive (since CA 0.6).
Pods that are not backed by a controller object (so not created by deployment, replica set, job, stateful set etc). *
Pods with local storage. *`
```

What does `local storage.*` actually meaning? Does hostPath, emptyDir belongs it?

**Comment by MaciekPytel** [comment]
It does. If you have a pod that uses local storage, but you want to allow CA to move it around you can set "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" annotation on it.
