### ISSUE TITLE
Local PV will prevent node scaling down

### ISSUE THREAD

**Issue by jewelzqiu** [kubernetes/autoscaler#6417]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: v1.26.3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.11-eks-8cb36c9
</pre></details>

**What environment is this in?**:

EKS

**What did you expect to happen?**:

Under-utilized nodes with local PV should be scaled down

**What happened instead?**:

Under-utilized nodes with local PV cannot be scaled down

**How to reproduce it (as minimally and precisely as possible)**:

If pod has local PV (provisioned by [local-volume-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/provisioner.md) in our use case) mounted
CA refuses to evict the pod because the local pv has NodeAffinity for specific node
There is no way we can bypass this restriction to scale down those under-utilized nodes

**Anything else we need to know?**:

Specifying `safe-to-evict-local-volumes` and `safe-to-evict` does no help,
because pod will eventually enter bounded PV check where it will fail

I think we should provide an option to remove some volumes before bounded PV check

**Comment by wackxu** [comment]
I also encountered this problem. Have you solved it? @jewelzqiu
