### ISSUE TITLE
leader-elect flags are not being accepted with ClusterAutoscaler 1.28.0 version

### ISSUE THREAD

**Issue by vbhargav875** [kubernetes/autoscaler#6421]
**Which component are you using?**:
ClusterAutoscaler - v1.28.0

Which autoscaling component hosted in this repository (cluster-autoscaler, vertical-pod-autoscaler, addon-resizer, helm charts) is the bug in?
cluster-autoscaler

**What version of the component are you using?**:
v1.28.0

What version of the relevant component are you using? Either the image tag or helm chart version.
cluster-autoscaler-release-1.28.0

Component version:

**What k8s version are you using (`kubectl version`)?**:
v1.28.2

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
`$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.2", GitCommit:"6f3fcf83109204e359ca38144405293dbeec2200", GitTreeState:"clean", BuildDate:"2023-10-20T09:33:45Z", GoVersion:"go1.20.8 4493 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}`

</pre></details>

**What environment is this in?**:

If you're using a cloud provider or hardware configuration as your deployment environment let us know here.
Oracle Cloud Infrastructure

**What did you expect to happen?**:
--leader-elect flag should be accepted.

What behaviour did you expect to see?
Should not observe the below error
`unknown flag: --leader-elect`

**What happened instead?**:
Observed below
`unknown flag: --leader-elect`

What behaviour did see instead?
Observed below error
`unknown flag: --leader-elect`

How to reproduce it (as minimally and precisely as possible):
Pass leader-elect argument to cluster-autoscaler v1.28.0

**Comment by MaciekPytel** [comment]
I think this was fixed in 1.28.2 - https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.28.2

**Comment by gjtempleton** [comment]
That issue was [only present in v1.28.1](https://github.com/kubernetes/autoscaler/issues/6293#issuecomment-1832732180) as far as we were aware. Can you double check the image tag you're using where you're seeing this behaviour please @vbhargav875 ?

**Comment by vbhargav875** [comment]
@gjtempleton I can confirm that the version I used was v1.28.0
Referring to the version specified in the [version.go](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.28/cluster-autoscaler/version/version.go#L20)

**Comment by gjtempleton** [comment]
Are you building the images yourselves or using an image published to registry.k8s.io?

**Comment by vbhargav875** [comment]
I am building the image myself. Yes, this commit is included.
If it helps, I had built the image on Nov 14th 2023 with the changes in the **cluster-autoscaler-release-1.28** branch. 
It looks like 1.28.1 came out towards the end on Nov.

**Comment by gjtempleton** [comment]
Yeah, in that case you've picked up the known bug from our v1.28.1 release, we only increment the version.go as part of the release process and tag itself. Building based on the head of a release branch will most likely put you in a state where your packaged code isn't matching a release cut by us.

Rebasing off the latest patch release in a given minor release series would be what I'd recommend going forward.

Any objection to us closing this as it's been patched in the release branches?

**Comment by vbhargav875** [comment]
Understood, thank you.
Yes, this issue can be closed.

**Comment by gjtempleton** [comment]
Thanks, and thanks for reporting it!
/close
