### ISSUE TITLE
VPA in recommender mode deletes pods

### ISSUE THREAD

**Issue by RafPe** [kubernetes/autoscaler#6422]
**Which component are you using?**: vertical-pod-autoscaler

**What version of the component are you using?**: now 0.14 , before 1.0 

Component version: now 0.14 , before 1.0 

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.8-eks-8cb36c9

</pre></details>

**What environment is this in?**: production/test

If you're using a cloud provider or hardware configuration as your deployment environment let us know here: AWS & EKS 

**What did you expect to happen?**: I expected VPA to not interact with any workloads unless instructed by VPA objects defining either recommendation mode or updating mode

**What happened instead?**: VPA started removing/deleting pods without any VPAs defined

```
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.286640       1 recommender.go:155] Recommender Run
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.286683       1 cluster_feeder.go:317] Start selecting the vpaCRDs.
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.286689       1 cluster_feeder.go:352] Fetched 0 VPAs.
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.287216       1 cluster_feeder.go:401] Deleting Pod {example-api example-api-worker-6fd49dd676-2mc64}
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.299810       1 metrics_client.go:83] 242 podMetrics retrieved for all namespaces
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.300883       1 cluster_feeder.go:440] ClusterSpec fed with #630 ContainerUsageSamples for #315 containers. Dropped #0 samples.
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.300909       1 recommender.go:165] ClusterState is tracking 244 PodStates and 0 VPAs
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:28.301070       1 recommender.go:175] ClusterState is tracking 493 aggregated container states
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:22:37.907981       1 reflector.go:559] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:136: Watch close - *v1.DaemonSet total 7 items received
vpa-recommender-5fd797b6cf-62cgf recommender I0106 07:23:28.288449
```

**How to reproduce it (as minimally and precisely as possible)**: Install on EKS 1.27 , remove the updater component from the installation and then try to see if it deletes the pods ?! 

**Anything else we need to know?**: It is really hard for me to describe how to replicate it as this is just happening on my end with vanialla installation without any VPAs configured. So I would like to understand If I am missing something or the VPA framework is just takinga wrong decisions here ....

**Comment by voelzmo** [comment]
Hey, @RafPe,

thanks for the detailed description! You're looking at the log output generated by the `recommender`, which is _never_ interfering with your workload, regardless of the configuration and operating mode. See the [documentation](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#components-of-vpa) and the linked [architecture diagram from the original proposal](https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/vertical-pod-autoscaler.md#overview): The `recommender` is responsible for coming up with new recommendations for the `resources` of a Container. The other VPA components act on those new recommendations: the `updater` might evict your workload, the `admission-webhook` will modify the `resources` section in the PodSpec for newly created Pods.

You should be able to confirm that nothing happens by looking at the `uptime` for your Pods: They should continue to run.

When you see that `uptime` has an unexpected low value and suspect that VPA might be the reason for this (once you switch from recommendation mode to actually updating the Pod resources), you can confirm this by looking at the `events`. Here is an example where the example `hamster` app gets evicted by the `updater`:
```
k get events -A --field-selector=reason=EvictedByVPA
NAMESPACE   LAST SEEN   TYPE     REASON         OBJECT                        MESSAGE
default     5s          Normal   EvictedByVPA   pod/hamster-c6967774f-jxg8j   Pod was evicted by VPA Updater to apply resource recommendation.
default     65s         Normal   EvictedByVPA   pod/hamster-c6967774f-tl2th   Pod was evicted by VPA Updater to apply resource recommendation.
```

Now, what does the log statement you found mean? It originates from a part of the code [where the `recommender` loads information about all Pods in your cluster into its in-memory state](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go#L399-L404). In this section, the recommender also identifies "stale in-memory state", meaning it finds Pods in its state that no longer exist in you cluster. Therefore, it goes ahead and _deletes the in-memory information for these Pods_. As I mentioned earlier: The recommender only _lists_ your Pods and gathers usage information, it never modifies or deletes them.

Hope that makes sense!
