### ISSUE TITLE
Cluster Autoscaler patch releases Jan 2024

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#6424]
I'm planning to cut new Cluster Autoscaler patch releases for 1.26-29 next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

This will likely be the last round of patches for 1.26, as 1.29 is out and our current policy is to support last 3 minors.

I'm planning to cut new Cluster Autoscaler patch releases for 1.26-28 next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

Tagging cloud provider owners for visibility:
@4ND3R50N
@7fELF
@alphajc
@andrewsykim
@Andrius521
@apricote
@ArturasRa
@arunmk
@avorima
@BigDarkClown
@cprivitere
@ctrox
@davidjumani
@dbonfigli
@deitch
@detiber
@displague
@d-mo
@dougsong
@drmorr0
@ellistarn
@elmiko
@enxebre
@ericrrath
@feiskyer
@gajicdev
@gandhipr
@gjtempleton
@happytreees
@hardikdr
@hello2mao
@jackfrancis
@jayantjain93
@jaypipes
@Jeffwan
@jlamillan
@johnl
@jtherin
@kevin-wangzefeng
@LKaemmerling
@louisportay
@MaciekPytel
@marwanad
@MorrisLaw
@mrajashree
@NeilW
@nilo19
@optik-aper
@OriHoch
@pawelkuc

**Comment by MaciekPytel** [comment]
@PhilippeChepy
@piepmatz
@pierre-emmanuelJ
@RainbowMango
@remyleone
@ringtail
@schegi
@Sh4d1
@shysank
@sohan-oracle
@tallaxes
@tghartland
@thirdeyenick
@towca
@trungng92
@vishalanarase
@v-pap
@zalmarge

**Comment by NeilW** [comment]
Hi,

Backported cherry-picks of the Brightbox cloud provider for release 1.27 are in PR #6425

**Comment by NeilW** [comment]
Backported cherry-picks of the Brightbox cloud provider for release 1.26 are in PR #6429

**Comment by Shubham82** [comment]
Hi @MaciekPytel, I think we missed the Jan Patch release, could you please tell us when you are planning to do that because users want some features in the previous version of CA.

Thanks!

**Comment by lyoung-confluent** [comment]
@MaciekPytel Sorry to be a bother, do we have a new ETA for this patch release? I'm hoping https://github.com/kubernetes/autoscaler/issues/6620 will make the cut for the final 1.26 release which was merged yesterday.

**Comment by gjtempleton** [comment]
Put a bit of context in #6626, but these releases were cut but not promoted back in June, as such I'm intending to promote the images Maciek cut at the same time as I cut the March releases later this week/next week including a final 1.26 release based on the state of the release branch then.

**Comment by Shubham82** [comment]
> Put a bit of context in #6626, but these releases were cut but not promoted back in January, as such I'm intending to promote the images Maciek cut at the same time as I cut the March releases later this week/next week including a final 1.26 release based on the state of the release branch then.

Thanks, @gjtempleton for the above information.

I'm closing this issue with reference to issue #6626, so there will be no confusion in the CA patch releases.
