### ISSUE TITLE
Is the Cluster-AutoScaler restarts/manages if any node in the cluster dies or crashes? [AWS]

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/autoscaler#643]
Is the Cluster-AutoScaler restarts/manages the node if any node in the cluster dies or crashes? I can see that it can scale up or scale down but what if a node dies? Does it maintains the desired number of nodes in the cluster?

AWS

**Comment by aleksandra-malinowska** [comment]
Not really. Cluster Autoscaler respects minimum and maximum limits when adding/removing nodes, but it doesn't change the cluster size only to fit those constraints. 

It only ever adds nodes if there are unschedulable pods in the cluster. If a node crashes/dies unexpectedly, the pods that were running on it will be rescheduled elsewhere. If there's not enough space for them in the cluster, they become unschedulable, at which point CA will try to add a node (or nodes) for them.

It removes a node if it thinks it's underutilized and unneeded (all pods running on it can be rescheduled somewhere else.) There are some very specific cases when it may detect and remove an unhealthy node (that never registered or became ready), but it doesn't monitor or manage the nodes.
