### ISSUE TITLE
Patching CVE and encounter library compile issue

### ISSUE THREAD

**Issue by jimmy03190** [kubernetes/autoscaler#6430]
I've run image scan on latest auto-scaler on Harbor Trivy. The result shows folllowing CVE.
![image](https://github.com/kubernetes/autoscaler/assets/75720599/21dc4f87-a2de-4164-8a2c-2b5ce1079b3a)
After update otelgrpc library to v0.46.0, something goes wrong with image build like following:
![image](https://github.com/kubernetes/autoscaler/assets/75720599/3dd09525-f454-46a9-9fce-a8e15cd3b0a6)
I've tried using older version of this library (otelgrpc) and it only works with v0.44.0. Any newer version will cause the same error message. I also tried to search [this issue](https://github.com/etcd-io/etcd/issues/16926) but it seems already fixed with previous version. Is there any way to avoid this issue?

**Anything else we need to know?**:
go_lang_version: 1.21.5

How I reproduce this issue:
1.Clone latest build from github
2.Run following commands:

> git clone https://github.com/kubernetes/autoscaler
cd cluster-autoscaler
go get go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0
go mod tidy
go mod vendor
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cluster-autoscaler-amd64 --ldflags "-s"
export TAG=aws.registry.xxx.com/infra/cluster-autoscaler:v1.29.2
docker build . -t $TAG --platform linux/amd64 -f Dockerfile.amd64

What I'm trying to do is to patch image without CVE. If there is other way to avoid above issue?

**Comment by jimmy03190** [comment]
Anyone? I tried to upgrade otelgrupc to v0.47.0 but the same error remains.

**Comment by fzhqual** [comment]
Hi, I got the same issue when upgrading otelgrpc library to v0.46.0. Did you figure out a way to resolve it?
