### ISSUE TITLE
include https://github.com/kubernetes/autoscaler/pull/5901 in older version like 1.24, 1.25, 1.26 and 1.27

### ISSUE THREAD

**Issue by nkryption** [kubernetes/autoscaler#6467]
**Which component are you using?**:
cluster-autoscaler

Which component hosted in this repository is this a feature for?
cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
The fix/feature that the PR:https://github.com/kubernetes/autoscaler/pull/5901 is not in older versions like 1.24, 1.25, 1.26 and 1.27.
hence we face issue in which count of unneeded nodes increase to a large as the scale down is in cooldown.

**Describe the solution you'd like.**:
Include the changes in PR:https://github.com/kubernetes/autoscaler/pull/5901 for 1.24, 1.25, 1.26 and 1.27

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by Shubham82** [comment]
As per our current policy, we only support the last 3 minor releases,  as v1.29 is out, support releases are v1.26, v1.27, v1.28

**Comment by Shubham82** [comment]
Is it ok to make the changes in v1.26 and v1.27, as this feature was added in v1.28.

**Comment by nkryption** [comment]
> Is it ok to make the changes in v1.26 and v1.27, as this feature was added in v1.28.

Currently we have k8s clusters starting with version starting with 1.24 till 1.27. Adding this in 1.26 and 1.27 would help but it would be really great if we can have this in 1.24 and 1.25 as well.

**Comment by Shubham82** [comment]
I think we can't release the CA patch release for v1.24 and v1.25. (#6424)

@gjtempleton @MaciekPytel  your thoughts on this?

**Comment by nkryption** [comment]
> I think we can't release the CA patch release for v1.24 and v1.25. (#6424)
> 
> @gjtempleton @MaciekPytel your thoughts on this?

@Shubham82 Any chance for having this in 1.26 and 1.27 at least ?

**Comment by Shubham82** [comment]
> @Shubham82 Any chance of having this in 1.26 and 1.27 at least ?

@nkryption, Yeah I will open a PR to cherry-pick #5901 to CA1.26 and 1.27.

**Comment by Shubham82** [comment]
Hi @nkryption
I have raised the following PR to fix this issue:
For CA 1.27  #6505
For CA 1.26  #6504

**Comment by x13n** [comment]
Note that #5901 fixed a problem with removal of unneeded *node groups*, not unneeded *nodes*. To my knowledge no cloud provider except for GKE supports dynamic creation/deletion of node groups, so I doubt these specific changes will help anywhere else. We can backport the changes (approved already), in case I'm wrong since they do fix a bug, but  I'm pretty sure it is not the bug you're looking for.

**Comment by nkryption** [comment]
> Note that #5901 fixed a problem with removal of unneeded _node groups_, not unneeded _nodes_. To my knowledge no cloud provider except for GKE supports dynamic creation/deletion of node groups, so I doubt these specific changes will help anywhere else. We can backport the changes (approved already), in case I'm wrong since they do fix a bug, but I'm pretty sure it is not the bug you're looking for.

We were facing similar problem in AWS in which the unneeded nodes were getting piled up and when we tested it by ugrading to CA version 1.28.2 along with tweaking "scale-down-delay-after-add", it does solve the problem. 
hence we wanted this fix in lower versions as well.

**Comment by Shubham82** [comment]
> Note that #5901 fixed a problem with removal of unneeded _node groups_, not unneeded _nodes_. To my knowledge no cloud provider except for GKE supports dynamic creation/deletion of node groups, so I doubt these specific changes will help anywhere else. We can backport the changes (approved already), in case I'm wrong since they do fix a bug, but I'm pretty sure it is not the bug you're looking for.

@nkryption, Please check the above thing, mentioned by @x13n. Also, if your concern is resolved, can we close this issue as the Corresponding PRs are merged?
Thanks!

**Comment by nkryption** [comment]
thanks a lot @Shubham82 and @x13n for your help.

**Comment by nkryption** [comment]
@Shubham82 by when can we expect the release for 1.26 and 1.27 ?

**Comment by Shubham82** [comment]
@nkryption, it will be in the patch release for 1.26 and 1.27 and I think we missed the Jan patch release for CA (#6424)
We can ask this on the corresponding issue.
