### ISSUE TITLE
Min & max not set for AWS ASG

### ISSUE THREAD

**Issue by TimJones** [kubernetes/autoscaler#647]
I have a small K8S v1.8.6 cluster deployed using kops with `--node-count 2`. This sets up an ASG with Min\Max instances both set to 2.

I then install an autoscaler Deployment with `--nodes=1:3:<asg-name>` but listing the ASG still shows Min\Max both set to 2.

I have to run `kops edit instancegroup nodes` to set the min\max to match before autoscaler can work.

I would expect autoscaler to set the min\max based on its config at startup.

**Comment by aleksandra-malinowska** [comment]
> I would expect autoscaler to set the min\max based on its config at startup.

This feature (instance groups having built-in min/max limits which prevent resize requests) is AWS-specific. So it isn't part of Cluster Autoscaler's logic, the only change to override those settings would have to be in [cloud provider code](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws). Contributions are welcome :)

If you'd like to implement this, but are unsure how to do it, you can try to reach to other AWS cloud provider contributors for guidance (@sethpollack @mumoshu)

**Comment by TimJones** [comment]
I'd be happy to contribute when I have a few space cycles!

**Comment by whereisaaron** [comment]
`cluster-autoscaler` already appears to have the [functionality with `--autodiscover`](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/auto_scaling.go#L78) to discover AWS ASGs and the min/max settings at start-up. The feature here would be to periodically re-run that discovery process and either update or entirely replace state.

The workaround is a CronJob to delete the cluster-autoscaler Pod periodically (ode for a [`kubectl rolling-update`](https://github.com/kubernetes/kubernetes/issues/13488)). That way it exhibits the desired behavior to automatically discover new settings and new ASGs.
