### ISSUE TITLE
cluster-austoscaler fails to scale up but "cannot put pod ... on any node"

### ISSUE THREAD

**Issue by druskus20** [kubernetes/autoscaler#6474]
Cluster autoscaler fails to upscale the cluster, and says: ` failed to find place for monitoring/promtail-2945g: cannot put pod promtail-2945g on any node`. Inspecting the promtail deployment it says that there is no space available. 

```
I0129 10:39:36.378398       1 filter_out_schedulable.go:63] Filtering out schedulables
I0129 10:39:36.378517       1 klogx.go:87] failed to find place for monitoring/promtail-2945g: cannot put pod promtail-2945g on any node
I0129 10:39:36.378546       1 filter_out_schedulable.go:120] 0 pods marked as unschedulable can be scheduled.
I0129 10:39:36.378559       1 filter_out_schedulable.go:83] No schedulable pods
I0129 10:39:36.378564       1 filter_out_daemon_sets.go:40] Filtering out daemon set pods
I0129 10:39:36.378568       1 filter_out_daemon_sets.go:49] Filtered out 1 daemon set pods, 0 unschedulable pods left
I0129 10:39:36.378607       1 static_autoscaler.go:547] No unschedulable pods
I0129 10:39:36.378624       1 static_autoscaler.go:570] Calculating unneeded nodes
I0129 10:39:36.378642       1 pre_filtering_processor.go:67] Skipping ip-.....eu-central-1.compute.internal - node group min size reached (current: 1, min: 1)
I0129 10:39:36.378685       1 eligibility.go:104] Scale-down calculation: ignoring 2 nodes unremovable in the last 5m0s
I0129 10:39:36.378742       1 static_autoscaler.go:617] Scale down status: lastScaleUpTime=2024-01-26 11:45:22.131922634 +0000 UTC m=+178766.264966769 lastScaleDownDeleteTime=2024-01-26 12:16:23.326990628 +0000 UTC m=+180627.460034760 lastScaleDownFailTime=2024-01-24 09:06:15.171872009 +0000 UTC m=-3580.695083854 scaleDownForbidden=false scaleDownInCooldown=false
I0129 10:39:36.378778       1 static_autoscaler.go:642] Starting scale down
I0129 10:39:46.396938       1 static_autoscaler.go:287] Starting main loop
```

The issue is probably not limited to promtail.

Promtail deployment:
```
NAMESPACE     NAME                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
monitoring    promtail               3         3         2       3            2           <none>                     2d22h
```

After that, I scaled up the nodegroup size on aws to `desired=desired+1`. This works, the pod gets scheduled, but soon after cluster-autoscaler downsized the cluster by one, and the promtail begins to error again.

```
I0129 10:49:09.386954       1 filter_out_schedulable.go:63] Filtering out schedulables
I0129 10:49:09.387112       1 klogx.go:87] failed to find place for monitoring/promtail-2945g: cannot put pod promtail-2945g on any node
I0129 10:49:09.387128       1 filter_out_schedulable.go:120] 0 pods marked as unschedulable can be scheduled.
I0129 10:49:09.387142       1 filter_out_schedulable.go:83] No schedulable pods
I0129 10:49:09.387150       1 filter_out_daemon_sets.go:40] Filtering out daemon set pods
I0129 10:49:09.387157       1 filter_out_daemon_sets.go:49] Filtered out 1 daemon set pods, 0 unschedulable pods left
I0129 10:49:09.387183       1 static_autoscaler.go:547] No unschedulable pods
I0129 10:49:09.387206       1 static_autoscaler.go:570] Calculating unneeded nodes
...
I0129 10:49:09.387315       1 eligibility.go:104] Scale-down calculation: ignoring 2 nodes unremovable in the last 5m0s
I0129 10:49:09.387331       1 cluster.go:155] ip-10-0-5-200.eu-central-1.compute.internal for removal
I0129 10:49:09.387377       1 cluster.go:178] node ip-....eu-central-1.compute.internal may be removed
I0129 10:49:09.387393       1 nodes.go:84] ip-....eu-central-1.compute.internal is unneeded since 2024-01-29 10:40:16.518981056 +0000 UTC m=+434060.652025191 duration 8m52.866617551s
I0129 10:49:09.387438       1 static_autoscaler.go:617] Scale down status: lastScaleUpTime=2024-01-26 11:45:22.131922634 +0000 UTC m=+178766.264966769 lastScaleDownDeleteTime=2024-01-26 12:16:23.326990628 +0000 UTC m=+180627.460034760 lastScaleDownFailTime=2024-01-24 09:06:15.171872009 +0000 UTC m=-3580.695083854 scaleDownForbidden=false scaleDownInCooldown=false
I0129 10:49:09.387471       1 static_autoscaler.go:642] Starting scale down
I0129 10:49:09.387496       1 nodes.go:126] ip-.....eu-central-1.compute.internal was unneeded for 8m52.866617551s
I0129 10:49:19.405346       1 static_autoscaler.go:287] Starting main loop
I0129 10:49:19.405429       1 auto_scaling_groups.go:393] Regenerating instance to ASG map for ASG names: []
I0129 10:49:19.405459       1 auto_scaling_groups.go:400] Regenerating instance to ASG map for ASG tags: map[k8s.io/cluster-autoscaler/elk-cloud: k8s.io/cluster-autoscaler/enabled:]
I0129 10:49:19.524372       1 auto_scaling_groups.go:142] Updating ASG eks-eks_nodes_one-....
I0129 10:49:19.524410       1 aws_wrapper.go:703] 0 launch configurations to query
I0129 10:49:19.524416       1 aws_wrapper.go:704] 0 launch templates to query
I0129 10:49:19.524423       1 aws_wrapper.go:724] Successfully queried 0 launch configurations
I0129 10:49:19.524429       1 aws_wrapper.go:735] Successfully queried 0 launch templates
I0129 10:49:19.524436       1 aws_wrapper.go:746] Successfully queried instance requirements for 0 ASGs
I0129 10:49:19.524448       1 aws_manager.go:130] Refreshed ASG list, next refresh after 2024-01-29 10:50:19.524444186 +0000 UTC m=+434663.657488332
I0129 10:49:19.525846       1 aws_manager.go:186] Found multiple availability zones for ASG "eks-eks_nodes_other...."; using eu-central-1a for failure-domain.beta.kubernetes.io/zone label
```

**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

ca helm: 9.34.1
Promtail helm 6.9.3

Component version:

registry.k8s.io/autoscaling/cluster-autoscaler:v1.28.2
docker.io/grafana/promtail:2.7.4
argocd

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.8-eks-8cb36c9", GitCommit:"fca3a8722c88c4dba573a903712a6feaf3c40a51", GitTreeState:"clean", BuildDate:"2023-11-22T21:52:13Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

EKS

**What did you expect to happen?**:

I expected the number of nodes to scale from 3 to 4 in order to schedule promtail.
After manually applying the scale up instead, I expected it to remain at the set size.

**What happened instead?**:

* CA did not scale up the nodegroup.
* After manually scaling up the nodegroup, CA scaled down the cluster again.

**Anything else we need to know?**:

* The nodegroup is always within min/max.
* Scale down works normally.

**Comment by dkbhadeshiya** [comment]
We are facing the same issue with v1.29.0

**Comment by kushthedude** [comment]
/remove-lifecycle stale
 
 Is there any update here? This is making autoscaler pretty much irrelevant for us too

**Comment by ozzieba** [comment]
by default promtail [installs](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L15) a DaemonSet rather than a Deploy, is that what you're doing? Daemonsets are generally ignored by Cluster Autoscaler

**Comment by druskus20** [comment]
> by default promtail [installs](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L15) a DaemonSet rather than a Deploy, is that what you're doing? Daemonsets are generally ignored by Cluster Autoscaler

It has been a while and I don't have access to the same environment anymore. However, yes, I am pretty sure It was a daemonset indeed

**Comment by kushthedude** [comment]
We can close it; we have moved to karpenter for now. Maybe if anyone else
faces this we can reopen it.
