### ISSUE TITLE
Deployed cluster autoscaler with 3 replica in our aws cloud,facing leader elect lock issue

### ISSUE THREAD

**Issue by Lokeshmaxi** [kubernetes/autoscaler#6503]
Deployed cluster autoscaler with 3 replica in our aws cloud,facing leader elect lock issue, we need to run cluster autoscaler as HA , i need to know whether cluster-autoscaler work ,when replica configured to more than 1? what is the best practice to run cluster-autoscaler as   HA?

**Comment by psychic-spoon** [comment]
Yes, cluster autoscaler works as HA. If it is configured to have 3 replica, then two pods would be in 
`lock is held by cluster-autoscaler-xxxxxx and has not yet expired                                                                                      |leaderelection.go:255] failed to acquire lease cluster/cluster-autoscaler`

Better to post the logs related to the lock issue.
