### ISSUE TITLE
VPA already offering v1

### ISSUE THREAD

**Issue by deshab** [kubernetes/autoscaler#6519]
**Which component are you using?**:
VPA

VPA
**What version of the component are you using?**:
apiVersion: autoscaling.k8s.io/v1

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.28.4
</pre></details>

**What environment is this in?**:
PROD

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by deshab** [comment]
apiVersion: autoscaling.k8s.io/v1 is it still BETA, as not finding documents in official k8s doc.

**Comment by sftim** [comment]
This might be more of a documentation bug.
