### ISSUE TITLE
GKE chooses to scale up more expensive spot N2D pool instead of a cheaper spot T2D pool

### ISSUE THREAD

**Issue by gdubicki** [kubernetes/autoscaler#6536]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

I don't know, it's GKE-managed

**What k8s version are you using (`kubectl version`)?**:

<pre>
$ kubectl version
Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-gke.1217000
</pre>

**What environment is this in?**:

GKE

**What did you expect to happen?**:

I had 2 node pools, both of the spot instances, n2d-standard-32 and t2d-standard-32, and workloads that can run on both of them.

When a pool scale-up was needed I expected it would be done for the t2d pool as these instances are cheaper.

**What happened instead?**:

The more expensive n2d pool was scaled up.

**How to reproduce it (as minimally and precisely as possible)**:

I haven't tried to reproduce it, I've just seen it in production.

**Anything else we need to know?**:

I have taken a glance at how the pricing is being compared by the autoscaler and it seems that it is doomed to often be mistaken this way because of the hard-coded, rarely-updated, non-region-specific prices.

Because the [spot prices may change even monthly in GCP now](https://cloud.google.com/spot-vms/pricing) and are highly region-specific, I don't think it's a good approach.

In my case, for us-west1, according to the code t2d spot is 140% more expensive than the n2d spot, while in reality is about 17% cheaper...

See [this Google Sheet](https://docs.google.com/spreadsheets/d/1Wfc9Uw5fES15xycon9-uVNPjNoQw-8d4KYvw3UoaD8c/edit?usp=sharing) for the details.

**Comment by gdubicki** [comment]
I think that the autoscaler should either the current prices using some GCP API or you should consider introducing a solution similar to the CI/CD in https://github.com/Cyclenerd/google-cloud-compute-machine-types to keep up-to-date prices in the code.

**Comment by gdubicki** [comment]
I am interested in contributing some code for this, but I would need to know what solution would be accepted first.

**Comment by Bryce-Soghigian** [comment]
Would be interesting to see if we can bake in pricing providers similar to that of karpenter. Karpenter pricing providers follow two standards. 
1. Live Pricing data 
2. CodeGen static pricing cases in the case of live pricing data failure. 

See Karpenter pricing providers for inspiration:
https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/pricing/pricing.go#L38
https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/pricing/pricing.go#L45

**Comment by gdubicki** [comment]
I guess that https://github.com/cloudpilot-ai/karpenter-provider-gcp will sooner become a solution to this problem than Cluster Autoscaler.

**Comment by gdubicki** [comment]
It seems this is the way to achieve my goal now in GKE: https://cloud.google.com/blog/products/containers-kubernetes/introducing-new-gke-custom-compute-class-api
