### ISSUE TITLE
License Scan and Findings 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/autoscaler#6538]
kubernetes-2024-01-03.zip/autoscaler/addon-resizer/vendor/[github.com/hashicorp/golang-lru/LICENSE](http://github.com/hashicorp/golang-lru/LICENSE)

This code is under the MPL-2.0 license which is weak copyleft. Be sure that it is used only as dynamic libraries, to be safe if it's not required remove it from your repo.

Like https://github.com/kubernetes/kubernetes/blob/master/hack/unwanted-dependencies.json

**Comment by jeffcshapiro** [comment]
Per Bob Killen @mrbobbytables
This has been granted a license exception approval:

[github.com/hashicopr/golang-lru](http://github.com/hashicopr/golang-lru) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2019-03-11
