### ISSUE TITLE
cluster-autoscaler tests broken by missing dependency

### ISSUE THREAD

**Issue by rvkubiak** [kubernetes/autoscaler#655]
I've been working on build automation for the cluster-autoscaler, so I believe this was broken fairly recently.  I have a build result from 2 days ago where the tests passed as expected.

Today, if I try to run 'make test-in-docker' for cluster-autoscaler it fails.  It seems like this is probably related to the recent change away from ubuntu-slim.
https://github.com/kubernetes/autoscaler/commit/8070f370239526e5e75166fc612454b24d63a55f#diff-c414d0c9ddb3d63d0f645e12211318af

~/autoscaler-broken/cluster-autoscaler$ make test-in-docker
rm -f cluster-autoscaler
docker build -t autoscaling-builder ../builder
Sending build context to Docker daemon  3.584kB
Step 1/8 : FROM golang:1.8.3
 ---> 7e62a8729fa7
Step 2/8 : LABEL maintainer "Marcin Wielgus <mwielgus@google.com>"
 ---> Using cache
 ---> 00d9b65460cf
Step 3/8 : ENV GOPATH /gopath/
 ---> Using cache
 ---> 8cf7b9d9dfbf
Step 4/8 : ENV PATH $GOPATH/bin:$PATH
 ---> Using cache
 ---> 4e8a44b814d2
Step 5/8 : RUN go version
 ---> Using cache
 ---> a9270542558d
Step 6/8 : RUN go get github.com/tools/godep
 ---> Using cache
 ---> 86671c0a4972
Step 7/8 : RUN godep version
 ---> Using cache
 ---> ebf2c59b5d4f
Step 8/8 : CMD /bin/bash
 ---> Using cache
 ---> 3a50faf81849
Successfully built 3a50faf81849
Successfully tagged autoscaling-builder:latest
docker run -v `pwd`:/gopath/src/k8s.io/autoscaler/cluster-autoscaler/ autoscaling-builder:latest bash -c 'cd /gopath/src/k8s.io/autoscaler/cluster-autoscaler && godep go test ./... '
# k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/seccomp/libseccomp-golang
vendor/github.com/seccomp/libseccomp-golang/seccomp.go:25:22: fatal error: seccomp.h: No such file or directory
 // #include <seccomp.h>
                      ^
compilation terminated.
<snip>
godep: go exit status 2
Makefile:52: recipe for target 'test-in-docker' failed
make: *** [test-in-docker] Error 1

**Comment by aleksandra-malinowska** [comment]
Oops, it was indeed broken by that change. Thanks for catching it so quickly! #656 should fix it.

Perhaps we could include running unit tests in Docker in our presubmit to avoid it happening in the future. @mwieglus WDYT?

**Comment by mwielgus** [comment]
#661 Fixes the issue.
