### ISSUE TITLE
Cluster autoscaler 1.29.0 minSize not respected

### ISSUE THREAD

**Issue by schlichtanders** [kubernetes/autoscaler#6564]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
1.29.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1+k3s2
</pre></details>

**What environment is this in?**:

Hetzner

**What did you expect to happen?**:
When configuring autoscaler to have minSize, I expect the nodegroup to get at least as many nodes.

**What happened instead?**:

It stays at 0 nodes. 

**How to reproduce it (as minimally and precisely as possible)**:

I already had a cluster where I changed the minimum from 0 to 1 and nothing happens.
The easiest way to set a cluster on hetzner is to use [kube-hetzner](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner)

**Anything else we need to know?**:

The logs only show logs about down scaling tries.

**Comment by apricote** [comment]
@schlichtanders Did the mentioned flag solve your issue?

**Comment by schlichtanders** [comment]
Thank you apricote for pinging. The issue indeed got resolved, but if I am right, it was a more complex problem where the upscaling failed because the deployment of the autoscaler failed. Thank you for your help and hope that it may help others in similar situations as well.

Closing as this is no longer a problem for me.
