### ISSUE TITLE
Wrong CPU utilization with --ignore-daemonsets-utilization=true

### ISSUE THREAD

**Issue by AnhQKatalon** [kubernetes/autoscaler#6576]
**Which component are you using?**: Cluster Autoscaler

**What version of the component are you using?**: v1.27.2

Component version:

**What k8s version are you using (`kubectl version`)?**: EKS 1.27

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: EKS

**What did you expect to happen?**: CPU utilization is around 0.52

**What happened instead?**: Node A is not suitable for removal - cpu utilization too big (0.709220)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Hello all,

Currently, I am using Cluster Autoscaler for our EKS Cluster. I have just noticed that the log showing the CPU utilization for my nodes does not seem correct.

I have turned on the option `--ignore-daemonsets-utilization=true`, but it seems the CPU utilization still includes it. Below is the information of my node
![image](https://github.com/kubernetes/autoscaler/assets/115980474/86cc75a7-c958-4244-b7ec-16092e3dc921)
<img width="604" alt="image" src="https://github.com/kubernetes/autoscaler/assets/115980474/3c89f30a-0f9b-4035-a771-62ed98e6100c">

Only the final pod is created from the Deployment. All the other pods are from Deamonsets. So from the [FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-down-work), I expect the CPU utilization is calculated by 
`(CPU requests not include Daemonset's Pod) / (CPU Allocatable) = 1000 / 1930 = 0.51`

But from the cluster-autoscaler pod log, it outputs the following information:
`Node XXX is not suitable for removal - cpu utilization too big (0.709220)`

I am not sure how the number `0.709220` is calculated. Below is the command from the autoscaler pod
```
./cluster-autoscaler --cloud-provider=aws --namespace=kube-system --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/eks-cluster-prod --balance-similar-node-groups=false --cordon-node-before-terminating=true --daemonset-eviction-for-empty-nodes=true --daemonset-eviction-for-occupied-nodes=true --ignore-daemonsets-utilization=true --ignore-mirror-pods-utilization=true --logtostderr=true --max-graceful-termination-sec=1200 --scale-down-delay-after-add=5m --scale-down-enabled=true --scale-down-unneeded-time=10m --scale-down-utilization-threshold=0.2 --skip-nodes-with-custom-controller-pods=false --skip-nodes-with-local-storage=false --status-config-map-name=cluster-autoscaler-status --stderrthreshold=info --v=4 --write-status-configmap=true
```

Appreciate your help so much on this case

**Comment by daimaxiaxie** [comment]
In the code, the utilization calculation is like this: `(CPU requests not include Daemonset's Pod) / (CPU Allocatable - daemonset's pod requests)`
https://github.com/kubernetes/autoscaler/blob/c96aa9b97087603cb6884e1af7c20fa2969fb86d/cluster-autoscaler/simulator/utilization/info.go#L125
