### ISSUE TITLE
Unable to monitor etcd-cluster pods managed by etcd-operator

### ISSUE THREAD

**Issue by deepakzac** [kubernetes/autoscaler#6591]
**Which component are you using?**:

vertical-pod-autoscaler
**What version of the component are you using?**:
VPA version 1.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.27.0
Kustomize Version: v5.0.1
Server Version: v1.26.3
</pre></details>

**What environment is this in?**:
On Prem

**What did you expect to happen?**:
VPA is successfully created and provides recommendation for etcd-cluster service

**What happened instead?**:
See the below error
```
❯ kubectl describe vpa -A
Name:         custom-etcd-cluster
Namespace:    cm
Labels:       <none>
Annotations:  <none>
API Version:  autoscaling.k8s.io/v1
Kind:         VerticalPodAutoscaler
Metadata:
  Creation Timestamp:  2024-03-06T15:36:21Z
  Generation:          1
  Resource Version:    694859
  UID:                 11a87626-17fa-49bc-a68a-84850823fbff
Spec:
  Target Ref:
    API Version:  etcd.database.coreos.com/v1beta2
    Kind:         EtcdCluster
    Name:         etcd-cluster
  Update Policy:
    Update Mode:  Off
Status:
  Conditions:
    Last Transition Time:  2024-03-06T15:36:29Z
    Message:               Cannot read targetRef. Reason: Unhandled targetRef etcd.database.coreos.com/v1beta2 / EtcdCluster / etcd-cluster, last error etcdclusters.etcd.database.coreos.com "etcd-cluster" not found
    Status:                True
    Type:                  ConfigUnsupported
<truncated for brevity>



❯ kubectl get etcdclusters.etcd.database.coreos.com -n cm etcd-cluster
NAME           AGE
etcd-cluster   24h

❯ kubectl describe etcdclusters.etcd.database.coreos.com -n cm etcd-cluster
Name:         etcd-cluster
Namespace:    cm
Labels:       app=etcd
          
API Version:  etcd.database.coreos.com/v1beta2
Kind:         EtcdCluster
<truncated for brevity>
  Members:
    Ready:
      etcd-cluster-9zqk8rj9mn
      etcd-cluster-ftzgrjtfj5
      etcd-cluster-lsvstvspn4
  Phase:           Running
  Service Name:    etcd-cluster-client
  Size:            3
  Target Version:
Events:            <none>
<truncated for brevity>

```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by voelzmo** [comment]
Hey @deepakzac, thanks for the detailed description!

I can see that you're using a CRD to manage your etcd cluster. Similar to the Horizontal Pod Autoscaler, the VPA [has some requirements for autoscaling custom resources](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#how-can-i-apply-vpa-to-my-custom-resource), namely it needs the `/scale` subresource.

Looking at the CRD's name, I'm wondering if you are using the [CoreOS etcd operator](https://github.com/coreos/etcd-operator)? Given that the project is archived for a few years already, this seems not like a good idea. You might want to switch to an alternative, which hopefully also supports the `/scale` subresource, such as https://github.com/gardener/etcd-druid or find a different way to provide a managed etcd solution.

I'm closing this for now, feel free to re-open with additional information if I'm getting things wrong here!

/remove-kind bug
/kind support
/close

**Comment by deepakzac** [comment]
@voelzmo Thank you for the quick response and the pointer to the FAQ. I missed that. Makes sense.
And yes, we are using the operator from CoreOS.
