### ISSUE TITLE
deamonset/per-node resource correction

### ISSUE THREAD

**Issue by bmiguel-teixeira** [kubernetes/autoscaler#6608]
**Which component are you using?**:
vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Currently, the VPA targets the average utilization of resources. Even for daemon sets the same logic is applied.

Deamonsets are special in the sense that their resource consumption is usually tied to what is running on that particular node. (ex: log collectors, scanners, metrics collectors etc). This resource consumption usually varies by a large margin per-node. Some nodes may have bootstrapped a while ago and are empty-ish, while some other nodes may be under load. Some nodes (on diff pools) may be different profiles.

**Describe the solution you'd like.**:
When enabling VPA in a daemonset application, id like to have an option (or operation mode) to toggle VPA to calculate & update resources on a per-node basis.

Instead of averaging all the pods together, it would analyze pod by pod (one in each node for daemonset) and update those pods as needed.

**Describe any alternative solutions you've considered.**:
N/A

**Additional context.**:
Taken into account that VPA already handles evictions & mutations, I believe the work would be focused on calculating resource utilization on a per-node basis (for daemonsets). Rest of the logic would mostly stay in-place and be re-used.

Is there something similar already proposed or being discussed? 

Ty

**Comment by alvaroaleman** [comment]
This seems to be a duplicate https://github.com/kubernetes/autoscaler/issues/5928
