### ISSUE TITLE
Kubernetes VPA Recommendation providing same value for Lower, Upper and Target Bound

### ISSUE THREAD

**Issue by arjunchatla88** [kubernetes/autoscaler#6612]
I have implemented the Vertical Pod Autoscaler in the non-production environment. Upon executing the 'kubectl -n namespace describe verticalpodautoscaler name' command, I've observed consistent values listed under recommendations. This observation persists across multiple namespaces where I conducted tests. Although the CPU and memory values vary for each deployment, the lower, upper, and target values remain unchanged. I'm seeking guidance on any additional steps required to address this issue. Your input would be greatly appreciated 

Recommendation:
    Container Recommendations:
      Container Name:  sonarqube
      Lower Bound:
        Cpu:     25m
        Memory:  262144k
      Target:
        Cpu:     25m
        Memory:  262144k
      Uncapped Target:
        Cpu:     25m
        Memory:  262144k
      Upper Bound:
        Cpu:     25m
        Memory:  262144k

**Comment by arjunchatla88** [comment]
I have resolved the issue after installing the metric server which was missing from the Kubernetes cluster. But now the recommendation has insanely high memory values for upper bound. The resource quota is set to 24 Gi . Please advise 

Lower Bound:
        Cpu:     12m
        Memory:  1570771403
      Target:
        Cpu:     12m
        Memory:  1836551791
      Uncapped Target:
        Cpu:     12m
        Memory:  1836551791
      Upper Bound:
        Cpu:           265m
        Memory:        44400413041

**Comment by suresh-mahawar** [comment]
I am facing the same issue
>But now the recommendation has insanely high memory values for upper bound

**Comment by voelzmo** [comment]
The "upper bound" is not a recommendation for a memory value that you should be using. It is part of how VPA works to determine if the currently set requests are "different enough" from the new recommendation, the "target".
The reason why you're seeing so high "upper bound" values is that the vpa-recommender multiplies with a huge uncertainty factor if it saw only a very small number of measurements. This is to avoid accidental downscaling, which can lead to real problems, especially for memory.

The "lower bound" converges much faster, as accidental upscaling shouldn't cause problems for your workload, but will "just" cost you some money.

The relevant pieces in the code are [here](https://github.com/kubernetes/autoscaler/blob/b3a501cbe11e46bea1f8879d39c8436ef03e7139/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L118-L143), if you care about the nitty gritty details and how fast each of the bounds converge.

I'm closing this for now, if you encounter any additional issues, feel free to re-open this issue.

/area support
/close
