### ISSUE TITLE
Backport PR #6245 to 1.26, 1.27 and 1.28 branches

### ISSUE THREAD

**Issue by lyoung-confluent** [kubernetes/autoscaler#6620]
I would like to backport @alexanderConstantinescu's fix from https://github.com/kubernetes/autoscaler/pull/6245 to previous `cluster-autoscaler` minor versions, ideally starting from back in `1.24` when the issue/regression was first introduced.

**Comment by lyoung-confluent** [comment]
Per [this comment](https://github.com/kubernetes/autoscaler/issues/6467#issuecomment-1909487495) only the last 3 minor releases are supports which means v1.26, v1.27, v1.28. As such, I have opened backport PRs only for these versions:
* https://github.com/kubernetes/autoscaler/pull/6621
* https://github.com/kubernetes/autoscaler/pull/6622
* https://github.com/kubernetes/autoscaler/pull/6623

FYI I did have to resolve a small merge conflict on the v1.26 branch to apply the commit.

**Comment by gjtempleton** [comment]
Beat me to it on the only supporting back to 1.26 (and the next release of that will be the last patch release for 1.26).

**Comment by lyoung-confluent** [comment]
Looks like each of the PRs have passed tests/linting
