### ISSUE TITLE
Cluster Autoscaler Patch Releases March 2024

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#6626]
I'm planning to cut new Cluster Autoscaler patch releases for 1.26-29 at the end of this week/start of next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

We missed the promotion of 1.26.7, 1.27.6, 1.28.3, and 1.29.1 in the [January release cycle](#6424), but will be promoting these images which were published to the staging repo 6 weeks ago at the same time.

This will now be the last round of patches for 1.26.

Tagging cloud provider owners for visibility:
@4ND3R50N
@7fELF
@alphajc
@andrewsykim
@Andrius521
@apricote
@ArturasRa
@arunmk
@avorima
@BigDarkClown
@cprivitere
@ctrox
@davidjumani
@dbonfigli
@deitch
@detiber
@displague
@d-mo
@dougsong
@drmorr0
@ellistarn
@elmiko
@enxebre
@ericrrath
@feiskyer
@gajicdev
@gandhipr
@gjtempleton
@happytreees
@hardikdr
@hello2mao
@jackfrancis
@jayantjain93
@jaypipes
@Jeffwan
@jlamillan
@johnl
@jtherin
@kevin-wangzefeng
@LKaemmerling
@louisportay
@MaciekPytel
@marwanad
@MorrisLaw
@mrajashree
@NeilW
@nilo19
@optik-aper
@OriHoch
@pawelkuc

**Comment by gjtempleton** [comment]
@PhilippeChepy
@piepmatz
@pierre-emmanuelJ
@RainbowMango
@remyleone
@ringtail
@schegi
@Sh4d1
@shysank
@sohan-oracle
@tallaxes
@tghartland
@thirdeyenick
@towca
@trungng92
@vishalanarase
@v-pap
@zalmarge

**Comment by daimaxiaxie** [comment]
There are two bug fixes https://github.com/kubernetes/autoscaler/pull/6507, https://github.com/kubernetes/autoscaler/pull/6602 and a feature https://github.com/kubernetes/autoscaler/pull/6545. I hope they can be merged.

**Comment by m-barthelemy** [comment]
Would this release include a fix for this HIGH severity finding? https://github.com/kubernetes/autoscaler/issues/6279

**Comment by gjtempleton** [comment]
Short answer, unless we have information suggesting this is a high enough risk to work around the fact we vendor it from the upstream k/k repo and it's still to be patched there, no. I've put a bit more context in the original issue.

**Comment by gjtempleton** [comment]
Releases published and release notes published

/close
