### ISSUE TITLE
Support for inPlaceVerticalScaling - Timelines ??

### ISSUE THREAD

**Issue by SteveWoodTi2** [kubernetes/autoscaler#6680]
Vertical Pod Autoscaling

I've read the various issues and support tickets on this but I'm kind of wanting to know how long before VPA supports this awesome feature.    Where I currently work this would be a massive help to us.

Our use case for it is that springboot java spikes CPU on startup which leads to cpu throttling which in turn effects startup times.   Some of our services read from Kafka and we'd like to scale these to zero and use keda to scale it up when messages arrive on the topic.  If we could increase CPU and mem at startup to improve startup times and then reduce it to normal working levels after that then that could possibly lead to cost savings across our estate, well in theory.
<!--

**Comment by voelzmo** [comment]
closing as duplicate of https://github.com/kubernetes/autoscaler/issues/4016 which you can track the progress in. My gut feeling is that this will take a while, given that the feature is still in alpha state.
/close
