### ISSUE TITLE
addon-resizer build fails on `addon-resizer-release-1.8`

### ISSUE THREAD

**Issue by kumar-mallikarjuna** [kubernetes/autoscaler#6681]
**Which component are you using?**:

`addon-resizer`

**What version of the component are you using?**:

`addon-resizer-release-1.8:a2763929b4882d526ef1a67962bbe3125e8ef577`

Component version:

**What k8s version are you using (`kubectl version`)?**:

N/A

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details> N/A

**What environment is this in?**: local

**What did you expect to happen?**: Success build

**What happened instead?**: Build fails
```zsh
➜  addon-resizer git:(addon-resizer-release-1.8) ✗ make all
docker run --rm -it -v `pwd`:/go/src/k8s.io/autoscaler/addon-resizer/:Z \
        golang:1.20.10 \
        /bin/bash -c "\
            cd /go/src/k8s.io/autoscaler/addon-resizer/ && \
            go test ./nanny -v"
vendor/github.com/prometheus/common/model/labelset.go:20:2: package slices is not in GOROOT (/usr/local/go/src/slices)
note: imported by a module that requires go 1.21
make: *** [test] Error 1
```

**How to reproduce it (as minimally and precisely as possible)**:

1. Checkout `addon-resizer-release-1.8:a2763929b4882d526ef1a67962bbe3125e8ef577`
2. Run `make all`

**Anything else we need to know?**:

**Comment by Shubham82** [comment]
Closing this issue, as it was resolved by PR #6682

/close
