### ISSUE TITLE
Couldn't read config: warning: Failed to create GCE Manager

### ISSUE THREAD

**Issue by pradeeppandeyy** [kubernetes/autoscaler#669]
I0217 19:37:05.849940       5 reflector.go:236] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:144
I0217 19:37:05.850063       5 reflector.go:236] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:169
I0217 19:37:05.850162       5 reflector.go:236] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:207
I0217 19:37:05.850269       5 reflector.go:236] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:237
I0217 19:37:05.850309       5 reflector.go:236] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:259
I0217 19:37:06.044719       5 request.go:638] Throttling request took 194.371932ms, request: GET:https://172.30.0.1:443/api/v1/nodes?resourceVersion=0
I0217 19:37:06.244718       5 request.go:638] Throttling request took 378.657428ms, request: PUT:https://172.30.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
E0217 19:37:06.252461       5 gce_manager.go:71] Couldn't read config: warning:
can't store data at section "global", variable "network-project-id"
F0217 19:37:06.252509       5 cloud_provider_builder.go:65] Failed to create GCE Manager: <nil>

**Comment by MaciekPytel** [comment]
I've seen something like that a few months back (around 1.7 release I think?). It was a problem in underlying library, which would fail if it noticed an unexpected field and when a new field was added to config older CA versions started to crash. 

Can you share your kubernetes / CA version? My intuition would be that updating to newer CA version will likely solve the issue.

**Comment by pradeeppandeyy** [comment]
I was previously using gce.conf, now I have removed it and working fine. thanks
