### ISSUE TITLE
Make VPA recommender target memory percentile configurable

### ISSUE THREAD

**Issue by mKeRix** [kubernetes/autoscaler#6700]
**Which component are you using?**:

Vertical Pod Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We have some workloads that follow a pattern of settings memory requests equal to limit, to avoid unexpected pod evictions for memory reclaiming. We would like to use VPA on these deployments as well, to auto-scale both CPU and memory. VPA however currently [hardcodes](https://github.com/kubernetes/autoscaler/blob/8273c9ce0b8d556554a34e927fd430e6558547fa/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L108) the target percentile for memory to `0.9`, which in this scenario would lead to a constant underscaling of resources. This in turn leads to a somewhat regular stream of OOM kills in this scenario.

**Describe the solution you'd like.**:

In #4799 a flag was introduced to make the target percentile for CPU configurable. It would be nice to have the same kind of flag for memory too.

**Describe any alternative solutions you've considered.**:

For now, this can be worked around by ensuring that VPA-controlled applications always have a memory request-to-limit ratio of more than 1. Nonetheless, fine-tuning the VPA suggestions would give us more flexibility for how we run things.

**Additional context.**:

I'm happy to try and contribute the code changes for this, I just want to make sure that this would be in line with what the project maintainers see for the project before investing the time. Hence, I created this issue to discuss.

**Comment by voelzmo** [comment]
will be fixed by merging https://github.com/kubernetes/autoscaler/pull/6660
