### ISSUE TITLE
VPA Updater 1.1.0 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [kubernetes/autoscaler#6763]
**Which component are you using?**: `vertical pod autoscaler / updater`

**What version of the component are you using?**: `1.1.0`

Component version: `1.1.0`

**What k8s version are you using (`kubectl version`)?**: `1.29`

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: v1.29.1
Server Version: v1.29.1-eks-b9c9ed7
</pre></details>

**What environment is this in?**:

**What did you expect to happen?**: `to not panic`

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:  always occurs in larger clusters

**Anything else we need to know?**: This only appears to occur in our larger clusters with more than 50 nodes.  I've tried moving the service around and the error still persists.

**Comment by rsavage-nozominetworks** [comment]
In the meanwhile, I've downgraded back to 1.0.0, and no more issues.  There's something going on with 1.1.0 under load.

**Comment by DeanDonkov** [comment]
Observing the same error on my relatively small cluster as well.

**Comment by voelzmo** [comment]
Hey, thanks for reporting this! This has already been fixed on `master` and the `vpa-release-1.1` branch. We have released [vpa version 1.1.1](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-1.1.1) containing the fix.

/duplicates #6709
