### ISSUE TITLE
Release VPA 1.1.1

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/autoscaler#6765]
Please follow instructions in
[RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md) and note each
completed step on this issue.

Planned to be released within the next week to resolve issue fixed in https://github.com/kubernetes/autoscaler/pull/6712

/kind release

**Comment by kwiesmueller** [comment]
Images promoted: https://github.com/kubernetes/k8s.io/pull/6764

**Comment by Shubham82** [comment]
closing this issue, as it wasn't closed by the above label.

/close

Thanks!
