### ISSUE TITLE
Broken link in cluster-autoscaler FAQ.md

### ISSUE THREAD

**Issue by uucloud** [kubernetes/autoscaler#6805]
**Which component are you using?**:

cluster-autoscaler

**What did you expect to happen?**:

The document hyperlink "TLS bootstrapping process" in the ["How does scale-up work"](https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/) section of cluster-autoscaler's FAQ.md is currently leading to a 404 error. The correct address is [here](https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/).

**Comment by Shubham82** [comment]
Closing this issue, as resolved by PR #6806
/close
