### ISSUE TITLE
Implement Check-capacity Provisioning Class

### ISSUE THREAD

**Issue by yaroslava-serdiuk** [kubernetes/autoscaler#6814]
Implementation is almost done, creating an issue for visibility.

[Check-capacity Provisioning Class](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md#check-capacitykubernetesio-class) check if the ProvisioningRequest could fit in existing capacity. If yes, CA add Provisioned=True condition and reserve the capacity for 10 mins. When reservation time passes, the BookingExpired=True condition is added, which means that CA won't reserve capacity for this ProvisioningRequest.

The original proposal: [Provisioning Request CRD](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md)

**Comment by kerthcet** [comment]
As the proposal mentioned, we'll not reserve resources for check-capacity, will we now regarding to `reserve the capacity for 10 mins`?

**Comment by yaroslava-serdiuk** [comment]
> As the proposal mentioned, we'll not reserve resources for check-capacity, will we now regarding to `reserve the capacity for 10 mins`?

Good point, thanks. The original proposal suggested to not reserve the capacity, but that was reevaluated during implementation. 

So yes, if there is capacity for ProvReq in the cluster, CA adds Provisioned=True condition and reserve the capacity for 10 mins, so other ProvReqs won't be able to use it for 10 mins. Then BookinigExpired=True condition is added, which means that CA doesn't reserve capacity for this ProvReq. 
However note, the reservation happens during CA simulation, CA doesn't block scheduler from scheduling real pods. So the real pods still could be scheduled on reserved capacity. 
This reservation is aimed for ProvisioningRequest only, in order to not have situation when two ProvReqs have Provisioned=True condition, but actually only one of it could fit in the cluster.

**Comment by kerthcet** [comment]
Thanks for the explanation, but what will happen if two ProvReqs ask for capacities the same time. Will they both success or one will success and another one will failure due to the reservation fact.

**Comment by yaroslava-serdiuk** [comment]
CA process ProvReqs one by one. If we have two ProvReqs that asking the same capacity, but cluster could fulfil only one of them, then the first picked ProvReq will have Provisioning=True condition and the second ProvReq will have Provisioned=False condition. When 10 mins passes, the first ProvReq will have Provisioned=True and BookingExpired=True conditions and the second ProvReq will have Provisioned=True condition.

**Comment by yaroslava-serdiuk** [comment]
> So if I want to use ProvReq, what's the best practice, check for capacity first then sent the real provisioning request? Or the scale-up ProvReq will check the capacity as well in ahead.

Not sure what did you mean by real ProvisioningRequest. Each ProvReq belongs to a specific ProvisioningClass. ProvisioningRequest of check-capacity ProvisioningClass is aimed to check capacity in the cluster for requested resources. 
ProvisioningRequest of AtomicScaleUp (or BestEffortAtomicScaleUp) ProvisioningClass is aimed to scaleUp the cluster to fulfil request: https://github.com/kubernetes/autoscaler/issues/6815
