### ISSUE TITLE
Implement AtomicScaleUp ProvisioningClass

### ISSUE THREAD

**Issue by yaroslava-serdiuk** [kubernetes/autoscaler#6815]
The [Atomic-scale-up Provisioning Class](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/provisioning-request.md#atomic-scale-upkubernetesio-class) aims to provision the resources required for the specified pods in an atomic way.

```[tasklist]
- [x] Update API to support AtomicScaleUp (the implementation of the method is a cloud provider responsibility, if the method is not implemented, fallback to IncreaseSize)
- [x] Implement ScaleUp for Provisioning Class
- [x] Update ProvisioningRequest Injector
- [x] Update ProvisioningRequest Processor
- [x] Fix https://github.com/kubernetes/autoscaler/issues/6517
- [x] Backport to 1.30
```

**Comment by yaroslava-serdiuk** [comment]
@aleksandra-malinowska is already working on ScaleUp implementation.
/assign @aleksandra-malinowska

**Comment by aleksandra-malinowska** [comment]
@yaroslava-serdiuk regarding the 'update ProvisioningRequest injector', I assume you meant adding the new class to supported classes list. But it doesn't seem like this list isn't used anywhere (we don't validate if the request is of the supported class in injector). Is this WAI? 

I can see why we wouldn't validate classhere - we should take into account the requests that were provisioned and will cause a workload to be admitted - but I'm not sure if this was a conscious decision. LMK if I should add validation or just clean up this var.

Relevant code: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/processors/provreq/provisioning_request_injector.go#L41C5-L41C33

**Comment by yaroslava-serdiuk** [comment]
+ need to be cherry picked (can't create cherry-pick at the moment): https://github.com/kubernetes/autoscaler/pull/6873, https://github.com/kubernetes/autoscaler/pull/6880

**Comment by yaroslava-serdiuk** [comment]
cc: @x13n
