### ISSUE TITLE
VPA doesn't accept `1.2Gi` in `.spec.ResourcePolicy.MinAllowed`

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/autoscaler#6819]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 0.14.0 (provided within GKE clusters)

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.12-gke.1115000", GitCommit:"885327b7f1bebce409c843425b4688e3eeed33f4", GitTreeState:"clean", BuildDate:"2024-03-28T09:16:53Z", GoVersion:"go1.21.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:

GKE

**What did you expect to happen?**:

VPA accepts `1.2Gi` in `.spec.ResourcePolicy.MinAllowed`

**What happened instead?**:

It doesn't.

```
$ kubectl edit vpa awesome-app -n mercari

error: verticalpodautoscalers.autoscaling.k8s.io "awesome-app" could not be patched: admission webhook "gke-vpa.k8s.io" denied the request: MinAllowed: Memory [{{0 0} {0xc070473f80}  BinarySI}] must be a whole number of bytes
```

**How to reproduce it (as minimally and precisely as possible)**:

Create VPA with MinAllowed with `1.2Gi`

**Anything else we need to know?**:

**Comment by sanposhiho** [comment]
Also, I don't understand why minAllowed in this test case is "bad minAllowed memory value".
https://github.com/kubernetes/autoscaler/blob/5ecf37aec8f3e6f3530ac9bda4d956893435e2d1/vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/handler_test.go#L177-L197

**Comment by adrianmoisey** [comment]
> Also, I don't understand why minAllowed in this test case is "bad minAllowed memory value".

I think it's because the input is `100m`, where it should be `100M`

**Comment by adrianmoisey** [comment]
I can confirm that this bug exists in VPA 1.1.1.

**Comment by adrianmoisey** [comment]
It seems as though this issue is related to https://github.com/kubernetes/autoscaler/pull/4798

**Comment by sanposhiho** [comment]
> I think it's because the input is 100m, where it should be 100M

`100m` and `100M` are different and both are valid memory value.

**Comment by voelzmo** [comment]
`100m` is 100 millibytes, which is 0.1 bytes, and the VPA wants (as the error message points out) a whole number of bytes.

The case for `1.2Gi` is quite interesting, because if you convert this binary format into (decimal) bytes, you also end up with a fractional amount of bytes
```
1.2*1024*1024*1024=1288490188.8
```

My understanding is that internally k8s will also end up converting memory into decimal bytes and can only deal with whole bytes, therefore this validation ensures this. See https://github.com/kubernetes/autoscaler/issues/4774 for some context.
