### ISSUE TITLE
Cluster Autoscaler Patch Releases May 2024

### ISSUE THREAD

**Issue by BigDarkClown** [kubernetes/autoscaler#6865]
I'm planning to cut new Cluster Autoscaler patch releases for 1.27-1.30 at the end of this week/start of next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

Tagging cloud provider owners for visibility:
@4ND3R50N
@7fELF
@alphajc
@andrewsykim
@Andrius521
@apricote
@ArturasRa
@arunmk
@avorima
@BigDarkClown
@cprivitere
@ctrox
@davidjumani
@dbonfigli
@deitch
@detiber
@displague
@d-mo
@dougsong
@drmorr0
@ellistarn
@elmiko
@enxebre
@ericrrath
@feiskyer
@gajicdev
@gandhipr
@gjtempleton
@happytreees
@hardikdr
@hello2mao
@jackfrancis
@jayantjain93
@jaypipes
@Jeffwan
@jlamillan
@johnl
@jtherin
@kevin-wangzefeng
@LKaemmerling
@louisportay
@MaciekPytel
@marwanad
@MorrisLaw
@mrajashree
@NeilW
@nilo19
@optik-aper
@OriHoch
@pawelkuc
@PhilippeChepy
@piepmatz
@pierre-emmanuelJ
@RainbowMango
@remyleone
@ringtail
@schegi
@Sh4d1
@shysank
@sohan-oracle
@tallaxes
@tghartland
@thirdeyenick
@towca
@trungng92
@vishalanarase
@v-pap
@zalmarge

**Comment by BigDarkClown** [comment]
@PhilippeChepy
@piepmatz
@pierre-emmanuelJ
@RainbowMango
@remyleone
@ringtail
@schegi
@Sh4d1
@shysank
@sohan-oracle
@tallaxes
@tghartland
@thirdeyenick
@towca
@trungng92
@vishalanarase
@v-pap
@zalmarge

**Comment by apricote** [comment]
For `Hetzner` most fixes are already merged and backported already. We have one fix pending review but its not even in `main` yet, so no need to wait for it+backports: https://github.com/kubernetes/autoscaler/pull/6750
