### ISSUE TITLE
vpa: Follow Kubernetes logging guideline

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/autoscaler#6905]
**Which component are you using?**:

vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently, the logging in the VPA components does not follow the best practices and guidelines which are followed in the K8s ecosystem. VPA, as a core K8s component, should follow [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md).

For example, let's take https://github.com/kubernetes/autoscaler/blob/bd8153b59d9d0da84a9d4e9b6b34e08f89b03f26/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L220. The issues with this log are:
- It does not start with a capital letter. From [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md): "Start from a capital letter."
- It is not a structured log. See [Structured Logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging).

**Describe the solution you'd like.**:
Follow [sig-instrumentation's Logging guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md) in the VPA's codebase.

**Describe any alternative solutions you've considered.**:
N/A

**Additional context.**:
N/A

**Comment by Shubham82** [comment]
cc @voelzmo @kwiesmueller
