### ISSUE TITLE
pprof for vpa-admission-controller

### ISSUE THREAD

**Issue by huizhifan** [kubernetes/autoscaler#6946]
**Which component are you using?**:
vertical-pod-autoscaler

vpa-admission-controller
**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

In our cluster, there are 3k pods and 100-200 vpa objects with Off updateMode. Theoretically, the vpa-admission-controller is supposed to have little work load. But the memory usage goes up to 1000Mi. We want to learn why this amount of memory is consue
**Describe the solution you'd like.**:

Enable pprof in vpa-admission-controller
**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by voelzmo** [comment]
/triage accepted
/label good-first-issue

This is very relevant to issues we've seen before like https://github.com/kubernetes/autoscaler/issues/6368
