### ISSUE TITLE
Moving from 1.29 -> 1.30 using helm chart, cluster autoscaler fails with NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by zenbones** [kubernetes/autoscaler#6982]
With the cluster-autoscaler, using the helm chart (both 9.36.0 and 9.37.0), in AWS EKS, the component works fine in k8s 1.29 and fails in k8s 1.30 with...

I0626 21:53:36.018910       1 aws_manager.go:79] AWS SDK Version: 1.48.7
E0626 21:53:39.180984       1 aws_manager.go:128] Failed to regenerate ASG cache: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F0626 21:53:39.181014       1 aws_cloud_provider.go:455] Failed to create AWS Manager: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

The yaml for the autoscaler component and the aws-auth config maps are identical in both k8s versions, only the autoscaler runs fine in 1.29.

**Comment by zenbones** [comment]
Required oidc service level iam role. Solved.

**Comment by nitinjagjivan** [comment]
It worked after running annotate command:
 kubectl annotate serviceaccount cluster-autoscaler  -n kube-system eks.amazonaws.com/role-arn=arn:aws:iam::xxxxxxxxxxx:role/eksctl-eks-cluster-xxxxx-addon-iamserviceaccou-Role1-xxxxxxxxxx
 
 Also I needed to modify IAM Role trust relationship to include SA cluster-autoscaler along with the existing 'cluster-autoscaler-eks'
