### ISSUE TITLE
Which version for ARM ?

### ISSUE THREAD

**Issue by nlamirault** [kubernetes/autoscaler#699]
According to the GCR website, addon-resizer-arm tag is [2.1](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/addon-resizer-arm?gcrImageListsize=50)

On the README, it is written : 
```Currently recommended version is 1.8, on addon-resizer-release-1.8 branch.```

Where does come from the v2.1 release ? We can't use the 1.8 release on ARM ?

Thanks.

**Comment by bskiba** [comment]
@x13n
