### ISSUE TITLE
how to compile cluster-autoscaler binary

### ISSUE THREAD

**Issue by pradeeppandeyy** [kubernetes/autoscaler#701]
how to compile cluster-autoscaler binary

**Comment by feiskyer** [comment]
Clone the autoscaler codes to `$GOPATH/src/k8s.io/autoscaler`, then run
```
cd $GOPATH/src/k8s.io/autoscaler/cluster-autoscaler
make
```

**Comment by bskiba** [comment]
Thanks @feiskyer for responding! Closing.

**Comment by pradeeppandeyy** [comment]
@feiskyer Thanks, I already tried this and working well for me.
