### ISSUE TITLE
Dependabot use GO rc version

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/autoscaler#7029]
**Problem:**
Depandabot uses the Go RC version to update the Golang version for [updater](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/Dockerfile), [admission-controller](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/Dockerfile), and [recommender](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/Dockerfile) in VPA. It isn't recommended to use Golang rc version, so configure Dependabot to ignore the RC version of Go while updating the Golang version.

Ref: Here is the PR opened by Dependabot for the updater, admission-controller, and recommender to update the Golang version to the RC version:
#7000 #7001 #7002

**Proposed Solution:**
one of the solutions we can use is to use the [Ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) option in depandabot.yaml to ignore rc version.

**Comment by Shubham82** [comment]
cc @voelzmo @kwiesmueller @adrianmoisey
Your thoughts on this?

**Comment by adrianmoisey** [comment]
I'm happy with this. Those `rc` PRs are basically noise, avoiding creating them would be good.

**Comment by kwiesmueller** [comment]
Agree, we should not get those `rc` versions as suggestions.

**Comment by Shubham82** [comment]
Hi, before raising the PR, Just want to confirm whether is it correct to use `versions: [ "*.*rc*" ]` for versions options under the ignore option.
The first asterisk is for the major version.
The second asterisk is for the minor version.
The third asterisk is for different rc(release candidates) for the go version.

WDYT?

**Comment by adrianmoisey** [comment]
I think it's worth a try.
I see someone else had issues here: https://stackoverflow.com/questions/78712896/how-to-instruct-dependabot-to-ignore-pre-releases-or-release-candidate-versions

**Comment by Shubham82** [comment]
> I see someone else had issues here: https://stackoverflow.com/questions/78712896/how-to-instruct-dependabot-to-ignore-pre-releases-or-release-candidate-versions
@adrianmoisey, but `versions: ["*.*.*-rc.*"]` is used in the link you shared, in that *(third one) is used for the patch version but the release candidate is released before the actual release ( as close as possible to the actual release) so there is no need for patch release here and also instead of -rc it should be rc. (eg: go1.23rc1)

> I think it's worth a try.
Sure, is there any way to check it locally, as depandabot is a GitHub action? so only the repository owner can check this IMO.
@voelzmo @kwiesmueller

**Comment by adrianmoisey** [comment]
> @adrianmoisey, but `versions: ["*.*.*-rc.*"]` is used in the link you shared, in that *(third one) is used for the patch version but the release candidate is released before the actual release ( as close as possible to the actual release) so there is no need for patch release here and also instead of -rc it should be rc. (eg: go1.23rc1)

Correct. Those options didn't for for the person posting that post. I like your idea better

**Comment by Shubham82** [comment]
> Correct. Those options didn't for for the person posting that post. I like your idea better

Thanks for your response! I will open a PR for it, I am just waiting for the other members' views.

**Comment by Shubham82** [comment]
I will open a PR for it soon.

/assign

**Comment by Shubham82** [comment]
I have raised the PR #7084 for it.
PTAL!
