### ISSUE TITLE
No Write-up to add a Helm Repo (KWOK Provider)

### ISSUE THREAD

**Issue by network-charles** [kubernetes/autoscaler#7040]
The KWOK documentation didn't specify that a repo needs to be added before installing the charts.

**Reference**:
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/kwok#2-configure-cluster-autoscaler-to-use-kwok-cloud-provider

I'll be happy to work on this.

**Comment by Shubham82** [comment]
@network-charles, a similar issue opened #6339 to improvement for helm docs for the Kwok provider.

Please have a look, I think we can update the Kwok README.md
