### ISSUE TITLE
Decrease Size of Cluster Question

### ISSUE THREAD

**Issue by jamespinkerton** [kubernetes/autoscaler#706]
Hi. I have a quick question. If I launch a pod to kubernetes and it increases the size of the cluster and then completes, how long does it take for the cluster to shrink again? Is this configurable?

Thanks!
James

**Comment by bskiba** [comment]
Depending on some factors, it takes between 10 and 20 minutes. There are a couple of mechanisms that delay scale down. For example we wait 10 minutes after a scale up before we even start checking if scale down can happen. Also, we measure the time that the node is unneeded (underutilized) and only delete it after it has been in that state for a significant amount of time (by default 10 minutes for ready nodes, 20 minutes for a node that is unready).

These options are configurable by Cluster Autoscaler flags. You can check them together with their default values here:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/main.go#L80
 
Also note that we tend to remove the nodes one by one, which will make the process longer if you are looking to shrink the cluster by multiple nodes. If there are nodes that are completely empty (can contain deamonset pods, but no need to move any pods to other nodes), we do delete them in bulk, but if there is a need to drain the node, we only remove one at a time.

**Comment by jamespinkerton** [comment]
How does one set (change) these options when running the Kubernetes Engine?

**Comment by bskiba** [comment]
On GKE it's not configurable, only if you are running in plain GCE.

**Comment by jamespinkerton** [comment]
Thank you!
