### ISSUE TITLE
`fail to get pod controller`, due to pod created by custom controller

### ISSUE THREAD

**Issue by jacobeatsspam** [kubernetes/autoscaler#7077]
**Which component are you using?**:

Vertical Pod Autoscaler

**What version of the component are you using?**:

1.1.1

**What k8s version are you using (`kubectl version`)?**:

1.29

**What did you expect to happen?**:

I expect VPA's [`controllerfetcher`](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/vpa/api.go#L143C8-L151) to only handle pods owned by a Deployment or Statefulset.

**What happened instead?**:

VPA prints errors because it's attempting to list a pod owned by a 3rd party controller: 

```
api.go:153] fail to get pod controller: pod=argo-rollouts-dashboard-66d98c5789-% err=Unhandled targetRef argoproj.io/v1alpha1 / Rollout / argo-rollouts-dashboard
```

**How to reproduce it (as minimally and precisely as possible)**:

1) Install a 3rd party operator, such as Argo, Prometheus Operator, etc.
1) Monitor `admission-controller`'s log output. Be sure to set the highest verbosity `--v=5`.

**Comment by voelzmo** [comment]
Hey @jacobeatsspam, I think we're missing some information here:
It seems the log statement you're pasting is truncated, usually it should continue with `, last error <some error here>` ([source](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.1.1/vertical-pod-autoscaler/pkg/target/fetcher.go#L142))
Using custom resources is supported, [as long as they implement the `/scale` subresource](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#how-can-i-apply-vpa-to-my-custom-resource), and we have seen people use it for argo rollouts specifically (e.g. [here someone](https://github.com/kubernetes/autoscaler/issues/7024) has many of them and wants _native support_ for argo rollout, but it does work for them).

Maybe this is a permission problem or there is any other reason why the admission-controller cannot access the `/scale` subresource for the CRD? How did you install VPA?

In general, I would also advise you to update to [vpa release 1.1.2](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-1.1.2), as there has been an important bugfix in the vpa-updater.

/triage needs-information
