### ISSUE TITLE
Release VPA 1.2.0

### ISSUE THREAD

**Issue by raywainman** [kubernetes/autoscaler#7098]
Please follow instructions in
[RELEASE.md](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md) and note each
completed step on this issue.

Please provide any information that is related to the release:

- When we plan to do the release?

ASAP

- Are there any issues / PRs blocking the release?

No

**Comment by adrianmoisey** [comment]
\o/

**Comment by maxboone** [comment]
I see in the docs that "The current default version is Vertical Pod Autoscaler 1.1.2", and can't find any specific changelog for the 1.2.0 release, how is the compatibility?

**Comment by Shubham82** [comment]
Hi @maxboone, The VPA 1.2.0 has not been released yet, it is under process. I think we are left with the last step of release i.e. [Finalize release](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/RELEASE.md#finalize-release).

The text you mentioned above is under the [README.md](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#readme) we have to update it also(maybe after release).

@raywainman will tell better on this one. PTAL!

**Comment by ialidzhikov** [comment]
Yep, we are also waiting for the release to be finalized!

**Comment by maxboone** [comment]
Ah, mentioned it as we use a [deployment file from the master / main branch](https://raw.githubusercontent.com/kubernetes/autoscaler/master/vertical-pod-autoscaler/deploy/recommender-deployment.yaml) directly in our CI/CD, so it suddenly showed as outdated (but I thought it was released already as it popped up). That's on us!

Thanks :)

**Comment by Shubham82** [comment]
Thanks @raywainman for the information.

**Comment by ialidzhikov** [comment]
Thank you @raywainman and all other involved maintainers for driving the new release! 🎉

**Comment by huizhifan** [comment]
Hi @raywainman, what's the minimal k8s version VPA1.2.0 supports?
