### ISSUE TITLE
Cluster autoscaler more AWS  DescribeLaunchTemplateVersions due to PR-6245

### ISSUE THREAD

**Issue by linhua11** [kubernetes/autoscaler#7102]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: 1.29.2 and 1.29.4

Component version:

**What k8s version are you using (`kubectl version`)?**: 1.29

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: AWS

**What did you expect to happen?**: No increased AWS API call due to rate limit issue

**What happened instead?**:  Due to PR-6245, even if we don't use MixedInstancesPolicy.instanceRequirements since we use balacing-label and having active nodes. It still calls DescribeLaunchTemplateVersions which pushes the CA to have some rate limiting issue. And there is no way to disable this feature

**How to reproduce it (as minimally and precisely as possible)**: 
Just start a CA with balancing labels like
    - --balancing-label=xxxxx
    - --expander=least-waste
    - --aws-use-static-instance-list=true
Compare the number of aws api calls between version 1.27.6 and 1.27.7, you will find increased API calls

**Anything else we need to know?**:

**Comment by Shubham82** [comment]
/area provider/aws
/area cluster-autoscaler

Here is the PR that is mentioned in the issue description:  #6245

**Comment by rrangith** [comment]
hi @linhua11 i opened https://github.com/kubernetes/autoscaler/pull/7383 which should fix this issue

**Comment by linhua11** [comment]
@rrangith thanks for the fix
