### ISSUE TITLE
Document Azure MSI support

### ISSUE THREAD

**Issue by jcrowthe** [kubernetes/autoscaler#711]
Azure's [Managed Service Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview) is supported as an alternative to utilizing a service principal for the authorization to the backend Azure cloud provider. This is a request to support MSI in the Azure autoscaler in addition to the current service principal.

If accepted, this task would be added to this list: https://github.com/kubernetes/autoscaler/issues/449

**Comment by feiskyer** [comment]
@jcrowthe This has been already supported by "useManagedIdentityExtension", but it is not documented yet

**Comment by jcrowthe** [comment]
@feiskyer Excellent, thank you for pointing that out! I'll likely try this out tomorrow and submit a PR with some documentation. I'll keep you posted. Thanks!

**Comment by feiskyer** [comment]
@jcrowthe thanks

**Comment by jcrowthe** [comment]
@feiskyer I'm seeing your commit [here](https://github.com/kubernetes/autoscaler/commit/59b0087eeb3333657835e4a64fbf21cbbdbdad4a#diff-260f9ffb803a074dcf5da1b73734869f) on Dec 27, 2017, but this is not in the latest release, v1.1.2.

I am unfamiliar with the release schedule, and I see that v1.1.2 shows
> This branch is 16 commits ahead, 334 commits behind master.

Do we have an ETA on when this will be rolled into a release?

**Comment by feiskyer** [comment]
@jcrowthe Sorry, I didn't notice this problem.

@mwielgus @MaciekPytel CA 1.1.2 still doesn't include recent Azure changes. Its commits are still four months ago. When will recent Azure changes included in CA?

**Comment by jcrowthe** [comment]
@feiskyer I saw the v1.2.0 was cut a few days ago, and just got to looking at this now. After some trial and error, and reading through the code, here is the current progress:
1. [this function](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.2/cluster-autoscaler/cloudprovider/azure/azure_util.go#L381-L406) doesn't account for MSI. In order to get around this, all variables checked need to be set to something other than empty string. This probably needs another if statement here.
1. the managed identity file needs to be mounted into the pod (this is just for documentation):
```
...
        volumeMounts:
        - mountPath: /var/lib/waagent/ManagedIdentity-Settings
          name: managed-identity
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /var/lib/waagent/ManagedIdentity-Settings
          type: ""
        name: managed-identity
...
```

After doing these, however, I get blocked by an error:
```
...
I0326 22:13:34.933110       1 cloud_provider_builder.go:72] Building azure cloud provider.
I0326 22:13:34.933133       1 cloud_provider_builder.go:158] Creating Azure Manager with default configuration.
I0326 22:13:34.933231       1 azure_manager.go:152] Starting azure manager with subscription ID "<id>"
I0326 22:13:34.933312       1 azure_client.go:100] azure: using managed identity extension to retrieve access token
F0326 22:21:05.330895       1 cloud_provider_builder.go:162] Failed to create Azure Manager: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/.../virtualMachines?api-version=2017-03-30: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post http://localhost:50343/oauth2/token?api-version=1.0: dial tcp [::1]:50343: getsockopt: connection refused'
```
I'm intrigued as to why it is attempting to dial an ipv6 address for localhost? Looking at the host with netstat, only the ipv4 localhost address is being listened on, so it makes sense that it is getting a connection refused:
```
tcp        0      0 127.0.0.1:50343         0.0.0.0:*               LISTEN      1537/msi-extension
```

Would you be able to point me in the right direction?

**Comment by feiskyer** [comment]
@jcrowthe hostNetwork should be used to access localhost on the Node

**Comment by jcrowthe** [comment]
@feiskyer Thanks for your help here. Currently I have to create dummy values for the AAD variables, as previously mentioned. Would you like me to submit a PR to document MSI as it currently stands, including these dummy variables? Or should we fix that validation function first?

**Comment by feiskyer** [comment]
@jcrowthe Yep, will fix this next week
