### ISSUE TITLE
VPA vpa-up.sh installation of admission controller is broken

### ISSUE THREAD

**Issue by antweiss** [kubernetes/autoscaler#7140]
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

1.2.0 installed from master

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2+k3s2

</pre></details>

**What did you expect to happen?**:

Admission controller to run 

**What happened instead?**:

admission controller varsion 1.1.2 is installed instead of 1.2.0 
which leads to an error:

  Normal   Pulled     14s                kubelet            Successfully pulled image "registry.k8s.io/autoscaling/vpa-admission-controller:1.1.2" in 492ms (492ms including waiting). Image size: 23699891 bytes.
  Warning  BackOff    1s (x4 over 27s)   kubelet            Back-off restarting failed container admission-controller in pod vpa-admission-controller-5477857485-pwfbs_kube-system(94551eb7-1271-46ae-bee7-29c86fe7fc55)

kubectl logs -n kube-system vpa-admission-controller-5477857485-pwfbs
unknown flag: --reload-cert

**How to reproduce it (as minimally and precisely as possible)**:

Just run hack/vpa-up.sh

**Anything else we need to know?**:

The cuplrit is that admission controller image ins in wrong version (1.1.2 instead of 1.2.0) in the deployment yaml in the released tag.
Caused by this line: https://github.com/kubernetes/autoscaler/blob/dbc88c0a4dc4c53342f7b90cba8c5587e3cae4bf/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml#L23

**Comment by Shubham82** [comment]
@antweiss, it is now 1.2.0, See the following [admission-controller-deployment.yaml](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml) file on master:
https://github.com/kubernetes/autoscaler/blob/cc6ddad1539e9a57ada158d945af3d3cbf2a037e/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml#L23

I think you are not using the master branch. Please check.

**Comment by antweiss** [comment]
From what I see the vpa-up.sh script checks out the tag.

Anton Weiss
http://otomato.io

**Comment by antweiss** [comment]
Here: https://github.com/kubernetes/autoscaler/blob/cc6ddad1539e9a57ada158d945af3d3cbf2a037e/vertical-pod-autoscaler/hack/vpa-up.sh#L26

**Comment by Shubham82** [comment]
Hi @antweiss, The value for `DEFAULT_TAG` is now configured to 1.2.0 in the vpa-up.sh
see this:
https://github.com/kubernetes/autoscaler/blob/cc6ddad1539e9a57ada158d945af3d3cbf2a037e/vertical-pod-autoscaler/hack/vpa-up.sh#L22

The following PR #7130 made the changes. Maybe you have to update your master branch with the upstream master branch (latest).
I hope this will help you.

**Comment by antweiss** [comment]
Hi @Shubham82 . It's still broken because the image tag in the deployment yaml that's in vertical-pod-autoscaler-1.2.0 tag is set to 1.1.2: https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.2.0/vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml

You can verify for yourself in this Killercoda scenario I built: https://killercoda.com/antweiss/scenario/vpa

**Comment by Shubham82** [comment]
@antweiss,  you are using the `vertical-pod-autoscaler-1.2.0` release branch, I think we missed updating the VPA version to 1.2.0 in the `vertical-pod-autoscaler-1.2.0` release branch.
I will open a PR for it soon.

Thanks!

**Comment by Shubham82** [comment]
@antweiss there is some issue, `vertical-pod-autoscaler-1.2.0` is a tag, not the branch, the branch is the `vpa-release-1.2` for VPA 1.2.0
See this:
https://github.com/kubernetes/autoscaler/tree/vpa-release-1.2/vertical-pod-autoscaler

I didn't see it previously. we updated the VPA version to 1.2.0 for the `vpa-release-1.2` branch, please check and use that one. (only left with README.md file)

cc @raywainman, is there any way we can update the VPA version under the tag  `vertical-pod-autoscaler-1.2.0`?

I hope this will resolve your issue.

**Comment by antweiss** [comment]
You can move the tag to point to the commit with the fix.

Anton Weiss
http://otomato.io

**Comment by Shubham82** [comment]
> Gah sorry team - I thought I checked this path via the e2e tests but I likely missed this.
> 
> I'll ask leads to update the tag to make sure the manifest changes are included.
> 
> Will ping this bug when it's done.

Thanks @raywainman

**Comment by antweiss** [comment]
sure, thanks, wasn't looking for a quick fix - just wanted to save the hassle for whoever tries to install it following the documented path (vi vpa-up.sh)

**Comment by Shubham82** [comment]
Thanks, @raywainman @MaciekPytel for the quick fix.

we can close this issue once PR #7146 is merged.

**Comment by antweiss** [comment]
Thanks all!!!
