### ISSUE TITLE
VPA - Support for custom metrics

### ISSUE THREAD

**Issue by haggrip** [kubernetes/autoscaler#7151]
**Which component are you using?**:
Vertical Pod Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We use celery and vertical autoscaling in our app. Celery has a main worker and each for each task a new process is spawned. Sometimes, the tasks get OOMKilled, but because the main worker process has not died, it is not counted as an OOMKill event in kubernetes, and the vertical autoscaler does not update the task deployment.
**Describe the solution you'd like.**:

Support custom metrics in a similar manner to HPA. Ideally, we could send OOM events from our tasks and have the vertical autoscaler consume them to update memory requests

**Describe any alternative solutions you've considered.**:

Modifying our tasks to update the vertical autoscaling CRDs when memory errors are detected. This seems like an anti-pattern to any kubernetes native application, but I welcome other opinions on this matter.

**Comment by haggrip** [comment]
It does! We are yet to implement this across our clusters, but from local tests I've done, I get the expected behavior when running on cgroupv2. With cgroupv1 we are missing a lot of OOM events in our celery workloads.

**Comment by adrianmoisey** [comment]
Perfect! Glad it's a solution. Should we close this issue?

**Comment by haggrip** [comment]
Yes, this can be closed. I think cgroupv2 should be recommended when running VPA. I would like to contribute documentation if appropriate. Should I open another issue for this?

**Comment by adrianmoisey** [comment]
> Yes, this can be closed. I think cgroupv2 should be recommended when running VPA. I would like to contribute documentation if appropriate. Should I open another issue for this?

Let's close this for now. If you want to add documentation, then make a PR and reference this (closed) issue.

/close
