### ISSUE TITLE
Question on VPA - Benefits of Using 'prometheus' for VPA Recommender --storage Option

### ISSUE THREAD

**Issue by dongheeJeong** [kubernetes/autoscaler#7168]
Hello everyone,

I’m currently exploring the Vertical Pod Autoscaler (VPA) and considering the --storage option for the recommender component, which can be set to either checkpoint (default) or prometheus.

I understand that configuring prometheus might require additional setup and integration steps. Could someone please clarify the benefits of using prometheus over the default checkpoint method?

Specifically, I’m interested in understanding:

 - What advantages does prometheus provide compared to the default checkpoint method?

If there are any documents or resources that cover this comparison, please point me to them.

Thank you so much for your time and assistance!

**Comment by adrianmoisey** [comment]
Honestly, I'm not too sure.
The feature was added in https://github.com/kubernetes/autoscaler/pull/535 with no description

My understanding is that it allows for more flexibility with getting history of Pod metrics.

**Comment by adrianmoisey** [comment]
Oh another option is that metrics-api may not be installed on a cluster, and someone would prefer to use Prometheus.

**Comment by dwilliams782** [comment]
Isn't the point that on recommender start up, by default it will look for `VerticalPodAutoscalerCheckpoint` object per VPA, whereas with Prometheus it can query a configurable amount of historical data? 

AFAICT, the main difference is when you are deploying recommender for the first time using `VerticalPodAutoscalerCheckpoint` resources will be inaccurate until it has collected a good amount of data (over the course of days / weeks I would guess)?

**Comment by adrianmoisey** [comment]
Yup, that's definitely an advantage of Prometheus over metric-server. Thanks for mentioning it.

**Comment by adrianmoisey** [comment]
I've recently had a look at this code and it seems like the only advantage is to that the history is loaded into the VPA for Prometheus. 
After that, the VPA gets metrics per Pod from the metrics-server.

**Comment by adrianmoisey** [comment]
I hope that answers your question, please re-open if not.

/remove-kind bug
/kind support
/close
