### ISSUE TITLE
Stop using kube-env for node information

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/autoscaler#718]
We should find a more stable source of information than kube-env for information the autoscaler needs.
Ideally this will be provided by the upcoming Machines API.
See:
- [Add AUTOSCALER_ENV_VARS to kube-env to hotfix cluster autoscaler](https://github.com/kubernetes/kubernetes/pull/61119)
- [Extend cluster autoscaler to check AUTOSCALER_ENV_VARS in kube-env](https://github.com/kubernetes/autoscaler/pull/710)

/cc @bskiba @roberthbailey @mwielgus

**Comment by mwielgus** [comment]
Nothing happened on this issue for the last 2 years. The used fields are still OK.
