### ISSUE TITLE
Scale down in AWS does not remove node from Cluster

### ISSUE THREAD

**Issue by gmaxwell94** [kubernetes/autoscaler#719]
using v1.1.1  scales up correctly,  
scales instances down as expected but as part of the tear down of a instance should be deleted from the k8 cluster

in 
static_autoscaler does not seems to  get any nodes from 
unregisteredNodes := a.ClusterStateRegistry.GetUnregisteredNodes()
removeOldUnregisteredNodes   
 
which means the  call in clusterstage.go  in func UpdateNodes

notRegistered, err := getNotRegisteredNodes(nodes, csr.cloudProvider, currentTime)
is returning empty for nodes in "NotReady" state that is > a few minutes

NAME                            STATUS     AGE
ip-172-16-88-136.ec2.internal   NotReady   57m
ip-172-16-88-146.ec2.internal   NotReady   1h
ip-172-16-88-148.ec2.internal   Ready      1h
ip-172-16-88-153.ec2.internal   NotReady   1h
ip-172-16-88-154.ec2.internal   NotReady   1h
ip-172-16-88-159.ec2.internal   NotReady   15h
ip-172-16-88-167.ec2.internal   NotReady   15h
ip-172-16-88-176.ec2.internal   NotReady   1h
ip-172-16-88-179.ec2.internal   Ready      15h
ip-172-16-88-200.ec2.internal   NotReady   1h
ip-172-16-88-204.ec2.internal   NotReady   1h
ip-172-16-88-209.ec2.internal   NotReady   1h
ip-172-16-88-211.ec2.internal   NotReady   1h
ip-172-16-88-226.ec2.internal   NotReady   1h
ip-172-16-88-244.ec2.internal   NotReady   15h
ip-172-16-88-253.ec2.internal   NotReady   1h

the api call gives the following
curl http://10.2.0.1:8080/api/v1/nodes
info for a node
note the taints
--------------------------------
        "taints": [
          {
            "key": "ToBeDeletedByClusterAutoscaler",
            "value": "1521144316",
---------------------------------
So in all aspects this nodes should have been deleted. 

  "items": [
    {
      "metadata": {
        "name": "ip-172-16-88-136.ec2.internal",
        "selfLink": "/api/v1/nodes/ip-172-16-88-136.ec2.internal",
        "uid": "d8eebf45-288a-11e8-a356-0e75d3579f66",
        "resourceVersion": "70753",
        "creationTimestamp": "2018-03-15T19:55:44Z",
        "labels": {
          "node-role.kubernetes.io/vanilla": "true",
          "beta.kubernetes.io/arch": "amd64",
          "beta.kubernetes.io/instance-type": "c5.xlarge",
          "beta.kubernetes.io/os": "linux",
          "failure-domain.beta.kubernetes.io/region": "us-east-1",
          "failure-domain.beta.kubernetes.io/zone": "us-east-1a",
          "kubernetes.io/hostname": "10.2.136.1"
        },
        "annotations": {
          "node.alpha.kubernetes.io/ttl": "0",
          "volumes.kubernetes.io/controller-managed-attach-detach": "true"
        }
      },
      "spec": {
        "podCIDR": "10.2.15.0/24",
        "externalID": "i-08b22eee77e88d42f",
        "providerID": "aws:///us-east-1a/i-08b22eee77e88d42f",
        "taints": [
          {
            "key": "ToBeDeletedByClusterAutoscaler",
            "value": "1521144316",
            "effect": "NoSchedule"
          }
        ]
      },
      "status": {
        "capacity": {
          "cpu": "4",
          "memory": "7817136Ki",
          "pods": "110"
        },
        "allocatable": {
          "memory": "7714736Ki",
          "pods": "110",
          "cpu": "4"
        },
        "conditions": [
          {
            "type": "OutOfDisk",
            "status": "False",
            "lastHeartbeatTime": "2018-03-15T20:05:25Z",
            "lastTransitionTime": "2018-03-15T19:55:44Z",
            "reason": "KubeletHasSufficientDisk",
            "message": "kubelet has sufficient disk space available"
          },
          {
            "type": "MemoryPressure",
            "status": "Unknown",
            "lastHeartbeatTime": "2018-03-15T20:05:25Z",
            "lastTransitionTime": "2018-03-15T20:06:06Z",
            "reason": "NodeStatusUnknown",
            "message": "Kubelet stopped posting node status."
          },
          {
            "type": "DiskPressure",
            "status": "Unknown",
            "lastHeartbeatTime": "2018-03-15T20:05:25Z",
            "lastTransitionTime": "2018-03-15T20:06:06Z",
            "reason": "NodeStatusUnknown",
            "message": "Kubelet stopped posting node status."
          },
          {
            "type": "Ready",
            "status": "Unknown",
            "lastHeartbeatTime": "2018-03-15T20:05:25Z",
            "lastTransitionTime": "2018-03-15T20:06:06Z",
            "reason": "NodeStatusUnknown",
            "message": "Kubelet stopped posting node status."
          }
        ],
        "daemonEndpoints": {
          "kubeletEndpoint": {
            "Port": 10250
          }
        },
        "nodeInfo": {
          "machineID": "6c0dbeffde9846e48691730623978522",
          "systemUUID": "EC2DDA3B-88DA-AC74-676C-460A410A0384",
          "bootID": "12e8a887-d13b-482c-9199-9fd68396e6cd",
          "kernelVersion": "4.9.76-38.79.amzn2.x86_64",
          "osImage": "Debian GNU/Linux 9 (stretch)",
          "containerRuntimeVersion": "docker://17.12.0-ce",
          "kubeletVersion": "v1.9.1",
          "kubeProxyVersion": "v1.9.1",
          "operatingSystem": "linux",
          "architecture": "amd64"
        },
        "images": [
          {
            "names": [
              "gcr.io/google-containers/hyperkube@sha256:69cd6e29c8bd7658e6597cba6aa0110e91c8ef9a993844717e7819cf91d77563",
              "gcr.io/google-containers/hyperkube:v1.9.1"
            ],
            "sizeBytes": 617915509
          }
        ]
      }
    },

The current date on the host is Thu Mar 15 21:04:16 UTC 2018  so all heartbeats are older than a few minutes.

Thanks
Greg Maxwell

**Comment by MaciekPytel** [comment]
Do I understand correctly that the underlying VMs have been deleted as expected? GetUnregisteredNodes() is based on API call to cloudprovider and what you describe is consistent with VMs being deleted, but Node objects remaining in k8s.

If that's the case than the problem is not in Cluster Autoscaler. CA does not add or remove Node objects from k8s cluster. All it does is create or delete VMs. Managing Node objects is the responsibility of kubelet and NodeController.
