### ISSUE TITLE
Hard-coded server type in Hetzner provider will break on 2024-09-06

### ISSUE THREAD

**Issue by apricote** [kubernetes/autoscaler#7210]
**Which component are you using?**:

cluster-autoscaler Hetzner provider

/area provider/hetzner
/area cluster-autoscaler

**What version of the component are you using?**: 

Component version: All current versions

**What k8s version are you using (`kubectl version`)?**:

Does not matter

**What environment is this in?**:

Hetzner Cloud

**What did you expect to happen?**:

The Hetzner Cloud provider should continue to work after 2024-09-06.

**What happened instead?**:

The Hetzner Cloud provider will stop working on 2024-09-06.

**How to reproduce it (as minimally and precisely as possible)**:

- Replace the hardcoded server type ([code](https://github.com/kubernetes/autoscaler/blob/9226cf6bb20c1ea81c95744a77708074d2b61f67/cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go#L211)) with a server type that does not exist (ie. `xyz123`)
- Start the provider
- Observe error messages:

      mixed_nodeinfos_processor.go:160] Unable to build proper template node for draining-node-pool: failed to create resource list for node group draining-node-pool error: failed to get machine type xyz123 info error: server type not found
      static_autoscaler.go:387] Failed to get node infos for groups: failed to create resource list for node group draining-node-pool error: failed to get machine type xyz123 info error: server type not found

**Anything else we need to know?**:

The server type `cx11` was deprecated on 2024-06-06. It will be removed from the API on 2024-09-06: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated

The server type is hardcoded for a `draining-node-pool`, which is not actually used anywhere in the provider. It is only added to the list of known node pools.

Two options:

- Replace `cx11` by the replacement type `cx22`

  This is minimally invasive, but has the same problem that we are hardcoding a value that might change or be deprecated.

- Remove `draining-node-pool` completely from the code
  
  This feels like the clean choice, as this node pool is not used internally. However, this is a user visible change (node pool will disappear from the status config map), so I am not sure if we can backport this to previous releases.

**Comment by apricote** [comment]
Update from internal conversations:

We plan to implement a workaround for known current users of `cluster-autoscaler`. This will still cause issues for new users unless a new version of `cluster-autoscaler` is released.

The workaround will only be available for ~2 weeks after new releases are cut.

We will inform impacted customers about this so they can update before it starts breaking.

**Comment by apricote** [comment]
Backports to current release branches:

- https://github.com/kubernetes/autoscaler/pull/7298
- https://github.com/kubernetes/autoscaler/pull/7299
- https://github.com/kubernetes/autoscaler/pull/7300
- https://github.com/kubernetes/autoscaler/pull/7301

**Comment by apricote** [comment]
## Information for customers

The fix has now been released in new versions of cluster-autoscaler. Please upgrade to the these versions before 4 November 2024.

The following versions include the patches:

- ≥ 1.28.7
- ≥ 1.29.5
- ≥ 1.30.2
- ≥ 1.31.1

We will remove all access to the CX11 server type after 4 November 2024. If you are still using unpatched versions of cluster-autoscaler, they will stop working.

If you were using the alternative container images we provided (`docker.io/hetznercloud/cluster-autoscaler`), please switch back to the images built by the Kubernetes community (`registry.k8s.io/autoscaling/cluster-autoscaler`). We will remove the alternative container images on 19 November 2024.

We will be happy to help you with any questions. Please write us a support request by logging onto your account: https://console.hetzner.cloud/support

**Comment by Shubham82** [comment]
Thanks @apricote for this information.

Can we mention this information under Hetzner [README.md](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/hetzner/README.md) as a Note, so that users will get the information about it.

WDYT?

**Comment by apricote** [comment]
We also sent the above as an email to all active users of cluster-autoscaler on Hetzner Cloud. I think that should be enough. Anyone newly installing cluster-autoscaler should hopefully use the latest patch releases.

**Comment by Shubham82** [comment]
> We also sent the above as an email to all active users of cluster-autoscaler on Hetzner Cloud. I think that should be enough. Anyone newly installing cluster-autoscaler should hopefully use the latest patch releases.

ok @apricote, I didn't know about the email things. it seems good to me then.

Thanks!

**Comment by btribit** [comment]
Is there any chance we can get this tagged and release? As of 1.31.0 this change is not in place yet.

**Comment by Shubham82** [comment]
It should be in the CA 1.31 patch release (1.31.1). which is not yet release.
It will be released soon.

For information: #7315

**Comment by Shubham82** [comment]
Hi @btribit, FYI: The [patch release](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.31.1) for CA 1.31 (CA 1.31.1) has been released, PTAL!

**Comment by btribit** [comment]
@Shubham82 , works like a champ! Found it in the registry too. Thank you!
