### ISSUE TITLE
[Hetzner] Routes are not cleaned after scale down/node removal

### ISSUE THREAD

**Issue by pat-s** [kubernetes/autoscaler#7227]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

1.29.4

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
1.29.8
</pre></details>

**What environment is this in?**:

hetzner, k3s

**What did you expect to happen?**:

Cleanup of routes on node removal

**What happened instead?**:

Routes were not cleaned up, resulting in many unused routes including hitting the route limit of the account

**How to reproduce it (as minimally and precisely as possible)**:

I'd assume everybody is affected by this. Inspecting Networks -> Routes should list many (unused) routes.

**Anything else we need to know?**:

The issue has been reported earlier in #4049 but without response.

**Comment by Shubham82** [comment]
cc @apricote
PTAL!

**Comment by apricote** [comment]
Hello @pat-s,

creating and deleting routes is the responsibility of `hcloud-cloud-controller-manager` and not related to the cluster-autoscaler provider.

Could you [open a new bug issue](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/new?assignees=&labels=bug&projects=&template=bug.yaml) with the project instead?

**Comment by pat-s** [comment]
Did as instructed, thanks @apricote
