### ISSUE TITLE
vpa-up.sh reliably fails to create secrets, but only the first time you run it.

### ISSUE THREAD

**Issue by rsalmond** [kubernetes/autoscaler#7270]
**Which component are you using?**: VPA

**What version of the component are you using?**: 

Component version: 1.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-gke.1326000
</pre></details>

**What environment is this in?**:

GKE

**What did you expect to happen?**:

`./hack/vpa-up.sh` should execute `gencerts.sh` every time it is executed.

**What happened instead?**:

`./hack/vpa-up.sh` skips the execution of `gencerts.sh` the first time it is run. Subsequent runs work correctly.

**How to reproduce it (as minimally and precisely as possible)**:

1. start a new VM
2. clone kubernetes/autoscaler
3. run `./hack/vpa-up.sh`

**Anything else we need to know?**:

Steps executed on a brand new machine:

**Run 1**

```console
$ git clone https://github.com/kubernetes/autoscaler.git
Cloning into 'autoscaler'...
remote: Enumerating objects: 207306, done.
remote: Counting objects: 100% (2838/2838), done.
remote: Compressing objects: 100% (1875/1875), done.
remote: Total 207306 (delta 1581), reused 1499 (delta 918), pack-reused 204468 (from 1)
Receiving objects: 100% (207306/207306), 239.69 MiB | 20.82 MiB/s, done.
Resolving deltas: 100% (132221/132221), done.
Updating files: 100% (20815/20815), done.
lab[default] student@50:~
$ cd autoscaler/vertical-pod-autoscaler/
lab[default] student@50:~/autoscaler/vertical-pod-autoscaler
$ uptime
 13:44:17 up 11 min,  1 user,  load average: 0.37, 0.20, 0.14
lab[default] student@50:~/autoscaler/vertical-pod-autoscaler
$ ./hack/vpa-up.sh
HEAD is now at 6569b7734 Merge pull request #7178 from raywainman/vpa-release-1.2
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalercheckpoints.autoscaling.k8s.io created
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalers.autoscaling.k8s.io created
clusterrole.rbac.authorization.k8s.io/system:metrics-reader created
clusterrole.rbac.authorization.k8s.io/system:vpa-actor created
clusterrole.rbac.authorization.k8s.io/system:vpa-status-actor created
clusterrole.rbac.authorization.k8s.io/system:vpa-checkpoint-actor created
clusterrole.rbac.authorization.k8s.io/system:evictioner created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-actor created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-status-actor created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-checkpoint-actor created
clusterrole.rbac.authorization.k8s.io/system:vpa-target-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-target-reader-binding created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-evictioner-binding created
serviceaccount/vpa-admission-controller created
serviceaccount/vpa-recommender created
serviceaccount/vpa-updater created
clusterrole.rbac.authorization.k8s.io/system:vpa-admission-controller created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-admission-controller created
clusterrole.rbac.authorization.k8s.io/system:vpa-status-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-status-reader-binding created
role.rbac.authorization.k8s.io/system:leader-locking-vpa-updater created
rolebinding.rbac.authorization.k8s.io/system:leader-locking-vpa-updater created
role.rbac.authorization.k8s.io/system:leader-locking-vpa-recommender created
rolebinding.rbac.authorization.k8s.io/system:leader-locking-vpa-recommender created
deployment.apps/vpa-updater created
deployment.apps/vpa-recommender created
deployment.apps/vpa-admission-controller created
service/vpa-webhook created
```

**Run 2**
```console
$ ./hack/vpa-up.sh
HEAD is now at 6569b7734 Merge pull request #7178 from raywainman/vpa-release-1.2
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "verticalpodautoscalercheckpoints.autoscaling.k8s.io" already exists
Error from server (AlreadyExists): error when creating "STDIN": customresourcedefinitions.apiextensions.k8s.io "verticalpodautoscalers.autoscaling.k8s.io" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:metrics-reader" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:vpa-actor" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:vpa-status-actor" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:vpa-checkpoint-actor" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:evictioner" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:metrics-reader" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-actor" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-status-actor" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-checkpoint-actor" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:vpa-target-reader" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-target-reader-binding" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-evictioner-binding" already exists
Error from server (AlreadyExists): error when creating "STDIN": serviceaccounts "vpa-admission-controller" already exists
Error from server (AlreadyExists): error when creating "STDIN": serviceaccounts "vpa-recommender" already exists
Error from server (AlreadyExists): error when creating "STDIN": serviceaccounts "vpa-updater" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:vpa-admission-controller" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-admission-controller" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "system:vpa-status-reader" already exists
Error from server (AlreadyExists): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "system:vpa-status-reader-binding" already exists
Error from server (AlreadyExists): error when creating "STDIN": roles.rbac.authorization.k8s.io "system:leader-locking-vpa-updater" already exists
Error from server (AlreadyExists): error when creating "STDIN": rolebindings.rbac.authorization.k8s.io "system:leader-locking-vpa-updater" already exists
Error from server (AlreadyExists): error when creating "STDIN": roles.rbac.authorization.k8s.io "system:leader-locking-vpa-recommender" already exists
Error from server (AlreadyExists): error when creating "STDIN": rolebindings.rbac.authorization.k8s.io "system:leader-locking-vpa-recommender" already exists
Error from server (AlreadyExists): error when creating "STDIN": deployments.apps "vpa-updater" already exists
Error from server (AlreadyExists): error when creating "STDIN": deployments.apps "vpa-recommender" already exists
Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
Certificate request self-signature ok
subject=CN=vpa-webhook.kube-system.svc
Uploading certs to the cluster.
secret/vpa-tls-certs created
Deleting /tmp/vpa-certs.
Error from server (AlreadyExists): error when creating "STDIN": deployments.apps "vpa-admission-controller" already exists
Error from server (AlreadyExists): error when creating "STDIN": services "vpa-webhook" already exists
```

**Comment by adrianmoisey** [comment]
I figured out what's happening.
On the first run you're on the master branch. 
https://github.com/kubernetes/autoscaler/blob/59aba2b4063ad195075636e371345c2f75c7522a/vertical-pod-autoscaler/hack/vpa-up.sh#L29

`vpa-up.sh` is passing `apply` to `vpa-process-yamls.sh`.

`vpa-process-yamls.sh` only generates a certificate when `create` is passed in, see:
https://github.com/kubernetes/autoscaler/blob/59aba2b4063ad195075636e371345c2f75c7522a/vertical-pod-autoscaler/hack/vpa-process-yamls.sh#L66-L67

However, part of `vpa-up.sh` is to change to the latest tag, which is `vertical-pod-autoscaler-1.2.1`.
In that tag, `vpa-up.sh` passes in `apply` to `vpa-process-yamls`, which then follows the path to create the certs.

https://github.com/kubernetes/autoscaler/blob/6569b7734cd3c86c14d102e04fb0fb979c643a88/vertical-pod-autoscaler/hack/vpa-up.sh#L29

The change from `create` to `apply` happened in https://github.com/kubernetes/autoscaler/pull/7199

@voelzmo @raywainman thoughts? Should we revert that change or fix the logic in `vpa-up.sh`?

**Comment by raywainman** [comment]
Ha, good find @adrianmoisey.

Probably makes sense to revert #7199 and fix this properly?

**Comment by adrianmoisey** [comment]
> Ha, good find @adrianmoisey.
> 
> Probably makes sense to revert #7199 and fix this properly?

I've made https://github.com/kubernetes/autoscaler/pull/7306 to fix it.
Let me know what you think.

**Comment by raywainman** [comment]
I lgtm'ed that PR with a few suggestions, thanks a lot for the quick fix!

**Comment by voelzmo** [comment]
> only generates a certificate when `create` is passed in, see:

Hey, I'm only looking at this now and I think this explanation contains all the right information, but isn't entirely correct.

I think what's happening is that the current setup is broken on `master`:
* `hack/vpa-up.sh` passes in `apply`
* `hack/process-vpa-yamls.sh` only creates certs when `create` is passed in

We didn't cherry-pick https://github.com/kubernetes/autoscaler/pull/7199 to VPA 1.2, so that branch works fine:
* `hack/vpa-up.sh` passes in `create`
* `hack/process-vpa-yamls.sh` creates certs when `create` is passed in

So imho the fix should be to adapt `hack/process-vpa-yamls.sh` to create certs when `apply` is passed in and probably also avoid re-generating certs when they already exist in the cluster. The latter is done by PR #7306, but it has side-effects: the certs are replaced on disk with new ones, it is just masking that the upload failed. I also think it is problematic to just continue with the regular `vpa-up`, when generating the certs has failed – I think we should rather revert #7306 and  #7199. 
Seems like we found the reason why the installation script uses `create` rather than `apply`.

**Comment by adrianmoisey** [comment]
> The latter is done by PR #7306, but it has side-effects: the certs are replaced on disk with new ones, it is just masking that the upload failed. 

The script currently [writes certs to a temporary directory](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh#L25) and [deletes them in the end](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh#L69-L70). 

This makes me believe that cert in cluster is the source of truth, and the certs on disk are temporary.

> I also think it is problematic to just continue with the regular `vpa-up`, when generating the certs has failed

That behaviour isn't new, it's existed for a long time now: https://github.com/kubernetes/autoscaler/blame/f79e8d44162a9696ab856af6473d25534baf71b7/vertical-pod-autoscaler/hack/vpa-process-yamls.sh#L68

**Comment by adrianmoisey** [comment]
> Ah, good find, that makes sense! So forget about the part with "don't re-generate the local certs" – shouldn't the correct way to fix this still be to pass `apply` to the `gencerts.sh` script and have it behave the same way on `master` and on the current release branch?

Are you talking about the fact that this line matches `create` or `update` rather than `create or apply` ?
https://github.com/kubernetes/autoscaler/blob/afb3a087f9d491435785bfaa42e7ed7b3dc750b3/vertical-pod-autoscaler/hack/vpa-process-yamls.sh#L66

That is definitely a mistake.
