### ISSUE TITLE
Configurable minimum memory for all workloads

### ISSUE THREAD

**Issue by mwarkentin** [kubernetes/autoscaler#7280]
**Which component are you using?**:

VerticalPodAutoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

We recently enabled VPA on some workloads - one of the containers (pgbouncer) has extremely low memory usage (`1-3Mi`). 

![image](https://github.com/user-attachments/assets/6bacceb2-c13d-45db-8136-33d43437619a)

VPA set memory request and limit to ~`3Mi` as expected, however our containers started to crash, and were not resolved by VPAs OOM handling.

We saw errors like the following: `Error: failed to start containerd task "pgbouncer": cannot start a stopped process: unknown`

I am wondering if the containers running on GKE require a certain minimum amount of memory in order to start at all, based on some of these references to similar errors that I found:

* https://github.com/moby/moby/issues/38921
* https://github.com/opencontainers/runc/issues/1980
* https://github.com/moby/moby/issues/41164

**Describe the solution you'd like.**:

If that's the case, it would be nice if I could enforce a hard minimum (maybe 10Mi) across all of my VPAs, which container resources would not be set below, even if the container policy set a minimum of `1Mi`

**Describe any alternative solutions you've considered.**:

Right now, my approach will be to require setting a container policy for every container, and trying to enforce that they always have a value of `10Mi` or higher everywhere.

**Additional context.**:

**Comment by kaiyuu800Q** [comment]
I think you can add a extra arg --pod-recommendation-min-memory-mb={Int}  on vpa-recommender args

**Comment by adrianmoisey** [comment]
That is correct, you can set a minimum:
https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.2.1/vertical-pod-autoscaler/pkg/recommender/logic/recommender.go#L30

Interestingly, the default is 250MiB, which is strange that you got such a low value.

/assign

**Comment by mwarkentin** [comment]
I'm using the GKE VPA, so I'm guessing this is something I'll need to take up with support there. 

Thanks for the pointers, if you'd like this can be closed.

**Comment by adrianmoisey** [comment]
I see that their docs say that there is no default minimum: https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler#containerresourcepolicy_v1_autoscalingk8sio

**Comment by mwarkentin** [comment]
Thanks, I think that confirms this is an issue with GKE VPA only!
