### ISSUE TITLE
If there are some method to set a min memory request recommendation for specify pods created

### ISSUE THREAD

**Issue by kaiiyvwu** [kubernetes/autoscaler#7293]
When I set pod-recommendation-min-memory-mb in the VPA recommender, it applies the minimum memory request to all pods according to the specified value. However, for some specific pods, we want to set a different minimum memory request. Is there a method to achieve this?

**Comment by adrianmoisey** [comment]
Yup, it's possible via resourcePolicy.
Here's an example: https://github.com/kubernetes/autoscaler/blob/a2b793d530022f7ffb96d26a47995a08d5ae343e/vertical-pod-autoscaler/examples/hamster.yaml#L22-L31

**Comment by adrianmoisey** [comment]
Oh, what I don't know is if the resourcePolicy's minimum overrides the `pod-recommendation-min-memory-mb` parameter.
Could you test it out and report back?

**Comment by kaiiyvwu** [comment]
Thanks for your reply,I test the resourcePolicy's minimum overrides the pod-recommendation-min-memory-mb parameter with vpa 0.11.0  when create new pod
1. If vpa.spec.resourcePolicy.containerPolicies.minAllowed >  pod-recommendation-min-memory-mb,the spec.resourcePolicy.containerPolicies.minAllowed will be applied in pod.spec.container.resources.request
2. If pod-recommendation-min-memory-mb > vpa.spec.resourcePolicy.containerPolicies.minAllowed, the pod-recommendation-min-memory-mb will be applied in pod.spec.container.resources.request
__But, the vpa.spec.resourcePolicy.containerPolicies.minAllowed is not applied in vpa.status.recommendation__

**Comment by adrianmoisey** [comment]
Hmmm, that's not ideal.
I think it's because the updater uses `pod-recommendation-min-memory-mb` parameter when making a recommendation, and the admission-controller uses `spec.resourcePolicy.containerPolicies.minAllowed` when figuring out what to set.

One workaround is running multiple VPA recommenders, with various different defaults.
Something like this: https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#starting-multiple-recommenders

**Comment by kaiiyvwu** [comment]
Thanks, I read the source code and find out that the admission-controller compare `spec.resourcePolicy.containerPolicies.minAllowed` and `recommended value` and use the max between them.

**Comment by kaiiyvwu** [comment]
I test resourcePolicy's minimum overriding the pod-recommendation-min-memory-mb  repeatly and  catch a different behavior. The  resourcePolicy's minimum can be appleid to vpa.status.recommendation when resourcePolicy's minimum is lower than pod-recommendation-min-memory-mb.And vpa recommender source code also do like this.
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/estimator.go  line 150-160

There are similar code in admission webhook when create pod. I think it will work and set resource minimum  when vpa.spec.resourcePolicy.containerPolicies.minAllowed is set but vpa.status.recommendation is not updated immediately.

Thank you.
