### ISSUE TITLE
Cluster Autoscaler Patch Releases - September/October 2024

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/autoscaler#7315]
Hi all, slightly behind schedule, but I'm aiming to cut new Cluster Autoscaler patch releases for **1.28-1.31** within the next week. If there are any bugfix cherry-picks you want included, please prepare the PRs and let me know in the comments.

Tagging cloud provider owners for visibility:
@BigDarkClown
@MorrisLaw
@RainbowMango
@aleksandra-malinowska
@andrewsykim
@apricote
@bryce-soghigian
@comtalyst
@cprivitere
@d-mo
@dbonfigli
@deitch
@detiber
@displague
@drmorr0
@ellistarn
@elmiko
@enxebre
@feiskyer
@gjtempleton
@hardikdr
@hello2mao
@jackfrancis
@jayantjain93
@jlamillan
@kevin-wangzefeng
@maciekpytel
@nilo19
@ringtail
@tallaxes
@tghartland
@towca
@vadasambar
@vishalanarase
@x13n
@yaroslava-serdiuk

**Comment by apricote** [comment]
All set for https://github.com/kubernetes/autoscaler/labels/area%2Fprovider%2Fhetzner

Thanks for taking care of this :blush:

**Comment by aleksandra-malinowska** [comment]
Opened #7316 with ProvisioningRequest v1 CRD (1.31 only, since v1 was introduced in 1.31.0). Probably not strictly necessary as it doesn't introduce any code change and CA doesn't automatically apply CRD, but if someone wants to use the version from the same branch as CA, they'll get burned without it.

**Comment by thearchitector** [comment]
Is there an updated timeline here?

**Comment by x13n** [comment]
@gjtempleton Please include https://github.com/kubernetes/autoscaler/pull/7409 if you didn't start the patch release process yet.

**Comment by gjtempleton** [comment]
I got around to updating the k/k dependencies in PRs yesterday, but hadn't got the images built and published yet. The cherry-pick needs a quick tweak before it can be merged, should be easy enough to fix up though, so happy to wait until tomorrow for that.

To answer your question @thearchitector, I'll get the images built and pushed to staging tomorrow, promotion might take another day depending on review bandwidth.

**Comment by thearchitector** [comment]
> To answer your question @thearchitector, I'll get the images built and pushed to staging tomorrow, promotion might take another day depending on review bandwidth.

Thanks!

**Comment by gjtempleton** [comment]
Promotion PR is here: https://github.com/kubernetes/k8s.io/pull/7429#issuecomment-2420830819

**Comment by Shubham82** [comment]
Closing this issue as Releases and release notes are published.

/close

Thanks @gjtempleton
