### ISSUE TITLE
cluster-autoscaler is unable to register new nodes and removes them when they are still required because of workload (Hetzner)

### ISSUE THREAD

**Issue by marcospastor** [kubernetes/autoscaler#7337]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
1.30.2

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.2+rke2r1

</pre></details>

**What environment is this in?**:
Hetzner Cloud

**What did you expect to happen?**:
When new nodes are requested by autoscaler, they should be registered once joined to kubernetes cluster

**What happened instead?**:
Nodes are correctly created but they keep in unregistered status (autoscaler-status config map). In a later moment these nodes are removed even if current workload needs them

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by marcospastor** [comment]
Found these logs, don't know if could be related with issue:
I1003 12:31:52.011431       1 hetzner_cloud_provider.go:81] failed to find hcloud server for node pool1-211c234bbe19e7c9
I1003 12:31:52.011455       1 hetzner_cloud_provider.go:81] failed to find hcloud server for node pool1-7d1b02902603895e
I1003 12:31:52.011464       1 hetzner_cloud_provider.go:81] failed to find hcloud server for node pool1-fca1ecdea599c47

**Comment by marcospastor** [comment]
Just for clarification, we are using Hetzner for server instances only but Kubernetes cluster has been deployed using RKE2 so we are not using ProviderID=hcloud but ProviderID=rke2. Probably this could be the issue. All Kubernetes workers are tagged with ProviderID=rke2 (rke2://<node_name>)

**Comment by marcospastor** [comment]
After a few tests I tried to set kubelet argument 'provider-id=hcloud://<node-name>'. This way autoscaled node is joining Kubernetes cluster with correct ProviderID and autoscaler detects it properly (no longer **failed to find hcloud server for node pool1-xxxxxx log** messages).

**Comment by marcospastor** [comment]
OK. Kubernetes autoscaled nodes should have hcloud://<hetzner_server_id>> instead. This way nodes are registered as expected.

**Comment by marcospastor** [comment]
I'm going to close this issue. The problem was related with ProviderID. As using custom RKE2 Kubernetes cluster, ProviderID was 'rke2' at nodes. After creating worker nodes with ProviderID with 'hcloud' value it started working as expected.

Thanks.

**Comment by dominic-p** [comment]
Sorry to revive a dead post, but I'm running into the exact same behavior on my kubeadm cluster. CA will create a new node, and almost immediately after it is ready, the node is deleted. In the autoscaler logs I see:

```
I0405 15:13:40.492779       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"16c59639-a0b4-431c-9932-320f5320c654", APIVersion:"v1", ResourceVersion:"7171", FieldPath:""}): type: 'Normal' reason: 'ScaledUpGroup' Scale-up: setting group internal-main-worker size to 1 instead of 0 (max: 2)
...
W0405 15:18:40.954166       1 hetzner_servers_cache.go:93] Fetching servers from Hetzner API
I0405 15:18:41.320004       1 hetzner_node_group.go:576] Set node group internal-main-worker size from 0 to 0, expected delta 0
W0405 15:18:41.320057       1 clusterstate.go:313] Disabling scale-up for node group internal-main-worker until 2025-04-05 15:43:40.492386026 +0000 UTC m=+3936.499194342; errorClass=Other; errorCode=cloudProviderError
I0405 15:18:41.320073       1 metrics.go:510] Function scaleUp took 5m0.827723961s to complete
I0405 15:18:41.320088       1 eventing_scale_up_processor.go:47] Skipping event processing for unschedulable pods since there is a ScaleUp attempt this loop
E0405 15:18:41.320093       1 static_autoscaler.go:518] Failed to scale up: failed to increase node group size: failed to 
create all servers: failed to start server internal-main-worker-564727d3f7ac0a3f error: context deadline exceeded
...
I0405 15:19:42.014185       1 hetzner_cloud_provider.go:84] failed to find hcloud server for node hcloud://62357047       
W0405 15:19:42.014203       1 clusterstate.go:657] Nodegroup is nil for hcloud://62357047
I0405 15:19:42.014226       1 static_autoscaler.go:415] 1 unregistered nodes present
I0405 15:19:42.014236       1 hetzner_cloud_provider.go:84] failed to find hcloud server for node hcloud://62357047       
W0405 15:19:42.014244       1 static_autoscaler.go:821] No node group for node hcloud://62357047, skipping
```

I was able to run `kubectl describe nodes` during the brief second that the worker node was listed before it was deleted. I saw

```
...
Lease:              Failed to get lease: leases.coordination.k8s.io "internal-main-worker-70e6320b0a094c20" not found
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason
          Message
  ----             ------  -----------------                 ------------------                ------
          -------
  MemoryPressure   False   Sat, 05 Apr 2025 07:43:14 -0700   Sat, 05 Apr 2025 07:43:14 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Sat, 05 Apr 2025 07:43:14 -0700   Sat, 05 Apr 2025 07:43:14 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Sat, 05 Apr 2025 07:43:14 -0700   Sat, 05 Apr 2025 07:43:14 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Sat, 05 Apr 2025 07:43:14 -0700   Sat, 05 Apr 2025 07:43:14 -0700   KubeletNotReady
          [container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: no CNI configuration file in /etc/cni/net.d/. Has your network provider started?, CSINode is not yet initialized]
...
Events:
  Type    Reason                   Age              From             Message
  ----    ------                   ----             ----             -------
  Normal  Starting                 6s               kubelet          Starting kubelet.
  Normal  NodeHasSufficientMemory  6s (x2 over 6s)  kubelet          Node internal-main-worker-70e6320b0a094c20 status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    6s (x2 over 6s)  kubelet          Node internal-main-worker-70e6320b0a094c20 status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     6s (x2 over 6s)  kubelet          Node internal-main-worker-70e6320b0a094c20 status is now: NodeHasSufficientPID
  Normal  NodeAllocatableEnforced  6s               kubelet          Updated Node Allocatable limit across pods
  Normal  RegisteredNode           4s               node-controller  Node internal-main-worker-70e6320b0a094c20 event: Registered Node internal-main-worker-70e6320b0a094c20 in Controller
```

Notably, there was no ProviderID set on the node like there is on the control plane node. I understand that the CCM is responsible for setting this, and indeed I see that it is registered with the CCM (4 seconds before it's deleted). But, I can't understand what process is deleting it.

In the end, my questions is: how did you set the provider-id kubelet config on the newly created nodes? The only thing I can think of is a cloud-init script, but I'm not sure how I would get the server ID in that context. Any pointers you can give would be greatly appreciated.

**Comment by marcospastor** [comment]
Hi dominic-p,

In our setup we use prebuild images with RKE2 installed and when CA creates nodes we get Hetzner ID using **hcloud cli** (installed and configured inside image) using cloud init script. Then we complete **/etc/rancher/rke2/config.yaml** adding this line: **kubelet-arg: "provider-id=hcloud://xxxxxxx"**

Hetzner ID can be obtained with this command:
**hcloud --context _hcloud_profile_ server describe _node_name_ -o json | jq .id**

When you define node pools at CA, a label is also required at **/etc/rancher/rke2/config.yaml** identifying which node pool new node is assigned to.

As node name includes node pool, we get node pool name at cloud init then add it to **/etc/rancher/rke2/config.yaml** as 

**node-label:
  - "hcloud/node-group=_node_pool_group_"**

Hope it helps

Marcos

**Comment by dominic-p** [comment]
Thanks for the quick and in-depth reply, Marcos. I really appreciate it. I've been banging my head against this one for days now, and nothing is working. 

I apologize if I'm being dense, but I'm still struggling to understand how you are getting the `node_name` for use in your `hcloud` command. On my cluster, my worker nodes get names like "internal-main-worker-415377ab6fa41056". I know the prefix, of course, but the last part of the node name is unpredictable to me. Do your names not look like that? Or, do you have some way of looking them up before you need to use them to get the node's ID?

Right now, my best idea is to write a script to run in cloud-init that will try to get the new worker's public IP and then use that to search for the node using the hetzner API. Not exactly elegant.

**Comment by dominic-p** [comment]
Oh. my. gosh. 🤦‍♂️ Ok, I guess I need some more sleep. Thank you.
