### ISSUE TITLE
Cluster-AutoScaler: Need pick up latest versions of OCI-GO-SDK

### ISSUE THREAD

**Issue by YichunLu** [kubernetes/autoscaler#7341]
**Which component are you using?**: Cluster AutoScaler

**Which component hosted in this repository is this a feature for?**:  [Link to repo](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/oci/vendor-internal/github.com/oracle/oci-go-sdk)

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**: OCI GO SDK has released several new versions since last year's update. Several issues has been identified and addressed within the latest GO SDK but has not been picked up by the autoscaler.
 

**Describe the solution you'd like.**: Upgrade the OCI GO SDK version to [some latest version](https://github.com/oracle/oci-go-sdk/releases?page=1), at least >= 65.55.1. 

**Describe any alternative solutions you've considered.**: NA

**Additional context.**:

**Comment by Shubham82** [comment]
cc @jlamillan
PTAL!

/area provider/oci

**Comment by jlamillan** [comment]
ack

**Comment by jlamillan** [comment]
Waiting on [PR](https://github.com/kubernetes/autoscaler/pull/7385) to be merged...
