### ISSUE TITLE
GCP: InstanceTemplates are no longer `global` resources

### ISSUE THREAD

**Issue by 4wdonny** [kubernetes/autoscaler#7396]
**Which component are you using?**:
Cluster Autoscaler

cluster-autoscaler 
**What version of the component are you using?**: 1.28.2

Component version: 1.28.2 

**What k8s version are you using (`kubectl version`)?**: 

v1.29.8-gke.1096000

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**: Google

GCP has changed the location of instance templates...they used to be Global and now they are regional. Is this configurable in the Autoscaler?

**Comment by 4wdonny** [comment]
Last night a node pool was upgraded to `1.29.8-gke.1096000` and the underlying instance template for the MIG changed from a `global` one to a regional one.

**Comment by Shubham82** [comment]
cc @BigDarkClown @x13n

**Comment by aaktaev** [comment]
Same for k8s=1.29.9-gke.1177000 and ClusterAutoscaler appVersion=v1.29.3:

```
Unable to build proper template node for https://www.googleapis.com/compute/v1/projects/$PROJECT/zones/europe-west1-b/instanceGroups/gke-k8s-system-grp: googleapi: Error 404: The resource 'projects/$PROJECT/global/instanceTemplates/gke-k8s-system-7777777' was not found, notFound
```

**Comment by 4wdonny** [comment]
@x13n I attempted using CA 1.29 and encountered the same issue.

**Comment by x13n** [comment]
It was backported but not released yet. The release is happening right now
- new CA patch versions for both 1.28 and 1.29 should work correctly with
regional templates.

**Comment by aaktaev** [comment]
Hi, @x13n , 
Was the patch for ClusterAutoscaler v1.29 released?

**Comment by Shubham82** [comment]
Hi @4wdonny, the patch release for CA (1.28-1.31) is out. Could you please check if all things work fine?
if the issue is resolved so can we close this issue?

**Comment by Shubham82** [comment]
Closing this issue, as this issue is fixed in the patch release of CA1.28 (1.28.7) and CA1.29 (1.29.5).

If there is any concern, please reopen this issue.

Thanks!
