### ISSUE TITLE
Miss testHistogramOptions in decaying_histogram_test.go

### ISSUE THREAD

**Issue by yangjiajun2014** [kubernetes/autoscaler#7412]
**Which component are you using?**:
 vertical-pod-autoscaler

**What version of the component are you using?**:
master branch

The test needs a testHistogramOptions but I did not find it.

https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/util/decaying_histogram_test.go

**Comment by adrianmoisey** [comment]
/area vertical-pod-autoscaler

testHistogramOptions lives here: https://github.com/kubernetes/autoscaler/blob/3a29dc2690102a6758cd085e9d6a3bcf4d7c29d8/vertical-pod-autoscaler/pkg/recommender/util/histogram_test.go#L35

Hope that helps!
/close
