### ISSUE TITLE
Convert resources to a more human relevant SI

### ISSUE THREAD

**Issue by jacobeatsspam** [kubernetes/autoscaler#7417]
**Which component are you using?**:

VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Yes. VPA memory recommendations are applied as kilobytes (`k`, the non-binary 1000 byte) and it's not very relevant to the humans that are reading the podspec later.

**Describe the solution you'd like.**:

Convert to the units to highest SI suffix without decimal places.

**Describe any alternative solutions you've considered.**:

N/A

**Comment by adrianmoisey** [comment]
/area vertical-pod-autoscaler

This looks like a dupe of https://github.com/kubernetes/autoscaler/issues/7094

**Comment by omerap12** [comment]
I’m happy to help with that if needed.

**Comment by adrianmoisey** [comment]
Go for it!
/assign omerap12
