### ISSUE TITLE
Helm chart - Allow custom extra arguments

### ISSUE THREAD

**Issue by nicolas-laduguie** [kubernetes/autoscaler#7422]
**Which component are you using?**:
Helm chart

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
At the moment, the helm chart provides ability to give `extraArgs` in yaml key=value format, or eventually key for arguments not requiring any value (see https://github.com/kubernetes/autoscaler/blob/1603c19e62dc46a9bb1d176624e1964d974b3ef1/charts/cluster-autoscaler/templates/deployment.yaml#L128C45-L128C54).
For some other needs, it would be beneficial to let the user provide any value as an extra argument.
For instance providing a env variable like `$ENV_VAR` as an extra argument would help making arguments more dynamic, loaded from configmap or secrets for instance. 

**Describe the solution you'd like.**:

Since the `extraArgs` value is already templated and computed in a specific way, would be easier to create a new `customArgs` value that would be given as is to the command.

**Comment by omerap12** [comment]
PR submitted here: https://github.com/kubernetes/autoscaler/pull/7423

**Comment by nicolas-laduguie** [comment]
Issue fixed and released in helm chart v9.44.0
