### ISSUE TITLE
Image tag `1.30.3` in container registry `registry.k8s.io/autoscaling/cluster-autoscaler` with no associated release

### ISSUE THREAD

**Issue by wcarlsen** [kubernetes/autoscaler#7443]
**Which component are you using?**:

Cluster-autoscaler and it's associated helm chart.

**What version of the component are you using?**:

Component version:
* Helm chart version: 9.43.0
* Cluster-autoscaler version: 1.30.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4-eks-a737599

</pre></details>

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

I see an image tag `1.30.3` in container registry `registry.k8s.io/autoscaling/cluster-autoscaler` with no associated release.

![Screenshot_20241029_091945](https://github.com/user-attachments/assets/0f05e637-d6ed-49ce-a73d-6e47d5982ad9)

**What happened instead?**:

I expected a tag `1.30.3` with no associated release to not be present in the registry. Maybe this comes from a deleted release?

**How to reproduce it (as minimally and precisely as possible)**:

```bash
docker pull registry.k8s.io/autoscaling/cluster-autoscaler:v1.30.3
```

**Anything else we need to know?**:

**Comment by Shubham82** [comment]
@wcarlsen, I think it is due to Promotion PR (https://github.com/kubernetes/k8s.io/pull/7429) for images of the CA Patch release being merged and the corresponding CA Patch release not yet released (#7315)

**Comment by Shubham82** [comment]
cc @gjtempleton, please correct me if I missed something here.
PTAL!

**Comment by Shubham82** [comment]
> Yep, that's on me. Apologies, got to the point of promoting the images but not the tags and associated release notes before some issues. Will get this resolved today.

Thanks @gjtempleton

**Comment by gjtempleton** [comment]
Release notes and associated tags now cut, apologies for the delay @wcarlsen

**Comment by Shubham82** [comment]
> Release notes and associated tags now cut, apologies for the delay @wcarlsen

Thanks, @gjtempleton for all the work.

**Comment by Shubham82** [comment]
Hi @wcarlsen, can we close this issue, as it is resolved?

**Comment by wcarlsen** [comment]
Yes off course. Thanks for the reminder @Shubham82 and no worries @gjtempleton.
