### ISSUE TITLE
cluster_autoscaler_failed_scale_ups_total metric is missing from metrics until an event is registered

### ISSUE THREAD

**Issue by elmiko** [kubernetes/autoscaler#7448]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.29

**What k8s version are you using (`kubectl version`)?**:

1.29

**What environment is this in?**:

n/a

**What did you expect to happen?**:

metric should be initialized so that the zero value can be seen in prometheus data.

**What happened instead?**:

metric does not appear until it has been updated.

**How to reproduce it (as minimally and precisely as possible)**:

1. start the CA
2. curl the metrics endpoint and grep for `cluster_autoscaler_failed_scale_ups_total`

**Anything else we need to know?**:

this should be fairly straightforward to fix.

**Comment by thiha-min-thant** [comment]
Hi @elmiko , could you please assign to me? Thanks!
