### ISSUE TITLE
Node Group at min size but taint remains?

### ISSUE THREAD

**Issue by johnharris85** [kubernetes/autoscaler#747]
Not sure if this is by design behavior or not, but we have a couple of nodes with a taint indicated they should have been scaled down by CA in January, however logs of CA show that doing so would have taken it below the min size, so they clearly weren't. However the taints remain meaning we actually have less nodes available for scheduling than min size.

k8s: 1.8.4
CA: 0.6.0

**Comment by MaciekPytel** [comment]
This has been fixed in CA 1.0.1 (#369).

Also CA releases are bundled together with k8s versions. Kubernetes 1.8 ships with CA 1.0. We strongly recommend against using older CA with newer Kubernetes.
