### ISSUE TITLE
VPA sets limit more than maxAllowed

### ISSUE THREAD

**Issue by NEO2756** [kubernetes/autoscaler#7510]
vertical-pod-autoscaler

Component version: 1.2.1
**What environment is this in?**:
EKS

**What did you expect to happen?**:
 Limit Set should be less than equal to maxAllowed
**What happened instead?**:
Pod is running in VPA Initial mode. After manually recreation the request/limit set to : -
1. The limit is set to 9007199254 ~ 8.3 Gi though maxAllowed was 8Gi
2. Recommendation does not show 9007199254. How this has been calculated ?
3. Also a scenario where request is set more than limit. This scenario is recreation after an OOM.
![Screenshot 2024-11-14 at 2 28 23 PM](https://github.com/user-attachments/assets/85b35345-e569-4e52-af66-eb8128dfdf14).
```
resources:
        limits:
          cpu: '6'
          memory: '9007199254'. #8.3 Gi
        requests:
          cpu: 500m
          memory: 1Gi
``` 
Recommendations for this pod:-
```
Recommendation:
    Container Recommendations:
      Container Name:  <pod-name>
      Lower Bound:
        Cpu:     500m
        Memory:  1Gi
      Target:
        Cpu:     500m
        Memory:  1Gi
      Uncapped Target:
        Cpu:     15m
        Memory:  476450463
      Upper Bound:
        Cpu:     500m
        Memory:  1293222685
``` 
Resource Policy snippet:- 
```
Spec:
  Resource Policy:
    Container Policies:
      Container Name:     <Pod-name>
      Controlled Values:  RequestsAndLimits
      Max Allowed:
        Cpu:     6
        Memory:  8Gi
      Min Allowed:
        Cpu:           500m
        Memory:        1Gi
      Container Name:  <pod-name-x>
      Mode:            Off
```

**Comment by adrianmoisey** [comment]
maxAllowed only controls "requests", see https://github.com/kubernetes/autoscaler/blob/a01276ef14639152c7cca3585aaa132ca0c3c238/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L202-L205

Limits is set as as a ratio between the Pod's original requests/limits ratio.
