### ISSUE TITLE
Allow testing of multiple VPA recommendations concurrently 

### ISSUE THREAD

**Issue by K8Y** [kubernetes/autoscaler#7519]
**Which component are you using?**:

vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

This feature should allow users to deploy multiple VPAs that have the same `targetRef` and indicate that some VPAs are for testing only. As a result, the admission-controller and the updater should ignore these "testing" VPAs 

This will make it easier to test out different VPA configurations concurrently and compare the different resulting recommendations

**Describe the solution you'd like.**:

The admission-controller and the updater should ignore VPAs with a label indicating a testing VPA. For example, they should ignore VPAs with the label `vpaTest=true`

**Describe any alternative solutions you've considered.**:

An alternative could be to only process VPAs that have a label that indicate they should be used; however, this solution is not chosen as it would change current behavior (all existing VPAs would need to get this label)

**Comment by adrianmoisey** [comment]
Sounds like a "dryrun" mode is needed for VPAs.

I could be wrong, but this sounds like enhancement proposal territory

**Comment by omerap12** [comment]
Hmm, I might be missing something, but why not just set `updateMode: "Off"`? Wouldn't that achieve the same functionality?

**Comment by adrianmoisey** [comment]
Um. Yes, you're right. I forgot, we do exactly this to test out VPAs.

**Comment by K8Y** [comment]
Currently, if there are multiple VPAs that match a pod, [GetControllingVPAForPod](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/vpa/api.go#L130C6-L130C29) called in the [updater](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L184), will return a VPA using this [Stronger](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/vpa/api.go#L113) function, but it does not take into account their update modes. It would be helpful for testing to have, for example, one in `Auto` and a few in `Off` so that the `Auto` one will be acted upon and the `Off` ones are only there so that users can view their resource recommendations

I see `Off` VPAs are ignored in the admission-controller [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/resource/vpa/matcher.go#L72). Could we add a similar exception in the updater?

**Comment by adrianmoisey** [comment]
> Currently, if there are multiple VPAs that match a pod, [GetControllingVPAForPod](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/utils/vpa/api.go#L130C6-L130C29) called in the [updater](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L184)

A few lines above that is a part to [ignore VPAs that aren't set to Auto or Recreate](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/logic/updater.go#L149-L153).

So the updater should bail out before it gets to `GetControllingVPAForPod` on that sort of VPA.
