### ISSUE TITLE
Implement or Remove TODO Comment in VPA Estimator

### ISSUE THREAD

**Issue by omerap12** [kubernetes/autoscaler#7528]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
We currently have a TODO comment in the code: [comment](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/logic/estimator.go#L26). This has been there for a while without anyone implementing it. I’m wondering if it's still relevant. Either way, we should either implement the change or remove the comment.

**Describe the solution you'd like.**:
I propose implementing the separation, which would allow us to further extend the VPA's capabilities. However, I’m also fine with keeping the VPA as it currently is.

**Describe any alternative solutions you've considered.**:
Simply delete the comment.

**Additional context.**:
NONE

**Comment by adrianmoisey** [comment]
I see value in separating the estimator, I agree in the reason for doing so.

However, if we deleted the comment and did the separation later, I don't think that would hurt the project either.
