### ISSUE TITLE
Document humanize memory quantities feature

### ISSUE THREAD

**Issue by omerap12** [kubernetes/autoscaler#7539]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

**Describe the solution you'd like.**:
A new feature was introduced in [PR #7428](https://github.com/kubernetes/autoscaler/pull/7428), but documentation for this feature is currently missing.
Reference: [Comment on the PR](https://github.com/kubernetes/autoscaler/pull/7428#issuecomment-2436137446).
As the author of this feature, I am happy to take on the task of documenting it.

**Describe any alternative solutions you've considered.**:
NONE

**Additional context.**:
NONE

**Comment by adrianmoisey** [comment]
I'm working on shuffling around the docs a bit. Can you wait until I've finished that before adding these docs?

**Comment by omerap12** [comment]
> I'm working on shuffling around the docs a bit. Can you wait until I've finished that before adding these docs?

Of course :)
