### ISSUE TITLE
VPA: add if error is expected in pods_eviction_restriction_test

### ISSUE THREAD

**Issue by omerap12** [kubernetes/autoscaler#7544]
**Which component are you using?**:
VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Currently we have unit tests in: [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction_test.go#L569) we need to include if an error is expected or not in each unit case ( otherwise we can just ignore some errors if they are expected but then we get a lint error (ref: https://github.com/kubernetes/autoscaler/pull/7542#discussion_r1863307336)
Opening this issue to track and address the problem so it isn’t overlooked.

**Describe the solution you'd like.**:
Each test should say if we expect an error or not.

**Describe any alternative solutions you've considered.**:

**Additional context.**:

**Comment by adrianmoisey** [comment]
/retitle VPA: add if error is expected in pods_eviction_restriction_test
