### ISSUE TITLE
VPA: Remove the vendor dir

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/autoscaler#7570]
**Which component are you using?**:
/area vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Remove the vendor dir for dev-productivity purposes. Right now, on updating dependencies the GitHub web app crashes. The vendor dir also causes delays while cloning the rep and while resolving conflicts (you get unnecessary conflicts under the vendor dir).

**Describe the solution you'd like.**:

Remove the vendor dir for the VPA. The cluster-autoscaler no longer has a vendor dir. It seems to be removed with https://github.com/kubernetes/autoscaler/pull/6973.

**Describe any alternative solutions you've considered.**:
N/A

**Additional context.**:

See https://github.com/kubernetes/autoscaler/pull/7551#issuecomment-2519495512

**Comment by adrianmoisey** [comment]
/open

Still waiting on https://github.com/kubernetes/autoscaler/pull/7572
