### ISSUE TITLE
Update flags for vpa components automatically

### ISSUE THREAD

**Issue by voelzmo** [kubernetes/autoscaler#7589]
**Which component are you using?**:
/area vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:
Keeping the flag documentation at https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/docs/faq.md#what-are-the-parameters-to-vpa-recommender up-to-date is a manual effort, which is cumbersome and error-prone.

**Describe the solution you'd like.**:
We should auto-generate the flag docs similar to https://github.com/kubernetes/autoscaler/pull/7014

Options are: running it automatically in our CI or putting it into some `make generate` command and force PR authors to run this before they submit with a pre-check.

**Comment by adrianmoisey** [comment]
+1

I also want to generate the API documentations automatically, which is something I'm busy working on

**Comment by omerap12** [comment]
Perhaps I'm mistaken, but it seems the documentation is not up to date. Having this script would be useful for keeping them current.
