### ISSUE TITLE
[AZURE] 

### ISSUE THREAD

**Issue by Drupi** [kubernetes/autoscaler#759]
Hello, I properly setup the autoscaler on Azure but .. I have this communication in POD logs. Every value is correct, base64 encrypted. Anyone had this problem ?

Failed to update node registry: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<Sub-ID>/resourceGroups/<Resource-group>/providers/Microsoft.Compute/virtualMachineScaleSets/agentpool1?api-version=2017-03-30: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

**Comment by feiskyer** [comment]
From the error message, subscription and resourceGroup are empty. Have you set them according to [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md)?

**Comment by Drupi** [comment]
Yes, I just delete them for the publishing purposes.

**Comment by Drupi** [comment]
I wondering why the standard deployment is pointing to the ScaleSets..

**Comment by feiskyer** [comment]
which image are you using? for standard deployment, you should use v1.2.0 version, e.g. `gcr.io/google_containers/cluster-autoscaler:v1.2.0`

**Comment by Drupi** [comment]
Great ! I changed the version and now it's working :) Thank you very much for help.. 

There is an error in Documentation ? There is written that for 1.9.X we should use ver. 1.1.X?

**Comment by feiskyer** [comment]
cluster-autoscaler v1.2.X is built with kubernetes v1.10, while v1.1.X is built with kubernetes v1.9. But Azure vmas support is added from v1.2.0.

@mwielgus @bskiba  Are there any known problems if v1.2.X is used with kubernetes v1.9.X?

**Comment by bskiba** [comment]
There is no specific issues that I am aware of, but we really do zero cross-version testing so cannot guarantee anything and can only quote the [FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#which-version-on-cluster-autoscaler-should-i-use-in-my-cluster).

> CA internally simulates k8s scheduler and using different versions of scheduler code can lead to subtle issues.

Basically there is a chance you would be alright, but you can also run into bugs where for example autoscaler is wrong about what scheduler would do and will not scale up the cluster when you think it should.

**Comment by bskiba** [comment]
Any chance you will be able to use 1.10?

**Comment by Drupi** [comment]
Think not. For now I'm testing scaling up and down. I will provide the feedback after tests.

**Comment by Drupi** [comment]
Hello, Yesterday I performed tests for scaling and everything is working well. So for now I'm closing the issue.
