### ISSUE TITLE
VPA: Document controlledResources

### ISSUE THREAD

**Issue by aurel333** [kubernetes/autoscaler#7597]
**Which component are you using?**:

/area vertical-pod-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Currently the VPA scales both the RAM and the CPU allocated to a container, but this may not always be desirable. For example JVM workload seem to not interact well with RAM scaling (as explained by others in [this issue](https://github.com/kubernetes/autoscaler/issues/5029).

**Describe the solution you'd like.**:

This feature request and the following PR (that I will do if this feature request is not rejected 🙂) aim to add a configuration in the VPA components (likely the recommender and maybe the webhook) to not act on the CPU or the memory

**Describe any alternative solutions you've considered.**:

- Target the VPA on workload that react correctly with it:
  - This is not good enough as most of the workload that would benefit from the VPA are Java applications

**Comment by adrianmoisey** [comment]
Are you looking for `controlledResources`? 
Take a look at this example: https://github.com/kubernetes/autoscaler/blob/e45c1d14ce9cd28d2b7e831edb343c7e6121c468/vertical-pod-autoscaler/examples/hamster.yaml#L8-L31

**Comment by aurel333** [comment]
Yes it was exactly this! I completely missed it, thank you

**Comment by adrianmoisey** [comment]
/retitle VPA: Document controlledResources
/kind documentation
/remove-kind feature
/reopen

I'm going to reopen this and use it as an issue to improve the documentation
