### ISSUE TITLE
Cluster Autoscaler does a list of pods for nodegroup instead of using informer

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/autoscaler#76]
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/nodes.go#L36

This is called for by BuildNodeInfoForNode, which is called for each node by GetNodeInfosForGroups. We should change it to informer.

cc: @mwielgus

**Comment by mwielgus** [comment]
This is not entirely true. We do it once per node group and only if there is a pending pod.

**Comment by MaciekPytel** [comment]
Right, you're correct. Which makes this much less of a priority, but we should still change it to informer at some point.
