### ISSUE TITLE
Calculate GPU count for least waste

### ISSUE THREAD

**Issue by resouer** [kubernetes/autoscaler#771]
Current least waste model may give you a GPU machine if CPU memory waste is similar.

We should calculate GPU in the score as well.

**Comment by resouer** [comment]
kindly ping @mwielgus , is this a valid feature request? Any blocker in your mind?

I can write up a patch if needed.

**Comment by mwielgus** [comment]
Please write a patch :).

**Comment by WebSpider** [comment]
This looks like a fun challenge for a go newbie and k8s dev newbie to look into,  so I would like to have a crack at this
