### ISSUE TITLE
Unable to scale up: no node info

### ISSUE THREAD

**Issue by EPinci** [kubernetes/autoscaler#776]
I'm using the autoscaler v1.2 on a Azure, VMAS, ACS-Engine deployed Kubernetes cluster.
Autoscaler is unable to scale up my cluster with:

```
I0405 08:17:06.844074       1 scale_up.go:59] Pod default/busybox-deployment-5b6d9ff767-vld8x is unschedulable
E0405 08:17:06.844119       1 scale_up.go:446] No node info for: nodepool1
E0405 08:17:06.844187       1 scale_up.go:122] No node info for: nodepool1
I0405 08:17:06.844259       1 scale_up.go:186] No expansion options
```

What am I missing in here?

Thank you.

**Comment by feiskyer** [comment]
@EPinci  Is `nodepool1` same with acs-engine's agentPoolProfiles name?

**Comment by EPinci** [comment]
Yes, nodepool1 is the name. Scaling down works (although with #775), scaling up fails.

**Comment by feiskyer** [comment]
Which version of Kubernetes are you running? Has useInstanceMetadata set to false for all nodes?

**Comment by EPinci** [comment]
I'm on v1.9.3 and nope, useInstanceMetadata has not been set to false in original ACS-Engine's json - is there a way to set that on an already existing cluster/nodes?

**Comment by feiskyer** [comment]
@EPinci It could be set in /etc/kubernetes/azure.json, but new nodes created by scaling up still set useInstanceMetadata to true (new nodes are still provisioned by original deploy templates).

By the way, autoscaler v1.2.X is recommended only to be used with kubernetes v1.10.X. See also [here](https://github.com/kubernetes/autoscaler/issues/759#issuecomment-377164622).

**Comment by feiskyer** [comment]
I think the issues has been resolved. Let's close it.

/close
