### ISSUE TITLE
AWS: updated instance type doesn't update cluster-autoscaler instance template

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/autoscaler#789]
In AWS, I updated my instance type for my autoscaling group's launch configuration and doubled the cpu and memory.

However, this didn't update the cluster-autoscaler instance template and I see that my Pods still won't schedule even though they'll fit on the new instance type:

```
  Normal   NotTriggerScaleUp  6s                 cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

Version:
```
          image: gcr.io/google_containers/cluster-autoscaler:v1.0.4
```

**Comment by aleksandra-malinowska** [comment]
Were there any instances in that group that weren't yet updated? Cluster Autoscaler uses an existing node from a group as "template", and falls back to reading group's template only if there are no existing nodes in it.

**Comment by julianvmodesto** [comment]
Ah yes, all but one of my nodes haven't been updated. My intent wasn't to rolling-update them, but only update the launch configuration so only new nodes are created with more resources.

Would it be feasible to change this default behavior and reverse it? What would the implications / side effects be?

From a user's intent, it's closer to what I want e.g. as a user, I expected cluster-autoscaler to scale up since if it did, the new template would be used, not the old one.

**Comment by aermakov-zalando** [comment]
I agree with @julianvmodesto. The group template (launch configuration in AWS) is a much better representation on what the newly created node would look like, and this is what matters when scaling up. It also simplifies the mental model of how the autoscaler behaves and gets rid of the nasty edge cases when node configuration is changed. For example, our cluster upgrade process sets a `lifecycle-status=decommission-pending` label on all nodes that would be removed during the upgrade and new nodes come up with `lifecycle-status=ready`. However, one of the users decided to add a node selector matching only `lifecycle-status=ready` nodes (which is something you would expect to work) and during the next cluster upgrade the pods were stuck in Pending without triggering scale up.

**Comment by tecnobrat** [comment]
I was trying to find out if there is a way to do something where when and ASG it updated to a new launch template that the cluster autoscaler noticed that the LT has changed, and has new instance types on it, or simply just a new AMI.  Then autoscaler is responsible for decommissioning and terminating instances one by one in a rolling fashion.

The idea is that autoscaler is responsible for my nodes, and also ensuring that my nodes are running based on the latest LT.

**Comment by aweeks** [comment]
I just wanted to report that I think this issue continues to be relevant.  I ran into a cluster-autoscaler problem today that seems to be related.

Repro steps:

1. Create ASG with launch configuration for instance type A
2. Ensure that no instances of this ASG exist (desired capacity = 0)
3. Modify launch configuration to use instance type B, where B has more CPU/memory capacity than B
4. Create pod with a request that is too large to fit on instance type A, but DOES fit on instance type B

CAS will then fail to scale up the ASG, with the following message
```
I1109 01:09:47.803817       1 scale_up.go:288] Pod XXX can't be scheduled on asg-YYY, predicate checking error: Insufficient cpu; predicateName=NodeResourcesFit; reasons: Insufficient cpu; debugInfo=
```

To unstick CAS, you can manually set desired capacity = 1.  It appears as though CAS recognizes the updated capacity information as soon as it sees a single example of the new node type in the ASG.

**Comment by jrouly** [comment]
I am also continuing to see this issue (cluster-autoscaler helm chart version `9.18.0`).

Manually bringing up an instance in the auto scaling group by setting Desired Capacity to one does appear to "teach" the autoscaler about the resources available in the group, but it also appears to "forget" this when the pods are shuffled around.

We are using EKS managed node groups on AWS with Launch Templates. Other than that difference, the repro steps provided by @aweeks match mine exactly.
