### ISSUE TITLE
aws - autoscaler failing with Wrong id: expected format aws:///<zone>/<name>

### ISSUE THREAD

**Issue by sujithvs74** [kubernetes/autoscaler#790]
I have deployed autoscaler in aws with auto discovery option and application fails with below error,

> I0411 03:07:37.172013       1 polling_autoscaler.go:111] Poll finished
I0411 03:07:37.172031       1 static_autoscaler.go:97] Starting main loop
I0411 03:07:37.353080       1 reflector.go:428] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174: Watch close - *v1.Pod total 0 items received
I0411 03:07:37.355165       1 round_trippers.go:436] GET https://10.96.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=3644534&timeoutSeconds=422&watch=true 200 OK in 1 milliseconds
W0411 03:07:37.393124       1 clusterstate.go:514] Failed to get nodegroup for dev-k8s-node-asg-230-i-089e4d2f163533989: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.393145       1 clusterstate.go:514] Failed to get nodegroup for stg-k8s-w2-npe-master-3: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.393152       1 clusterstate.go:514] Failed to get nodegroup for dev-k8s-node-prm-1: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.393158       1 clusterstate.go:514] Failed to get nodegroup for dev-k8s-node-asg-230-i-0eb3341fce85be39c: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.393164       1 clusterstate.go:514] Failed to get nodegroup for dev-k8s-node-asg-230-i-091d1a037311d5daf: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.393169       1 clusterstate.go:514] Failed to get nodegroup for dev-k8s-node-asg-230-i-041dd54f2baaa4553: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.393188       1 clusterstate.go:560] Readiness for node group dev-k8s-node-asg-230 not found
W0411 03:07:37.393203       1 clusterstate.go:560] Readiness for node group stg-k8s-agent-w2-asg not found
I0411 03:07:37.393235       1 static_autoscaler.go:162] 7 unregistered nodes present
I0411 03:07:37.393266       1 static_autoscaler.go:230] Filtering out schedulables
I0411 03:07:37.393358       1 static_autoscaler.go:240] No schedulable pods
I0411 03:07:37.393378       1 static_autoscaler.go:244] No unschedulable pods
I0411 03:07:37.393392       1 static_autoscaler.go:280] Calculating unneeded nodes
W0411 03:07:37.476803       1 utils.go:394] Error while checking node group for dev-k8s-node-asg-230-i-089e4d2f163533989: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.476828       1 utils.go:394] Error while checking node group for stg-k8s-w2-npe-master-3: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.476835       1 utils.go:394] Error while checking node group for dev-k8s-node-prm-1: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.476839       1 utils.go:394] Error while checking node group for dev-k8s-node-asg-230-i-0eb3341fce85be39c: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.476845       1 utils.go:394] Error while checking node group for dev-k8s-node-asg-230-i-091d1a037311d5daf: Wrong id: expected format aws:///<zone>/<name>, got
W0411 03:07:37.476849       1 utils.go:394] Error while checking node group for dev-k8s-node-asg-230-i-041dd54f2baaa4553: Wrong id: expected format aws:///<zone>/<name>, got
I0411 03:07:37.477001       1 static_autoscaler.go:309] Scale down status: unneededOnly=true lastScaleUpTime=2018-04-11 03:00:49.050134466 +0000 UTC lastScaleDownDeleteTime=2018-04-11 03:00:49.050135304 +0000 UTC lastScaleDownFailTime=2018-04-11 03:00:49.05013595 +0000 UTC schedulablePodsPresent=false isDeleteInProgress=false
W0411 03:07:37.477028       1 clusterstate.go:346] Failed to find readiness information for dev-k8s-node-asg-230
W0411 03:07:37.477037       1 clusterstate.go:403] Failed to find readiness information for dev-k8s-node-asg-230
W0411 03:07:37.477041       1 clusterstate.go:346] Failed to find readiness information for dev-k8s-node-asg-230
W0411 03:07:37.477049       1 clusterstate.go:346] Failed to find readiness information for stg-k8s-agent-w2-asg
W0411 03:07:37.477060       1 clusterstate.go:403] Failed to find readiness information for stg-k8s-agent-w2-asg
W0411 03:07:37.477064       1 clusterstate.go:346] Failed to find readiness information for stg-k8s-agent-w2-asg
I0411 03:07:37.479834       1 round_trippers.go:436] GET https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status 200 OK in 2 milliseconds

**Comment by trondhindenes** [comment]
I can repro. Because of some limitations with the "cloud-provider" flag in kube-apiserver/kubelet, we're running non-aws-integrated clusters on ec2. I'd still like to use autoscaling instead of building my own. I'm assuming this is why this error appears: 
`clusterstate.go:517] Failed to get nodegroup for ldm-0110069: Wrong id: expected format aws:///<zone>/<name>` 

I guess my question is: Is there any way of getting cluster-autoscaling working without the "cloud-provider" flag set in kube-apiserver/kubelet ?

**Comment by aleksandra-malinowska** [comment]
> I guess my question is: Is there any way of getting cluster-autoscaling working without the "cloud-provider" flag set in kube-apiserver/kubelet ?

Set ProviderId field in node's spec.

Cluster Autoscaler resizes the cluster by deleting or creating VMs. In particular, it needs to know which VM to delete to make a specific node disappear. The only way to find out this information is from the node's ProviderId field. What the kubelet flag does is (among other things) make sure all nodes have this field set to the id of the underlying VM. The format is different for each cloud provider, but the basic mechanism is the same.

**Comment by trondhindenes** [comment]
Thanks @aleksandra-malinowska  - I guess all of this points back to the fact that the "cloud-provider" stuff in Kubernetes core simply aren't well enough documented. It's incredibly hard to figure out what "happens" when the cloud provider flags aren't set.

**Comment by sujithvs74** [comment]
I followed https://docs.google.com/document/d/17d4qinC_HnIwrK0GHnRlD1FKkTNdN__VO4TH9-EzbIY/edit to enable cloud provider for my cluster, after that I didn't see above error. But its true cloud-provider integrations are not well documented.
