### ISSUE TITLE
Autoscaling Azure nodepool to zero

### ISSUE THREAD

**Issue by EPinci** [kubernetes/autoscaler#796]
Is it possible to scale down to zero nodes a nodepool on Azure?

**Comment by EPinci** [comment]
@feiskyer Do you have any information on this?

**Comment by EPinci** [comment]
@feiskyer I see. I'm using VMAS.

**Comment by feiskyer** [comment]
Filed #823 to fix the issue

**Comment by EPinci** [comment]
@ewok2030, you might want to take note of this... :)

**Comment by Shaked** [comment]
Hey, although it's an old thread, I was wondering how can I autoscale down to zero nodes following the attached PR #823? 

Couldn't find it anywhere. 

Thank you!
Shaked
