### ISSUE TITLE
How to protect pods from node scale down

### ISSUE THREAD

**Issue by resouer** [kubernetes/autoscaler#812]
Is there any way to prevent scale down happen if there's some specific pods running on it?

The use case is sometimes, there are some pods that can not be killed until they exit by themselves.

**Comment by aleksandra-malinowska** [comment]
The cleanest way would be probably to create a PodDisruptionBudget with min unavailable set to 0 (or whatever works for your case.) 

See [What types of pods can prevent CA from removing a node?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) for more information on what else can prevent a pod from being evicted during scale-down.

**Comment by resouer** [comment]
Thanks, I think it should be `minAvailable=1`
