### ISSUE TITLE
 cluster-autoscaler-status configmap does not mirror changes in AWS ASG

### ISSUE THREAD

**Issue by danbondd** [kubernetes/autoscaler#819]
I'm not entirely sure if this is an issue, or my misconfiguration, but I am running the `cluster-autoscaler:1.1.0` on `kubernetes:1.9.7` and the cluster-autoscaler-status configmap does not dynamically pull changes made to an AWS Auto Scaling Group.

I manually updated the maxSize of an ASG in the AWS console and the cluster-autoscaler-status configmap was never updated. I waited at least 2 hours before I manually restarted the pod and it pulled the latest config.

Is this the desired functionality or do I have something misconfigured? I am using the example [deployment](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml).

**Comment by aleksandra-malinowska** [comment]
It's a known issue/feature request: #209, #647. Contributions are welcome :)

Closing as it duplicates the above issues.
