### ISSUE TITLE
Issue with the vendoring

### ISSUE THREAD

**Issue by prashanth26** [kubernetes/autoscaler#820]
Hi,
    I was trying to re-vendor (on the release-1.1, release-1.2 and master) using to Godep but was running into these errors. Is the vendoring really broken, or am I missing something here? Any inputs would be helpful.

prashanth@C02V64QBHTD6 ~/G/s/k/a/cluster-autoscaler> git checkout cluster-autoscaler-release-1.1
Branch cluster-autoscaler-release-1.1 set up to track remote branch cluster-autoscaler-release-1.1 from origin.
Switched to a new branch 'cluster-autoscaler-release-1.1'
prashanth@C02V64QBHTD6 ~/G/s/k/a/cluster-autoscaler> godep save
godep: Package (github.com/Microsoft/hcsshim) not found
prashanth@C02V64QBHTD6 ~/G/s/k/a/cluster-autoscaler> godep restore
\# cd /Users/prashanth/Gotemp3/src/github.com/appc/spec; git checkout 191882f834bc779082c4664ed5d464e28d22b270
fatal: reference is not a tree: 191882f834bc779082c4664ed5d464e28d22b270
godep: error downloading dep (github.com/appc/spec/schema): exit status 128
\# cd /Users/prashanth/Gotemp3/src/github.com/aws/aws-sdk-go; git checkout 9c92d9960e4dc397caa84af12ad6513cf78c0b3f
fatal: reference is not a tree: 9c92d9960e4dc397caa84af12ad6513cf78c0b3f
godep: error downloading dep (github.com/aws/aws-sdk-go/aws): exit status 128
\# cd /Users/prashanth/Gotemp3/src/github.com/containerd/containerd; git checkout c8106ff35532072e317a71cce55f18e7917cafcb
fatal: reference is not a tree: c8106ff35532072e317a71cce55f18e7917cafcb
godep: error downloading dep (github.com/containerd/containerd/api/services/containers/v1): exit status 128
\# cd /Users/prashanth/Gotemp3/src/github.com/containernetworking/cni; git checkout 63a263a1942c52411f51677dde8b56710874cbb5
fatal: reference is not a tree: 63a263a1942c52411f51677dde8b56710874cbb5
godep: error downloading dep (github.com/containernetworking/cni/libcni): exit status 128
^C⏎           
                                                                                                                                                                           
prashanth@C02V64QBHTD6 ~/G/s/k/a/cluster-autoscaler> git checkout cluster-autoscaler-release-1.2
Checking out files: 100% (10542/10542), done.
Branch cluster-autoscaler-release-1.2 set up to track remote branch cluster-autoscaler-release-1.2 from origin.
Switched to a new branch 'cluster-autoscaler-release-1.2'
prashanth@C02V64QBHTD6 ~/G/s/k/a/cluster-autoscaler> godep save
godep: Package (bitbucket.org/ww/goautoneg) not found
prashanth@C02V64QBHTD6 ~/G/s/k/a/cluster-autoscaler>

Thanks in advance. 

Regards,
Prashanth

**Comment by aleksandra-malinowska** [comment]
It is broken in a way. For various reasons, mostly dependency on kubernetes/kubernetes and the way kubernetes/kubernetes deals with its own dependencies, simple godep save/restore doesn't work for this component. See https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-update-ca-dependencies-particularly-k8siokubernetes for step-by-step instructions for updating dependencies.

**Comment by prashanth26** [comment]
@aleksandra-malinowska Thanks for this. It took me a while to get the dependencies working even with that link. I was missing the _override google api package. Anyways it works now. 

Thanks a lot 👍
