### ISSUE TITLE
Documents not comprehensible

### ISSUE THREAD

**Issue by markbooch** [kubernetes/autoscaler#840]
the document shows "The /etc/ssl/certs/ca-certificates.crt should exist by default on your ec2 instance."
but no other information indicates the purpose of this requirment, and what does it means the specific certificate?

see more:
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#common-notes-and-gotchas

**Comment by PaulFurtado** [comment]
Also really curious about this. Does anyone know why the cluster autoscaler singles out that the ca certificates should be mounted, but no other kubernetes infrastructure does? It seems like an odd requirement.
