### ISSUE TITLE
Scale down never occur when the node group auto-discovery feature is enabled

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/autoscaler#85]
This was originally [reported in the kube-aws repo](https://github.com/kubernetes-incubator/kube-aws/issues/677).

In nutshell, PollingAutoscaler, which is used only when the auto-discovery feature is enabled, is resetting `lastScaleDownFailedTrial` to the current time before each iteration of CA.
`lastScaleDownFailedTrial` must be maintained properly among different instances of StaticAutoscaler created per an iteration of CA=a node groups poll.

**Comment by MaciekPytel** [comment]
@mumoshu can you take a look at that? We can't introduce new feature (auto-discovery) in 0.6 if we know using it basically breaks CA.

**Comment by mumoshu** [comment]
@MaciekPytel Thanks for checking in - Sure thing! I'll submit a PR today
