### ISSUE TITLE
Autoscaling a acs-engine deployed cluster after upgrading deploys the wrong Kubernetes version

### ISSUE THREAD

**Issue by ofcourseican** [kubernetes/autoscaler#860]
I have the node autoscaler installed in a cluster that I deployed through acs-engine.

After the initial deployment I upgraded the cluster from v1.9.6 to v1.10.1 through the acs-engine upgrade command.

Now whenever the autoscaler scales up, I get a new v1.9.6 node up and running.

I think the autoscaler should deploy a node with the version that cluster is currently running on.

A workaround I can think of would be to just modify the azuredeploy.parameters.json file/cluster-autoscaler-azure-deploy-parameters secret and put in the new version. But that would mean, that whenever updating I also would need to patch that file.

**Comment by aleksandra-malinowska** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@ofcourseican Confirmed the issue, this is because of using old deployment templates and parameters (only exists win VMAS clusters).

Delete the autoscaler deployment and secret, then re-deploy autoscaler should fix the issue.

Let me add a document for such cases.

**Comment by ofcourseican** [comment]
Sounds like a valid solution for now.

Just one question: Should I get a new azuredeploy.parameters.json after upgrading the cluster? And is there any way to get that file from the running cluster. Asking for a friend of course ;)

**Comment by feiskyer** [comment]
> I just did another upgrade from 1.10.1 to 1.10.2 in that cluster. Unfortunately even after the update the azuredeploy.parameters.json does not change.

Confirmed the issue, let me check with acs-engine folks.

**Comment by ofcourseican** [comment]
@feiskyer any progress on this? Can I help sorting this out in any way?

**Comment by feiskyer** [comment]
@ofcourseican not yet, acs-engine should be updated and save new generated templates/parameters when running upgrade.

**Comment by ofcourseican** [comment]
@feiskyer I tried the latest acs-engine versions. Still no luck 😢

**Comment by feiskyer** [comment]
> @feiskyer I tried the latest acs-engine versions. Still no luck 😢

Sorry, this is still not supported yet. We will add this to acs-engine soon.

**Comment by feiskyer** [comment]
this is still happening today

/reopen

**Comment by mo-saeed** [comment]
@feiskyer any updates here, do you have any workaround ?

**Comment by feiskyer** [comment]
@mo-saeed not yet, this is still a known issue. It's recommended not to run aks-engine upgrade for CA running clusters. See https://github.com/Azure/aks-engine/issues/401 and https://github.com/Azure/aks-engine/issues/400.

**Comment by mboersma** [comment]
Both Azure/aks-engine#400 and Azure/aks-engine#401 are now closed, so with the next AKS Engine release we should (finally) see upgrade working with cluster-autoscaler enabled.

After that, if we find any bugs relating to upgrade with cluster-autoscaler, please [open an issue](https://github.com/Azure/aks-engine/issues/new?assignees=&labels=bug&template=bug_report.md&title=) at the AKS Engine project and we'll pounce on it.

**Comment by mo-saeed** [comment]
@mboersma Thanks for the updates, that's good news !
Just one question, the problem i had before when upgrading a cluster with cluster-autoscaling enabled is that after the upgrade process, autoscaler will scale nodes with the older version of kubernetes as it uses the old VMSS ARM template and the fix was to delete and recreate the autoscaler. doest this PR fix this issue as well ?

**Comment by mboersma** [comment]
@mo-saeed that's not explicitly something this fixes, although before this there were cases where it could fail and not all nodes would be a newer Kubernetes version. I haven't seen the behavior you describe, however, when testing upgrade numerous times against multiple node pools with cluster-autoscaler enabled.

So...maybe fixed? If you are able to test with aks-engine master or try with a future minor release, please do open an issue if it isn't.

**Comment by feiskyer** [comment]
Close per https://github.com/kubernetes/autoscaler/issues/860#issuecomment-498400958

/close
