### ISSUE TITLE
Simplify vendor updates for cluster-autoscaler

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/autoscaler#877]
Cluster-autoscaler introduces a `fix_gopath.sh` scripts for packages not in kubernetes/kubernetes repo. It makes vendor updates complicated and `godep restore` not working because of commits changed in original packages.

I suggest we switch to godep for all packages, including k/k vendors and outside packages. With this method, a simple vendor update process is only with two commands:

```
godep restore
godep save ./...
```

**Comment by MaciekPytel** [comment]
@mwielgus is more knowledgeable about it than I am. AFAIK he wrote the script, because we've regularly run into problems with repos that are duplicated in kubernetes /staging (when the repo and what was in staging were out of sync).

**Comment by feiskyer** [comment]
> we've regularly run into problems with repos that are duplicated in kubernetes /staging (when the repo and what was in staging were out of sync).

Do we still have staging sync issues today?
