### ISSUE TITLE
Failed to (Auto)Scale nodes on Azure using VMSS

### ISSUE THREAD

**Issue by rofreitas** [kubernetes/autoscaler#881]
Kubernetes 1.10.2
Auto Scaler 1.2.1

Error: Specified api-version 2017-03-30 does not meet the minimum required api-version 2017-12-01 to set this property enableIPForwarding.

LOG's POD: 
{"log":"E0517 17:01:46.612618       1 azure_scale_set.go:138] virtualMachineScaleSetsClient.CreateOrUpdate for scale set \"k8s-medium-11014877-vmss\" failed: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code=\"MinimumApiVersionNotSpecifiedToSetTheProperty\" Message=\"Specified api-version 2017-03-30 does not meet the minimum required api-version 2017-12-01 to set this property enableIPForwarding.\"\n","stream":"stderr","time":"2018-05-17T17:01:46.612903996Z"}
{"log":"W0517 17:01:46.612720       1 clusterstate.go:248] Disabling scale-up for node group k8s-medium-11014877-vmss until 2018-05-17 17:11:46.612713696 +0000 UTC\n","stream":"stderr","time":"2018-05-17T17:01:46.612960796Z"}

**Comment by feiskyer** [comment]
@rofreitas This is a known limitation of Azure API. Could you try with autoscalcer 1.2.2 ?

**Comment by rofreitas** [comment]
Hello @feiskyer, yes, we have. With 1.2.2 version we have this log once

}
{"log":"I0518 14:08:11.981238       1 azure_client.go:305] azure: using client_id+client_secret to retrieve access token\n","stream":"stderr","time":"2018-05-18T14:08:11.98421133Z"}
{"log":"E0518 14:17:41.987265       1 azure_scale_set.go:199] VirtualMachineScaleSetVMsClient.List failed for k8s-low-11014877-vmss: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/30a25c0e-1b63-4aa3-9240-834cf5725970/resourceGroups/k8s_acs/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-low-11014877-vmss/virtualMachines?api-version=2017-12-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/41b8b3dc-75f9-4731-afd1-7e15af53e66a/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.244.0.10:53: dial udp 10.244.0.10:53: i/o timeout'\n","stream":"stderr","time":"2018-05-18T14:17:41.987564467Z"}
{"log":"F0518 14:17:41.987360       1 cloud_provider_builder.go:162] Failed to create Azure Manager: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/30a25c0e-1b63-4aa3-9240-834cf5725970/resourceGroups/k8s_acs/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-low-11014877-vmss/virtualMachines?api-version=2017-12-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/41b8b3dc-75f9-4731-afd1-7e15af53e66a/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 10.244.0.10:53: dial udp 10.244.0.10:53: i/o timeout'\n","stream":"stderr","time":"2018-05-18T14:17:41.987629767Z"}

and them there is no more log. Even if I kill the POD there is no new logs.

**Comment by feiskyer** [comment]
seems your pod couldn't reach external network. Could you check whether the kube-dns is working as expected?

**Comment by rofreitas** [comment]
Hi @feiskyer , thank you for answering me.

You are right. As I had deleted and recreated the cluster using ACS and I had forgotten to associate route table to subnet on Azure. After do that the autoscaler 1.2.2 worked very well. 

For others with the same problem, after generate the files with ACS generate, changes the "azuredeploy.parameters" for 

    "kubernetesClusterAutoscalerSpec": {
      "value": "k8s-gcrio.azureedge.net/cluster-autoscaler:v1.2.**2**"

This needs to be set at this step because the cluster has a scritp.sh which overwrites the yaml even if you set the cluster-auto-scaler.yaml on the master.

**Comment by feiskyer** [comment]
FYI: acs-engine has upgraded cluster-autoscaler to v1.2.2. See https://github.com/Azure/acs-engine/pull/3014

**Comment by rofreitas** [comment]
Thanks.
