### ISSUE TITLE
Autoscaler 0.6.2 crashing - Failed to describe ASG tags - NoCredentialProviders

### ISSUE THREAD

**Issue by tmwtp** [kubernetes/autoscaler#890]
Hi,

We have the 0.6.2 version installed and running on our clusters for some time now.

I am trying to deploy it into one of our lab clusters now and getting the following error:

I0523 13:41:00.590344       1 auto_scaling.go:133] Failed to describe ASG tags for keys [k8s.io/cluster-autoscaler/enabled kubernetes.io/cluster/XXXXXXXXXX] : NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F0523 13:41:00.590414       1 cloud_provider_builder.go:91] Failed to create AWS cloud provider: Failed to get ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

1. We are working with k8s version 1.7.5

2. We have both tags needed on both masters and nodes:

k8s.io/cluster-autoscaler/enabled & kubernetes.io/cluster/XXXXXX

3. We have the proper IAM permissions for the service to work:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}

Will appreciate your help here

Thanks,

Roiy

**Comment by rsignell-usgs** [comment]
@tmwtp , did you ever figure this out?  
I'm hitting the exact same problem.

**Comment by SongGithub** [comment]
I am having the same problem. k8s=1.11, autoscaler=1.3.1

**Comment by squarell0805** [comment]
We met same problem with k8s=1.11.3, autoscaler=1.3.3.  But k8s=1.9.6 with autoscaler=1.1.1 succeed.

**Comment by bhargavkeshav** [comment]
Issue still exists 
`E1014 20:05:28.980584       1 aws_manager.go:148] Failed to regenerate ASG cache: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
F1014 20:05:28.980605       1 aws_cloud_provider.go:330] Failed to create AWS Manager: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors`

image:
  repository: k8s.gcr.io/cluster-autoscaler
  tag: v1.13.1

**Comment by bhargavkeshav** [comment]
Please reopen this issue?
