### ISSUE TITLE
Autoscaler + Jobs + Scheduler (RoundRobin) = overrequest of resources

### ISSUE THREAD

**Issue by Sturgelose** [kubernetes/autoscaler#892]
We are using Node Autoscaler in AWS in order to manage our batch processing spikes done with kubernetes Jobs at certain hours of the day. However we are seeing a bit of incompatibility between the default kube-scheduler logic and Autoscaler.

1. Autoscaler won't kill nodes if there are Jobs running (expected). We can't stop a Job mid way.
2. kube-scheduler always deploys pods with a round-robin schedule. 

This means that if we start many jobs one after the other, after the spike, we end with multiple nodes started (because we needed more resources before during the spike). After the spike, most of the nodes end with a  usage under 50% of resources because round-robin scheduling works as expected and Jobs get distributed but autoscaler cannot kill nodes because they are jobs. Also, autoscaler will only decrease the cluster if the node has no Job scheduled during 10 min.

Could there be an option to maybe mark a node with under usage as non-schedulable (cordonated) when there are **many** nodes with low resource usage?  This way, we give time to the Job to end but without adding extra jobs in the node. If we would need to start a new node, we just need to allow scheduling in the node again instead of starting a new node!

Otherwise, while we are waiting for it to end, other jobs will be scheduled in the same node and start the loop again and we will end with tons of nodes with just a single node running in each node... (costly in terms of money....)

An other option is to create a custom scheduler instance, but I thought that as the issue comes with the autoscaler logic, it would make more sense to implement here.

I'd be willing to help developing this if anyone can give me some pointers on where the logic is implemented :)

**Comment by aleksandra-malinowska** [comment]
The taint's effect should probably be PreferNoSchedule. This way, Cluster Autoscaler wouldn't even need to remove it to allow scheduling pods on a node if there's no place elsewhere in the cluster. It would have to untaint the node only if it was no longer a candidate for removal (and probably clear it at startup/shutdown time, too.) 

Adding the taint for nodes that are already candidates for scale-down would probably be straightforward - there are clear points at which they start/stop to be considered for removal. What would be a bit more complicated is special treatment for non-replicated pods (such as jobs). This would require splitting the logic that decides whether a node can be removed into something that says the node can't be considered for removal at all, and something that says "not now". The tricky part may be deciding what should be considered a blocker for adding the taint, so that we don't taint the entire cluster.

**Comment by Sturgelose** [comment]
True, I just started today going through the documentation of the scheduler and taints, so didn't know about the PreferNoSchedule 😅

Anyways, my proposal was more related towards the case where I have 2 candidate nodes to be downscaled (which is usual in my cluster). These 2 nodes have been marked as candidates during the last 3 hours, but they are not being evicted because of the jobs being scheduled on them afterwards. If they were tainted, they would had eventually been evicted, so the solution already fixes the issues with jobs :)

I guess that just setting the PreferNoschedule taint ONLY when a node it's an eviction candidate, would force to fill non candidate nodes. If a candidate gets a scheduled pod it's because there is nowhere else to put it, and would eventually stop being a candidate after being filled a bit.

The other discussion is how the PreferNoschedule gets applied when there are multiple nodes with this taint. If it's a round-robin again, then we have a similar issue as the initial one. 

So, proposal:
* case 1 eviction candidate node: we set the PreferNoschedule taint to this node
* case 2+ eviction candidate nodes: the most filled node gets set a PreferNoschedule taint and the rest get set a NoSchedule taint (or something like this).

As we fill a node, a node will eventually stop being a candidate, and we can set the a PreferNoSchedule to the other candidate node. 
The only extreme case I can think about is when you have a node with space, but you are trying to schedule a pod that is too big for it. Then, either we find a NoSchedule pod and change the taint, or either we might have to start a new node.

**Comment by aleksandra-malinowska** [comment]
>  These 2 nodes have been marked as candidates during the last 3 hours, but they are not being evicted because of the jobs being scheduled on them afterwards. If they were tainted, they would had eventually been evicted, so the solution already fixes the issues with jobs :)

Not sure if we mean the same thing by "candidate" - in its internal state, Cluster Autoscaler only tracks nodes that are underutilized and can be drained in simulation. A node with pods that belong to a Job (or don't belong to any controller) won't be considered. In your example, we'd like to taint such node. On the other hand, a node running a kube-system pod also won't be considered, and we don't want to taint it in hope that pod dies.

> case 2+ eviction candidate nodes: the most filled node gets set a PreferNoschedule taint and the rest get set a NoSchedule taint (or something like this).

This sounds fairly complicated, and placing NoSchedule taint on nodes that we aren't sure we can ever remove doesn't sound good.

A simpler way to address this may be to limit the number of currently tainted nodes, probably depending on the size of the cluster (e.g. we can't taint more than X% of nodes at any time.) This of course leaves other questions, e.g. should we remove the taint after some time if the node isn't removed after all?

**Comment by Sturgelose** [comment]
Sorry, about candidate, I meant what is shown here in the ConfigMap created by clusterAutoscaler to track what is happening:
```
Cluster-autoscaler status at 2018-05-24 14:25:02.994903007 +0000 UTC:
Cluster-wide:
  Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=0)
               LastProbeTime:      2018-05-24 14:25:02.628848337 +0000 UTC
               LastTransitionTime: 2018-04-09 12:49:57.825487148 +0000 UTC
  ScaleUp:     NoActivity (ready=3 registered=3)
               LastProbeTime:      2018-05-24 14:25:02.628848337 +0000 UTC
               LastTransitionTime: 2018-05-24 14:02:06.555877827 +0000 UTC
  ScaleDown:   CandidatesPresent (candidates=1)
               LastProbeTime:      2018-05-24 14:25:02.628848337 +0000 UTC
               LastTransitionTime: 2018-05-24 14:20:55.824780234 +0000 UTC

NodeGroups:
  Name:        nodes.kubernetes.example.com
  Health:      Healthy (ready=2 unready=0 notStarted=0 longNotStarted=0 registered=2 longUnregistered=0 cloudProviderTarget=2 (minSize=1, maxSize=5))
               LastProbeTime:      2018-05-24 14:25:02.628848337 +0000 UTC
               LastTransitionTime: 2018-04-09 12:49:57.825487148 +0000 UTC
  ScaleUp:     NoActivity (ready=2 cloudProviderTarget=2)
               LastProbeTime:      2018-05-24 14:25:02.628848337 +0000 UTC
               LastTransitionTime: 2018-05-24 14:02:06.555877827 +0000 UTC
  ScaleDown:   CandidatesPresent (candidates=1)
               LastProbeTime:      2018-05-24 14:25:02.628848337 +0000 UTC
               LastTransitionTime: 2018-05-24 14:20:55.824780234 +0000 UTC
```
As you see, I have 1 "candidate" to be evicted. The reason is that right now I have only 1 pod of a job running there, but it's not triggering any scale down because of it being part of a job. So I guess that it's a candidate to scale down because of its resources usage, but not getting evicted because of the job. So, yes, this would be a node to be tainted case. 

A bit my guess with all this is that autoscaler already does some calculus in order to define potential candidates that can be deleted in the future, so it's making use of this in order to take tainting decisions.

And yes, I agree that nodes with "kube-system" pods shouldn't be tainted at all ;)

**Comment by aleksandra-malinowska** [comment]
> As you see, I have 1 "candidate" to be evicted. The reason is that right now I have only 1 pod of a job running there, but it's not triggering any scale down because of it being part of a job. So I guess that it's a candidate to scale down because of its resources usage, but not getting evicted because of the job. So, yes, this would be a node to be tainted case.

Can you provide Cluster Autoscaler logs related to nodes in that node group? Status is updated using the same list of nodes as is used for actual scale-down. If we were considering nodes, but not removing them because of a known blocker (in this case, non-replicated pods), it would suggest there's a bug.

**Comment by Sturgelose** [comment]
Here you have (I changed some names for privacy reasons ;) )
```
E0524 13:17:49.270847       1 scale_down.go:762] Not deleted yet &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:dashboard-798d748cb8-mqt2d,GenerateName:dashboard-798d748cb8-,Namespace:dev,SelfLink:/api/v1/namespaces/dev/pods/dashboard-798d748cb8-mqt2d,UID:cece8349-5f46-11e8-84ce-066abd78f814,ResourceVersion:39241529,Generation:0,CreationTimestamp:2018-05-24 11:37:15 +0000 UTC,DeletionTimestamp:2018-05-24 13:18:19 +0000 UTC,DeletionGracePeriodSeconds:*30,Labels:map[string]string{app: dashboard,environment: dev,pod-template-hash: 3548304764,version: v0.4.0,},Annotations:map[string]string{kubernetes.io/created-by: {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"dev","name":"dashboard-798d748cb8","uid":"3e4e0ac4-59cb-11e8-84ce-066abd78f814","apiVersion":"extensions","resourceVersion":"37336374"}}
,},OwnerReferences:[{extensions/v1beta1 ReplicaSet dashboard-798d748cb8 3e4e0ac4-59cb-11e8-84ce-066abd78f814 0xc421545728 0xc421545729}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[{default-token-pj9mx {nil nil nil nil nil SecretVolumeSource{SecretName:default-token-pj9mx,Items:[],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{dashboard artifacts.example.es/dashboard:1.2.2-dev [] []  [{http 0 3000 TCP }] [] [] {map[] map[cpu:{{10 -3} {<nil>} 10m DecimalSI} memory:{{64 6} {<nil>} 64M DecimalSI}]} [{default-token-pj9mx true /var/run/secrets/kubernetes.io/serviceaccount  <nil>}] Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:80,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:90,TimeoutSeconds:10,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:80,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:30,TimeoutSeconds:10,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} nil /dev/termination-log File Always nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{},ServiceAccountName:default,DeprecatedServiceAccount:default,NodeName:ip-172-20-40-224.eu-west-1.compute.internal,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,},ImagePullSecrets:[{docker-donkey-artifacts}],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[{node.alpha.kubernetes.io/notReady Exists  NoExecute 0xc4215459e0} {node.alpha.kubernetes.io/unreachable Exists  NoExecute 0xc421545a00}],HostAliases:[],PriorityClassName:,Priority:nil,},Status:PodStatus{Phase:Running,Conditions:[{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-05-24 11:37:15 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2018-05-24 11:37:48 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-05-24 11:37:15 +0000 UTC  }],Message:,Reason:,HostIP:172.20.40.224,PodIP:100.96.160.141,StartTime:2018-05-24 11:37:15 +0000 UTC,ContainerStatuses:[{dashboard {nil ContainerStateRunning{StartedAt:2018-05-24 11:37:18 +0000 UTC,} nil} {nil nil nil} true 0 artifacts.example.es/dashboard:1.2.2-dev docker-pullable://artifacts.example.es/dashboard@sha256:697992c3107abdedd613dd9fbc833a838fd36776d5c1915a2267835e03b10687 docker://39ae1221ce23b35b13242a871151e73c71ca676fbab0585f813125e15ab29e36}],QOSClass:Burstable,InitContainerStatuses:[],},}
E0524 13:17:54.276724       1 scale_down.go:762] Not deleted yet &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:dashboard-798d748cb8-mqt2d,GenerateName:dashboard-798d748cb8-,Namespace:dev,SelfLink:/api/v1/namespaces/dev/pods/dashboard-798d748cb8-mqt2d,UID:cece8349-5f46-11e8-84ce-066abd78f814,ResourceVersion:39241552,Generation:0,CreationTimestamp:2018-05-24 11:37:15 +0000 UTC,DeletionTimestamp:2018-05-24 13:18:19 +0000 UTC,DeletionGracePeriodSeconds:*30,Labels:map[string]string{app: dashboard,environment: dev,pod-template-hash: 3548304764,version: v0.4.0,},Annotations:map[string]string{kubernetes.io/created-by: {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"dev","name":"dashboard-798d748cb8","uid":"3e4e0ac4-59cb-11e8-84ce-066abd78f814","apiVersion":"extensions","resourceVersion":"37336374"}}
,},OwnerReferences:[{extensions/v1beta1 ReplicaSet dashboard-798d748cb8 3e4e0ac4-59cb-11e8-84ce-066abd78f814 0xc420f296d8 0xc420f296d9}],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[{default-token-pj9mx {nil nil nil nil nil SecretVolumeSource{SecretName:default-token-pj9mx,Items:[],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{dashboard artifacts.example.es/dashboard:1.2.2-dev [] []  [{http 0 3000 TCP }] [] [] {map[] map[cpu:{{10 -3} {<nil>} 10m DecimalSI} memory:{{64 6} {<nil>} 64M DecimalSI}]} [{default-token-pj9mx true /var/run/secrets/kubernetes.io/serviceaccount  <nil>}] Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:80,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:90,TimeoutSeconds:10,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:80,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:30,TimeoutSeconds:10,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} nil /dev/termination-log File Always nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{},ServiceAccountName:default,DeprecatedServiceAccount:default,NodeName:ip-172-20-40-224.eu-west-1.compute.internal,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,},ImagePullSecrets:[{docker-donkey-artifacts}],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[{node.alpha.kubernetes.io/notReady Exists  NoExecute 0xc420f299d0} {node.alpha.kubernetes.io/unreachable Exists  NoExecute 0xc420f29a00}],HostAliases:[],PriorityClassName:,Priority:nil,},Status:PodStatus{Phase:Pending,Conditions:[{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-05-24 11:37:15 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2018-05-24 13:17:50 +0000 UTC ContainersNotReady containers with unready status: [dashboard]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-05-24 11:37:15 +0000 UTC  }],Message:,Reason:,HostIP:172.20.40.224,PodIP:,StartTime:2018-05-24 11:37:15 +0000 UTC,ContainerStatuses:[{dashboard {ContainerStateWaiting{Reason:ContainerCreating,Message:,} nil nil} {nil nil nil} false 0 artifacts.example.es/dashboard:1.2.2-dev  }],QOSClass:Burstable,InitContainerStatuses:[],},}
```

**Comment by aleksandra-malinowska** [comment]
OK, it sounds like it may be a bug then. We shouldn't treat Job pods as replicated (I think.) cc @mwielgus - WDYT?

**Comment by bkmeneguello** [comment]
So, there is some solution for this case? I have a similar problem with pods that cannot be terminated and an autoscaling group which I want to reduce always there is node underutilization. My pods are short lived so I just need to avoid nodes with more resources available to "pack" the pods in fewer nodes an allow the autoscaling to reduce my workers count.
@Sturgelose did you found any solution? I'm thinking to create a custom scheduler to achieve this.

**Comment by antonblr** [comment]
Came here while looking for an answer to the same question. 

E.g. GitHub / GitLab CI pods - we would want them to finish. One option is to not evict / interrupt them is to use `safe-to-evict: "false"` annotation. Since the Kubernetes scheduler tends to spread pods across available nodes for better distribution and availability, it's very likely that most, if not all, of your nodes will end up running at least one CI job pod with this annotation. This effectively prevents the Cluster Autoscaler from scaling down any node that has a running job, even if the node is otherwise underutilized.

Could it be some other annotation, like `wait-for-completion` or providing CA with a label selector to tell which pods will finish eventually and it is ok to taint that node as `PreferNoSchedule` ?

**Comment by antonblr** [comment]
Ended-up with a custom scheduler that fills nodes to capacity first.
