### ISSUE TITLE
Helm - Rbac - Autoscaling nodes apiserver:nodes is foridden

### ISSUE THREAD

**Issue by ChMarco** [kubernetes/autoscaler#898]
I have an issue with autoscaler seems that is missing some authorizations ... on the master it works ...
I created even a separated namespace with a user but still the same #issue
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

logs deployment/cluster-autoscaler --namespace=test-autosc
I0527 20:37:59.475210 1 main.go:225] Cluster Autoscaler 0.6.0
F0527 20:37:59.487483 1 main.go:257] Failed to get nodes from apiserver: nodes is forbidden: User "system:serviceaccount:test-autosc:default" cannot list nodes at the cluster scope
goroutine 1 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.stacks(0xc420139600, 0xc4206d8000, 0xbb, 0x1bf)
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).output(0x39a6240, 0xc400000003, 0xc420207340, 0x390a66c, 0x7, 0x101, 0x0)
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).printf(0x39a6240, 0x3, 0x26e7790, 0x26, 0xc4206b7e88, 0x1, 0x1)
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.Fatalf(0x26e7790, 0x26, 0xc4206b7e88, 0x1, 0x1)
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:257 +0x48f

**Comment by MaciekPytel** [comment]
You're running an old and no-longer supported version of Cluster Autoscaler. CA 0.6 was meant to work with Kubernetes 1.7 and has not been updated for newer Kubernetes. For 1.9 cluster you should be using Cluster Autoscaler 1.1.X.

Helm chart you're using is not maintained by Cluster Autoscaler maintainers. You should contact the maintainer of the chart to update it. Alternatively you can deploy Cluster Autoscaler using the documentation in this repo (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#deployment).
