### ISSUE TITLE
AKS - Autoscaler Pod fails to find nodepool scaleset

### ISSUE THREAD

**Issue by mansoorcheema** [kubernetes/autoscaler#913]
**Kubernetes**  1.9.6
**Autoscaler**  1.1.2
**Cluster Type** AKS

node pool name extracted from label agentpool from command
 _**kubectl get nodes --show-labels**_

| NAME            |           STATUS  |   ROLES |    AGE  |     VERSION  |  LABELS |
| --------------  | ---------------- | -------- | -------- | ------------- | --------- |
| aks-nodepool1-40256392-0 |   Ready |    agent  |   7d  |      v1.9.6 |   agentpool=nodepool1 . . . |
| aks-nodepool1-40256392-1 |  Ready   |  agent    | 7d      |  v1.9.6    | agentpool=nodepool1 . . .   |

I can confirm that there isn't any scaleset of name nodepool1 visible either on portal nor via rest API but it seems that it is the nodepool used by aks as shown from kubectl get nodes command. Is nodepool same as scaleset?

**Autoscaler pod (cluster-autoscaler-5768479cdd-vxwc7) Logs** 
.
I0530 06:44:07.328200       1 cloud_provider_builder.go:128] Creating Azure Manager with default configuration.
I0530 06:44:07.328386       1 azure_manager.go:137] read configuration: 89e96a87-7615-4262-8f34-84f742ec7d40
I0530 06:44:07.328603       1 azure_manager.go:154] Created scale set client with authorizer . . .
0530 06:44:07.328767       1 azure_manager.go:162] Created scale set vm client with authorizer
.
 Failed to get scaleSet with name nodepool1: compute.VirtualMachineScaleSetsClient#Get: Failure responding to request: StatusCode=404 Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Compute/virtualMachineScaleSets/nodepool1' under resource group 'mansoorakscluster' was not found."
.
.
I would like to mention that the guideline about using autoscaler on Azure [https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md](url) mentions Kubernetes 1.10.X but AKS does not support any thing beyond 1.9.6.

**Comment by feiskyer** [comment]
AKS doesn't run on vmss yet, [AKS deploy guide](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#aks-or-acs-deployment) should be used (instead of vmss).

**Comment by mansoorcheema** [comment]
Yes. I am following the AKS deploy guide where it mentions that 

> And fill the node groups in container command by --nodes, with the range of nodes (minimum to be set as 3 which is the default cluster size) and node pool name obtained from pre-requirements steps above, e.g.

        - --nodes=3:10:nodepool1

From this guide the AKS yaml file [cluster-autoscaler-containerservice.yaml](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/cluster-autoscaler-containerservice.yaml) accepts command arguments where  i pass _**- --nodes=3:10:nodepool1**_ where nodepool1 is obtained as mentioned in guide.

**Comment by feiskyer** [comment]
> Failed to get scaleSet with name nodepool1: compute.VirtualMachineScaleSetsClient#Get

From the logs above, you are running in vmss mode. Could you try to redeploy CA based on cluster-autoscaler-containerservice.yaml?

**Comment by cfe84** [comment]
Autoscaler 1.1.2 supports only VMSS, there's a very clear indication at top of the README that AKS is supported only from 1.2. Minimum for AKS is 1.2.x, which requires k8s 1.10. What you're seeing is CA assuming you have a VMSS and failing to find it.

▶️ This is isn't supported yet.

**Comment by Mumrau** [comment]
" Minimum for AKS is 1.2.x, which requires k8s 1.10." said @cfe84 
But AKS latest version is 1.9.6, how is that possible that somehow someone managed to test it?

**Comment by feiskyer** [comment]
@Mumrau Yep, v1.10.x will be supported soon on AKS

**Comment by Mumrau** [comment]
Roger that. I'll still experiment with the v1.2.2 on my k8s 1.9.6 for
science purposes.
Thanks.

**Comment by feiskyer** [comment]
AKS already supports v1.10.x and CA v1.2.x could be used now. Let's close this issue.

/close

**Comment by feiskyer** [comment]
/reopen

@Mumrau What errors are reported in CA logs?

**Comment by feiskyer** [comment]
@Mumrau  Great, thanks.

/close
