### ISSUE TITLE
[cluster-autoscaler]: parameter documentation

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes/autoscaler#918]
I can't find any documentation of all parameters - forcing me to download binary and running --help. It would be awesome to have a complete list of all parameters and their use.

**Comment by bskiba** [comment]
I know it's far from ideal, but all the flags available should be present in the main.go file: 
https://github.com/kubernetes/autoscaler/blob/947ddd8c0309e22cff8e909799ee43ed08bd0027/cluster-autoscaler/main.go#L73

**Comment by WebSpider** [comment]
I'll work on some docs for this, while I get to know the dev-side of go, k8s and CA.
/remove-lifecycle stale
