### ISSUE TITLE
autoscaller donot work after changing min and max limits

### ISSUE THREAD

**Issue by mohmagdy** [kubernetes/autoscaler#943]
i have cluster autoscaler installed , initially my max cluster size was 2 and then i removed the autoscaler and reinstall it with higher cluster size of 10 , however the autoscaling donot work and i am getting below error in autoscaler pod logs

`static_autoscaler.go:245] Failed to scale up: failed to increase node group size: ValidationError: New SetDesiredCapacity value 3 is above max value 2 for the AutoScalingGroup.`

`kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`

and autosacler yaml file
` ` ` 
  serviceAccountName: cluster-autoscaler
      containers:
        - name: cluster-autoscaler
          image: gcr.io/google_containers/cluster-autoscaler:v0.6.0
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8085
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --cloud-provider=aws
            - --nodes=4:10:nodes.MYDOMAIN
          env:
            - name: AWS_REGION
              value: us-east-1
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
` ` `

**Comment by r-divakaran** [comment]
Hey @mohmagdy how did you create the kubernetes cluster, using KOPS !? 
If yes, verify if the min and max size of nodes set via KOPS matches to what is configured in autoscaler.

**Comment by aleksandra-malinowska** [comment]
On AWS, ASG limits must match (or exceed) those set for CA. Also see #647 for more information about this setup.
