### ISSUE TITLE
Migrate leader election to use Lease objects

### ISSUE THREAD

**Issue by kgolab** [kubernetes/autoscaler#944]
As commented [by @liggitt](https://github.com/kubernetes/kubernetes/pull/64503#discussion_r194060708) and [@wojtek-t](https://github.com/kubernetes/kubernetes/pull/64503#discussion_r194326600) in [PR 64503](https://github.com/kubernetes/kubernetes/pull/64503) we should at some point migrate leader election to use newer API, preferably Lease objects.

The new API is expected in Kubernetes 1.12.

**Comment by krmayankk** [comment]
/remove-lifecycle rotten

Doesnt look like auto scaler is using the new Lease api as per this https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/main.go#L410 Seems like a very simple change to implement
