### ISSUE TITLE
ACS-engine private cluster with jumpbox enabled prevents autoscaler deployment

### ISSUE THREAD

**Issue by bnookala** [kubernetes/autoscaler#958]
I've got a cluster deployed with acs-engine v.18.1. I tried adding the cluster autoscaler 1.2.2 for acs-engine to the project, and got as far as deploying, but found this error from the logs:

```
I0613 03:50:51.308133       1 azure_client.go:305] azure: using client_id+client_secret to retrieve access token
E0613 03:50:54.308498       1 azure_util.go:251] Found 2 resources with type Microsoft.Network/networkSecurityGroups in the template. There should only be 1
F0613 03:50:54.308519       1 cloud_provider_builder.go:162] Failed to create Azure Manager: failed to parse node group spec: Found 2 resources with type Microsoft.Network/networkSecurityGroups in the template. There should only be 1
```

From the azure arm template, there are indeed two network security groups - one for the cluster, and the other for the jumpbox we provisioned with the cluster. 

Removing the jumpbox profile from the cluster manifest resolves this issue: https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#jumpboxprofile, but removes the ability for a cluster to remain "private".

**Comment by feiskyer** [comment]
@bnookala This should be a bug within azure utils. Let me check what's wrong and how to fix that.

/assign
