### ISSUE TITLE
GKE cluster-autoscaler stuck in "Initializing" state in Regional cluster

### ISSUE THREAD

**Issue by rdsubhas** [kubernetes/autoscaler#986]
- `cluster-autoscaler` is found to be stuck in `Initializing` state in a GKE Regional cluster
- Nodes are not scaling up and stuck in Pending state

### Cluster info

```
Kubernetes master version: 1.10.2-gke.3
Node pool version: 1.10.2-gke.3
Node image: cos
Node zones:
europe-west1-d
europe-west1-c
europe-west1-b
```

### GKE-Autoscaler status

```
kubectl describe configmap cluster-autoscaler-status -n kube-system
Data
====
status:
----
Cluster-autoscaler status at 2018-06-19 09:17:36.680001758 +0000 UTC:
Initializing
Events:  <none>
```

### Other notes

- We run around 10 GKE clusters. Only this one is a Regional cluster. All others are regular/zonal, and do not have this issue
- We will try to upgrade to 1.10.4 to see if it initializes
- We will try to turn off autoscaling, turn on again, and see if it initializes
- Will keep the thread updated

**Comment by aleksandra-malinowska** [comment]
Hi @rdsubhas, can you reach to GCP support, providing information necessary to identify the affected cluster?

**Comment by rdsubhas** [comment]
Hi @aleksandra-malinowska thanks for your fast response, and btw:

- We added a new node pool with autoscaling enabled
- We removed the node pools that had autoscaling enabled

And the cluster-autoscaler re-initialized, we are able to see the configmap status now. Thanks, we'll close this and if we notice it again, we'll reach out to GCP support as suggested 👍

**Comment by rdsubhas** [comment]
Tagging #972 as that was the first thing we were trying to look for, and got us to probably try raising an issue here 😄 Cheers...

**Comment by jasperkuperus** [comment]
> Hi @aleksandra-malinowska thanks for your fast response, and btw:
> 
> * We added a new node pool with autoscaling enabled
> * We removed the node pools that had autoscaling enabled
> 
> And the cluster-autoscaler re-initialized, we are able to see the configmap status now. Thanks, we'll close this and if we notice it again, we'll reach out to GCP support as suggested 👍

This saved me. Particularly the removal of the old autoscaled node pool. I did already try to just add a new autoscaling node pool, without luck. But removing the old one did the trick. Magically, autoscaler re-initialises itself and everything's up and running again.

The trigger for me was an update of k8s, both the control plane and the node pools. After the upgrade, autoscaling stopped working.
